### ISSUE TITLE
Add Support For Primary Phone Field

### ISSUE THREAD

**Issue by OptikSage** [nextcloud/contacts#1011]
**Is your feature request related to a problem? Please describe.**
When adding a new contact on iOS by selecting an existing number (recents) and choosing New Contact the contact's phone number is created with the Primary field (as discovered using Outlook/CalDav Syncronizer). However, this field is not shown or available when using the Nextcloud Web Client.

**Describe the solution you'd like**
A the Primary Phone field as an option in the Nextcloud Web Client

**Comment by skjnldsv** [comment]
Duplicate of #202
