### ISSUE TITLE
Downloaded .vcf Contact Files are Indecipherably Named

### ISSUE THREAD

**Issue by unamundan** [nextcloud/contacts#1019]
### Reproducible steps

- Via browser interface, select / open a contact record
- Click on the “...” (ellipsis) icon and select “Download”
- The downloaded .vcf file is an unfriendly _machine_ name.

### What You Expect

   Download Bob Smith’s contact card and get a file named:

```
    Bob Smith.vcf
```

### What You Get

  Download Bob Smith’s contact card and get a file named:

```
    51B81412-25E6-4C59-BBBB-B41D18E7FEA7.vcf
```

**Comment by jancborchardt** [comment]
This seems to be an issue still or again, with current master. → Reopening

**Comment by skjnldsv** [comment]
@jancborchardt please give more info, are we talking about groups download? Contact download?

**Comment by skjnldsv** [comment]
Ah, so surprisingly, it works on my dev instance, not on my prod instance.

**Comment by skjnldsv** [comment]
according ttps://caniuse.com/#feat=download it will be refused if the file is not on the same site origin. Maybe there is a conflict here?

**Comment by skjnldsv** [comment]
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen.
