### ISSUE TITLE
ITEM2.xxx properties - the url label is not correctly set

### ISSUE THREAD

**Issue by j-ed** [nextcloud/contacts#1026]
### The field label of the following URL is not correctly set:
```
ITEM2.URL;TYPE=PREF,WORK;VALUE=URI:http://a-valid-url.de
```
### Expected result:
The type `WORK` should be recognized correctly and the corresponding label **`Arbeit`** (German language) should be displayed.
### Current result:
![20190329_nc-kontakte_wrong_url_label](https://user-images.githubusercontent.com/2572764/55238986-09583c80-5236-11e9-82b1-0d4bcbaff101.png)

**Comment by skjnldsv** [comment]
How did you set this data?
Did you manually created the entry or did you use a software? :)

**Comment by j-ed** [comment]
No, I'm not trying to keep you busy 😉 I found that entry in my address book as I grepped for "**ITEM**". Based on the given PRODID of this vcard the record is seems to be really old: `PRODID:-//ownCloud//NONSGML Contacts 0.3//EN`.

**Comment by skjnldsv** [comment]
That is strange indeed.
though I don't really want to auto remove the data. This does not feel like a safe way to clean data that should not be there.
I'll leave this open to see if something come into my mind :)

**Comment by ChristophWurst** [comment]
is this still a problem?

**Comment by j-ed** [comment]
@ChristophWurst I've just checked my address book entries as before and still found ITEM properties which aren't correctly been displayed in the GUI. I must admit that I'm not synchronizing contacts with an iPhone anymore and therefore most of the records are looking fine now 😉 
One record e.g. contained the following lines and was displayed in the GUI as "WORK,FAX":
```
TEL;TYPE="WORK,FAX";VALUE=UNKNOWN:+49 2222 33445566
ITEM2.X-ABLABEL:WORK\,FAX
```
After I've manually corrected the entry using the GUI so that "Arbeit" is shown in front of the fax number, the record has been modified as follows:
```
TEL;TYPE="WORK","FAX";VALUE=UNKNOWN:+49 2222 33445566
ITEM2.X-ABLABEL:WORK\,FAX
```
As you can the the TYPE syntax has been changed but the abandoned ITEM2 property still exists.

**Comment by j-ed** [comment]
The issue hasn't been fixed yet.
