### ISSUE TITLE
ITEM2.xxx properties - the url label is not set at all

### ISSUE THREAD

**Issue by j-ed** [nextcloud/contacts#1027]
### The field label of the following URL is not set at all
```
ITEM2.URL;TYPE=pref;VALUE=URI:http://a-valid-url.de
```
### Expected result:
If the type field only contains `pref` the corresponding label should be set to the default value **`Internetseite`** (German language).
### Current result:
![20190329_nc-kontakte_empty_url_label](https://user-images.githubusercontent.com/2572764/55239755-a1a2f100-5237-11e9-8ba0-df9b55b6e085.png)

**Comment by skjnldsv** [comment]
Hum, I'm not sure vcards support a default value here.
Type is empty there (pref is irrelevant in that case). 

Though it should have at least an info stating none are set, not just an empty space :)

**Comment by j-ed** [comment]
I don't know how an entry is exactly parsed but I would assume that SabreDAV allows to set default values for empty fields - but you are the specialist here 😉

**Comment by skjnldsv** [comment]
Ah, ok. I get it, this is simple, the URL does not allow custom labels/type! :)
Closing this one then :wink:

**Comment by j-ed** [comment]
Oh yes, you're right. But shouldn't the default label should be displayed in this case? The following entry e.g. is correctly displayed in another vcard record:
```
URL;VALUE=URI:http://www.domain.com/
```

**Comment by skjnldsv** [comment]
@j-ed you're right! i'll push a fix :)
