### ISSUE TITLE
ITEM2.xxx properties - the phone number label is not correctly set

### ISSUE THREAD

**Issue by j-ed** [nextcloud/contacts#1028]
### The field label of the following phone number is not correctly set:
**Example 1:**
```
4L06RU.TEL;TYPE="WORK,VOICE":+49 1234 556677
4L06RU.X-ABLABEL:VOICE
```
**Example 2:**
```
9JN9AI.TEL;TYPE=pref:+49 1234 556677
9JN9AI.X-ABLABEL:WORK\;VOICE\;PREF
```
**Example 3:**
```
FACL6F.TEL;TYPE=CELL,PREF:+49 1234 556677
FACL6F.X-ABLABEL:PREF\;CELL
```
### Expected result:
The type `WORK` or `CELL` should be recognized correctly and the corresponding label `Arbeit` or `Mobil` (German language) should be displayed.
### Current result:
**Example 1:**
![20190329_nc-kontakte_wrong_phone_label-1](https://user-images.githubusercontent.com/2572764/55240417-25111200-5239-11e9-98bf-2d821aa58b0d.png)
**Example 2:**
![20190329_nc-kontakte_wrong_phone_label-2](https://user-images.githubusercontent.com/2572764/55240439-2e9a7a00-5239-11e9-8ae4-94e37e7b6ae3.png)
**Example 3:**
![20190329_nc-kontakte_wrong_phone_label-3](https://user-images.githubusercontent.com/2572764/55240454-365a1e80-5239-11e9-9a2f-5fa2c718dee2.png)

**Comment by skjnldsv** [comment]
> ```
> 4L06RU.X-ABLABEL:VOICE
> ```
> ```
> 9JN9AI.X-ABLABEL:WORK\;VOICE\;PREF
> ```
> ```
> FACL6F.X-ABLABEL:PREF\;CELL
> ```

All of those are not valid.
X-ABLABEL is a text entry and supports text only. That is why the semi-colon are escaped with `\;`

How did you get those data? Is this coming from the nextcloud app?
How did those fields get created?

**Comment by j-ed** [comment]
Unfortunately I cannot tell you how these entries have originally been created but I have in mind that the Calendar app had some trouble with incorrectly formatted entries in vcards in the past. Especially the escaped separator was an issue.
Based on the PRODID the records were synced from my Android phone some time ago:
```
PRODID:-//NTBAB//Android//ContactSync//9.0//164
REV:20171008T115403Z

PRODID:-//NTBAB//Android//ContactSync//9.0//164

PRODID:-//NTBAB//Android//ContactSync//9.0//166
```

**Comment by skjnldsv** [comment]
@j-ed so unfortunately, I cannot really find any thing to do here. I guess we cannot really determine if the ABLABEL have been misused as a type or not :(
