### ISSUE TITLE
ITEM2.xxx properties - custom date not displayed

### ISSUE THREAD

**Issue by j-ed** [nextcloud/contacts#1029]
### custom dates should be displayed:
**Example 1:**
```
36BU01.X-ABLABEL:Hochzeitstag
36BU01.X-ABDATE;TYPE=pref:1990-01-04
```
**Example 2:**
```
LGVLP0.X-ABDATE:1991-07-12
LGVLP0.X-ABLABEL:_$!&lt\;Anniversary&gt\;!$_
```
### Expected result:
Custom dates should be displayed in the Contacts app.
### Current result:
Non of the provides dates are currently shown.

**Comment by skjnldsv** [comment]
ABDATE is another topic: #223 :wink:
