### ISSUE TITLE
Last group not displayed

### ISSUE THREAD

**Issue by AS-dh** [nextcloud/contacts#103]
Contacts Version 1.5.2 as contained in nextcloud 11.0.1

Context The observed behavior is with contacts obtained by using CalDav Synchronizer but that origin doesn't matter (and yes, I did read the preamble: This is very likely not related to the sync process)

### Steps to reproduce
1. Group contacts in a significant number (I have 21 groups resulting from Outlook categories)
2. The last group does not display on the left-most column (I have for example "Wiss" as last group)
3. Add a dummy group alphabetically sorted last (I introduced a "Z" group): Now "Wiss" is displayed but not "Z")

### Expected behaviour
All available groups should be displayed

### Actual behaviour
The alphabetically last sorted group does not show up (although all contacts are available and can be reached by the explicit link (in the example above https://nextcloud.myplace.com/index.php/apps/contacts/#/Wiss

### Server configuration
**Operating system**: Web hoster all-inkl (I assume Ubuntu)

**Web server:** Apache

**Database:** Mysql  5.6.33

**PHP version:** 7.0 (CGI)

**Nextcloud version:** (see Nextcloud admin page) 11.0.1

**Contacts version:** (see Nextcloud apps page) 1.5.2

**Updated from an older Nextcloud or fresh install:** updated from 10 -> 11.0.0 -> 11.0.1

**Signing status:** ?

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.

->No errors have been found.

**List of activated apps:**
activity gallery contacts calendar bookmarks
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** no

**Are you using encryption:**/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Client configuration
**Browser:**

**Operating system:**

**CardDAV-clients:**

### Logs
#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by skjnldsv** [comment]
When you said not displayed, you mean because of the windows height, Or because there is a bug?
Does the group appear on the contacts that have it?

**Comment by AS-dh** [comment]
The group does not display because of a bug, regardless of the height (I'm including a screenshot of the lower left corner: In my example the "Wiss" group is now displayed but only because I introduced a dummy "Z" group which is not displayed.  And Yes the contacts do have the "Wiss" group when looked at individually.
![Uploading nextcloud-contacts-group-bug.png…]()

**Comment by skjnldsv** [comment]
@AS-dh your image is broken :)

**Comment by AS-dh** [comment]
Sorry, I don't seem to be able to upload neither a png nor a jpg file.  But it isn't really relevant. I looks basically as follows:

Group n-2
Group n-1
Settings

So group n is not shown

**Comment by skjnldsv** [comment]
It's because you save your message before the upload is done.
I could use a screenshot to be fair, much easier to understand.

So the group is present in the code (use the dev tools)?

**Comment by skjnldsv** [comment]
Okay, I get it. Will fix asap.

**Comment by skjnldsv** [comment]
@AS-dh Are you using core@master?

**Comment by AS-dh** [comment]
Sorry, I'm new to github, so I'm not sure I understand your question:  I installed nextcloud 11.0.1 on a web hoster using the download at nextcloud.com and use the contacts add-on out-of-the-box. I did not clone the repository, if that is what you mean by "are you using core@master".

**Comment by skjnldsv** [comment]
I was wondering if you were using nextcloud 12 from github master :)
But you answered my question.

This is strange indeed.

**Comment by AS-dh** [comment]
Fix works perfectly. Thanks!
