### ISSUE TITLE
An email address label is not set if the address type is given twice

### ISSUE THREAD

**Issue by j-ed** [nextcloud/contacts#1030]
## Expected behavior
The Contacts app should show the correct email address label if the address type is given twice.

## Current behavior
The contacts app shows an empty email address label.

**Example:**
```
EMAIL;TYPE=WORK,WORK,pref:address@nowhere.com
```
** Result:**
![20190329_nc-kontakte_empty_email_label](https://user-images.githubusercontent.com/2572764/55241538-95b92e00-523b-11e9-90b7-e9d5aebd864e.png)

#### Server Configuration
OS: Linux 3.16.63
Web server: Apache2 2.4.37
Database: MariaDB 10.2.22
PHP version: 7.2.14
Nextcloud version: 15.0.5
Contacts app version: 3.0.5

#### Client Configuration
Browser: Mozilla Firefox 66.0.2
Operating system: Windows 10

**Comment by skjnldsv** [comment]
> ```
> EMAIL;TYPE=WORK,WORK,pref:address@nowhere.com
> ```

I'm not sure I get it. You mean because there is two WORK types?
We should indeed have a repair step for this, as this is not valid :thinking:

**Comment by j-ed** [comment]
That's my assumption, because several other entries are correctly displayed. Unfortunately I found several different ways how email address entry types have been formatted in my address book. All others seem to be correctly displayed. Here is the list:
```
EMAIL
EMAIL;TYPE="home,pref"
EMAIL;TYPE="work,pref"
EMAIL;TYPE=HOME
EMAIL;TYPE=HOME,PREF
EMAIL;TYPE=WORK
EMAIL;TYPE=WORK,PREF
EMAIL;TYPE=WORK,WORK,pref
EMAIL;TYPE=home
EMAIL;TYPE=home,pref
EMAIL;TYPE=work
EMAIL;TYPE=work,pref
EMAIL;TYPE=work;PREF=1
```

**Comment by skjnldsv** [comment]
Fix in https://github.com/nextcloud/contacts/pull/1042
