### ISSUE TITLE
Pls. consider making emoji support more consistent 🤔

### ISSUE THREAD

**Issue by giddyhup** [nextcloud/contacts#1047]
**Is your feature request related to a problem? Please describe.**
Like it or not, emoji use becomes more widespread. I am not particular fond of them in address books but I know users who pepper their contact fields with them.   

I tested it and it seems emoji support is limited. I added an emoji to a contact's name in iOS and in a Windows client (Em Client): it did not appear in the database. An emoji entered in a name via the web interface was synced to Em Client's display name field and to the contact name in iOS. Modifications on both clients did not end up in the database.

**Describe the solution you'd like**
Emoji support would help to convince people to move away from local contact storage.

**Describe alternatives you've considered**
: )  (Old style emojis.)

**Additional context**
Using emojis has been debated in [another issue](https://github.com/nextcloud/contacts/issues/735). 
If it should work and the fault lies with the respective clients then please close this request. Thanks.

**Comment by skjnldsv** [comment]
Hey @giddyhup !
Thanks for reporting :)
What do you mean by 'in the database'?

I have some contacts with emoji in the displayName or other fields and it's being displayed find on the contacts app :thinking: 
![Capture d’écran_2019-04-08_18-52-40](https://user-images.githubusercontent.com/14975046/55742359-c5ccb200-5a2f-11e9-8083-715e41c7276c.png)

Do you have some emoji font installed on your machine?

**Comment by giddyhup** [comment]
Hi @skjnldsv !

Thanks for your reply. Please add an emoji to the first name of a contact in your (iOS?) contacts app and see if it gets synced to the database.  

I just modified locally a contact where I had added an emoji through Nextcloud's contacts app and that worked. Originally, the emoji only showed up in the "display as" field but now it is in both, weird. I think there is something going on between clients' different handling and inheriting from/to the "display as field".

**Comment by skjnldsv** [comment]
@giddyhup so, what is the status here?

**Comment by giddyhup** [comment]
It seems to work when I add an emoji to a contact via the Nexcloud contacts UI. Currently, iPhone contacts do not sync from my iOS devices (iOS 12.3, various; iPadOS 13 PB 4). It doesn't matter if the change to an existing contact is just characters or emojis.

**Comment by skjnldsv** [comment]
So I think this then have to do with iOS as it properly sync for me between nextcloud instances and between nextcloud and android :/

Let's close then!
