### ISSUE TITLE
Support Timezone and Language

### ISSUE THREAD

**Issue by olantrust** [nextcloud/contacts#1048]
Currently, the following two properties, specified by both vCard 3 and vCard 4 are not exposed:

**Language** 'LANG' property
Which sets the language(s) used by the contact.

**Timezone** 'TZ' property
Which sets the usual timezone of a contact.

This is particularly useful for the many Users who have international friends or colleagues to ensure contact is timely.

**Comment by georgehrke** [comment]
RFC for ref: https://tools.ietf.org/html/rfc6350#section-6.4.4
