### ISSUE TITLE
[3.1.0] contact photos not shown in contact list anymore

### ISSUE THREAD

**Issue by j-ed** [nextcloud/contacts#1051]
## Expected behavior
The contacts app should display a contact photo in the contacts list, instead of a letter, if one is available.

## Current behavior
Since I've updated the contacts app to v3.1.0 contact photo are only shown in the contact details but not in the contact list anymore.

![20190409_NC-Kontakte-Bild](https://user-images.githubusercontent.com/2572764/55797536-ff072f80-5acc-11e9-9b2d-84e54b563980.png)

### Steps to reproduce
1. Open the Contacts app.
2. Select a contact in he contacts list which contains a photo.
3. Check if this image is shown in the list once it has been selected.

#### Server Configuration
OS: Linux 3.6.63
Web server: Apache2 2.4.37
Database: MariaDB 10.2.22
PHP version: 7.2.14
Nextcloud version: 15.0.7
Contacts app version: 3.1.0

#### Client Configuration
Browser: Mozilla Firefox 66.0.2
Operating system: Windows 10

**Comment by skjnldsv** [comment]
Fixed in https://github.com/nextcloud/contacts/commit/6a9025c57dfd738d3d25651853bc38e15db90f1c

**Comment by j-ed** [comment]
@skjnldsv Wow, faster than light 👍

**Comment by skjnldsv** [comment]
@j-ed I actually noticed this only after releasing... :man_facepalming:
