### ISSUE TITLE
Allow assignment of images already in Nextcloud as contact photos

### ISSUE THREAD

**Issue by mossholderm** [nextcloud/contacts#106]
- [ ] If the image is already in Nextcloud, should we really need to upload it again?
- [ ] Provide an editor to cut and resize images like we don on the user settings

**Comment by jancborchardt** [comment]
@icewind1991 @nickvergessen @MorrisJobke who implemented the »Choose from Files« function for the user avatar on the personal settings page? We could reuse that here. :)

**Comment by MorrisJobke** [comment]
> @icewind1991 @nickvergessen @MorrisJobke who implemented the »Choose from Files« function for the user avatar on the personal settings page? We could reuse that here. :)

I think @icewind1991 added this. The Choose from Files is `OC.dialogs.filepicker()` and those parameters: https://github.com/nextcloud/server/blob/a2f6fea4081e7920ed6cd33a96e2b80dc0c51303/core/js/oc-dialogs.js#L170-L178

**Comment by jancborchardt** [comment]
@MorrisJobke thanks for the pointer! :) I’m setting this as starter issue then, would you agree?

**Comment by skjnldsv** [comment]
I edited OP to merge two issues into one, see #33
