### ISSUE TITLE
Empty screen with Edge

### ISSUE THREAD

**Issue by dominikleuthold** [nextcloud/contacts#1063]
### Describe the bug
Since the Installation of Contacts 3.1.0, the contacts screen remains blank with the browser Edge. With Chrome everythings works fine.

**To Reproduce**
1. Click on the Contacts button in the main screen

**Expected behavior**
The contacts list and detail pane should be shown.

**Actual behavior**
The screen remains blank.

**Screenshots**
See attached

**Operating system**: 
Linux Ubuntu 18.04.2 LTS
Using newest Nextcloud Docker Image: nextcloud:apache

**Web server:** Apache with Nginx proxy

**Database:** MariaDB

**PHP version:** ?

**Nextcloud version:** 15.0.7

**Contacts version:** 3.1.0

**Updated from an older Nextcloud or fresh install:**
Updated docker Image from 15.0.5 to 15.0.7

**Signing status:**

Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
Result: No errors have been found.

### Client configuration
**Browser:** 
Microsoft Edge 44.17763.1.0

**Operating system:** Windows 10 Pro 1809

**CardDAV-clients:**
DAVx5 on Android

#### *Web server error log*
Nothing related found in the logs

#### *data/nextcloud.log*
Nothing related found in the logs

#### Browser log
See attached HAR file.
[contacts.zip](https://github.com/nextcloud/contacts/files/3082264/contacts.zip)
![contacts](https://user-images.githubusercontent.com/26244621/56169395-3c445380-5fde-11e9-9239-cf96240efea1.PNG)

**Comment by dominikleuthold** [comment]
Wow, that was quick. 👍

**Comment by skjnldsv** [comment]
@dominikleuthold I wanted to do a release soon anyway :)

**Comment by dominikleuthold** [comment]
just installed 3.1.1 and can confirm that it works perfectly. :-)
