### ISSUE TITLE
"Addressbook" section in contact details not necessary if there is only one address book

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/contacts#1065]
The concept of an "address book" that contacts are stored in is quite technical. The default is only having one address book, and in that case the section in the contact details is greyed out anyway:
![Addressbook](https://user-images.githubusercontent.com/925062/56385063-57050b00-621e-11e9-831a-00c7f6440835.png)

Since it is not relevant in this case, we don’t need to show it at all. cc @nextcloud/contacts

**Comment by skjnldsv** [comment]
I guess yes X) :+1:
