### ISSUE TITLE
Avatar placeholder shows behind partly transparent avatar

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/contacts#1066]
If you upload a partially transparent image as an avatar, it will display like that with the placeholder behind it:
![placeholder](https://user-images.githubusercontent.com/925062/56389779-ba953580-622a-11e9-9f1f-e4677424f743.png)

Probably better is to just leave the background transparent? Although that might make images invisible in dark theme, so we could also think about making the background white for that.

**Comment by skjnldsv** [comment]
Ah damn, this is a feature in case of the avatar does not load. :thinking:

**Comment by jancborchardt** [comment]
Right, makes sense.

Is it possible to only show `app-content-list-item-icon__avatar` when the image can be loaded? Cause then we can add `background-color: white;` to it, as the avatar placeholder color is on the parent element `app-content-list-item-icon` and would be overwritten then.

**Comment by skjnldsv** [comment]
> Is it possible to only show `app-content-list-item-icon__avatar` when the image can be loaded?

That requires js, and that's what I wanted to avoid :)
I'll see what I can do ;)

**Comment by gary-kim** [comment]
It may be possible to, either during the upload process or when loading the photo from the `vcf`, replace the transparency in the image with a color. That way, the image behind will still be visible if the image does not load but if it has loaded, the background image will not be visible.
This would still require js but it would be very small and will be while the card is loading rather then on load.

If that's okay, I can make a pull request with the change.

**Comment by skjnldsv** [comment]
@gary-kim we do not load the photo from the vcf. We use the photo endpoint from nextcloud server :)
~~I would try to avoid a javascript event watcher (like `onload`) or any kind of scripting because ti might be ok for 1 contacts or 50, but 500 watchers...~~
Since we implemented the virtual scroller recently, actually it might be ok to use `@error` on the image.

```onerror="this.style.display='none'"``` something similar in vuejs
