### ISSUE TITLE
contacts app: new property not saved

### ISSUE THREAD

**Issue by ThomasT02** [nextcloud/contacts#1071]
### Steps to reproduce
1. Go to an existing contact
2. add new property, here: Deathdate
3. select a date from the calender
4. go to another existing contact (expecting the changes made were saved)
5. go back to the "deathdate-contact"
6. see actual behavior (deathdate was not saved)
7. change another property e.g. given name AND add new property, here: Deathdate
8. select a date from the calender
9. go to another existing contact (for saving)
10. go back to the "deathdate-contact"
11. see expected behavior (deathdate was saved)

### Expected behaviour
expecting the deathdate still exist

### Actual behaviour
deathdate was not saved

## Server configuration detail

**Operating system:** Linux info 3.0 #1337 SMP Tue Jan 01 00:00:00 CEST 2000 all GNU/Linux Linux info 3.0 #1337 SMP Tue Jan 01 00:00:00 CEST 2000 all GNU/Linux Linux info 3.0 #1337 SMP Tue Jan 01 00:00:00 CEST 2000 all GNU/Linux Linux info 3.0 #1337 SMP Tue Jan 01 00:00:00 CEST 2000 all GNU/Linux

**Webserver:** Apache (cgi-fcgi)

**Database:** mysql 5.5.60

**PHP version:** 

7.1.27
Modules loaded: Core, date, libxml, openssl, pcre, sqlite3, zlib, bcmath, bz2, calendar, ctype, curl, dba, dom, hash, fileinfo, filter, ftp, gd, gettext, SPL, iconv, session, intl, json, mbstring, mcrypt, standard, PDO, mysqlnd, pdo_sqlite, Phar, posix, Reflection, imap, shmop, SimpleXML, soap, pdo_mysql, exif, tidy, tokenizer, wddx, xml, xmlreader, xmlwriter, xsl, zip, mysqli, cgi-fcgi

**Nextcloud version:** 15.0.7 - 15.0.7.0

**Updated from an older Nextcloud/ownCloud or fresh install:** updated from owncloud 10.0.3

**Where did you install Nextcloud from:** ?

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.1.0
 - activity: 2.8.2
 - admin_audit: 1.5.0
 - bruteforcesettings: 1.3.0
 - calendar: 1.6.5
 - cloud_federation_api: 0.1.0
 - contacts: 3.1.0
 - dav: 1.8.1
 - deck: 0.6.0
 - drawio: 0.9.2
 - encryption: 2.3.0
 - federatedfilesharing: 1.5.0
 - federation: 1.5.0
 - files: 1.10.0
 - files_external: 1.6.0
 - files_pdfviewer: 1.4.0
 - files_sharing: 1.7.0
 - files_texteditor: 2.7.0
 - files_trashbin: 1.5.0
 - files_versions: 1.8.0
 - files_videoplayer: 1.4.0
 - gallery: 18.2.0
 - issuetemplate: 0.5.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.3.0
 - metadata: 0.9.0
 - notes: 2.6.0
 - oauth2: 1.3.0
 - password_policy: 1.5.0
 - provisioning_api: 1.5.0
 - richdocuments: 3.2.4
 - serverinfo: 1.5.0
 - sharebymail: 1.5.0
 - support: 1.0.0
 - survey_client: 1.3.0
 - theming: 1.6.0
 - twofactor_backupcodes: 1.4.1
 - updatenotification: 1.5.0
 - user_saml: 2.1.1
 - workflowengine: 1.5.0
Disabled:
 - announcementcenter
 - caniupdate
 - comments
 - files_accesscontrol
 - files_antivirus
 - files_automatedtagging
 - files_retention
 - firstrunwizard
 - groupfolders
 - impersonate
 - mail
 - nextcloud_announcements
 - notifications
 - onlyoffice
 - radio
 - sharepoint
 - systemtags
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": ***REMOVED SENSITIVE VALUE***"
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "https:\/\/***REMOVED SENSITIVE VALUE***".de\/ownCloud",
    "dbtype": "mysql",
    "version": "15.0.7.0",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "debug": false,
    "filelocking.enabled": true,
    "installed": true,
    "logtimezone": "UTC",
    "loglevel": 4,
    "maintenance": false,
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "smtp",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "25",
    "mail_smtpauthtype": "LOGIN",
    "mail_smtpauth": 1,
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "mail_smtptimeout": 15,
    "theme": ""
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

## Client configuration

**Browser:** Firefox 0.0 

**Operating system:** Windows 10

## Logs

<details><summary>Web server error log</summary>

```
Insert your web server log here 
```
</details>

<details><summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

<details><summary>Browser log</summary>

Insert your browser log here, this could for example include:

	a) The javascript console log
	b) The network log
	c) ...
</details>

**Comment by ThomasT02** [comment]
Hello,
"is there anybody out there?" ;-)
I'm waiting for reactions, questions, statemants to this one month old issue. Is there anybody responsible?

**Comment by skjnldsv** [comment]
Hey! Sorry, your ticket slept through :)
I will need your browser console log to investigate this issue.
Open your console, reload your page and/or do the action leading to this issue and copy/paste the log in this thread.

<details>
<summary>How to access your browser console (Click to expand)</summary>

# Chrome
- Press either CTRL + SHIFT + J to open the “console” tab of the Developer Tools.
- Alternative method:
    1. Press either CTRL + SHIFT + I or F12 to open the Developer Tools.
    2. Click the “console” tab.

# Safari
- Press CMD + ALT + I to open the Web Inspector.
- See Chrome’s step 2. (Chrome and Safari have pretty much identical dev tools.)

# IE9
1. Press F12 to open the developer tools.
2. Click the “console” tab.

# Firefox
- Press CTRL + SHIFT + K to open the Web console (COMMAND + SHIFT + K on Macs).
- or, if Firebug is installed (recommended):
    1. Press F12 to open Firebug.
    2. Click on the “console” tab.

# Opera
1. Press CTRL + SHIFT + I to open Dragonfly.
2. Click on the “console” tab.
</details>

**Comment by ThomasT02** [comment]
I'm afraid I'm not giving you what you want... Please help me.
There are no visible changes in the console when doing the theps I described above.

JQMIGRATE: Migrate is installed, version 1.4.1 jquery-migrate.min.js:2:494
New search handler registered search.js:67:12
Content Security Policy: 'x-frame-options' wird wegen 'frame-ancestors'-Direktive ignoriert.
Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf eval blockiert ("script-src"). 0daa1eb8-7532-4cc9-989e-3035cd1424e6:27:22
Connected to dav! 
Object { rootUrl: "https://<IP>/<path>/remote.php/dav/", advertisedFeatures: (17) […], currentUserPrincipal: {…}, principalCollections: (4) […], calendarHomes: [], addressBookHomes: (1) […], parser: {…}, _isConnected: true, _request: {…} }
Contacts.vue:288
The escapeHTML library is deprecated! It will be removed in nextcloud 19.
globals.js:30:10
The escapeHTML library is deprecated! It will be removed in nextcloud 19.
globals.js:30:10

**Comment by skjnldsv** [comment]
Hey :)
No worries. Well, console looks fine. Did you opened the console before doing the steps you mentioned ?

I could also use a screenshot of your network requests.
Before you do anything, still on the development tools, there is a tab called `network`. Click on it and then the xhr filter. Do your action and screenshot the network log like this:
![capture d ecran_2018-09-27_21-49-46](https://user-images.githubusercontent.com/14975046/46170857-43548000-c29f-11e8-9403-db72713dd9c1.png)

**Comment by ThomasT02** [comment]
Hi,
I opened nextcloud, then I opened the console and then I made my input.

![2019-06-13 16_45_04-](https://user-images.githubusercontent.com/46403012/59443010-8f2e6180-8dfb-11e9-8879-27e6b79a29e2.png)

**Comment by skjnldsv** [comment]
Looks fine as well :/
No errors here. You did all the steps you mentioned before taking the screenshot?

**Comment by ThomasT02** [comment]
Yes I did.

**Comment by skjnldsv** [comment]
Damn, I really cannot repdoruce the issue.
Does it happens with every contact?

Maybe you could do a screencast of this? I might be missing something :thinking:

**Comment by ThomasT02** [comment]
Atached you find the screencast. I don't know if it happens with every contact. But I think so.

This happens in the video:
Starting with two "Deathman" with nearly empty data set.
Giving Deathman1 a deathdate
switching to Deathman2 (expecting the changes in Deathman1 will be saved)
switching back to Deathman1, see that nothing was saved
let Deathman1 die a second time AND give him a first name
switching to Deathman2 for saving
switching back to Deathman1 and see he is still dead.

[2019-06-14 13-07-28.zip](https://github.com/nextcloud/contacts/files/3290402/2019-06-14.13-07-28.zip)

**Comment by skjnldsv** [comment]
Ahh, ok!
You did not changed the value!
Therefore nothing is saved. :)

**Comment by ThomasT02** [comment]
Yes. You got it. It works as designed.
So when I add an item, e.g. the deathdate or a sex, and the proposal is OK for me, I MUST anyway confirm the value. - This is not what I expect. (I am the user).
But its not a bug. Maybe a design failure. ;-)

**Comment by skjnldsv** [comment]
No I think we should maybe save directly.
@jancborchardt what do you think?
Is it better to not save the default value as the user could have selected the wrong entry in the 'add new property' menu? Or same right away despite it not being the value the user wants?

On a side note, if the user misclicked, s.he will removed the unwanted property, so we might want to save the default value. On another hand, the default value is here because we need one, but having a birthday on the current day is maybe not what the user usually want to do :thinking:

**Comment by jancborchardt** [comment]
Yes, if we give a default value it should directly be saved as per @ThomasT02's expectation. :)


> On another hand, the default value is here because we need one, but having a birthday on the current day is maybe not what the user usually want to do

That’s case is fine? We can do nothing to assume the birthdate, so people will simply adjust it.

**Comment by skjnldsv** [comment]
Good to me! :)

**Comment by ThomasT02** [comment]
Hi, are there any further questions to start?

**Comment by skjnldsv** [comment]
Nope, just people that have enough time to start on this.
This is unfortunately not a priority right now :(

**Comment by skjnldsv** [comment]
Can't reproduce the issue anymore
