### ISSUE TITLE
Ctrl-S should trigger save of contact, not open save dialog

### ISSUE THREAD

**Issue by stefan-niedermann** [nextcloud/contacts#1073]
**Is your feature request related to a problem? Please describe.**
Pressing `Ctrl` + `S` does open the default browser safe dialog which is not useful

**Describe the solution you'd like**
Force saving the current contact on hitting `Ctrl` + `S` (or do nothing but show some kind of notification)

**Describe alternatives you've considered**

**Additional context**
Some other apps like notes do this, too. See e. g. https://github.com/nextcloud/notes/issues/120

For better cross-app experience this should be done by Contacts, too.

quote from @jancborchardt 
> The »Save website as« dialog is useless in this context. Rather we should do it like in the files_texteditor app, and make Ctrl-S simply force save the note.

cc @nextcloud/designers

**Comment by skjnldsv** [comment]
Well, we auto-save on each change already, so it doesn't really make sense.
But it would at least remove the save as and fire a save again just in case! :thinking:
