### ISSUE TITLE
Company Saved as Contact Name (webdav iOS)

### ISSUE THREAD

**Issue by sknsean** [nextcloud/contacts#1083]
### Describe the bug
When adding a company name to a contact the name is removed and the company is displayed.

**To Reproduce**
Create a new contact, add company name

**Expected behavior**
The First and Last should be kept and the company name added as a company name.

**Actual behavior**
Only the company name is synced

**Screenshots**
![nextcloudcontacts](https://user-images.githubusercontent.com/12713608/57015842-33c35e00-6c17-11e9-8485-63ade477081b.png)
![IMG_0835](https://user-images.githubusercontent.com/12713608/57015846-37ef7b80-6c17-11e9-8036-19f2c03d6463.PNG)

**Comment by sknsean** [comment]
possibly related to #986 #165 #848

**Comment by sknsean** [comment]
BEGIN:VCARD
VERSION:3.0
PRODID:-//Sabre//Sabre VObject 4.1.6//EN
UID:701932cf-5f16-4114-8894-ca9701b3838f
REV;VALUE=DATE-AND-OR-TIME:20190501T113643Z
FN:Jens Jensen
ADR;TYPE=HOME:;;;;;;
EMAIL;TYPE=HOME:jens@jensenc.dk
TEL;TYPE="HOME,VOICE":+4580808080
ORG:Consultantcompany
END:VCARD

**Comment by skjnldsv** [comment]
Hello :)
If I understand correctly, you expect to have `Jens Jensen` displayed on your iOS device?

**Comment by sknsean** [comment]
Yes exactly :-)
There is also an extra " before the "HOME" number.
![IMG_0836](https://user-images.githubusercontent.com/12713608/57020783-ba356b00-6c2a-11e9-9404-29ca83d6ea3e.PNG)
As seen here the First and Last name is empty

**Comment by skjnldsv** [comment]
This is an iOS issue then. If you look at your contact vcard, you'll see that the FN property is still set with the proper data. iOS have just decided to display the ORG instead.

First name and Last name are empty because you never set it on nextcloud. You need ot add a `detailed name` property (`N`) on nextcloud. But I still don't know if iOS will prefer displaying the ORG or the N property then. Please try and report back :)

For the `"` in front of home, this is also an iOS issue unfortunately. This is correct, a [vcard can have](https://tools.ietf.org/html/rfc6350#page-35) a `TYPE="home,voice"` data set, but iOS is somehow not properly displaying it :thinking: 
Can you try

**Comment by sknsean** [comment]
Vcf when Contact is created from iOS
BEGIN:VCARD
VERSION:3.0
PRODID:-//Apple Inc.//iOS 12.2//EN
N:Nielsen;Niels;;;
FN:Niels Nielsen
ORG:FishingCompany;
EMAIL;type=INTERNET;type=HOME;type=pref:niels@fish.eu
TEL;type=HOME;type=VOICE;type=pref:44 74 74 74
REV:2019-05-01T14:08:13Z
UID:BE3309BE-0E6B-4F17-BD4B-F1E2DBBDA6F1
END:VCARD

Hehe, it’s not easy to fix things in iOS ;-).
Will try to set first and last name, later and report back

**Comment by skjnldsv** [comment]
> Vcf when Contact is created from iOS

and it's properly displayed in iOS?
If so then it's fine, but you should know that you will need to use the `detailed name` property and not only the `display name` one :)

**Comment by sknsean** [comment]
Yes it's properly displayed.
It's also properly displayed when setting first and last name.
Would it be difficult to change (aka. more difficult than to convince Apple to comply with the standard):
TEL;TYPE="HOME,VOICE": to TEL;type=HOME;type=VOICE:

**Comment by skjnldsv** [comment]
Issue is that if we do so, we might also lose compatibility with other softwares/platforms :)
Also I think the library we use for that is bugged and does not support it properly.
https://github.com/mozilla-comm/ical.js/issues/343

**Comment by a1pilot** [comment]
#1107 for the VCF format.

I've brought up the company name issue before. Didn't end well.

**Comment by a1pilot** [comment]
Not stale. No missing information. Fix needed.

**Comment by skjnldsv** [comment]
Sorry, forgot to remove the needs info label :)
Though closing since for multiple types we have this: https://github.com/nextcloud/contacts/issues/942
And for the various vcf formats #1107
