### ISSUE TITLE
Show me what contacts cannot be imported

### ISSUE THREAD

**Issue by jkischel** [nextcloud/contacts#1090]
**Is your feature request related to a problem? Please describe.**
I made an import and got a message like "15 of your 260 contacts cannot be imported. more infos, see your browser console."

**Describe the solution you'd like**
Well, contacts should tell me what contacts _exactly_ cannot be imported. You surely agree that this is not a good user experience to manually have to figure out what went wrong.

**Comment by skjnldsv** [comment]
Duplicate of #990
