### ISSUE TITLE
Scrolling in the contacts list is difficult in 3.1.1

### ISSUE THREAD

**Issue by RobertZenz** [nextcloud/contacts#1091]
Scrolling in the list in 3.1.1 will lazily rearrange the items, leaving you with something between 1 and 3 seconds of overlapping contacts which then jump into their "slots" or off the screen.

 1. Have enough contacts for a "largish" list, 60 should do fine.
 2. Grab the scrollbar and yank it from one position to another.

I would provide you with a screenshot, but I'm not very keen to post my contacts list here. I'm seeing this with the latest Firefox.

**Comment by skjnldsv** [comment]
Hello! :)
Could you send the screenshot or the screencast to my mail then?
skjnldsv@protonmail.com? I'm [the maintainer of the app](https://github.com/nextcloud/contacts/commit/4d25967eddd33d5e3b42379858222a4aaa9da8de), so I'll keep your sensitive info safe :wink: 

We indeed introduce a speed improvement in the contacts list on 3.1.x, but I did not noticed anything wrong while using the contacts app (quite the opposite).
What are your system specs? Is it a powerful machine? Server too?

Thanks for your report! :v:

**Comment by RobertZenz** [comment]
Right, I always forget that my server is introducing a slight latency (see #923).

I'll send you a screenshot.

**Comment by skjnldsv** [comment]
Also, please take the time to think about the title of your issues next time.
Not the kind of titles that give me the most motivation to work on :wink: :pray:

**Comment by skjnldsv** [comment]
@RobertZenz any news?

**Comment by RobertZenz** [comment]
@skjnldsv What did you mean, I did send you the screenshot as requested shortly after you've posted it. Did you not receive it?

**Comment by skjnldsv** [comment]
@RobertZenz it was in spam! Sorry :)

**Comment by skjnldsv** [comment]
@RobertZenz wow, that is messed up!
What browser are you using? Have you also cleared your cache?

**Comment by RobertZenz** [comment]
As said, the latest Firefox does show this behavior with the debug console open and the cache being disabled.

**Comment by skjnldsv** [comment]
I can also reproduce the issue now! 😉

Thanks for the help!

**Comment by RobertZenz** [comment]
Different question but related, is there a chance that you can scrap that hard-coded JavaScript positioning? I'm using a few CSS changes in the theme (through the Custom CSS app) to increase information density on my screen. So previously I simply reduced the height of the items to fit more items into the list view. With the latest version that isn't working anymore because there seems to be some JavaScript logic which is rearranging the items and is using a hardcoded size. So on my full HD screen I can only see 13 contacts in the list at any time, with the previous version and my CSS changes it was nearly 23 contacts. Do you get what I mean?

**Comment by skjnldsv** [comment]
@RobertZenz Not sure.
You manually increased the height of the list entries?

**Comment by RobertZenz** [comment]
No, I decreased it. Consider the following view as it is right now:

![Default view](https://user-images.githubusercontent.com/611377/57950692-4a8cd480-78e8-11e9-9de5-c190f482d689.png)

Now I used custom CSS to decrease the height of every item in the list to see more of my contacts at once:

![Reduced height](https://user-images.githubusercontent.com/611377/57950733-61cbc200-78e8-11e9-827d-3ddebdb0e127.png)

I'm even considering making the avatar smaller so that I can fit even more contacts simultaneously on my screen. The more contacts I see at once, the less scrolling I'll have to do.

Now with the latest version I can't do that anymore, because the layout logic is assuming a fixed height of each item which I can't influence anymore using CSS.

**Comment by skjnldsv** [comment]
Ah yes.
Sorry, you can still manually compile and edit this app to fit your visual needs, but I will not change the sizing. It have been carefully selected for the usability guidelines and a proper mobile user experience. So the height will not change, and unfortunately the scrolling system uses hardcoded javascript height for it, so I will not be able to change it :)

**Comment by RobertZenz** [comment]
I see, okay, I will then go with that. Thank you.
