### ISSUE TITLE
add an option to enable callto link after phone numbers

### ISSUE THREAD

**Issue by adsworth** [nextcloud/contacts#110]
it'd be nice if a callto link could be displayed after phone numbers. This would allow users to initiate calls directly from the contacts app.

**Comment by adsworth** [comment]
the same could be said for email addresses. :)

**Comment by skjnldsv** [comment]
Good idea indeed!

**Comment by skjnldsv** [comment]
Should we display it only in mobile view?

**Comment by adsworth** [comment]
I'd say yes definitely.

**Comment by j-ed** [comment]
@skjnldsv Why should you limit the availability of callto links only to the mobile view?
I could imagine that users would use the auto dial feature on a desktop PC to, especially
if Nextcloud is used in a business environment.

**Comment by adsworth** [comment]
I'd definitely say on both views. Personally I don't need it in the mobile view as I sync to my android address book.

**Comment by skjnldsv** [comment]
@j-ed I guess you're right! And since this is a protocol, other apps may be using it.

**Comment by skjnldsv** [comment]
Fixed by #193
