### ISSUE TITLE
Possibility to hide the detailed name to make a leaner UI

### ISSUE THREAD

**Issue by rollanders** [nextcloud/contacts#1101]
I do not need the detailed name with Prefix, First name, Middle name, Family name and Suffix. The displayed name is all I need. I can delete the detailed name but will then miss the possibility to sort on First or Family name. The alternative would be to hide the detailed name. I would like to have that possibility in the configuration - I do not want to go through all the contacts. I guess it is a question about the CSS. Maybe I can fix it on my set up?

**Comment by skjnldsv** [comment]
Yes, you could manually hide this on your setup.
You can use something like uBlock/adblock with this filter `##.property[prop-name="n"]`

Though we will not add this feature as this is out of scope.
This is a too specific use case :)

**Comment by rollanders** [comment]
Do you mean I should use an adblocker on my Web-browser? And that all other users should do the same? 
I think I am not the only one who would welcome this possibility. Can you rethink and open up the request again? 
As a pesonal solution I would rather hide it by editing the CSS-file. That would then work for all users. Can you guide me on that possibility?

**Comment by skjnldsv** [comment]
Since most of users nowadays uses adblock, and you asked for a `fix [it] on my set up`, so I provided a simple option for you :)
I will not add an option for that. I think this is out of the scope of this software, but more importantly, having too many options is a really bad user experience and we do not want to go this way. 
References: https://ometer.com/preferences.html and https://nextcloud.com/design/

**Comment by skjnldsv** [comment]
Though you can also install the [theming_customcss app](https://apps.nextcloud.com/apps/theming_customcss) and add the following css:
```css
.app-contacts .property[prop-name="n"] {
	display: none;
}
```

**Comment by rollanders** [comment]
Thanks. Will try that.
    Den tisdag 14 maj 2019 14:36:10 CEST, John Molakvoæ <notifications@github.com> skrev:  
 
 
Though you can also install the theming_customcss app and add the following css:
.app-contacts .property[prop-name="n"] {
	display: none;
}

**Comment by rollanders** [comment]
Thanks. Exactly what I wanted.

**Comment by rollanders** [comment]
May I get the CSS for the Company and Title fileds. I do not want them

**Comment by skjnldsv** [comment]
Sure.
use ```#details-org-container {
	display: none;
}```

**Comment by rollanders** [comment]
Thanks for a rapid answer. Sorry, this did not work. Something is missing? 
I tried 
#details-org-container { display: none; }
and
.app-contacts #details-org-container { display: none; }
and 
.app-contacts .details-org-container { display: none; }
and 
.app-contacts .property[details-org-container] { display: none; }

**Comment by skjnldsv** [comment]
```
.app-contacts #details-org-container {
	display: none !important;
}
```

**Comment by rollanders** [comment]
Many thanks. 
This looks much leaner and nicer. I think more than me would welcome that as an option
