### ISSUE TITLE
Sync existing users with contacts

### ISSUE THREAD

**Issue by Lars1963** [nextcloud/contacts#1117]
As I just discovered, it seems not possible to add any existing nc-users to the contact-apps (by hand or automated). So all the users are duplicated, which imo is not very usefull.

I found a similar issue here: https://github.com/nextcloud/server/issues/693

Is there any chance that this feature will be implemented?

**Comment by skjnldsv** [comment]
Yes, this is planned, but we're lacking free time to tackle this :)
Let's focus on the server issue ;)

**Comment by mburnicki** [comment]
Please also keep in mind that this should not be done by default.

Compare it to an email server at your internet hoster: you have a single domain/account at the hoster, and can you create many more email users or web users for your domain account, but you don't see the accounts of other customers of the same hoster who also have different domains registered.

So unless you have a "small" nextcloud installation where everybody who has an nextcloud account is also a contact of the other ones who have an account, you shouldn't even see other nextcloud accounts, IMO.

**Comment by Lars1963** [comment]
@mburnicki 
Okay, I do have a "small" organisation, where in the main adressbook the users are also the employees. They are now shown twice in the contact-search, which imo is most confusing. Therefore I would like to see a option to manually sync between users and contacts or a option in the search-panel to not show users.

![contacts](https://user-images.githubusercontent.com/45886938/58461519-29ba4f80-8130-11e9-936a-748dcd231276.png)

**Comment by skjnldsv** [comment]
Yes, this is what https://github.com/nextcloud/server/issues/693 is all about, please add a :+1: there :)
