### ISSUE TITLE
Contacts saving errors out (PUT 415) (for vcards v.2.1)

### ISSUE THREAD

**Issue by newhinton** [nextcloud/contacts#1125]
### Describe the bug
I wanted to sort all my ~200 contacts and make use of groups. I started sorting them. At first everything seems fine, the groups are beeing created and contacts moved, however, a reload reveals that only most of the contacts are beeing transferred. Some error out, but it is only visible on the console. The error does not contain great information about the error itself.

1. Open Contact
2. Add Group
3. Continue working on contacts
4. Reload and see that some have not been saved.

This behaviour is not limited by groups, basically any field is "readonly" and changes are not saved in the backend.

`
Error: ""
    r https://domain.tld/apps/contacts/js/contacts.js?v=d261a300-80:512
    r https://domain.tld/apps/contacts/js/contacts.js?v=d261a300-80:512
    e https://domain.tld/apps/contacts/js/contacts.js?v=d261a300-80:512
    e https://domain.tld/apps/contacts/js/contacts.js?v=d261a300-80:512
    e https://domain.tld/apps/contacts/js/contacts.js?v=d261a300-80:512
    onreadystatechange https://domain.tld/apps/contacts/js/contacts.js?v=d261a300-80:512
contacts.js:637:4631

`

Used browser: Firefox
Nextcloud 16.0.1
Contacts  3.1.1

If you need a "broken" contact, i can provide some.

**Comment by skjnldsv** [comment]
Hey :)
I will need a better log :/

If any error happens on contacts, we write detailed messages in the console.

**Comment by newhinton** [comment]
That is basically everything i get out of it which is clearly related to the saving. 

Interestingly: For every contact that does work, i get the following:

`
The following contact needed a correction that failed: duplicate types [Object]
`


I will try to copy over my whole contacts database to my dev instance, but that will have to wait until tomorrow :D

**Comment by newhinton** [comment]
So, i got it set up and those are my results:

The error is still the same, 
` Error: ""` 
 `    n dist.js:2878` 
 `    e dist.js:2928` 
 `    e dist.js:3066` 
`     e dist.js:3158` 
`     onreadystatechange dist.js:3688` 
` addressbooks.js:598` 


It affects ALL version 2.1 vcards, and some 3.0 and even less 4.0

**Comment by newhinton** [comment]
This is all very strange, and i don't quiet know what to do with the information i found :D

**Comment by newhinton** [comment]
It seems the import issue may be related to #990

**Comment by newhinton** [comment]
Okay, that is strange. I am home now, and all my contacts save properly.

Which is strange, because that means that somehow on two different machines, and two different isp's the same contacts failed to save

**Comment by newhinton** [comment]
If i reeimport the corresponding vcard (download, delete & import) the vcard works fine (on prod)
On my dev machine, i have no errors whatsoverer (except the import stuff, but i guess we can rule that out as the cause for my problems)

**Comment by skjnldsv** [comment]
> It affects ALL version 2.1 vcards (107)

Make sense sinc we don't support vcard 2.1

**Comment by skjnldsv** [comment]
Could you check the network tab and see the output of the failed uploads? (not the 2.1 as we already know what's up)

**Comment by newhinton** [comment]
Okay. it seems that 2.1 is the issue. I get an 415 if i try to save the contact:

Request URL:https://domain.tld/remote.php/dav/addressbooks/users/Felix/Contacts/71b0bed1-7927-4722-8e4d-f35bf5aad541.vcf
Request method:PUT
Remote address:ip:443
Status code:
415
Version:HTTP/2.0
Referrer Policy:no-referrer-when-downgrade

The payload confirms that it is indeed a v 2.1 (have tested this for a few contacts)


So, now i know why it happens, but what should we do about it?

**Comment by skjnldsv** [comment]
You need to manually convert your vcard 2.1 to 3.0.
This plugin seems to be made for that, never tried it though
https://github.com/jowave/vcard2to3

**Comment by newhinton** [comment]
While that should solve my immediate problem, that could occur to other people as well. Is there a way this app could do such things automatically in the future? Or would that be work that is simply out of scope?

**Comment by skjnldsv** [comment]
Then : duplicate of https://github.com/nextcloud/contacts/issues/273
or https://github.com/nextcloud/contacts/issues/492 ;)

**Comment by newhinton** [comment]
that is what i thought! ;)

therefore: case closed!

thanks for pointing out 2.1 incompatibility, that made clear what was happening :)

**Comment by skjnldsv** [comment]
Also relevant https://github.com/nextcloud/contacts/issues/990
