### ISSUE TITLE
Only blank page presented after update to v3.1.2

### ISSUE THREAD

**Issue by steve-s-71** [nextcloud/contacts#1133]
App shows only a blank page after update to v3.1.2. Apparently the contact sync via DAVx5 still works.

Any ideas?

NC 15.0.7, tested with Firefox und Chrome

**Comment by skjnldsv** [comment]
Hello!
I will need your browser console log to investigate this issue.
Open your console, reload your page and/or do the action leading to this issue and copy/paste the log in this thread.

<details>
<summary>How to access your browser console (Click to expand)</summary>

# Chrome
- Press either CTRL + SHIFT + J to open the “console” tab of the Developer Tools.
- Alternative method:
    1. Press either CTRL + SHIFT + I or F12 to open the Developer Tools.
    2. Click the “console” tab.

# Safari
- Press CMD + ALT + I to open the Web Inspector.
- See Chrome’s step 2. (Chrome and Safari have pretty much identical dev tools.)

# IE9
1. Press F12 to open the developer tools.
2. Click the “console” tab.

# Firefox
- Press CTRL + SHIFT + K to open the Web console (COMMAND + SHIFT + K on Macs).
- or, if Firebug is installed (recommended):
    1. Press F12 to open Firebug.
    2. Click on the “console” tab.

# Opera
1. Press CTRL + SHIFT + I to open Dragonfly.
2. Click on the “console” tab.
</details>

**Comment by steve-s-71** [comment]
Hi @skjnldsv here is the console output:

![Untitled 1](https://user-images.githubusercontent.com/17343515/59288141-5d8a8e80-8c73-11e9-9936-5f3c048666cb.jpg)

**Comment by skjnldsv** [comment]
Hello, could you expand the red error? :)

**Comment by auberginepop** [comment]
Same issue here running NC 15.0.8 in the snap.

**Comment by skjnldsv** [comment]
Also, have you tried clearing the cache?

**Comment by steve-s-71** [comment]
Here you go, @skjnldsv:


![Untitled 1](https://user-images.githubusercontent.com/17343515/59288409-076a1b00-8c74-11e9-9a94-f916a653321b.jpg)

**Comment by steve-s-71** [comment]
Yes, clearing the cache was the first I did....

**Comment by skjnldsv** [comment]
@steve-s-71 @auberginepop can any of you install custom tar.gz apps?
(so I can make you try some test builds?

**Comment by steve-s-71** [comment]
I think yes. I dont risk my contacts data doing that - right?

**Comment by skjnldsv** [comment]
@steve-s-71 no, contacts are stored in the db, the contacts app have nothing to do with that :)

**Comment by skjnldsv** [comment]
Here, please try this version
[contacts.tar.gz](https://github.com/nextcloud/contacts/files/3277596/contacts.tar.gz)

**Comment by skjnldsv** [comment]
(you can still uninstall&delete, then install the default appstore one after that)

**Comment by JerryPenguin** [comment]
Hi,
thank you for the quick reaction.
Your new version runs fine with me.
I had the same problem, which is now fixed.

Thank you

**Comment by skjnldsv** [comment]
Fixed in https://github.com/nextcloud/contacts/commit/853c3dead32d1375954e252bb4c3ccce867b56ec

3.1.3 is out

**Comment by steve-s-71** [comment]
Thank you @skjnldsv, 3.1.3 work like a charm!

**Comment by skjnldsv** [comment]
Thanks for the feedback everyone :)
Sorry for the fuzz!

**Comment by auberginepop** [comment]
Fast work!!
