### ISSUE TITLE
Strange behaviour when creating a group

### ISSUE THREAD

**Issue by MeCias** [nextcloud/contacts#1142]
Hi,

just noticed with the latest contact app 3.1.3 that if I am creating a group a window pops up that shows some code like structure. Not sure whether it is a feature or a bug?

![Annotation 2019-06-15 132336](https://user-images.githubusercontent.com/4476171/59550873-d68a2e80-8f70-11e9-9a02-663080a15969.jpg)

**Comment by skjnldsv** [comment]
@raimund-schluessler you had this issue as well, right?
Or was it @korelstar ?

**Comment by korelstar** [comment]
Yes, both of us ;-)

Please see https://github.com/nextcloud/nextcloud-vue/issues/411

**Comment by tdoerschel** [comment]
I can confirm this issue as well on both my nextcloud instances

**Comment by skjnldsv** [comment]
Closing in favour of https://github.com/nextcloud/nextcloud-vue/issues/411
