### ISSUE TITLE
VCard object with uid already exists in this addressbook collection on creation

### ISSUE THREAD

**Issue by yan-** [nextcloud/contacts#1177]
This is similar to #854 

### Steps to reproduce
1. Create a new contact in Android or Thunderbird (with CardBook)
2. Click on 'sync'

### Expected behaviour
Contact is synchronized to Nextcloud without errors or created if new.

### Actual behaviour
I get the error message "HTTP 400 Bad Request" in Android and the the following error log entry in Nextcloud. Contacts are not synced/created.

[webdav] Fatal: Sabre\DAV\Exception\BadRequest: VCard object with uid already exists in this addressbook collection. at <<closure>>

0. /var/www/html/cloud/3rdparty/sabre/dav/lib/CardDAV/AddressBook.php line 144
   OCA\DAV\CardDAV\CardDavBackend->createCard("2", "fc1bf920-97b9-4 ... f", "BEGIN:VCARD\r\n ... n")
1. /var/www/html/cloud/3rdparty/sabre/dav/lib/DAV/Server.php line 1096
   Sabre\CardDAV\AddressBook->createFile("fc1bf920-97b9-4 ... f", "BEGIN:VCARD\r\n ... n")
2. /var/www/html/cloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php line 525
   Sabre\DAV\Server->createFile("addressbooks/us ... f", "BEGIN:VCARD\r\n ... n", null)
3. <<closure>>
   Sabre\DAV\CorePlugin->httpPut(Sabre\HTTP\Reque ... "}, Sabre\HTTP\Response {})
4. /var/www/html/cloud/3rdparty/sabre/event/lib/EventEmitterTrait.php line 105
   undefinedundefinedcall_user_func_array([Sabre\DAV\CorePlugin {},"httpPut"], [Sabre\HTTP\Requ ... }])
5. /var/www/html/cloud/3rdparty/sabre/dav/lib/DAV/Server.php line 479
   Sabre\Event\EventEmitter->emit("method:PUT", [Sabre\HTTP\Requ ... }])
6. /var/www/html/cloud/3rdparty/sabre/dav/lib/DAV/Server.php line 254
   Sabre\DAV\Server->invokeMethod(Sabre\HTTP\Reque ... "}, Sabre\HTTP\Response {})
7. /var/www/html/cloud/apps/dav/lib/Server.php line 316
   Sabre\DAV\Server->exec()
8. /var/www/html/cloud/apps/dav/appinfo/v2/remote.php line 35
   OCA\DAV\Server->exec()
9. /var/www/html/cloud/remote.php line 163
   undefinedundefinedrequire_once("/var/www/html/c ... p")

PUT /remote.php/dav/addressbooks/users/yan/contacts/fc1bf920-97b9-4f69-96e2-6a5f217d6557.vcf
from [IP] by yan at 2019-07-16T14:59:14+00:00

## Server configuration detail

**Operating system:** Linux 4.19.0-5-amd64 #1 SMP Debian 4.19.37-5 (2019-06-19) x86_64

**Webserver:** Apache/2.4.38 (Debian) (apache2handler)

**Database:** mysql 10.3.15

**PHP version:** 

7.3.4-2
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, sodium, standard, apache2handler, mysqlnd, PDO, xml, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, imagick, intl, json, exif, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache

**Nextcloud version:** 16.0.3 - 16.0.3.0

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.2.0
 - activity: 2.9.1
 - bruteforcesettings: 1.4.0
 - calendar: 1.7.0
 - cloud_federation_api: 0.2.0
 - comments: 1.6.0
 - contacts: 3.1.3
 - dav: 1.9.2
 - federatedfilesharing: 1.6.0
 - federation: 1.6.0
 - files: 1.11.0
 - files_pdfviewer: 1.5.0
 - files_rightclick: 0.13.0
 - files_sharing: 1.8.0
 - files_texteditor: 2.8.0
 - files_trashbin: 1.6.0
 - files_versions: 1.9.0
 - files_videoplayer: 1.5.0
 - firstrunwizard: 2.5.0
 - gallery: 18.3.0
 - issuetemplate: 0.5.0
 - logreader: 2.1.0
 - lookup_server_connector: 1.4.0
 - nextcloud_announcements: 1.5.0
 - notifications: 2.4.1
 - oauth2: 1.4.2
 - password_policy: 1.6.0
 - privacy: 1.0.0
 - provisioning_api: 1.6.0
 - recommendations: 0.4.0
 - serverinfo: 1.6.0
 - sharebymail: 1.6.0
 - support: 1.0.0
 - survey_client: 1.4.0
 - systemtags: 1.6.0
 - theming: 1.7.0
 - twofactor_backupcodes: 1.5.0
 - updatenotification: 1.6.0
 - viewer: 1.0.0
 - workflowengine: 1.6.0
Disabled:
 - admin_audit
 - encryption
 - files_external
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "***REMOVED SENSITIVE VALUE***"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "16.0.3.0",
    "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "sendmail",
    "mail_sendmailmode": "smtp",
    "mail_domain": "***REMOVED SENSITIVE VALUE***"
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

## Client configuration

**Browser:** Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0

**Operating system:** 

## Logs

<details><summary>Web server error log</summary>

```

```
</details>

<details><summary>Nextcloud log</summary>

```
[webdav] Fatal: Sabre\DAV\Exception\BadRequest: VCard object with uid already exists in this addressbook collection. at <<closure>>

0. /var/www/html/cloud/3rdparty/sabre/dav/lib/CardDAV/AddressBook.php line 144
   OCA\DAV\CardDAV\CardDavBackend->createCard("2", "fc1bf920-97b9-4 ... f", "BEGIN:VCARD\r\n ... n")
1. /var/www/html/cloud/3rdparty/sabre/dav/lib/DAV/Server.php line 1096
   Sabre\CardDAV\AddressBook->createFile("fc1bf920-97b9-4 ... f", "BEGIN:VCARD\r\n ... n")
2. /var/www/html/cloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php line 525
   Sabre\DAV\Server->createFile("addressbooks/us ... f", "BEGIN:VCARD\r\n ... n", null)
3. <<closure>>
   Sabre\DAV\CorePlugin->httpPut(Sabre\HTTP\Reque ... "}, Sabre\HTTP\Response {})
4. /var/www/html/cloud/3rdparty/sabre/event/lib/EventEmitterTrait.php line 105
   undefinedundefinedcall_user_func_array([Sabre\DAV\CorePlugin {},"httpPut"], [Sabre\HTTP\Requ ... }])
5. /var/www/html/cloud/3rdparty/sabre/dav/lib/DAV/Server.php line 479
   Sabre\Event\EventEmitter->emit("method:PUT", [Sabre\HTTP\Requ ... }])
6. /var/www/html/cloud/3rdparty/sabre/dav/lib/DAV/Server.php line 254
   Sabre\DAV\Server->invokeMethod(Sabre\HTTP\Reque ... "}, Sabre\HTTP\Response {})
7. /var/www/html/cloud/apps/dav/lib/Server.php line 316
   Sabre\DAV\Server->exec()
8. /var/www/html/cloud/apps/dav/appinfo/v2/remote.php line 35
   OCA\DAV\Server->exec()
9. /var/www/html/cloud/remote.php line 163
   undefinedundefinedrequire_once("/var/www/html/c ... p")

PUT /remote.php/dav/addressbooks/users/yan/contacts/fc1bf920-97b9-4f69-96e2-6a5f217d6557.vcf
from [IP] by yan at 2019-07-16T18:34:05+00:00
```
</details>

<details><summary>Browser log</summary>

</details>

**Comment by skjnldsv** [comment]
Well, this is on purpose.
An uid means unique identifier, so you cannot have duplicate.

If there is a conflict (like your current situation), it will deny the push.
Are you trying to push a contact that is already synced in your server?
