### ISSUE TITLE
The contact you were trying to edit has changed. Please manually refresh the contact. Any further edits will be discarded.

### ISSUE THREAD

**Issue by tomynr1** [nextcloud/contacts#1204]
### Steps to reproduce
Update an existing contact. (my contacts are mostly imported from a vcf file with my google contacts)

### Expected behaviour
Contact get updated

### Actual behaviour
* Some/all fields get reset if I switch to another contact and back to the one I have modified.

* `The contact you were trying to edit has changed. Please manually refresh the contact. Any further edits will be discarded.` appers in top left corner

* A refresh button appears near the message bubble

## Server configuration detail

**Operating system:** Linux 4.4.0-157-generic #185-Ubuntu SMP Tue Jul 23 09:17:01 UTC 2019 x86_64

**Webserver:** nginx/1.15.8 (fpm-fcgi)

**Database:** mysql 10.0.38

**PHP version:** 

7.3.7-2+ubuntu16.04.1+deb.sury.org+1
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, sodium, session, standard, cgi-fcgi, mysqlnd, PDO, xml, apcu, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, geoip, gettext, iconv, igbinary, imagick, intl, json, ldap, exif, mysqli, pdo_mysql, apc, posix, readline, redis, shmop, SimpleXML, smbclient, soap, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Phar, libsmbclient, Zend OPcache

**Nextcloud version:** 16.0.3 - 16.0.3.0

**Updated from an older Nextcloud/ownCloud or fresh install:** last minor release

**Where did you install Nextcloud from:** nextcloud.com

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.2.0
 - activity: 2.9.1
 - admin_audit: 1.6.0
 - apporder: 0.7.1
 - bookmarks: 1.1.1
 - bruteforcesettings: 1.4.0
 - calendar: 1.7.0
 - cloud_federation_api: 0.2.0
 - comments: 1.6.0
 - contacts: 3.1.3
 - cospend: 0.1.0
 - data_request: 1.3.0
 - dav: 1.9.2
 - event_update_notification: 0.3.4
 - federatedfilesharing: 1.6.0
 - files: 1.11.0
 - files_downloadactivity: 1.5.0
 - files_external: 1.7.0
 - files_markdown: 2.0.6
 - files_pdfviewer: 1.5.0
 - files_rightclick: 0.13.0
 - files_sharing: 1.8.0
 - files_trashbin: 1.6.0
 - files_versions: 1.9.0
 - files_videoplayer: 1.5.0
 - firstrunwizard: 2.5.0
 - flowupload: 0.1.2
 - gallery: 18.3.0
 - issuetemplate: 0.5.0
 - logreader: 2.1.0
 - lookup_server_connector: 1.4.0
 - metadata: 0.9.0
 - nextcloud_announcements: 1.5.0
 - notes: 3.0.1
 - notifications: 2.4.1
 - oauth2: 1.4.2
 - ocdownloader: 1.7.2
 - onlyoffice: 2.4.0
 - password_policy: 1.6.0
 - phonetrack: 0.5.2
 - previewgenerator: 2.1.0
 - privacy: 1.0.0
 - provisioning_api: 1.6.0
 - rainloop: 6.0.3
 - ransomware_protection: 1.4.0
 - recommendations: 0.4.0
 - serverinfo: 1.6.0
 - sharebymail: 1.6.0
 - sharerenamer: 2.6.1
 - spreed: 6.0.4
 - support: 1.0.0
 - text: 1.0.1
 - theming: 1.7.0
 - twofactor_backupcodes: 1.5.0
 - twofactor_totp: 3.0.1
 - updatenotification: 1.6.0
 - video_converter: 0.1.0
 - viewer: 1.0.0
 - workflowengine: 1.6.0
Disabled:
 - deck
 - encryption
 - federation
 - files_texteditor
 - survey_client
 - systemtags
 - tasks
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "onlyoffice": {
        "verify_peer_off": true
    },
    "activity_expire_days": 14,
    "auth.bruteforce.protection.enabled": true,
    "blacklisted_files": [
        ".htaccess",
        "Thumbs.db",
        "thumbs.db"
    ],
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "cloud.t-szabo.com",
        "cloud.famszabo.com"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "https:\/\/cloud.famszabo.com",
    "dbtype": "mysql",
    "version": "16.0.3.0",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "htaccess.RewriteBase": "\/",
    "overwriteprotocol": "https",
    "loglevel": 1,
    "logtimezone": "Europe\/Berlin",
    "logfile": "\/var\/www\/nextcloud_data\/nextcloud.log",
    "log_rotate_size": 104857600,
    "cron_log": true,
    "installed": true,
    "filesystem_check_changes": 0,
    "quota_include_external_storage": false,
    "knowledgebaseenabled": false,
    "memcache.local": "\\OC\\Memcache\\APCu",
    "filelocking.enabled": "true",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 0,
        "timeout": 0
    },
    "maintenance": false,
    "theme": "",
    "integrity.check.disabled": false,
    "updater.release.channel": "stable",
    "enable_previews": true,
    "enabledPreviewProviders": [
        "OC\\Preview\\PNG",
        "OC\\Preview\\JPEG",
        "OC\\Preview\\GIF",
        "OC\\Preview\\BMP",
        "OC\\Preview\\XBitmap",
        "OC\\Preview\\Movie",
        "OC\\Preview\\PDF",
        "OC\\Preview\\MP3",
        "OC\\Preview\\TXT",
        "OC\\Preview\\MarkDown"
    ],
    "preview_max_x": 1024,
    "preview_max_y": 768,
    "preview_max_scale_factor": 1,
    "mail_smtpmode": "smtp",
    "mail_smtpauthtype": "LOGIN",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "587",
    "mail_smtpauth": 1,
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "mysql.utf8mb4": true,
    "app_install_overwrite": [
        "calendar",
        "apporder"
    ],
    "ldapIgnoreNamingRules": false,
    "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
    "mail_sendmailmode": "smtp"
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** false

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

## Client configuration

**Browser:** Brave browser

**Operating system:** Ubuntu 18.04.3 LTS and Windows 7 SP1

## Logs

<details><summary>Web server error log</summary>

```
2019/08/08 09:52:41 [warn] 13001#13001: *59175 an upstream response is buffered to a temporary file /var/lib/nginx/proxy/9/33/0000000339 while reading upstream, client: xxx.xxx.xx.xxx, server: cloud.example.com, request: "PROPFIND /remote.php/dav/addressbooks/users/user/afxxxxx-ff72-4xxx-xxx2-c3exxxxf9c40/ HTTP/1.1", upstream: "http://127.0.0.1:82/remote.php/dav/addressbooks/users/user/afxxxxx-ff72-4xxx-xxx2-c3exxxxf9c40/", host: "cloud.example.com"

```
</details>

<details><summary>Nextcloud log</summary>

```
[webdav] Fatal: Sabre\DAV\Exception\UnsupportedMediaType: This resource only supports valid vCard or jCard data. Parse error: End of document reached prematurely at <<closure>>

 0. /var/www/nextcloud/3rdparty/sabre/dav/lib/CardDAV/Plugin.php line 294
    Sabre\CardDAV\Plugin->validateVCard("*** sensitive parameter replaced ***", false)
 1. <<closure>>
    Sabre\CardDAV\Plugin->beforeWriteContent("*** sensitive parameter replaced ***", Sabre\CardDAV\Card {}, "*** sensitive parameter replaced ***", false)
 2. /var/www/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php line 105
    undefinedundefinedcall_user_func_array([OCA\DAV\CardDAV ... "], ["*** sensitive  ... e])
 3. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 1128
    Sabre\Event\EventEmitter->emit("beforeWriteContent", ["*** sensitive  ... e])
 4. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php line 513
    Sabre\DAV\Server->updateFile("*** sensitive parameters replaced ***")
 5. <<closure>>
    Sabre\DAV\CorePlugin->httpPut(Sabre\HTTP\Reque ... "}, Sabre\HTTP\Response {})
 6. /var/www/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php line 105
    undefinedundefinedcall_user_func_array([Sabre\DAV\CorePlugin {},"httpPut"], [Sabre\HTTP\Requ ... }])
 7. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 479
    Sabre\Event\EventEmitter->emit("method:PUT", [Sabre\HTTP\Requ ... }])
 8. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 254
    Sabre\DAV\Server->invokeMethod(Sabre\HTTP\Reque ... "}, Sabre\HTTP\Response {})
 9. /var/www/nextcloud/apps/dav/lib/Server.php line 316
    Sabre\DAV\Server->exec()
10. /var/www/nextcloud/apps/dav/appinfo/v2/remote.php line 35
    OCA\DAV\Server->exec()
11. /var/www/nextcloud/remote.php line 163
    undefinedundefinedrequire_once("/var/www/nextcl ... p")

PUT /remote.php/dav/addressbooks/users/user/af18427f-ff72-4c78-b942-c3e5179f9c40/dbf68755-7724-48e0-ae67-55b9f3ce3611.vcf
from 127.0.0.1 by user at 2019-08-08T10:28:53+02:00
```
</details>

<details><summary>Browser log</summary>

Insert your browser log here, this could for example include:

	a) The javascript console log
<img src="https://i.imgur.com/k0lSCv6.png"  width="750">
	b) The network log
<img src="https://i.imgur.com/pesJdmK.png"  width="750">

        c) Request headers

:authority: cloud.example.com
:method: PUT
:path: /remote.php/dav/addressbooks/users/user/af18427f-ff72-4c78-b942-c3e5179f9c40/1f82c028-5efd-4226-8e7a-a3d231c748bf.vcf
:scheme: https
accept: */*
accept-encoding: gzip, deflate, br
accept-language: en-US,en;q=0.9
cache-control: max-age=0
content-length: 382
content-type: application/xml; charset=UTF-8
cookie: __cfduid=dbe5e1a2c8af7f8dfca487c48872c22871564152279; oc_sessionPassphrase=xBqpTTlbm1pDrezYnSBKgRgR8h6Ce6xqLRxWGm5ft7DAUHW3I21MdvQjuZ3M%2F5HB45Hxhb2m6poh14PIelYdDFWURii4DzDuMeoLqGTGjqyYMwNYb%2B6Mr8fW0IwtZ9ID; __Host-nc_sameSiteCookielax=true; __Host-nc_sameSiteCookiestrict=true; ocy4nduglrq1=oq8halj52j1vob6ud96h8penu4; nc_username=user; nc_token=AEnWcvAE2KOc3SaFRUltIzx70kJB1B6N; nc_session_id=oq8halj52j1vob6ud96h8penu4
depth: 0
dnt: 1
if-match: null
origin: https://cloud.example.com
referer: https://cloud.example.com/
requesttoken: 0fWQv5i2lRcFDw3w92h95PNYvPzcaw9/cxQL3TZF+BM=:iI397s2B5lBhZ2fAh14TkYsQ0JifDWMSWCZtqQ4Sllw=
sec-fetch-mode: cors
sec-fetch-site: same-origin
user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.87 Safari/537.36
x-requested-with: XMLHttpRequest

</details>

**Comment by skjnldsv** [comment]
Hey!
I will ned multiple informations
1. please properly copy the json formatted string from your nextcloud log, the one you pasted is really difficult to read :)
2. I will need a screenshot of your network requests.
Before you do anything, still on the development tools, there is a tab called `network`. Click on it and then the xhr filter. Do your action and screenshot the network log like this:
![capture d ecran_2018-09-27_21-49-46](https://user-images.githubusercontent.com/14975046/46170857-43548000-c29f-11e8-9403-db72713dd9c1.png)
Also on the failing request, please copy the request headers (or screenshot)

**Comment by tomynr1** [comment]
@skjnldsv Thank you for your quick reply and sorry for my misstakes. I have updated the bugreport with the requested data.

**Comment by skjnldsv** [comment]
@tomynr1 Thanks :)
Could you also copy/paste (here, no need to edit first post) the response headers of the first request (after you edited a field), not the 412 one that is failing ;)

**Comment by tomynr1** [comment]
@skjnldsv Sure! After I copied the header, I have disabled caching on cloudflare and it seems like the problem is solved, or at least I cannot reproduce it for now. Is there a way of using caching on cloudflare without causing problems like this?

```
cache-control: no-store, no-cache, must-revalidate
cf-ray: 5030850ec844d8f9-AMS
content-security-policy: default-src 'none';
date: Thu, 08 Aug 2019 09:38:51 GMT
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
expires: Thu, 19 Nov 1981 08:52:00 GMT
oc-etag: "3156b6d0e6a0909abb05b1fddca90de1"
pragma: no-cache
referrer-policy: strict-origin
server: cloudflare
status: 204
strict-transport-security: max-age=15768000; includeSubDomains; preload;
x-content-type-options: nosniff
x-download-options: noopen
x-frame-options: SAMEORIGIN
x-permitted-cross-domain-policies: none
x-robots-tag: none
x-xss-protection: 1; mode=block
```

**Comment by skjnldsv** [comment]
Okay, that was going to be my next question :)
Since you're using cloudflare, please check this issue: https://github.com/nextcloud/contacts/issues/1157
