### ISSUE TITLE
Unclear how to exit import view

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/contacts#1231]
Currently when you do an import, this is what you see when it finishes:
![fully done needs primary close button](https://user-images.githubusercontent.com/925062/63694951-d67f9800-c817-11e9-9dc4-cf3b8fa55e2f.png)

It’s not really clear how to get out of it. Then at some point you see the X icon on the top right:
https://github.com/nextcloud/contacts/issues/606

Instead, there should be a primary button saying something like "Continue to Contacts". (While it’s importing it could be deactivated and have a spinner or so?) What do you think? :)

**Comment by skjnldsv** [comment]
Great idea!
Can you do it? :)
