### ISSUE TITLE
NC 11.01 / Contacts 1.5.3: One word in translation wrong (but only on my system)

### ISSUE THREAD

**Issue by kangaroo72** [nextcloud/contacts#124]
Hi,

I had a long time problems with syncing contacts. Now everything's fine, but one little thing (cosmetical).
I have a german user-interface. When I want to add a contact there has to be the selection "Privat" ... but there's the label called "Home". Every other label are in german.
Can someone tell me what file to edit?

Thanks

**Comment by skjnldsv** [comment]
@kangaroo72 On which property?

**Comment by kangaroo72** [comment]
I just want to change this word in german to "Privat"
![contact](https://cloud.githubusercontent.com/assets/6906390/22731005/775d58ae-ede9-11e6-85bb-3d52ccf9ffc5.jpg)

**Comment by skjnldsv** [comment]
https://www.transifex.com/nextcloud/nextcloud/translate/#de/contacts/99347862?q=home
