### ISSUE TITLE
Add an option to download a vCard 4.0 VCF file rather than a vCard 3.0 VCF file

### ISSUE THREAD

**Issue by MetaEntropy** [nextcloud/contacts#1247]
**Is your feature request related to a problem? Please describe.**
The problem is described on the following nextcloud server issue:
https://github.com/nextcloud/server/issues/16942

High quality CardDAV clients generate vCard 4.0 cards.
Nextcloud internally store these vCard 4.0 cards
The Nextcloud Contacts application support these vCard 4.0 cards
But the "Download" link in the Nextcloud Application provides vCard 3.0 cards, downgrading the content.

**Cause of the problem**
sabre/dav conservatively generates vCard 3.0 for any client that does not explicitly specify "Accept: text/vcard; version=4.0" in the HTTP request headers.
Web browsers use generic "Accept: * / *" lines.
The sabre/dav behavior is intentional (https://github.com/sabre-io/dav/issues/1190)

**Describe the solution you'd like**
Please, accept patches that fixes the problem:
1) A nextcloud server patch providing a plugin that provides a way to explicitly specify a version number as a HTTP query parameter version=4.0
2) A nextcloud contacts patch providing links to ?version=3.0 and ?version=4.0

[nextcloud-contacts-vcard-explicit-version-export-support.patch.txt](https://github.com/nextcloud/contacts/files/3565104/nextcloud-contacts-vcard-explicit-version-export-support.patch.txt)
[nextcloud-server-vcard-explicit-version-export-support.patch.txt](https://github.com/nextcloud/contacts/files/3565105/nextcloud-server-vcard-explicit-version-export-support.patch.txt)

**Describe alternatives you've considered**
1) Defaulting to vCard 4.0 for HTTP requests with 'Accept: * / *'. This may cause some compatibility problems with CardDAV clients unaware of vCard 4.0 (see https://github.com/sabre-io/dav/issues/1190)
2) Implementing the whole logic in nextcloud/contacts rather than in nextcloud/server, with links such as http://example.com/apps/contacts/vcf/123456789.vcf?version=4.0

**Additional context**
Please, find a screen shot showing both links when the patch are applied

![download-updated](https://user-images.githubusercontent.com/3903761/64101466-3624f880-cd6e-11e9-89d6-0c188b167a7f.png)

**Comment by skjnldsv** [comment]
Closing in favour of https://github.com/nextcloud/server/issues/12878
