### ISSUE TITLE
address type drop-down hides the delete button in multi-column view

### ISSUE THREAD

**Issue by j-ed** [nextcloud/contacts#126]
## Expected behavior
The Contacts app should allow to delete an address entry independently from the position where it is displayed on the screen and how many address entries exist.

## Current behavior
The Contacts app doesn't allow to delete an address entry if more than one entry exist, both entries are listed in multi-column view and the entry which should be deleted is displayed in the left column,
because the type drop-down hides the delete button.

Example:
![20170209_kontakte_adresse_loeschen](https://cloud.githubusercontent.com/assets/2572764/22795959/e0efbc5c-eef8-11e6-9b12-615d25905392.png)

### Steps to reproduce
1. Open a contact record with two existing address entries.
2. Make sure that the address entries are listed in two columns.
3. Try to delete the address entry in the left column.

#### Server Configuration

OS: Linux 3.2.84
Web server: Apache2 2.4.25
Database: MariaDB 5.5.54
PHP version: 5.6.29
Nextcloud version: 11.0.1
Contacts app: 1.5.3
#### Client Configuration

Browser: Mozilla Firefox 51.0.1
Operating system: Windows 7

**Comment by skjnldsv** [comment]
Yup, the column view is not ideal :/

**Comment by irgendwie** [comment]
The css column feature seems to ignore the delete icon, leading to the overlap.

**Comment by skjnldsv** [comment]
@irgendwie flex is the answer :)
