### ISSUE TITLE
more confirmation when delete

### ISSUE THREAD

**Issue by Chialya** [nextcloud/contacts#1261]
I have edit the compiled contacts.js.
I want an confirm message, when delete anything !

In the contact list is a nice feature to wait 7 sec till the contact will delete finaly.
-> but for me this is BULL SHUT!  (sorry)
How often a complete contact will be deleted? -> super rare !

So I've removed the "icon-delete" in the contact-list,
so there is no delete icon, like the older visions.

The permanently visible "icon-delete" for all contact-properties is also NOT GOOD !
A mobile phone number is quickly deleted by a mistake.

I've build in a dialog to confirm:
methods:{... confirmDeleteX:function(){OC.dialogs.alert(t("contacts"," {prop} ",{prop:this.property.name}),t("contacts","Delete ?"),this.deleteProperty,!0)}}

-> The confirmation bevore delete works perfectly!
but "this.deleteProperty" is not workling in the Message :(
Have an idea?

**Comment by skjnldsv** [comment]
Hello, I cannot understand your report.
Please use the appropriate template and have a look at our code of conduct https://nextcloud.com/code-of-conduct/. We don't need swearing nor use wording like "I want xxx". 
Thanks a lot.
