### ISSUE TITLE
Almost impossible to edit / add contacts

### ISSUE THREAD

**Issue by PlauzeTung** [nextcloud/contacts#1268]
### Steps to reproduce
1. Edit a contact information
2. Edit another contact information
3. The message "The contact you were trying to edit has changed" appears
4. All entered information after step 2 is lost

### Expected behaviour
Either:

- synchronize manually when I press a button

or:

- keep synchronizing the entered information without the error message
and lost information

### Actual behaviour
see reproducing steps

## Server configuration detail

**Operating system:** Linux 4.4.0-124-generic #148~14.04.1-Ubuntu SMP Thu May 3 07:26:53 UTC 2018 x86_64

**Webserver:** Apache/2.4 (fpm-fcgi)

**Database:** mysql 5.6.41

**PHP version:** 

7.1.30
Modules loaded: Core, date, libxml, openssl, pcre, sqlite3, zlib, bcmath, calendar, ctype, curl, dom, hash, fileinfo, filter, ftp, gd, gettext, gmp, SPL, iconv, session, intl, json, ldap, mbstring, mcrypt, standard, PDO, mysqlnd, pdo_sqlite, Phar, posix, readline, Reflection, imap, SimpleXML, soap, pdo_mysql, exif, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, mysqli, cgi-fcgi, imagick, ssh2, memcached, tideways, ionCube Loader, Zend OPcache

**Nextcloud version:** 16.0.4 - 16.0.4.1

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.2.0
 - activity: 2.9.1
 - admin_audit: 1.6.0
 - bruteforcesettings: 1.4.0
 - calendar: 1.7.1
 - cloud_federation_api: 0.2.0
 - comments: 1.6.0
 - contacts: 3.1.3
 - dav: 1.9.2
 - federatedfilesharing: 1.6.0
 - federation: 1.6.0
 - files: 1.11.0
 - files_pdfviewer: 1.5.0
 - files_rightclick: 0.15.1
 - files_sharing: 1.8.0
 - files_texteditor: 2.8.0
 - files_trashbin: 1.6.0
 - files_versions: 1.9.0
 - files_videoplayer: 1.5.0
 - firstrunwizard: 2.5.0
 - gallery: 18.3.0
 - impersonate: 1.3.0
 - issuetemplate: 0.5.0
 - logreader: 2.1.0
 - lookup_server_connector: 1.4.0
 - nextcloud_announcements: 1.5.0
 - notes: 3.0.3
 - notifications: 2.4.1
 - oauth2: 1.4.2
 - ocsms: 2.1.3
 - password_policy: 1.6.0
 - privacy: 1.0.0
 - provisioning_api: 1.6.0
 - recommendations: 0.4.0
 - serverinfo: 1.6.0
 - sharebymail: 1.6.0
 - support: 1.0.0
 - survey_client: 1.4.0
 - systemtags: 1.6.0
 - tasks: 0.11.3
 - theming: 1.7.0
 - twofactor_backupcodes: 1.5.0
 - updatenotification: 1.6.0
 - viewer: 1.1.0
 - workflowengine: 1.6.0
Disabled:
 - encryption
 - files_external
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "chemeleon.lima-city.de"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "tempdirectory": "\/home\/webpages\/lima-city\/chemeleon\/nextCloud\/tmp",
    "overwrite.cli.url": "https:\/\/chemeleon.lima-city.de",
    "dbtype": "mysql",
    "version": "16.0.4.1",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "maintenance": false,
    "theme": "",
    "loglevel": 2,
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "smtp",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "587",
    "mail_smtpauthtype": "LOGIN",
    "mail_smtpauth": 1,
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "mysql.utf8mb4": true,
    "updater.secret": "***REMOVED SENSITIVE VALUE***"
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

## Client configuration

**Browser:** Firefox 69.0

**Operating system:** Windows 10 x64

## Logs

<details><summary>Web server error log</summary>

```
php log says:

no errors found

(error_php71.log is empty)
```
</details>

<details><summary>Nextcloud log</summary>

```
no other error message than this:

Error	PHP	Undefined index: log-detail at /home/webpages/lima-city/chemeleon/nextCloud/apps/issuetemplate/lib/Detail.php#59
```
</details>

<details><summary>Browser log</summary>

Network console:

JQMIGRATE: Migrate is installed, version 1.4.1 jquery-migrate.min.js:2:494
New search handler registered search.js:67:12
The escapeHTML library is deprecated! It will be removed in nextcloud 19. 2 globals.js:30:10
Connected to dav! 
Object { rootUrl: Getter & Setter, advertisedFeatures: Getter & Setter, currentUserPrincipal: Getter & Setter, principalCollections: Getter & Setter, calendarHomes: Getter & Setter, addressBookHomes: Getter & Setter, parser: Getter & Setter, _isConnected: Getter & Setter, _request: Getter & Setter, … }
Contacts.vue:288
The escapeHTML library is deprecated! It will be removed in nextcloud 19. 13 globals.js:30:10
The following contact needed a correction that failed: duplicate types 
Object { jCal: Getter & Setter, addressbook: Getter & Setter, vCard: Getter & Setter, conflict: Getter & Setter, dav: Getter & Setter, … }
validate.js:38:14
The following contact has been repaired: invalid REV 
Object { jCal: Getter & Setter, addressbook: Getter & Setter, vCard: Getter & Setter, conflict: Getter & Setter, dav: Getter & Setter, … }
validate.js:42:14
The following contact needed a correction that failed: duplicate types 
Object { jCal: Getter & Setter, addressbook: Getter & Setter, vCard: Getter & Setter, conflict: Getter & Setter, dav: Getter & Setter, … }
validate.js:38:14
The following contact needed a correction that failed: duplicate types 
Object { jCal: Getter & Setter, addressbook: Getter & Setter, vCard: Getter & Setter, conflict: Getter & Setter, dav: Getter & Setter, … }
validate.js:38:14
Error: ""
    r xmlUtility.js:73
    r xmlUtility.js:73
    e attachError.js:36
    e networkRequestHttpError.js:26
    e networkRequestClientError.js:26
    onreadystatechange request.js:353
contacts.js:354:13
This contact is outdated, the server refused it 
Object { jCal: Getter & Setter, addressbook: Getter & Setter, vCard: Getter & Setter, conflict: Getter & Setter, dav: Getter & Setter, … }
contacts.js:360:14

</details>

**Comment by skjnldsv** [comment]
This is already fixed in the upcoming version :)

**Comment by PlauzeTung** [comment]
ah okay, thank you, I'll wait for the next update then...

**Comment by skjnldsv** [comment]
Incoming :rocket: :wink:

**Comment by PlauzeTung** [comment]
I just updated to 16.0.5 and it's still happening...

**Comment by skjnldsv** [comment]
@PlauzeTung the next version of contacts, not nextcloud :)

**Comment by PlauzeTung** [comment]
Ah okay, when is the next update going to be released?

**Comment by skjnldsv** [comment]
Theoretically today :p

**Comment by skjnldsv** [comment]
@PlauzeTung released!
