### ISSUE TITLE
Feature Request: Save Contact websites to Bookmarks app

### ISSUE THREAD

**Issue by sunjam** [nextcloud/contacts#1272]
**Is your feature request related to a problem? Please describe.**
This is a useful to have request and not a priority.  I'd like to request contact website urls be automatically imported into the excellent [Nextcloud Bookmarks app](https://github.com/nextcloud/bookmarks) via REST api. That app is maintained by @marcelklehr  
If possible, to have a simple user toggle for those wanting to import to the [Bookmarks app](https://github.com/nextcloud/bookmarks) they have installed.

**Describe the solution you'd like**
Via Bookmarks [REST API](https://github.com/nextcloud/bookmarks/tree/master/docs)
* _Website URL_ becomes a [_Bookmark URL_](https://github.com/nextcloud/bookmarks/blob/master/docs/bookmark.rst).
* _Group Labels_ could become [_Bookmark Tags_](https://github.com/nextcloud/bookmarks/blob/master/docs/tag.rst)
* _Contact Notes_ could become [_Bookmark Descriptions_](https://github.com/nextcloud/bookmarks/blob/master/docs/bookmark.rst).  
* This action [might also be possible to automate with the Flow app](https://github.com/nextcloud/workflow_script) currently in development [for Nextcloud 18, as announced here](https://nextcloud.com/blog/nextcloud-flow-makes-it-easy-to-automate-actions-and-workflows/).

**Describe alternatives you've considered**
Manually adding the url to bookmarks, but this would be useful to have better integrated.

![Screen Shot 2019-09-23 at 11 59 51 AM](https://user-images.githubusercontent.com/1787238/65454329-c39dba80-ddf9-11e9-9b4c-2459c40c4322.png)

**Comment by skjnldsv** [comment]
Hey! Thanks for your suggestion!
@marcelklehr, what do you think?

**Comment by marcelklehr** [comment]
Like the idea of integrating the notes app with bookmarks, this definitely sounds like a good idea and I think such integrations are incredibly useful. I'm uncertain on the details of how this should look, however. As always, the devil is in details like ideally, bookmarks so created should probably be properly linked to a contact to propagate changes and display the associated contact, also I already foresee a [bike shed](https://en.wikipedia.org/wiki/Law_of_triviality) about where in the bookmarks tree these bookmarks should be put.

@skjnldsv What are your thoughts on this from a UX perspective? Also regarding https://github.com/nextcloud/bookmarks/issues/447

**Comment by marcelklehr** [comment]
Ah, I hadn't considered that. I was thinking more along the lines of an automatic integration, but this would be rather simple. The relevant URL would be: `c.nc.com/aps/bookmarks#/bookmarklet/<url>/<title?>`

**Comment by skjnldsv** [comment]
You're using hashes for the new vue bookmarks?

**Comment by marcelklehr** [comment]
Yup?

**Comment by skjnldsv** [comment]
You can use regular url with vue router :)
Makes it a bit cleaner ;)

**Comment by marcelklehr** [comment]
the API is now `apps/bookmarks/bookmarklet?url=xxx&title=yyy`, because URLs as part of the path apparently cause trouble.

**Comment by skjnldsv** [comment]
Fine for me! :D
Any starting version for this? So I'm sure I can stay compatible?

**Comment by marcelklehr** [comment]
That'll be v2.2.0 then

**Comment by jancborchardt** [comment]
Design-wise:
- Instead of the delete icon, we show a 3-dot menu with "Save to Bookmarks" and "Delete" (of course only when Bookmarks is installed)
- "Save to Bookmarks" simply saves it into the root bookmarks place, no tags or anything
- Gives tooltip feedback saying "Saved to Bookmarks [ Edit ]" in case people want to edit it.

That’s a simple first implementation, no space for bikeshedding. ;)

**Comment by skjnldsv** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there a no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.

If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.
