### ISSUE TITLE
Blank lines in vcf file result in failures

### ISSUE THREAD

**Issue by zontreck** [nextcloud/contacts#1277]
If the VCF file contains blank lines such as a export from "My Contacts Backup" for iOS just as a example, contacts will fail to import.

EXAMPLE
```
BEGIN:VCARD

VERSION:3.0

N;CHARSET=UTF-8:;;;;
```

**Comment by skjnldsv** [comment]
Hi!
Please use the issue template next time.

The vcf is not valid if it contains new lines.
There is nothing we can do. :/
You can manually replace the double new lines if you want it to pass.

I'm suggesting you use a proper vcf export tool to export valid contacts :)
