### ISSUE TITLE
Allow to share contacts with circles

### ISSUE THREAD

**Issue by doobry-systemli** [nextcloud/contacts#1299]
It would be nice to allow sharing calendars with Nextcloud circles (from the [circles app](https://github.com/nextcloud/circles/)). Is this something that you plan to implement?

On shared Nextcloud instances without admin access, circles are the only way to maintain groups on your own. Would be nice if the calendar app would support them.

**Comment by l0cKy93** [comment]
+1 for this feature request.
Like doobry-systemli said, Circles are very important for sharing without a central administrator. But without a good integration to other apps it is quite useless

**Comment by skjnldsv** [comment]
cc @daita

**Comment by tcitworld** [comment]
Closed in favour of #2422
