### ISSUE TITLE
Display Nickname as "contact label" if (Display) Name is not available

### ISSUE THREAD

**Issue by Amunak** [nextcloud/contacts#1322]
**Is your feature request related to a problem?**
There is no "contact label" when there is no full name or display name for a given contact.

**Describe the solution you'd like**
When the contact has at least a Nickname, that could be used as the label / display name.

Ideally when there isn't even a nickname, you could also show the company name (and possibly the title of the person within that company).

This:
![image](https://user-images.githubusercontent.com/781546/67671347-11b45980-f976-11e9-87f3-5c16372d31a3.png)

Could become this:
![image](https://user-images.githubusercontent.com/781546/67671483-56d88b80-f976-11e9-8bc8-4eb57b160222.png)

**Comment by skjnldsv** [comment]
Hi!
Not having a display name is against the vCard specifications.
If we do that, people will leave invalid vCards and not comply to the rfcs :shrug: 
Sorry, for me this is an incentive to being non-compliant :wink:

**Comment by Amunak** [comment]
Are the actual real name and display name separate things in vCard?

I think it would be totally acceptable to just copy the Nickname field into display name then. Or allow to "fix" that issue on all contacts at once or whatever.

The issue, currently, is that if I upload my Google contacts to NC I get about half of the usability, since suddenly contacts without a name display as blank, and I can't even easily fix them.
