### ISSUE TITLE
CardDAV sync with iOS 13 and macOS 15 becomes a mess

### ISSUE THREAD

**Issue by helmut72** [nextcloud/contacts#1326]
### Steps to reproduce (1)
1. create new contact: test, private phone 1234, work phone 4321, private mail test@private.com, work mail test@work.com
2. sync with iOS 13
3. sync with macOS 15

### Expected behaviour
Field mappings are equal on all clients

### Actual behaviour
Field mappings becomes a mess, private is "HOME and HOME,VOICE:

<img width="928" alt="Bildschirmfoto 2019-11-01 um 07 48 58" src="https://user-images.githubusercontent.com/1388751/68008077-ef745180-fc7d-11e9-9236-ca4d7f7d5d38.png">

### Steps to reproduce (2)
1. change in iOS 13 back to private and work as it should be
2. reload NC webinterface
3. sync with macOS 15

### Expected behaviour
Field mappings are equal on all clients

### Actual behaviour
Field mappings becomes a mess, private is empty, work is private:

<img width="1233" alt="Bildschirmfoto 2019-11-01 um 08 00 26" src="https://user-images.githubusercontent.com/1388751/68008093-fdc26d80-fc7d-11e9-9268-b0a0787ed905.png">

### Server configuration

**Database:**
MariaDB 10.3 UTF8MB4

**PHP version:**
7.3

**Nextcloud version:**
17.0

**Client version:**
iOS 13 and macOS 15

**Comment by skjnldsv** [comment]
Yep, welcome to a system that doesn't respect standards :woman_shrugging:

**Comment by skjnldsv** [comment]
Transferring for the sake of traceability :)

**Comment by helmut72** [comment]
> Yep, welcome to a system that doesn't respect standards

Which implementation is the standard?

BusyContacts do at least the same with Phone fields, but without quotation mark before HOME:

![Bildschirmfoto 2019-11-06 um 08 10 12](https://user-images.githubusercontent.com/1388751/68277257-17452a00-006f-11ea-8531-eee71db09f73.png)

**Comment by skjnldsv** [comment]
> Which implementation is the standard?

HOME,VOICE, "HOME,VOICE", "HOME"... All of those are valid according to the vcard rfc standards :)

**Comment by KoMa1978** [comment]
Same happens with only "Home" ... 

If you create a new contact in NC with a phone number for "Home", the type on the IOS device is "Home (with a leading "). After choosing a type on IOS 13 or if creating a new contact on the IOS 13 device, the "Home" phone number in NC will be "Choose type".

**Comment by skjnldsv** [comment]
Could you create a fake contact on iOS with lots of different entries (and various WORK, HOME, VOICE, FAX...) and paste it here?

**Comment by KoMa1978** [comment]
I think this is not really needed ... good examples are in this case and #942 is the same issue and https://github.com/mozilla-comm/ical.js/pull/388 as well ...

**Comment by skjnldsv** [comment]
Perfect then! Let's close this in favor of the others :)
Thanks for the help!

**Comment by helmut72** [comment]
Still the same with NC 18 and Contacts 3.1.8 from today.
