### ISSUE TITLE
Exporting Contacts via an occ terminal command

### ISSUE THREAD

**Issue by pdschandler** [nextcloud/contacts#1343]
Apologies is this is already a feature or possible somehow, I couldn't find anything in the docs.

**Is your feature request related to a problem? Please describe.**
When migrating or de-comissioning an old Nextcloud instance, it would be helpful to have a terminal-based way to export contacts in case GUI access is down.

**Describe the solution you'd like**
A terminal-based export command for `occ` that creates an entire backup of the contacts archive, in the same manner as the GUI.

**Additional context**
I'm currently at the tail-end of a migration, and I stupidly forgot to actually export the contacts from our old instance. I still have the old instance around in old Docker containers, but unfortunately spinning them back up in their old configuration isn't working anymore, probably because I stole the domain for the new instance. On paper my old instance should be accessible via a new domain I set up, but for some reason I'm just getting a 504 error from NGINX and I really don't feel like troubleshooting it. I do have command-line access to my instance though, so I'd be all set if Contacts had this feature.

**Comment by skjnldsv** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there a no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.
