### ISSUE TITLE
Too easy to delete contact

### ISSUE THREAD

**Issue by ralxxx** [nextcloud/contacts#1368]
**Is your feature request related to a problem? Please describe.**
Currently it is very easy to delete a contact from the web backend. - just by clicking on the trash can next to the contact name in the contact list. The risk is that contacts are deleted by mistake. 

**Describe the solution you'd like**
As it is rather the exception that a contact is being deleted from the contact list, I would prefer if a contact could be deleted only by clicking first on the contact itself and then on the three dots in the upper right corner (and finally confirming by deleting contact).

**Additional context**
![80_nextclouddeletecontact2](https://user-images.githubusercontent.com/36100882/71541936-4d60a500-2960-11ea-9581-a8b55b814d2b.jpg)

![80_nextclouddeletecontact](https://user-images.githubusercontent.com/36100882/70849647-d0263200-1e81-11ea-9f07-8f5c65fadca9.jpg)

There's a link to another issue raised earlier: https://github.com/nextcloud/server/issues/18181

**Comment by skjnldsv** [comment]
@jancborchardt shall we add a confirm? An undo (cc #637)? Both?
Add a separator?

**Comment by lfischer** [comment]
Hello,
I would prefer a mandatory confirmation as minimum.

**Comment by jancborchardt** [comment]
I agree that the trash action in the AppContentList is too much. It should only be in the 3-dot menu in the detail view.

This will already solve the biggest problem. Undo is a thing we should look into as well of course, but that’s separate.

**Comment by jancborchardt** [comment]
If someone wants to submit a pull request to fix this, the only thing to do is simply to delete the following lines which are for the delete action:

https://github.com/nextcloud/contacts/blob/master/src/components/ContactsList/ContactsListItem.vue#L30-L35

Marking this as good first issue :)

**Comment by skjnldsv** [comment]
> If someone wants to submit a pull request to fix this, the only thing to do is simply to delete the following lines which are for the delete action:

this one is about the delete from top right menu @jancborchardt I think :)
So deleting the undo entry will not make it easier to delete 
Also, it would make the undo action impossible

**Comment by jancborchardt** [comment]
> > If someone wants to submit a pull request to fix this, the only thing to do is simply to delete the following lines which are for the delete action:
> 
> this one is about the delete from top right menu @jancborchardt I think :)

No, @ralxxx said (emphasis mine) ;)

> Currently it is very easy to delete a contact from the web backend. - just by clicking on the **trash can next to the contact name in the contact list**.

Including the first screenshot of the circled trash cans. :)

**Comment by skjnldsv** [comment]
I bought new :eyeglasses: ! :see_no_evil: 
So we should remove the delete button from the list directly? Is it what you were trying to do with




> If someone wants to submit a pull request to fix this, the only thing to do is simply to delete the following lines which are for the delete action:
> 
> https://github.com/nextcloud/contacts/blob/4d3c86d3afa9e3a238506fdd85287cc55b6d275a/src/components/ContactsList/ContactsListItem.vue#L30-L35

**Comment by jancborchardt** [comment]
@skjnldsv exactly. :) I think this will be the simple fix. (The "Delete" action in the 3-dot menu of the detail view is totally fine, and not so easy to accidentally click.)

**Comment by skjnldsv** [comment]
Then it's also a matter of removing the delete method/logic and undo methods/logic in the contacts/src/components/ContactsList/ContactsListItem.vue component :)
Not just removing the undo but also the delete entries :+1:

**Comment by jancborchardt** [comment]
Pull request open at https://github.com/nextcloud/contacts/pull/1430 :)
