### ISSUE TITLE
Version in info.xml still 3.1.6

### ISSUE THREAD

**Issue by raimund-schluessler** [nextcloud/contacts#1388]
The version in https://github.com/nextcloud/contacts/blob/master/appinfo/info.xml#L14 is still 3.1.6 although 3.1.7 was released already.

**Comment by skjnldsv** [comment]
Fixed, we'll see with 3.1.8
https://github.com/nextcloud/contacts/commit/6ae45acf8b862afd5443c81cc2eca10d3a099b3f
Thanks :)
