### ISSUE TITLE
RELATED property incorrectly formatted - sync fails

### ISSUE THREAD

**Issue by olantrust** [nextcloud/contacts#1395]
ISSUE

Create a contact in Nextcloud Contacts add a 'related' field set, and enter a name or other free text:

E.g.
Mary J Blige
Sister: Theresa May

Using DavX, the related field will not sync to Android devices (and other systems) and will be lost.

Create the same field on an Android device, and the related field will correctly display on Nextcloud.

CAUSE:

https://tools.ietf.org/html/rfc6350#page-42
Specifies that the RELATED property can either contain a URI value or a TEXT value.
The default is URI. If a TEXT value is entered then it must be specified.

On Android when a free text value is entered in the RELATED field, it creates a vCard record like this:
RELATED;TYPE=sister;VALUE=TEXT:Theresa May

In Nextcloud contacts when a free text value is entered it creates a vCard record like this:
RELATED;TYPE=SISTER:Teresa May

In accordance with the RFC, since no TEXT value is declared, and since 'Teresa May' is not a valid URI, it is an error and is not synced.

SOLUTION
If free text is entered, specify 'VALUE=TEXT'

**Comment by olantrust** [comment]
Also there should be a picker for creating a URI link to a contact in the addressbook, #669 seems to relate to this.

**Comment by skjnldsv** [comment]
Closing in favour of #669

**Comment by olantrust** [comment]
This does not appear to be the same as #669 , @skjnldsv - could you consider reopening or explaining how that bug covers this one - in case I've missed something?
This current issue is a bug about data loss occurring in the current implementation when syncing from Nextcloud to Android (via DavX). The suggested replacement issue is a proposed enhancement to allow direct links between contacts ...
Many thanks

**Comment by skjnldsv** [comment]
#669 is because we force URL as default. Thus why is your issue appearing.
Despite the text you're entering, it is seen as an url (invalid sure, but parsed as is nonetheless)

Having a proper Picker to automatically fill the url and parse any free-typed text as, well, TEXT, is all in the other issue :)

**Comment by olantrust** [comment]
> #669 is because we force URL as default. Thus why is your issue appearing.
> Despite the text you're entering, it is seen as an url (invalid sure, but parsed as is nonetheless)
> 
> Having a proper Picker to automatically fill the url and parse any free-typed text as, well, TEXT, is all in the other issue :)

Thank you for explaining and addressing

**Comment by olantrust** [comment]
@skjnldsv Just reconsidering this, the bug described here does not seem to be fixed by #669, so it seems this bug should be reopened?

The RFC specifies that 'RELATED' can contain a URI *or* or a text value. Nextcloud does not sync if a text value is entered. That is a bug, and not one that appears to be resolved by #669 which appears to allow linking to another contact, not free text entry.
