### ISSUE TITLE
Move search field

### ISSUE THREAD

**Issue by Tarry91** [nextcloud/contacts#142]
I couldn't find any issue for this yet. I would love to have a basic search option to find a contact quickly.

It should be possible to search for text in:
first name,
last name,
email,
address,
maybe phone numbers

**Comment by Tarry91** [comment]
Ok apparently I am blind. There is a search option on the top right of the screen, next to the profile picture.

Maybe the search option can be moved to the top of the contact list? Similar to how it is done on the iPhone or Mac contact app.

**Comment by irgendwie** [comment]
The point is, that by design the search is only in the top right, which is consistent across all apps for Nextcloud. Additionally when pressing <kbd>Ctrl</kbd>+<kbd>F</kbd> the search field is automatically focused.
