### ISSUE TITLE
Restrict permissions on shared Addressbook

### ISSUE THREAD

**Issue by republicus** [nextcloud/contacts#1433]
**Is your feature request related to a problem? Please describe.**
I am trying to create a shared Address book to use with Nextcloud Maps.
First I have to create my own contact then add it to a shared address book.

This works to plot all of us on the map as intended. But everyone with share privileges to that address book also have read/write access to modify all contacts' details in that Address book.

**Describe the solution you'd like**
1) It would be nice to publish/share my Personal Info to groups/address books without having to create a new contact for myself.
2) Ability for contact to be member of multiple address books.
3) More importantly, though, that an Address book have multiple sharing options (compared to Files/Folders) so that an Addressbook can not be edited except by the author of the contact in that Address book. [Can create, but can NOT delete or change]

Update:
I am testing Nextcloud with a small group of trusted members, but already and by accident, a contact was removed from the shared Addressbook.

**Shared Addressbooks are to permissive for any sizable setup.**

Share permissions should be similar to system-wide share permissions.
![image](https://user-images.githubusercontent.com/47370709/73188829-72783d00-40f1-11ea-961c-1e34eb0cf950.png)

**Comment by guerby** [comment]
For an organization using nextcloud it would be nice to be able to share read-only address books. 

eg: we generate and update a detailed address book from our user database (LDAP + scripting on our side), share it (URL) with all members of the organization with read-only rights, then all users with an android phone with nextcloud + davx5 app have all the up to date contacts ready to use and no risk to edit/delete something by mistake.

davx5 offer the option to have the address book read-only but it is per device/user/adress book setting, it would be much safer to have it on nextcloud.

**Comment by skjnldsv** [comment]
@georgehrke any idea how hard it would be to implement this?
Do you have similar thing in calendar?

**Comment by georgehrke** [comment]
The problem here is that the CRUDS model is not part of Caldav/Carddav. While we might enforce it on the server, all clients out there only know read-only/read-write, leading to plenty of undefined behavior and bad user experience.

We have similar issues for WebDAV, but there > 99% of users are running our official desktop / mobile clients, who can show proper error messages and prevent you from performing these illegal actions.

**Comment by skjnldsv** [comment]
Right, so closing as wontfix :+1:

**Comment by guerby** [comment]
> The problem here is that the CRUDS model is not part of Caldav/Carddav. While we might enforce it on the server, all clients out there only know read-only/read-write, leading to plenty of undefined behavior and bad user experience.
> 
> We have similar issues for WebDAV, but there > 99% of users are running our official desktop / mobile clients, who can show proper error messages and prevent you from performing these illegal actions.

Mays be I miss something but is there a setting to allow a read-only URL for addressbook in nextcloud ?
