### ISSUE TITLE
No address books visible App is started

### ISSUE THREAD

**Issue by futzi190** [nextcloud/contacts#1435]
#634 # Expected behaviour
Update zu 17.0.2 /Contacts 3.1.8
Hello everyone, I don't see any address books in Nextcloud. The app is switched on. Below is the message: the import is deactivated because no address book is available
New address books do not appear either

### Server configuration
Synology Intel(R) Celeron(R) CPU J3355 @ 2.00GHz Intel(R) Celeron(R) CPU J3355 @ 2.00GHz (2 2 cores)

**Database:**
MariaDB 10
**Webserver**
Apache (2.4)
**PHP version:**
PHP (7.2)
**Nextcloud version:** (see Nextcloud admin page)
17.0.2
**Contacts version:** (see Nextcloud apps page)
3.1.8
**Updated from an older Nextcloud or fresh install:**
update from older Version
**Signing status:**
Admin
Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
occweb is available 7 login Telnet 
available
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no
#### Nextcloud log (data/nextcloud.log)
Doctrine\DBAL\Exception\InvalidFieldNameException: An exception occurred while executing 'SELECT `id`, `uri`, `lastmodified`, `etag`, `size`, `carddata`, `uid` FROM `oc_cards` WHERE `addressbookid` = ?' with params ["3"]: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'carddata' in 'field list'

Thanks for your help

**Comment by futzi190** [comment]
Problem solved, inserted a missing column "carddata" in the database

**Comment by skjnldsv** [comment]
That is supper weird.
No update should remove part of your database, especially since the contacts app do not touch the database at all.

Please make sure to check any previous logs so you can find out what happened. :)
