### ISSUE TITLE
Option for banking information (IBAN)

### ISSUE THREAD

**Issue by Martinius** [nextcloud/contacts#1436]
Hello,

I am a very happy user of the nextcloud contacts app. I was recently wondering if it is possible to store the banking information of a contact (e. g. the IBAN). It seems there is also a vCard standart for that: 

https://stackoverflow.com/questions/10045664/storing-bank-account-in-vcard-file

I think this would be a very usefull feature, since you might not want to ask people for their banking information all the time. Maybe I will try to implement this feature myself. But I don't know if I will find time to do so soon.

Best regards

**Comment by skjnldsv** [comment]
It doesn't seems to be a consensus on the value to use, we could indeed use `X-BANK-ACCOUNT-NUMBER` But it would only be visible on nextcloud contacts, so I'm not sure. From the past we always tried to refrain ourselves from implementing custom values as this is not unified across contacts managers :)

cc @jancborchardt

**Comment by jancborchardt** [comment]
@Martinius which value do other contact apps like iOS Contacts and Google Contacts use for this?

**Comment by Martinius** [comment]
> @Martinius which value do other contact apps like iOS Contacts and Google Contacts use for this?

@jancborchardt Neither Android nor iOS support this by default. Here is a list what is supported on Android and iOS:

https://developer.android.com/guide/topics/providers/contacts-provider

https://developer.apple.com/documentation/contacts/cnmutablecontact

If found a few custom apps on Android which support more vCard options, but I could not figure out if any of them support banking information. To be honest I am quite surprised how few options these default apps can handle.  I think the best thing I can do right now is to add a note with the banking information. This is supported by both iOS and Android.

Best regards

**Comment by skjnldsv** [comment]
> I think the best thing I can do right now is to add a note with the banking information. This is supported by both iOS and Android.

Unfortunately, I think you're right, this would be the easiest so far :/
