### ISSUE TITLE
No export button on NC10

### ISSUE THREAD

**Issue by Gomez** [nextcloud/contacts#144]
The export button in the settings is missing. The html code is there, if i remove the class 'ng-hide', the button apears and works.

I suspect https://github.com/nextcloud/contacts/blob/master/js/components/addressBook/addressBook_controller.js#L25. But need to look closer.

I updated to version 1.5.3 and have Nextcloud version":"9.1.4.1"

**Comment by tcitworld** [comment]
I have the same issue with both `9, 2, 0, 5` and `9, 0, 7, 1` versions.

**Comment by Gomez** [comment]
@skjnldsv Have you look at it? Just a update would be enough.

**Comment by tcitworld** [comment]
I resolved this by migrating to a new release and hardcoding the nextcloud version following the nextcloud numerotation and no longer the oc one.

**Comment by skjnldsv** [comment]
Yeah, we need a new version comparison function. No time for this yet, but this is a starter issue!

**Comment by tcitworld** [comment]
We could also just have a list of acceptable versions.

**Comment by jancborchardt** [comment]
Does this also happen with Nextcloud 11 and 12? If not we can close it.

**Comment by skjnldsv** [comment]
@jancborchardt if we set the app as being only compatible for NC11 and higher, we can remove the version comparison function and this issue become invalid. :)

**Comment by jancborchardt** [comment]
@karlitschek @MorrisJobke @LukasReschke @jospoortvliet @skjnldsv @irgendwie do you have any objections to setting the minimum required Nextcloud version for the Contacts app to 11?

**Comment by MorrisJobke** [comment]
> @karlitschek @MorrisJobke @LukasReschke @jospoortvliet @skjnldsv @irgendwie do you have any objections to setting the minimum required Nextcloud version for the Contacts app to 11?

I'm fine with that.
