### ISSUE TITLE
Since last Update today fields aren't saved anymore

### ISSUE THREAD

**Issue by Tux12Fun** [nextcloud/contacts#1443]
### Describe the bug
......
I add a field to the contact. After leaving the App the field isn't saved. If I add a new propertie the Input Boxes are shown twice.
......

**To Reproduce**
1. Go to contacts app
2. Search Contact
3. Click on Contact
4. Add a new Property like gender
5. The Property is shown twice. Once right once left.
6. Choose gender or edit the property value.
7. Jump to a other contact.
8. Leave the App -> goto Calendar.
9. Go Back and serach the Contact.
10. Property is missing (not saved)

**Expected behavior**
Property should be saved correctly

**Actual behavior**
Seams that save doesn't occur

**Screenshots**

### Server configuration

**Operating system**: Windows, Linux, MacOS...
Linux Raspi

**Web server:** Apache, Nginx...
Nginx

**Database:** MariaDB, MySQL, PostgreSQL... 
MySQL - MariaDB10

**PHP version:** 7.3

**Nextcloud version:** (see Nextcloud admin page)
17.0.2

**Contacts version:** (see Nextcloud apps page)
3.1.8

**Updated from an older Nextcloud or fresh install:**
updated

**Signing status:**
```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

**List of activated apps:**
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**Nextcloud configuration:**
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your instance's installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

### Client configuration
**Browser:**
Google Chrome 78.0.3904.108

**Operating system:**
Win 10

**CardDAV-clients:**

#### *Web server error log*
```
Insert your webserver log here
```

#### *data/nextcloud.log*
```
no log messages
```

#### Browser log
<details>
<summary>How to access your browser console (Click to expand)</summary>

# Chrome
- Press either CTRL + SHIFT + J to open the “console” tab of the Developer Tools.
- Alternative method:
    1. Press either CTRL + SHIFT + I or F12 to open the Developer Tools.
    2. Click the “console” tab.

# Safari
- Press CTRL + ALT + I to open the Web Inspector.
- See Chrome’s step 2. (Chrome and Safari have pretty much identical dev tools.)

# IE9
1. Press F12 to open the developer tools.
2. Click the “console” tab.

# Firefox
- Press CTRL + SHIFT + K to open the Web console (COMMAND + SHIFT + K on Macs).
- or, if Firebug is installed (recommended):
    1. Press F12 to open Firebug.
    2. Click on the “console” tab.

# Opera
1. Press CTRL + SHIFT + I to open Dragonfly.
2. Click on the “console” tab.
</details>

```
No error messages in web Console.
```

**Comment by CoudCoud** [comment]
I'm also affected by this bug.
I don't know if it's related, but since this update, when I try to import a .vcf file, the UI says it imported the contact, but it also says that this contact is defective ("contact défectueux" in French) and that I need to open a console in my web browser.

**Comment by skjnldsv** [comment]
I will need a screenshot of your network requests.
Before you do anything, still on the development tools, there is a tab called `network`. Click on it and then the xhr filter. Do your action and screenshot the network log like this:
![capture d ecran_2018-09-27_21-49-46](https://user-images.githubusercontent.com/14975046/46170857-43548000-c29f-11e8-9403-db72713dd9c1.png)

**Comment by CoudCoud** [comment]
Hello, here is a screenshot.
![Capture d’écran de 2020-02-10 14-06-50](https://user-images.githubusercontent.com/59912942/74152716-2b209f00-4c0f-11ea-9f41-af39ffd2613e.png)
I also tried to add a new contact, and I have the same problem as https://github.com/nextcloud/contacts/issues/1452

**Comment by jaller94** [comment]
Can we change the title to include the version number (likely 3.1.8)?
The statement of "last Update today" becomes outdated quickly and makes it harder to classify the ticket by reading it's name in the list of issues.

**Comment by tdoerschel** [comment]
Hi, it seems to be a duplicate to #1453
I added my info there

**Comment by skjnldsv** [comment]
Yep, seems like it! :)
Closing in favour of #1453, thanks for the help here!!
