### ISSUE TITLE
Contact title name field does not sync with "Name" propperty.

### ISSUE THREAD

**Issue by hialvaro** [nextcloud/contacts#1444]
### Describe the bug
If I have a "Name" propperty (Where I can add Prefix, Name, Additional names, surname...) if I change the main "Name" field (The one on the title that is displayed in big called "contact-fullname" in the HTML id) it does not reflect the change on the "Name" field from the "Name" propperty. Same thing happens vice-versa.

**To Reproduce**
1. Go to a contact to edit its propperties.
2. Go to "Add new propperty" and add the "Name" propperty.
3. Click on the Main field where the name is displayed in big letters to edit the name.
4. See that changes are not applied on the "Name propperty" field.

> Same is happening vice-versa.

**Expected behavior**
The name is changed on both "name" fields.

**Actual behavior**
Name is changed just on the actual field that is being changed and the other remains the same.

### Server configuration

**Operating system**:  Ubuntu

**Web server:** Apache

**Database:** MySQL 

**PHP version:** 7.3

**Nextcloud version:** 18.0.0

**Contacts version:** 3.1.8

**Updated from an older Nextcloud or fresh install:** No

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 

No errors have been found.
```

**List of activated apps:**
```
Enabled:
  - activity: 2.11.0
  - bruteforcesettings: 1.5.0
  - calendar: 2.0.1
  - carnet: 0.19.2
  - cloud_federation_api: 1.1.0
  - comments: 1.8.0
  - contacts: 3.1.8
  - dav: 1.14.0
  - federatedfilesharing: 1.8.0
  - files: 1.13.1
  - files_external: 1.9.0
  - files_pdfviewer: 1.7.0
  - files_rightclick: 0.15.2
  - files_sharing: 1.10.1
  - files_trashbin: 1.8.0
  - files_versions: 1.11.0
  - files_videoplayer: 1.7.0
  - logreader: 2.3.0
  - lookup_server_connector: 1.6.0
  - music: 0.12.1
  - nextcloud_announcements: 1.7.0
  - notifications: 2.6.0
  - oauth2: 1.6.0
  - password_policy: 1.8.0
  - photos: 1.0.0
  - privacy: 1.2.0
  - provisioning_api: 1.8.0
  - recommendations: 0.6.0
  - serverinfo: 1.8.0
  - settings: 1.0.0
  - sharebymail: 1.8.0
  - survey_client: 1.6.0
  - systemtags: 1.8.0
  - text: 2.0.0
  - theming: 1.9.0
  - twofactor_backupcodes: 1.7.0
  - updatenotification: 1.8.0
  - viewer: 1.2.0
  - workflowengine: 2.0.0
Disabled:
  - accessibility
  - admin_audit
  - encryption
  - federation
  - firstrunwizard
  - mail
  - onlyoffice
  - support
  - user_ldap

```

**Nextcloud configuration:**
```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.168.1.30"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "sqlite3",
        "version": "18.0.0.10",
        "overwrite.cli.url": "http:\/\/192.168.1.30\/nextcloud",
        "installed": true,
        "has_rebuilt_cache": true
    }
}

```

### Client configuration
**Browser:** Firefox

**Operating system:** Windows 10

**CardDAV-clients:** DAVx5

**Comment by skjnldsv** [comment]
Hi! Thanks for yourissue.
This is not the same field. This was done on purpose.
You can have a different contacts name than a detailed name
"Mom" => "Jenna Doe"

**Comment by pawlowskatze** [comment]
Hi,I'm aware that it's quite silly to comment on closed tickets but I put all my hope in this desperate attempt because it's almost the only ticket I found that deals with the symptom context of a problem I have.

I fully understand your decision to not "interlink" the contact TITLE with the contact name fields. But: How can I use that title field outside of Nextcloud?
For example, the contacts are nicely synched with my Android phone using Davx5. However, the "title" doesn't show up anywhere. Is there any (contact/dialer) app known or a hack/trick so that I can make my Android phone use the contact TITLE instead of the standard names fileds?

TIA, Thomas

**Comment by skjnldsv** [comment]
@pawlowskatze no worries! It's not *silly*, it's a valid question :)
There are other softwares that supports the title property, thunderbird, macos for example.
Unfortunately it seems that Android default doesn't support it, maybe you can find other contacts apps that do?
