### ISSUE TITLE
Unclear which format to use for social media profiles

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/contacts#1445]
In Contacts, for `x-socialprofile` the type `text` is forced, but in the info section it says `The url of the profile. e.g. https://www.facebook.com/Nextclouders/`. So should the type not be "uri"?

And then to make it easier, whenever you add a social property, we should prefill the start of the URL like `https://facebook.com/` and focus it after that.
This works even with federated systems like Mastodon, Diaspora and Nextcloud social as we can simply have a default URL like `https://joindiaspora.com/` and `https://mastodon.social/` and it can be adjusted then.

**Comment by skjnldsv** [comment]
Have you tried changing it to url?
Or is this issue only about the placeholder? :)

**Comment by call-me-matt** [comment]
I would say most people will input the usernames only. For twitter, it is quite common to use @twittername, for example. And when you see advertisements, normally you see a reference with facebook-logo plus the respective username. So I would not insist on putting an URL here. Also, it takes up a lot of space with redundant information to the type field, displayed just in front of it.

**Comment by skjnldsv** [comment]
Fixed with placeholders
