### ISSUE TITLE
Since 3.1.8 creating new contacts doesn't save properly

### ISSUE THREAD

**Issue by DBJRdev** [nextcloud/contacts#1452]
### Describe the bug
Creating a new contact does not work properly anymore. A spinner indicates the non-saved state. At a certain point the new contact is saved, but often data is lost.

**To Reproduce**
1. Create new contact, insert name of contact and start typing a phone number
2. Spinner keeps turning
3. Continue with other fields
4. Sometimes the contact seems saved, sometimes not

In the console you an see an "Error: dist.js:1:56302" is triggered.

**Expected behavior**
Creating new contact should make sure it's actually saved

**Actual behavior**
Sometimes saved, sometimes not.

### Server configuration

**Operating system**: Debian

**Web server:** Apache

**Database:** MySQL 5.7

**PHP version:** 7.3

**Nextcloud version:** 17.0.3, but was there on 17.0.2 as well

**Contacts version:** 3.1.8
It did not appear, to our knowledge, with version 3.1.6

**Updated from an older Nextcloud or fresh install:**
basic install was 17.0.0 

### Client configuration
**Browser:** Firefox on Ubuntu 19.10

**CardDAV-clients:**
Nextcloud web ui

#### Browser log
This contact did not have a proper uid. Setting a new one for  
Object { jCal: (3) […], addressbook: {…}, vCard: {…}, conflict: false }
contact.js:72:11
XHRPUThttps://***DOMAIN***.de/remote.php/dav/addressbooks/users/***USER***/kontakte/BBAE65B8-3DAB-4177-8786-7C7DC3A29F9C.vcf
[HTTP/2 201 Created 182ms]

XHRPROPFINDhttps://***DOMAIN***.de/remote.php/dav/addressbooks/users/***USER***/kontakte/BBAE65B8-3DAB-4177-8786-7C7DC3A29F9C.vcf
[HTTP/2 207 Multi-Status 63ms]

XHRPUThttps://***DOMAIN***.de/remote.php/dav/addressbooks/users/***USER***/kontakte/D19B3B02-042F-4DDE-B9A9-BCE7D31C2A19.vcf
[HTTP/2 400 Bad Request 86ms]

Error: dist.js:1:56302
XHRGEThttps://***DOMAIN***.de/ocs/v2.php/apps/notifications/api/v2/notifications
[HTTP/2 200 OK 93ms]

**Comment by pawlosck** [comment]
I have the same problem. When I want to fill "New contact" (contact name) field as first, contact is not saved. Contact is creted but fields are empty. I am using similar configuration.
Ubuntu 19.10 (client and server), nextcloud 18.0, contact app 3.1.8, firefox for ubuntu

**Comment by gabul1312** [comment]
Hello, same here !
Same error inside browser logs (Firefox 72.0.2) :
Error: dist.js:1:56302

OS: Ubuntu Server 18.04.4
Web server: Nginx 1.14.0
Database: MySQL 8.0.19
PHP version: 7.2.24
Nextcloud version: 18.0.0
Contacts version: 3.1.8

As a (annoying) workaround :
1) Create a new contact
2) Write just one letter in the "Contact name" field
3) Click on another contact in the address book
4) Go back to your new contact and now you can edit all what you want, and it'll be saved.

Really weird, any clue about this ?
Thanks a lot

**Comment by skerbis** [comment]
Same here in Nextcloud 17 and 18

**Comment by tdoerschel** [comment]
Hi, it seems to be a duplicate to #1453 
I added my info there

**Comment by DBJRdev** [comment]
Closed, because it's solved (see discussion at #1453 and following new release).
