### ISSUE TITLE
Double entries when adding new properties to contact

### ISSUE THREAD

**Issue by eibex** [nextcloud/contacts#1464]
### Describe the bug
When adding two same properties (e.g address, birthday) to a contact the data written in the new property box edits the contents of the one added beforehand. (e.g. two birthdays are added instead of one, and if you put 16 March 1970, the second birthday will show 16 March 1970 too). This does not happen if the page is refreshed after creating the first property.

Furthermore, when adding a new property two duplicate boxes (that share the contents and same bug as above) are created. You can delete one of the two just fine though.

**To Reproduce**
1. Go to Contacts
2. Click on any contact
3. Click on add a property
4. Select any property (and see that it will be duplicated)
5. Edit the content of a property (and see that the edits happen on both instances of the property if you didn't delete one)
6. Create a new property again of the same type without refreshing the page
7. Edit it (and the contents of the new property will overwrite the contents of the older one)

**Expected behavior**
No duplicates on property creation.
No content overwrites if I need to add the same properties (without CTRL+R / F5).

### Server configuration
**Operating system**: Ubuntu 18.04

**Web server:** Apache 2.4.41

**Database:** PostgreSQL

**PHP version:** 7.2

**Nextcloud version:** 17.0.3

**Contacts version:** 3.1.8

**Updated from an older Nextcloud or fresh install:** Updated to every single minor and major version of Nextcloud since Nextcloud 16 (always on stable channel).

**Signing status:**
```
No errors have been found.
```

**Comment by skjnldsv** [comment]
Fixed by https://github.com/nextcloud/nextcloud-vue/pull/844

**Comment by skjnldsv** [comment]
Fixed have been released as 1.3.1, waiting for update pull request

**Comment by skjnldsv** [comment]
Fix in https://github.com/nextcloud/contacts/pull/1465
