### ISSUE TITLE
remove leading and trailing white-spaces from contact entry fields

### ISSUE THREAD

**Issue by j-ed** [nextcloud/contacts#147]
## Expected behavior
The contacts app should remove leading and trailing white-spaces from contact entry fields before they're stored in the database.

## Current behavior
The contacts app is currently not removing leading and trailing white-spaces from contact entry fields which causes unexpected address book sorting results.
 
### Steps to reproduce
1. Open the contacts app
2. Enter e.g. a Name with leading white-spaces
3. Check the sorting of the address entries not only in the Contacts app but also e.g. in a hands-free car phone.

#### Server Configuration
OS: Linux 3.2.84
Web server: Apache2 2.4.25
Database: MariaDB 5.5.54
PHP version: 5.6.29
Nextcloud version: 11.0.1
Contacts app version: 1.5.3 

#### Client Configuration
Browser: Mozilla Firefox 51.0.1
Operating system: Windows 7

**Comment by irgendwie** [comment]
Why would one insert white-spaces in the first place? :smile:
We'll think about it!

**Comment by skjnldsv** [comment]
@irgendwie something to add in `validate`?

**Comment by irgendwie** [comment]
sounds good... maybe someone added whitespaces on purpose :man_shrugging:

**Comment by skjnldsv** [comment]
Duplicate https://github.com/nextcloud/contacts/issues/67

**Comment by skjnldsv** [comment]
Damn, wrong topic! Not duplicate, my bad! Too many tabs opened!

**Comment by sleepypioneer** [comment]
I have assigned myself to this and will work on it as one of the next PRs for Team Popcorn (RGSoC 2018)

**Comment by sleepypioneer** [comment]
Hi @skjnldsv and @irgendwie I have problems recreating this issue, I don't have a hands free car app but on the app it appears that trailing white spaces at least from the beginning are removed, is it possible this was fixed else where? Or perhaps I miss something, I am very new to this :) Thank you in advance!

**Comment by skjnldsv** [comment]
@sleepypioneer I can't reproduce either.  Seems to be fixed, maybe our update to the new vcard library.
Adding a space before, and/or after, and triggering a save send the proper data.
