### ISSUE TITLE
long adress book name > unsusable interface

### ISSUE THREAD

**Issue by alexanderdd** [nextcloud/contacts#1472]
**To Reproduce**
1. create addressbook with a name of 20 or more letters, share it with other user
1. other user wants to use three-dot icon of the shared addressbook

**Expected behavior**
addressbook name should be shortened automatically, three-dot menu should be at the end of the line

**Actual behavior**
threedot menu is moved to next line, interface not usable:
![Unbenannt](https://user-images.githubusercontent.com/28591861/74836522-d9b79480-531f-11ea-90e3-ee725e2a1f37.png)

### Server configuration
Operating system: Linux 4.15.0-60-generic #67-Ubuntu SMP Thu Aug 22 16:55:30 UTC 2019 x86_64

Webserver: nginx/1.14.0 (fpm-fcgi)

Database: mysql 5.7.27

PHP version: 7.2.24-0ubuntu0.18.04.1

Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, sodium, session, standard, cgi-fcgi, mysqlnd, PDO, xml, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, gmp, iconv, igbinary, imagick, imap, intl, json, exif, mysqli, pdo_mysql, Phar, posix, readline, redis, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache

Nextcloud version: 17.0.3 - 17.0.3.1

**Contacts version:**  3.1.8

**Comment by skjnldsv** [comment]
Easy fix: 

- [ ] add title so you can have full name on hover
