### ISSUE TITLE
Linting error in PropertyDateTime.vue

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/contacts#1484]
```
Cannot read property 'indexOf' of undefined
Occurred while linting …/contacts/src/components/Properties/PropertyDateTime.vue:166
```

**Comment by skjnldsv** [comment]
Yes I saw that, this is coming from the plugin it seems
https://github.com/benmosher/eslint-plugin-import/issues/1616

**Comment by georgehrke** [comment]
Bumping `eslint-plugin-node` to 11 fixed it for me in Calendar

**Comment by skjnldsv** [comment]
@georgehrke no peer conflicts? Are you using @nextcloud/eslint-config ?

**Comment by georgehrke** [comment]
I'm still on `eslint-plugin-Nextcloud`. I had to bump `eslint-plugin-node` manually, but nothing broke.

**Comment by skjnldsv** [comment]
That is why then :)
Let me see!

**Comment by skjnldsv** [comment]
@georgehrke same here https://github.com/nextcloud/photos/pull/218/files
But updating to eslint-plugin-node doesn't fix it :(
