### ISSUE TITLE
feat: Add custom properties/attributes to Contacts

### ISSUE THREAD

**Issue by ichtestemalwieder** [nextcloud/contacts#1486]
**Problem**: 
Almost every user will have the requirement to add custom attributes / properties to a vcard. But this seems curently to be not supported in the app. 

**Solution/Acceptance Criteria:** 
Having a config option, that allows to create custom properties
Custom properties should then be listed/selectebale in the contacts management/create screen when entering custom properties: 

![image](https://user-images.githubusercontent.com/54768881/75352452-0f252a80-58aa-11ea-864d-764507fe6819.png)

When searching for a solution, I came a cross lots of users also searching for a solution/requiring this feature.  Thanks!

**Comment by skjnldsv** [comment]
Hey :)
This have been suggested before, but any kind of custom properties would get ignored/discarded by all other vcard editors (mobile, desktop...) meaning it really only make sense to Nextcloud. This is something we do not wish and will just create extra work and make it harder to maintain in the long run.

I would suggest you use the `notes` property to fill an missing informations :wink:

**Comment by ichtestemalwieder** [comment]
@skjnldsv thanks for your answer. 

First of all it would absolutely be great to integreate your explanation into the offocial contacts docs. I have so many posts seen asking this and it is the first thing that every person interested in using nextcloud is asking this question. Everyone wants this feature and if it is not possible it should be prominently answered that it is not possible and why... 

Thanks

**Comment by skjnldsv** [comment]
@ichtestemalwieder agreed! It would help my management of issues here too :)
Let me see what I can find :)

**Comment by skjnldsv** [comment]
> ## Could you add XXX property?
> This is a complicated answer. We did not created the way contacts works. We are following the official vCard format. This format include a predefined set of properties that other applications/devices supports too. Adding a custom property would just make it compatible with Nextcloud and will not be understood by any other clients. Long story short, we suggest you use the Notes field to add your custom data :)

What do you think @ichtestemalwieder ?

**Comment by ichtestemalwieder** [comment]
@skjnldsv, thanks very much! Absolutely amazing and very helpfull!

(As described I always thought Contacts is a CRM Frontend and never thought about vcard).

**Comment by skjnldsv** [comment]
> (As described I always thought Contacts is a CRM Frontend and never thought about vcard).

This is both a bliss and a nightmare to work with ^^

**Comment by skjnldsv** [comment]
> @skjnldsv, thanks very much! Absolutely amazing and very helpfull!

Thanks for your help! It's awesome to have people like you here :hugs:

**Comment by MiMoHo** [comment]
**This is** not cosmetic but **an issue resulting in data loss inside the platform making Nextcloud Contacts appear unreliable 
when the user is not aware of the vCard limitation as demonstrated in #1969, #1997, #2039**. Hence, _wontfix_ is not an option.

[RFC 6350](https://datatracker.ietf.org/doc/html/rfc6350) does allow `x-` names, but only as "experimental" extensions that are "not intended for released products" and are "unlikely to interoperate". In other words: the standard itself already acknowledges that these fields are not the mainstream interoperability path, but it does not say user data should be dropped or rewritten.

If a user can enter and presumably save a value inside the Nextcloud frontend or in third-party applications, it is inacceptable that when refreshing or updating the contact in Nextcloud, it results in values dropped or silently normalized. Custom tags are entered for a good reason. Once a database starts discarding data that it previously accepted, it stops being a reliable source of trust.

Interoperability is important, but it should not outrank preservation of user-owned data. A field that Nextcloud does not understand should at minimum preserve losslessly as opaque data. Anything less creates silent data loss, which is far more damaging than an advanced field not showing in an unprogressive third-party app that Nextcloud has no influence on and reliability for. But once officially supported, other editors can follow.

**Nextcloud should demonstrate a feature-friendly approach by preserving and maintaining `x-` names as this is the behavior users expect from a contact manager and platform, especially one that positions itself around control over personal data.**

Please reopen the issue for fixing @skjnldsv
