### ISSUE TITLE
l10n: Understanding problem of string. Please provide some context

### ISSUE THREAD

**Issue by rakekniven** [nextcloud/contacts#1490]
https://github.com/nextcloud/contacts/blob/d4970976e0012e10ecae6529541f15be7e0d11f7/src/components/Settings/SettingsAddressbook.vue#L193

What does this mean?

Please provide explanation.

Reported at Transifex.

**Comment by skjnldsv** [comment]
That trying to enable/disable the addressbook failed :)

**Comment by skjnldsv** [comment]
We should clearly find a better wording ;)

**Comment by slsimic** [comment]
Suggestion
 Toggling of addressbook was not successful

**Comment by skjnldsv** [comment]
@rakekniven would that be ok for you?
@slsimic you can provide the change by editing https://github.com/nextcloud/contacts/blob/d4970976e0012e10ecae6529541f15be7e0d11f7/src/components/Settings/SettingsAddressbook.vue#L193

**Comment by rakekniven** [comment]
"Toggling of addressbook was not successful"

> Perfect.

**Comment by rakekniven** [comment]
Just for the records:

Reported at Transifex:
https://www.transifex.com/nextcloud/nextcloud/translate/#sr/contacts/154381751
