### ISSUE TITLE
Upgrade crashes the apps

### ISSUE THREAD

**Issue by GormCh** [nextcloud/contacts#1498]
Hi.
Using the button Upgrade Contacts and Calender results in error. The contact app disappear and and can not be loaded again. When trying to re-active the app following message pops up.
App "contacts" cannot be installed because appinfo file cannot be read.
If the app is deleted it can be re-installed.
Nextcloud 18
php 2.4

Is there a way to "manually install the apps?

Regards
Gorm

### Describe the bug
......
......

**To Reproduce**

**Expected behavior**
Tell us what you expected to happen.

**Actual behavior**
Tell us what happened instead.

**Screenshots**

### Server configuration

**Operating system**: Windows, Linux, MacOS...

**Web server:** Apache, Nginx...

**Database:** MariaDB, MySQL, PostgreSQL... 

**PHP version:** 7.0, 7.1, 7.2...

**Nextcloud version:** (see Nextcloud admin page)

**Contacts version:** (see Nextcloud apps page)

**Updated from an older Nextcloud or fresh install:**

**Signing status:**
```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

**List of activated apps:**
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**Nextcloud configuration:**
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your instance's installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

### Client configuration
**Browser:**
Firefox

**Operating system:**
Windows 10

**CardDAV-clients:**

#### *Web server error log*

```
Insert your webserver log here
```

#### *data/nextcloud.log*
```
Insert your Nextcloud log here
[nextcloud.log](https://github.com/nextcloud/contacts/files/4283630/nextcloud.log)

#### Browser log
<details>
<summary>How to access your browser console (Click to expand)</summary>

# Chrome
- Press either CTRL + SHIFT + J to open the “console” tab of the Developer Tools.
- Alternative method:
    1. Press either CTRL + SHIFT + I or F12 to open the Developer Tools.
    2. Click the “console” tab.

# Safari
- Press CTRL + ALT + I to open the Web Inspector.
- See Chrome’s step 2. (Chrome and Safari have pretty much identical dev tools.)

# IE9
1. Press F12 to open the developer tools.
2. Click the “console” tab.

# Firefox
- Press CTRL + SHIFT + K to open the Web console (COMMAND + SHIFT + K on Macs).
- or, if Firebug is installed (recommended):
    1. Press F12 to open Firebug.
    2. Click on the “console” tab.

# Opera
1. Press CTRL + SHIFT + I to open Dragonfly.
2. Click on the “console” tab.
</details>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by skjnldsv** [comment]
Hey :)
This seems more like a failure in your setup :)

Can you list the files in your apps folder?
And if there is the contacts app here, manually delete it?

**Comment by GormCh** [comment]
Hi there.
I managed to delete both the Contacts and the Calender app. The apps could then be uploaded and installed. There is nothing special in the setup. The only, perhaps not 100% a standard install, is that the data directory sits in a protected area behind the actual web address only accessible via the Absoluthe Path. That shouldn't cause an update error.

I'll keep an eye on this when a new update arrives.

Gorm

**Comment by skjnldsv** [comment]
Thanks for checking this :)
