### ISSUE TITLE
Compatibility with Android CyanogenMod 14

### ISSUE THREAD

**Issue by SIRSteiner** [nextcloud/contacts#15]
I did some changes to get a compatibility with my smartphone.
1. ..../js/public/script.js, tel options
   {id: 'HOME', name: t('contacts', 'Home')},
   {id: 'WORK', name: t('contacts', 'Work')},
   {id: 'CELL', name: t('contacts', 'Mobile')},
   {id: 'CELL,WORK', name: t('contacts', 'Mobile work')},
   {id: 'FAX', name: t('contacts', 'Fax')},
   {id: 'FAX,HOME', name: t('contacts', 'Fax home')},
   {id: 'FAX,WORK', name: t('contacts', 'Fax work')},
   {id: 'PAGER', name: t('contacts', 'Pager')},
   {id: 'VOICE', name: t('contacts', 'Voice')},
   {id: 'CAR', name: t('contacts', 'Car')},
   {id: '', name: t('contacts', 'Further')}
2. the correspondending translations
   "Home" : "Privat",
   "Work" : "Geschäftlich",
   "Mobile" : "Handy (privat)",
   "Mobile work" : "Handy (geschäftl.)",
   "Fax" : "Fax",
   "Fax home" : "Fax (privat)",
   "Fax work" : "Fax (geschäftl.)",
   "Pager" : "Pager",
   "Voice" : "Anruf",
   "Car" : "Auto",
   "Further" : "Sonstige",

I don't know if these options are default (standard) values.

**Comment by irgendwie** [comment]
I'm not sure, if I understand the problem here. Is the translation in{correct,accurate} for german language?
A few type-params for telephone are specified by the [RFC6350](https://tools.ietf.org/html/rfc6350#section-5.6).

**Comment by juliushaertl** [comment]
I think this is related to https://github.com/owncloud/contacts/issues/207

The mapping list is currently hardcoded at https://github.com/nextcloud/contacts/blob/master/js/services/vCardProperties.js#L113-L122 and options that are not part of the list will be displayed with empty label.

**Comment by riegercloud** [comment]
I have similar issues on iOS 10.1.1 and iPhone 5S:
(1) I created a new contact in nextcloud ui

![1](https://cloud.githubusercontent.com/assets/20593693/20065687/44d8eb3c-a50f-11e6-9865-3a4926d39a86.jpg)

(2) Sync with iPhone

![2](https://cloud.githubusercontent.com/assets/20593693/20065729/721a7804-a50f-11e6-9f64-a310249f6713.jpg)

The mis-spelling home,voice / work/voice appear

(3) edited the contact in iPhone: changed to Privat, Arbeit, Mobil

![3](https://cloud.githubusercontent.com/assets/20593693/20065753/8aa0d1c0-a50f-11e6-88ef-313a67ff97f0.jpg)

(4) Switched back to nextclouds ui

![4](https://cloud.githubusercontent.com/assets/20593693/20065997/64be491e-a510-11e6-8b55-3f7dde7a4213.jpg)

Cell, Voice will appear in nextcloud ui.

I am running nextcloud 10.0.1 stable, Contacts 1.4.0.0, nginx 1.11.5, mariaDB 10.0.27, php 7.0.12
Browser Edge and Firefox 49.0.2

Looking forward to your response, many thanks in advance,
Cheers, Carsten

**Comment by kangaroo72** [comment]
Dear SIRSteiner,

did I understand you right?? You solved the bug for yourself, editing a file?! Is this for me possible too?? Is it possible to integrate a "fixed" contacts app, alpha, beta or however as a workaround until it's fixed??
I urgent need working caldav, 'cause I want to drop Exchange ...

Thanks

**Comment by SIRSteiner** [comment]
Yes I solved it for me after editing script.js (and the translation file) and it works perfect for me with CyanogenMod 14.1

**Comment by kangaroo72** [comment]
Cool - maybe this works for me too?! Can  you provide me your scripts.js please - is this possbile??

Thanks a lot, Tom

**Comment by riegercloud** [comment]
i updated to the current contact app (apps.nextcloud.com) v. 1.5.2 but the behaviour ist still the same:
Instead of the german words "Arbeit" or "Privat" again "Work, Voice" and "Privat, Voice are shown:

![grafik](https://cloud.githubusercontent.com/assets/20593693/20803307/ffcbe6c8-b7ee-11e6-9ea8-da7555090c96.png)

... related to: https://github.com/nextcloud/contacts/issues/32 ?

**Comment by riegercloud** [comment]
hi guys, any progress?

**Comment by skjnldsv** [comment]
Duplicate #32 
Let's focus on the same issue here.
