### ISSUE TITLE
Save icon is invisible

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/contacts#1502]
### Describe the bug
The save icon is invisible

**To Reproduce**
1. Go to our instance
2. Open a contact with broken data

**Expected behavior**
See save icon

**Actual behavior**
See nothing

**Screenshots**
![Bildschirmfoto von 2020-03-05 10-55-53](https://user-images.githubusercontent.com/1374172/75970033-1367ce00-5ed0-11ea-8b23-141e5f530ded.png)

### Server configuration
**Nextcloud version:**

18

**Comment by skjnldsv** [comment]
Can't reproduce, can you?

**Comment by ChristophWurst** [comment]
![Bildschirmfoto von 2020-04-27 09-29-14](https://user-images.githubusercontent.com/1374172/80345575-9884b900-8869-11ea-99d5-74116839c519.png)

yes

**Comment by skjnldsv** [comment]
Fix with new header white background 
![Capture d’écran_2020-09-06_12-13-50](https://user-images.githubusercontent.com/14975046/92323622-73cff780-f03a-11ea-97ba-e9c512cbc821.png)
