### ISSUE TITLE
Multiple Anniversary Fields

### ISSUE THREAD

**Issue by grandeljay** [nextcloud/contacts#1505]
**Is your feature request related to a problem? Please describe.**
Currently only 1 Anniversary Field per Contact can be set.

**Describe the solution you'd like**
I would like to add multiple anniversaries to contacts. Here are some examples:

- Beginning of the relationship
- Legal Marriage/Wedding
- Christian/Church Wedding
- Other Milestones important for some people/couples (First Joint Apartment, etc.)

**Describe alternatives you've considered**
I do not know of an alternative for the contacts app.

**Additional context**

**Comment by skjnldsv** [comment]
Hey !
Unfortunately this is not up to us :(
https://tools.ietf.org/html/rfc6350#section-6.2.6

See the cardinality: `*1` => https://tools.ietf.org/html/rfc6350#page-8
