### ISSUE TITLE
Sorting of names is sometimes "last, first", sometimes "first last"

### ISSUE THREAD

**Issue by Luto73** [nextcloud/contacts#151]
### Steps to reproduce
1. Create a new contact entry
2. If you do nothing the sorting is "firstname lastname"
3. If you add "detailed name" information the sorting changes to "lastname, firstname"

### Expected behaviour
Sorting should be consistent either "lastname, firstname" (preferred by me) or "firstname lastname"

### Actual behaviour
Sorting seems to be chaotically

### Server configuration
**Operating system**: Debian Wheezy

**Web server:** Apache 2.2

**Database:** MySQL 5.5

**PHP version:** 7.0.15

**Nextcloud version:** 11.0.2

**Contacts version:** 1.5.3

**Updated from an older Nextcloud or fresh install:** Update
**Signing status:** No errors have been found.

**List of activated apps:**

Enabled:
  - activity: 2.4.1
  - admin_audit: 1.1.0
  - bookmarks: 0.9.1
  - calendar: 1.5.1
  - comments: 1.1.0
  - contacts: 1.5.3
  - dav: 1.1.1
  - encryption: 1.4.1
  - federatedfilesharing: 1.1.1
  - files: 1.6.1
  - files_accesscontrol: 1.1.2
  - files_pdfviewer: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - mail: 0.6.2
  - nextcloud_announcements: 1.0
  - notes: 2.2.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - tasks: 0.9.5
  - templateeditor: 0.2
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - updatenotification: 1.1.1
  - workflowengine: 1.1.1
Disabled:
  - external
  - federation
  - files_automatedtagging
  - files_downloadactivity
  - files_external
  - files_retention
  - twofactor_totp
  - user_external
  - user_ldap
  - user_saml

**The content of config/config.php:**

{
    "system": {
        "instanceid": "1234567",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "trusted.domain"
        ],
        "datadirectory": "\/var\/local\/nextcloud-data",
        "dbtype": "mysql",
        "version": "11.0.2.7",
        "installed": true,
        "forcessl": true,
        "enable_previews": true,
        "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
        "maintenance": false,
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "nextcloud",
        "mail_smtpmode": "php",
        "mail_domain": "xxx.yyy",
        "mail_smtpauthtype": "PLAIN",
        "mail_smtpauth": 1,
        "mail_smtpsecure": "tls",
        "theme": "",
        "loglevel": 2,
        "secret": "***REMOVED SENSITIVE VALUE***",
        "overwritewebroot": "\/nextcloud",
        "overwrite.cli.url": "\/nextcloud",
        "trashbin_retention_obligation": "auto",
        "filelocking.enabled": "true",
        "updatechecker": true,
        "htaccess.RewriteBase": "\/nextcloud",
        "updater.release.channel": "stable",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379
        },
        "memcache.locking": "\\OC\\Memcache\\Redis"
    }
}

**Are you using external storage: no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Opera 43.0

**Operating system:** Windows 10 Pro

**CardDAV-clients:** Web-Interface

**Comment by irgendwie** [comment]
Sorting is done via the displayname - nonetheless with the next version of contacts a basic sort by feature is integrated.

**Comment by skjnldsv** [comment]
@irgendwie I think what @Luto73 is saying, is that adding a detailed name for a contact changes the sorting of this contact without respecting the sort dropdown option selection.

@Luto73 ?

**Comment by Luto73** [comment]
@skjnldsv I must admit I did not know that I can select the sorting order because I do not see where this option is hidden. But you got me right with your interpretation that adding a detailed name changes sort order.

**Comment by irgendwie** [comment]
@Luto73 the sort feature isn't integrated in 1.5.3 but will come with 1.5.4.
ref https://github.com/nextcloud/contacts/pull/121

**Comment by skjnldsv** [comment]
@irgendwie Oups! :p

**Comment by skjnldsv** [comment]
Fixed with latest 2.0.1
