### ISSUE TITLE
Add support for SIP numbers

### ISSUE THREAD

**Issue by schaarsc** [nextcloud/contacts#1511]
### Steps to reproduce
1. in Android-contacts-app add SIP number to contact
2. sync with Nextcloud

There is no field type for SIP-Nr in NC-contacts. To be able to use the Android build-in SIP-client, the "normal" telephone field cannot be used. The build-in SIP-client takes the number from a separate field.

### Expected behaviour
SIP number is listed as "Instant messaging" number

### Actual behaviour
SIP type should be a type of telephone number, not instant messaging.

### Server configuration

**Nextcloud version:** (see Nextcloud admin page)
18

**Comment by skjnldsv** [comment]
Can you post a vcard example please? :)

**Comment by schaarsc** [comment]
it turned out that Android stores the SIP number in IMPP...

> BEGIN:VCARD
> VERSION:3.0
> FN:Test Test2
> N:Test;Test2;;;
> IMPP:sip:1234567
> IMPP:sip:0999999
> REV:20200309T210750Z
> END:VCARD

Since it is stored in the IMPP field I'd not change the GUI beyond the drop down list item and include SIP in addition to IRC, XMPP, etc.

**Comment by skjnldsv** [comment]
Seems fair to me! :)

**Comment by skjnldsv** [comment]
Implemented with #1512, but there is https://github.com/nextcloud/contacts/issues/1396 in the way

**Comment by schaarsc** [comment]
@skjnldsv, excellent. Thank you!

**Comment by Saphar** [comment]
I am syncing my contacts with DAVx5 and Nexcloud Contacts. Then I have Linphone Android for SIP calls. Seems that Android interprets differently the contact format. If I add a SIP address from Linphone I get in the vcf file this field:
X-SIP:4271@sipdomain.ltd
If I add the SIP account and XMPP accounts on Nextcloud, they are not visible in the contacts on Android, neither in Linphone app.
