### ISSUE TITLE
Contact picture not changeable / removable

### ISSUE THREAD

**Issue by Bodenseematze** [nextcloud/contacts#1513]
### Describe the bug

If a contact does not have a picture, the contacts app allows to set one (e.g. by uploading a picture from the PC).
But if a contact already has a picture, there is no way to change or remove it.

......
......

**To Reproduce**
1. Open contacts app
2. Click on a contact without picture
3. Click on the empty place where the picture normally is - a dialog opened with "upload a new picture" and "coose from files"
4. Add a picture to that contact - you'll see the picture of the contact instead the empty place
5. If you now click on that "round circle" with the picture, the picture opens "big" - but there's no dialog popping up - neither at the small "round circle picture" nor at the "big picture".

**Expected behavior**

The dialog to choose another picture or to remove the existing picture should be available.

**Actual behavior**

No dialog is available after a picture has been added.

### Server configuration

**Operating system**: Linux

**Web server:** Apache, Nginx...

**Database:** MariaDB

**PHP version:** 7.3

**Nextcloud version:** 17.0.3

**Contacts version:** 3.2.0

**Updated from an older Nextcloud or fresh install:** updated

Tested with Firefox 73.0.1

**Comment by skjnldsv** [comment]
Hey! Have you check the top right corner of the image?

**Comment by Bodenseematze** [comment]
Youd mean the "big picture"?

I rechecked - there's nothing happening - neither at the "big picture" nor on the "circle picture"...

**Comment by skjnldsv** [comment]
![Capture d’écran_2020-03-11_15-23-15](https://user-images.githubusercontent.com/14975046/76427146-3e5c9100-63ac-11ea-857f-658f8fa44fdf.png)

**Comment by Bodenseematze** [comment]
Contact without pic:
![Contacts_NewContact01](https://user-images.githubusercontent.com/13251886/76503520-f9813a80-643d-11ea-8fc1-1ce668195064.jpg)

![Contacts_NewContact02](https://user-images.githubusercontent.com/13251886/76503559-02720c00-643e-11ea-83f0-6142d62016c0.jpg)

Contact with pic:
![Contacts_ContactWithPic01](https://user-images.githubusercontent.com/13251886/76503613-0c940a80-643e-11ea-8bfe-86fbf31277b9.jpg)

![Contacts_ContactWithPic02](https://user-images.githubusercontent.com/13251886/76503625-11f15500-643e-11ea-91a4-f87bf3795b55.jpg)

**Comment by skjnldsv** [comment]
Try moving your mouse? :p
Next upcoming version removes the fade out delay

**Comment by call-me-matt** [comment]
I searched for that, too - its a little tricky:
When a contact has an image, the originally overlayed menu is moved downwards (seems like an error to me):
![grafik](https://user-images.githubusercontent.com/34400929/78838539-aecfef80-79f6-11ea-84a6-745793ed8639.png)

Additionally, there is another well hidden menu that only shows when you click on the picture. You find it in the very top right corner of the window as shown above (https://github.com/nextcloud/contacts/issues/1513#issuecomment-597663766) 

Hope that helped.

**Comment by skjnldsv** [comment]
> When a contact has an image, the originally overlayed menu is moved downwards (seems like an error to me):

That's on purpose.
Clicking the image is by default. Once you're in the image there is a menu in the top riight. It used to fade out like the viewer with images, but we disabled it in latests releases, it was not discoverable then :)
