### ISSUE TITLE
Mistakenly renders "TYPE=VOICE" the same as 'TYPE="HOME,VOICE"'

### ISSUE THREAD

**Issue by rugk** [nextcloud/contacts#1521]
### Describe the bug
If you change a phone number to "Anruf" (German word for "call"), it get's directly changed back to "Privat" ("private").

I want to change this for phone numbers that belong to companies/institutions and thus can never be private, but also are not really a "work" number, as of course a company only has a work number.
Best examples are emergency numbers like 112. You can neither say it is "work" nor "private", it's just a "call number". And so I try to choose this entry in the dropdown there.

**To Reproduce**
1. Edit a contact.
2. Change the entered phone number category to "call".
3, Let it save. (until circle ends spinning)
4. Switch to another contact, switch back.

**Expected behavior**
It shows you "private" again. (the old category)

**Actual behavior**
It should save this as "call".

Note that it _does_ work if I change it to other values, like "work" or so, I could only see this bug for the German "Anruf".

**Screenshots**
![call](https://user-images.githubusercontent.com/11966684/77008492-89574500-6966-11ea-8d36-26769fd354e3.png)

### Server configuration

**Operating system**: Linux

**Web server:**  nginx...

**Database:** MySQL 

**PHP version:** 7.0

**Nextcloud version:** 15.0.14.1

**Contacts version:** 3.1.6

**Updated from an older Nextcloud or fresh install:** fresh

### Client configuration
**Browser:** Firefox 74

**Operating system:** Linux/Fedora

#### *data/nextcloud.log*
looked into, nothing related

**Comment by rugk** [comment]
BTW [this is the vcf file that gets changed](https://gist.github.com/rugk/817048d3a43be5711647ce611993bbe3/revisions#diff-54679015a7029b8e47df67f5c16e4b8bL7) and [this is the final result](https://gist.github.com/rugk/817048d3a43be5711647ce611993bbe3/02c6183e380542f5c20342fea922e06f8ccd019c).

Note how it changes this:
```diff
-TEL;TYPE="HOME,VOICE":116 116
+TEL;TYPE=VOICE:116 116
```

Thus, I guess this is just a rendering bug. (and the data is actually changed)
In my local phone app [SimpleContacts](https://github.com/SimpleMobileTools/Simple-Contacts/) that gets then rendered as "miscellaneous" (German "Sonstiges"), which is quite fine IMHO.
Though when does the Nextcloud contacts app call it "Anruf", mhh?

**Comment by skjnldsv** [comment]
Hey! Thanks for your feedback :)
We use the same as what Android and iOS uses.
This is why those contacts are most used for, so we comply here.

https://github.com/nextcloud/contacts/blob/b7fc96f7f8a1e3c5ef9c785814c21240815328da/src/models/rfcProps.js#L191
https://github.com/nextcloud/contacts/issues/32#issuecomment-269648038
