### ISSUE TITLE
Unable to edit contact

### ISSUE THREAD

**Issue by creywood** [nextcloud/contacts#1547]
Sorry for the generic title, and I think this is going to be some type of deployment issue, but maybe you can point me the right direction.

### Describe the bug

I've been having some issues saving contacts on my Nextcloud instance for a while. I was previously seeing the issue running Nextcloud v15 (unsure Contact app version) and am now running v18 with Contacts v3.2.0 and the issue remains. When I try to edit (eg. the phone number) for a contact the spinner appears but the change doesn't get saved. I'm running Nextcloud on a yunohost server and in the Javascript error console I'm seeing some SSO errors but all other Nextcloud apps are working without issues. When I modify the field contents I see the Javascript error `TypeError: t.replace is not a function` and the network is not hit. `t.replace` in this case appears to be within a RFC6868 parsing function.

I use DAVx5 to sync with Android and have no issue editing contacts there (which are successfully synced).

As a result of DAVx5 working and the network not getting hit I believe the problem is possibly in the Contacts app part of the stack (or the deployment/configuration of it).

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to a contact
2. Edit a field, eg. a name field or phone number
3. See spinner start and never resolve
4. Reload contact and see field not updated

### Server configuration

**Operating system**: Yunohost on Debian Stretch

**Web server:** Nginx

**Database:** MariaDB (I believe.. dbtype is mysql but Maria server is installed)

**PHP version:** 7.3 (but was seen with earlier version)

**Nextcloud version:** Seen on v15 through v18.0.2.2

**Contacts version:** Seen on v3.2.0 and (I believe) earlier versions

**Updated from an older Nextcloud or fresh install:** Updated from v15 (but was seeing on v15 too)

**List of activated apps:**
```
> select appid from oc_appconfig where configKey='enabled' and configValue='yes';
+-------------------------+
| appid                   |
+-------------------------+
| accessibility           |
| activity                |
| calendar                |
| cloud_federation_api    |
| comments                |
| contacts                |
| dav                     |
| deck                    |
| federatedfilesharing    |
| federation              |
| files                   |
| files_external          |
| files_pdfviewer         |
| files_rightclick        |
| files_sharing           |
| files_trashbin          |
| files_versions          |
| files_videoplayer       |
| firstrunwizard          |
| logreader               |
| lookup_server_connector |
| maps                    |
| nextcloud_announcements |
| notes                   |
| notifications           |
| oauth2                  |
| onlyoffice              |
| password_policy         |
| photos                  |
| privacy                 |
| provisioning_api        |
| recommendations         |
| serverinfo              |
| settings                |
| sharebymail             |
| support                 |
| survey_client           |
| systemtags              |
| tasks                   |
| text                    |
| theming                 |
| twofactor_backupcodes   |
| updatenotification      |
| user_ldap               |
| viewer                  |
| workflowengine          |
+-------------------------+
```

### Client configuration
**Browser:** Firefox v74, also seen on earlier versions

**Operating system:** Linux

**CardDAV-clients:** DAVx5

**Comment by skjnldsv** [comment]
Sorry for the delay
I will need a screenshot of your network requests.
Before you do anything, still on the development tools, there is a tab called `network`. Click on it and then the xhr filter. Do your action and screenshot the network log like this:
![capture d ecran_2018-09-27_21-49-46](https://user-images.githubusercontent.com/14975046/46170857-43548000-c29f-11e8-9403-db72713dd9c1.png)

**Comment by creywood** [comment]
That's a nice little blast from the past! In good news I'm no longer unable to reproduce this (with Contacts 3.3.0, Nextcloud 18.0.5). Closing the issue.
