### ISSUE TITLE
Adding a contact when group is selected creates new groups

### ISSUE THREAD

**Issue by Luto73** [nextcloud/contacts#156]
When a contact group is selected and you add a contact the new contact gets the group name set to serveral the single letters the group name consists of. For example: if you select the group "Coworkers" and add a new contact this contact will be placed in the groups "C", "o", "w", ".", "r", "k", "e", ".", "s". (see screenshot)
![nextcloud-contacts-bug](https://cloud.githubusercontent.com/assets/26164833/23679813/5c67b02a-0389-11e7-928e-44cb6fa4addc.PNG)

### Steps to reproduce
1. select a group within the contacts app
2. add a new contact
3.

### Expected behaviour
The member group should not be split up in single letters. Instead the new contact should be member of the selected group.

### Actual behaviour
Instead the group name is split up into single letters and these "groups" are assigned to the new contact.

### Server configuration
**Operating system**: Debian Wheezy

**Web server:** Apache 2.2

**Database:** MySQL 5.5

**PHP version:** 7.0.15

**Nextcloud version:** 11.0.2

**Contacts version:** 1.5.3

**Updated from an older Nextcloud or fresh install:** Update
**Signing status:** No errors have been found.

**List of activated apps:**

Enabled:
  - activity: 2.4.1
  - admin_audit: 1.1.0
  - bookmarks: 0.9.1
  - calendar: 1.5.1
  - comments: 1.1.0
  - contacts: 1.5.3
  - dav: 1.1.1
  - encryption: 1.4.1
  - federatedfilesharing: 1.1.1
  - files: 1.6.1
  - files_accesscontrol: 1.1.2
  - files_pdfviewer: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - mail: 0.6.2
  - nextcloud_announcements: 1.0
  - notes: 2.2.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - tasks: 0.9.5
  - templateeditor: 0.2
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - updatenotification: 1.1.1
  - workflowengine: 1.1.1
Disabled:
  - external
  - federation
  - files_automatedtagging
  - files_downloadactivity
  - files_external
  - files_retention
  - twofactor_totp
  - user_external
  - user_ldap
  - user_saml

**The content of config/config.php:**

{
    "system": {
        "instanceid": "1234567",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "trusted.domain"
        ],
        "datadirectory": "\/var\/local\/nextcloud-data",
        "dbtype": "mysql",
        "version": "11.0.2.7",
        "installed": true,
        "forcessl": true,
        "enable_previews": true,
        "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
        "maintenance": false,
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "nextcloud",
        "mail_smtpmode": "php",
        "mail_domain": "xxx.yyy",
        "mail_smtpauthtype": "PLAIN",
        "mail_smtpauth": 1,
        "mail_smtpsecure": "tls",
        "theme": "",
        "loglevel": 2,
        "secret": "***REMOVED SENSITIVE VALUE***",
        "overwritewebroot": "\/nextcloud",
        "overwrite.cli.url": "\/nextcloud",
        "trashbin_retention_obligation": "auto",
        "filelocking.enabled": "true",
        "updatechecker": true,
        "htaccess.RewriteBase": "\/nextcloud",
        "updater.release.channel": "stable",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379
        },
        "memcache.locking": "\\OC\\Memcache\\Redis"
    }
}

**Are you using external storage: no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Opera 43.0

**Operating system:** Windows 10 Pro

**CardDAV-clients:** Web-Interface

**Comment by irgendwie** [comment]
@skjnldsv how did we miss this? :man_facepalming:

**Comment by Matttter** [comment]
Can confirm, I have this too. Would be nice to see a fix, although it's not something I would put a high priority on
