### ISSUE TITLE
[19 Beta1] - broken

### ISSUE THREAD

**Issue by Dragon988** [nextcloud/contacts#1560]
Hi there,

I'm sure you're already aware but if not contacts is broken in Nextcloud 19 Beta 1. It gets stuck in a constant loading loop.

I'm not sure if this is the right place to report beta bugs and I don't know what the developers actually need to troubleshoot beta bugs so if you can point me in the right direction, thanks!

![firefox_HxFnHg11JW](https://user-images.githubusercontent.com/7935624/78454084-aec49e00-764a-11ea-96f0-b82fcadefe32.png)

Errors below:

`"reqId":"yku2TNTYEILS0JDz9z4o","level":0,"time":"2020-04-04T14:58:34+00:00","remoteAddr":"ip
![firefox_HxFnHg11JW]
","user":"paradox","app":"serverDI","method":"GET","url":"/apps/contacts/All%20contacts","message":"The requested alias \"PreviewManager\" is depreacted. Please request \"OCP\\IPreview\" directly. This alias will be removed in a future Nextcloud version.","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:74.0) Gecko/20100101 Firefox/74.0","version":"19.0.0.2"}
{"reqId":"yKxtwzC9MfJJnCEeghZN","level":0,"time":"2020-04-04T14:58:34+00:00","remoteAddr":"ip","user":"paradox","app":"serverDI","method":"GET","url":"/apps/accessibility/js/accessibility?v=0","message":"The requested alias \"PreviewManager\" is depreacted. Please request \"OCP\\IPreview\" directly. This alias will be removed in a future Nextcloud version.","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:74.0) Gecko/20100101 Firefox/74.0","version":"19.0.0.2"}
{"reqId":"ZRifptRw36WGnu9BwSn5","level":0,"time":"2020-04-04T14:58:34+00:00","remoteAddr":"ip","user":"paradox","app":"serverDI","method":"GET","url":"/avatar/paradox/64?v=1","message":"The requested alias \"PreviewManager\" is depreacted. Please request \"OCP\\IPreview\" directly. This alias will be removed in a future Nextcloud version.","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:74.0) Gecko/20100101 Firefox/74.0","version":"19.0.0.2"}
{"reqId":"IOOpLfT6lV7N0dfKFXAL","level":0,"time":"2020-04-04T14:58:34+00:00","remoteAddr":"ip","user":"paradox","app":"serverDI","method":"GET","url":"/ocs/v2.php/apps/notifications/api/v2/notifications","message":"The requested alias \"PreviewManager\" is depreacted. Please request \"OCP\\IPreview\" directly. This alias will be removed in a future Nextcloud version.","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:74.0) Gecko/20100101 Firefox/74.0","version":"19.0.0.2"}
{"reqId":"0Vqd0WSoOqgwq9YqY3q7","level":0,"time":"2020-04-04T14:58:35+00:00","remoteAddr":"ip","user":"paradox","app":"serverDI","method":"PROPFIND","url":"/remote.php/dav/","message":"The requested alias \"PreviewManager\" is depreacted. Please request \"OCP\\IPreview\" directly. This alias will be removed in a future Nextcloud version.","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:74.0) Gecko/20100101 Firefox/74.0","version":"19.0.0.2"}
{"reqId":"z8zayqYuZL1lwNBiUAOw","level":0,"time":"2020-04-04T14:58:35+00:00","remoteAddr":"ip","user":"paradox","app":"serverDI","method":"PROPFIND","url":"/remote.php/dav/principals/users/paradox/","message":"The requested alias \"PreviewManager\" is depreacted. Please request \"OCP\\IPreview\" directly. This alias will be removed in a future Nextcloud version.","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:74.0) Gecko/20100101 Firefox/74.0","version":"19.0.0.2"}
{"reqId":"nqhZ5Ttwp0zgulMRaNrQ","level":0,"time":"2020-04-04T14:58:35+00:00","remoteAddr":"ip","user":"paradox","app":"serverDI","method":"PROPFIND","url":"/remote.php/dav/addressbooks/users/paradox/","message":"The requested alias \"PreviewManager\" is depreacted. Please request \"OCP\\IPreview\" directly. This alias will be removed in a future Nextcloud version.","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:74.0) Gecko/20100101 Firefox/74.0","version":"19.0.0.2"}
`

**Comment by skjnldsv** [comment]
Hey!
Thanks for checking this!
What version of Contacts did you use for this? We did not released a 19 version yet :thinking: :)

**Comment by Dragon988** [comment]
Yeah I'm early to the party. The contacts app is 3.2.0. There is/was a public 19 beta1 download on the nextcloud website.

Like I said, you're probably aware of the bug. Just trying to be helpful. :)

**Comment by Dragon988** [comment]
Speaking of the beta I'm pretty impressed with the lack of bugs in it. Looking forward to beta 2.

**Comment by skjnldsv** [comment]
> Speaking of the beta I'm pretty impressed with the lack of bugs in it. Looking forward to beta 2.

That's super great to hear :)


> Like I said, you're probably aware of the bug. Just trying to be helpful. :)

Actually I'm not sure. I fixed an important bug on contacts (I just pushed the fix) but did not releases. It might be this. But I don't see the output I was expecting in the console :thinking: 

Mind to test this release?
[contacts.tar.gz](https://github.com/nextcloud/contacts/files/4431781/contacts.tar.gz)

**Comment by Dragon988** [comment]
> 
> 
> > Speaking of the beta I'm pretty impressed with the lack of bugs in it. Looking forward to beta 2.
> 
> That's super great to hear :)
> 
> > Like I said, you're probably aware of the bug. Just trying to be helpful. :)
> 
> Actually I'm not sure. I fixed an important bug on contacts (I just pushed the fix) but did not releases. It might be this. But I don't see the output I was expecting in the console 🤔
> 
> Mind to test this release?
> [contacts.tar.gz](https://github.com/nextcloud/contacts/files/4431781/contacts.tar.gz)

With that release there were some issues on the initial load but reloading the page fixed it. Might have just been my browser cache.

Thanks! 👍

**Comment by skjnldsv** [comment]
Awesome! Closing then! Thanks for your help!! Stay safe!

**Comment by ostasevych** [comment]
> > > Speaking of the beta I'm pretty impressed with the lack of bugs in it. Looking forward to beta 2.
> > 
> > 
> > That's super great to hear :)
> > > Like I said, you're probably aware of the bug. Just trying to be helpful. :)
> > 
> > 
> > Actually I'm not sure. I fixed an important bug on contacts (I just pushed the fix) but did not releases. It might be this. But I don't see the output I was expecting in the console 🤔
> > Mind to test this release?
> > [contacts.tar.gz](https://github.com/nextcloud/contacts/files/4431781/contacts.tar.gz)
> 
> With that release there were some issues on the initial load but reloading the page fixed it. Might have just been my browser cache.
> 
> Thanks! 👍

Hi! I am also seeing the same bug with nc19 beta1 and reloading page doesn't help. Do you have recommendatins or should I wait for beta2...

**Comment by Dragon988** [comment]
Reloading worked for me but mine was an upgraded 18.0.3. I don't know if it works on a fresh 19 install.

**Comment by Dragon988** [comment]
Note that this is not fixed in 19 beta 2.

Fix above still works. Still requires reloading the page to fix contacts.

**Comment by skjnldsv** [comment]
This is not about the beta it's about contacts not having a release compatible with 19 yet. https://apps.nextcloud.com/apps/contacts#downloads

**Comment by Dragon988** [comment]
> 
> 
> This is not about the beta it's about contacts not having a release compatible with 19 yet. https://apps.nextcloud.com/apps/contacts#downloads

Understandable, sorry for wasting your time.

**Comment by ostasevych** [comment]
> Note that this is not fixed in 19 beta 2.
> 
> Fix above still works. Still requires reloading the page to fix contacts.

Yes, with fix it works fine! Thanks for that.
