### ISSUE TITLE
Syntax error. The contact cannot be opened.

### ISSUE THREAD

**Issue by Skeeve245** [nextcloud/contacts#1565]
### Steps to reproduce
I have more than 300 contacts that I synced from my outlook via carddav to Nextcloud.
When I select a contact, in the contacts app in Nextcloud, in the overview to show the details for the contact, for some contacts a message pops up within the browser window:
“Syntaxfehler. Der Kontakt kann nicht geöffnet werden.” (rough translation:
"Syntax error. The contact cannot be opened)
and the contact disappears from the overview. Choosing a different app and the the contacts app brings the contact again (in the overview).
That happens only to some contacts. Other contacts make no problem at all.
There is no error in the logs of Nextcloud and I don’t know where else to look.
Downloading the database as XML to look for differences between contacts that can be displayed and contacts that cannot be displayed.

### Expected behaviour
1. In one address I had to replace a “-” as last name.

2. For what ever reasons a lot of addresses had the following syntax for mail addresses:
EMAIL;PREF:name@domain.TLD <- This crashed the app. After changing to:
EMAIL;TYPE=INTERNET;TYPE=HOME:name@domain.TLD
-> everything was good!!!
In my android app the first syntax showed “sonstige” (diverse) as type. When I changed type to home or work everything was fine!

### Actual behaviour
So please either check the address before displaying for correct format or implement a new category, or replace "PREF" by "TYPE=INTERNET;TYPE=HOME" as I will do it with all my contacts.
I am sure that I created the corrupt contacts with outlook but at android they are at least showing up.
It would be great if - at least - the nextcloud.log would show something.

## Server configuration detail

**Operating system:** Linux 4.9.0-0.bpo.11-amd64 #1 SMP Debian 4.9.189-3+deb9u2~deb8u1 (2019-11-12) x86_64

**Webserver:** Apache (cgi-fcgi)

**Database:** mysql 5.7.28

**PHP version:** 

7.3.15
Modules loaded: Core, date, libxml, openssl, pcre, zlib, bcmath, bz2, calendar, ctype, dba, dom, hash, fileinfo, filter, ftp, gettext, gmp, SPL, iconv, session, json, mbstring, pcntl, standard, Phar, posix, Reflection, imap, shmop, SimpleXML, soap, sockets, exif, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, zip, mysqlnd, cgi-fcgi, imagick, curl, gd, mysqli, PDO, pdo_mysql, xsl, sqlite3, intl, sodium, ldap, tidy, pdo_sqlite, ionCube Loader, Zend OPcache

**Nextcloud version:** 18.0.3 - 18.0.3.0

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.4.0
 - activity: 2.11.0
 - admin_audit: 1.8.0
 - admin_notifications: 1.0.2
 - analytics: 2.2.0
 - announcementcenter: 3.7.0
 - apporder: 0.9.0
 - bruteforcesettings: 1.6.0
 - calendar: 2.0.2
 - camerarawpreviews: 0.7.3
 - circles: 0.18.4
 - cloud_federation_api: 1.1.0
 - comments: 1.8.0
 - contacts: 3.2.0
 - dav: 1.14.0
 - deck: 0.8.2
 - documentserver_community: 0.1.5
 - emlviewer: 0.0.5
 - extract: 1.2.3
 - federatedfilesharing: 1.8.0
 - federation: 1.8.0
 - files: 1.13.1
 - files_accesscontrol: 1.8.1
 - files_fulltextsearch: 1.4.2
 - files_fulltextsearch_tesseract: 1.4.1
 - files_lock: 0.8.1
 - files_mindmap: 0.0.20
 - files_pdfviewer: 1.7.0
 - files_rightclick: 0.15.2
 - files_sharing: 1.10.1
 - files_trashbin: 1.8.0
 - files_versions: 1.11.0
 - files_videoplayer: 1.7.0
 - firstrunwizard: 2.7.0
 - forms: 1.1.1
 - fulltextsearch: 1.4.1
 - fulltextsearch_elasticsearch: 1.5.1
 - groupfolders: 6.0.5
 - groupquota: 0.1.2
 - issuetemplate: 0.6.0
 - logreader: 2.3.0
 - lookup_server_connector: 1.6.0
 - maps: 0.1.6
 - metadata: 0.11.1
 - nextbackup: 19.12.1
 - nextcloud_announcements: 1.7.0
 - notes: 3.2.0
 - notifications: 2.6.0
 - oauth2: 1.6.0
 - occweb: 0.0.7
 - ocr: 6.0.29
 - onlyoffice: 4.1.4
 - password_policy: 1.8.0
 - passwords: 2020.4.0
 - phonetrack: 0.6.2
 - photos: 1.0.0
 - polls: 1.3.0
 - privacy: 1.2.0
 - provisioning_api: 1.8.0
 - quicknotes: 0.2.3
 - quota_warning: 1.7.0
 - rainloop: 6.1.0
 - ransomware_protection: 1.6.1
 - recommendations: 0.6.0
 - serverinfo: 1.8.0
 - settings: 1.0.0
 - sharebymail: 1.8.0
 - spreed: 8.0.7
 - support: 1.1.0
 - survey_client: 1.6.0
 - suspicious_login: 3.1.0
 - systemtags: 1.8.0
 - tasks: 0.12.1
 - text: 2.0.0
 - theming: 1.9.0
 - twofactor_backupcodes: 1.7.0
 - twofactor_totp: 4.1.3
 - updatenotification: 1.8.0
 - user_usage_report: 1.2.0
 - viewer: 1.2.0
 - w2g2: 3.0.1
 - wopi: 3.5.4
 - workflow_pdf_converter: 1.3.1
 - workflow_script: 1.3.1
 - workflowengine: 2.0.0
Disabled:
 - encryption
 - files_antivirus
 - files_automatedtagging
 - files_external
 - old_groupfolders
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "www.tpmd.de"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "18.0.3.0",
    "overwrite.cli.url": "https:\/\/www.tpmd.de\/nextcloud",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "installed": true,
    "maintenance": false,
    "theme": "",
    "loglevel": 2,
    "mail_smtpmode": "smtp",
    "mail_sendmailmode": "smtp",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauth": 1,
    "mail_smtpport": "25",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "updater.release.channel": "stable",
    "app_install_overwrite": [
        "auto_mail_accounts",
        "admin_notifications"
    ],
    "filesystem_check_changes": 1,
    "updater.secret": "***REMOVED SENSITIVE VALUE***"
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36

**Operating system:** Windows 10

## Logs

Web server error log</summary>

```
The log shows nothing regarding this case. If you like I can transmit a snipplet.
```
</details>

<details><summary>Nextcloud log</summary>

```
The log shows nothing regarding this case.
```
</details>

<details><summary>Browser log</summary>

</details>

**Comment by skjnldsv** [comment]
Hello!
I will need your browser console log to investigate this issue.
Open your console, reload your page and/or do the action leading to this issue and copy/paste the log in this thread.

<details>
<summary>How to access your browser console (Click to expand)</summary>

# Chrome
- Press either CTRL + SHIFT + J to open the “console” tab of the Developer Tools.
- Alternative method:
    1. Press either CTRL + SHIFT + I or F12 to open the Developer Tools.
    2. Click the “console” tab.

# Safari
- Press CMD + ALT + I to open the Web Inspector.
- See Chrome’s step 2. (Chrome and Safari have pretty much identical dev tools.)

# IE9
1. Press F12 to open the developer tools.
2. Click the “console” tab.

# Firefox
- Press CTRL + SHIFT + K to open the Web console (COMMAND + SHIFT + K on Macs).
- or, if Firebug is installed (recommended):
    1. Press F12 to open Firebug.
    2. Click on the “console” tab.

# Opera
1. Press CTRL + SHIFT + I to open Dragonfly.
2. Click on the “console” tab.
</details>

**Comment by Skeeve245** [comment]
Working contact:
JQMIGRATE: Migrate is installed, version 1.4.1
ProxyBus.js:65 Proxying an event bus of version 1.1.2 with 0.2.1
t @ ProxyBus.js:65
(anonymous) @ index.js:20
n @ bootstrap:19
(anonymous) @ requesttoken.js:11
n @ bootstrap:19
(anonymous) @ index.js:25
n @ bootstrap:19
(anonymous) @ client.js:12
n @ bootstrap:19
(anonymous) @ notifications.js?v=bbb762f1-1:21
n @ bootstrap:19
(anonymous) @ bootstrap:83
(anonymous) @ notifications.js?v=bbb762f1-1:1
globals.js:66 Handlebars is deprecated: please ship your own, this will be removed in Nextcloud 20
ne @ globals.js:66
get @ globals.js:96
e.default @ no-conflict.js:9
(anonymous) @ handlebars.runtime.js:60
n @ bootstrap:19
(anonymous) @ runtime.js:3
n @ bootstrap:19
(anonymous) @ file.handlebars:1
n @ bootstrap:19
(anonymous) @ richObjectStringParser.js:13
n @ bootstrap:19
(anonymous) @ bootstrap:83
(anonymous) @ notifications.js?v=bbb762f1-1:1
globals.js:66 oc_config is deprecated: use OC.config instead
ne @ globals.js:66
get @ globals.js:96
(anonymous) @ main.js:70
i @ bootstrap:63
(anonymous) @ bootstrap:198
(anonymous) @ contacts.js?v=bbb762f1-1:1
25globals.js:66 moment is deprecated: please ship your own, this will be removed in Nextcloud 20

Not working contact:
JQMIGRATE: Migrate is installed, version 1.4.1
ProxyBus.js:65 Proxying an event bus of version 1.1.2 with 0.2.1
t @ ProxyBus.js:65
(anonymous) @ index.js:20
n @ bootstrap:19
(anonymous) @ requesttoken.js:11
n @ bootstrap:19
(anonymous) @ index.js:25
n @ bootstrap:19
(anonymous) @ client.js:12
n @ bootstrap:19
(anonymous) @ notifications.js?v=bbb762f1-1:21
n @ bootstrap:19
(anonymous) @ bootstrap:83
(anonymous) @ notifications.js?v=bbb762f1-1:1
globals.js:66 Handlebars is deprecated: please ship your own, this will be removed in Nextcloud 20
ne @ globals.js:66
get @ globals.js:96
e.default @ no-conflict.js:9
(anonymous) @ handlebars.runtime.js:60
n @ bootstrap:19
(anonymous) @ runtime.js:3
n @ bootstrap:19
(anonymous) @ file.handlebars:1
n @ bootstrap:19
(anonymous) @ richObjectStringParser.js:13
n @ bootstrap:19
(anonymous) @ bootstrap:83
(anonymous) @ notifications.js?v=bbb762f1-1:1
globals.js:66 oc_config is deprecated: use OC.config instead
ne @ globals.js:66
get @ globals.js:96
(anonymous) @ main.js:70
i @ bootstrap:63
(anonymous) @ bootstrap:198
(anonymous) @ contacts.js?v=bbb762f1-1:1
25globals.js:66 moment is deprecated: please ship your own, this will be removed in Nextcloud 20

**Comment by Skeeve245** [comment]
Are absolutely the same

**Comment by Skeeve245** [comment]
Sorry - I did not choose a non working address. And now the output is different!!!
JQMIGRATE: Migrate is installed, version 1.4.1
ProxyBus.js:65 Proxying an event bus of version 1.1.2 with 0.2.1
t @ ProxyBus.js:65
(anonymous) @ index.js:20
n @ bootstrap:19
(anonymous) @ requesttoken.js:11
n @ bootstrap:19
(anonymous) @ index.js:25
n @ bootstrap:19
(anonymous) @ client.js:12
n @ bootstrap:19
(anonymous) @ notifications.js?v=bbb762f1-1:21
n @ bootstrap:19
(anonymous) @ bootstrap:83
(anonymous) @ notifications.js?v=bbb762f1-1:1
globals.js:66 Handlebars is deprecated: please ship your own, this will be removed in Nextcloud 20
ne @ globals.js:66
get @ globals.js:96
e.default @ no-conflict.js:9
(anonymous) @ handlebars.runtime.js:60
n @ bootstrap:19
(anonymous) @ runtime.js:3
n @ bootstrap:19
(anonymous) @ file.handlebars:1
n @ bootstrap:19
(anonymous) @ richObjectStringParser.js:13
n @ bootstrap:19
(anonymous) @ bootstrap:83
(anonymous) @ notifications.js?v=bbb762f1-1:1
globals.js:66 oc_config is deprecated: use OC.config instead
ne @ globals.js:66
get @ globals.js:96
(anonymous) @ main.js:70
i @ bootstrap:63
(anonymous) @ bootstrap:198
(anonymous) @ contacts.js?v=bbb762f1-1:1
25globals.js:66 moment is deprecated: please ship your own, this will be removed in Nextcloud 20
ne @ globals.js:66
get @ globals.js:96
timestamp @ Notification.vue:143
vn.get @ vue.esm.js:4488
vn.evaluate @ vue.esm.js:4593
(anonymous) @ vue.esm.js:4845
(anonymous) @ Notification.vue?6ef9:1
t._render @ vue.esm.js:3557
r @ vue.esm.js:4075
vn.get @ vue.esm.js:4488
vn @ vue.esm.js:4477
(anonymous) @ vue.esm.js:4082
On.$mount @ vue.esm.js:9063
On.$mount @ vue.esm.js:11974
init @ vue.esm.js:3127
(anonymous) @ vue.esm.js:5989
f @ vue.esm.js:5936
v @ vue.esm.js:6064
f @ vue.esm.js:5965
(anonymous) @ vue.esm.js:6488
t._update @ vue.esm.js:3954
_update @ vue.esm.js:8894
r @ vue.esm.js:4075
vn.get @ vue.esm.js:4488
vn @ vue.esm.js:4477
(anonymous) @ vue.esm.js:4082
On.$mount @ vue.esm.js:9063
On.$mount @ vue.esm.js:11974
init @ vue.esm.js:3127
(anonymous) @ vue.esm.js:5989
f @ vue.esm.js:5936
v @ vue.esm.js:6064
f @ vue.esm.js:5965
(anonymous) @ vue.esm.js:6527
t._update @ vue.esm.js:3957
r @ vue.esm.js:4075
vn.get @ vue.esm.js:4488
vn.run @ vue.esm.js:4563
pn @ vue.esm.js:4319
(anonymous) @ vue.esm.js:1989
Yt @ vue.esm.js:1915
Show 11 more frames
ContactDetails.vue:513 r
(anonymous) @ ContactDetails.vue:513

**Comment by skjnldsv** [comment]
Arf, this is too obfuscated, can you do me a screenshot instead?
Also, it's not loading at all, right?
You are not editing the contact before it fails?

**Comment by Skeeve245** [comment]
No, it's not loading at all!
No, I am not editing the contact before it fails, I choose it in the column with the overview and it fails when it shall display details.
I need on moment, as a corrected the data base and have now no problems anymore and everytime that I shall give you information I have to switch the tabels ...

**Comment by Skeeve245** [comment]
Choosing a contact:
![image](https://user-images.githubusercontent.com/1341211/78877645-790c2480-7a51-11ea-90f2-5ba229bda17b.png)

**Comment by Skeeve245** [comment]
Loosing the contact ...
![image](https://user-images.githubusercontent.com/1341211/78877841-bffa1a00-7a51-11ea-86c1-526f277c0af4.png)

**Comment by skjnldsv** [comment]
And screenshot of the console please :) (the last red entries should be enough)

**Comment by Skeeve245** [comment]
![image](https://user-images.githubusercontent.com/1341211/78882432-5598a800-7a58-11ea-8f51-c91bfa016f27.png)

**Comment by skjnldsv** [comment]
Can you expand it? :p
Contacts 3.1.2 ?

**Comment by Skeeve245** [comment]
Contacts 3.2.0!
Yes!
![image](https://user-images.githubusercontent.com/1341211/78895618-6f91b500-7a6f-11ea-8f5c-ed1ca3a0a731.png)

QMIGRATE: Migrate is installed, version 1.4.1
ProxyBus.js:65 Proxying an event bus of version 1.1.2 with 0.2.1
t @ ProxyBus.js:65
globals.js:66 Handlebars is deprecated: please ship your own, this will be removed in Nextcloud 20
ne @ globals.js:66
globals.js:66 oc_config is deprecated: use OC.config instead
ne @ globals.js:66
25globals.js:66 moment is deprecated: please ship your own, this will be removed in Nextcloud 20
ne @ globals.js:66
ContactDetails.vue:513 rmessage: "Invalid parameters in 'EMAIL;PREF:adolfwolber@gmail.com'"name: "ParserError"stack: "    at new r (https://www.tpmd.de/nextcloud/apps/contacts/js/contacts.js?v=bbb762f1-1:1:17930)↵    at Function.i._handleContentLine (https://www.tpmd.de/nextcloud/apps/contacts/js/contacts.js?v=bbb762f1-1:1:18693)↵    at https://www.tpmd.de/nextcloud/apps/contacts/js/contacts.js?v=bbb762f1-1:1:18109↵    at Function.i._eachLine (https://www.tpmd.de/nextcloud/apps/contacts/js/contacts.js?v=bbb762f1-1:1:21641)↵    at Object.i [as parse] (https://www.tpmd.de/nextcloud/apps/contacts/js/contacts.js?v=bbb762f1-1:1:18080)↵    at new t (https://www.tpmd.de/nextcloud/apps/contacts/js/contacts.js?v=bbb762f1-1:1195:300)↵    at https://www.tpmd.de/nextcloud/apps/contacts/js/contacts.js?v=bbb762f1-1:1151:5279"__proto__: constructor: ƒ Error()name: "Error"message: ""toString: ƒ toString()__proto__: Object
(anonymous) @ ContactDetails.vue:513
index.js:281 OC.requestToken changed xjFIeSzC3ACVIJg43qruGDpJHu+yzkcRG3Rh/3W9FyU=:r1MHHUC3s3HTZ+FajN6jUlMBLJb2qw8jdA4RzyL+U20=
index.js:281 OC.requestToken changed /wsXMO6SzcsIKoc432FlpVLXVE5pjC+fQdDbMX+NKnY=:lmlYVILnorpObf5ajRUo7zufZjct6WetLqqrASjObj4=
index.js:281 OC.requestToken changed gMu3Lqpv64QpTg2szoypyqsRCZNqLusCpEHBkx9s7Y4=:6an4SsYahPVvCXTOnPjkgMJZO+ouS6Mwyzuxo0gvqcY=
index.js:281 OC.requestToken changed tkkih7plhfYazjmY8O674dGCmSn6W4vDp2fheQs5uBo=:3ytt49YQ6odciUD6opr2q7jKq1C+PsPxyB2RSVx6/FI=
index.js:281 OC.requestToken changed VP/V9KGUy1w/388BEurWgPCtsRf+dg93BQgpsOfuLb4=:PZ2akM3hpC15mLZjQJ6bypnlg266E0dFanJZgLCtafY=

**Comment by Skeeve245** [comment]
Meet me in my Talk to find more information!
https://www.tpmd.de/nextcloud/index.php/call/j99ez8zk
(You might have to wait there as I am not always at my desk ...)

**Comment by Skeeve245** [comment]
I will leave the office in about 30 minute. I will return on Tuesday.

**Comment by skjnldsv** [comment]
Hey! You got your answer in the screenshot :)
Your contact is not valid, `EMAIL;PREF:email@domain.ext` is not valid!

**Comment by skjnldsv** [comment]
It should be `EMAIL;PREF=1:email@domain.ext`
