### ISSUE TITLE
Menu Icon hard to see on mobile

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/contacts#1583]
![grafik](https://user-images.githubusercontent.com/24530680/79637689-c4c17b00-8181-11ea-944e-637b9cb3b55f.png)

**Possible solution:**
![grafik](https://user-images.githubusercontent.com/24530680/79637694-cd19b600-8181-11ea-8434-f8b28d67d58d.png)

**Comment by jancborchardt** [comment]
There is a design proposal for this at https://github.com/nextcloud/server/issues/16934#issuecomment-542201187
Are you interested in implementing that @jakobroehrl? :)

> ![Contacts app menu](https://user-images.githubusercontent.com/925062/64036387-5dec4480-cb53-11e9-8239-22b538b62e8e.png)

**Comment by skjnldsv** [comment]
This is a Vue components issue :)
