### ISSUE TITLE
Problems while import vcards

### ISSUE THREAD

**Issue by SIRSteiner** [nextcloud/contacts#16]
I had the following problems:
1. comma where replaced with \, -> I removed the replace command in vcard.js
2. several problems with tel types while import vcard v2.1
3. several problems with quoted-printable values while import vcard v2.1

To avoid 2. and 3. I converted all vcards to v3.0 with a little sed-script.

**Comment by irgendwie** [comment]
1. Known issue with the vcard lib we are using (https://github.com/Heymdall/vcard/issues/5), not completely fixed by now - some values need to be escaped that way.
2. Could you please explain a bit more about the problem?
3. Quoted-printable is currently not supported but was already mentioned before the fork (ref https://github.com/owncloud/contacts/issues/399, https://github.com/owncloud/contacts/issues/503)

**Comment by SIRSteiner** [comment]
1. Thanks for this information
2. I'll do a fresh nextcloud installation to exlain it step by step this week
3. That's the problem because exporting i.e. contacts with german umlauts or ß from EGroupware v1.8 you get vcard v2.1 with quoted-printable-strings.

**Comment by irgendwie** [comment]
I'm sorry for the inconveniences! I was already looking for some libraries, dealing with quoted printables since Thunderbird/Lightning is also exporting VCards with that encoding. But I didn't have time to implement it by now. PRs are very welcomed!

**Comment by SIRSteiner** [comment]
Let me explain some problems while import vcard v2.1 without quoted printable:

1. ADR;HOME;... was imported as ADR;HOME=; thats why no type for the address was shown
2. TEL;CELL;HOME:... was imported as TEL;CELL=;HOME=:
3. EGroupware exports 2 ORG-fields (i.e. ORG:Versicherung;Baden-Badener;). After import there is only the first field visible but if you look at the imported data there are both fields. Also after sync with the phone the second field is visible there. Maybe "contacts" need a second field?

So I cannot advise to import vcard v2.1

**Comment by xenji** [comment]
Regarding the problem described in 1., I tried to submit a patch which I think fixes the other part of the problem. See https://github.com/Heymdall/vcard/pull/6

**Comment by xenji** [comment]
FYI The patch has been merged upstream.
