### ISSUE TITLE
Mac Contacts app needs another path to sync

### ISSUE THREAD

**Issue by PersonaA** [nextcloud/contacts#160]
### Steps to reproduce
1. Copy provided in UI link to address book.
2. Use it with Mac OS X Contacts app to sync.

### Expected behaviour
Path that works is `/remote.php/dav/principals/users/USERNAME`.

### Actual behaviour
Provided path is `/remote.php/dav/addressbooks/users/USERNAME/ADDRESSBOOK/`.
Empty address book in Contact app.

### Server configuration

https://hub.docker.com/r/wonderfall/nextcloud/

**Nextcloud version:**
11.0.2

**Contacts version:**
1.5.3

**Updated from an older Nextcloud or fresh install:**
Updated from 11.0.0

### Client configuration

**Operating system:**
Mac OS X 10.12.1

**CardDAV-clients:**
Contacts Version 10.0 (1756.9)

**Comment by tessus** [comment]
@ynt what link would you have to use, if you had another address book (e.g.: address book named **testab**)?

I'm having similar issues syncing with Mac and I just can't figure it out.

**Comment by irgendwie** [comment]
Since the URL in the settings shows the direct link to the address books (which is intended behavior), we won't change it.
In theory it should be enough to provide `/remote.php/dav/` to the Mac contacts client, since it should be able to find all address books and paths automatically.
