### ISSUE TITLE
Import contacts from command line

### ISSUE THREAD

**Issue by NicoP-S** [nextcloud/contacts#162]
Hello,

would it be possible to make a command line import of vcf files? This would be a nice feature. I would like to add users daily to some addressbooks but i can't find an option for it.
I have checked the occ commands .
Regards
Nico

**Comment by irgendwie** [comment]
If one would want to implement this, it should be done in the carddav backend in nextcloud/server.
Still I don't really see any reason or use-case to implement this, because one could use any available carddav library and script a simple tool to do exactly what you wish for.
