### ISSUE TITLE
Strange resolvine of vcard X-ANDROID-CUSTOM:vnd.android.cursor.item/relation

### ISSUE THREAD

**Issue by IamSAB** [nextcloud/contacts#1620]
In the Android contacts app you can create relations for contacts therefore relate a contact to mulitple other contacts. This feature is also available in the nextcloud contacts app ui.

However, I noticed, that relations created on my mobile phone are not the same anymore when sync to the server.

Her an example. I created the relations on my phone, then exported it to VCF. Then I did the sync to nextcloud (using DAVdroid) and downloaded the VCF there. Here the comparison:

VCF from my phone
```
X-ANDROID-CUSTOM:vnd.android.cursor.item/relation;Assistant;1;;;;;;;;;;;;;
X-ANDROID-CUSTOM:vnd.android.cursor.item/relation;Brother;2;;;;;;;;;;;;;
X-ANDROID-CUSTOM:vnd.android.cursor.item/relation;Child;3;;;;;;;;;;;;;
X-ANDROID-CUSTOM:vnd.android.cursor.item/relation;Domestic Partner;4;;;;;;;;;;;;;
X-ANDROID-CUSTOM:vnd.android.cursor.item/relation;Father;5;;;;;;;;;;;;;
X-ANDROID-CUSTOM:vnd.android.cursor.item/relation;Friend;6;;;;;;;;;;;;;
X-ANDROID-CUSTOM:vnd.android.cursor.item/relation;Manager;7;;;;;;;;;;;;;
X-ANDROID-CUSTOM:vnd.android.cursor.item/relation;Mother;8;;;;;;;;;;;;;
X-ANDROID-CUSTOM:vnd.android.cursor.item/relation;Parent;9;;;;;;;;;;;;;
X-ANDROID-CUSTOM:vnd.android.cursor.item/relation;Partner;10;;;;;;;;;;;;;
X-ANDROID-CUSTOM:vnd.android.cursor.item/relation;Referrred;11;;;;;;;;;;;;;
X-ANDROID-CUSTOM:vnd.android.cursor.item/relation;Relative;12;;;;;;;;;;;;;
X-ANDROID-CUSTOM:vnd.android.cursor.item/relation;Sister;13;;;;;;;;;;;;;
X-ANDROID-CUSTOM:vnd.android.cursor.item/relation;Spouse;14;;;;;;;;;;;;;
X-ANDROID-CUSTOM:vnd.android.cursor.item/relation;Custom;0;Custom;;;;;;;;;;;;
```

VCF from nextcloud
```
RELATED;TYPE=co-worker;VALUE=TEXT:Assistant
**RELATED;TYPE=sibling;VALUE=TEXT:Brother**
RELATED;TYPE=child;VALUE=TEXT:Child
RELATED;TYPE=spouse;VALUE=TEXT:Domestic Partner
**RELATED;TYPE=parent;VALUE=TEXT:Father**
RELATED;TYPE=friend;VALUE=TEXT:Friend
**RELATED;TYPE=co-worker;VALUE=TEXT:Manager**
**RELATED;TYPE=parent;VALUE=TEXT:Mother**
RELATED;TYPE=parent;VALUE=TEXT:Parent
**RELATED;TYPE=spouse;VALUE=TEXT:Partner**
**RELATED;VALUE=TEXT:Referrred**
**RELATED;TYPE=kin;VALUE=TEXT:Relative**
RELATED;TYPE=sibling;VALUE=TEXT:Sister
RELATED;TYPE=spouse;VALUE=TEXT:Spouse
RELATED;TYPE=custom;VALUE=TEXT:Custom
````
Apparrently, it is expected, that the android relations get resolved to the RELATED attribute in vcard. But as you see, the conversion is not correct for all relations.

I wonder, where this differences are created. I cannot say what causes this mistakes: DAVdroid, some parts of the contact app (do you have some predifined relations?) or even Android.

I cannot say, if this is a bug or an expected behaviour considering the implementation of the vcard relations. Can you give me some insights, what could cause these problem?

**Comment by skjnldsv** [comment]
Hey!
yes, this is a feature from Davx, forwarding custom android properties to the correct vCard ones.


> VCF from nextcloud

When you say from Nextcloud, you mean changed with Nextcloud or just downloaded from the Contacts app?

**Comment by IamSAB** [comment]
Ok, that good to know. Should I then post an issue on the Davx repository?

You are correct. I downloaded the vcard directly via the nextcloud contacts app without editing and saving the contact.

**Comment by skjnldsv** [comment]
It might be by design
https://www.davx5.com/manual/technical_information.html?highlight=related#relation
