### ISSUE TITLE
Missing translation of "Settings" dialog header

### ISSUE THREAD

**Issue by j-ed** [nextcloud/contacts#1629]
**Describe the bug**
The name of the settings dialog header isn't translated.

**To Reproduce**
1. Open the Contacts app.
2. Check the name of the settings dialog in the lower left corner.

**Expected behavior**
"Settings" should be translated to e.g. "Einstellungen" if the German language has been selected.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/2572764/81783168-42677500-94fb-11ea-95c9-85012aced256.png)

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS X]: **Windows 10**
 - Browser [e.g. chrome, safari]: **Firefox 76.0.1**

**Server (please complete the following information):**
 - OS: [e.g. CentOS 7]: **Linux 4.9.218**
 - HTTP server: [e.g. nginx 1.1]: **Apache2 2.4.41**
 - Database [e.g. MySQL 5.3]: **MariaDB 10.2.24**
 - PHP version: [e.g. v7.2]: **7.3.13**
 - Nextcloud version: [e.g. 15.0.1 (see Nextcloud admin page)]: **18.0.4**
 - Contacts app version: [e.g. 1.1.0 (see Nextcloud apps page)]: **3.3.0**
 - Nextcloud external user backend: [e.g. ldap, or none]: **none**

**Comment by call-me-matt** [comment]
I have nextcloud version 18.0.4 and contacts app version 3.3.0, too - but it's translated to German here (Einstellungen).

**Comment by skjnldsv** [comment]
Same :shrug:
