### ISSUE TITLE
Contact delete tooltip

### ISSUE THREAD

**Issue by Dreamsorcerer** [nextcloud/contacts#163]
Go to Contacts, you'll see in the top-right of the contact window what looks like a download button and a delete button.

Hovering over these 2 buttons both give the tooltip 'Download'. Presumably, the second button should in fact read 'Delete'.

Running latest version.

**Comment by irgendwie** [comment]
Already fixed by https://github.com/nextcloud/contacts/pull/116, still no new version was released until now and the error is still observable in the current release.
