### ISSUE TITLE
Add contact to multiple address books

### ISSUE THREAD

**Issue by philipreimer** [nextcloud/contacts#1630]
**Is your feature request related to a problem? Please describe.**
Imagine the following situation:

* I would like to use nextcloud for different projects with a different user group per project.
* I have set up the nextcloud users, and divided them into user groups.
* Some users are in multiple projects and thus in multiple user groups.
* I have created a contact in the contact app for each nextcloud user.
* Now I would like to create an address book for each project and share it with the project's user group, so that each user can only see those contacts, that are part of the user's project.

All that is working fine until I come to a contact for a user who is in more than one project.
Because I can only assign the contact to one address book.
So it seems that I have to duplicate the existing contact for each additional address book that I would like to add.
Of course that also leads to duplicate contacts in the overall contact list, if a user is in multiple projects and thus has access to multiple address books.

**Describe the solution you'd like**
I would like to be able to include a contact in multiple address books, so I can share the same contact with different user groups.
But if the same contact exists in more than one of the address books which I can access as a user, that same contact should only appear once in the list of contacts (contacts app and the contacts list in the upper right corner of the global nextcloud menu)

**Describe alternatives you've considered**

I know I can assign a contact to multiple groups in the contact app, but those "contact groups" cannot be shared with other users or user groups.

**Comment by skjnldsv** [comment]
Hello,
This is not possible at all.
You cannot do that with the vCard standards unfortunately :/

**Comment by demlak** [comment]
Since the VCARD itself does not hold the name of the adressbook, this question is about nextcloud and it's way of managing adressbooks.

The feature of adding one contact to multiple adressbooks seems to be just a multi-value for `adressbook` in the database.

please reopen this issue as a feature request

**Comment by philipreimer** [comment]
> please reopen this issue as a feature request

@demlak you mean as a new issue in [nextcloud/server](https://github.com/nextcloud/server) or would another project be more suitable?

**Comment by demlak** [comment]
sorry, i'm not familiar with the correct place where this should be..
but the content of this is a feature request which is closed by @skjnldsv because of a not coresponding argument, i think.

**Comment by skjnldsv** [comment]
Hey!
Thank you for your interest :)
Like mentioned, this is not doable. First of all because this is not part of the rfc, and secondly because this would complicate thing a lot and it would be basically a hack on how we manage things.
Sorry, this will not be possible!

Take care!
Cheers

**Comment by demlak** [comment]
what RFC? it does not impact anything on vcards!

**Comment by IeuanK** [comment]
@demlak 
> what RFC? it does not impact anything on vcards!
> it is only a nextcloud thing.. not related to the vcards itself, but the managment how nextcloud is working with the vcards.
> 
> or did i oversee something?

RFC is the 'Request for Comments' for CardDav and its card format. It is what describes the standard, but is open to comments on how it could be improved.

A critical point that @skjnldsv's comment is missing is that NextCloud simply interfaces with a standard CardDav server, it does not store data in an abstraction layer. This is why the whole Contacts app is such a terrible mess and why it is impossible to share an address book with multiple users easily or add a contact to multiple address books. 

There is also no workaround for this. If you share an address book with a user then open their main 'Contacts' address book, it does not include shared address books. This very simply means that there is no way to easily manage multiple address books across multiple users, and no way to have a contact in multiple address books without duplicates.

**Comment by ver-luisant** [comment]
> @demlak
> 
> Can't really blame them, there are plenty of other features that need the attention more than this detail, and there are plenty of other tools that do an infinitely better job at managing contacts than this hacked-together Contacts app.

Hi,
Any suggestion for such other tools (open source, self hosted) ?
I have the same need as @philipreimer to add contact to multiple address books, and this is currently a showtopper for me using the Contacts app.
Thanks.

**Comment by pkoevesdi** [comment]
Same here, I don't see it as a detail. To me, not being able to ahre groupsm nor to get a dav-URL from them, nor being able to put a contaact into ore than one address book, is a total blocker for the contancts app. So, I'm also very interested in other apps that can do this? Any contants server or what are You referring to?

**Comment by Schleichmichl** [comment]
After reading this conversation I'm a little bit confused. Confused about the decision why this little important detail will not be implemented. Nextcloud is going big, there is fancy stuff implemented for big organisations and I can't share a part of my contacts? Really? Are you kidding me? That this feature was forgotten, ok. But will not be implemented?

My use case is: Create a additional address book to share it with my fritzbox so that I have only specific contacts there in the connected telephone.

I'm really stunned.
