### ISSUE TITLE
UI appears broken

### ISSUE THREAD

**Issue by blizzz** [nextcloud/contacts#1632]
### Describe the bug

The addressbook entry, also the very first on upon creation,  is shown below the fold. It is disconnected form the column layout and the some elements (e.g main name, company, phone) are not editable.

**To Reproduce**
1. Get contacts from git, run make, enable it
2. move to contacts app
3. click on "New contact"

**Expected behavior**

Addressbook entries shall be shown as before

**Actual behavior**

![Screenshot_20200516_005720](https://user-images.githubusercontent.com/2184312/82102549-386a8f80-9710-11ea-938a-1afe1ee125d0.png)

and after pressing space or page down:

![Screenshot_20200516_005833](https://user-images.githubusercontent.com/2184312/82102616-618b2000-9710-11ea-9faf-87ac33d00485.png)

### Server configuration

**Operating system**: Linux (Arch btw)

**Web server:** Apache

**Database:** PostgreSQL... 

**PHP version:** 7.4

**Nextcloud version:** git - stable19 - 9d7198f31e75498f2df35c156cbcfdfc2f346ad2

**Contacts version:** git - master - 4bec35b0ce9b5a114f34b435335271d2db0fe84a

**Updated from an older Nextcloud or fresh install:** fresh

### Client configuration
**Browser:** FF 76

**Operating system:** Linux

#### Browser log

no error

**Comment by blizzz** [comment]
@skjnldsv

**Comment by jotoeri** [comment]
Left one is #app-content-vue, right one is #app-content

![grafik](https://user-images.githubusercontent.com/47433654/82833703-1cf54680-9ebf-11ea-9836-198704f5b727.png)
