### ISSUE TITLE
19.0.0RC2: no default address book created

### ISSUE THREAD

**Issue by kyrofa** [nextcloud/contacts#1635]
### Describe the bug
On a fresh install of Nextcloud 19.0.0RC2, when I install the contacts app the "+ New contact" button is grayed out and unclickable. I needed to go to settings and create an address book before I could create any contacts. This was not required in previous versions of the app.

**To Reproduce**
1. Install 19.0.0RC2
2. Install the contacts app
3. Note that you cannot create a new contact before first creating a new address book

**Expected behavior**
I expected a default address book to be created for me so I could immediately start creating contacts.

**Actual behavior**
No address book was created, and no message was given leading me toward what to do, requiring me to dig around in the app settings to stumble onto the fact that I didn't have an address book and needed to create one (I didn't even know multiple address books were supported!).

**Comment by skjnldsv** [comment]
Weird! cc @georgehrke we touched something on server?

**Comment by georgehrke** [comment]
@skjnldsv There is the ContactsInteraction addressbook by default, which happens to be read-only. That might explain the behavior.

**Comment by georgehrke** [comment]
You are only checking if there is an existing addressbook, not if it's writable one:
https://github.com/nextcloud/contacts/blob/master/src/views/Contacts.vue#L322

**Comment by skjnldsv** [comment]
Yeah, this was a fallback on contacts just in case.
But still, shouldn't server create a default one?

**Comment by georgehrke** [comment]
Same problem in the server: https://github.com/nextcloud/server/blob/master/apps/dav/lib/HookManager.php#L163

**Comment by georgehrke** [comment]
Ignore my previous comment, ContactsInteraction will not be counted there.

**Comment by georgehrke** [comment]
@kyrofa Are you talking about the admin-user who just created the nextcloud instance or any user created later on?

**Comment by kyrofa** [comment]
@georgehrke I only tested the admin user.

**Comment by skinofthesoul** [comment]
Just wanted to say thank you – I had the exact same problem, and being completely new to Nextcloud, I have been clicking myself silly through all the settings and options searching for the *something* that I obviously still needed to do to get this going. It absolutely did not occur to me that I could create an address book with this little text field on the bottom left! Thank you, I can get some work done now!

**Comment by kyrofa** [comment]
> It absolutely did not occur to me that I could create an address book with this little text field on the bottom left!

Haha, glad I'm not the only one that didn't know! Thank you for the kind comment.

**Comment by floli** [comment]
Adding that I can still reproduce this on 19.0.0 released version, installed from docker image only for the admin user. For a normal user, the default address book was created.

**Comment by floli** [comment]
Anyone knows how to manually recreate the **default address book** so that it is localized correctly and everything. For example, when I create an address book "Contacts" it is not localized, in contrast to the default address book.

**Comment by skjnldsv** [comment]
> Anyone knows how to manually recreate the **default address book** so that it is localized correctly and everything?

I doubt this is localised. I might be on creation if your language is set at the specific moment. Other than this, it will not :thinking:

**Comment by georgehrke** [comment]
> Other than this, it will not

It actually does:

https://github.com/nextcloud/server/blob/b219eadb8f3f459f2c71e937dfd3542f0792da8e/apps/dav/lib/CardDAV/AddressBook.php#L58

@floli See this file for the required URI and display name:

https://github.com/nextcloud/server/blob/18acb137d3b973f04ee039fd4a4e8ed1bca25127/apps/dav/lib/CardDAV/CardDavBackend.php#L59

**Comment by skjnldsv** [comment]
Ah wow, thank @georgehrke !
Creating a `contacts` address book should work if there isn't any I guess?

**Comment by floli** [comment]
I created a `contacts` adressbook (results in setting URL to to contacts) and renamed it to `Contacts` (does not change URL). This results in a translated name `Kontakte` for me.
