### ISSUE TITLE
app completely broken

### ISSUE THREAD

**Issue by paolomeraviglia** [nextcloud/contacts#164]
### Steps to reproduce
1. install from regular "add app"
2. open the contacts app
3.

### Expected behaviour
There would be all the menu to add / remove contacts and groups
### Actual behaviour
only blue nextcloud menu showed and on the left side a left bar with only the settings icon but without anything
### Server configuration
linux LXC debian 87
**Web server:**
nextcloud via nginx on a lxc + apache2.4 with ispconfig configured as reverse proxy
**Database:**
mariadb
**PHP version:**
7.1
**Nextcloud version:** (see Nextcloud admin page)
11.0.2 (stable)
**Contacts version:** (see Nextcloud apps page)
1.5.3
**Updated from an older Nextcloud or fresh install:**
fresh install
**Signing status:**

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
No errors have been found.

**List of activated apps:**
contacts, calendar
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
local with glusterfs
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no
#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**
chrome

**Operating system:**
debian 8

**CardDAV-clients:**
none

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by paolomeraviglia** [comment]
ok, the problem appear to be something with cloudflare: when connecting directly to the server all the things works great

**Comment by irgendwie** [comment]
Interesting, is there any error in the Javascript console of your browser or in the nextcloud log?

**Comment by paolomeraviglia** [comment]
There aren't errors from server but i see multiple errors related to
angularjs from the browser's console

Il 14 mar 2017 01:14, "Alexander Weidinger" <notifications@github.com> ha
scritto:

**Comment by skjnldsv** [comment]
What are the errors?

**Comment by paolomeraviglia** [comment]
JQMIGRATE: Migrate is installed, version 1.4.0
angular.js:310 Uncaught SyntaxError: Unexpected identifier
angular-route.js:3 Uncaught TypeError: Cannot read property 'module' of undefined
    at angular-route.js:3
    at angular-route.js:36
angular-uuid4.js:12 Uncaught ReferenceError: angular is not defined
    at angular-uuid4.js:12
angular-cache.js:1 Uncaught TypeError: Cannot use 'in' operator to search for 'default' in undefined
    at angular-cache.js:1
    at angular-cache.js:1
    at angular-cache.js:1
angular-sanitize.js:1 Uncaught TypeError: Cannot read property '$$minErr' of undefined
    at angular-sanitize.js:1
    at angular-sanitize.js:29
select.js:2 Uncaught ReferenceError: angular is not defined
    at select.js:2
    at select.js:120
script.js:1 Uncaught ReferenceError: angular is not defined
    at script.js:1
ui-bootstrap.min.js:7 Uncaught ReferenceError: angular is not defined
    at ui-bootstrap.min.js:7
ui-bootstrap-tpls.min.js:7 Uncaught ReferenceError: angular is not defined
    at ui-bootstrap-tpls.min.js:7
DevTools failed to parse SourceMap: https://<DOMAIN>/core/vendor/jquery/dist/jquery.min.map

**Comment by paolomeraviglia** [comment]
browser: chrome
if you open it without cloudflare, there are no such errors, but after that you'll have in your cache these files, so to test it I used incognito mode

**Comment by aryasenna** [comment]
Can confirm, other than Contacts, Notes is also broken when Nextcloud is hosted behind CloudFlare.
Cloudflare does some JS minifying and you might have the rocketloader activated (I don't). Those could interfere with JS, but yes this is out-box-issue for standard nextcloud app in well-known deployment platform.

**Comment by irgendwie** [comment]
jfr https://github.com/owncloud/contacts/issues/450

**Comment by jancborchardt** [comment]
Thanks to @apotek & @maximevaillancourt for the solution

> The workaround here appears to be to log in to cloudflare, go to the "Speed" page, go to the Auto Minify section, and uncheck the box for javascript.
> 
> While your JS won't be minified anymore by cloudfront, at least it will work.
> 
> ![screen shot 2017-05-17 at 5 27 05](https://cloud.githubusercontent.com/assets/279278/26147491/ba60a488-3ac1-11e7-8cfa-78d0266c3ed9.png)

Closing this hence.
