### ISSUE TITLE
UI: more consistent layout when adding fields?

### ISSUE THREAD

**Issue by gqgunhed** [nextcloud/contacts#1643]
I really like the way the contacts app works in Nextcloud web UI. 
But what brings down productivity a lot is that every single contact has its own layout of fields depending on:
- how many email address or phone number fields are active, etc.
- physical screen resolution/layout/width
I understand that this is intentionally flexible to allow adding information to contacts as needed.
The way the layout works you always need a few seconds to find the second email address field you just activated.

But could it be possible to keep the detail view of a contact more consistent in layout when adding additional fields? Let's say with a primary-column and primary-vertical-position for specific fields?
Like Name, Phone, Email left column, postal address second column (if available), notes, birthday, etc. on third column (if available).

Does this make sense? I think it would increase the readability of the presented information in the web interface.
Looking forward to reading from you.

**Comment by skjnldsv** [comment]
cc @jancborchardt

**Comment by FBachofner** [comment]
I strongly second this request.

In addition to improved useability, "enterprise" adopters would have a much easier time training users too.  Right now a screenshot is a moving target!

**Comment by basti1982** [comment]
I also like the idea of a more structured layout.

**Comment by skjnldsv** [comment]
With #1755 we improved a lot the overall flow.
This doesn't do weird splitting between columns. I'll mark this as closed, please try the upcoming release (will come soon), then if you think there is still room for improvements, feel free to re-open :hugs:

**Comment by Sensor66** [comment]
I am using Nexcloud in the version of Murena, and this "flexible" lay-out is IMHO, not made for productive work. Searching every contact for it's details in different places is a major pain in the ass. That lay-out can be flexible in the sense that users can choose, but thereafter it shoud be fixed. The memory must get into my muscles, not to be researched with every look-up. 

So I strongly second this original request.

Or am I missing something, and CAN the lay-out be fixed?

Thank you.
