### ISSUE TITLE
Change photo by clicking on image

### ISSUE THREAD

**Issue by tbm** [nextcloud/contacts#1654]
Changing the photo for a contact is not very obvious since the menu is very far from the photo and easy to miss.

It would be nice if clicking on the photo would allow you to change it.

**Comment by call-me-matt** [comment]
Hi, I think so too and made a proposal to tackle this: https://github.com/nextcloud/contacts/pull/1645

![unhide edit button](https://user-images.githubusercontent.com/34400929/82939664-f3f2b580-9f93-11ea-866c-3f4d35bed7c3.gif)

**Comment by tbm** [comment]
@call-me-matt thanks, that looks nice.

Sorry I didn't see issue #1513 since I searched for "photo".

**Comment by skjnldsv** [comment]
Closed with your awesome work @call-me-matt
