### ISSUE TITLE
Exception occurred while executing 'SHOW FULL TABLES WHERE Table_type = 'BASE TABLE'' and Can't read dir of './nextcloud/' (errno: 13 "Permission denied") 

### ISSUE THREAD

**Issue by tifDev** [nextcloud/contacts#1661]
When i was trying to activate the application on NextCloud, i got this error:
`An exception occurred while executing 'SHOW FULL TABLES WHERE Table_type = 'BASE TABLE'': SQLSTATE[HY000]: General error: 1018 Can't read dir of './nextcloud/' (errno: 13 "Permission denied")` 

How can i solve this?

**Comment by skjnldsv** [comment]
Hey! Thsi doesn't seems to be related to contacts at all.
Looks like you either have permissions access or no space on device

As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com
