### ISSUE TITLE
sharing files with contact groups

### ISSUE THREAD

**Issue by ArnY** [nextcloud/contacts#167]
i'm surprised I couldn't find a previous issue about this subject, so I apologize if I missed it.

Since we are allowing users to create groups of contacts, they are expecting to be able to use those groups for sharing files. Surprisingly, it doesn't seem to be possible. Is it a bug or a missing feature?

**Comment by oparoz** [comment]
It's currently a missing feature. Contact groups have been integrated with several apps already, but we're still working towards full integration.

**Comment by faabiiiooo** [comment]
Would be great, if the feature for file sharing is available soon.

**Comment by alexanderdd** [comment]
Nextcloud user groups are a different thing than contact groups. 
Don't know how to resolve that...

**Comment by ArnY** [comment]
The ability of creating groups of users and share with those groups is now provided by the Circles plugin but lack of integration with the Contacts plugin is pretty confusing if both plugins are activated. Not sure if I can close this issue or not.

**Comment by sunjam** [comment]
I'm also confused... is it possible to use the Circles app to add functionality to Contacts app as @ArnY  mentioned?

**Comment by skjnldsv** [comment]
> Nextcloud user groups are a different thing than contact groups.
> Don't know how to resolve that...

We can't. :)
This app is just an interface for your webdav contacts. It has nothing to do with sharing and stuff.
If you want, you can request (if it does not exists already) on the server, to be able to have contacts groups in the sharing dropdown :)
