### ISSUE TITLE
Add Matrix to list of Instant Messaging networks

### ISSUE THREAD

**Issue by jtrees** [nextcloud/contacts#1675]
**Is your feature request related to a problem? Please describe.**
I'd like a way to add my contacts' Matrix IDs to the address book.

**Describe the solution you'd like**
I'd like Matrix to be in the list of Instant Messaging networks.

**Describe alternatives you've considered**
It would also be possible to allow custom networks (my contacts app on Android does this). Unfortunately the entry appears broken in the Nextcloud Contacts app after adding the former via my phone.

**Additional context**
More info about Matrix: https://matrix.org/

**Comment by skjnldsv** [comment]
Hey, Thanks for this issue :)
Can you open a pull request to add it there? https://github.com/nextcloud/contacts/blob/2a7fa84dd7ba7f76bfeb391a6d2dba4327c685c9/src/models/rfcProps.js#L241

**Comment by EmTeedee** [comment]
@jtrees I think you need to open the pull request in this repository, not in your fork...

**Comment by jtrees** [comment]
> @jtrees I think you need to open the pull request in this repository, not in your fork...

Ahahaha. Thanks. I don't use GitHub much. ^^
