### ISSUE TITLE
NextCloud v19.0.0 complains about missing directory

### ISSUE THREAD

**Issue by Dieter15** [nextcloud/contacts#1680]
**Is your feature request related to a problem? Please describe.**
On a Raspberry B3 running on Debian 10 I installed NextCloud v19.0.0 (official download from nextcloud.org) from scratch, together with MariaDB 10.3. I created a NC user  who also has admin privileges. When logging in with that user, the following message pops up in the upper right corner of the NC screen:
This directory is unavailable, please check the logs or contact the administrator✖

Of course I deeply checked the logs but did not find any hint what the reason for the error message could be.

**Describe the solution you'd like**
It would like to see further detailed information which directory is unavailable, i.e. the name of the directory in question should be displayed.

**Describe alternatives you've considered**
No alternatives do far. Despite the above mentioned error message NC is operational.

**Additional context**

**Comment by skjnldsv** [comment]
What directory are we talking about?
It seems to me your update was done incorrectly, please disable, delete and install the contacts app again (you will not lose the data)

**Comment by Dieter15** [comment]
Hi John,

> What directory are we talking about?
Good question. My suggestion was that NC not only displays that error message but also provides the name of the directory.

> It seems to me your update was done incorrectly, please disable, delete and install the contacts app again (you will not lose the data)
Your statement is a vague understanding what could be the cause.
Before you sent this e-mail I disabled the contacts app, deleted it and reinstalled it.
The problem still remains.

Furthermore the error message is displayed after login, but before the contacts app is opened.

I kindly ask you to provide the name of the missing directory and I could help myself (probably).

Furthermore I wrote that I installed NC from scratch. This means that no update was involved.
The command "sudo -u www-data php ./occ maintenance:repair" produced the following output:

- Repair MySQL collation
- All tables already have the correct collation -> nothing to do
- Repair mime types
- Clean tags and favorites
- 0 tags of deleted users have been removed.
- 0 tags for delete files have been removed.
- 0 tag entries for deleted tags have been removed.
- 0 tags with no entries have been removed.
- Repair invalid shares
- Move .step file of updater to backup location
- Fix potential broken mount points
- No mounts updated
- Add log rotate job
- Clear frontend caches
- Image cache cleared
- SCSS cache cleared
- JS cache cleared
- Clear every generated avatar on major updates
- Add preview background cleanup job
- Queue a one-time job to cleanup old backups of the updater
- Cleanup invalid photocache files for carddav
- Add background job to cleanup login flow v2 tokens
- Remove potentially over exposing share links
- No need to remove link shares.
- Clear access cache of projects
- Reset generated avatar flag
- Update name of the stored view
- Fix component of birthday calendars
- 3 birthday calendars updated.
- Regenerating birthday calendars to use new icons and fix old birthday events without year
- Repair step already executed
- Fix broken values of calendar objects
0 [->--------------------------]
- Registering building of calendar search index as background job
- Repair step already executed
- Registering background jobs to update cache for webcal calendars
- Added 0 background jobs to update webcal calendars
- Registering building of calendar reminder index as background job
- Repair step already executed
- Clean up orphan event and contact data
- 0 events without a calendar have been cleaned up
- 0 properties without an events have been cleaned up
- 0 changes without a calendar have been cleaned up
- 0 cached events without a calendar subscription have been cleaned up
- 0 changes without a calendar subscription have been cleaned up
- 0 contacts without an addressbook have been cleaned up
- 0 properties without a contact have been cleaned up
- 0 changes without an addressbook have been cleaned up
- Remove activity entries of private events
- Removed 0 activity entries
- Fix the share type of guest shares when migrating from ownCloud
- Copy the share password into the dedicated column
- Set existing shares as accepted
- Update OAuth token expiration times
- Switches from default updater server to the customer one if a valid subscription is available
- Repair step already executed
- Add background job to check for backup codes
- Populating added database structures for workflows

I do not see any error messages.

Kind regards
Dieter

> 
>

**Comment by skjnldsv** [comment]
Where do you see this "missing folder issue".
Keep in mind this is usually issues that are handled in the forum :)
