### ISSUE TITLE
NC remains in en_US locale

### ISSUE THREAD

**Issue by Dieter15** [nextcloud/contacts#1681]
### Describe the bug
On a Raspberry B3 running on Debian 10 I installed NextCloud v19.0.0 (official download from nextcloud.org) from scratch, together with MariaDB 10.3. In config.php the language-realated entries are:
  'default_language' => 'de',
  'default_locale' => 'de_DE',

The result of "echo ${LANG}" is: de_DE.UTF-8

After login to NC the menus are in English language. In the NC settings the language is set to "English (US)".
Setting the Language to "Deutsch" (i.e. "German"), does not help at all. The menus still display English text, and after some time, NC seems to forget the above manual setting and falls back to  "English (US)".

**To Reproduce**
1. Set up NC v19.9.0 from scratch
2. Create a user (preferably with admin privileges)
3. Add the two language-related parameters (see above) to config.php
4. Restart NC
5. Login to NC

**Expected behavior**
I expected NC to follow the language directive immediately. If there were problems doing so (e.g. missing files, etc.), NC should also tell about it.

**Actual behavior**
NC v19.0.0 sticks to "English (US)".

**Screenshots**

### Server configuration

**Operating system**: Windows, Linux, MacOS...
Debian 10

**Web server:** Apache, Nginx...
Apache 2.4.38

**Database:** MariaDB, MySQL, PostgreSQL... 
MariaDB 10.3

**PHP version:** 7.0, 7.1, 7.2...

**Nextcloud version:** (see Nextcloud admin page)
NC v19.0.0

**Contacts version:** (see Nextcloud apps page)

**Updated from an older Nextcloud or fresh install:**
Fresh install (from scratch)

**Signing status:**
```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
No errors have been found.


**List of activated apps:**
All NC apps (from version 19.0.0) enabled, none disabled.
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
Enabled:
  - accessibility: 1.5.0
  - activity: 2.12.0
  - calendar: 2.0.3
  - cloud_federation_api: 1.2.0
  - comments: 1.9.0
  - contacts: 3.3.0
  - contactsinteraction: 1.0.0
  - dav: 1.15.0
  - federatedfilesharing: 1.9.0
  - federation: 1.9.0
  - files: 1.14.0
  - files_pdfviewer: 1.8.0
  - files_rightclick: 0.16.0
  - files_sharing: 1.11.0
  - files_trashbin: 1.9.0
  - files_versions: 1.12.0
  - files_videoplayer: 1.8.0
  - firstrunwizard: 2.8.0
  - logreader: 2.4.0
  - lookup_server_connector: 1.7.0
  - nextcloud_announcements: 1.8.0
  - notifications: 2.7.0
  - oauth2: 1.7.0
  - password_policy: 1.9.1
  - photos: 1.1.0
  - privacy: 1.3.0
  - provisioning_api: 1.9.0
  - recommendations: 0.7.0
  - serverinfo: 1.9.0
  - settings: 1.1.0
  - sharebymail: 1.9.0
  - support: 1.2.1
  - survey_client: 1.7.0
  - systemtags: 1.9.0
  - text: 3.0.1
  - theming: 1.10.0
  - twofactor_backupcodes: 1.8.0
  - updatenotification: 1.9.0
  - viewer: 1.3.0
  - workflowengine: 2.1.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_ldap

**Nextcloud configuration:**
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your instance's installation folder
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "himbaerchen.de",
            "192.168.178.243"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "default_language": "de",
        "default_locale": "de_DE",
        "defaultapp": "files",
        "dbtype": "mysql",
        "version": "19.0.0.12",
        "overwrite.cli.url": "https:\/\/himbaerchen.de\/nextcloud\/",
        "overwritehost": "himbaerchen.de",
        "overwritewebroot": "\/nextcloud",
        "overwriteprotocol": "https",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "loglevel": 2,
        "maintenance": false,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "theme": "",
        "updater.release.channel": "stable",
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\PDF"
        ]
    }
}


### Client configuration
**Browser:**
Firefox 68.9.0esr (64-Bit)

**Operating system:**
Debian 10.4

**CardDAV-clients:**

### Logs
#### *Web server error log*
```
Insert your webserver log here
```

### Nextcloud log
#### *data/nextcloud.log*
```
Insert your Nextcloud log here
```

#### Browser log
<details>
<summary>How to access your browser console (Click to expand)</summary>

# Chrome
- Press either CTRL + SHIFT + J to open the “console” tab of the Developer Tools.
- Alternative method:
    1. Press either CTRL + SHIFT + I or F12 to open the Developer Tools.
    2. Click the “console” tab.

# Safari
- Press CTRL + ALT + I to open the Web Inspector.
- See Chrome’s step 2. (Chrome and Safari have pretty much identical dev tools.)

# IE9
1. Press F12 to open the developer tools.
2. Click the “console” tab.

# Firefox
- Press CTRL + SHIFT + K to open the Web console (COMMAND + SHIFT + K on Macs).
- or, if Firebug is installed (recommended):
    1. Press F12 to open Firebug.
    2. Click on the “console” tab.

# Opera
1. Press CTRL + SHIFT + I to open Dragonfly.
2. Click on the “console” tab.
</details>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by skjnldsv** [comment]
@Dieter15 hey!

Can you reproduce this behaviour with other apps as well?

**Comment by Dieter15** [comment]
In Contacts I choose "German", NC switched to "German". This setting also 
survived a logout, that is "German" is still selected. Everything seems to 
be OK.

Thanks a lot for your suggestion to test with another app.

Best regards
Dieter
