### ISSUE TITLE
Number of contacts should be displayed in the navigation row of the group

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/contacts#17]
Instead of displaying it on the bottom of the list, the contact count of »Everyone« and all the individual groups should be displayed in the navigation. Just like for the User management and apps like Mail and News.

**Comment by skjnldsv** [comment]
@jancborchardt, see https://github.com/owncloud/contacts/pull/341

**Comment by jancborchardt** [comment]
@daniellandau can you open a pull request with the work in progress you have? :)

**Comment by daniellandau** [comment]
Ah, yes. It's done, but included in https://github.com/nextcloud/contacts/pull/88. Doesn't really make much sense in my opinion to try to break this off from the bigger whole.

**Comment by jancborchardt** [comment]
@daniellandau ah ok, thanks for the clarification! :)
