### ISSUE TITLE
Send/Recieve SMS directly from nextcloud contacts (with external provider api key) - recomendation/idea

### ISSUE THREAD

**Issue by ncusertest** [nextcloud/contacts#1702]
Hello. 

First of all, this might be out of the scope of the platform, but will recommend any way, and if it is please inform me or close the thread. 

Just signed up for this post. I started using nextcloud a few days ago and im really impressed and excited. This thing really solves a lot of problems! Now, on my recomendation, dont know If I could help, I believe I have the required knowledge to code, but I would like to start this as a recommendation and if people like it or someone thinks its simple enough to be done we could work together and add an app in the nextcloud app store that enables sending and receiving sms messages directly from the contacts page(like: chosing a contact with a phone saved, having an extra button to send an sms, or having en extra column on the right with sent and recieved sms messages history). Currently I have a provider (wont mention which to not be flagged as advertisement) that provides an easy enough api, I already use them for other web apps I have made to send OTP to my users. 

Configuring this would be as easy as if the user desires to use/enable it, should sign up with the provider ((even as nextcloud referal) - then add credit to his account there) and save his/her usename & api key in nextcloud/contacts - later on, maybe add a selection of providers that the user could choose from) - or go without any paid provider/gateway and having linked his/her phone as a gateway

So, Is this feature acceptable by the original devs, and seen as useful by other users? If so, I will check/study some (any) other nextcloud app works/gets implemented in the platform and begin developing it. 

I know, noone uses sms anymore, but they come handy for some applications or notifications.

Thanks for your time!
Will be closely monitoring for any replies :)

**Comment by skjnldsv** [comment]
Hey! Glad you're finding Nextcloud awesome and thanks for your interest  :)

I believe that would be the job for a dedicated app to be honest.
Contacts could integrate in it, but contacts should stay *just* a contacts manager imho.
For ease of use and maintainability (which is already hard enough) :see_no_evil:

**Comment by skjnldsv** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there a no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.
