### ISSUE TITLE
Add possibility to create virtual address book

### ISSUE THREAD

**Issue by Mannshoch** [nextcloud/contacts#171]
If possible I would like to share address books based on Categories.

I wish to share some personal data with other people by selected category and elements.
See Mokup
![grafik](https://cloud.githubusercontent.com/assets/7795891/24054748/8cca70f2-0b3d-11e7-8046-4a7862eb6773.png)

**Comment by jancborchardt** [comment]
This is out of scope for this app. There’s either:

- Sharing an address book, which is already possible
- Sharing a group: https://github.com/nextcloud/contacts/issues/212
- Sharing individual contacts: https://github.com/nextcloud/contacts/issues/111

**Comment by Mannshoch** [comment]
thanks @jancborchardt for comment it. Yes this solution is maybe a bit much enhanced, thats why I created the simpler idea #212 .

**Comment by jancborchardt** [comment]
@Mannshoch yeah, thank you for all the testing and suggestions. :) Much appreciated.
