### ISSUE TITLE
why cant i remove contact when its added by email app?

### ISSUE THREAD

**Issue by Pushergene** [nextcloud/contacts#1710]
![Screenshot_2020-07-18 Kontakte - Nextcloud](https://user-images.githubusercontent.com/26966213/87859259-3d6fd900-c923-11ea-9fd0-bb64c0602742.png)

**Comment by Pushergene** [comment]
![Screenshot_2020-07-18 Contacts - Nextcloud](https://user-images.githubusercontent.com/26966213/87860177-e968f280-c92a-11ea-84e0-45c42caf2db0.png)

On Other Account its completly greyed out i cant even add a Contact because of Mail App! HELLO?!?!?!

**Comment by skjnldsv** [comment]
Hey! Because this is just recently contacted contacts. This is a dynamic addressbook. You can disable it globally if you don't want this feature.

**Comment by Pushergene** [comment]
Yea, i solved it by disabling the App which collects data to share contacts, would be nice if the developers could make it easier to understand

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by skjnldsv** [comment]
Thanks for your feedback!
It's indeed not very discoverable if you're new to Nextcloud! Sorry for the trouble :)
