### ISSUE TITLE
Contacts: Importing is disabled because there are no address books available

### ISSUE THREAD

**Issue by freeztyler** [nextcloud/contacts#1717]
I have a Problem with Contacts: **"Importing is disabled because there are no address books available"**

![contacts](https://user-images.githubusercontent.com/68825800/88488277-624ff600-cf8c-11ea-81a3-66a8045a91c3.PNG)

**Comment by skjnldsv** [comment]
Hey, Please create an addressbook so you can create contacts into it.

**Comment by skjnldsv** [comment]
(should be done automatically, but there is a bug see #1635)

**Comment by skjnldsv** [comment]
Closing in favour of 1635
