### ISSUE TITLE
[Request/Improvement] Entry's => CleanDB Contacts Entrys (for clean re-import/ re-sync from Handy)

### ISSUE THREAD

**Issue by blackcrack** [nextcloud/contacts#1721]
Is your feature request related to a problem? Please describe.
Have wrong import the Contacts in Adminaccount ,
this was wrong, i had to edit directly my mariadb for clean it up the Entry Contacts entry of my Administrator account.

This could also happend with other Meeting-Entrys !

Describe the solution you'd like
In
<b>Configuration </b>
Contacts
[Name of Contactbook____]
Sorting
[Clean Contact Books]
[Import Contacts]

Clean Contact Books => Popup WAPPER (to see, it is important) =>

```
<h1>Clean up your Meeting Entry's in the DB</h1>
<h3>->Warning if you clean the Entry's must you import ics or rebuild your Meetingentry's again !<-</h3>
<b>Entry's</b>
<hr> 
ID|Name         | Entry's (Nr.) |       Warning+ all will deleted checkbox        | Cleanbuttons
----------------------------------------------------------------------------------------------------------------
2 Default         165   Warning, all data in Default is deleted in the DB !        [X]  [clean up/delete all entrys]
1 Contactbook3      4   Warning, all data in Contactbook3 is deleted in the DB !   [_]  [clean up/delete all entrys]<= gray
3 Contactbook2    164   Warning, all data in Contactbook2 is deleted in the DB !   [_]  [clean up/delete all entrys]<= gray
4 Contactbook4     90   Warning, all data in Contactbook4  is deleted in the DB !  [_]  [clean up/delete all entrys]<= gray
5 Contactbook5    120   Warning, all data in Contactbook5  is deleted in the DB !  [_]  [clean up/delete all entrys]<= gray
6 Contactbook6    111   Warning, all data in Contactbook6 is deleted in the DB !   [_]  [clean up/delete all entrys]<= gray
7 Contactbook1     95   Warning, all data in Contactbook1 is deleted in the DB !   [_]  [clean up/delete all entrys]<= gray
```
an Button for clean all Cav-Entry's in the Card-Entry's  

**Describe alternatives you've considered**
i had must edit via PHPMyAdmin the Entry and have clean it in the Root account because i have import
a user contacts.vcf with this root account..

**Additional context**
The Users should have the possibility for clean up his own entry's for fresh building up and hold the original Entry-Meeting-Name without extra delete and add without Administrator, therewith it is possible for hold the "ID" and the other in original in database and the original Place let untouched of the CardName

best
Backy
and yes, i have add a equal issue on a other app
the user should be in possible for clean up his entry in his account:
https://github.com/nextcloud/calendar/issues/2428

**Comment by skjnldsv** [comment]
Hi, same response from https://github.com/nextcloud/calendar/issues/2428
Sorry :)

Have a nice weekend! Stay safe!
