### ISSUE TITLE
Cannot switch contact after deleting address (t.trim is not a function)

### ISSUE THREAD

**Issue by stvogel** [nextcloud/contacts#1731]
1. Go to a contact and remove the address-field.
2. Try to switch to another contact by clicking on another contact in the left-navigation-bar ... you cannot switch

The error in the browser-console is:
```
vue.runtime.esm.js:1888 
TypeError: t.trim is not a function
    at contact.js:264
    at Array.filter (<anonymous>)
    at t.get (contact.js:264)
    at a.get (ContactDetails.vue:416)
    at dn.get (vue.runtime.esm.js:4479)
    at dn.evaluate (vue.runtime.esm.js:4584)
    at a.groups (vue.runtime.esm.js:4836)
    at a.<anonymous> (ContactDetails.vue?a439:14)
    at a.t._render (vue.runtime.esm.js:3548)
    at a.r (vue.runtime.esm.js:4066)
```
### Server configuration
**Operating system**: Linux
**Web server:** Apache
**Database:** MySQL 5.7.29
**PHP version:** 7.3.15
**Nextcloud version:** 19.0.1
**Contacts version:** 3.3.0

### Client configuration
**Browser:** Chrome

**Comment by skjnldsv** [comment]
Hey!
Thanks, fix is in https://github.com/nextcloud/contacts/pull/1732
Can you test this release?
[contacts.tar.gz](https://github.com/nextcloud/contacts/files/5015589/contacts.tar.gz)

**Comment by stvogel** [comment]
Wooooow. You're quick ... I don't know what to say.
I tested it out and it works like a charm. I tested it with my contacts (not the file you provided). Hope that's ok.

Thanks for your quick fix! That's so great.  Fixed in less than an hour!!

**Comment by skjnldsv** [comment]
Thanks for the help! :)
