### ISSUE TITLE
Exported contacts cannot be imported back.

### ISSUE THREAD

**Issue by devdan** [nextcloud/contacts#1733]
### Describe the bug
Exported contacts cannot be imported back.

**To Reproduce**
1. Export all contacts
2. Create a new user or clear address book
3. Import contacts from step 1.

**Expected behavior**
Contacts should be imported without errors

**Actual behavior**
Some contacts cannot be imported, no meaningful error message in browser console.
The cause of this consists of 2 parts.

1) Some contacts are exported with version 2.1 in the vcf file although the support for importing version 2.1 was removed from nextcloud. Why are some contacts still exported with version 2.1 while most are exported with version 3.0 or 4.0 and nextcloud does not even support importing version 2.1?

2) After changing the version from 2.1 to 3.0, the importer complained about multiple occurances of PRODID. In my case, this occured in all contacts with version 2.1 so there should be some kind of relation. After removing the duplicate PRODID tags, all contacts could be imported.

### Server configuration

**Operating system**:  Linux

**Web server:** Apache

**Database:** MySQL

**PHP version:** 7.3

**Nextcloud version:** 18

**Contacts version:** (see Nextcloud apps page)

**Updated from an older Nextcloud or fresh install:** export on old version, import on fresh install

**Signing status:**
```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

### Client configuration
**Browser:** Firefox

**Operating system:** Linux

**Comment by skjnldsv** [comment]
> **Expected behavior**
> Contacts should be imported without errors

Hey!
So, your contacts are not valid, of course they won't be accepted.
How do you think we should fix/correct the vCards in such cases?

**Comment by skjnldsv** [comment]
Closing as there is other opened issues for 2.1 cards
