### ISSUE TITLE
Contacts App export not work with utf8mb4

### ISSUE THREAD

**Issue by jaynj** [nextcloud/contacts#1742]
### Expected behaviour
When exporting the address book using the contacts app on desktop, the resulting vcf file contains unreadable contents
which caused errors when restoring it later.

### Actual behaviour
The address book contains Chinese characters.  Errors generated when restoring the vcf.

### Steps to reproduce
1. Desktop->Contacts->All contacts->Download->vcf
2. truncate oc_cards and oc_cards_properties tables;
3. Desktop->Contacts->Settings->Import -> Many records are flagged as errors.

### Client configuration
Client version:

Operating system:
Ubuntu 18.04

OS language:
English

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From Nextcloud or distro) (Linux only):

Installation path of client:

### Server configuration

Nextcloud version:
19.0.1

Storage backend (external storage):

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: Output of `nextcloud --logwindow` or `nextcloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the Nextcloud directory)
(See also https://docs.nextcloud.com/desktop/2.3/troubleshooting.html#log-files)

2. Web server error log:

3. Server logfile: nextcloud log (data/nextcloud.log):

**Comment by skjnldsv** [comment]
Hello!
I will need your browser console log to investigate this issue.
Open your console, reload your page and/or do the action leading to this issue and copy/paste the log in this thread.

<details>
<summary>How to access your browser console (Click to expand)</summary>

# Chrome
- Press either CTRL + SHIFT + J to open the “console” tab of the Developer Tools.
- Alternative method:
    1. Press either CTRL + SHIFT + I or F12 to open the Developer Tools.
    2. Click the “console” tab.

# Safari
- Press CMD + ALT + I to open the Web Inspector.
- See Chrome’s step 2. (Chrome and Safari have pretty much identical dev tools.)

# IE9
1. Press F12 to open the developer tools.
2. Click the “console” tab.

# Firefox
- Press CTRL + SHIFT + K to open the Web console (COMMAND + SHIFT + K on Macs).
- or, if Firebug is installed (recommended):
    1. Press F12 to open Firebug.
    2. Click on the “console” tab.

# Opera
1. Press CTRL + SHIFT + I to open Dragonfly.
2. Click on the “console” tab.
</details>

**Comment by creopard** [comment]
Does this also relate to #1749?
Maybe also using mixed Vcard versions, e.g. 3.0 and 4.0?

**Comment by skjnldsv** [comment]
Yes, most likely.
If I don't have the logs, I cannot tel anyway.
