### ISSUE TITLE
Nextcloud Contacts flags DAVx5 edits as broken (again, see closed issues)

### ISSUE THREAD

**Issue by LDAP** [nextcloud/contacts#1749]
### Describe the bug
Nextcloud Contacts flags DAVx5 edits as broken

**To Reproduce**
1. Edit a contact on an android device
2. Sync the contact using davx5 3.2.1.4-play to nextcloud
3. Open the contact on nextcloud contacts

**Expected behavior**
no warning should be displayed

**Actual behavior**
nextcloud warns about broken contact

**Screenshots**
![grafik](https://user-images.githubusercontent.com/8215084/90330890-8e213300-dfb0-11ea-8363-a8658a363a68.png)

### Server configuration

**Operating system**: Windows, Linux, MacOS...
Linux
**Web server:** Apache, Nginx...
Nginx
**Database:** MariaDB, MySQL, PostgreSQL... 
PostgreSQL 12.3
**PHP version:** 7.0, 7.1, 7.2...
7.3.21
**Nextcloud version:** (see Nextcloud admin page)
19.01
**Contacts version:** (see Nextcloud apps page)
3.3.0
**Updated from an older Nextcloud or fresh install:**
Updated from Nextcloud 18
**Signing status:**
```
No errors have been found.
```

### Client configuration
**Browser:**
-
**Operating system:**
Android
**CardDAV-clients:**
DAVx5
#### *Web server error log*
```
empty
```

#### *data/nextcloud.log*
```
empty
```

#### Browser log
<details>
<summary>How to access your browser console (Click to expand)</summary>

# Chrome
- Press either CTRL + SHIFT + J to open the “console” tab of the Developer Tools.
- Alternative method:
    1. Press either CTRL + SHIFT + I or F12 to open the Developer Tools.
    2. Click the “console” tab.

# Safari
- Press CTRL + ALT + I to open the Web Inspector.
- See Chrome’s step 2. (Chrome and Safari have pretty much identical dev tools.)

# IE9
1. Press F12 to open the developer tools.
2. Click the “console” tab.

# Firefox
- Press CTRL + SHIFT + K to open the Web console (COMMAND + SHIFT + K on Macs).
- or, if Firebug is installed (recommended):
    1. Press F12 to open Firebug.
    2. Click on the “console” tab.

# Opera
1. Press CTRL + SHIFT + I to open Dragonfly.
2. Click on the “console” tab.
</details>

```
no browser used
```

**Comment by skjnldsv** [comment]
Let's take a different approach yes :)

**Comment by kangaroo72** [comment]
That's an confusing annoying problem since months for me, now I have the root cause. THANK YOU!!

**Comment by skjnldsv** [comment]
Yes, this is a really annoying bug :p

**Comment by creopard** [comment]
Didn't the PR #1597 already fix this?

**Comment by skjnldsv** [comment]
No, apparently not

**Comment by blue-bean** [comment]
I also have this problem since months... (DAVx5 and Nextcloud 18, both always up to date)

**Comment by bugspencor** [comment]
I'm running into a similar problem with the CardBook extension on Thunderbird.

See here: https://gitlab.com/CardBook/CardBook/-/issues/887 (I'm not the reporter of that issue)

As far as I can see PR #1597 is not included in a release yet. @LDAP: Are you running a development-snapshot of the contacts app? Is there an easy way to run development snapshot of Contacts?

**Comment by LDAP** [comment]
> 
> 
> I'm running into a similar problem with the CardBook extension on Thunderbird.
> 
> See here: https://gitlab.com/CardBook/CardBook/-/issues/887 (I'm not the reporter of that issue)
> 
> As far as I can see PR #1597 is not included in a release yet. @LDAP: Are you running a development-snapshot of the contacts app? Is there an easy way to run development snapshot of Contacts?

I am running the offical stable release.

**Comment by sutidor** [comment]
contacts 3.4.0 release solved this for me
