### ISSUE TITLE
Missing UID in contact data

### ISSUE THREAD

**Issue by milgner** [nextcloud/contacts#175]
### Steps to reproduce
1. Upgraded to Nextcloud 11, contacts app 1.5.3
2. Open contacts app
3. Javascript console shows error:

```
contact_model.js:30 Uncaught (in promise) TypeError: Cannot read property 'value' of undefined
    at Contact.uid (contact_model.js:30)
    at contact_service.js:37
```

4. Spinning wheel, no contacts shown.

### Expected behaviour
My contacts should be displayed :)

### Actual behaviour
It looks like the app is trying to access the `UID` property and there isn't any. I debugged into the code in question which says

```javascript
return model.getProperty('uid').value;
```

Accessing other data like `email()` works just fine. So now I'm wondering why it suddenly complains about a missing UID and whether there might have been a migration that was supposed to run but didn't during upgrade?
Is there any way to add new UID to those contacts missing them?

I know my way around MySQL so if you have an idea what should go where, I'll gladly write a migration script myself :wink:

**Comment by skjnldsv** [comment]
I don't see why a contact won't have any uid set!
importing create uid for each before storing it to the db and the dav server will refuse any vcard without uid. Did you edit your database?

**Comment by milgner** [comment]
Yes, it's quite baffling. I did not edit the database. The CardDAV sync on my phone works just fine, too.

**Comment by skjnldsv** [comment]
Hum, could come from an external sync indeed. We need to prevent this from happening.

**Comment by irgendwie** [comment]
Aren't cards without an UID rejected by the carddav backend in nextcloud/server?

**Comment by skjnldsv** [comment]
Apparently not! 🤔

**Comment by skjnldsv** [comment]
UIDs are automatically created on import and create in the contacts app. This needs to be created on https://github.com/nextcloud/server

**Comment by wirepatch** [comment]
I do have the very same problem affecting only one user on my system (11.0.4 / 1.5.3). Having `'loglevel' => 0` / Debug enabled an attempt exporting the adressbook yields an internal server error:

```
Internal Server Error:
Technical details

Remote Address: 141.62.31.244
Request ID: 0yPQDknmq8xphI1UeOez
```

Nginx's `{access|error}.log` reveals nothing. Any advice greatly welcome.

**Comment by skjnldsv** [comment]
Look at your nextcloud.log file into the data folder! :)
