### ISSUE TITLE
Deletet Contacts, how to get it back?

### ISSUE THREAD

**Issue by HueDa90** [nextcloud/contacts#1750]
Deletet Contacts, how to get it back?

i tried to delete a contact group, but now delted all contacts.

![image](https://user-images.githubusercontent.com/55594684/90336014-4f53a300-dfd9-11ea-8737-e83ae2a9421c.png)

how to get it back?

### Describe the bug
......
......

**To Reproduce**

**Expected behavior**
Tell us what you expected to happen.

**Actual behavior**
Tell us what happened instead.

**Screenshots**

### Server configuration

**Operating system**: Windows, Linux, MacOS...

**Web server:** Apache, Nginx...

**Database:** MariaDB, MySQL, PostgreSQL... 

**PHP version:** 7.0, 7.1, 7.2...

**Nextcloud version:** (see Nextcloud admin page)

**Contacts version:** (see Nextcloud apps page)

**Updated from an older Nextcloud or fresh install:**

**Signing status:**
```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

**List of activated apps:**
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**Nextcloud configuration:**
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your instance's installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

### Client configuration
**Browser:**

**Operating system:**

**CardDAV-clients:**

#### *Web server error log*
```
Insert your webserver log here
```

#### *data/nextcloud.log*
```
Insert your Nextcloud log here
```

#### Browser log
<details>
<summary>How to access your browser console (Click to expand)</summary>

# Chrome
- Press either CTRL + SHIFT + J to open the “console” tab of the Developer Tools.
- Alternative method:
    1. Press either CTRL + SHIFT + I or F12 to open the Developer Tools.
    2. Click the “console” tab.

# Safari
- Press CTRL + ALT + I to open the Web Inspector.
- See Chrome’s step 2. (Chrome and Safari have pretty much identical dev tools.)

# IE9
1. Press F12 to open the developer tools.
2. Click the “console” tab.

# Firefox
- Press CTRL + SHIFT + K to open the Web console (COMMAND + SHIFT + K on Macs).
- or, if Firebug is installed (recommended):
    1. Press F12 to open Firebug.
    2. Click on the “console” tab.

# Opera
1. Press CTRL + SHIFT + I to open Dragonfly.
2. Click on the “console” tab.
</details>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by skjnldsv** [comment]
> i tried to delete a contact group, but now delted all contacts.

What did you do to delete this?
If you deleted the addressbook, you can't get it back :(

**Comment by HueDa90** [comment]
Problem is solved. I could make a new one. Just tried all things my users could do. Close ticket please. Thank you
