### ISSUE TITLE
"Recently contacted" address book shows up in email clients

### ISSUE THREAD

**Issue by janvlug** [nextcloud/contacts#1762]
### Describe the bug
The "Recently contacted" address book showed up in GNOME Evolution and Thunderbird after an upgrade to Nextcloud 19. I use GNOME Online Accounts to access online accounts on my Fedora systems.
I do not want a "Recently contacted" address book to be shared over all my systems.

As a side note, the "Recently contacted" address book is not very present in the Nextcloud web interface to Nextcloud Contacts. I have to go to Settings to actually see this address book. There is no sharing indicator as well. This made it non-intuitive to find this new address book in Nextcloud.

**To Reproduce**
1. Start with Nextcloud 18.
2. Set up your Nextcloud account in GNOME Online Accounts.
3. Upgrade to Nextcloud 19.

**Expected behavior**
No new automatically added "Recently contacted" address book in your email clients on other systems.

**Actual behavior**
All my email clients showed (the detection) of a "Recently added" address book.

**Operating system**: Fedora Linux with GNOME Wayland

**Nextcloud version:** 19.0.2

**Contacts version:** 3.3.0

**Updated from an older Nextcloud or fresh install:** Updated from latest 18 version

See also:
https://bugzilla.mozilla.org/show_bug.cgi?id=1661651

**Comment by skjnldsv** [comment]
Hey! This is on purpose, :)
Just ignore/disable the sync in your clients.
