### ISSUE TITLE
Add a new contact number from Url

### ISSUE THREAD

**Issue by b2cbd** [nextcloud/contacts#1768]
Is there any way to add a contact number from the URL ( `something like this /app/contacts/add?number=+1XXX` ) which will open the contact app and fill up the number as new contact? So that I can integrate with external applications.

**Comment by skjnldsv** [comment]
Hey!
There is currently no way to create contacts dynamically.

**Comment by b2cbd** [comment]
@skjnldsv  Oops! Perhaps - is there any way to create a contact from another nextcloud app?

**Comment by skjnldsv** [comment]
We're using carddav, so any app wanting to push a vcard to your carddav endpoint will work really :)

**Comment by skjnldsv** [comment]
I'll close as I don't think this fits the issue tracker :)
