### ISSUE TITLE
Read-only duplicate contact. How to delete? How to remove read-only so I can edit?

### ISSUE THREAD

**Issue by whisperdancer** [nextcloud/contacts#1772]
Raspberry Pi OS
Nextcloud 19.0.2
Nginx 1.14.2
PHP 7.3
Contacts Latest Version

I have a single address book.

I have a duplicate contact and it's read-only. I try to delete it by clicking the 3 dots and there is no delete option because it's read-only. I have no idea how this contact was created. I didn't create it and I'm the only user on this server. How can I delete it?

I have other read-only contacts. I can't edit them or delete them. Where did they come from and how do I remove the read-only status?

Thank you.

**Comment by skjnldsv** [comment]
Hey! What addressbook is it coming from?

**Comment by whisperdancer** [comment]
I only have one address book, contacts

**Comment by skjnldsv** [comment]
What do you mean by "readonly" then?
Can you do a screenshot of the main UI with the bottom left settings opened please?

**Comment by whisperdancer** [comment]
<img width="217" alt="cap2" src="https://user-images.githubusercontent.com/8562620/92314465-90adf180-ef8c-11ea-8c41-18639c56fd24.PNG">
<img width="296" alt="Capture" src="https://user-images.githubusercontent.com/8562620/92314466-9277b500-ef8c-11ea-91e5-8f88fce7ad97.PNG">

**Comment by skjnldsv** [comment]
So this is a contact from the "recently contacted addressbook", this is a new feature with nc19.

**Comment by Leprazoriy** [comment]
How do I delete these contacts? The fields are filled in incorrectly! Why are they created? How can I turn off their automatic creation?

**Comment by skjnldsv** [comment]
Disable the recently contacted app

**Comment by Leprazoriy** [comment]
Name of this app is Contacts Interaction?

**Comment by skjnldsv** [comment]
Yep!
You can also read the releases announcements/changelog This is all written there :rocket:
