### ISSUE TITLE
Improve addressbook creation UI

### ISSUE THREAD

**Issue by Galiwyx** [nextcloud/contacts#1773]
### Describe the bug
I can't create an address book

**To Reproduce**
1. I use docker version of Nextcloud
2. Install Contact App

**Expected behavior**
No adress book available, nothing happens when I click on "Contacts: Importing is disabled because there are no address books available"

**Screenshots**
![image](https://user-images.githubusercontent.com/206181/92184029-47588780-ee50-11ea-957e-08197560594a.png)

### Server configuration
Operating system: Linux 4.19.107-Unraid #1 SMP Thu Mar 5 13:55:57 PST 2020 x86_64

Webserver: nginx/1.18.0 (fpm-fcgi)

Database: mysql 10.4.14

PHP version:

7.3.21 Modules loaded: Core, date, libxml, pcre, zlib, filter, hash, readline, Reflection, SPL, session, cgi-fcgi, bcmath, bz2, ctype, curl, dom, fileinfo, ftp, gd, gmp, iconv, intl, json, ldap, mbstring, openssl, pcntl, PDO, pgsql, posix, standard, SimpleXML, smbclient, sodium, sqlite3, xml, xmlwriter, zip, exif, imap, mysqlnd, pdo_pgsql, pdo_sqlite, Phar, xmlreader, pdo_mysql, apcu, igbinary, redis, memcached, imagick, mcrypt, libsmbclient, Zend OPcache

Nextcloud version: 19.0.1 - 19.0.1.1

**Comment by skjnldsv** [comment]
> I can't create an address book

What happen when create an address book?

**Comment by Galiwyx** [comment]
I can't, I must click on the button right?

**Comment by skjnldsv** [comment]
No, there is an input with "Address book name" on your screenshot, enter a name and press enter or the arrow to submit the creation.

**Comment by Galiwyx** [comment]
oh okay, it's working, I'm dumb...

**Comment by skjnldsv** [comment]
You're not!
Do you have any suggestion on how to make that a bit more straightforward?

**Comment by Galiwyx** [comment]
For me the right arrow isn’t very representative. I thin it was a search field, not a « create » field.

**Comment by skjnldsv** [comment]
@jancborchardt what about another settings in the bottom for address books?
I feel it would be much easier to understand :)

![Capture d’écran_2020-09-06_16-29-14](https://user-images.githubusercontent.com/14975046/92328020-29f90880-f05e-11ea-8a97-3b22dd451346.png)

**Comment by skjnldsv** [comment]
So, I actually found https://github.com/nextcloud/contacts/issues/1703
Which is pretty close to this, let's discuss it there.
