### ISSUE TITLE
Possibility for Custom Labels?

### ISSUE THREAD

**Issue by uwsvps** [nextcloud/contacts#178]
Hello,

I am currently running the nightly build as of March 24, 2017. I was curious as to whether it would be possible to add custom fields to certain fields? E.g.; Instead of Home, Work, or Mobile, being able to enter any custom text such as iPhone, Android, etc... Attached is a picture of what I am trying to achieve. I apologize if this has already been discussed and if so can someone please direct me to the correct location?
![contacts application](https://cloud.githubusercontent.com/assets/26662779/24317382/76a33c46-10c4-11e7-89d1-0f7d7c6fc37c.png)

**Comment by olantrust** [comment]
Good point. However, fields are 'phone, email, address, notes' etc...
What you are referring to are 'labels' ('home, work' etc..)
Please re-label this issue as 'Custom labels' rather than 'Custom fields'.

**Comment by olantrust** [comment]
@uwsvps Please give this a new title, as it is misleading.
What this issue is addressing is not about custom fields, it is about LABELS.
Thanks

**Comment by rkkoszewski** [comment]
Hi, any news on this? It would be really useful to set custom labels for the phone numbers.  Especially if you have contacts with multiple phone numbers for different countries (I use the country as label in Google).

**Comment by DidierLmn** [comment]
Indeed, when syncing with iOS and Mac you can already add custom labels and they are synced correctly, but the Nextcloud webinterface doesn’t show them, it displays a blank label.
I'd be great if this could be added.

**Comment by skjnldsv** [comment]
Duplicate #27
