### ISSUE TITLE
Import 5mb .vcf file skips some contacts / abborts

### ISSUE THREAD

**Issue by Matthias84** [nextcloud/contacts#1793]
### Describe the bug
You can't import larger .vcf files like 5mb. The import is incomplete and lacks a lot of items.
As a workaround you can splitup your files to 2.5mb chunks, which worked for me. Similar to this bug in calendar https://github.com/nextcloud/calendar/issues/2570

**To Reproduce**
1. Export your calendar on your old nextcloud -> 5MB .VCF file
2. Create default adressbook on your new nextcloud
3. Choose import Calendar-file
4. _(no feedback anymore)_

### Expected behaviour
The import should successfully import all items. If there are problems, I want to get notified and the detail information to understand the problems.

### Actual behaviour
Only some items are imported, which seems to be a regression as the size might cause some timeouts. Unfortunately, you don't get feedback on progress, or that some items are still missed, which might be related to a better UX like #990 suggests.

### Server configuration

**Operating system**: centos

**Web server:** nginx

**Database:** mariadb

**PHP version:** 7.0, 7.1, 7.2...

**Nextcloud version:** 19.0.2

**Contacts version:** latest

**Updated from an older Nextcloud or fresh install:** fresh

### Client configuration
**Browser:** Firefox 80

**Operating system:** Linux Mint 20

**Comment by robertdebock** [comment]
I've got a similar issue; I'm trying to import [20000 fake contacts](https://github.com/nextcloud/contacts/files/6349377/fake-contacts.vcf.zip).

The first few 100 contacts are imported, and at some moment errors are starting to show and the import stops.

The moment where the import stops seems quite random, sometimes I'm able to import 48, sometimes 1233.

The machine I'm trying this on is a newly installed, updated NextCloud deployment.

I've generated a [support report](https://github.com/nextcloud/contacts/files/6349438/2021-04-21.md).

**Comment by joshtrichards** [comment]
> The import should successfully import all items. If there are problems, I want to get notified and the detail information to understand the problems.

The better reporting on errors/imports is covered in #990 as noted. As for the size for imports, even Google doesn't support importing very many contacts at once[1] and suggests breaking things up. But, yes, I agree the UX could still be better. Let's keep #990 for that.

[1] https://support.google.com/contacts/answer/1069522?hl=en&co=GENIE.Platform%3DDesktop#zippy=%2Ccant-import-my-contacts

> The first few 100 contacts are imported, and at some moment errors are starting to show and the import stops.

The 20000 fake contacts import is a fairly worst case scenario.  Google Contacts, as an example, only supports 3,000 at a time. With better reporting entries that error out can be identified. Let's stick to #990 for that.
