### ISSUE TITLE
Connecting cardDAV to ios is very difficult and not usable.

### ISSUE THREAD

**Issue by acobb12** [nextcloud/contacts#1802]
Connecting contacts via cardDAV is very difficult. I can connect contact with every other email client other than iOS. Thanks!

**Comment by skjnldsv** [comment]
Hi! This issue is lacking a lot of details! Have you checked te docs? What issues are you experiencing ?

**Comment by nursoda** [comment]
I did this on two devices and it was a breeze – all you need to know is that iOS expects you to head to Accounts, and add a "CardDAV" account. Enter domain, username, password (or App-PIN if you use 2FA), sync. Ready. As described in docs.nextcloud.com … so: What was YOUR issue?

**Comment by skjnldsv** [comment]
Yes, because it's also nicely explained on our docs
https://docs.nextcloud.com/server/stable/user_manual/pim/sync_ios.html

Closing, feel free to open a pr on the documentation if you want to enhance the manual :)
https://github.com/nextcloud/documentation/edit/master/user_manual/pim/sync_ios.rst
