### ISSUE TITLE
Integrate LDAP contacts

### ISSUE THREAD

**Issue by svalentin1984** [nextcloud/contacts#1806]
**Is your feature request related to a problem? Please describe.**

It would be extremely needed to integrate LDAP contacts into a user addressbook. In such a way an administrator may share this address book to all the users.

Currently, after configuring LDAP, all the contacts are added to the system address book which is extremely inefficient thus they are not accessible in the user's address book via remote CardDav. Also, the LDAP contacts in the system address book are only visible when searching and no contact details are provided there (beside email). The System address book cannot be displayed the same way as a user address book.

**Describe the solution you'd like**
The possibility to create an address book in the Contacts app and integrate the LDAP users in that address book (without duplicating the system address book entry). 

Another solution would be to improve the system address book and make it more accessible and visible (as a user address book)

**Describe alternatives you've considered**
A possible workaround I used is to export the current system address book containing the LDAP contacts using davfs and import it to an existing address book (also using davfs). However, this solution duplicates the contacts (for example in search, duplicated contacts appear - one from the user address book and one from the system address book). 

The LDAP connector in Nextcloud brings the defined attributes of each user from the LDAP server, but most of those attributes are not visible and not exported via the vCard files of the system address book (only First Name, Last Name, Other email and picture)

The ldap_backend app tries to provide some features but still can't be used to provide a viable solution.

**Comment by skjnldsv** [comment]
cc @blizzz

**Comment by MohammedNoureldin** [comment]
Any new regarding this?

**Comment by blizzz** [comment]
Probably solved by https://apps.nextcloud.com/apps/ldap_contacts_backend ?

**Comment by MohammedNoureldin** [comment]
@blizzz actually not, because it does not have CardDav forthe LDAP contacts. Or am I missing anything?

**Comment by LazyGatto** [comment]
Need this feature too.
Without LDAP global address book - it is impossible to use Contacts App in companies in right way :(
