### ISSUE TITLE
Address book setup in Thunderbird (Cardbook) fails to validate (error enclosed)

### ISSUE THREAD

**Issue by wgregori** [nextcloud/contacts#181]
I'm using nextcloud 11.0.2 with Contacts 1.5.3.  I've been having troubles adding addressbooks to Thunderbird (add-on Cardbook).  I've been using Cardbook and Thunderbird for a long time.  The address books that are already setup work fine.  When I try to setup a new address book I get this error during the 'validation' process.

2017.03.30 17:49:22:006 : Validation module : Validating without discovery request on https://cloud.gregorigroup.com/remote.php/dav/addressbooks/users/rmendieta/contacts/ ...
2017.03.30 17:49:22:175 : Validation module : Impossible to parse the server response because of this line : 					</head>
------------------------------------------^

Thanks

**Comment by irgendwie** [comment]
Sorry, can't reproduce the problem on my side. Would you mind providing additional information, like the nextcloud log and/or additional logging from the Cardbook addon?

**Comment by wgregori** [comment]
Here is the log file from Nextcloud (sorry I did not include this)
	Sabre\DAV\Exception\NotFound: HTTP/1.1 404 Addressbook with name 'contacts' could not be found

    /var/www/nextcloud/apps/dav/lib/Connector/Sabre/DavAclPlugin.php - line 85: OCA\DAV\Connector\Sabre\DavAclPlugin->checkPrivileges('addressbooks/us...', '{DAV }read', 1, true)
    [internal function] OCA\DAV\Connector\Sabre\DavAclPlugin->propFind(Object(Sabre\DAV\PropFind), Object(OCA\DAV\CardDAV\AddressBook))
    /var/www/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105: call_user_func_array(Array, Array)
    /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 1035: Sabre\Event\EventEmitter->emit('propFind', Array)
    /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 955: Sabre\DAV\Server->getPropertiesByNode(Object(Sabre\DAV\PropFind), Object(OCA\DAV\CardDAV\AddressBook))
    /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php - line 336: Sabre\DAV\Server->getPropertiesForPath('addressbooks/us...', Array, 1)
    [internal function] Sabre\DAV\CorePlugin->httpPropFind(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
    /var/www/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105: call_user_func_array(Array, Array)
    /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 479: Sabre\Event\EventEmitter->emit('method PROPFIND', Array)
    /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 254: Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
    /var/www/nextcloud/apps/dav/lib/Server.php - line 227: Sabre\DAV\Server->exec()
    /var/www/nextcloud/apps/dav/appinfo/v2/remote.php - line 30: OCA\DAV\Server->exec()
    /var/www/nextcloud/remote.php - line 165: require_once('/var/www/nextcl...')
    {main}


This is the only Thunderbird (Cardbook) log I could find:

2017.04.01 09:23:23:347 : Validation module : Validating without discovery request on https://cloud.gregorigroup.com/remote.php/dav/addressbooks/users/rmendieta/contacts/ ...
2017.04.01 09:23:24:438 : Validation module : Impossible to parse the server response because of this line : 					</head>
------------------------------------------^

Thanks,
Wayne

**Comment by irgendwie** [comment]
> Sabre\DAV\Exception\NotFound: HTTP/1.1 404 Addressbook with name 'contacts' could not be found

Sounds like you are trying to access a non-existing address book. Please make sure the you did type the URL correctly (or just copy it from the contacts app in the settings area), otherwise please provide the error log to the developers of Cardbook. Maybe they can narrow the error down.
