### ISSUE TITLE
email address not shown in minimal contact in Contacts 3.4.0

### ISSUE THREAD

**Issue by nursoda** [nextcloud/contacts#1812]
### Describe the bug
Thunderbird CardBook added a contact to my NC for a mail address that was unknown. When I displayed that contact in contacts web UI, I didn't see an email address – which is odd because CardBook would only add the contact (to its "collected new contacts" group) if id had an address.

So there are at least cases that a valid email address isn't shown in contact details. It is shown in the contacts list however, so it's parsed correctly.

I was able to reproduce the bug by importing the attached file, which I exported through the contacts web app, redacted some entries using a text editor.

**To Reproduce**
1. validate the attached file, should be valid vCard 3.0
2. import the attached file in Contacts web app
3. reload Contacts by clicking on it in NC headline menu
4. select test contact to display its content

**Expected behavior**
Email address should be visible in the contacts list AND in the details.

**Actual behavior**
Email address is visible in the contacts list but NOT in the details.

**vCard**
```
BEGIN:VCARD
VERSION:3.0
PRODID:-//vi/CardBook V51.7//EN
UID:2ab1f9ac-cf5c-718d-f5e8-61ac0e6843cc
FN:test
EMAIL:test@domain.org
REV:2020-09-30T18:18:00Z
END:VCARD
```

**Screenshot**
![NoEmail](https://user-images.githubusercontent.com/8425483/94711784-e0dc6180-0348-11eb-9ede-7fca36913bd4.png)

### Configuration
Arch Linux (current), NGINX 1.18, PHP-FPM 7.4, MariaDB 10.5
Nextcloud 19.0.3.1, Contacts 3.4.0, NC: updated, Signing: OK
Browser: Firefox 81.0 on Arch Linux (current), CardDAV-clients: TB CardBook (yet not relevant here!)

**Comment by skjnldsv** [comment]
Hi! 
Please add the console log on your upcoming issues report :wink: 

```
vue.runtime.esm.js:1888 TypeError: Cannot read property 'placeholder' of null
    at i.<anonymous> (PropertyText.vue?a04c:1)
    at i.e._render (vue.runtime.esm.js:3548)
```

**Comment by fgtham** [comment]
I see a related problem in version 3.4.0, where a contact's telephone number is not always displayed, e.g.:

![2020-10-01-135018_1920x1080_scrot](https://user-images.githubusercontent.com/1180356/94806765-cfe62b80-03ee-11eb-8391-31977e00aa36.png)

As you can see in the screenshot, the phone number is present in the jCal array.

It appears to be an issue only with some contacts, though.

Console log:

```
TypeError: Cannot read property 'placeholder' of null
    at i.<anonymous> (PropertyText.vue?a04c:1)
    at i.e._render (vue.runtime.esm.js:3548)
    at i.r (vue.runtime.esm.js:4066)
    at An.get (vue.runtime.esm.js:4479)
    at new An (vue.runtime.esm.js:4468)
    at e (vue.runtime.esm.js:4073)
    at i.Tn.$mount (vue.runtime.esm.js:8415)
    at init (vue.runtime.esm.js:3118)
    at vue.runtime.esm.js:5978
    at m (vue.runtime.esm.js:5925)
```
