### ISSUE TITLE
Group cannot be deleted while it is selected

### ISSUE THREAD

**Issue by nursoda** [nextcloud/contacts#1813]
### Describe the bug
While testing groups in Contacts I noticed that if one selects a group of contacts, and edits one of the selected group, I cannot delete THAT group from the contact. I think this was different before: In prior version that contact still would remain to be displayed in the details section while it disappeared in the contacts list (since it no longer belonged to this group). Now, It disappears completely (which is OK also), but it should be saved before.

It is possible to select "all contacts" and remove the group then of course. However, if you have many contacts, that's not handy.

**To Reproduce**
1. have one contact 'test' in a group 'test'
2. select it
3. delete its group by "removing" the checkmark within the group dropdown (in the contact details section on the right hand side)

**Expected behavior**
Contact should be saved without the group set that was just deleted.

**Actual behavior**
Removal of this group is not saved.

### Configuration
Arch Linux (current), NGINX 1.18, PHP-FPM 7.4, MariaDB 10.5
Nextcloud 19.0.3.1, Contacts 3.4.0, NC: updated, Signing: OK
Browser: Firefox 81.0 on Arch Linux (current)

**Comment by skjnldsv** [comment]
Thank you so much for testing the 3.4.0 @nursoda :)
