### ISSUE TITLE
No longer able to disregard year in birthday

### ISSUE THREAD

**Issue by keunes** [nextcloud/contacts#1814]
### Describe the bug
I just updated the Contacts app. I now can no longer able to disable/hide/ignore the year in the birthday, something I'm convinced was possible before

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to a contact without a birthday
2. Click on 'Add new property' and select 'Birthday'
3. Hover the three dots, and click it

**Expected behavior**
Have a menu which allows to delete, and hide/ignore the year in this field

**Actual behavior**
Clicking changes the three dots into a delete button.

**Screenshots**
![Screenshot_2020-09-30 Contacts - Nextcloud](https://user-images.githubusercontent.com/11229646/94738164-50654780-036f-11eb-9a4f-8746af840e85.png)
![Schermafdruk van 2020-09-30 22-44-51](https://user-images.githubusercontent.com/11229646/94738162-4fccb100-036f-11eb-9e17-1aafe060333a.png)

### Server configuration
**Nextcloud version:** 19.0.3

**Contacts version:** 3.4.0

**Updated from an older Nextcloud or fresh install:** fresh

**Comment by keunes** [comment]
Also, the three dots show on first loading a contact, but after the 'Delete' button has been shown when moving away (end hover), the trash icon and the three dots disappear. Not sure if that's intended, but either way it feels inconsistent (like something is wrong).

**Comment by tessus** [comment]
Yes, it was possible before. Now you can't enter a birthday without a year.

Workaround: I enter the birthday without a year on my phone and sync. Kind of embarrassing, but hey, what can you do.

**Comment by keunes** [comment]
Those who upvoted this issue: are you actually able to set a birthday at all, now (in the browser app)? I just tried, with Contacts app version 3.4.2, and when I select a date (even including a year) via the date-picker, this date doesn't get stored. @3c7 @Luzifer @call-me-matt @tessus @csware

**Comment by 3c7** [comment]
> 
> 
> Those who upvoted this issue: are you actually able to set a birthday at all, now (in the browser app)? I just tried, with Contacts app version 3.4.2, and when I select a date (even including a year) via the date-picker, this date doesn't get stored. @3c7 @Luzifer @call-me-matt @tessus @csware

Yes, I'm able to set the birthday.

**Comment by SebastianKrupinski** [comment]
Tested. This has been fixed.
