### ISSUE TITLE
Hamburger menu shown on a contact

### ISSUE THREAD

**Issue by keunes** [nextcloud/contacts#1816]
### Describe the bug
A hamburger menu is shown on a contact in the list. Looks weird, and not sure why it's there.

**To Reproduce**
It seems always there. Already noticed it before the recent (3.4.0) update. 

**Expected behavior**
Not have this hamburger menu.

**Actual behavior**
Seems to close the whole sidebar, but it's ugly and placed outside of the element it's acting on. Maybe it's meant to be there on mobile only?

**Screenshots**
![Screenshot_2020-09-30 Contacts - Nextcloud - hamburger](https://user-images.githubusercontent.com/11229646/94740464-02524300-0373-11eb-8556-359bd66c3c31.png)

### Server configuration
**Nextcloud version:** 19.0.3
**Contacts version:** 3.4.0

**Comment by skjnldsv** [comment]
> Maybe it's meant to be there on mobile only?

Nope, thi sis a new feature now, we also allow anyone to decide if they prefer a full content view or not :)
Though this issue you're raising is discussed in another issue https://github.com/nextcloud/server/issues/16934
