### ISSUE TITLE
Some fields are covered by other fields

### ISSUE THREAD

**Issue by pawlosck** [nextcloud/contacts#1817]
Add a lot of fields. Number of fields must be bigger than free space on the page.
Fields on botton contact page are on top of fields which are one level higher.

Firefox 81 Ubuntu x64
Contacts app: 3.4.0
Nextcloud: 19.03

**Comment by skjnldsv** [comment]
Hey!
Could you add a screenshot please?

**Comment by pawlosck** [comment]
![Screenshot_20201001_104416](https://user-images.githubusercontent.com/3769853/94788231-95bb6080-03d3-11eb-8835-2467edd6e784.png)

**Comment by pawlosck** [comment]
![Screenshot_20201001_105533](https://user-images.githubusercontent.com/3769853/94789126-cea80500-03d4-11eb-9a7d-a9732449ab54.png)
Beside, is it correct position of this button (three lines)?

**Comment by skjnldsv** [comment]
I cannot reproduce your issue.
Can you share the contact here and tell me your screen resolution please? :)



> ![Screenshot_20201001_105533](https://user-images.githubusercontent.com/3769853/94789126-cea80500-03d4-11eb-9a7d-a9732449ab54.png)
> Beside, is it correct position of this button (three lines)?

Thi sis another issue, let's not mix tickets. See #1816

**Comment by pawlosck** [comment]
A lot of my contacts looks like on screenshot, so strange, that you can't reproduce it.
I can't share contact (personal data :) ).  I will try to prepare contact with fake data and I will send you. 
Resolution: 1920x1080 / Screen: 15,4"
Bug probably is connected with field "Note". I checked some contacts and it looks like only field Note is covered by other field. Try to add very long description (about 20-30 lines should be enought) into field Note and add other field to be below field Note.

PS. About hamburger menu. I thought it's connected problem.

**Comment by skjnldsv** [comment]
> Bug probably is connected with field "Note". I checked some contacts and it looks like only field Note is covered by other field. Try to add very long description (about 20-30 lines should be enought) into field Note and add other field to be below field Note.

I tried as well with the Note, but the Note field always stretches with the content, so it doesn't cause an issue on my pc.
You can send the contact on john@nextcloud.com if you wanna be safe :)
____
Can you make sure to clear your cache as well?
1. [clear your browser's cache](https://www.refreshyourcache.com/)
2. [run](https://docs.nextcloud.com/server/stable/admin_manual/configuration_server/occ_command.html#run-occ-as-your-http-user) an [`occ maintenance:repair`](https://docs.nextcloud.com/server/stable/admin_manual/configuration_server/occ_command.html#maintenance-commands-label) on your server

Thanks :wink:

**Comment by pawlosck** [comment]
I sent contact via e-mail.
I checked in Chromium and the same problem. Cache cleared.
During modification, contact looks well. You have to create contact, go to other contact and next open again broken contact and then you should see this bug. When you trying to modify Note field, then field below Note field is moved to other place, but after reopen the same contact, bug still exists.

**Comment by skjnldsv** [comment]
> During modification, contact looks well. You have to create contact, go to other contact and next open again broken contact and then you should see this bug. When you trying to modify Note field, then field below Note field is moved to other place, but after reopen the same contact, bug still exists.

Nice! That was it!
Thanks for narrowing this down! :)
