### ISSUE TITLE
Contact Title (Name, Company, Position) not colored anymore

### ISSUE THREAD

**Issue by tdoerschel** [nextcloud/contacts#1818]
Hi,
with the latest update, the header of contacts details view (on top, where it writes the name in big bold letters, and company+position) is not colored anymore.
See screenshot attached.

If this is intended, I suggest another form of visual separation. Maybe a horizontal line, or light gray background?
![contacts-color](https://user-images.githubusercontent.com/46196223/94775560-59cad000-03c0-11eb-9965-5f04f50ef2ea.jpg)

Firefox 81.0 and Chrome 85.0 on Windows 10
contacts 3.4.0
nextcloud 19.0.3
PHP 7.4.10 and 7.3.22

P.S. Thanks a lot for fixing #522 ! *thumbs-up*

**Comment by skjnldsv** [comment]
Not a bug :)
see https://github.com/nextcloud/contacts/pull/1447
