### ISSUE TITLE
Contacts app is not loading

### ISSUE THREAD

**Issue by alsvartr** [nextcloud/contacts#1844]
When trying to access `/apps/contacts/` there is only "Loading" text and page is never loaded.

Nothing usefull in log files, but browser web console shows errors:
```
Uncaught (in promise) TypeError: t.shares is undefined
    Xe addressbooks.js:65
    t addressbooks.js:255
    t addressbooks.js:253
    promise callback*t/< addressbooks.js:252
    u runtime.js:45
    _invoke runtime.js:271
    e runtime.js:97
    We contacts.js:1096
    a contacts.js:1096
    qe contacts.js:1096
    qe contacts.js:1096
    getAddressbooks addressbooks.js:241
    v vuex.esm.js:747
    dispatch vuex.esm.js:438
    dispatch vuex.esm.js:332
    beforeMount Contacts.vue:320
    promise callback*beforeMount Contacts.vue:318
    VueJS 27
    <anonymous> main.js:82
    Webpack 3
addressbooks.js:65:2
```

### Steps to reproduce
1. Go to contacts app page

### Expected behaviour
Contacts app loaded successfully

### Server configuration

**Nextcloud version:** 19

**Contacts version:** 3.1.8

**Updated from an older Nextcloud/ownCloud or fresh install:** updated from 18

**Comment by skjnldsv** [comment]
Contacts version?

**Comment by Kourai** [comment]
Different error, but same result...
Contact is stuck on "Loading Contact" after updating from Nextcloud 19 to 20

```
Uncaught (in promise) Error: 
    S dist.js:1
    r dist.js:1
    r dist.js:1
    o dist.js:1
    t dist.js:1
    n dist.js:1
    t dist.js:1
    n dist.js:1
    onreadystatechange dist.js:1
    e dist.js:1
    e dist.js:1
    l dist.js:1
    _invoke dist.js:1
    v dist.js:1
    Ae dist.js:1
    i dist.js:1
    de dist.js:1
    de dist.js:1
    value dist.js:1
    e dist.js:1
    l dist.js:1
    _invoke dist.js:1
    v dist.js:1
    Ae dist.js:1
    i dist.js:1
    de dist.js:1
    de dist.js:1
    value dist.js:1
    e dist.js:1
    l dist.js:1
    _invoke dist.js:1
    v dist.js:1
    ze dist.js:1
    i dist.js:1
    Fe dist.js:1
    Fe dist.js:1
    value dist.js:1
    e dist.js:1
    l dist.js:1
    _invoke dist.js:1
    v dist.js:1
    ze dist.js:1
    i dist.js:1
    Fe dist.js:1
    Fe dist.js:1
    value dist.js:1
    e dist.js:1
    l dist.js:1
    _invoke dist.js:1
    v dist.js:1
    lr dist.js:1
    i dist.js:1
    ur dist.js:1
    ur dist.js:1
    value dist.js:1
    t addressbooks.js:253
    l dist.js:1
    _invoke dist.js:1
    v dist.js:1
    jn contacts-main.js:1392
    i contacts-main.js:1392
    _n contacts-main.js:1392
    _n contacts-main.js:1392
    getAddressbooks addressbooks.js:251
    g vuex.esm.js:847
    dispatch vuex.esm.js:512
    dispatch vuex.esm.js:402
    beforeMount Contacts.vue:473
    promise callback*beforeMount Contacts.vue:471
    VueJS 27
    <anonymous> main.js:75
    Webpack 3
dist.js:1:92232
```

**Comment by skjnldsv** [comment]
I will need a screenshot of your network requests.
Before you do anything, still on the development tools, there is a tab called `network`. Click on it and then the xhr filter. Do your action and screenshot the network log like this:
![capture d ecran_2018-09-27_21-49-46](https://user-images.githubusercontent.com/14975046/46170857-43548000-c29f-11e8-9403-db72713dd9c1.png)

**Comment by alsvartr** [comment]
@skjnldsv 
![Screenshot from 2020-10-12 11-18-31](https://user-images.githubusercontent.com/205880/95722626-d8efbc00-0c7c-11eb-8c0e-74ac1005fa2e.png)

**Comment by skjnldsv** [comment]
> Contacts version 3.1.8

Please update to 3.4.0 :)
If this is still happening after that, free to reopen.

**Comment by skjnldsv** [comment]
> Different error, but same result...
> Contact is stuck on "Loading Contact" after updating from Nextcloud 19 to 20


Please open your own issue :)

**Comment by alsvartr** [comment]
> > Contacts version 3.1.8
> 
> Please update to 3.4.0 :)
> If this is still happening after that, free to reopen.

Now it gives me this error in console:
`Uncaught SyntaxError: expected expression, got '<'`

**Comment by skjnldsv** [comment]
Could you post the entire error please? :)

**Comment by alsvartr** [comment]
> Could you post the entire error please? :)

![Uploading Screenshot from 2020-10-12 19-57-48.png…]()

**Comment by alsvartr** [comment]
![Screenshot from 2020-10-12 19-57-48](https://user-images.githubusercontent.com/205880/95772436-66ef9500-0cc5-11eb-82c4-a5620abd3f0c.png)

**Comment by skjnldsv** [comment]
Can you open the contacts-main.js file and check the content?
Any error in your nextcloud log?

**Comment by Quix0r** [comment]
Sorry, but an other JS error prevents the app from loading.

**Comment by Quix0r** [comment]
`SyntaxError: missing ( before catch` - contacts-main.js is compressed.

**Comment by skjnldsv** [comment]
What browser?

> contacts-main.js is compressed

It is but we serve map files too. If you haven't setup your webserver properly, please do so.
And then give me the source file line location of the error.

**Comment by skjnldsv** [comment]
Also please provide full logs, we can't help you otherwise
