### ISSUE TITLE
Some phone numbers are not shown

### ISSUE THREAD

**Issue by h-h-** [nextcloud/contacts#1847]
### Describe the bug
Phone numbers with missing type are not shown.
Phone numbers with TYPE=PREF are not shown.

**To Reproduce**
Create a contact on the phone, sync to NC and view it in the contacts app. My exported test contact look like this:

BEGIN:VCARD
VERSION:3.0
PRODID:-//Sabre//Sabre VObject 4.3.0//EN
UID:c8d32f14-adf9-411d-b6a1-5cdb0e0acefe
FN:MaxPrefix Maxvorname Maxmiddlename Maxsurname\, Maxsuffix
N:Maxsurname;Maxvorname;Maxmiddlename;MaxPrefix;Maxsuffix
NICKNAME:MaxiSpitz
X-PHONETIC-FIRST-NAME:MaxiPhonetisch
X-PHONETIC-MIDDLE-NAME:MaxiiiPhonetisch
X-PHONETIC-LAST-NAME:MustermannPhonetisch
ORG:MaxiFirma
TITLE:MaxiTitelInDaFirma
TEL;TYPE=cell:9876
TEL;TYPE=home:8765
TEL;TYPE=work:765
TEL:6540
TEL;TYPE=car:543
TEL;TYPE=x-company_main:321
TEL;TYPE=isdn:210
TEL;TYPE=voice:109
EMAIL;TYPE=home:maxi.mus@a.bcd
EMAIL;TYPE=work:maxi@bcd.efg
EMAIL:max@mex.jio
IMPP;TYPE=home:aim:mxichat
IMPP;TYPE=home:msnim:mxc2
IMPP;TYPE=home:ymsgr:mxc3
IMPP;TYPE=home:skype:mxc4
ADR;TYPE=home;LABEL=Maxlstreet 1:;;Maxlstreet 1;;;;
ADR;TYPE=work;LABEL=Maxlwork 33:;;Maxlwork 33;;;;
NOTE:So a maxl 4
URL;TYPE=x-homepage;VALUE=URI:mx.dfr.chj
URL;TYPE=x-homepage;VALUE=URI:myxi.hhh
ITEM1.X-ABDATE;VALUE=DATE-AND-OR-TIME:20191017
ITEM1.X-ABLABEL:_$!<Anniversary>!$_
X-ANNIVERSARY;VALUE=DATE-AND-OR-TIME:20191017
BDAY:20191219
REV:20201012T200647Z
END:VCARD

The entry TEL:6540 is not shown.
This also happens with entries like

TEL;TYPE=PREF:+45678901234

**Expected behavior**
I expect to see all phone numbers

**Actual behavior**
The described numbers are not shown

### Server configuration

**Operating system**: Ubuntu 20.04.1 LTS

**Web server:** Apache

**Database:** MariaDB, MySQL, PostgreSQL... 

**PHP version:** 7.0, 7.1, 7.2...

**Nextcloud version:** 19.0.3

**Contacts version:** 3.4.0

### Server configuration detail

Operating system: Linux 5.4.0-48-generic #52-Ubuntu SMP Thu Sep 10 10:58:49 UTC 2020 x86_64

Webserver: Apache (fpm-fcgi)

Database: mysql 5.7.31

PHP version: 7.3.23

Modules loaded: Core, date, libxml, openssl, pcre, sqlite3, zlib, bcmath, bz2, ctype, curl, dom, hash, fileinfo, filter, ftp, gd, gmp, SPL, iconv, intl, json, ldap, mbstring, pcntl, PDO, session, pdo_sqlite, posix, Reflection, standard, SimpleXML, mysqlnd, exif, tokenizer, xml, xmlreader, xmlwriter, zip, pdo_mysql, cgi-fcgi, redis, Zend OPcache

Nextcloud version: 19.0.3 - 19.0.3.1

Updated from an older Nextcloud/ownCloud or fresh install:

Where did you install Nextcloud from: unknown

<details><summary>Signing status</summary>

Array ( )

</details>

<details><summary>List of activated apps</summary>

Enabled:
 - accessibility: 1.5.0
 - activity: 2.12.0
 - bruteforcesettings: 2.0.1
 - calendar: 2.0.4
 - cloud_federation_api: 1.2.0
 - comments: 1.9.0
 - contacts: 3.4.0
 - contactsinteraction: 1.0.0
 - dav: 1.15.0
 - federatedfilesharing: 1.9.0
 - federation: 1.9.0
 - files: 1.14.0
 - files_pdfviewer: 1.8.0
 - files_rightclick: 0.16.0
 - files_sharing: 1.11.0
 - files_trashbin: 1.9.0
 - files_versions: 1.12.0
 - files_videoplayer: 1.8.0
 - firstrunwizard: 2.8.0
 - logreader: 2.4.0
 - lookup_server_connector: 1.7.0
 - mail: 1.4.1
 - nextcloud_announcements: 1.8.0
 - notifications: 2.7.0
 - oauth2: 1.7.0
 - password_policy: 1.9.1
 - photos: 1.1.0
 - privacy: 1.3.0
 - provisioning_api: 1.9.0
 - recommendations: 0.7.0
 - richdocuments: 3.7.4
 - serverinfo: 1.9.0
 - settings: 1.1.0
 - sharebymail: 1.9.0
 - spreed: 9.0.4
 - support: 1.2.1
 - survey_client: 1.7.0
 - systemtags: 1.9.0
 - text: 3.0.1
 - twofactor_backupcodes: 1.8.0
 - viewer: 1.3.0
 - workflowengine: 2.1.0
Disabled:
 - admin_audit
 - encryption
 - files_external
 - theming
 - user_ldap

</details>

**Comment by h-h-** [comment]
Also the email without type is not shown:
EMAIL:max@mex.jio

**Comment by skjnldsv** [comment]
Hello!
I will need your browser console log to investigate this issue.
Open your console, reload your page and/or do the action leading to this issue and copy/paste the log in this thread.

<details>
<summary>How to access your browser console (Click to expand)</summary>

# Chrome
- Press either CTRL + SHIFT + J to open the “console” tab of the Developer Tools.
- Alternative method:
    1. Press either CTRL + SHIFT + I or F12 to open the Developer Tools.
    2. Click the “console” tab.

# Safari
- Press CMD + ALT + I to open the Web Inspector.
- See Chrome’s step 2. (Chrome and Safari have pretty much identical dev tools.)

# IE9
1. Press F12 to open the developer tools.
2. Click the “console” tab.

# Firefox
- Press CTRL + SHIFT + K to open the Web console (COMMAND + SHIFT + K on Macs).
- or, if Firebug is installed (recommended):
    1. Press F12 to open Firebug.
    2. Click on the “console” tab.

# Opera
1. Press CTRL + SHIFT + I to open Dragonfly.
2. Click on the “console” tab.
</details>

**Comment by h-h-** [comment]
### Here is the browser console log
Created by first showing the contact, then deleting the console log and refreshing with ctrl -F5
P.S.: When setting the browser language from german to english (United States) the number is still not shown.

GEThttps://ubus.ubp5afyxpvwkn3pb.myfritz.net/index.php/apps/contacts/All%20contacts/c8d32f14-adf9-411d-b6a1-5cdb0e0acefe~adressbuch1
[HTTP/1.1 200 OK 1469ms]

Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf inline blockiert ("script-src"). utils.js:35:9
Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf data: blockiert ("media-src").
GEThttps://ubus.ubp5afyxpvwkn3pb.myfritz.net/index.php/css/core/68c8-512b-server.css?v=d41d8cd98f00b204e9800998ecf8427e-9f225586
[HTTP/1.1 200 OK 694ms]

GEThttps://ubus.ubp5afyxpvwkn3pb.myfritz.net/index.php/css/core/68c8-512b-css-variables.css?v=d41d8cd98f00b204e9800998ecf8427e-9f225586
[HTTP/1.1 200 OK 1149ms]

GEThttps://ubus.ubp5afyxpvwkn3pb.myfritz.net/apps/files_pdfviewer/css/style.css?v=4fda350b
[HTTP/1.1 200 OK 524ms]

GEThttps://ubus.ubp5afyxpvwkn3pb.myfritz.net/index.php/css/notifications/b1d7-512b-styles.css?v=d41d8cd98f00b204e9800998ecf8427e-9f225586
[HTTP/1.1 200 OK 2812ms]

GEThttps://ubus.ubp5afyxpvwkn3pb.myfritz.net/index.php/css/contacts/1321-512b-contacts.css?v=d41d8cd98f00b204e9800998ecf8427e-9f225586
[HTTP/1.1 200 OK 1664ms]

GEThttps://ubus.ubp5afyxpvwkn3pb.myfritz.net/index.php/css/core/68c8-512b-results.css?v=d41d8cd98f00b204e9800998ecf8427e-9f225586
[HTTP/1.1 200 OK 2198ms]

GEThttps://ubus.ubp5afyxpvwkn3pb.myfritz.net/core/js/dist/main.js?v=9f225586
[HTTP/1.1 200 OK 4283ms]

GEThttps://ubus.ubp5afyxpvwkn3pb.myfritz.net/index.php/js/core/merged-template-prepend.js?v=9f225586
[HTTP/1.1 200 OK 3392ms]

GEThttps://ubus.ubp5afyxpvwkn3pb.myfritz.net/core/search/js/search.js?v=9f225586
[HTTP/1.1 200 OK 1221ms]

GEThttps://ubus.ubp5afyxpvwkn3pb.myfritz.net/apps/files_pdfviewer/js/previewplugin.js?v=9f225586
[HTTP/1.1 200 OK 1310ms]

GEThttps://ubus.ubp5afyxpvwkn3pb.myfritz.net/apps/files_sharing/js/dist/main.js?v=9f225586
[HTTP/1.1 200 OK 1393ms]

GEThttps://ubus.ubp5afyxpvwkn3pb.myfritz.net/apps/files_videoplayer/js/main.js?v=9f225586
[HTTP/1.1 200 OK 1491ms]

GEThttps://ubus.ubp5afyxpvwkn3pb.myfritz.net/apps/notifications/js/notifications.js?v=9f225586
[HTTP/1.1 200 OK 3776ms]

GEThttps://ubus.ubp5afyxpvwkn3pb.myfritz.net/extra-apps/contacts/js/contacts-main.js?v=9f225586
[HTTP/1.1 200 OK 7529ms]

GEThttps://ubus.ubp5afyxpvwkn3pb.myfritz.net/apps/files_rightclick/js/script.js?v=9f225586
[HTTP/1.1 200 OK 2361ms]

GEThttps://ubus.ubp5afyxpvwkn3pb.myfritz.net/apps/firstrunwizard/js/about.js?v=9f225586
[HTTP/1.1 200 OK 2492ms]

GEThttps://ubus.ubp5afyxpvwkn3pb.myfritz.net/core/search/js/searchprovider.js?v=9f225586
[HTTP/1.1 200 OK 2629ms]

GEThttps://ubus.ubp5afyxpvwkn3pb.myfritz.net/core/js/files/fileinfo.js?v=9f225586
[HTTP/1.1 200 OK 2710ms]

GEThttps://ubus.ubp5afyxpvwkn3pb.myfritz.net/core/js/files/client.js?v=9f225586
[HTTP/1.1 200 OK 2836ms]

GEThttps://ubus.ubp5afyxpvwkn3pb.myfritz.net/index.php/css/icons/icons-vars.css?v=1602535590
[HTTP/1.1 200 OK 4516ms]

Unerkannte at-Regel oder Fehler beim Verarbeiten der at-Regel '@-ms-viewport'. 68c8-512b-server.css:1:23177
Unbekannte Pseudoklasse oder Pseudoelement '-ms-input-placeholder'.  Regelsatz wegen ungültigem Selektor ignoriert. 68c8-512b-server.css:1:54180
GEThttps://ubus.ubp5afyxpvwkn3pb.myfritz.net/index.php/apps/accessibility/js/accessibility?v=0
[HTTP/1.1 200 OK 1566ms]

GEThttps://ubus.ubp5afyxpvwkn3pb.myfritz.net/apps/files/img/app.svg?v=9f225586
[HTTP/1.1 200 OK 1709ms]

GEThttps://ubus.ubp5afyxpvwkn3pb.myfritz.net/apps/photos/img/app.svg?v=9f225586
[HTTP/1.1 200 OK 1693ms]

GEThttps://ubus.ubp5afyxpvwkn3pb.myfritz.net/apps/activity/img/activity.svg?v=9f225586
[HTTP/1.1 200 OK 1695ms]

GEThttps://ubus.ubp5afyxpvwkn3pb.myfritz.net/extra-apps/spreed/img/app.svg?v=9f225586
[HTTP/1.1 200 OK 1685ms]

GEThttps://ubus.ubp5afyxpvwkn3pb.myfritz.net/extra-apps/mail/img/mail.svg?v=9f225586
[HTTP/1.1 200 OK 1680ms]

GEThttps://ubus.ubp5afyxpvwkn3pb.myfritz.net/extra-apps/contacts/img/app.svg?v=9f225586
[HTTP/1.1 200 OK 1696ms]

GEThttps://ubus.ubp5afyxpvwkn3pb.myfritz.net/extra-apps/calendar/img/calendar.svg?v=9f225586
[HTTP/1.1 200 OK 1680ms]

GEThttps://ubus.ubp5afyxpvwkn3pb.myfritz.net/apps/settings/img/admin.svg?v=9f225586
[HTTP/1.1 200 OK 1685ms]

GEThttps://ubus.ubp5afyxpvwkn3pb.myfritz.net/apps/firstrunwizard/img/info.svg?v=9f225586
[HTTP/1.1 200 OK 1746ms]

GEThttps://ubus.ubp5afyxpvwkn3pb.myfritz.net/apps/settings/img/help.svg?v=9f225586
[HTTP/1.1 200 OK 1731ms]

GEThttps://ubus.ubp5afyxpvwkn3pb.myfritz.net/core/img/actions/logout.svg?v=9f225586
[HTTP/1.1 200 OK 1736ms]

GEThttps://ubus.ubp5afyxpvwkn3pb.myfritz.net/index.php/avatar/harald/32?v=1
[HTTP/1.1 200 OK 2267ms]

GEThttps://ubus.ubp5afyxpvwkn3pb.myfritz.net/core/img/logo/logo.svg?v=1
[HTTP/1.1 200 OK 111ms]

JQMIGRATE: Migrate is installed, version 1.4.1 jquery-migrate.min.js:2:551
'none', URL oder Filterfunktion erwartet, aber 'Alpha(' gefunden.  Fehler beim Verarbeiten des Wertes für 'filter'.  Deklaration ignoriert. c8d32f14-adf9-411d-b6a1-5cdb0e0acefe~adressbuch1:48:9
'none', URL oder Filterfunktion erwartet, aber 'alpha(' gefunden.  Fehler beim Verarbeiten des Wertes für 'filter'.  Deklaration ignoriert. c8d32f14-adf9-411d-b6a1-5cdb0e0acefe~adressbuch1:667:10
'none', URL oder Filterfunktion erwartet, aber 'Alpha(' gefunden.  Fehler beim Verarbeiten des Wertes für 'filter'.  Deklaration ignoriert. c8d32f14-adf9-411d-b6a1-5cdb0e0acefe~adressbuch1:1044:9
'none', URL oder Filterfunktion erwartet, aber 'Alpha(' gefunden.  Fehler beim Verarbeiten des Wertes für 'filter'.  Deklaration ignoriert. c8d32f14-adf9-411d-b6a1-5cdb0e0acefe~adressbuch1:1051:9
'none', URL oder Filterfunktion erwartet, aber 'Alpha(' gefunden.  Fehler beim Verarbeiten des Wertes für 'filter'.  Deklaration ignoriert. c8d32f14-adf9-411d-b6a1-5cdb0e0acefe~adressbuch1:1055:9
'none', URL oder Filterfunktion erwartet, aber 'Alpha(' gefunden.  Fehler beim Verarbeiten des Wertes für 'filter'.  Deklaration ignoriert. c8d32f14-adf9-411d-b6a1-5cdb0e0acefe~adressbuch1:1307:10
'none', URL oder Filterfunktion erwartet, aber 'Alpha(' gefunden.  Fehler beim Verarbeiten des Wertes für 'filter'.  Deklaration ignoriert. c8d32f14-adf9-411d-b6a1-5cdb0e0acefe~adressbuch1:175:9
'none', URL oder Filterfunktion erwartet, aber 'Alpha(' gefunden.  Fehler beim Verarbeiten des Wertes für 'filter'.  Deklaration ignoriert. c8d32f14-adf9-411d-b6a1-5cdb0e0acefe~adressbuch1:182:9
'none', URL oder Filterfunktion erwartet, aber 'Alpha(' gefunden.  Fehler beim Verarbeiten des Wertes für 'filter'.  Deklaration ignoriert. c8d32f14-adf9-411d-b6a1-5cdb0e0acefe~adressbuch1:186:9
'none', URL oder Filterfunktion erwartet, aber 'Alpha(' gefunden.  Fehler beim Verarbeiten des Wertes für 'filter'.  Deklaration ignoriert. c8d32f14-adf9-411d-b6a1-5cdb0e0acefe~adressbuch1:438:10
'none', URL oder Filterfunktion erwartet, aber 'alpha(' gefunden.  Fehler beim Verarbeiten des Wertes für 'filter'.  Deklaration ignoriert. c8d32f14-adf9-411d-b6a1-5cdb0e0acefe~adressbuch1:132:11
Unbekannte Eigenschaft '-moz-border-radius'.  Deklaration ignoriert. c8d32f14-adf9-411d-b6a1-5cdb0e0acefe~adressbuch1:136:22
'none', URL oder Filterfunktion erwartet, aber 'alpha(' gefunden.  Fehler beim Verarbeiten des Wertes für 'filter'.  Deklaration ignoriert. c8d32f14-adf9-411d-b6a1-5cdb0e0acefe~adressbuch1:146:11
Unbekannte Eigenschaft '-moz-border-radius'.  Deklaration ignoriert. c8d32f14-adf9-411d-b6a1-5cdb0e0acefe~adressbuch1:150:22
Unbekannte Eigenschaft 'zoom'.  Deklaration ignoriert. c8d32f14-adf9-411d-b6a1-5cdb0e0acefe~adressbuch1:9:10
Deklaration erwartet, aber '*' gefunden.  Übersprungen bis zur nächsten Deklaration c8d32f14-adf9-411d-b6a1-5cdb0e0acefe~adressbuch1:10:5
'none', URL oder Filterfunktion erwartet, aber 'progid' gefunden.  Fehler beim Verarbeiten des Wertes für 'filter'.  Deklaration ignoriert. c8d32f14-adf9-411d-b6a1-5cdb0e0acefe~adressbuch1:55:13
'none', URL oder Filterfunktion erwartet, aber 'progid' gefunden.  Fehler beim Verarbeiten des Wertes für 'filter'.  Deklaration ignoriert. c8d32f14-adf9-411d-b6a1-5cdb0e0acefe~adressbuch1:71:13
'none', URL oder Filterfunktion erwartet, aber 'alpha(' gefunden.  Fehler beim Verarbeiten des Wertes für 'filter'.  Deklaration ignoriert. c8d32f14-adf9-411d-b6a1-5cdb0e0acefe~adressbuch1:137:13
'none', URL oder Filterfunktion erwartet, aber 'progid' gefunden.  Fehler beim Verarbeiten des Wertes für 'filter'.  Deklaration ignoriert. c8d32f14-adf9-411d-b6a1-5cdb0e0acefe~adressbuch1:204:13
'none', URL oder Filterfunktion erwartet, aber 'progid' gefunden.  Fehler beim Verarbeiten des Wertes für 'filter'.  Deklaration ignoriert. c8d32f14-adf9-411d-b6a1-5cdb0e0acefe~adressbuch1:309:13
'none', URL oder Filterfunktion erwartet, aber 'progid' gefunden.  Fehler beim Verarbeiten des Wertes für 'filter'.  Deklaration ignoriert. c8d32f14-adf9-411d-b6a1-5cdb0e0acefe~adressbuch1:321:13
'none', URL oder Filterfunktion erwartet, aber 'progid' gefunden.  Fehler beim Verarbeiten des Wertes für 'filter'.  Deklaration ignoriert. c8d32f14-adf9-411d-b6a1-5cdb0e0acefe~adressbuch1:585:13
'none', URL oder Filterfunktion erwartet, aber 'alpha(' gefunden.  Fehler beim Verarbeiten des Wertes für 'filter'.  Deklaration ignoriert. c8d32f14-adf9-411d-b6a1-5cdb0e0acefe~adressbuch1:15:10
$ is deprecated: The global jQuery is deprecated. It will be updated to v2.4 in Nextcloud 20 and v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. globals.js:61:15
Handlebars is deprecated: please ship your own, this will be removed in Nextcloud 20 globals.js:61:15
$ is deprecated: The global jQuery is deprecated. It will be updated to v2.4 in Nextcloud 20 and v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 3 globals.js:61:15
Notifications permissions denied App.vue:296
GEThttps://ubus.ubp5afyxpvwkn3pb.myfritz.net/apps/notifications/img/notifications-new.svg
GEThttps://ubus.ubp5afyxpvwkn3pb.myfritz.net/apps/notifications/img/notifications.svg

GEThttps://ubus.ubp5afyxpvwkn3pb.myfritz.net/apps/notifications/img/notifications.svg
[HTTP/1.1 200 OK 73ms]

XHRGEThttps://ubus.ubp5afyxpvwkn3pb.myfritz.net/ocs/v2.php/apps/notifications/api/v2/notifications
[HTTP/1.1 200 OK 821ms]

GEThttps://ubus.ubp5afyxpvwkn3pb.myfritz.net/core/img/favicon-touch.png
[HTTP/1.1 200 OK 71ms]

GEThttps://ubus.ubp5afyxpvwkn3pb.myfritz.net/core/img/favicon.ico
[HTTP/1.1 200 OK 74ms]

Unbekannte Pseudoklasse oder Pseudoelement '-ms-clear'.  Regelsatz wegen ungültigem Selektor ignoriert. c8d32f14-adf9-411d-b6a1-5cdb0e0acefe~adressbuch1:1:34858
Fehler beim Verarbeiten des Wertes für 'left'.  Deklaration ignoriert. c8d32f14-adf9-411d-b6a1-5cdb0e0acefe~adressbuch1:1:490
Fehler beim Verarbeiten des Wertes für 'left'.  Deklaration ignoriert. c8d32f14-adf9-411d-b6a1-5cdb0e0acefe~adressbuch1:1:811
Fehler beim Verarbeiten des Wertes für 'top'.  Deklaration ignoriert. c8d32f14-adf9-411d-b6a1-5cdb0e0acefe~adressbuch1:1:1117
Fehler beim Verarbeiten des Wertes für 'top'.  Deklaration ignoriert. c8d32f14-adf9-411d-b6a1-5cdb0e0acefe~adressbuch1:1:1434
Fehler beim Verarbeiten des Wertes für 'left'.  Deklaration ignoriert. c8d32f14-adf9-411d-b6a1-5cdb0e0acefe~adressbuch1:1:490
Fehler beim Verarbeiten des Wertes für 'left'.  Deklaration ignoriert. c8d32f14-adf9-411d-b6a1-5cdb0e0acefe~adressbuch1:1:811
Fehler beim Verarbeiten des Wertes für 'top'.  Deklaration ignoriert. c8d32f14-adf9-411d-b6a1-5cdb0e0acefe~adressbuch1:1:1117
Fehler beim Verarbeiten des Wertes für 'top'.  Deklaration ignoriert. c8d32f14-adf9-411d-b6a1-5cdb0e0acefe~adressbuch1:1:1434
jQuery is deprecated: The global jQuery is deprecated. It will be updated to v2.4 in Nextcloud 20 and v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 3 globals.js:61:15
Fehler beim Verarbeiten des Wertes für 'left'.  Deklaration ignoriert. c8d32f14-adf9-411d-b6a1-5cdb0e0acefe~adressbuch1:1:490
Fehler beim Verarbeiten des Wertes für 'left'.  Deklaration ignoriert. c8d32f14-adf9-411d-b6a1-5cdb0e0acefe~adressbuch1:1:811
Fehler beim Verarbeiten des Wertes für 'top'.  Deklaration ignoriert. c8d32f14-adf9-411d-b6a1-5cdb0e0acefe~adressbuch1:1:1117
Fehler beim Verarbeiten des Wertes für 'top'.  Deklaration ignoriert. c8d32f14-adf9-411d-b6a1-5cdb0e0acefe~adressbuch1:1:1434
Initial state loaded defaultProfileState HOME rfcProps.js:39:8
Initial state loaded localesState 
Array(750) [ {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, … ]
rfcProps.js:40:8
Unbekannte Pseudoklasse oder Pseudoelement '-ms-clear'.  Regelsatz wegen ungültigem Selektor ignoriert. c8d32f14-adf9-411d-b6a1-5cdb0e0acefe~adressbuch1:1:34858
Fehler beim Verarbeiten des Wertes für 'left'.  Deklaration ignoriert. c8d32f14-adf9-411d-b6a1-5cdb0e0acefe~adressbuch1:1:490
Fehler beim Verarbeiten des Wertes für 'left'.  Deklaration ignoriert. c8d32f14-adf9-411d-b6a1-5cdb0e0acefe~adressbuch1:1:811
Fehler beim Verarbeiten des Wertes für 'top'.  Deklaration ignoriert. c8d32f14-adf9-411d-b6a1-5cdb0e0acefe~adressbuch1:1:1117
Fehler beim Verarbeiten des Wertes für 'top'.  Deklaration ignoriert. c8d32f14-adf9-411d-b6a1-5cdb0e0acefe~adressbuch1:1:1434
XHRPROPFINDhttps://ubus.ubp5afyxpvwkn3pb.myfritz.net/remote.php/dav/
[HTTP/1.1 207 Multi-Status 604ms]

New search handler registered search.js:67:12
jQuery is deprecated: The global jQuery is deprecated. It will be updated to v2.4 in Nextcloud 20 and v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. globals.js:61:15
$ is deprecated: The global jQuery is deprecated. It will be updated to v2.4 in Nextcloud 20 and v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. globals.js:61:15
session heartbeat polling started session-heartbeat.js:97:9
$ is deprecated: The global jQuery is deprecated. It will be updated to v2.4 in Nextcloud 20 and v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 3 globals.js:61:15
jQuery is deprecated: The global jQuery is deprecated. It will be updated to v2.4 in Nextcloud 20 and v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. globals.js:61:15
XHRPROPFINDhttps://ubus.ubp5afyxpvwkn3pb.myfritz.net/remote.php/dav/principals/users/harald/
[HTTP/1.1 207 Multi-Status 618ms]

Connected to dav! 
Object { rootUrl: "https://ubus.ubp5afyxpvwkn3pb.myfritz.net/remote.php/dav/", advertisedFeatures: (17) […], currentUserPrincipal: {…}, principalCollections: (4) […], calendarHomes: [], publicCalendarHome: {…}, addressBookHomes: (1) […], parser: {…}, _isConnected: true, _request: {…} }
Contacts.vue:472
XHRPROPFINDhttps://ubus.ubp5afyxpvwkn3pb.myfritz.net/remote.php/dav/addressbooks/users/harald/
[HTTP/1.1 207 Multi-Status 655ms]

XHRREPORThttps://ubus.ubp5afyxpvwkn3pb.myfritz.net/remote.php/dav/addressbooks/users/harald/adressbuch1/
[HTTP/1.1 207 Multi-Status 1890ms]

XHRREPORThttps://ubus.ubp5afyxpvwkn3pb.myfritz.net/remote.php/dav/addressbooks/users/harald/z-app-generated--contactsinteraction--recent/
[HTTP/1.1 207 Multi-Status 1101ms]

XHRPROPFINDhttps://ubus.ubp5afyxpvwkn3pb.myfritz.net/remote.php/dav/addressbooks/users/harald/adressbuch1/c8d32f14-adf9-411d-b6a1-5cdb0e0acefe.vcf
[HTTP/1.1 207 Multi-Status 613ms]

Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf inline blockiert ("script-src"). inject.js:22:29
Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf inline blockiert ("script-src"). inject.js:41:35
Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf data: blockiert ("media-src").
Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf inline blockiert ("script-src"). utils.js:35:9
TypeError: e.localType is null
    lr PropertyText.vue:1
    VueJS 40
    r ContactDetails.vue:600
    l dist.js:1
    _invoke dist.js:1
    v dist.js:1
    Tr contacts-main.js:1521
    i contacts-main.js:1521
    promise callback*Tr contacts-main.js:1521
    i contacts-main.js:1521
    promise callback*Tr contacts-main.js:1521
    i contacts-main.js:1521
    wr contacts-main.js:1521
    wr contacts-main.js:1521
    selectContact ContactDetails.vue:569
    beforeMount ContactDetails.vue:491
    VueJS 23
vue.runtime.esm.js:1888:12
TypeError: e.localType is null
    lr PropertyText.vue:1
    VueJS 40
    r ContactDetails.vue:600
    l dist.js:1
    _invoke dist.js:1
    v dist.js:1
    Tr contacts-main.js:1521
    i contacts-main.js:1521
    promise callback*Tr contacts-main.js:1521
    i contacts-main.js:1521
    promise callback*Tr contacts-main.js:1521
    i contacts-main.js:1521
    wr contacts-main.js:1521
    wr contacts-main.js:1521
    selectContact ContactDetails.vue:569
    beforeMount ContactDetails.vue:491
    VueJS 23
vue.runtime.esm.js:1888:12
TypeError: e.localType is null
    lr PropertyText.vue:1
    VueJS 40
    r ContactDetails.vue:600
    l dist.js:1
    _invoke dist.js:1
    v dist.js:1
    Tr contacts-main.js:1521
    i contacts-main.js:1521
    promise callback*Tr contacts-main.js:1521
    i contacts-main.js:1521
    promise callback*Tr contacts-main.js:1521
    i contacts-main.js:1521
    wr contacts-main.js:1521
    wr contacts-main.js:1521
    selectContact ContactDetails.vue:569
    beforeMount ContactDetails.vue:491
    VueJS 23
vue.runtime.esm.js:1888:12
TypeError: e.localType is null
    lr PropertyText.vue:1
    VueJS 40
    r ContactDetails.vue:600
    l dist.js:1
    _invoke dist.js:1
    v dist.js:1
    Tr contacts-main.js:1521
    i contacts-main.js:1521
    promise callback*Tr contacts-main.js:1521
    i contacts-main.js:1521
    promise callback*Tr contacts-main.js:1521
    i contacts-main.js:1521
    wr contacts-main.js:1521
    wr contacts-main.js:1521
    selectContact ContactDetails.vue:569
    beforeMount ContactDetails.vue:491
    VueJS 23
vue.runtime.esm.js:1888:12
GEThttps://ubus.ubp5afyxpvwkn3pb.myfritz.net/extra-apps/contacts/js/contacts-moment44.js?v=1d95478b46b9baa51f23
[HTTP/1.1 200 OK 0ms]

Locale used de-at 2 PropertyDateTime.vue:176
XHRGEThttps://ubus.ubp5afyxpvwkn3pb.myfritz.net/ocs/v2.php/apps/notifications/api/v2/notifications
[HTTP/1.1 304 Not Modified 903ms]

**Comment by skjnldsv** [comment]
Fixed already, pending release :)
https://github.com/nextcloud/contacts/blob/dacd518b633e32113d7c5879cc8195d01cb8b6d3/src/components/Properties/PropertyText.vue#L168
