### ISSUE TITLE
More consistent read-only highlighting

### ISSUE THREAD

**Issue by call-me-matt** [nextcloud/contacts#1849]
**Is your feature request related to a problem? Please describe.**
I find the read-only highlighting not consequent. 

**Describe the solution you'd like**
In my opinion all entry-fields should be greyed-out, like its done for the address-book-field. Currently the headlines are highlighted. For _Name_, _Company_ and _Title_ I would leave it like it is.

![grafik](https://user-images.githubusercontent.com/34400929/95819576-9c789a80-0d26-11eb-83f7-67807deaa7d1.png)

**Comment by hamza221** [comment]
The UI has changed a lot since, I'll close it as complete. feel free to open a new issue if you find issues with new UI
