### ISSUE TITLE
l10n: Unfinished string text in Transifex

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/contacts#1851]
In Transifex there is an unfinished string text for:

1.
https://github.com/nextcloud/contacts/blob/ce8992545a4bc9b63fb10a69380b5457880002cc/src/components/Settings/SettingsImportContacts.vue#L48

The sentence ends with: `Import into the `.

2.
https://github.com/nextcloud/contacts/blob/ce8992545a4bc9b63fb10a69380b5457880002cc/src/views/Contacts.vue#L149

The sentence ends with: `You don`.

**Comment by skjnldsv** [comment]
@MorrisJobke @ChristophWurst @juliushaertl the bot doesn't like this?

**Comment by ChristophWurst** [comment]
Apparently. Change `` `You don't have any contacts yet` `` to `` 'You don\'t have any contacts yet' ``

**Comment by skjnldsv** [comment]
I don\'t wanna!

**Comment by skjnldsv** [comment]
I don\\'t wanna!

**Comment by ChristophWurst** [comment]
:eye: :lips: :eye:

**Comment by MorrisJobke** [comment]
> I don\'t wanna!

Then you need to fix `gettext` as this is what we are using: https://github.com/nextcloud/docker-ci/blob/master/translations/translationtool/src/translationtool.php#L75-L98

**Comment by Valdnet** [comment]
@skjnldsv Are you running on a fix? In Transifex, I'd like to translate it 😉.

**Comment by skjnldsv** [comment]
No, haven't done it yet,

**Comment by Valdnet** [comment]
@skjnldsv What will we do about it? I tried to convert `'` to `"` but I'm not sure if you can use `"` in vue.
Then, to use `\` in the latter case, think about it `gettext`.

Translators are waiting for a quick fix as they cannot fully translate the project 😉.

**Comment by skjnldsv** [comment]
You can use them, but it's just a matter of string parsing.
In forms we do not use quotes to mention forms names. Let's do the same here. Let's just simply remove the quotes around the name.

**Comment by Valdnet** [comment]
> Let's just simply remove the quotes around the name.

I thought so too, but I didn't know if you would agree to it 😉.

@skjnldsv Please approval PR: #1836.

**Comment by Valdnet** [comment]
@skjnldsv It still remains to be corrected:
https://github.com/nextcloud/contacts/blob/ce8992545a4bc9b63fb10a69380b5457880002cc/src/views/Contacts.vue#L149

**Comment by Valdnet** [comment]
@skjnldsv If you agree, approve PR: #1893 and close issue again 😉.
