### ISSUE TITLE
Overlapping menu icon half over icon of first contact

### ISSUE THREAD

**Issue by janvlug** [nextcloud/contacts#1862]
A menu icon is shown in an incorrect place, half through a contact icon.

**To Reproduce**
Go to the contacts app.

**Expected behavior**
No overlapping elements (icon/menu)

**Actual behavior**
Menu is half through an icon for a contact.

**Screenshots**
![image](https://user-images.githubusercontent.com/5903208/96362504-13020780-112e-11eb-9c6c-c8db200f399d.png)

### Server configuration

**Operating system**: Synology (Linux)

**PHP version:** 7.3

**Nextcloud version:** Nextcloud 19.0.4

**Contacts version:** 3.4.0

**Updated from an older Nextcloud or fresh install:** updated

### Client configuration
I see this on Firefox and Chromium on Fedora 32 Linux.

**Comment by skjnldsv** [comment]
See https://github.com/nextcloud/server/issues/16934#issuecomment-542201187 :)
