### ISSUE TITLE
Add New 'Website' Property not working

### ISSUE THREAD

**Issue by MarkPartlett** [nextcloud/contacts#1866]
**To Reproduce**
1. Go to '+ Add New Property'
2. Click on 'Choose property type'
3. Scroll down to 'Website'
4. Click on 'Website'

**Expected behavior**
Expected Website Property added to Contact

**Actual behavior**
No Website Property

### Server configuration

**Operating system**: Linux.

**Web server:** Apache.

**Database:** MariaDB.

**PHP version:** 7.4.11

**Nextcloud version:** 20.0.0

**Contacts version:** 3.4.0

**Updated from an older Nextcloud or fresh install:** Fresh install Docker

**Signing status:**
No errors have been found.

**Comment by essig** [comment]
Can confirm the issue. It's since Contacts v3.4.0. It's the same on Nextcloud 19.0.4.
Additionally, the properties 'Location' and 'Phonetic first name' cannot be added, either.

**Comment by skjnldsv** [comment]
Fixed in upcoming version, sorry, I'll release as soon as possible!

**Comment by skjnldsv** [comment]
Released! Please test 3.4.1 :)
