### ISSUE TITLE
Contacts quick search obsolete with Unified Search (NC20+)?

### ISSUE THREAD

**Issue by wiswedel** [nextcloud/contacts#1867]
With the introduction of Unified Search in Nextcloud 20, isn't the contacts quick search button in the header bar obsolete?

**Comment by skjnldsv** [comment]
cc @jancborchardt

**Comment by tdoerschel** [comment]
I don't think so.
In fact, the unified search of NC20 is a step backward in contacts app for me:
now there is no way to have a "search filter" on the contact list.

Also, unified search does not search all fields that the old search did.

The quick search does not "filter" the contacts list either, but at least it searches more fields.

Is there a way to get the "old" search back in NC20, or make unified search filter the contact list while typing?
This keeps me from rolling out NC20 right now.

**Comment by tdoerschel** [comment]
Just to give an example:
I want to search for all contacts from the same company, and have them as a filtered list,
so that I can click them on-after-another to find the right person in this company (e.g. according to notes, or position etc.)

**Comment by alexanderdd** [comment]
adding to the example above: Unified Seach shows generic contacts symbol, not the image of my contacts -- but maybe the image is exactly what I need so I can find that person from company XY?

By the way, as admin, go to users and type a name in unified search - the user list will get filtered.

@skjnldsv Is there a place to discuss the general direction where search/filtering is going in Nextcloud? This is a meta level topic.

**Comment by skjnldsv** [comment]
> @skjnldsv Is there a place to discuss the general direction where search/filtering is going in Nextcloud? This is a meta level topic.

Yes, we discussed it on some tickets on server :)
https://github.com/nextcloud/server/issues/9917


> By the way, as admin, go to users and type a name in unified search - the user list will get filtered.

Yes, we do the same in apps, and some other areas :)

**Comment by ChristophWurst** [comment]
I'm closing this question because it seems answered.

Generally please put question on the forums and leave the issue tracker for bugs and feature requests.
