### ISSUE TITLE
Download contact pictures from Xing

### ISSUE THREAD

**Issue by ntimo** [nextcloud/contacts#1868]
**Is your feature request related to a problem? Please describe.**
When setting Xing as a social media profile for contacts, the profile picture is not automatically downloaded and updated.

**Describe the solution you'd like**
Nextcloud contacts should update profile pictures using Xing.

**Comment by call-me-matt** [comment]
I would love to implement this! In order to do so, I need a "recipe" (or public API) to fetch the profile picture from there. I found those for facebook, instagram, twitter, tumblr, mastodon, and diaspora. But xing and linkedin seem to lock their network from external access.

**Comment by call-me-matt** [comment]
ah well, turns out the profile pictures are public. yay!

**Comment by call-me-matt** [comment]
@skjnldsv should Xing be part of the selection-list?
`src/models/rfcProps.js:		{ id: 'XING', name: 'Xing', placeholder: 'https://www.xing.com/profile/…' },`

**Comment by skjnldsv** [comment]
> @skjnldsv should Xing be part of the selection-list?
> `src/models/rfcProps.js:		{ id: 'XING', name: 'Xing', placeholder: 'https://www.xing.com/profile/…' },`

I guess? Hard to tell, those properties are most likely not super standard 😬

**Comment by call-me-matt** [comment]
> I guess?

I'll let you decide. Also if that's part of the above or a separate PR...

**Comment by ntimo** [comment]
Thanks for adding this so fast :)

**Comment by skjnldsv** [comment]
Yes, thanks @call-me-matt :rocket: :hugs:
