### ISSUE TITLE
Add tel: links for phone numbers

### ISSUE THREAD

**Issue by juzim** [nextcloud/contacts#187]
I regularly look up phone numbers from my computer. To place the call I have to copy&paste the number in skype/hangouts/etc (or use Join to send it to my phone in my case).

A simple link with 'href="tel:PHONENUMBER"' would suffice to be able to call numbers with any application by just clicking it but I'm not sure what would be the best place to put it. The options are:

- add a toggle to switch between editing the number and showing a clickable link (adds an extra click to many workflows)
- add a "call" button next to the trash icon
- somehow make the number in the input clickable (possible but not recommended)
- add a modifier for clicks on the number (shift+click = place call)

In my opinion, adding a "call"-button in [templates/detailItems/tel.html](https://github.com/nextcloud/contacts/blob/02ceb6732857e15c9b905a7390ee4506d29fbcd4/templates/detailItems/tel.html) should be the best solution since it wouldn't interfere with any logic and there doesn't seem to be any space restrictions/wrapping issues around the trash icon.

Since this is my first project for nextcloud, it would be great to get some input if this is possible, wanted and what might be the best approach.

**Comment by irgendwie** [comment]
I would prefer the extra call button

**Comment by skjnldsv** [comment]
@irgendwie Like we do with the website field?

Also (unrelated, but not entirely) it could be great to set the default input type to "tel" for the mobile users :)

**Comment by irgendwie** [comment]
@skjnldsv sounds good to me, I imagine something like this:

![2017-04-19-093643_399x57](https://cloud.githubusercontent.com/assets/8360698/25168407/bd052ff4-24e3-11e7-9529-a2db5a37954a.png)

I'm fine with setting the default input type to tel.
