### ISSUE TITLE
Configured contacts account in iOS not available for selection as default. All other accounts can be selected. Sync works.

### ISSUE THREAD

**Issue by CapSel** [nextcloud/contacts#1870]
### Describe the bug
After adding CardDAV account to iOS I cannot select it as default. It's not on the list. Contacts app on iOS can access contacts from nextcloud. Path 

**To Reproduce**
Follow steps listed there: https://docs.nextcloud.com/server/13.0.0/user_manual/pim/sync_ios.html

**Expected behavior**
CardDAV should be on the list for default account.

**Actual behavior**
Not on the list of accounts to select as default.

**Screenshots**
Not needed.

### Server configuration
Archlinux default installation, current, no containers (docker etc) or VMs.

**Solution that works for me**
Instead of path `example.com/remote.php/dav/principals/users/USERNAME/` enter `example.com/remote.php/carddav/principals/USERNAME/`.

**Comment by call-me-matt** [comment]
I had some issues there, too. Removing and adding it multiple times (without changing anything besides the name) solved it for me. I blamed Apple for it, but maybe worth an investigation.

**Comment by skjnldsv** [comment]
Nah, apple is a nightmare for this, this is a known iOS issue iirc.
No better solution to give you unfortunately, this ain't coming from Nextcloud :(

**Comment by CapSel** [comment]
Can't you redirect wrong path to good path? It could at least be possible to do in .htaccess.
For me removing and adding does not work, changing name does not work.

**Comment by raffisweb** [comment]
> Same issue here.
> 
> Disabling the "Contacts Interaction" app immediately solved it for me on two NC instances.

Solved it for me, too. Is there a bug reported on this?

**Comment by KarstenDE** [comment]
Is there some progress about this?
I am facing same issue and nothing helps ...

**Comment by tankerktv** [comment]
> Same issue here. Disabling the "Contacts Interaction" app immediately solved it for me on two NC instances.

What is this? Can you explain please, where this setting located?)

**Comment by tonypags** [comment]
I got stuck on this issue because **I already had the "Contacts Interaction" app disabled**. I eventually figured out that I had to enable this app while connecting my iOS to CardDav, let it sync, then disable the "Contacts Interaction" app on my NC instance. Once I saw the recent contacts group disappear from the list on my phone, I went to settings and found the option to set CardDav as default was there. 

Also something that delayed me: I was deleting and re-adding the account on my phone a bunch and that caused my user account to lock out. Once I enabled that account, and had the app enabled, I was able to log in, then disable the app to get the workaround to function. 

Hope this helps someone.

**Comment by flotpg** [comment]
Hi
I stumbled into this issue today, again.
I added the account on my new phone while contacts interaction app was already disabled.
So I enabled it on next card (current version),
Disabled the account on iOS (just make it inactive, no need to remove and re-add).
Wait a few seconds, enable the account again.
Then I was able to select the account as default account.

![Image](https://github.com/user-attachments/assets/24674b48-5d82-4d69-8dda-63d54eaa352d)

**Comment by andre1808** [comment]
@flotpg Thank god for your comment!
I was so frustrated thinking about transferring my contacts to iCloud to stop this madness..
I've found the "solution" by disabling the contacts interaction app, but I simply could not make it work.

My setup:
- work exchange account
- nextcloud contacts and calendar

So after removing the profile, adding caldav and carddav servers manually and so many other tries, I gave it one final shot using your method:
- have contacts interaction app disabled in nextcloud
- add nextcloud profile through the app
- have it sync
- enable contacts interaction app
- wait a couple seconds
- disable contacts interaction app
- disable nextcloud contacts profile
- wait a couple seconds
- enable nextcloud contacts profile
- profit

**Comment by prplecake** [comment]
iOS 26 appears to have made this problem worse. None of the workarounds work around.

**Comment by RenaissanceDork** [comment]
Thank you to @CapSel for creating this issue! I was having the exact problem described. My setup:

- Nextcloud Hub 26 Winter (33.0.0)
- "Contact Interaction" app in Nextcloud disabled
- iOS 26.3.1 (a)

However, when I deleted the account from the iPhone and re-added using the path `example.com/remote.php/carddav/principals/USERNAME/` I could then set the account as the default contact account. Note that I simply added the account as a CardDAV account directly in iOS' settings. I did not use the profile from the Nextcloud app.

I am adding this info in case it might be helpful to others.

**Comment by fsmeets** [comment]
After a lot of frustration today I found the comment by @andre1808 This worked for me with NC 33 and iOS 27 beta. I used the profile from the NC iOS app to configure the CardDav account.

**Comment by joao-p-marques** [comment]
> Thank you to [@CapSel](https://github.com/CapSel) for creating this issue! I was having the exact problem described. My setup:
> 
> * Nextcloud Hub 26 Winter (33.0.0)
> * "Contact Interaction" app in Nextcloud disabled
> * iOS 26.3.1 (a)
> 
> However, when I deleted the account from the iPhone and re-added using the path `example.com/remote.php/carddav/principals/USERNAME/` I could then set the account as the default contact account. Note that I simply added the account as a CardDAV account directly in iOS' settings. I did not use the profile from the Nextcloud app.
> 
> I am adding this info in case it might be helpful to others.

Running iOS 26 and NC 33, and this is the only thing that worked for me. Thanks!
