### ISSUE TITLE
Manually trigger contact photo download from social platforms

### ISSUE THREAD

**Issue by ntimo** [nextcloud/contacts#1872]
**Is your feature request related to a problem? Please describe.**
When setting up new contacts it should be possible to force the download of profile pictures from social networks so there avatar is available immediately without waiting a week. 

**Describe the solution you'd like**
A button or occ command is added to force the profile picture download

**Comment by call-me-matt** [comment]
I know, it's lacking description - but good news: that feature already exists!
The menu where you update a contacts picture is enhanced with entries for the supported social networks (if a respective entry is present for that contact)

![manually trigger get for social profile pictures](https://user-images.githubusercontent.com/34400929/82121847-5e377900-9790-11ea-8a76-4a51604c9612.gif)
