### ISSUE TITLE
Cannot bulk add contacts to groups

### ISSUE THREAD

**Issue by AuspeXeu** [nextcloud/contacts#1874]
### Describe the bug
When assigning a set of contacts to a group the app becomes unresponsive.

**To Reproduce**
1. Create a group
2. Press 'Add contacts'
3. Select a bunch of contacts to be added (8-12)
4. Open the console of the browser and see error appear as you click 'Add to group'

**Expected behavior**
No error and closing the dialog after the contacts are added.

**Actual behavior**
Error and freeze.

**Screenshots**
![image](https://user-images.githubusercontent.com/2115696/97018619-a8970000-154f-11eb-965b-a83861a27925.png)

### Server configuration
**Operating system**: Linux

**Web server:** Nginx...

**Database:** PostgreSQL

**PHP version:** 7.0

**Nextcloud version:** 20.0.0

**Contacts version:** 3.4.1

**Comment by skjnldsv** [comment]
Hey!
Can you manually try this release please?
[contacts.tar.gz](https://github.com/nextcloud/contacts/files/5438090/contacts.tar.gz)

**Comment by AuspeXeu** [comment]
Not sure how I would install this custom contacts archive.

**Comment by skjnldsv** [comment]
Depending on your setup, you just need to delete the contacts folder in your apps directory, and extract the archive there.
After you're done testing, you can delete the contacts folder again and re-install contacts via your apps settings (the traditional way)

Don't forget to clear your cache before testing
Hi! Before we continue, please do the following steps:
1. [clear your browser's cache](https://www.refreshyourcache.com/)
2. [run](https://docs.nextcloud.com/server/stable/admin_manual/configuration_server/occ_command.html#run-occ-as-your-http-user) an [`occ maintenance:repair`](https://docs.nextcloud.com/server/stable/admin_manual/configuration_server/occ_command.html#maintenance-commands-label) on your server

Thanks :wink:

**Comment by AuspeXeu** [comment]
The bulk add seems to work now, however I am getting the following error when I open the dialog and whenever I select a contact.

![image](https://user-images.githubusercontent.com/2115696/97203239-d6c94980-17b4-11eb-963c-0a54652dab5d.png)

**Comment by skjnldsv** [comment]
Thanks :)
I'll debug a bit further!

**Comment by goligo** [comment]
Which release will contain the fix for this issue?

**Comment by skjnldsv** [comment]
The upcoming one :)

**Comment by goligo** [comment]
Very funny.

**Comment by skjnldsv** [comment]
> Very funny.

I wasn't being funny. The current latest is something like 3.4.1 iirc, so this will be released as a patch release like we usually do :) 
You can fine the releases list on GitHub or our app store.

**Comment by goligo** [comment]
The issue has been closed, but a release containing the bug fix is not available yet. So from my perspective it is a valid question, when the fix will be available. Something like "The next patch release 3.4.2 is planned to be released next week." would have been helpful to me.

**Comment by skjnldsv** [comment]
Of course! But I'm not always remembering the latest version and we don't schedule release date here, so no ETA 😉
Enjoy the weekend! ✨
