### ISSUE TITLE
Group broken when creating new contact

### ISSUE THREAD

**Issue by lightonflux** [nextcloud/contacts#189]
### Steps to reproduce
1. Create new group "nextcloud bugs" in a new contact
2. change view to that group
3. create new contact in that view

### Expected behaviour

New contact should get the same group that is currently in view. Or none at all.

### Actual behaviour

Contact apps splits group name in single letters and adds the new contact to every latter as separate groups:

![bildschirmfoto von 2017-04-16 20-24-55](https://cloud.githubusercontent.com/assets/1377943/25073286/b918c452-22e3-11e7-9bb2-c1e1dd6628ed.png)

### Server configuration
**Operating system**: CentOS release 6.8 

**Web server:** apache

**Database:** sqlite 

**PHP version:** 5.6

**Nextcloud version:** 11.0.2 (stable)

**Contacts version:**  1.5.3

**Updated from an older Nextcloud or fresh install:** updated

**Signing status:** perfectly signed, no errors

**List of activated apps:**

```
Enabled:
  - activity: 2.4.1
  - admin_audit: 1.1.0
  - calendar: 1.5.1
  - comments: 1.1.0
  - contacts: 1.5.3
  - dav: 1.1.1
  - direct_menu: 0.10.0
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_pdfviewer: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - tasks: 0.9.5
  - templateeditor: 0.2
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - updatenotification: 1.1.1
  - workflowengine: 1.1.1
Disabled:
  - audioplayer
  - encryption
  - external
  - files_accesscontrol
  - files_automatedtagging
  - files_external
  - files_retention
  - spreed
  - user_external
  - user_ldap
  - user_saml
**Are you using encryption:** no

### Client configuration
**Browser:** Firefox 52

**Operating system:** Debian 9

**Comment by irgendwie** [comment]
ref. #156
