### ISSUE TITLE
l10n: Unusable text at Transifex with vue string

### ISSUE THREAD

**Issue by rakekniven** [nextcloud/contacts#1897]
https://github.com/nextcloud/contacts/blob/d5c693b77c65742360095b9385d6bea4b2713510/src/components/Settings/SettingsImportContacts.vue#L48

This results in :

![2020-10-28_15h45_21](https://user-images.githubusercontent.com/2069590/97452014-97c20200-1934-11eb-871d-8ca427a47d8b.png)

**Comment by skjnldsv** [comment]
It's fixed already, just wait for the next sync :)

**Comment by rakekniven** [comment]
Could you please reference commit? Try to learn every day 😄

**Comment by Valdnet** [comment]
@rakekniven I try to 😉.
