### ISSUE TITLE
catch missing ( in "apps/contacts/js/contacts-main.js"

### ISSUE THREAD

**Issue by Captain-FLAM** [nextcloud/contacts#1917]
Contacts version 3.4.1

I just changed the line 692, column 514, changing to **catch( ){ }**
because else contacts app doesn't work !

To the TEAM : please apply the modification for the next version.
Thanks.

**Comment by skjnldsv** [comment]
@Captain-FLAM this is compiled files.
Please explain your issue and process s well as give us some logs please

Hello!
I will need your browser console log to investigate this issue.
Open your console, reload your page and/or do the action leading to this issue and copy/paste the log in this thread.

<details>
<summary>How to access your browser console (Click to expand)</summary>

# Chrome
- Press either CTRL + SHIFT + J to open the “console” tab of the Developer Tools.
- Alternative method:
    1. Press either CTRL + SHIFT + I or F12 to open the Developer Tools.
    2. Click the “console” tab.

# Safari
- Press CMD + ALT + I to open the Web Inspector.
- See Chrome’s step 2. (Chrome and Safari have pretty much identical dev tools.)

# IE9
1. Press F12 to open the developer tools.
2. Click the “console” tab.

# Firefox
- Press CTRL + SHIFT + K to open the Web console (COMMAND + SHIFT + K on Macs).
- or, if Firebug is installed (recommended):
    1. Press F12 to open Firebug.
    2. Click on the “console” tab.

# Opera
1. Press CTRL + SHIFT + I to open Dragonfly.
2. Click on the “console” tab.
</details>

**Comment by skjnldsv** [comment]
Please also provide your nextcloud version and browser
