### ISSUE TITLE
Contacts with an accent are not imported correctly

### ISSUE THREAD

**Issue by Kalytis** [nextcloud/contacts#1921]
Hello,

### Describe the bug
I'm French, and I've got lots of contacts with an accent in their first/last name. However, when I mass-export my contacts in a VCF file, and then import them back to Contacts, all the contacts that had an accent fail to import.

No problem when importing a single accent-contact, alone in a VCF file.

**To Reproduce**
Create a contact with an accent in its name (é, è, à...)
Export all of your contacts
Import them in Nextcloud Contacts

**Expected behavior**
All the contacts should be imported correctly

**Actual behavior**
The contacts that have an accent in their name are not imported

### Server configuration

**Operating system**: Ubuntu 20.04

**Web server:** Nginx

**Database:** MariaDB

**PHP version:** 7.4

**Nextcloud version:** 20.0.1

**Contacts version:** 3.4.1

**Updated from an older Nextcloud or fresh install:** Fresh install

Thanks for your help !

**Comment by skjnldsv** [comment]
Works for me! :)
Can you post a contact example here please?

I will also need your browser console log to investigate this issue.
Open your console, reload your page and/or do the action leading to this issue and copy/paste the log in this thread.

<details>
<summary>How to access your browser console (Click to expand)</summary>

# Chrome
- Press either CTRL + SHIFT + J to open the “console” tab of the Developer Tools.
- Alternative method:
    1. Press either CTRL + SHIFT + I or F12 to open the Developer Tools.
    2. Click the “console” tab.

# Safari
- Press CMD + ALT + I to open the Web Inspector.
- See Chrome’s step 2. (Chrome and Safari have pretty much identical dev tools.)

# IE9
1. Press F12 to open the developer tools.
2. Click the “console” tab.

# Firefox
- Press CTRL + SHIFT + K to open the Web console (COMMAND + SHIFT + K on Macs).
- or, if Firebug is installed (recommended):
    1. Press F12 to open Firebug.
    2. Click on the “console” tab.

# Opera
1. Press CTRL + SHIFT + I to open Dragonfly.
2. Click on the “console” tab.
</details>

**Comment by Kalytis** [comment]
Really sorry about the delay.

I'm unable to reproduce aswell. It's very frustrating, but at least it's working, I guess...

Thanks a lot for your help !

**Comment by skjnldsv** [comment]
Thanks for the feedback! :)
