### ISSUE TITLE
Add fields to take Spouse and Children

### ISSUE THREAD

**Issue by bernd-wechner** [nextcloud/contacts#1924]
Yep, when working with contacts I often want to record the names of their spouse and children. Not an uncommon need. Workaround is to use notes fields, and usually have to use one (a work around). But Nextcloud Contacts can be a cut above the rest simply by supporting fields for that maybe?

Just a thought.  For triage obviously.

**Comment by skjnldsv** [comment]
Hey! :)
So, both spouse and children are already on the related and relationship fields:
https://github.com/nextcloud/contacts/blob/be28073fc83645825e0f1d0af8fce31b82a50ccf/src/models/rfcProps.js#L255
https://github.com/nextcloud/contacts/blob/be28073fc83645825e0f1d0af8fce31b82a50ccf/src/models/rfcProps.js#L286

**Comment by bernd-wechner** [comment]
Hey, thanks for the tip. Took a while to find it in the UI and alas I can only find it under "Relationship to you".

Which is not what I am after alas (like I need to make a special note about my own spouse and children ;-). 

No, much rather, given a contact I want a field t writ ether name of their spouse, and a field to write the name (and perhaps ages or years of birth) of their children. So that I can look up the contact and do the classic salesman's trick of "Hi X, how's Y? And I hope A, B, and C are donig fine. A must about to hit school next year?". because I have noted the names of their relations not mine ....

As I said, a Notes field is a classic work around. The thought here is to formalise it as it's a pretty common desire (IMHO) - to capture information about your contact (including their spouse and children's names).

**Comment by skjnldsv** [comment]
There are two types, one that is "Relationship to you" and one that is "Related contacts".
Related contacts is the one you're looking for. Theoritecally it should accept those types:
```vcard
   RELATED;TYPE=friend:urn:uuid:f81d4fae-7dec-11d0-a765-00a0c91e6bf6
   RELATED;TYPE=contact:http://example.com/directory/jdoe.vcf
   RELATED;TYPE=co-worker;VALUE=text:Please contact my assistant Jane Doe for any inquiries.
```

So either some text, either some uuid (direct link is most likely not what you want)

**Comment by bernd-wechner** [comment]
Hey wow that works. Was not what I'd call intuitive, but it works. When ir ead "related contacts" I assumed this to mean, contacts in Nextcloud, i..e NOT what I want, I specifically don't want to create a contact for each child and spouse, it is ancillary information against a contact I do deal with.

And then clicking the label to set the type, wow, I fluked a click on there to notice, that is so indirect and hidden.

And there was a bug in the search, I clicked the search bar and found a contact, tick, then clicked it and got a 404 error. Turns out the URL it jumps to is simply missing `index.php` before `apps`. This may be a webserver issue (and I can easily fix it I suspect by configuring it on the server, but it is the first and only time I've seen that. SO I checked the Files, Photos, Calendar and Bookmarks apps and their search bars all find things and when clicked send to a URL that loads (has `index.php` in the URL) so it looks like a Contacts search issue.  Perhaps a programmed premise that we have a server configured to work without index.php (it's nice, cleaner URLs and I should look into it). 

And then the Related contact has an icon to right, which when clicked opens http://textinthebox. So while it accepts a simple text (and I could enter a child's name and DOB or year of birth anyhow), there's an interesting link next to it that suggests the box should hold a URL. 

And finally, alas Cardbook doesn't see it. I'll drop a line to Cardbook to see if they'd be interested in recognising related contacts (as I do sue Cardbook in Thunderbird a lot)

**Comment by skjnldsv** [comment]
> so it looks like a Contacts search issue

it's actually both a setup and contacts issue #1852 

Please don't mix multiple issues on one. It's hard to track.
Since this one is resolved now, I'll close. Open new tickets for anything else that you might encounter (and after searching an existing issue doesn't already exists of course :+1: )
