### ISSUE TITLE
No tests specified

### ISSUE THREAD

**Issue by jangop** [nextcloud/contacts#1925]
The current documentation (`README.md`) states that “You can use the provided Makefile to run all tests by using: `make test`”

Inside `Makefile`, `test` is indeed defined:

```
test:
	npm run test
```

However, `package.json` contains no `test`:

```
	"scripts": {
		"build": "NODE_ENV=production webpack --progress --hide-modules --config webpack.js",
		"dev": "NODE_ENV=development webpack --progress --config webpack.js",
		"watch": "NODE_ENV=development webpack --progress --watch --config webpack.js",
		"lint": "eslint --ext .js,.vue src",
		"lint:fix": "eslint --ext .js,.vue src --fix",
		"stylelint": "stylelint src",
		"stylelint:fix": "stylelint src --fix"
	},
```

As such running `make test` returns:

```
Error: no test specified
```

**Comment by skjnldsv** [comment]
Yeah, right.
We don't have any frontend test for now :/

**Comment by ChristophWurst** [comment]
I've dropped those obsolete make targets from the Makefile and updated the readme
