### ISSUE TITLE
Inconsistent font sizes in address book menu

### ISSUE THREAD

**Issue by wiswedel** [nextcloud/contacts#1926]
The menu entries in the ... menu for address books have different font sizes:

![image](https://user-images.githubusercontent.com/1804221/98915314-08872380-24ca-11eb-943c-02e7f4a71ab2.png)

_Rename_ and _Delete_ are smaller than the rest.

Tested with Contacts 3.4.1 on Nextcloud 20.0.1

**Comment by skjnldsv** [comment]
Fixed in the components already :)

**Comment by skjnldsv** [comment]
Thanks for the report :rocket: :stars:
