### ISSUE TITLE
Restrict app to groups

### ISSUE THREAD

**Issue by szaimen** [nextcloud/contacts#1937]
I've searched for existing issues, but didn't found one, hence I opened this one.

**Is your feature request related to a problem? Please describe.**
Hey, I would like to restrict some users to not be able to use the contacts app. 

**Describe the solution you'd like**
I would like to be able to restrict the contacts app to specific groups without using the guests app.

**Describe alternatives you've considered**
Currently no idea

**Additional context**
Here is a screenshot for the calendar app:
![image](https://user-images.githubusercontent.com/42591237/99199863-5f2e7f00-27a2-11eb-8dc9-5a6b080b2970.png)

**Comment by skjnldsv** [comment]
Ah damn, contacts needs to have filesystem type in the appinfo to be able to register dav plugins
https://github.com/nextcloud/contacts/blob/3eefad88746550515c0c727070c21d649c24990c/appinfo/info.xml#L38

But when it's on, you cannot limit to group in the app management https://github.com/nextcloud/server/blob/228a96508a22b3805505ce61e0d36eba1e703460/apps/settings/src/mixins/AppManagement.js#L90

**Comment by szaimen** [comment]
@skjnldsv Thanks a lot, this was very fast! :D

**Comment by remihb** [comment]
Hi there, I need this feature but I can't find how to manually update an app to latest dev.
As far as I see, I can only get latest version of nextcloud app store (which is 4 weeks old for contacts).
Any tips to help me ?

**Comment by skjnldsv** [comment]
3.4.2 released @remihb

**Comment by remihb** [comment]
Just have to ask, cool ^^
So manual updating app is not possible, it is ?

**Comment by skjnldsv** [comment]
> So manual updating app is not possible, is it ?

From dev, you would have to pull github, compile the app, `make appstore` and install it manually by extracting the tarball. I don't recommend it

**Comment by remihb** [comment]
Fine thanks, it's just for the record :wink:
