### ISSUE TITLE
search / filter at "add contacts" dialog is case sensitive

### ISSUE THREAD

**Issue by 089** [nextcloud/contacts#1939]
### Describe the bug

As a user I want to find an existing contact in order to add it to a contact group. Currently the search is case sensitive. But IMHO it should not be. 

**To Reproduce**
1. Go to '/apps/contacts/'
2. Click on '...'-Symbol of a contact group
3. Click on 'Add contacts'
4. Search for a name of your choice in lower case only
5. See error: you do not see any result

**Expected behavior**
The search / filter should return results regardless of the upper or lower case or mixed case of the search term.

**Actual behavior**
The search / filter will only return results if the search term matches exactly.

**Screenshots**
That works: 

![Screenshot_Contacts_Stef_dsgvo](https://user-images.githubusercontent.com/7312003/99509590-3bc42980-2986-11eb-9d53-9fd85a293613.png)

That does not: 

![Screenshot_Contacts_stef](https://user-images.githubusercontent.com/7312003/99509206-c2c4d200-2985-11eb-97ba-666bc82c400f.png)

### Server configuration
**Operating system**: Linux 5.4.0-45-generic x86_64

**Web server:** Apache, Nginx...

**Database:** MariaDB, MySQL, PostgreSQL... 

**PHP version:** 7.0, 7.1, 7.2...

**Nextcloud version:** Nextcloud 19.0.4

**Contacts version:** 3.4.1

**Updated from an older Nextcloud or fresh install:** fresh

**Signing status:** 
```
No errors have been found.
```

**List of activated apps:**

**Nextcloud configuration:**

### Client configuration
**Browser:** Firefox 83.0

**Operating system:**

**CardDAV-clients:**

#### Browser log

```
jQuery is deprecated: The global jQuery is deprecated. It will be updated to v2.4 in Nextcloud 20 and v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 80 globals.js:61:15
Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf inline blockiert ("script-src"). utils.js:35:9
jQuery is deprecated: The global jQuery is deprecated. It will be updated to v2.4 in Nextcloud 20 and v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 108 globals.js:61:15
```

**Comment by skjnldsv** [comment]
https://github.com/nextcloud/contacts/blob/ce8992545a4bc9b63fb10a69380b5457880002cc/src/components/EntityPicker/EntityPicker.vue#L197
