### ISSUE TITLE
nothing shown after searching a contact and clicking on it

### ISSUE THREAD

**Issue by ramikilany** [nextcloud/contacts#1948]
### Describe the bug
I have contacts in my Contacts app, while searching for a name it shows the contact name in the search bar. Clicking on the name open a white page without content.

**To Reproduce**
1. Go to 'Contacts'
2. Click on 'Search'
3. Scroll down to 'the searched name'
4. Balnk Screen

**Expected behavior**
see the full contact info

**Actual behavior**
Blank whit screen with no result

**Screenshots**
![nextcloud](https://user-images.githubusercontent.com/22705122/100066862-3b240b00-2e3e-11eb-94d3-56afa9112bcb.png)

### Server configuration

**Operating system**: Ubuntu 20.04

**Web server:** Apache

**Database:** MariaDB

**PHP version:** 7.4

**Nextcloud version:** 20.0.2

**Contacts version:** 3.4.2

**Fresh install**

**Signing status:**
```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

**List of activated apps:**
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**Nextcloud configuration:**
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your instance's installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

### Client configuration
**Browser:Firefox 83**

**Operating system:Pop!_OS**

**CardDAV-clients:**

#### *Web server error log*
```
Insert your webserver log here
```

#### *data/nextcloud.log*
```
Insert your Nextcloud log here
```

#### Browser log
<details>
<summary>How to access your browser console (Click to expand)</summary>

# Chrome
- Press either CTRL + SHIFT + J to open the “console” tab of the Developer Tools.
- Alternative method:
    1. Press either CTRL + SHIFT + I or F12 to open the Developer Tools.
    2. Click the “console” tab.

# Safari
- Press CTRL + ALT + I to open the Web Inspector.
- See Chrome’s step 2. (Chrome and Safari have pretty much identical dev tools.)

# IE9
1. Press F12 to open the developer tools.
2. Click the “console” tab.

# Firefox
- Press CTRL + SHIFT + K to open the Web console (COMMAND + SHIFT + K on Macs).
- or, if Firebug is installed (recommended):
    1. Press F12 to open Firebug.
    2. Click on the “console” tab.

# Opera
1. Press CTRL + SHIFT + I to open Dragonfly.
2. Click on the “console” tab.
</details>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by skjnldsv** [comment]
https://github.com/nextcloud/contacts/issues/1852
