### ISSUE TITLE
Translated in Transifex, not available in the app

### ISSUE THREAD

**Issue by keunes** [nextcloud/contacts#1949]
Hello,

Not really a bug, but more of a support question: [one string](https://www.transifex.com/nextcloud/nextcloud/translate/#nl/contacts/300411949) is translated in Dutch on Transifex two months ago, but doesn't seem translated in the app. Were translations not pulled in this period, or is it actually a different string that I'm seeing untranslated?

I have the contacts app version 3.4.2.

In the screenshot below 'My contacts' is in English (which is to be expected, as it's a name of an address book that I can change). But the title '**Recently contacted**' is not user-changeable and translated on Transifex, so I suspect it should be translated in the app also (?)

![Schermafdruk van 2020-11-24 14-55-10](https://user-images.githubusercontent.com/11229646/100103442-3292fb00-2e65-11eb-92c0-835ba95c0442.png)

**Comment by ChristophWurst** [comment]
https://github.com/nextcloud/server/blob/master/apps/contactsinteraction/l10n/nl.js seems to be translated by now.
