### ISSUE TITLE
Send correct content-type in AJAX

### ISSUE THREAD

**Issue by gjedeer** [nextcloud/contacts#196]
Adding a new contact sends a PUT request with the following header:

```
Content-Type: application/xml;charset=UTF-8
```

The PUT body, however, is a text/vcard document. 

This is a problem with mod_security which rejects the requests because it cannot parse XML in a request body that's supposed to be XML, so it's a violation of the HTTP protocol.

I think this could be solved by adding:

```
xhr.setRequestHeader("text/vcard;charset=UTF8");
```

somewhere in the AJAX flow, but I was unable to locate the right place.

**Comment by irgendwie** [comment]
Thanks for reporting (and finding) this issue! :+1:

**Comment by gjedeer** [comment]
Thank you, the speed of response was amazing! 

I tested the patch and it works correctly. Now Nextcloud hits another rule in the ruleset but this time it's a problem with the ruleset not NC.
