### ISSUE TITLE
Loading contacts

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/contacts#1966]
**To Reproduce**
1. Select "Import Contacts".
2. Click on the button "Import from files".
3. Close the window without selecting any contacts file.

**Expected behavior**
Return to the file location button selection window.

**Actual behavior**
Constant display of the loading wheel.

![obraz](https://user-images.githubusercontent.com/47037905/101261750-d4ee9080-3739-11eb-823c-986a5eb92383.png)

### Server configuration

**Nextcloud version:** (see Nextcloud admin page)
20.0.2

**Contacts version:** (see Nextcloud apps page)
3.4.2

### Client configuration
**Browser:**
Firefox 83.0

**Operating system:**
Win10

**Comment by skjnldsv** [comment]
Hello!
I will need your browser console log to investigate this issue.
Open your console, reload your page and/or do the action leading to this issue and copy/paste the log in this thread.

<details>
<summary>How to access your browser console (Click to expand)</summary>

# Chrome
- Press either CTRL + SHIFT + J to open the “console” tab of the Developer Tools.
- Alternative method:
    1. Press either CTRL + SHIFT + I or F12 to open the Developer Tools.
    2. Click the “console” tab.

# Safari
- Press CMD + ALT + I to open the Web Inspector.
- See Chrome’s step 2. (Chrome and Safari have pretty much identical dev tools.)

# IE9
1. Press F12 to open the developer tools.
2. Click the “console” tab.

# Firefox
- Press CTRL + SHIFT + K to open the Web console (COMMAND + SHIFT + K on Macs).
- or, if Firebug is installed (recommended):
    1. Press F12 to open Firebug.
    2. Click on the “console” tab.

# Opera
1. Press CTRL + SHIFT + I to open Dragonfly.
2. Click on the “console” tab.
</details>

**Comment by Valdnet** [comment]
> I will need your browser console log to investigate this issue.

There are no errors in the browser.

**Comment by skjnldsv** [comment]
Even the debug output is important :)

**Comment by Valdnet** [comment]
What I was able to get:
```
Błąd mapy źródła: Error: The operation was aborted. 
URL zasobu: http://xxx.xxx.pl/apps/text/js/files.js?v=9855d732-3
URL mapy źródła: files.js.map
```

**Comment by skjnldsv** [comment]
Ah, sorry, I can reproduce now.
I misread your issue, my apologies :)

**Comment by joshtrichards** [comment]
No longer reproducible in Contacts v5.5.1 one. Closing.
