### ISSUE TITLE
Line breaks in address field lost

### ISSUE THREAD

**Issue by dbolton** [nextcloud/contacts#1967]
### Describe the bug
Samsung phone stores addresses in a single multi-line address field. Nextcloud contacts displays these as a single line. If you save changes in the Nextcloud contacts app the line breaks are permanently gone (or become \n) 

**To Reproduce**
1. Save multiline address on Samsung phone
2. Sync contacts
3. Edit contact in Nextcloud contacts app
4. Sync contacts

**Expected behavior**
Ideally Nextcloud contacts would display multiline addresses. Next best would be to not delete the line breaks. 

**Actual behavior**
Nextcloud contacts deleted the line breaks or converts them to \n

**Screenshots**

### Server configuration

**Operating system**: Android/Samsung

**Web server:** Apache, Nginx...

**Database:** MySQL 5.7

**PHP version:** 7.2

**Nextcloud version:** 19

**Contacts version:** 3.4.2

**Updated from an older Nextcloud or fresh install:** updated

**Signing status:** 
```
No errors have been found.
```

**List of activated apps:**
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**Nextcloud configuration:**
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your instance's installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

### Client configuration
**Browser:** firefox

**Operating system:** Android/Windows

**CardDAV-clients:** Samsung contacts with DAVx5, Thunderbird

#### *Web server error log*
```
Insert your webserver log here
```

#### *data/nextcloud.log*
```
Insert your Nextcloud log here
```

#### Browser log
<details>
<summary>How to access your browser console (Click to expand)</summary>

# Chrome
- Press either CTRL + SHIFT + J to open the “console” tab of the Developer Tools.
- Alternative method:
    1. Press either CTRL + SHIFT + I or F12 to open the Developer Tools.
    2. Click the “console” tab.

# Safari
- Press CTRL + ALT + I to open the Web Inspector.
- See Chrome’s step 2. (Chrome and Safari have pretty much identical dev tools.)

# IE9
1. Press F12 to open the developer tools.
2. Click the “console” tab.

# Firefox
- Press CTRL + SHIFT + K to open the Web console (COMMAND + SHIFT + K on Macs).
- or, if Firebug is installed (recommended):
    1. Press F12 to open Firebug.
    2. Click on the “console” tab.

# Opera
1. Press CTRL + SHIFT + I to open Dragonfly.
2. Click on the “console” tab.
</details>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by chlarsen** [comment]
Same here, continue to be a problem with Nextcloud 21.0.1.1 with Contacts 3.5.1.
The Contacts module is compatible with the Google Android 11 Contacts address format, with separate fields for Street, Street (2nd line), Town/City, District/Region and Country. However, other contact apps do not follow this format, and only offer one multi-line address field instead, which Nextcloud imports into the first Street field, with "\n" as Posix-compliant line break. Alas, the FLOSS address books from F-Droid all follow the latter standard, so that we are used to use Google's Contact app with a FLOSS cloud instance. (Nextcloud, that is). This IS a bit painful :-)...

**Comment by sciurius** [comment]
> which Nextcloud imports into the first Street field, with "\n" as Posix-compliant line break.

The problem is that the line breaks disappear from the text. E.g. "Street 27\n345678 Foo" becomes "Street 27345678 Foo".

**Comment by eisenherzz** [comment]
"\n" on the other hand creates problems here. Just imported an address book (coming from google). Worked fine for the Nextcloud side and Android. Just noticed that contacts with "\n" do not get synced to iOS contacts app. Only thing I found was removing "\n" manually from the addresses.

**Comment by SebastianKrupinski** [comment]
This should now be resolved.
