### ISSUE TITLE
Custom phone number label does not appear in contacts

### ISSUE THREAD

**Issue by finkandreas** [nextcloud/contacts#1969]
### Describe the bug
When I create a phone number with a custom label on my Android phone, it does not appear in the contacts frontend, there is simply no number visible.

**To Reproduce**
1. Create a new contact on your Android (8) phone
2. Add a phone number with a Custom label (e.g. John)
3. Sync from phone to nextcloud server (DAVx5)
4. Open the contact in your browser and see that there is no phone number
5. Download the contact, and see that the phone number is in the VCF available, it's simply not shown in the user interface.

**Expected behavior**
I would expect to see the label and the phone number

**Actual behavior**
No phone number is visible
Downloaded vcf file:
```
BEGIN:VCARD
VERSION:3.0
PRODID:-//Sabre//Sabre VObject 4.3.0//EN
UID:91884d87-9210-4d27-b074-caf676e9fff5
FN:Testcontact
N:;Testcontact;;;
GROUP1.TEL;TYPE=x-john:+1 234-567-890
GROUP1.X-ABLABEL:John
REV:20201209T075008Z
END:VCARD
```
**Screenshots**
The user interface shows only this information:
![scrot](https://user-images.githubusercontent.com/15714790/101601560-1a8eb000-39fd-11eb-9d90-6da418473012.jpg)

### Server configuration
**Operating system**: Linux 5.9.9-gentoo #1 SMP Sun Nov 22 10:47:11 CET 2020 x86_64

**Web server:** Apache (apache2handler)

**Database:** mysql 10.5.8

**PHP version:** 7.4.13
Modules loaded: Core, date, libxml, openssl, pcre, zlib, bcmath, bz2, ctype, curl, dba, dom, fileinfo, filter, gd, gettext, gmp, hash, iconv, SPL, intl, json, mbstring, session, standard, mysqlnd, PDO, pdo_mysql, Phar, posix, Reflection, mysqli, SimpleXML, soap, imap, tokenizer, xml, xmlreader, xmlwriter, xsl, zip, apache2handler, imagick, Zend OPcache7.0, 7.1, 7.2...

**Nextcloud version:** 20.0.2 - 20.0.2.2

**Contacts version:** (see Nextcloud apps page)

**Updated from an older Nextcloud or fresh install:** Updated from older version (cannot remember where I started, but rolling updates constantly, probably started with one of the first official releases after forking from owncloud)

**List of activated apps:**
```
Enabled:
  - accessibility: 1.6.0
  - activity: 2.13.3
  - admin_audit: 1.10.0
  - calendar: 2.1.2
  - cloud_federation_api: 1.3.0
  - comments: 1.10.0
  - contacts: 3.4.2
  - contactsinteraction: 1.1.0
  - cospend: 1.2.2
  - dashboard: 7.0.0
  - dav: 1.16.1
  - federatedfilesharing: 1.10.1
  - federation: 1.10.1
  - files: 1.15.0
  - files_pdfviewer: 2.0.1
  - files_rightclick: 0.17.0
  - files_sharing: 1.12.0
  - files_trashbin: 1.10.1
  - files_versions: 1.13.0
  - files_videoplayer: 1.9.0
  - firstrunwizard: 2.9.0
  - logreader: 2.5.0
  - lookup_server_connector: 1.8.0
  - nextcloud_announcements: 1.9.0
  - notifications: 2.8.0
  - oauth2: 1.8.0
  - password_policy: 1.10.1
  - photos: 1.2.0
  - privacy: 1.4.0
  - provisioning_api: 1.10.0
  - recommendations: 0.8.0
  - serverinfo: 1.10.0
  - settings: 1.2.0
  - sharebymail: 1.10.0
  - spreed: 10.0.3
  - support: 1.3.0
  - survey_client: 1.8.0
  - systemtags: 1.10.0
  - tasks: 0.13.6
  - text: 3.1.0
  - theming: 1.11.0
  - twofactor_backupcodes: 1.9.0
  - updatenotification: 1.10.0
  - user_status: 1.0.1
  - viewer: 1.4.0
  - weather_status: 1.0.0
  - workflowengine: 2.2.0
Disabled:
  - bruteforcesettings
  - encryption
  - files_external
  - user_ldap
```

**Nextcloud configuration:**
```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "forcessl": false,
        "theme": "",
        "trusted_domains": [
            "owncloud.***********.***"
        ],
        "version": "20.0.2.2",
        "loglevel": 2,
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trashbin_retention_obligation": "auto, 30",
        "maintenance": false,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "sendmail",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "log_rotate_size": 1048576,
        "overwrite.cli.url": "https:\/\/owncloud.***********.***",
        "htaccess.RewriteBase": "\/",
        "mysql.utf8mb4": true,
        "versions_retention_obligation": "auto, 180",
        "app_install_overwrite": [
            "contacts"
        ]
    }
}
```

### Client configuration
**Browser:**
firefox-83

**Operating system:**
Android-8

**CardDAV-clients:**
DAVx5

**Comment by skjnldsv** [comment]
https://github.com/nextcloud/contacts/issues/1842
