### ISSUE TITLE
Importing contacts which are written in arabic in a vcard file is not possible.

### ISSUE THREAD

**Issue by mdalch** [nextcloud/contacts#1984]
my vcard file contains contacts which written in both arabic and english, when i tried to import this file, only contacts with english names were imported.

**Comment by j-ed** [comment]
Unfortunately you've totally ignored the issue template and didn't provide the requested information. Additionally you haven't  provided an example vcf file which contains arabic characters. How should a developer classify your issue or reproduce it without any valuable information? Therefore please update your issue report and add the requested information.

**Comment by mdalch** [comment]
Sorry for the inconvenient, you are absolutely right. It seems the problem was from the csv file. I did export my contacts to a vcard for ios from contacts.google.com, and then i imported this file in nextcloud and it worked.

Previously I used export to a google csv and it didn’t work properly.
