### ISSUE TITLE
more of a question. will corrupt contacts that disappear cause issues later on?

### ISSUE THREAD

**Issue by allanblgrease** [nextcloud/contacts#1993]
### Describe the bug
......
"contacts" disappears after importing a corrupt vcf file. i tried importing this vcard about three times and i am worried that these files are still on my server and may cause issues later on. or do they auto delete?
side note: 
i was able to pick apart my vcard file and found an invalid character in one of the card names.. how that got corrupt i dont know but i was able to delete it and retype it and it imported fine after that.. so my concern is that the three other times of trying to import that corrupt file and causing my contacts file to disappear will later cause issues? if so how do i find and delete them?
......

**To Reproduce**
1. Go to '.contacts..'
2. Click on '..import..'
3. Scroll down to '..a corrupt vcf file and click ok..'
4. See error.. all contacts disappear 

**Expected behavior**
Tell us what you expected to happen.
contacts import

**Actual behavior**
Tell us what happened instead.
everything gone

**Screenshots**

### Server configuration

**Operating system**: Windows, Linux, MacOS...
my os is windows.. server is linux

**Web server:** Apache, Nginx...

**Database:** MariaDB, MySQL, PostgreSQL... 

**PHP version:** 7.0, 7.1, 7.2...

**Nextcloud version:** (see Nextcloud admin page)

**Contacts version:** (see Nextcloud apps page)

**Updated from an older Nextcloud or fresh install:**

**Signing status:**
```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

**List of activated apps:**
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**Nextcloud configuration:**
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your instance's installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

### Client configuration
**Browser:**

**Operating system:**

**CardDAV-clients:**

#### *Web server error log*
```
Insert your webserver log here
```

#### *data/nextcloud.log*
```
Insert your Nextcloud log here
```

#### Browser log
<details>
<summary>How to access your browser console (Click to expand)</summary>

# Chrome
- Press either CTRL + SHIFT + J to open the “console” tab of the Developer Tools.
- Alternative method:
    1. Press either CTRL + SHIFT + I or F12 to open the Developer Tools.
    2. Click the “console” tab.

# Safari
- Press CTRL + ALT + I to open the Web Inspector.
- See Chrome’s step 2. (Chrome and Safari have pretty much identical dev tools.)

# IE9
1. Press F12 to open the developer tools.
2. Click the “console” tab.

# Firefox
- Press CTRL + SHIFT + K to open the Web console (COMMAND + SHIFT + K on Macs).
- or, if Firebug is installed (recommended):
    1. Press F12 to open Firebug.
    2. Click on the “console” tab.

# Opera
1. Press CTRL + SHIFT + I to open Dragonfly.
2. Click on the “console” tab.
</details>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by skjnldsv** [comment]
Hi,

Sorry I didn't see your ticket!
I will need your browser console log to investigate this issue.
Open your console, reload your page and/or do the action leading to this issue and copy/paste the log in this thread.

<details>
<summary>How to access your browser console (Click to expand)</summary>

# Chrome
- Press either CTRL + SHIFT + J to open the “console” tab of the Developer Tools.
- Alternative method:
    1. Press either CTRL + SHIFT + I or F12 to open the Developer Tools.
    2. Click the “console” tab.

# Safari
- Press CMD + ALT + I to open the Web Inspector.
- See Chrome’s step 2. (Chrome and Safari have pretty much identical dev tools.)

# IE9
1. Press F12 to open the developer tools.
2. Click the “console” tab.

# Firefox
- Press CTRL + SHIFT + K to open the Web console (COMMAND + SHIFT + K on Macs).
- or, if Firebug is installed (recommended):
    1. Press F12 to open Firebug.
    2. Click on the “console” tab.

# Opera
1. Press CTRL + SHIFT + I to open Dragonfly.
2. Click on the “console” tab.
</details>

**Comment by allanblgrease** [comment]
issue resolved..
    with the use of davx5 on my android tablet i was able to sync my nextcloud contacts into my tablet. all of the corrupt contacts seem to load into the tablet just fine.. i then deleted the corrupt contact cards one at a time using the tablet, and as soon as i did all the files that had the corrupt contact cards all started to became available under the setting within the nextcloud contacts page (via the pc web browser).. and i was able to then delete that contact file..
i no longer have 3 dead links of the same contact when searching contacts. yea for me.. 

sorry i didnt provide enough info for you at the time of crating this ticket.. 
.

**Comment by allanblgrease** [comment]
thank you all for your time..
