### ISSUE TITLE
Tarball for 3.4.3 seems to contain 3.4.2

### ISSUE THREAD

**Issue by michaelkuhn** [nextcloud/contacts#2003]
### Describe the bug

I just wanted to upgrade to the newest release but noticed that the tarball for 3.4.3 seems to contain version 3.4.2. This only applies to the tarball not automatically generated by GitHub (https://github.com/nextcloud/contacts/releases/download/v3.4.3/contacts.tar.gz).

### To Reproduce

1. Go to releases page
2. Download contacts.tar.gz for 3.4.3

**Comment by skjnldsv** [comment]
It's fixed already :)
