### ISSUE TITLE
Contacts 3.4.3 recursion: properties using X-ABLabel not displayed in the NC web interface

### ISSUE THREAD

**Issue by LittleAlf** [nextcloud/contacts#2005]
### X-ABLabel recursion
A carddav entry synchronised from an Android phone or Mozilla Thunderbird with Nextcloud does **not** show the properties using X-ABLabel **in the NC web interface**. These entries are still there, but not shown!

Here the VCARD file from the original entry created in Thunderbird. and exported from it:
```
BEGIN:VCARD
VERSION:4.0
PRODID:-//Thunderbird.net/NONSGML Thunderbird CardBook V54.6//DE
UID:6f1396b9-7669-4cbc-b497-e5988f087bd9
FN:NachnameTB\, VornameTB
N:NachnameTB;VornameTB;;;
ITEM1.EMAIL:nach.vor@gmx.net
ITEM1.X-ABLABEL:User Defined Email Label
ITEM2.TEL:+1 1111
ITEM2.X-ABLABEL:User Defined Phone Label
REV:20210108T200438Z
X-THUNDERBIRD-ETAG:"3b7f9e6d771cbbfa0cd959064f8c7119"
END:VCARD

```
Here is the VCARD file re-exported from Nextcloud after this entry was synchronized with Thunderbird:
```
BEGIN:VCARD
VERSION:3.0
PRODID:-//Sabre//Sabre VObject 4.3.0//EN
UID:6f1396b9-7669-4cbc-b497-e5988f087bd9
FN:NachnameTB\, VornameTB
N:NachnameTB;VornameTB;;;
ITEM1.EMAIL:nach.vor@gmx.net
ITEM1.X-ABLABEL:User Defined Email Label
ITEM2.X-ABLABEL:User Defined Phone Label
ITEM2.TEL:+1 1111
REV:20210108T200438Z
END:VCARD

```
And here now, how it looks in the Nextcloud web interface. **Both entries using X-ABLabel are not shown**:
![grafik](https://user-images.githubusercontent.com/25395270/104064204-ca725b80-51fd-11eb-9b7b-dee570800dc1.png)

### System configuration:
- Nextcloud 19.0.6
- Contacts 3.4.3
- Android 10 phone using DAV5X Version 3.3.7 _or_
- Windows 10 64bit 20H2 with Mozilla Thinderbird 78.6.0 and CardDAV 54.6

If further infos are required, please, let me know.

### To Reproduce
1. Create a new entry in the Android contacts app or in Mozilla Thunderbird using user defined labels for phone number and/or email address.
2. Wait until these new entries are syncronized on the Nextcloud server or force a manual sync.
3. Display this new entry in the NC contacts web interface.

**Expected behavior**
The entries using X-ABLabel are corrected displayed in the NC contacts web interface.

This worked properly in earlier versions of the contacts app. It would be great if this would work again, because a hidden entry is misleading, and might lead to a deletion of the entry even though it contains data!

LittleAlf

**Comment by skjnldsv** [comment]
https://github.com/nextcloud/contacts/issues/1842
