### ISSUE TITLE
changes form #101 are not in the nightly build?

### ISSUE THREAD

**Issue by meikestone** [nextcloud/contacts#201]
Hello,

maybe I'm wrong, but I don't find the changes from 
https://github.com/nextcloud/contacts/pull/101
in the nightly builds?! What is my mistake?

Operating system: Ubuntu LTS 16.04 
Web server: Apache/2.4.18
Database: MariaDB 10.0.29
PHP version: 7.0
Nextcloud version: 11.0.2 (stable)
Contacts version: nextcloud_contacts_nightly_build_2017-04-22.tar.gz
Updated from an older Nextcloud or fresh install: fresh install

Thanks Meike

Btw.: I come from OC 8.1 and the contact app works quite perfect, especially with more than one address book. Why it must all reinvented?

**Comment by jancborchardt** [comment]
Any info on this @nextcloud/contacts? I guess meanwhile there has been a new release so I’m closing this.

@meikestone just for info: This contacts app is not reinventing stuff. :) The developers moved from oc to Nextcloud.
