### ISSUE TITLE
Instagram Profile Images Not Scraped

### ISSUE THREAD

**Issue by Ge0rg3** [nextcloud/contacts#2016]
_This is very similar to #2012, so please check that one out first :)_

### Describe the bug
When trying to use the "Get from instagram" button to assign profile photos from a twitter link, the user is shown a "Avatar download failed" error message, and the logs show the following:
```
Exception: Argument 1 passed to OC\Http\Client\Client::get() must be of the type string, null given, called in /var/www/nextcloud/apps/contacts/lib/Service/SocialApiService.php on line 213
```
I think this may be because Instagram now requires a valid session to view accounts, so I'm not sure how we can fix this without an API key.

### Example curl
```
curl -i -L https://www.instagram.com/barackobama/?__a=1 -H "User-Agent: Googlebot/2.1"
```
Please see how only the login screen is returned.

**Comment by call-me-matt** [comment]
I believe this is what happens after a certain amount of requests, but I am not sure. Anyways, not a good state. Ideas very welcome...

**Comment by skjnldsv** [comment]
@Ge0rg3 can you confirmed it works again after some time?

**Comment by Ge0rg3** [comment]
Nope, never works for me. Straight to the login page instead

**Comment by call-me-matt** [comment]
Maybe we can follow the discussion here?
https://gist.github.com/cosmocatalano/4544576
So far, no solution to this :cry:

**Comment by Ge0rg3** [comment]
Yep too bad, maybe we should disable the option until a workaround is found in future?

**Comment by call-me-matt** [comment]
Either that, or we add a setting to insert ones account details?

**Comment by call-me-matt** [comment]
@Ge0rg3 I suppose you have already tried [adding a user agent](https://github.com/nextcloud/contacts/blob/fix/insta-agent/lib/Service/Social/InstagramProvider.php) (as you have done in #2012)? For me, it works more reliable with that.

**Comment by Ge0rg3** [comment]
Yeah I think it helped slightly, but same issue after 2 or so reqs.
