### ISSUE TITLE
Wrong text with escaped special characters for "city" in contacts

### ISSUE THREAD

**Issue by stweil** [nextcloud/contacts#2020]
I just wanted to update a contact entry and noticed this text in the field "Stadt" (city): `Markt Lappersdorf @ESCAPEDLEFTPARENTHESIS@OT Kareth@ESCAPEDRIGHTPARENTHESIS@`.

The original text was of course `Markt Lappersdorf (OT Kareth)`.

My version of contacts is 3.4.3.

The original text was entered at least 2 years (or more) ago. The error might have gone unnoticed since some time. In the meantime I also switched the database from sqlite to mariadb. So it might be difficult to narrow down when and how the buggy text was introduced.

**Comment by ChristophWurst** [comment]
> ESCAPEDLEFTPARENTHESIS

I'M unable to find where that string is coming from. It's neither in this app nor server.

**Comment by stweil** [comment]
It looks like this was not a bug in Nextcloud, but a bug in CardBook. Clients running Thunderbird with CardBook have read/write access to the Nextcloud contacts via CardDAV, and there is a related (closed) issue for CardBook: https://gitlab.com/CardBook/CardBook/-/issues/888.

Sorry for the noise here. I close the issue.
