### ISSUE TITLE
Contacts App: change address book of a contact leads to error.

### ISSUE THREAD

**Issue by UteHaus** [nextcloud/contacts#2021]
### Steps to reproduce in Contacts
1. open a contact
2. set the address book value to the same value

### Expected behaviour
Consol outputs
TypeError: e is null
Error: Moving an object to the collection it's already part of is not supported
Error: Moving an object to the collection it's already part of is not supported
Masonry reflow ContactDetails.vue:774

### Server configuration

**Operating system:**
default Docker setup

**Web server:**
default Docker setup

**Database:**
Postgres 10

**PHP version:**
default Docker setup

**Nextcloud version:**
20.0.5

**Where did you install Nextcloud from:**
default Docker setup
[contancs_app-consol-error.txt](https://github.com/nextcloud/contacts/files/5825876/contancs_app-consol-error.txt)

**Comment by ChristophWurst** [comment]
Likely fixed with https://github.com/nextcloud/contacts/pull/2086
