### ISSUE TITLE
Meta: Sponsorship, no contribution tiers on Open Collective

### ISSUE THREAD

**Issue by giddyhup** [nextcloud/contacts#2022]
I'd like to sponsor Nextcloud and the Contacts app in particular (not just to get my favorite [issue ](https://github.com/nextcloud/contacts/issues/1107) addressed but for me it is the most used feature of Nextcloud). Yet it seems there are tiers to pick from on the Open Collective profile. Am I missing something?

**Comment by skjnldsv** [comment]
Yes, it seems like we're not really ready for opencollective. We tried migrating away from bountysource after their terms of service change, but we really haven't found a perfect solution yet :(

**Comment by skjnldsv** [comment]
I removed the link for clarity. Thanks for the heads up :)
