### ISSUE TITLE
[Question] how do I update a vcard via webdav API?

### ISSUE THREAD

**Issue by fisx** [nextcloud/contacts#2024]
This is not really a feature request, but more of a support question.  If there is any good resource where I can learn how to talk to this app via HTTP in my own code, I'd be very greatful for a link.  If there is documentation where this *should* be, and if you help me solve this, I'll make a PR to add it there.

I'm trying to write a script that updates the vcard with the put method.  The script is in haskell (using a fork of http://hackage.haskell.org/package/DAV, but that shouldn't be of concern here).

## Expected behavior:

the request should be answered with status 2xx. vcard should be update, and i should be able to see the updates in the nextcloud.

## Actual behavior:

the request is answered with 400; body contains "VCard object with uid already exists in this addressbook collection."  Fetching that same vcard with a corresponding get request on the same URL works fine.

## Request details:

I know connection to the server and authentication / authorization works because it works when I fetch the same vCard, and I use the same code to do it in both cases.  Here is the request:

```
Request {
  host                 = "<REDACTED>"
  port                 = 443
  secure               = True
  requestHeaders       = [("Authorization","<REDACTED>"),("User-Agent","hDAV/1.3.4"),("Content-Type","text/vcard; charset=utf-8")]
  path                 = "/remote.php/dav/addressbooks/users/<REDACTED>/some_address_book/2F9C49FC-5A97-11EB-9479-9B3B7B291B20.VCF"
  queryString          = ""
  method               = "PUT"
  requestVersion       = HTTP/1.1
}
```

The body contains a valid vcard (i got it from the same backend, and haven't changed it yet):

```
"BEGIN:VCARD\r\nVERSION:3.0\r\nPRODID:[...]\r\nEND:VCARD\r\n"
```

## Ideas:

Maybe I need to lock the resource before I can write to it?

**Comment by fisx** [comment]
I should probably add that I am completely clueless about the nextcloud architecture and code base.  Just trying to talk HTTP to it!  :-)

**Comment by skjnldsv** [comment]
It's not webdav, it's carddav.
You can find lots of ressources on how to manually manage carddav. Much better than whatever I could explain here :)

What I can tell you is that you can find the addressbooks URIs from the bottom left settings area.

**Comment by fisx** [comment]
> It's not webdav, it's carddav.

[technically](https://tools.ietf.org/html/rfc6352), carddav is an extension of webdav, but i wasn't aware of carddav, so this was still very helpful, thanks!

> You can find lots of ressources on how to manually manage carddav. Much better than whatever I could explain here :)

agreed, i'm on it!

> What I can tell you is that you can find the addressbooks URIs from the bottom left settings area.

yes, i was aware of that, but then i got stuck guessing how to send an update to a vcard.  let's see what the rfc can teach me.  :)

thanks, feel free to close this issue, but i'll add more answers to my question as i learn more, and close it myself once i've solved it completely.

**Comment by fisx** [comment]
I solved it here: https://github.com/fisx/hdav/

The readme contains a link to a tutorial that already contained the solution: https://sabre.io/dav/building-a-carddav-client/
