### ISSUE TITLE
Inanimate Entity

### ISSUE THREAD

**Issue by madorian** [nextcloud/contacts#203]
Why start developing a new entity management system and not think about the following.

The system expects a person, but I want to add an organization. Next I want to add a contact to this organization and further details about his position in this node structure (organization).

I further may want to make this entity public, so that others can see it (on the blockchain) and add info to it or I may even search for info about this organization and add it to my dataset.

Why doesn't it support tags? It support "groups", whatever non generic term that may be, but it's not indexed together with my "file" tags.

**Comment by skjnldsv** [comment]
I didn't understand what you meant sorry! :(
Could you be more specific?

**Comment by irgendwie** [comment]
No response, closing this for now - feel free to reopen the issue and further explain the feature you want to be added.
