### ISSUE TITLE
Can not sync the field "Language" of Outlook contact to Nextcloud Contact

### ISSUE THREAD

**Issue by enzoZestick** [nextcloud/contacts#2032]
Hello to everyone.

I'm trying to sync my outlook addressbook to nextcloud Contacts and till now it sync every information except the "Language" field. 

is there a way how to fix this?

Thank you  lot

**Comment by SebastianKrupinski** [comment]
Hi.

I know this is an old issue, but I was wondering if you could provide a export of the vcard from outlook and an export of the contact from Nextcloud.

Thank you
