### ISSUE TITLE
Customizable date

### ISSUE THREAD

**Issue by macapple194** [nextcloud/contacts#2037]
It would be useful to include an additional field for dates that was customizable (like on Google contacts). In this way it would be possible to insert other significant dates other than birthdays or anniversaries.
Thanks

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by skjnldsv** [comment]
Hi, unfortunately those are not official.
This relate to the property `X-ABDATE`, and aside from google, lots of contacts software does not understand those. 

See https://github.com/nextcloud/contacts/issues/223
