### ISSUE TITLE
Bug: Creation of Group with non-latin characters not possible

### ISSUE THREAD

**Issue by frankmayer** [nextcloud/contacts#2038]
### Steps to reproduce
1. Go into Contacts
2. Click "+New group"
3. In the text field enter anything non-latin (I entered "Δοκιμή" which is greek for "Test")
    Attention: The group will display in the list, but will not actually be created in the backend until a contact is added to it.
4. Try to add a contact to this list. It will fail, displaying "Adding 0 contacts to Δοκιμή"... and Browser log (console) throws the message I have included below

### Expected behaviour
Group is created, contact is added

### Actual behaviour
Fails to create group and add a contact

## Server configuration detail

**Operating system:** Linux 5.4.0-65-generic #73-Ubuntu SMP Mon Jan 18 17:25:17 UTC 2021 x86_64

**Webserver:** Apache/2.4.38 (Debian) (apache2handler)

**Database:** mariadb 10.5.8

**PHP version:** 

7.4.14
Modules loaded: Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, PDO, session, posix, Reflection, standard, SimpleXML, pdo_sqlite, Phar, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, apache2handler, apcu, bcmath, exif, gd, gmp, imagick, intl, ldap, memcached, pcntl, pdo_mysql, pdo_pgsql, redis, sodium, zip, Zend OPcache

**Nextcloud version:** 20.0.6 - 20.0.6.1

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.6.0
 - activity: 2.13.4
 - announcementcenter: 4.0.1
 - appointments: 1.8.1
 - apporder: 0.11.0
 - breezedark: 20.0.3
 - bruteforcesettings: 2.0.1
 - calendar: 2.1.3
 - circles: 0.20.6
 - cloud_federation_api: 1.3.0
 - comments: 1.10.0
 - contacts: 3.4.3
 - contactsinteraction: 1.1.0
 - dashboard: 7.0.0
 - dav: 1.16.2
 - deck: 1.2.3
 - epubreader: 1.4.5
 - event_update_notification: 1.2.0
 - external: 3.7.2
 - federatedfilesharing: 1.10.2
 - federation: 1.10.1
 - files: 1.15.0
 - files_automatedtagging: 1.10.1
 - files_markdown: 2.3.1
 - files_mindmap: 0.0.24
 - files_pdfviewer: 2.0.1
 - files_retention: 1.9.0
 - files_rightclick: 0.17.0
 - files_sharing: 1.12.2
 - files_texteditor: 2.14.0
 - files_trashbin: 1.10.1
 - files_versions: 1.13.0
 - files_videoplayer: 1.9.0
 - firstrunwizard: 2.9.0
 - flow_notifications: 1.0.3
 - flowupload: 1.1.2
 - forms: 2.1.0
 - groupfolders: 8.2.0
 - impersonate: 1.7.0
 - issuetemplate: 0.7.0
 - logreader: 2.5.0
 - lookup_server_connector: 1.8.0
 - nextcloud_announcements: 1.9.0
 - notes: 3.5.1
 - notifications: 2.8.0
 - oauth2: 1.8.0
 - password_policy: 1.10.1
 - pdfdraw: 0.1.2
 - photos: 1.2.3
 - polls: 1.7.5
 - privacy: 1.4.0
 - provisioning_api: 1.10.0
 - quicknotes: 0.6.3
 - quota_warning: 1.9.1
 - recommendations: 0.8.0
 - serverinfo: 1.10.0
 - settings: 1.2.0
 - sharebymail: 1.10.0
 - side_menu: 1.21.0
 - socialsharing_email: 2.1.0
 - socialsharing_facebook: 2.1.0
 - socialsharing_twitter: 2.1.0
 - spreed: 10.0.5
 - support: 1.3.0
 - survey_client: 1.8.0
 - systemtags: 1.10.0
 - talk_simple_poll: 1.2.0
 - tasks: 0.13.6
 - theming: 1.11.0
 - twofactor_backupcodes: 1.9.0
 - updatenotification: 1.10.0
 - user_saml: 3.3.3
 - user_status: 1.0.1
 - viewer: 1.4.0
 - weather_status: 1.0.0
 - whiteboard: 0.0.3
 - workflowengine: 2.2.0
Disabled:
 - admin_audit
 - encryption
 - files_external
 - hsts
 - registration
 - richdocumentscode
 - text
 - twofactor_email
 - twofactor_nextcloud_notification
 - user_ldap
 - workflow_script

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "htaccess.RewriteBase": "\/",
    "memcache.local": "\\OC\\Memcache\\APCu",
    "apps_paths": [
        {
            "path": "\/var\/www\/html\/apps",
            "url": "\/apps",
            "writable": false
        },
        {
            "path": "\/var\/www\/html\/custom_apps",
            "url": "\/custom_apps",
            "writable": true
        }
    ],
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "kgtz-nextcloud.frankmayer.net"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "20.0.6.1",
    "overwrite.cli.url": "http:\/\/kgtz-nextcloud.frankmayer.net",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "overwriteprotocol": "https",
    "mail_smtpmode": "smtp",
    "mail_smtpsecure": "tls",
    "mail_sendmailmode": "smtp",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauthtype": "LOGIN",
    "mail_smtpauth": 1,
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "25",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "maintenance": false,
    "app_install_overwrite": [
        "joplin",
        "documents"
    ]
}
```
</details>

**Are you using external storage, if yes which one:** 

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** 

## Client configuration

**Browser:** Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.96 Safari/537.36

**Operating system:** 

## Logs

<details><summary>Web server error log</summary>

```

```
</details>

<details><summary>Nextcloud log</summary>

```

```
</details>

<details><summary>Browser log</summary>

Contacts.vue:793 TypeError: Failed to execute 'setRequestHeader' on 'XMLHttpRequest': String contains non ISO-8859-1 code point.
    at xhr.js:125
    at Object.u [as forEach] (utils.js:253)
    at xhr.js:119
    at new Promise (<anonymous>)
    at e.exports (xhr.js:13)
    at e.exports (dispatchRequest.js:50)
</details>

**Comment by catkic** [comment]
I have the same problem

**Comment by frankmayer** [comment]
This issue https://github.com/nextcloud/deck/issues/2780 is probably having the same underlying problem.

**Comment by SebastianKrupinski** [comment]
Tested. This is now working.
