### ISSUE TITLE
Phone numbers and addresses with custom labels not visible

### ISSUE THREAD

**Issue by langfingaz** [nextcloud/contacts#2039]
### Description

I've created a contact "Abc" with three phone numbers and two addresses on my Android phone which syncs with DAVdroid to Nextcloud.

The contact has one mobile phone number and two other ones with custom names/labels "Test" and "Testing". Additionally it has two addresses with custom names/labels "Primary" and "Secondary".

**Expected behavior**
All 3 phone numbers and the two addresses should be visible when viewing the contact in the Nextcloud Contacts app.

Additionally it would be nice to see the custom labels such as for the first address: "Primary: Some Address".

**Actual behavior**
Only the first number (with the predefined label "Mobile") is visible. The other two numbers and the two addresses are not displayed.

**The contact from the vcf exported from Nextcloud Contacts**

```
BEGIN:VCARD
VERSION:4.0
PRODID:+//IDN bitfire.at//DAVx5/3.3.8-ose ez-vcard/0.11.2
UID:d349b67e-e17d-4016-9b37-4d97e5f9a962
FN:Abc
N:;Abc;;;
TEL;TYPE=cell:123456
GROUP1.TEL;TYPE=x-test:234567
GROUP2.TEL;TYPE=x-testing:345678
GROUP1.X-ABLABEL:Test
GROUP2.X-ABLABEL:Testing
GROUP3.X-ABLABEL:Primary
GROUP4.X-ABLABEL:Secondary
GROUP3.ADR;TYPE=x-primary;LABEL=Some Address:;;Some Address;;;;
GROUP4.ADR;TYPE=x-secondary;LABEL=Another Address:;;Another Address;;;;
REV:20210204T165134Z
END:VCARD
```

**Screenshots**
![Nextcloud Contacts](https://user-images.githubusercontent.com/10504672/106927702-b9d8d680-6712-11eb-9147-0cc5deba8b08.png)

On my phone where the contact was created (LineageOS contacts app):
![Android Contacts app](https://user-images.githubusercontent.com/10504672/106928234-41bee080-6713-11eb-919a-02d3510f390d.png)

### Server configuration

**Operating system**: Nextcloud Docker Alpine

**Web server:** Nginx (Docker)

**Database:** MariaDB (Docker)

**Nextcloud version:** 20.0.6

**Contacts version:** 3.4.3

**Updated from an older Nextcloud or fresh install:** fresh install

**Signing status:**
```
No errors have been found.
```

**List of activated apps and Nextcloud configuration:**
Not sure if this is related to my configuration. But if required, I can provide this.

### Client configuration
**Browser:** Firefox 85.0

**Operating system:** Archlinux

**CardDAV-clients:** DAVx^5 3.3.8-ose

#### *data/nextcloud.log*
I didn't notice anything pop up in the log while viewing the contact in Firefox

#### Browser log
I don't think this is related to client side rendering, but can of course provide my browser log if it may be helpful.

**Comment by troem** [comment]
Hello,

I have a similar / same issue. Even if I type the contact manual in the contacts app itself - all phone-numbers / e-mail addresses / addresses with custom labels will be hidden / are not shown.

**Comment by vince-from-nice** [comment]
It's a duplicate of my issue: https://github.com/nextcloud/contacts/issues/1997

I hope it will be fixed soon.

**Comment by langfingaz** [comment]
Thanks for notifying. I think we can close this issue then in favour of yours.

**Comment by vince-from-nice** [comment]
No matter for me but the advantage of having 2 issue is that the bug is more visible and has a better chance of being fixed quickly ;)
