### ISSUE TITLE
[Feature Request] Please add a Ressources Contact Type

### ISSUE THREAD

**Issue by Mannshoch** [nextcloud/contacts#204]
For our Club we need a List of Locations with their Ressources. At moment we added them as Person in a separate address-book and entered information in the Note field.

Ressources could also be used for the [nextcloud/calendar](https://github.com/nextcloud/calendar)
![ressource](https://cloud.githubusercontent.com/assets/7795891/25424102/728961f0-2a67-11e7-81d5-b64f466333d4.png)

**Comment by skjnldsv** [comment]
@Mannshoch Unfortunately we do not add properties that only us will support and that are not fficially supported by the rfc standards https://tools.ietf.org/html/rfc6350#page-2
Thus I will close this one.

Unless there is an existing property that I'm not aware of, in that case please explain a bit and re-open :)

**Comment by Mannshoch** [comment]
As a modification of my Request allow only to mark an Addressboock as a resource. The idea to add own fields is not needed.
