### ISSUE TITLE
GPS entry not displayed correctly in Contacts app

### ISSUE THREAD

**Issue by Dieter15** [nextcloud/contacts#2048]
### Describe the bug
1. A valid vCard (v3.0) entry of type "GEO" (conformant to RFC 6350) results in incorrect representation of the GPS data. The Contacts app adds a new field called "Location" but displays "0" instead of the (valid) GPS data.

2. A valid vCard (v4.0) entry of type "GEO:geo" (conformant to RFC 6350)  does not result in the display of a new field "Location".

BEGIN:VCARD
VERSION:3.0
FN:Smith\, John
N:Smith;John;;
BDAY:19370119
ADR;type=home:;;Wallstreet 1;New York;New Jersey;12345;USA
GEO:49.123456;9.87654
REV:20210202T080324Z
END:VCARD

BEGIN:VCARD
VERSION:4.0
FN:Smith\, John
N:Smith;John;;
BDAY:19370119
ADR;type=home:;;Wallstreet 1;New York;New Jersey;12345;USA
GEO:geo:49.123456,9.87654
REV:20210202T080324Z
END:VCARD

**To Reproduce**
1. Use the VCF file above
2. Import it in Contacts app
3. Display the person's vCard data
4. Look at field "Location"

**Expected behavior**
vCard 3.0: The contacts app is expected to show the GPS data (contained in the VCF file), not "0".
vCard 4.0: The contacts app is expected to show a field "Location" and displaying the GPS data (contained in the VCF file).

**Actual behavior**
See above

**Screenshots**

### Server configuration

**Operating system**: Windows, Linux, MacOS...
Debian 10

**Web server:** Apache, Nginx...
Apache 2.4.38

**Database:** MariaDB, MySQL, PostgreSQL... 
MariaDB

**PHP version:** 7.0, 7.1, 7.2...
PHP7.3

**Nextcloud version:** (see Nextcloud admin page)
NC 20.0.7

**Contacts version:** (see Nextcloud apps page)
v3.4.3

**Updated from an older Nextcloud or fresh install:**
Fresh install

**No further evidence required to solve this bug.**

**Signing status:**
```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

**List of activated apps:**
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**Nextcloud configuration:**
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your instance's installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

### Client configuration
**Browser:**

**Operating system:**

**CardDAV-clients:**

#### *Web server error log*
```
Insert your webserver log here
```

#### *data/nextcloud.log*
```
Insert your Nextcloud log here
```

#### Browser log
<details>
<summary>How to access your browser console (Click to expand)</summary>

# Chrome
- Press either CTRL + SHIFT + J to open the “console” tab of the Developer Tools.
- Alternative method:
    1. Press either CTRL + SHIFT + I or F12 to open the Developer Tools.
    2. Click the “console” tab.

# Safari
- Press CTRL + ALT + I to open the Web Inspector.
- See Chrome’s step 2. (Chrome and Safari have pretty much identical dev tools.)

# IE9
1. Press F12 to open the developer tools.
2. Click the “console” tab.

# Firefox
- Press CTRL + SHIFT + K to open the Web console (COMMAND + SHIFT + K on Macs).
- or, if Firebug is installed (recommended):
    1. Press F12 to open Firebug.
    2. Click on the “console” tab.

# Opera
1. Press CTRL + SHIFT + I to open Dragonfly.
2. Click on the “console” tab.
</details>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by SebastianKrupinski** [comment]
Tested. This is now working.
