### ISSUE TITLE
groups are not arranged alphabetical

### ISSUE THREAD

**Issue by droogi** [nextcloud/contacts#2051]
Hello, i grouped my contacs in own group categories.
these categories are displayed not alphabetical, i dont see any order.
its difficult to find the groups. (Gruppe)
Regards, droogi

**Comment by skjnldsv** [comment]
They are since 3.4.0 :)
https://github.com/nextcloud/contacts/pull/1788

**Comment by droogi** [comment]
sorry for wrong description.
groups are not in order when creating new contact and you choose the group from the list

**Comment by droogi** [comment]
![image](https://user-images.githubusercontent.com/4030579/108170848-f89b6300-70fa-11eb-95ec-7285b479262c.png)

**Comment by skjnldsv** [comment]
Got it! Thanks for the report :)

Next time, please use the provided template, and add screenshots/versions number etc etc :pray:

**Comment by droogi** [comment]
thanks
