### ISSUE TITLE
Sort groups

### ISSUE THREAD

**Issue by serversci** [nextcloud/contacts#2060]
**Problem:** In **/index.php/settings/users**, the Groups are listed, not not in dictionary-sorted order.

**Expected:** The groups would be shown in sorted order. This makes selection easier.

**Workarounds:** If I know the name of a group, I can search the web page above for the desired group name.

Is there any possible use of **occ** or other approach to force the group names to be sorted?

**Comment by skjnldsv** [comment]
They are since 3.4.0 https://github.com/nextcloud/contacts/pull/1788
