### ISSUE TITLE
Creating a contact in a group does not work

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/contacts#207]
### Steps to reproduce
1. Select a group
2. Create a new contact inside of this selected group
3. The name of the group is not shown as one word, it was splitted into the single letters - some letters are missing 🙄 

<img width="1073" alt="bildschirmfoto 2017-05-05 um 10 30 12" src="https://cloud.githubusercontent.com/assets/19711361/25738528/f93f84be-317d-11e7-8c37-afc6c8bdad57.png">

### Server configuration

**Operating system**:
Ubuntu 16.04
**Web server:**
Apache
**Database:**
SQLite 3.11.0
**PHP version:**
7.1.4
**Nextcloud version:** (see Nextcloud admin page)
12.0 beta1
**Contacts version:** (see Nextcloud apps page)
1.5.3

### Client configuration
**Browser:**
Safari 10.1.1
**Operating system:**
macOS Sierra 10.12.5 beta

**Comment by irgendwie** [comment]
duplicate and already fixed by https://github.com/nextcloud/contacts/pull/191
