### ISSUE TITLE
vCard object rejected if it contains both an UID and BDAY entry

### ISSUE THREAD

**Issue by Dieter15** [nextcloud/contacts#2082]
### Describe the bug
NC 20.0.7, NC Contacts app version 3.4.3, on Raspberry Pi 4B, Debian 10.8, Apache 2.4.38, PHP7.3.27.

I created several VCF files, each containing some vCard objects (v3.0). Every vCard object has a UID entry according to RFC 6530. Note that UID is an optional entry in vCard v3.0 and vCard4.0.

Some vCard objects also have a (valid) BDAY entry like BDAY:yyyymmdd.

Importing a VCF file yields exactly as many errors as are BDAY entries in it. This has been tested with all of my VCF files which are different from each other.

Deleting the UID entry (though it conforms to RFC 6530) does not yield errors during VCF import in NC Contacts app.

As a conclusion having both an UID entry and a BDAY entry in a vCard object (BEGIN:VCARD ... END:VCARD) yields an error.

Since UID is a valid entry in a vCard object, it should properly supported by NC.

Sample VCF file / vCard object:
BEGIN:VCARD
VERSION:3.0
UID:urn:uuid:abcdef-0123-4567-89ab-abcdefabcdef
FN:Smith\, John
N:Smith;John;;
BDAY:19790404
ADR;type=home:;;Wall street 1;New York;New Jersey;12345;USA
TEL;TYPE=home,voice:+1-234-56789
EMAIL;TYPE=home:john.smith@snakeoil.org
REV:20210222T080324Z
END:VCARD

**To Reproduce**
1. Create an NC calendar
2. Import vCard object (see above)
3. See error
4.  Fix the NC calendar bug

**Expected behavior**
Any UID entry which is conformant to RFC 6530 should be accepted by NC Calendar app.
This should be true both for vcard v3.0 als well as for vCard 4.0

**Actual behavior**
vCard object was NOT accepted if it contained both an UID and a BDAY entry.

**Screenshots**
Not needed

### Server configuration
Use up-to-date software (NC, Contacts app)

**Operating system**: Windows, Linux, MacOS...
Linux Dbeian 10.8

**Web server:** Apache, Nginx...
Apache 2.4.38

**Database:** MariaDB, MySQL, PostgreSQL... 
MariaDB

**PHP version:** 7.0, 7.1, 7.2...
PHP 7.3.27 (latest version on Raspberry)

**Nextcloud version:** (see Nextcloud admin page)
NC 20.0.7

**Contacts version:** (see Nextcloud apps page)
Contacts app 3.4.3

**Updated from an older Nextcloud or fresh install:**
Fresh install

**Signing status:**
Obviously not of interest

**List of activated apps:**
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**Nextcloud configuration:**
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your instance's installation folder

**Comment by skjnldsv** [comment]
What is the exact error the server returns please?
