### ISSUE TITLE
Export generates dupe PRODID tags which break Import

### ISSUE THREAD

**Issue by JaimeObregon** [nextcloud/contacts#209]
On **Nextcloud 12.0.0 beta 1** downloaded yesterday May 7th, exported an existing address book with 426 contacts and immediately imported it into a newly created, empty address book. Then three serious issues happened, which render the whole export/import heavily unpredictable: 

1. 70% of the contacts were not imported.
2. The importing process throws vague, useless errors: "Could not create the contact". 
3. Reimporting is not idempotent, generating duplicates and leaving the address book in an unpredictable state.

This is an screenshot of the errors I got (using the Spanish localization):
![captura de pantalla 2017-05-08 a las 8 55 17](https://cloud.githubusercontent.com/assets/417226/25793586/82e8b432-33cd-11e7-9869-911d85ce1293.png)

I would suggest:

* Ability to import all the contacts exported.
* More descriptive error notices, indicating which contact failed to import, and why.
* Idempotent / atomic importing.

### Steps to reproduce
1. Exported an existing address book with 426 contacts.
2. Created a new, empty address book.
3. Imported the previously exported contacts.

### Expected behaviour
426 contacts imported.

### Actual behaviour
Only 132 contacts imported.

### Server configuration

**Operating system**: CentOS 6.7 Final.

**Web server:** Apache

**Database:** MySQL

**PHP version:** 5.6

**Nextcloud version:** 12.0 beta 1

**Contacts version:** 1.5.3

**Updated from an older Nextcloud or fresh install:** Updated from 11.0.2

**Signing status:**

```
No errors have been found.
```

### Client configuration
**Browser:** Chrome 57

**Operating system:** macOS 10.12

**CardDAV-clients:** Web client.

**Comment by JaimeObregon** [comment]
I dug deeper into this and `tail -f nextcloud.log`'ed while retrying the import, finding out what seems to be the ultimate cause of point #1 in my original report:

```
Validation error in vCard: PRODID MUST NOT appear more than once in a VCARD component
```

A closer look at the freshly exported `.vcf` file shows many contacts with duplicated `VERSION` and `PRODID` tags:

```
BEGIN:VCARD
VERSION:3.0
VERSION:3.0
VERSION:3.0
VERSION:3.0
VERSION:3.0
PRODID:-//ownCloud//NONSGML Contacts 0.5.0.0//EN
PRODID:-//Sabre//Sabre VObject 3.4.7//EN
PRODID:-//Apple Inc.//Mac OS X 10.11.2//EN
N:Doe;John;;;
FN:John Doe
ORG:John Doe Corporation;
TEL;TYPE=WORK,VOICE,pref:999999999
TEL;TYPE=CELL,VOICE:999999999
ADR;TYPE=HOME,pref:;;;Alabama;;;
X-ABUID:D1038C47-C9A9-4E73-A480-XXXXXXXXXXXXX:ABPerson
X-MOZILLA-HTML:FALSE
UID:d418796d-a8c8-42e7-xxxx-xxxxxxxxxxxx
REV:2016-01-02T23:57:55+00:00
END:VCARD
```

**Comment by JaimeObregon** [comment]
I manually edited my `.vcf` file and removed all the duplicated `PRODID` tags, then retried the process in a blank address book and got no errors and all the contacts imported, thus confirming the cause of the error. I will now rename this issue for clarity.

**Comment by irgendwie** [comment]
The VERSION and PRODID should only be present once in the vcard.
I doubt that export in nextcloud produced these kind of vcards and rather the fields were present multiple times before. The only difference is, that they are now correctly validated and rejected by the dav backend.

I think we should validate contacts before importing and try to repair them.

**Comment by JaimeObregon** [comment]
I see. However at the end the invalid `.vcf` file with multiple `VERSION` and `PRODID` is generated by the Contacts application. Would it be a more robust approach to just always generate valid export files, in addition to validate the file in the backend when importing?

Regarding the possible cause of this duplicated `PRODID`, over the time I have managed my address books with many iOS and macOS devices, as well as the [Lightning addon](https://addons.mozilla.org/thunderbird/addon/lightning/) for Mozilla Thunderbird, which as far as I can tell uses a [Sabre](http://sabre.io) client under the hood. Three of these seem to have left their `PRODID`:

```
PRODID:-//ownCloud//NONSGML Contacts 0.5.0.0//EN
PRODID:-//Sabre//Sabre VObject 3.4.7//EN
PRODID:-//Apple Inc.//Mac OS X 10.11.2//EN
```

**Comment by irgendwie** [comment]
Normally the PRODID describes which application created the vcard - therefore should only be added when the vcard is created. Export in the contacts app is currently handled by the sabre/dav backend, we are just calling a link.

**Comment by skjnldsv** [comment]
@irgendwie 
> I think we should validate contacts before importing and try to repair them.

Didn't we already worked on this?

**Comment by skjnldsv** [comment]
Duplicate #129
