### ISSUE TITLE
Unable to add the Birthday field to existing contacts

### ISSUE THREAD

**Issue by schneidr** [nextcloud/contacts#2096]
I am unable to add the Birthday field to existing contacts. For newly created contacts the field Birthday is available.

### Steps to reproduce
1. Go to an existing contact
2. Click on 'Add new property'
3. 'Birthday' is not available.

### Expected behaviour
I expect to be able to add a Birthday field

### Actual behaviour
The field is not available.

![image](https://user-images.githubusercontent.com/401729/109480006-490bac80-7a7b-11eb-8389-729a94b72dd9.png)

## Server configuration detail

**Operating system:** Linux 4.15.0-126-generic #129-Ubuntu SMP Mon Nov 23 18:53:38 UTC 2020 x86_64

**Webserver:** Apache/2.4.29 (apache2handler)

**Database:** mysql 5.7.33

**PHP version:** 

7.2.24-0ubuntu0.18.04.7
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, sodium, session, standard, apache2handler, mysqlnd, PDO, xml, apcu, bcmath, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, gmp, iconv, igbinary, imagick, imap, intl, json, ldap, exif, mcrypt, memcache, msgpack, mysqli, pdo_mysql, pdo_sqlite, Phar, posix, readline, shmop, SimpleXML, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, yaml, zip, memcached, Zend OPcache

**Nextcloud version:** 20.0.8 - 20.0.8.1

**Updated from an older Nextcloud/ownCloud or fresh install:** 19.x

**Where did you install Nextcloud from:** nextcloud.com

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.6.0
 - activity: 2.13.4
 - admin_audit: 1.10.0
 - calendar: 2.1.3
 - cloud_federation_api: 1.3.0
 - comments: 1.10.0
 - contacts: 3.4.3
 - contactsinteraction: 1.1.0
 - cookbook: 0.8.1
 - dashboard: 7.0.0
 - dav: 1.16.2
 - federatedfilesharing: 1.10.2
 - federation: 1.10.1
 - files: 1.15.0
 - files_pdfviewer: 2.0.1
 - files_rightclick: 0.17.0
 - files_sharing: 1.12.2
 - files_trashbin: 1.10.1
 - files_versions: 1.13.0
 - files_videoplayer: 1.9.0
 - firstrunwizard: 2.9.0
 - issuetemplate: 0.7.0
 - logreader: 2.5.0
 - lookup_server_connector: 1.8.0
 - news: 15.3.2
 - nextcloud_announcements: 1.9.0
 - notifications: 2.8.0
 - oauth2: 1.8.0
 - password_policy: 1.10.1
 - photos: 1.2.3
 - privacy: 1.4.0
 - provisioning_api: 1.10.0
 - recommendations: 0.8.0
 - serverinfo: 1.10.0
 - settings: 1.2.0
 - sharebymail: 1.10.0
 - spreed: 10.0.6
 - systemtags: 1.10.0
 - text: 3.1.0
 - theming: 1.11.0
 - twofactor_backupcodes: 1.9.0
 - updatenotification: 1.10.0
 - user_status: 1.0.1
 - viewer: 1.4.0
 - weather_status: 1.0.0
 - workflowengine: 2.2.0
Disabled:
 - encryption
 - files_external
 - occweb
 - support
 - survey_client
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "cloud.schneidr.de"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "https:\/\/example.com",
    "dbtype": "mysql",
    "version": "20.0.8.1",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "logtimezone": "UTC",
    "installed": true,
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "sendmail",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "maintenance": false,
    "loglevel": 0,
    "theme": "",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauthtype": "LOGIN",
    "memcache.local": "\\OC\\Memcache\\Memcached",
    "memcache.distributed": "\\OC\\Memcache\\Memcached",
    "memcached_servers": [
        [
            "localhost",
            11211
        ]
    ],
    "mysql.utf8mb4": true,
    "app_install_overwrite": [
        "calendar",
        "occweb"
    ],
    "mail_sendmailmode": "smtp"
}
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** no

## Client configuration

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36

**Operating system:** Windows 10

## Logs

<details><summary>Web server error log</summary>

```
Insert your web server log here 
```
</details>

<details><summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

<details><summary>Browser log</summary>

Insert your browser log here, this could for example include:

	a) The javascript console log
	b) The network log
	c) ...
</details>

**Comment by schneidr** [comment]
Addition: Existing Birthdays are not shown. I checked the MySQL database and found a row with the `name`='BDAY' for the corresponding contact in the `oc_cards_properties` table. But it is not shown in the UI. I guess this would explain why I can't add it, but it doesn't explain why it isn't shown. The birthday calendar is empty as well.

**Comment by schneidr** [comment]
I added a birthday to a contact that didn't have one and compared it on the database.

The newly added birthday was in the format

    19800301

While the existing birthday was in the format

    01.03.1980

Just rewriting the `dd.mm.yyyy` format to `yyyymmdd` didn't help though, the birthday neither shows up on the calendar, nor on the contact UI.

**Comment by skjnldsv** [comment]
Hey! Yes, we don't show the birthday if there is already one as only one is allowed per vcard.
yours seems invalid, could you post the console log please?

Open your console, reload your page and/or do the action leading to this issue and copy/paste the log in this thread.

<details>
<summary>How to access your browser console (Click to expand)</summary>

# Chrome
- Press either CTRL + SHIFT + J to open the “console” tab of the Developer Tools.
- Alternative method:
    1. Press either CTRL + SHIFT + I or F12 to open the Developer Tools.
    2. Click the “console” tab.

# Safari
- Press CMD + ALT + I to open the Web Inspector.
- See Chrome’s step 2. (Chrome and Safari have pretty much identical dev tools.)

# IE9
1. Press F12 to open the developer tools.
2. Click the “console” tab.

# Firefox
- Press CTRL + SHIFT + K to open the Web console (COMMAND + SHIFT + K on Macs).
- or, if Firebug is installed (recommended):
    1. Press F12 to open Firebug.
    2. Click on the “console” tab.

# Opera
1. Press CTRL + SHIFT + I to open Dragonfly.
2. Click on the “console” tab.
</details>

**Comment by schneidr** [comment]
The console log after clicking on the user:

    vue.runtime.esm.js:1888 Error: Could not extract integer from ".1"
        at Object.strictParseInt (ical.js:122)
        at n (ical.js:6251)
        at Function.ICAL.VCardTime.fromDateAndOrTimeString (ical.js:6267)
        at Object.decorate (ical.js:988)
        at t._decorate (ical.js:2939)
        at t._hydrateValue (ical.js:2922)
        at t.getFirstValue (ical.js:3068)
        at s.get (ContactDetailsProperty.vue:302)
        at mn.get (vue.runtime.esm.js:4479)
        at mn.evaluate (vue.runtime.esm.js:4584)

But that only confirms that it is stored in an invalid format. The question is: How do I correct it in the database? Just rewriting the date doesn't work, or I could just run a simple script to change it in the database. It is cached somewhere else? I already tried restarting memcached, which I use as a caching server, but that didn't help either.

**Comment by schneidr** [comment]
Since I'm not getting an answer here I resorted to solve the issue by this:

- I exported my contacts into a .vcf file
- I ran search and replace over the .vcf file with the following regular expression:
    Search: `(\d{2})\.(\d{2})\.(\d{4})`
    Replace: `$3$2$1`
- I deleted my address book
- I created a new address book with the name `default`
- I imported the edited .vcf file

Now all birthdays are correct.

**Comment by skjnldsv** [comment]
Thanks, we definitely need to help on those date formats. The vcard library seems to have a lot of issues understanding the various formats :/

**Comment by SebastianKrupinski** [comment]
Tested. This is now working.
