### ISSUE TITLE
Some Contacts show: twitter:https://twitter.com/

### ISSUE THREAD

**Issue by Mannshoch** [nextcloud/contacts#210]
Nextcloud 11.0.3
On some Contacts I added "Social Network" entries now they appear like that:
`twitter:https://twitter.com/{Name}`

If I download the vCard I got following textentry
`IMPP;X-SERVICE-TYPE=facebook:xmpp:https://www.facebook.com/{Name}`

**Comment by skjnldsv** [comment]
Can't reproduce, if correct service is selected in the dropdown, the correct informations are saved
`X-SOCIALPROFILE;TYPE=TWITTER:twitter:https://twitter.com/TEST
`
