### ISSUE TITLE
Select group for a read-only contact possible

### ISSUE THREAD

**Issue by doitux** [nextcloud/contacts#2101]
I'm a default user of a big NC instance. The admin shared a read-only address book. When i select a contact from this address book i'm not able to edit contact information **except** the group affiliations. If i create a new group i'm able to add read-only contacts to the group. But after refreshing the page the whole group is gone :-1: 

I think currently it is a bug that i'm able to select group affiliations for read-only contacts. 
Or the bug is about not syncing the group affiliations to the DB, so it is gone when refreshing the page. 

But maybe in the future it would be a nice to have this issue as a new feature :+1: 

Unfortunately i'm not able to give information about the server or app version and configuration because i have no admin access.

**Comment by matclab** [comment]
We have exactly the same problem on nextcloud 26.0.2 and contact 5.2.0

**Comment by GVodyanov** [comment]
This has been fixed!
