### ISSUE TITLE
Allow events/hooks to trigger other apps

### ISSUE THREAD

**Issue by Schack17** [nextcloud/contacts#211]
Allow events/hooks to trigger other apps on create, change or delete contacts.
Usecase: Trigger a change and export the changed contact to an external phonebook. Fritz!Box as example.

**Comment by skjnldsv** [comment]
You mean an api ?

**Comment by j-ed** [comment]
As far as I understand this request, @Schack17 is looking for a way to define external program calls which are initiated each time an address record is modified. This would allow to initiate updates of other address books, like the one of a [Fritz!Box internet router](https://avm.de/produkte/fritzbox/) which also works as a small PBX.

BTW, this kind of activity can currently only be handled by setting-up a regular cronjob calling e.g. the following program: https://github.com/carlos22/carddav2fb

**Comment by Schack17** [comment]
@skjnldsv : @j-ed says exatly what I mean.

**Comment by tacruc** [comment]
Is as simple as adding Hooks into OCA\DAV\CardDAV\CardDavBackend ?

Where is the catch?

**Comment by skjnldsv** [comment]
There is no catch! But it's indeed not relevant to the contacts app!
You can create plugins linked to nextcloud dav, but regarding adding hooks on the javascript side, this is out of scope (and php is what you should use anyway for this) :)

So I'm closing this one!

@tacruc have a look at the existing plugins on `nextcloud/server/apps/dav`. You'll find some nice examples! :wink:

**Comment by tacruc** [comment]
>  But it's indeed not relevant to the contacts app!

I agree let me just use this for one quick Question.

@skjnldsv can you help me, and name one example, I searched already and clound't find a nice existing plugin for the cards?

And Of course I'm talking about HOOKS on the php side.

**Comment by skjnldsv** [comment]
@tacruc hum, I thought we were already using dav hooks on our plugins :thinking: 
It depends on what you are trying to do! There is many different hooks available, within nextcloud but within dav as well. :)
