### ISSUE TITLE
input for date via calender is inconvenient

### ISSUE THREAD

**Issue by droogi** [nextcloud/contacts#2116]
the input or editing of birthday /day of death / aniversary.... via the calender is very inconvenient. 

1. click on calender
2. multiple clicks to choose year
3. multiple clicks to choose month and day
4. confirmation with ok

I would prefer to insert the date via keyboard, just enter 1.3.1976 and press enter

![grafik](https://user-images.githubusercontent.com/4030579/111043719-509c5f80-8444-11eb-800b-ae052b0b59e3.png)

contacts 3.4.3 on nexthub 20.0.8

**Comment by skjnldsv** [comment]
See https://github.com/nextcloud/contacts/issues/1865
