### ISSUE TITLE
Multiple (postal) addresses not possible

### ISSUE THREAD

**Issue by dermig** [nextcloud/contacts#2117]
### Describe the bug
When creating a new contact within the contacts app and a (second) (postal) address is added, this second address seems to be a duplicate from the first one: No matter which of the two address are edited, the other one changes as well. Thus, one is unable to add a second (or third, fourth, ...) distinct address to a contact - all addresses seem to be a hard copy of the first one entered. However, after switching to another contact and back again, editing the other addresses works as expected. This is a possible workaround.

**To Reproduce**
1. Go to 'contacts' app
2. Click on 'new contact'
3. Enter values for the (postal) address
4. Add second address via the 'add new property' button and edit this one - the first address will change accordingly

**Expected behavior**
It should be possible to enter multiple distinct addresses for a newly created contact without switching to another contact beforehand.

**Actual behavior**
See description

**Screenshots**
See screen recording. Note: 'aaaa 2' is the contact which is newly created. 'aaaaa 1' is the contact I switch to (and back again to 'aaaa 2' to be able to add a second distinct address.
![Peek 2021-03-14 19-56](https://user-images.githubusercontent.com/12894726/111080677-dfba7d80-84ff-11eb-898e-f44f804c528f.gif)

### Server configuration
**Operating system**: Ubuntu 20.04

**Web server:** Nginx

**Database:** MariaDB

**PHP version:** 7.4.3

**Nextcloud version:** 20.0.8

**Contacts version:**  3.4.3

**Updated from an older Nextcloud or fresh install:** Updated

**Signing status:**
```
No errors have been found.
```

**List of activated apps:**
```
Enabled:
  - accessibility: 1.6.0
  - activity: 2.13.4
  - calendar: 2.1.3
  - cloud_federation_api: 1.3.0
  - comments: 1.10.0
  - contacts: 3.4.3
  - contactsinteraction: 1.1.0
  - dav: 1.16.2
  - documentserver_community: 0.1.9
  - federatedfilesharing: 1.10.2
  - federation: 1.10.1
  - files: 1.15.0
  - files_markdown: 2.3.3
  - files_pdfviewer: 2.0.1
  - files_rightclick: 0.17.0
  - files_sharing: 1.12.2
  - files_texteditor: 2.14.0
  - files_trashbin: 1.10.1
  - files_versions: 1.13.0
  - files_videoplayer: 1.9.0
  - firstrunwizard: 2.9.0
  - forms: 2.2.1
  - groupfolders: 8.2.0
  - logreader: 2.5.0
  - lookup_server_connector: 1.8.0
  - mail: 1.9.3
  - nextcloud_announcements: 1.9.0
  - notes: 4.0.4
  - notifications: 2.8.0
  - oauth2: 1.8.0
  - onlyoffice: 6.3.0
  - password_policy: 1.10.1
  - photos: 1.2.3
  - privacy: 1.4.0
  - provisioning_api: 1.10.0
  - serverinfo: 1.10.0
  - settings: 1.2.0
  - sharebymail: 1.10.0
  - support: 1.3.0
  - survey_client: 1.8.0
  - systemtags: 1.10.0
  - tasks: 0.13.6
  - text: 3.1.0
  - theming: 1.11.0
  - twofactor_backupcodes: 1.9.0
  - updatenotification: 1.10.0
  - user_status: 1.0.1
  - viewer: 1.4.0
  - weather_status: 1.0.0
  - workflowengine: 2.2.0
```

**Nextcloud configuration:**
```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "share_folder": "\/Mit mir geteilt",
        "dbtype": "mysql",
        "version": "20.0.8.1",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "overwriteprotocol": "https",
        "overwritehost": "***REMOVED SENSITIVE VALUE***",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "logtimezone": "Europe\/Berlin",
        "skeletondirectory": "",
        "maintenance": false,
        "mysql.utf8mb4": true,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "loglevel": 0,
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***"
    }
}
```

**Comment by j-ed** [comment]
It is only possible to use one type of an address at a time, so if you add a "**Private**" address you need to change the address label to "**Work**" or "**Other**" to make sure that they can be correctly stored or synchronized. You can change the address label by clicking on i and selecting a different one.

**Comment by skjnldsv** [comment]
Hum, that is an issue. I thought that was fixed already. Will investigate. Thanks for the report! :wink:

**Comment by dermig** [comment]
> It is only possible to use one type of an address at a time, so if you add a "**Private**" address you need to change the address label to "**Work**" or "**Other**" to make sure that they can be correctly stored or synchronized. You can change the address label by clicking on it and selecting a different one.

Just tried this (with Firefox and Chromium to rule out Browser dependencies) - doesn't help here. In fact, after switching to another contact and back again, I can specify multiple distinct "**Private**" addresses and all are correctly synced with my Android phone (using DAVx5) as well.

**Comment by hamza221** [comment]
I can't reproduce anymore
