### ISSUE TITLE
Error after updating contacts to 3.5.0

### ISSUE THREAD

**Issue by pavaroo** [nextcloud/contacts#2118]
I have updated the app contacts to the latest version 3.5.0.
Now when I open the app I get the error:
Internal server error.

The server could not complete the request.
If this happens again, please send the following technical details to your server administrator.
More details can be found in the server log.
Technical details

    Remote address: xx.xxx.xxx.xxx
    Request ID: YE84G3xMcDiINip1ZE@evQAAJxs

My Nextcloud version is 18.0.6

**Comment by j-ed** [comment]
> My Nextcloud version is 18.0.6

Nextcloud 18 has already been declared "**End-of-Life" and therefore you won't get any support on this version anymore.
Please follow [the thread](https://help.nextcloud.com/t/fehler-nach-update-der-app-kontakte/110958) in the help forum which you've opened in parallel and update your installation to a supported version asap.
