### ISSUE TITLE
Unable to import from *.abbu file (MacOS)

### ISSUE THREAD

**Issue by binarykitchen** [nextcloud/contacts#2119]
Using your latest version here. Exported all my contacts on MacOS into one single file called "Contacts – 16-03-2021.abbu"

Then imported that into this contacts app via Contacts > Settings > Import Contacts > Select local files.

Then a dialogue comes up saying "Done importing 0 contacts" huh? But there are 157 contacts.

Probably that file format isn't supported?

**Comment by skjnldsv** [comment]
Hi, we don't support abbu files.
Only vcf. See https://github.com/nextcloud/contacts/issues/20

**Comment by skjnldsv** [comment]
I'm actually surprised you were able to select this file as we filter them and ask for vcf only :)

**Comment by binarykitchen** [comment]
@skjnldsv EXACTLY mate. That's a bug itself and the message "Done importing 0 contacts" huh?

**Comment by skjnldsv** [comment]
I guess that would be https://github.com/nextcloud/contacts/issues/990 then :)

**Comment by skjnldsv** [comment]
Or https://github.com/nextcloud/contacts/issues/1653 actually
