### ISSUE TITLE
Contacts 3.5.0 Broken on Nextcloud 18

### ISSUE THREAD

**Issue by gandihar** [nextcloud/contacts#2121]
### Describe the bug
Contacts 3.5.0 is broken on Nextcloud 18.

I used the Apps panel in Nextcloud and it said Contacts 3.5.0 was an upgrade. I was previously running 3.4.3. After the app update had installed, I tried to get into Contacts. It threw an "Internal Server Error". Looking in the logs, I see this:

[index] Error: OCP\AppFramework\QueryException: Could not resolve socialApiService! Class socialApiService does not exist at <<closure>>

 0. /usr/share/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php line 115
    OC\AppFramework\Utility\SimpleContainer->resolve("socialApiService")
 1. /usr/share/nextcloud/lib/private/ServerContainer.php line 150
    OC\AppFramework\Utility\SimpleContainer->query("socialApiService", true)
 2. /usr/share/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php line 389
    OC\ServerContainer->query("socialApiService", true)
 3. /usr/share/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php line 77
    OC\AppFramework\DependencyInjection\DIContainer->query("socialApiService")
 4. /usr/share/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php line 100
    OC\AppFramework\Utility\SimpleContainer->buildClass(ReflectionClass  ... "})
 5. /usr/share/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php line 115
    OC\AppFramework\Utility\SimpleContainer->resolve("OCA\\Contacts\\ ... r")
 6. /usr/share/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php line 415
    OC\AppFramework\Utility\SimpleContainer->query("OCA\\Contacts\\ ... r")
 7. /usr/share/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php line 386
    OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback("OCA\\Contacts\\ ... r")
 8. /usr/share/nextcloud/lib/private/AppFramework/App.php line 112
    OC\AppFramework\DependencyInjection\DIContainer->query("OCA\\Contacts\\ ... r")
 9. /usr/share/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
    OC\AppFramework\App::main("OCA\\Contacts\\ ... r", "index", OC\AppFramework\ ... {}, {_route: "contacts.page.index"})
10. <<closure>>
    OC\AppFramework\Routing\RouteActionHandler->__invoke({_route: "contacts.page.index"})
11. /usr/share/nextcloud/lib/private/Route/Router.php line 299
    call_user_func(OC\AppFramework\ ... {}, {_route: "contacts.page.index"})
12. /usr/share/nextcloud/lib/base.php line 1011
    OC\Route\Router->match("/apps/contacts/")
13. /usr/share/nextcloud/index.php line 38
    OC::handleRequest()

GET /nextcloud/apps/contacts/
from (internal) by (topuser) at 2021-03-16T20:21:33-06:00

I find Class socialApiService in contacts/lib/Service/SocialApiService.php but Nextcloud won't. I've also scoured the search engines, and Github, and even this project's bug reports looking for a fix or anyone else having a similar issue.

**To Reproduce**
1. Have a working Nextcloud 18 instance (I know it's EOL, I'm working on upgrading) with working Contacts < 3.5.0.
2. Use the Apps admin interface to upgrade to Contacts 3.5.0.
3. Try to use Contacts.
4. Internal Server Error
5. See server logs

**Expected behavior**
Working Contacts.

**Actual behavior**
Broken Contacts, "Internal Server Error", see logs.

### Server configuration
**Operating system**: Linux (CentOS 7)

**Web server:** Apache 2.4

**Database:** MariaDB 10

**PHP version:** 7.3

**Nextcloud version:** 18.0.14

**Contacts version:** 3.5.0

**Updated from an older Nextcloud or fresh install:**
Upgraded and working previously.

**Signing status:**
No errors have been found.

**List of activated apps:**
Enabled:
  - accessibility: 1.4.0
  - activity: 2.11.1
  - apporder: 0.12.0
  - calendar: 2.0.5
  - cloud_federation_api: 1.1.0
  - comments: 1.8.0
  - contacts: 3.5.0
  - dav: 1.14.0
  - deck: 1.2.5
  - federatedfilesharing: 1.8.0
  - federation: 1.8.0
  - files: 1.13.1
  - files_external: 1.9.0
  - files_pdfviewer: 1.7.0
  - files_rightclick: 0.15.2
  - files_sharing: 1.10.1
  - files_trashbin: 1.8.0
  - files_versions: 1.11.0
  - files_videoplayer: 1.7.0
  - firstrunwizard: 2.7.0
  - logreader: 2.3.0
  - lookup_server_connector: 1.6.0
  - nextcloud_announcements: 1.7.0
  - notes: 3.6.4
  - notifications: 2.6.0
  - oauth2: 1.6.0
  - password_policy: 1.8.0
  - photos: 1.0.0
  - privacy: 1.2.0
  - provisioning_api: 1.8.0
  - recommendations: 0.6.0
  - serverinfo: 1.8.0
  - settings: 1.0.0
  - sharebymail: 1.8.0
  - spreed: 8.0.15
  - survey_client: 1.6.0
  - systemtags: 1.8.0
  - tasks: 0.13.6
  - text: 2.0.0
  - twofactor_backupcodes: 1.7.0
  - viewer: 1.2.0
  - workflowengine: 2.0.0
Disabled:
  - admin_audit
  - encryption
  - support
  - theming
  - updatenotification
  - user_ldap

**Nextcloud configuration:**
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "www.kobran.org",
            "kobran.org"
        ],
        "apps_paths": [
            {
                "path": "\/usr\/share\/nextcloud\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/usr\/share\/nextcloud\/apps-local",
                "url": "\/apps-local",
                "writable": true
            }
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "http:\/\/www.kobran.org\/nextcloud",
        "maintenance": false,
        "dbtype": "mysql",
        "version": "18.0.14.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "theme": "",
        "forcessl": true,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_sendmailmode": "smtp",
        "check_for_working_htaccess": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\APCu",
        "logtimezone": "MST7MDT",
        "updatechecker": false,
        "appcodechecker": true,
        "appstoreenabled": true,
        "htaccess.RewriteBase": "\/nextcloud",
        "loglevel": 2,
        "mysql.utf8mb4": true
    }
}

### Client configuration
**Browser:** Any

**Operating system:** Any

**CardDAV-clients:** ANY

#### *Web server error log*
Not useful.

#### *data/nextcloud.log*
{"reqId":"YFFnrSr5c@GTImX4yw1emgAAAA8","level":3,"time":"2021-03-16T20:21:33-06:00","remoteAddr":"(**REDACTED**)","user":"(**REDACTED**)","app":"index","method":"GET","url":"/nextcloud/apps/contacts/","message":{"Exception":"OCP\\AppFramework\\QueryException","Message":"Could not resolve socialApiService! Class socialApiService does not exist","Code":0,"Trace":[{"file":"/usr/share/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":115,"function":"resolve","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["socialApiService"]},{"file":"/usr/share/nextcloud/lib/private/ServerContainer.php","line":150,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["socialApiService",true]},{"file":"/usr/share/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":389,"function":"query","class":"OC\\ServerContainer","type":"->","args":["socialApiService",true]},{"file":"/usr/share/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":77,"function":"query","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->","args":["socialApiService"]},{"file":"/usr/share/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":100,"function":"buildClass","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":[{"name":"OCA\\Contacts\\Controller\\PageController","__class__":"ReflectionClass"}]},{"file":"/usr/share/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":115,"function":"resolve","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OCA\\Contacts\\Controller\\PageController"]},{"file":"/usr/share/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":415,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OCA\\Contacts\\Controller\\PageController"]},{"file":"/usr/share/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":386,"function":"queryNoFallback","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->","args":["OCA\\Contacts\\Controller\\PageController"]},{"file":"/usr/share/nextcloud/lib/private/AppFramework/App.php","line":112,"function":"query","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->","args":["OCA\\Contacts\\Controller\\PageController"]},{"file":"/usr/share/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Contacts\\Controller\\PageController","index",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"contacts.page.index"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"_route":"contacts.page.index"}]},{"file":"/usr/share/nextcloud/lib/private/Route/Router.php","line":299,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"_route":"contacts.page.index"}]},{"file":"/usr/share/nextcloud/lib/base.php","line":1011,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/contacts/"]},{"file":"/usr/share/nextcloud/index.php","line":38,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/usr/share/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","Line":106,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:85.0) Gecko/20100101 Firefox/85.0","version":"18.0.14.1","id":"60516bcabf10d"}

#### Browser log
This is not a browser problem.

**Comment by skjnldsv** [comment]
please upgrade to 19. 18 is EOL
Let me release a new fixed version
