### ISSUE TITLE
	Exception: App with id contacts has invalid signature

### ISSUE THREAD

**Issue by JB1985** [nextcloud/contacts#2122]
I cannot Update Contacts.

installed version: 3.4.3
Available version: 3.4.5
Nextcloud: 20.0.8

Error when I try to update the App:

Es ist ein Fehler bei der Anfrage aufgetreten. Es kann nicht fortgefahren werden.
Die App konnte nicht aktualisiert werden.

`[core] Error: Exception: App with id contacts has invalid signature at <<closure>>

0. /var/customers/webs/web144/nextcloud/lib/private/Installer.php line 198
   OC\Installer->downloadApp("*** sensitive parameter replaced ***", false)
1. /var/customers/webs/web144/nextcloud/apps/settings/lib/Controller/AppSettingsController.php line 532
   OC\Installer->updateAppstoreApp("*** sensitive parameters replaced ***")
2. /var/customers/webs/web144/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 169
   OCA\Settings\Controller\AppSettingsController->updateApp("*** sensitive parameters replaced ***")
3. /var/customers/webs/web144/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 100
   OC\AppFramework\Http\Dispatcher->executeController(OCA\Settings\Con ... {}, "updateApp")
4. /var/customers/webs/web144/nextcloud/lib/private/AppFramework/App.php line 152
   OC\AppFramework\Http\Dispatcher->dispatch(OCA\Settings\Con ... {}, "updateApp")
5. /var/customers/webs/web144/nextcloud/lib/private/Route/Router.php line 309
   OC\AppFramework\App::main("OCA\\Settings\\ ... r", "updateApp", OC\AppFramework\ ... {}, {appId: "*** sen ... "})
6. /var/customers/webs/web144/nextcloud/lib/base.php line 1008
   OC\Route\Router->match("/settings/apps/update/contacts")
7. /var/customers/webs/web144/nextcloud/index.php line 37
   OC::handleRequest()

GET /settings/apps/update/contacts
from XXXXX at 2021-03-17T14:56:24+00:00`

**Comment by skjnldsv** [comment]
Yeah, sorry about that, for some reason the appstore didn't understand the new release. Retry in like 30 minutes please :)

**Comment by hul51u** [comment]
I cannot update from 3.4.3 to 3.5.0. got the same error in my log file.

**Comment by JB1985** [comment]
Thanks!

v3.5.1 works again!
