### ISSUE TITLE
Can't install Contacts app: Client error: `GET https://github.com/nextcloud/contacts/releases/download/v3.5.0/contacts.tar.gz` resulted in a `404 Not Found` response: Not Found 

### ISSUE THREAD

**Issue by patrickbolle** [nextcloud/contacts#2123]
On a fresh Nextcloud 21 install today, trying to download Contacts app from Nextcloud App store results in this error message:
Client error: `GET https://github.com/nextcloud/contacts/releases/download/v3.5.0/contacts.tar.gz` resulted in a `404 Not Found` response: Not Found 

### Steps to reproduce
1. Try to install app from app store
2. See error message

### Server configuration
**Nextcloud version:** 
21.0.0

**Contacts version:** 
3.5.0

**Updated from an older Nextcloud or fresh install:**
Fresh install

**Comment by skjnldsv** [comment]
Yes, release has been rejected, please use 3.5.1
