### ISSUE TITLE
Integration with Collabora Office: Letter template completion

### ISSUE THREAD

**Issue by eglipeter** [nextcloud/contacts#2141]
We are always frustrated when we have to write "paper letters" to a customer. Addressing them is error-prone because the address must be copied manually to the document. Therefore, I propose an integration of the contacts app with the Collabora Online Office. It would be great if one could click in the Contact app a button that opens a predefined letter template in Collabora office and fills in values based on fields in the contacts view. By supporting arbitrary cardDAV fields, this would also allow e.g. to fill in customer numbers for invoice templates and so on.

**Comment by eglipeter** [comment]
Cross-Reference to Collabora:
https://github.com/nextcloud/richdocuments/issues/1458

**Comment by hamza221** [comment]
I think if feasible this feature should be implemented in https://github.com/nextcloud/richdocuments 

--
not transferring the issuehttps://github.com/nextcloud/richdocuments/issues/1458 already exits
