### ISSUE TITLE
Contact Pictures don´t show up

### ISSUE THREAD

**Issue by WeT-Klb** [nextcloud/contacts#215]
https://cloud.githubusercontent.com/assets/20600342/26034748/b7343682-38c1-11e7-9f81-053df7608e7e.jpg

https://cloud.githubusercontent.com/assets/20600342/26034758/d05e4e86-38c1-11e7-9043-f5f8cd3c1a30.jpg

https://cloud.githubusercontent.com/assets/20600342/26034760/d9ab3d6e-38c1-11e7-8e89-d7f2472030de.jpg

https://cloud.githubusercontent.com/assets/20600342/26034765/e0dc182e-38c1-11e7-9876-57515b2ccd8d.jpg

### Actual behaviour
When i add a new contact in Nextcloud 11 contacts app and try to attach a picture it won´t show up.
 I am told the Picture is too big if it it more than 1MB - but when i use a smaller one 240x240 less than 1MB it won´t appear.
 Weired Thing is the same Picture in contacts app on Owncloud 8.2.11 works perfektly.

### Server configuration
**Operating system**: Linux Qnap-TS251 4.2.8 #1 SMP Wed May 3 01:11:54 CST 2017 x86_64

**Web server:** Apache (fpm-fcgi)

**Database:** mysql 5.5.51

**PHP version:** 5.6.30
Modules loaded: Core, date, ereg, libxml, pcre, ctype, dom, fileinfo, filter, hash, json, SPL, openssl, posix, Reflection, SimpleXML, session, tokenizer, xml, xmlreader, xmlwriter, cgi-fcgi, imagick, zlib, curl, calendar, iconv, gd, standard, PDO, sqlite3, mysqlnd, pdo_mysql, pdo_sqlite, mysql, mysqli, Phar, zip, bcmath, dba, mbstring, ftp, gettext, imap, ldap, exif, mcrypt, pcntl, shmop, soap, sockets, wddx, xmlrpc, xsl, Zend OPcache

**Nextcloud version:** 11.0.3 (stable) - 11.0.3.2

**Updated from an older Nextcloud/ownCloud or fresh install: Fresh install**

**Where did you install Nextcloud from:  Qnap-Forum http://www.qoolbox.fr/NextCloud_11.0.3.qpkg.zip** 

**Signing status:**
<details>
	<summary>Signing status</summary>

```
[]
```

</details>

**List of activated apps:**
<details>
	<summary>App list</summary>
```

Enabled:
 - activity: 2.4.1
 - calendar: 1.5.2
 - comments: 1.1.0
 - contacts: 1.5.3
 - dav: 1.1.1
 - federatedfilesharing: 1.1.1
 - federation: 1.1.1
 - files: 1.6.1
 - files_pdfviewer: 1.0.1
 - files_sharing: 1.1.1
 - files_texteditor: 2.2
 - files_trashbin: 1.1.0
 - files_versions: 1.4.0
 - files_videoplayer: 1.0.0
 - firstrunwizard: 2.0
 - gallery: 16.0.0
 - issuetemplate: 0.2.1
 - logreader: 2.0.0
 - lookup_server_connector: 1.0.0
 - nextcloud_announcements: 1.0
 - notifications: 1.0.1
 - password_policy: 1.1.0
 - provisioning_api: 1.1.0
 - serverinfo: 1.1.1
 - sharebymail: 1.0.1
 - survey_client: 0.1.5
 - systemtags: 1.1.3
 - theming: 1.1.1
 - twofactor_backupcodes: 1.0.0
 - updatenotification: 1.1.1
 - weather: 1.4.1
 - workflowengine: 1.1.1

Disabled:
 - admin_audit
 - encryption
 - external
 - files_accesscontrol
 - files_automatedtagging
 - files_external
 - files_retention
 - templateeditor
 - user_external
 - user_ldap
 - user_saml
```
</details>

**The content of config/config.php:**
<details>
	<summary>Config report</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "***REMOVED SENSITIVE VALUE***",
        "***REMOVED SENSITIVE VALUE***"
    ],
    "datadirectory": "\/share\/CACHEDEV1_DATA\/.qpkg\/NextCloud\/nextcloud\/data",
    "overwrite.cli.url": "http:\/\/***REMOVED SENSITIVE VALUE***\/nextcloud",
    "dbtype": "mysql",
    "version": "11.0.3.2",
    "dbname": "Nextcloud",
    "dbhost": "localhost",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "logtimezone": "UTC",
    "installed": true,
    "maintenance": false,
    "updater.release.channel": "stable",
    "mail_smtpmode": "php",
    "mail_smtpauth": 1,
    "mail_smtpsecure": "ssl",
    "mail_smtpauthtype": "LOGIN",
    "mail_smtphost": "securesmtp@t-online.de",
    "mail_smtpport": "567"
}
```
</details>

**Are you using external storage, if yes which one:** files_external is disabled

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Client configuration
**Browser:** Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko

**Operating system:** Windows 7 Ultimate 64bit

#### Web server error log
<details>
	<summary>Web server error log</summary>
	```
	Insert your webserver log here
	```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
	<summary>Nextcloud log</summary>
	```
	Insert your Nextcloud log here
	```
</details>

#### Browser log
<details>
	<summary>Browser log</summary>
	```
	Insert your browser log here, this could for example include:

	a) The javascript console log
	b) The network log
	c) ...
	```
</details>

**Comment by WeT-Klb** [comment]
I found out one more Thing:
If i use Google Chrome to upload contact Pictures i can see them in Google Chrome.
But i neither can upload nor see contact Pictures in IE11.
Even i upload Pictures in Google Chrome and watch the contacts within IE11 the round field dissappeared but still no contact Picture Show up.
So somehow it´s related to IE11! ´Can somebody proof this?

WeT-Klb

**Comment by irgendwie** [comment]
We only test the contacts app against chrom{e|ium} and firefox - for both browser this feature should be working. Internet Explorer also isn't in my personal scope since most users use the two mentioned 3rd party browser (even on windows). PRs are very welcomed if one is willing to write workarounds for IE.

**Comment by bpcurse** [comment]
I have a similar issue with CardBook App for Thunderbird and Nextcloud Contacts app, when the contacts are uploaded to Nextcloud.
Some Contact Pictures are shown, some are not shown in Nextcloud and the picture upload placeholder / button is missing (in Firefox).
What I could find out is that the contact entries that are displayed fine use VCARD 3.0 and the ones not working are in the VCARD 4.0 format.
My workaround is to delete the picture in cardbook and sync. After that the picture upload button in nextcloud becomes available again and I can upload it there. The "downsync" to cardbook then works and the contact seems to be downgraded this way to VCARD 3.0.

Is this related / or of any help for the above issue?

**Comment by skjnldsv** [comment]
I think we dropped IE support. Only Edge is supported now! :)
