### ISSUE TITLE
How-to use the Social network, Instant messaging Field?

### ISSUE THREAD

**Issue by Mannshoch** [nextcloud/contacts#216]
How should I use this Fields?
Do I enter:
www.facebook.com/{NAME}
{NAME}
http://www.facebook.com/{NAME}
https://www.facebook.com/{NAME}

and what do I enter in Instant messaging Fields for Skype, XMPP, irc ? 

Please add a Tool-tip to show examples.

**Comment by jancborchardt** [comment]
Good point @Mannshoch. :) This is a good starter issue.

Ideally there should be clear choices for the »social network« field for Facebook, Twitter, etc. cc @nextcloud/contacts 

Skype and XMPP need placeholders for their inputs saying »Username«. cc @jonatoni @xh3n1

**Comment by jancborchardt** [comment]
Good point @Mannshoch. :) This is a good starter issue.

Skype and Facebook etc need placeholders for their inputs saying »Username« or »https://facebook.com/username«. cc @jonatoni @xh3n1 

What is the correct format @nextcloud/contacts?

**Comment by jancborchardt** [comment]
Fixed through https://github.com/nextcloud/contacts/pull/254 :)
