### ISSUE TITLE
Recommended setup on iPhone + MacBook [documentation]

### ISSUE THREAD

**Issue by binarykitchen** [nextcloud/contacts#2179]
Hello guys

Awesome app, thanks for your hard work.

This issue I'm raising is just asking for a little more documentation on the recommended setup on my iPhone and MacBook. Because I'm seeing too many duplicate contacts, some never get updated across all devices and on my Nexcloud + iCloud instances both.

Not sure if I should disable Contacts on iCloud but I'd like to have them synced there too. Tried many configs and settings but the mess becomes bigger. Maybe I'm doing something wrong?

A little pointer, a little documentation on this would be great. Thanks!

**Comment by skjnldsv** [comment]
Hey!

We have this https://docs.nextcloud.com/server/21/user_manual/en/pim/sync_ios.html
But I guess you're more searching for advices than synchro setup tutorial.
This tracker is more for issues and features, what you're asking should go into the forum :)

https://help.nextcloud.com
