### ISSUE TITLE
Can't select address books in "Clone contact" dialogue

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/contacts#2188]
### Describe the bug

I see an empty input, but not a selectable multiselect when I try to clone a contact from one address book to another.

**To Reproduce**
1. Create two address books A and B
2. Add a contact to A
3. Click "Clone contact"

**Expected behavior**

See a list where address book B is selectable (or also A if we allow copies into the same AB).

**Actual behavior**

![Bildschirmfoto vom 2021-05-03 19-19-16](https://user-images.githubusercontent.com/1374172/116909691-dcf92080-ac44-11eb-8ef2-27d246e4a9a0.png)

### Server configuration

*The* Nextcloud

**Comment by cbitsco** [comment]
Hey, Where are you finding "Clone" feature, we don't seem to have this as an option, and I would love to have a working clone within an address book. I frequently want to add contacts to an existing business contact, so to clone one and just change user details leaving the same address, main phone, website, groups etc would be ideal

Currently I export a vcf and then re-import it only woks 40% of the time usually falls over with an done importing and below a cryptic "1error" (not very helpful)

**Comment by jpmv27** [comment]
Nextcloud Contacts 5.5.3
Nextcloud 27.1.8

Still seeing this issue three years later. Makes it impossible to use the Clone function, as the list of address books is empty. (I am assuming here that it should be possible to clone into the same address book as the source, perhaps this is a misunderstanding on my part.)

I don't see any errors in the Nextcloud log.

**Comment by Miladiir** [comment]
+1 Clone Contact functionality simply not working at all. If I use this function it clones the same contact with the same uid into the same address book, which of course fails.

**Comment by hamza221** [comment]
Can't reproduce on main
