### ISSUE TITLE
Contacts not working with NC12

### ISSUE THREAD

**Issue by Dennis1993** [nextcloud/contacts#219]
### Steps to reproduce
1. Install fresh NextCloud 12 instance
2. activate the contacts app
3. now you see a Spinning Wheel
4. add a contact shows errors

### Expected behaviour
Spinning wheel and app completly not working

### Actual behaviour
No spinning wheel and usable app

### Server configuration
**Operating system**:
Ubuntu 17.04

**Web server:**
Apache 2.4

**Database:**
MySQL 5.7

**PHP version:**
PHP 7.1

**Nextcloud version:** (see Nextcloud admin page)
12.0.0

**Contacts version:** (see Nextcloud apps page)
1.5.3

**Updated from an older Nextcloud or fresh install:**
fresh installation

**List of activated apps:**
Default apps with Calendar (1.5.3) and contacts (1.5.3)

### Client configuration
**Browser:**
Firefox 53.0.3

**Operating system:**
Windows 10

Opening the app shows that:
![image](https://cloud.githubusercontent.com/assets/1473674/26323297/93f4aabc-3f2e-11e7-906b-c236cc8a3841.png)

If I click on "Neuer Kontakt" this error appear:
![image](https://cloud.githubusercontent.com/assets/1473674/26323291/89651bfe-3f2e-11e7-9645-c9f5496495e4.png)

**Comment by kiwiufa** [comment]
I'm experiencing very similar issue with nextcloud 12.0. It seems to work for a user admin, but not for any other user (not even for users with admin privileges). 
After a click on "+ New contact" I receive the following error:
TypeError: Cannot read property 'displayName' of undefined
    at new Contact (contact_model.js:12)
    at Object.create (contact_service.js:86)
    at Object.ctrl.createContact (newContactButton_controller.js:10)
    at fn (eval at compile (angular.js?v=0ccff16…-0:14817), <anonymous>:4:269)
    at expensiveCheckFn (angular.js?v=0ccff16…-0:15906)
    at callback (angular.js?v=0ccff16…-0:25885)
    at Scope.$eval (angular.js?v=0ccff16…-0:17682)
    at Scope.$apply (angular.js?v=0ccff16…-0:17782)
    at HTMLButtonElement.<anonymous> (angular.js?v=0ccff16…-0:25890)
    at HTMLButtonElement.dispatch (core.js?v=0ccff16…-0:3)

**Comment by lolihunter** [comment]
This is simple to fix.

There is no default address book created in nextcloud 12. simple use the settings below and enter a new name for a address book, example "Personal", then hit enter.

After creating one you can import contacts or create them.

**Comment by kiwiufa** [comment]
Thank you. The above has fixed the issue for me

**Comment by irgendwie** [comment]
In the upcoming version of contacts, an address-book is automatically created in case none is existing. Normally Nextcloud/server also automatically creates one, once a new user is created.

**Comment by hognoodle** [comment]
Thanks lolihunter, that was all I needed.
