### ISSUE TITLE
Default address book missing on developer installation

### ISSUE THREAD

**Issue by PatrycjaPuczko** [nextcloud/contacts#22]
I set up the contacts up from Git and there was no address book created.

**Comment by irgendwie** [comment]
The creation of a default addressbook is a postLogin hook, issued by the dav backend in [nextcloud/server](https://github.com/nextcloud/server): https://github.com/nextcloud/server/blob/master/apps/dav/lib/HookManager.php#L133-L141

It seems to be called every time, after a user logged in and creates an addressbook if the user doesn't already have one - nothing we can fix in the contacts app.
Would you mind [creating an issue in nextcloud/server](https://github.com/nextcloud/server/issues/new)?
