### ISSUE TITLE
Contact app importing a VCF ignores anniversary field

### ISSUE THREAD

**Issue by gjpc** [nextcloud/contacts#2209]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

PLEASE NOTE: The template app is marked not compatible so I did not install it or use it 

### Steps to reproduce
1. Create a new contact add anniversary date
2. Export the contact to a vcf
3. Delete the contact
4. Import the contact vcf

### Expected behaviour
Tell us what should happen
The anniversary date should be in the imported contact

### Actual behaviour
Tell us what happens instead
The anniversary date is not imported into the contact even though it is in the vcf

### Server configuration

**Operating system:**
Ubuntu 20.04 Linux 5.4.0-1048-aws x86_64
**Web server:**
Apache 2.2.46
**Database:**
MySQL 8.0 25

**PHP version:**
Version: 7.4.16

**Nextcloud version:** (see Nextcloud admin page)
21.0.1
**Updated from an older Nextcloud/ownCloud or fresh install:**
yes
**Where did you install Nextcloud from:**
AWS 
**Signing status:**
Let's Encrypt
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
Not applicable
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by stefan-niedermann** [comment]
I just tried it by exporting a contact with an anniversary as `.vcf` and importing it into a completely other nextcloud instance - the anniversary date has successfully been transferred → Not reproducible by me.

Maybe you can post the `.vcf` file here (after anonymize names, addresses, numbers etc!), or at least the part of the anniversary, as you stated that it is included in the `.vcf`? You can open the file using any text editor.

**Comment by gjpc** [comment]
Hi Stefan,

Here it is:

`
BEGIN:VCARD
VERSION:3.0
PRODID:-//Sabre//Sabre VObject 4.3.3//EN
UID:82d4b5d0-cb3f-4aca-90b4-ac7e6bb214a3
FN:Diane XXXXXXX
ADR;TYPE=HOME:;XXXXXXXX
EMAIL;TYPE=HOME:dXXXXXXXXXX
TEL;TYPE="HOME,VOICE":XXXXXXXXXX
BDAY;VALUE=DATE:19560520
ITEM1.X-ABDATE;VALUE=DATE-AND-OR-TIME:19980302
ITEM1.X-ABLABEL:_$!<Anniversary>!$_
X-ANNIVERSARY;VALUE=DATE:19980302
PHOTO;ENCODING=b;TYPE=JPEG:/9j/4AAQSkZJRgABAQEASABIAAD/4RRsRXhpZgAATU0AKgAA
...`

**Comment by stefan-niedermann** [comment]
So i noticed a difference between those two lines:

```
X-ANNIVERSARY;VALUE=DATE-AND-OR-TIME:20150607
```
vs.

```
X-ANNIVERSARY;VALUE=DATE:19980302
```

Could you manually change this line (and add `-AND-OR-TIME`) and check whether the import works correctly then?

**Comment by stefan-niedermann** [comment]
If yes, this raises a few questions:

1. Why is your export different from mine?
2. Why does the import not work with `VALUE=DATE` but only with `VALUE=DATE-AND-OR-TIME`
3. Which client did you use to set the anniversary initially? Did you set it with the calendar app of Nextcloud in your browser? Or did you use for example an Android calendar and synchronized it with DavX5? Something different?

**Comment by gjpc** [comment]
I changed the line and there is no effect, Anniversary is still missing


    Why is your export different from mine?
I have no idea
    Why does the import not work with VALUE=DATE but only with VALUE=DATE-AND-OR-TIME
I have no idea
    Which client did you use to set the anniversary initially? Did you set it with the calendar app of Nextcloud in your browser? Or did you use for example an Android calendar and synchronized it with DavX5? Something different?
I exported from NextCloud and then imported from NextCloud

**Comment by stefan-niedermann** [comment]
The first two questions were not really meant to be answered by you :wink:

> I exported from NextCloud and then imported from NextCloud

No, where did you **set** the **anniversary** date? Where did you type `02-03-1998` (or whatever)? In Nextcloud Calendar within your browser? Or on a synchronized Android device? Where did you enter the value?

**Comment by gjpc** [comment]
OK Stefan,

Looks like I wasted your time, sorry. I just did the export and import again with the anniversary date and it works. 

The original reason why I did the export/import was to have the name at the top of page reflect the entry. When I entered the contact originally, I misspelled the first name.  The form is not the easiest to fill out so exported, corrected the first name in the VCF, deleted the bad contact and did the import.

I have no idea how I screwed that up. 

How do you get the contact header name to change once you made an error inputting the name?

**Comment by stefan-niedermann** [comment]
Uhmmm... :thinking: Could you please 

![grafik](https://user-images.githubusercontent.com/4741199/119135321-89f1dc80-ba3e-11eb-962c-809d7d8c30a8.png)

and select `Anniversary`? It only appeared for me after explicitly adding it again, but the value was still there...

**Comment by stefan-niedermann** [comment]
> How do you get the contact header name to change once you made an error inputting the name?

You can just click there and edit it, even if it does not look like an input field:

![grafik](https://user-images.githubusercontent.com/4741199/119135483-c02f5c00-ba3e-11eb-8cc4-6a72c8125db5.png)

> I just did the export and import again with the anniversary date and it works.

Glad to hear that - feel free to close this issue then if it is solved for you :slightly_smiling_face:

**Comment by gjpc** [comment]
LOL, Magic! I had no idea that was an editable field! Maybe put a box around it in a future release?

Let's close this issue, thanks!
