### ISSUE TITLE
Very long time display of the contact list

### ISSUE THREAD

**Issue by ionl** [nextcloud/contacts#222]
### Steps to reproduce
1. Only click on the contacts app

### Expected behaviour
1. Quick request :-)

### Actual behaviour
1. I tested a lot of time and it takes about 17s to 19s to show contacts list. I have about 500 contacts. I set APCu data cache. I have only 1 picture.

### Server configuration
* Contacts app version: 1.5.3
* Nextcloud version: 11.0.3
* PHP version: 5.6
* Database and version: MariaDB 10.0.30 
* Server Distribution and version: debian 8 kernel 3.14

### Client configuration
* Browser and version: Firefox 53.0 and fresh chromium install 58.0
* Distribution and version: ubuntu 17.04 kernel 4.10
* Bandwidth 2MB/s

**Comment by mind22** [comment]
I wanted to ask the same. And i think its the pictures loading that long (in my case). I watched my network traffic and it is loading many MB and takes much too long to show up the needed information.

Would it be possible to first catch only the cards without pictures and bring it up? After this loading the pics as thumbnails would speed up.

**Comment by EddyLB** [comment]
I confirm that the time required to display the contacts is related with the download of pictures. With a network connection limited to about 256 kB/s, it took 8s without pictures and 1'30s with pictures for the same 392 cards.
It would indeed be better to download the pictures after having downloaded the cards.

**Comment by jancborchardt** [comment]
Performance issue, tagging as high – @nextcloud/contacts

**Comment by jancborchardt** [comment]
Performance issue, tagging as high – @nextcloud/contacts @nextcloud/javascript

**Comment by bavay** [comment]
Is it only related to the pictures? I have the same performance issue on mine (nextcloud 12, php7) and after enabling performance recording in Firefox, I saw that the two most time consuming calls are https://mountain.suny.ch/remote.php/dav/addressbooks/users/XXX/contacts/ (REPORT, it is 1.4M big) and the same as (PROPFIND). Then the downloading of angular.js?v=4a87eb2f1684b77467c938531f75b836-19 and core.js?v=4a87eb2f1684b77467c938531f75b836-19 also takes some time (these are big). 

I have between 150 and 200 contacts, around half with pictures (most of the pictures must be relatively low-res). 

Mathias
PS: by the way, it also reports that "Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src 'nonce-c1BjUm9RMlFlM0hEL1J3a2plbm5Vejk1UG4wUk1BUnB5RGZOM2tJZ0VETT06L281bjcwTGNTUnFIbkU5WHVwMkpDV2txZWhSd0JVMGduM1dFbENVVVVsOD0=' 'unsafe-eval'”). Source: ondrop attribute on INPUT element."

**Comment by ionl** [comment]
I have only 1 picture on about 500 contacts and it takes about 17s to 19s to show contacts list.
My connection is very poor : 2MB/s

**Comment by skjnldsv** [comment]
The new update 1.5.4 should improve things a lot. 
Would you please update this post after? :)

**Comment by ionl** [comment]
Yes!
Thanks very much! :)

**Comment by EddyLB** [comment]
Will do. Thank you so much!

**Comment by pafcioooo** [comment]
With over 2k contacts first contact shows after 20 seconds, after ca. 30 seconds Firefox gives a warning that "page is making browser slow", the list is finally loaded after 40 seconds.
Search is also working very slow.

It definitely needs optimization:-)

**Comment by skjnldsv** [comment]
@ionl @pafcioooo @EddyLB Please take a look at the latest nightly.
https://nightly.portknox.net/contacts/nextcloud_contacts_nightly_build_2017-09-14.tar.gz

**Comment by pafcioooo** [comment]
@skjnldsv, above mentioned nightly build is a huge improvment! 👍 

Full contacts list is loaded in 13 seconds! :-)
Search is working almost immediately.
Scrolling is also working smoothly.

Only after selecting a contact, its display time is too long, between 7-10 seconds. I am not sure what it depends on.

Thanks a lot anyway:-)

**Comment by skjnldsv** [comment]
@pafcioooo there was a fix for this I think.
Please take a look at the latest nightlies! :)

Glad to hear the loading improved a lot!

**Comment by pafcioooo** [comment]
@skjnldsv, ok I have also tested latest nightly build and display activities work the same as with previous build. 

From time to time after selecting some contact I get "page is making browser slow" in Firefox.

**Comment by skjnldsv** [comment]
@pafcioooo This is strange, I don't have this issue.
Could you open a new one and include some network xhr requests stats (size, time), some info about your uplink speed... etc :) ?

**Comment by skjnldsv** [comment]
fixed by #88 (ref #12)

**Comment by bavay** [comment]
I've just installed nightly_build_2017-09-21 and on my side, the initial loading is still quite slow... around 15s when reloading the page. On the other hand, since my nextcloud is running on a raspberry pi2, it could be that the database (mysql) slows everything down... (when running a tool such as mysqltuner, it complains a lot about the database structure)
