### ISSUE TITLE
Phone numbers ignored when importing vCards

### ISSUE THREAD

**Issue by dkabus** [nextcloud/contacts#224]
First: I really appreciate your work, thank you! ;)

### Steps to reproduce
1. Import vCard-file (version 3.0) with phone number in contacts app

or:

1. Import vCard-file on Android (works, phone number recognized)
2. Push changes via CardDAV to Nextcloud.
3. Pull from CardDAV deletes phone number

### Expected behaviour
The imported contact should be created with the phone numbers that are stored in the vcf.

### Actual behaviour
The imported contact is created but the phone number(s) are ignored (directly import in the app) or deleted (when syncing from android).

### Server configuration

**Operating system**: Raspbian GNU/Linux 8 (jessie)

**Web server:** Apache, version 2.4.10

**Database:** mysql, version 15.1

**PHP version:** 5.6.30-0

**Nextcloud version:** 12.0.0

**Contacts version:** 1.5.3

**Updated from an older Nextcloud or fresh install:** Fresh install on Nextcloud 12

**Signing status:**
No errors have been found.

**List of activated apps:**
  - activity: 2.5.2
  - bruteforcesettings: 1.0.2
  - calendar: 1.5.3
  - comments: 1.2.0
  - contacts: 1.5.3
  - dav: 1.3.0
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0

**Nextcloud configuration:**
```
{
    "system": {
        "instanceid": "oc75znjoa3pg",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "\/mnt\/elements\/Cloud\/data",
        "dbtype": "mysql",
        "version": "12.0.0.29",
        "logtimezone": "UTC",
        "installed": true,
        "maintenance": false,
        "theme": "",
        "loglevel": 0,
        "filesystem_check_changes": 1,
        "dbname": "nextcloud",
        "dbhost": "localhost",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***"
    }
}
```

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** No

### Client configuration
**Browser:** None; Firefox; Edge

**Operating system:** Android; Windows 10; Windows 10

**CardDAV-clients:** DAVdroid; contacts app; contacts app

**Comment by jancborchardt** [comment]
cc @nextcloud/contacts please check it out. :)

**Comment by skjnldsv** [comment]
Can you post an example of a failing vcard please?

**Comment by olleahouse** [comment]
BEGIN:VCARD
VERSION:4.0
FN:Oscar Malmqvist
NAME:Oscar Malmqvist
PHONE.WORK:0704189993
EMAIL:oscar.malmqvist@ahouse.se
LAST:A house
REV:1747922601891
END:VCARD
BEGIN:VCARD
VERSION:4.0
FN:Ronja Axelsson
NAME:Ronja Axelsson
PHONE.WORK:+46702427055
EMAIL:ronja.axelsson@ahouse.se
LAST:A house
REV:1747922601891
END:VCARD
BEGIN:VCARD
VERSION:4.0
FN:Jemima Ceesay
NAME:Jemima Ceesay
PHONE.WORK:+46708310067
EMAIL:jemima.ceesay@ahouse.se
LAST:A house
REV:1747922601891
END:VCARD
BEGIN:VCARD
VERSION:4.0
FN:Wilma Klintberg
NAME:Wilma Klintberg
PHONE.WORK:+46766034482
EMAIL:wilma.klintberg@ahouse.se
LAST:A house
REV:1747922601891
END:VCARD
BEGIN:VCARD
VERSION:4.0
FN:Astrid Sandberg
NAME:Astrid Sandberg
PHONE.WORK:+46738557930
EMAIL:astrid.sandberg@ahouse.se
LAST:A house
REV:1747922601891
END:VCARD
BEGIN:VCARD
VERSION:4.0
FN:Moa Gamlin
NAME:Moa Gamlin
PHONE.WORK:+46733540188
EMAIL:moa.gamlin@ahouse.se
LAST:A house
REV:1747922601891
END:VCARD
BEGIN:VCARD
VERSION:4.0
FN:Sara Johnson
NAME:Sara Johnson
PHONE.WORK:+46707674226
EMAIL:sara.johnson@ahouse.se
LAST:A house
REV:1747922601891
END:VCARD
BEGIN:VCARD
VERSION:4.0
FN:Narissala Asante
NAME:Narissala Asante
PHONE.WORK:+46707674226
EMAIL:narissala.asante@ahouse.se
LAST:A house
REV:1747922601891
END:VCARD
BEGIN:VCARD
VERSION:4.0
FN:Lukas Wannfors
NAME:Lukas Wannfors
PHONE.WORK:+46708514098
EMAIL:lukas.wannfors@ahouse.se
LAST:A house
REV:1747922601891
END:VCARD
BEGIN:VCARD
VERSION:4.0
FN:Lova Norgren
NAME:Lova Norgren
PHONE.WORK:+46709660916
EMAIL:lova.norgren@ahouse.se
LAST:A house
REV:1747922601891
END:VCARD
BEGIN:VCARD
VERSION:4.0
FN:Leon Wallin
NAME:Leon Wallin
PHONE.WORK:+46709660916
EMAIL:leon.wallin@ahouse.se
LAST:A house
REV:1747922601891
END:VCARD
BEGIN:VCARD
VERSION:4.0
FN:Hedvig Dolling
NAME:Hedvig Dolling
PHONE.WORK:+46725002805
EMAIL:hedvig@ahouse.se
LAST:A house
REV:1747922601891
END:VCARD
BEGIN:VCARD
VERSION:4.0
FN:Ann Larsson
NAME:Ann Larsson
PHONE.WORK:+46769003008
EMAIL:ann.larsson@ahouse.se
LAST:A house
REV:1747922601891
END:VCARD
BEGIN:VCARD
VERSION:4.0
FN:Tina Ingvarsson
NAME:Tina Ingvarsson
PHONE.WORK:+46708727704
EMAIL:tina.ingvarsson@ahouse.se
LAST:A house
REV:1747922601891
END:VCARD
BEGIN:VCARD
VERSION:4.0
FN:Lisa Blomgren
NAME:Lisa Blomgren
PHONE.WORK:+46708631687
EMAIL:lisa.blomgren@ahouse.se
LAST:A house
REV:1747922601891
END:VCARD
BEGIN:VCARD
VERSION:4.0
FN:Emelie Bogren
NAME:Emelie Bogren
PHONE.WORK:+46723787496
EMAIL:emelie.bogren@ahouse.se
LAST:A house
REV:1747922601891
END:VCARD
BEGIN:VCARD
VERSION:4.0
FN:Jarenya Svartsjö
NAME:Jarenya Svartsjö
PHONE.WORK:+46738557928
EMAIL:jarenya@ahouse.se
LAST:A house
REV:1747922601891
END:VCARD
BEGIN:VCARD
VERSION:4.0
FN:Gustav Almquist
NAME:Gustav Almquist
PHONE.WORK:+46841089900
EMAIL:gustav.almquist@ahouse.se
LAST:A house
REV:1747922601891
END:VCARD
BEGIN:VCARD
VERSION:4.0
FN:Julie Gardinier
NAME:Julie Gardinier
PHONE.WORK:+46702234347
EMAIL:julie.gardinier@ahouse.se
LAST:A house
REV:1747922601892
END:VCARD
BEGIN:VCARD
VERSION:4.0
FN:Fredrik Palo
NAME:Fredrik Palo
PHONE.WORK:+46707481056
EMAIL:fredrik.palo@ahouse.se
LAST:A house
REV:1747922601892
END:VCARD
BEGIN:VCARD
VERSION:4.0
FN:Zara Larsson
NAME:Zara Larsson
PHONE.WORK:+46707385714
EMAIL:zara@ahouse.se
LAST:A house
REV:1747922601892
END:VCARD
BEGIN:VCARD
VERSION:4.0
FN:Anna-Karin Runmon
NAME:Anna-Karin Runmon
PHONE.WORK:+46707481062
EMAIL:anna-karin.runmon@ahouse.se
LAST:A house
REV:1747922601892
END:VCARD
BEGIN:VCARD
VERSION:4.0
FN:Simone Hägred
NAME:Simone Hägred
PHONE.WORK:+4686651100
EMAIL:simone.hagred@ahouse.se
LAST:A house
REV:1747922601892
END:VCARD
BEGIN:VCARD
VERSION:4.0
FN:Cornelia Björk Linder
NAME:Cornelia Björk Linder
PHONE.WORK:+46766005929
EMAIL:cornelia@ahouse.se
LAST:A house
REV:1747922601892
END:VCARD
BEGIN:VCARD
VERSION:4.0
FN:Fatima Blomberg Dali
NAME:Fatima Blomberg Dali
PHONE.WORK:+46736460722
EMAIL:fatima@ahouse.se
LAST:A house
REV:1747922601892
END:VCARD
BEGIN:VCARD
VERSION:4.0
FN:Sofia Ekman
NAME:Sofia Ekman
PHONE.WORK:+46708984870
EMAIL:sofia.ekman@ahouse.se
LAST:A house
REV:1747922601892
END:VCARD
BEGIN:VCARD
VERSION:4.0
FN:Johan Almquist
NAME:Johan Almquist
PHONE.WORK:+46705687052
EMAIL:johan@ahouse.se
LAST:A house
REV:1747922601892
END:VCARD
BEGIN:VCARD
VERSION:4.0
FN:Maria Olofsson
NAME:Maria Olofsson
PHONE.WORK:+46709907848
EMAIL:maria.olofsson@ahouse.se
LAST:A house
REV:1747922601892
END:VCARD
BEGIN:VCARD
VERSION:4.0
FN:Richard Hammarskiöld
NAME:Richard Hammarskiöld
PHONE.WORK:+46709177297
EMAIL:richard@ahouse.se
LAST:A house
REV:1747922601892
END:VCARD
BEGIN:VCARD
VERSION:4.0
FN:Maria Ackelman
NAME:Maria Ackelman
PHONE.WORK:+46735662605
EMAIL:maria.ackelman@ahouse.se
LAST:A house
REV:1747922601892
END:VCARD
BEGIN:VCARD
VERSION:4.0
FN:Karin Tengsved
NAME:Karin Tengsved
PHONE.WORK:+46708149115
EMAIL:karin.tengsved@ahouse.se
LAST:A house
REV:1747922601892
END:VCARD
BEGIN:VCARD
VERSION:4.0
FN:Andreas Andersson
NAME:Andreas Andersson
PHONE.WORK:+46709710281
EMAIL:andreas@ahouse.se
LAST:A house
REV:1747922601892
END:VCARD
BEGIN:VCARD
VERSION:4.0
FN:Billie Josephson
NAME:Billie Josephson
PHONE.WORK:+46707473358
EMAIL:billie.josephson@ahouse.se
LAST:A house
REV:1747922601892
END:VCARD
BEGIN:VCARD
VERSION:4.0
FN:Ella Oldenmark
NAME:Ella Oldenmark
PHONE.WORK:+46761880072
EMAIL:ella.oldenmark@ahouse.se
LAST:A house
REV:1747922601892
END:VCARD
BEGIN:VCARD
VERSION:4.0
FN:Mikaela Holmberg
NAME:Mikaela Holmberg
PHONE.WORK:+46709900715
EMAIL:mikaela.holmberg@ahouse.se
LAST:A house
REV:1747922601892
END:VCARD
