### ISSUE TITLE
Don't show groups in share placeholder if group sharing is disabled

### ISSUE THREAD

**Issue by tcitworld** [nextcloud/contacts#2242]
### Steps to reproduce
1. Check out nextcloud/server#25658
2. Disallow sharing with groups in the sharing settings
3. Open the share section on an address book

### Expected behaviour
No mention of "groups" in the placeholder.

### Actual behaviour
Mention of "groups" in the placeholder.

**Comment by harisaisundhar** [comment]
Hello! I would like to work on this issue, is it available? If so, can you tell more about this ?

**Comment by tcitworld** [comment]
Great !

So in server we have introduced https://github.com/nextcloud/server/pull/25658 a while ago, which is a flag to disable sharing with groups. It's working as intended, no groups are suggested in the autocomplete sharing field, but it would be nicer if the placeholder just said `Share with users` instead of `Share with users or groups` when group sharing is disabled.

See https://github.com/nextcloud/contacts/blob/master/src/components/AppNavigation/Settings/SettingsAddressbookShare.vue#L82

To know if group sharing if enabled you'll have to get the config value here and provide it though initial state.
```php
$this->config->getAppValue('core', 'shareapi_allow_group_sharing', 'yes') === 'yes'
```
https://github.com/nextcloud/contacts/blob/master/lib/Controller/PageController.php

Then you can get the state for instance in a service:
https://github.com/nextcloud/contacts/blob/master/src/services/isContactsInteractionEnabled.js

And finally change the placeholder in the component linked at first depending on this value.

**Comment by harisaisundhar** [comment]
Awesome, thanks! Will come up with updates soon.

**Comment by Zishan-7** [comment]
Hey! I tried to fix the issue can you please review the PR?
