### ISSUE TITLE
Delete read-only contacts as systemadmin

### ISSUE THREAD

**Issue by LlamasAreAwesome** [nextcloud/contacts#2248]
### Describe the bug
A day ago, I had some contacts on my phone which I synchronised with nextcloud over the davx5 app. So far this worked great. I canceled the synchronisation but the synchronised contacts are still on my nextcloud. I tried to delete them, there are several tuts on some websites, but it isn't working cause they are read-only, but I'm the only user and admin. 

So my plan is to delete all contacts.

**First, where are the contacts store in the database?**
I tried to check some databases ``oc_addressbooks``, ``oc_addressbookchanges``, ``oc_cards`` ... , but i coudn't find any match.

**Second, even If I'll find these contacts in the databse, is it save to delete them or will I run into further problems?**

**Expected behavior**
I want to delete all contacts.

**Actual behavior**
Can't delete them cause they are read-only.

### Server configuration

**Operating system**: Ubuntu 20.04.2 LTS

**Web server:** Server version: Apache/2.4.41 (Ubuntu)
Server built:   2020-08-12T19:46:17

**Database:** MariaDB version: 10.3.29-MariaDB-0ubuntu0.20.04.1

**PHP version:** 7.4

**Nextcloud version:** 21.0.2

**Contacts version:** 3.5.1

**Updated from an older Nextcloud or fresh install:** fresh installed

**Signing status:**
```
No errors have been found.
```

**Nextcloud configuration:**
```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "21.0.2.1",
        "overwrite.cli.url": "https:\/\/***REMOVED SENSITIVE VALUE***",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "default_language": "de",
        "default_phone_region": "DE",
        "defaultapp": "files",
        "enable_previews": true,
        "preview_max_filesize_image": -1,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***"
    }
}
```

**Comment by skjnldsv** [comment]
Which addressbook are they coming from?

**Comment by skjnldsv** [comment]
> So far this worked great. I canceled the synchronisation but the synchronised contacts are still on my nextcloud

Have you disabled DavX5 now? As long as it's running it will keep syncing in the baackground

**Comment by LlamasAreAwesome** [comment]
Yes, I disabled sync and as well deleted DavX5  from the phone. The contacts are still there in read-only mode. 

The contacts were on my phone, but not anymore, I deleted them and tried to resync. If I sync they pop up again on my phone. Then I tried to delete them there without success. If I disable sync they vanished from the phone, but they are still on my nextcloud. 

This process showed me, that the contacts are only on my nextcloud not on my phone.

**Comment by skjnldsv** [comment]
> They are coming from the address book "Zuletzt kontaktiert", translated 'last used'.

Those are a feature.
You can disable this addressbook in your app management. It's called "contacts interraction"

**Comment by ann0see** [comment]
I'm having a similar issue. If I try to delete "Zuletzt kontaktiert" via web UI, I get an error message an the following entry in the log: 

```
[webdav] Fatal: Exception: This addressbook is immutable at <<closure>>

0. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Tree.php line 179
   OCA\ContactsInteraction\AddressBook->delete()
1. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php line 281
   Sabre\DAV\Tree->delete("addressbooks/us ... t")
2. /var/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php line 89
   Sabre\DAV\CorePlugin->httpDelete(Sabre\HTTP\Request {}, Sabre\HTTP\Response {})
3. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 472
   Sabre\DAV\Server->emit("method:DELETE", [Sabre\HTTP\Requ ... }])
4. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 253
   Sabre\DAV\Server->invokeMethod(Sabre\HTTP\Request {}, Sabre\HTTP\Response {})
5. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 321
   Sabre\DAV\Server->start()
6. /var/www/nextcloud/apps/dav/lib/Server.php line 332
   Sabre\DAV\Server->exec()
7. /var/www/nextcloud/apps/dav/appinfo/v2/remote.php line 35
   OCA\DAV\Server->exec()
8. /var/www/nextcloud/remote.php line 167
   require_once("/var/www/nextcl ... p")

DELETE /remote.php/dav/addressbooks/users/jonathan/z-app-generated--contactsinteraction--recent/
from <ip> by <user> at <time>
```

Is there any way to delete the "read only" contacts?

**Comment by ann0see** [comment]
Ok. This seems to be related: https://help.nextcloud.com/t/help-trying-to-understand-recently-contacted/86798

By disabling contacts integration my problem seems to be solved. @LlamasAreAwesome maybe this helps you too?
