### ISSUE TITLE
Cannot install contacts on NC 21.0.2

### ISSUE THREAD

**Issue by tomise** [nextcloud/contacts#2256]
Hello, 

I cannot install "contacts on my NC21.0.2.
When I kilcik on install contacts, get an error message:
**_Client error: `GET https://github.com/nextcloud/contacts/releases/download/v4.0.0-beta.0/contacts.tar.gz` resulted in a `404 Not Found` response: Not Found_**

What am I doing wrong or how can I fix it?

Best regards 

Tomise

### Describe the bug
......
......

**To Reproduce**

**Expected behavior**
Tell us what you expected to happen.

**Actual behavior**
Tell us what happened instead.

**Screenshots**

### Server configuration

**Operating system**: Windows, Linux, MacOS...

**Web server:** Apache, Nginx...

**Database:** MariaDB, MySQL, PostgreSQL... 

**PHP version:** 7.0, 7.1, 7.2...

**Nextcloud version:** (see Nextcloud admin page)

**Contacts version:** (see Nextcloud apps page)

**Updated from an older Nextcloud or fresh install:**

**Signing status:**
```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

**List of activated apps:**
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**Nextcloud configuration:**
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your instance's installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

### Client configuration
**Browser:**

**Operating system:**

**CardDAV-clients:**

#### *Web server error log*
```
Insert your webserver log here
```

#### *data/nextcloud.log*
```
Insert your Nextcloud log here
```

#### Browser log
<details>
<summary>How to access your browser console (Click to expand)</summary>

# Chrome
- Press either CTRL + SHIFT + J to open the “console” tab of the Developer Tools.
- Alternative method:
    1. Press either CTRL + SHIFT + I or F12 to open the Developer Tools.
    2. Click the “console” tab.

# Safari
- Press CTRL + ALT + I to open the Web Inspector.
- See Chrome’s step 2. (Chrome and Safari have pretty much identical dev tools.)

# IE9
1. Press F12 to open the developer tools.
2. Click the “console” tab.

# Firefox
- Press CTRL + SHIFT + K to open the Web console (COMMAND + SHIFT + K on Macs).
- or, if Firebug is installed (recommended):
    1. Press F12 to open Firebug.
    2. Click on the “console” tab.

# Opera
1. Press CTRL + SHIFT + I to open Dragonfly.
2. Click on the “console” tab.
</details>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by skjnldsv** [comment]
That was fast ahaha!
Please install latest `beta.1`

**Comment by tomise** [comment]
I have install beta.1, unfortunally doesn`t work, look error message: internal server error:
![image](https://user-images.githubusercontent.com/45357471/120820537-eed82700-c554-11eb-91bc-250af507fd36.png)

**Comment by tomise** [comment]
When I check the app, look this message:
sudo -u apache php occ app:check-code contacts
Analysing /var/www/html/nextcloud/apps/contacts/lib/Cron/SocialUpdate.php
 2 errors
    line   58: == - is discouraged
    line   61: == - is discouraged
Analysing /var/www/html/nextcloud/apps/contacts/lib/Service/Social/DiasporaProvider.php
 1 errors
    line  120: == - is discouraged
Analysing /var/www/html/nextcloud/apps/contacts/lib/Service/Social/FacebookProvider.php
 1 errors
    line   97: == - is discouraged
Analysing /var/www/html/nextcloud/apps/contacts/lib/Service/Social/InstagramProvider.php
 1 errors
    line  105: == - is discouraged
Analysing /var/www/html/nextcloud/apps/contacts/lib/Service/Social/MastodonProvider.php
 1 errors
    line  107: == - is discouraged
Analysing /var/www/html/nextcloud/apps/contacts/lib/Service/Social/TumblrProvider.php
 1 errors
    line   91: == - is discouraged
Analysing /var/www/html/nextcloud/apps/contacts/lib/Service/Social/TwitterProvider.php
 1 errors
    line  107: == - is discouraged
Analysing /var/www/html/nextcloud/apps/contacts/lib/Service/Social/XingProvider.php
 1 errors
    line  127: == - is discouraged
Analysing /var/www/html/nextcloud/apps/contacts/lib/Service/SocialApiService.php
 3 errors
    line  198: == - is discouraged
    line  206: == - is discouraged
    line  274: == - is discouraged
Analysing /var/www/html/nextcloud/apps/contacts/templates/main.php
 1 errors
    line    2: OC_Util - Static method of private class must not be called
Invalid appinfo.xml file found: Element 'screenshot': This element is not expected. Expected is ( category ).

App is not compliant
