### ISSUE TITLE
Address book shared with NC group does not show up for user in that group

### ISSUE THREAD

**Issue by dotdotfx** [nextcloud/contacts#226]
### Steps to reproduce
1. Share an address book from one user with a NC user group (e.g. group “team”)
2. Check with a user in that group if the AB shows in the UI (e.g. user “Anne”)
3. Share the same AB directly with that user (“Anne”) and check again

### Expected behaviour
If I share an address book with a NC user group, all users within that group should see the shared address book in the contacts app.

This worked in my NC 10 installation, but I don't know which prior version of Contacts was installed.

### Actual behaviour
If I share with the group, the AB does not show up in a user's contacts list. If I share the AB with the same user, but this time directly with his username, the AB shows up correctly.

### Server configuration

**Operating system**:
Ubuntu 16.04.2 LTS

**Web server:**
Apache/2.4.18 (Ubuntu)

**Database:**
MySQL 5.5.54-0ubuntu0.12.04.1-log

**PHP version:**
PHP 7.0.18-0ubuntu0.16.04.1

**Nextcloud version:** (see Nextcloud admin page)
12.0.0

**Contacts version:** (see Nextcloud apps page)
1.5.3

**Updated from an older Nextcloud or fresh install:**
Update from NC 10.0.0

**Signing status:**

```
“No errors have been found.”
```

**List of activated apps:**
```
Enabled:
  - activity: 2.5.2
  - bruteforcesettings: 1.0.2
  - calendar: 1.5.3
  - comments: 1.2.0
  - contacts: 1.5.3
  - dav: 1.3.0
  - external: 2.0.3
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_downloadactivity: 1.1.1
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0
```

**Nextcloud configuration:**

```
{
    "system": {
        "instanceid": "oce4002f702a",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.onlineradiomaster.de"
        ],
        "datadirectory": "\/www\/data\/cloud.onlineradiomaster.de\/data",
        "dbtype": "mysql",
        "version": "12.0.0.29",
        "dbname": "a6ahd_owncloud",
        "dbhost": "mysql.itz.uni-halle.de",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "theme": "",
        "maintenance": false,
        "secret": "***REMOVED SENSITIVE VALUE***",
        "share_folder": "\/Shared",
        "mail_smtpmode": "smtp",
        "mail_from_address": "support",
        "mail_domain": "onlineradiomaster.de",
        "mail_smtphost": "smtp.uni-halle.de",
        "mail_smtpport": "25",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "asset-pipeline.enabled": true,
        "loglevel": 2,
        "debug": true,
        "trashbin_retention_obligation": "auto",
        "mail_smtpsecure": "tls",
        "overwrite.cli.url": "https:\/\/cloud.onlineradiomaster.de",
        "htaccess.RewriteBase": "\/"
    }
}
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
Google Chrome 58.0.3029.110 (64bit)

**Operating system:**
macOS 10.12

**CardDAV-clients:**
n/a
```

**Comment by mcguenther** [comment]
I'm experiencing the same issue with my organization, and for us, having a shared address book is crucial. Does anyone have an idea why address books don't show up for users in a NC group with which it is shared with?

**Comment by jancborchardt** [comment]
Any idea @nextcloud/contacts @nextcloud/sharing?

**Comment by stweil** [comment]
I observe a slightly different behaviour in our Nextcloud (Nextcloud 12.0.0, Contacts 1.5.3):

* Sharing of an address book works with groups who's group name does not contain blanks.
* Sharing of an address book does not work with groups who's group name contains blanks.

Maybe the same problem exists for sharing with users. I did not test user names with blanks.

**Comment by skjnldsv** [comment]
Isn't this a server issue?

**Comment by stweil** [comment]
@skjnldsv, does it also work now with a group name which contains blanks?

**Comment by skjnldsv** [comment]
@stweil yes! :)

**Comment by irgendwie** [comment]
Should be fixed by https://github.com/nextcloud/server/pull/5299
