### ISSUE TITLE
Replace 'There is no member in this circle'

### ISSUE THREAD

**Issue by ArtificialOwl** [nextcloud/contacts#2284]
There is always members in a Circle, so we should replace 'There is no member in this circle' by something more 'You currently have no access to the memberlist'-like

**Comment by daita** [comment]
(for the Circles configured as JOINREQUEST)

**Comment by aryatalathi** [comment]
I would like to contribute here. Admin can you please assign me on this issue?

**Comment by aryatalathi** [comment]
@ArtificialOwl Sir, can you please review the PR #3133 ?
I have made the required changes. Please review it so that if it is fulfilling the requirements, it can get merged. Thank you!
