### ISSUE TITLE
Category with comma in name is interpreted as two categories

### ISSUE THREAD

**Issue by brunt82** [nextcloud/contacts#230]
### Steps to reproduce
1. Configure Thunderbirds addon "Cardbook" to sync with Nextcloud.
2. Create a new contact in Cardbook.
3. Add a new category "test,test2" and assign it to the new contact.
4. Open Nextcloud contacts app and notice, that the contact is assigned to two categories "test" and "test2".

### Expected behaviour
The category for the contact should be displayed as "test,test2".

### Actual behaviour
It is displayed two categories "test" and "test2".

### Additional information
Wireshark shows that Cardbook transmits the comma encoded to the server ("test\\,test2") and when I download the vcard, the comma is still encoded. Therefore Cardbook interprets the string still as one category (correct).  
However: it seems that the contacts app use the encoded comma as delimiter for the categories, although delimiters are not encoded.

### Server configuration

**Operating system**: Ubuntu 16.04.2 LTS

**Web server:** Apache/2.4.18

**Database:**  sqlite3, Version: 3.11.0

**PHP version:** 7.0.15

**Nextcloud version:** 12.0

**Updated from an older Nextcloud/ownCloud or fresh install:** First install was a 12 beta, which was upgraded to the current version.

**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
  - activity: 2.5.2
  - bruteforcesettings: 1.0.2
  - calendar: 1.5.3
  - comments: 1.2.0
  - contacts: 1.5.3
  - dav: 1.3.0
  - federatedfilesharing: 1.2.0
  - files: 1.7.2
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - user_ldap: 1.2.1
  - workflowengine: 1.2.0
Disabled:
  - admin_audit
  - encryption
  - federation
  - files_external
  - spreed
  - user_external
</details>

**Nextcloud configuration:**
<details>
<summary>Nextcloud configuration</summary>
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nextcloud-test.test.de"
        ],
        "datadirectory": "\/nextcloud-data",
        "overwrite.cli.url": "http:\/\/nextcloud-test.test.de",
        "dbtype": "sqlite3",
        "version": "12.0.0.29",
        "dbname": "nextcloud",
        "dbhost": "127.0.0.1",
        "dbport": "",
        "dbtableprefix": "oc_",
        "instanceid": "och55ujpywqp",
        "logtimezone": "UTC",
        "installed": true,
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "loglevel": 2,
        "maintenance": false,
        "updater.release.channel": "stable",
        "mail_from_address": "no-reply",
        "mail_smtpmode": "sendmail",
        "mail_smtpauthtype": "LOGIN",
        "mail_domain": "test.de",
        "theme": ""
    }
}
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP

#### LDAP configuration 
<details>
<summary>LDAP config</summary>
+-------------------------------+-----------------------------------------------------------------------------------------------------+
| Configuration                 |                                                                                                     |
+-------------------------------+-----------------------------------------------------------------------------------------------------+
| hasMemberOfFilterSupport      | 0                                                                                                   |
| hasPagedResultSupport         |                                                                                                     |
| homeFolderNamingRule          |                                                                                                     |
| lastJpegPhotoLookup           | 0                                                                                                   |
| ldapAgentName                 | uid=readonly,ou=special-users,dc=test=de                                                       |
| ldapAgentPassword             | ***                                                                                                 |
| ldapAttributesForGroupSearch  |                                                                                                     |
| ldapAttributesForUserSearch   | sn;givenName;uid;mail                                                                               |
| ldapBackupHost                |                                                                                                     |
| ldapBackupPort                |                                                                                                     |
| ldapBase                      | dc=test,dc=de                                                                                     |
| ldapBaseGroups                | ou=groups,dc=test,dc=de                                                                           |
| ldapBaseUsers                 | ou=users,dc=test,dc=de                                                                            |
| ldapCacheTTL                  | 600                                                                                                 |
| ldapConfigurationActive       | 1                                                                                                   |
| ldapDefaultPPolicyDN          |                                                                                                     |
| ldapDynamicGroupMemberURL     |                                                                                                     |
| ldapEmailAttribute            | mail                                                                                                |
| ldapExperiencedAdmin          | 1                                                                                                   |
| ldapExpertUUIDGroupAttr       | cn                                                                                                  |
| ldapExpertUUIDUserAttr        | uid                                                                                                 |
| ldapExpertUsernameAttr        |                                                                                                     |
| ldapGidNumber                 | gidNumber                                                                                           |
| ldapGroupDisplayName          | cn                                                                                                  |
| ldapGroupFilter               | (&(|(objectclass=groupOfUniqueNames))(!(cn=studenten*)))                                            |
| ldapGroupFilterGroups         |                                                                                                     |
| ldapGroupFilterMode           | 0                                                                                                   |
| ldapGroupFilterObjectclass    |                                                                                                     |
| ldapGroupMemberAssocAttr      | uniqueMember                                                                                        |
| ldapHost                      | ldaps://idm.test.de                                                                          |
| ldapIgnoreNamingRules         |                                                                                                     |
| ldapLoginFilter               | (&(&(objectclass=inetOrgPerson)(mail=*)(!(mail=*@domain1.edu))(!(mail=*@domain2.de)))(uid=%uid)) |
| ldapLoginFilterAttributes     |                                                                                                     |
| ldapLoginFilterEmail          | 0                                                                                                   |
| ldapLoginFilterMode           | 0                                                                                                   |
| ldapLoginFilterUsername       | 1                                                                                                   |
| ldapNestedGroups              | 0                                                                                                   |
| ldapOverrideMainServer        |                                                                                                     |
| ldapPagingSize                | 500                                                                                                 |
| ldapPort                      | 636                                                                                                 |
| ldapQuotaAttribute            |                                                                                                     |
| ldapQuotaDefault              |                                                                                                     |
| ldapTLS                       | 0                                                                                                   |
| ldapUserDisplayName           | mail                                                                                                |
| ldapUserDisplayName2          |                                                                                                     |
| ldapUserFilter                | (&(objectclass=inetOrgPerson)(mail=*)(!(mail=*@domain1.edu))(!(mail=*@domain2.de)))              |
| ldapUserFilterGroups          |                                                                                                     |
| ldapUserFilterMode            | 0                                                                                                   |
| ldapUserFilterObjectclass     |                                                                                                     |
| ldapUuidGroupAttribute        | auto                                                                                                |
| ldapUuidUserAttribute         | auto                                                                                                |
| turnOffCertCheck              | 0                                                                                                   |
| turnOnPasswordChange          | 0                                                                                                   |
| useMemberOfToDetectMembership | 1                                                                                                   |
+-------------------------------+-----------------------------------------------------------------------------------------------------+
</details>

### Client configuration
**Browser:** FF, Chrome

**Operating system:** Ubuntu 16

**Comment by xh3n1** [comment]
hey @jancborchardt,   should the  category name separated by  comma  not be interpreted as two categories when you create a new group?

**Comment by skjnldsv** [comment]
Haven't I already fixed this?
#85

**Comment by skjnldsv** [comment]
Okay, my bad, this is #85 that induced this issue. 
We decided, back then, that we should ban commas in groups. Otherway we can't fix the un-escaped groups. Either way, we'll have users complaining because their categories are now fused and users complaining because they can't put commas in their categories. I think it's easier to just say to the user to use another punctuation for their groups.


BUT we could add a tooltip saying that commas are forbidden. It would be easier!
Or replace them by another punctuation automatically on insert! :)

**Comment by brunt82** [comment]
> I think it's easier to just say to the user to use another punctuation for their groups.
>
> BUT we could add a tooltip saying that commas are forbidden. It would be easier!
But what about other clients? I tested it with Cardbook (as described) and a tooltip in a Nextcloud app would not prevent creating such categories in Cardbook, Android smartpone, etc.

**Comment by skjnldsv** [comment]
Will take a look on how the app handle outside modifications on categories.

**Comment by skjnldsv** [comment]
Okay, commas from outside are still interpreted as two categories.
I prefer forcing the split. People who get their groups merged are stuck with unusable groups. But people with a single group which get split in two still have their list preserved (two replicate of the same group) but at least can still use the app.

In favour of closing this. If one of you @nextcloud/contacts have another opinion, please say the word. :)

in the (next?) future, removing groups will hopefully be possible. So we'll get easier managment if a group get split and you only want one on the other two ;)

**Comment by jancborchardt** [comment]
Yeah, forcing the split is a better default for sure.
