### ISSUE TITLE
Right panel not refreshed when switching Circle.

### ISSUE THREAD

**Issue by ArtificialOwl** [nextcloud/contacts#2300]
- Log with User1 and create 2 circles: 
* 1 OPEN+JOINREQUEST+VISIBLE (name: 'Locked 001')
* 1 OPEN+VISIBLE (name: 'Open 001')

- Log with User2 and refresh the list of available Circles.
- Select the 'locked' Circle,
- Select the 'open' Circle:
 
The error is that the right panel displays a message and a button to 'Request to join' the circle 'Open 001' but it should display single button 'Join Circle'

**Comment by skjnldsv** [comment]
Is this still happening on rc0 ?

**Comment by ArtificialOwl** [comment]
seems ok, still display Request to join, but I guess it's fine
