### ISSUE TITLE
Contacts app looks a bit strange on mobile

### ISSUE THREAD

**Issue by szaimen** [nextcloud/contacts#2307]
I've done this screenshot on c.nc.c just yet so it should be the latest beta release v4.0.0-beta.3

3 points come to my mind:
1. the avatar is too close to the left
2. the action menu on the right is too close to the right
3. the `Zulect geändert vor seconds` looks out of place simply floating and interfering with anything behind it

![image](https://user-images.githubusercontent.com/42591237/123414369-177f9980-d5b4-11eb-8f44-9bc64b05368c.png)

**Comment by szaimen** [comment]
cc @nextcloud/designers

**Comment by marcoambrosini** [comment]
Maybe the field labels could be moved either inside the inputs or above them

**Comment by GretaD** [comment]
the latest master of contacts looks like this, but the points mentioned by @szaimen are still valid.
![contactsmobileview](https://user-images.githubusercontent.com/12728974/123933081-533ea880-d992-11eb-8fcb-6b5dd4577969.png)

another idea maybe would be to have everything centered, so the start of the image can be aligned with "Home" and "3 dot menu" with the end of the longest input field. cc @jancborchardt  @nimisha-vijay

**Comment by nimisha-vijay** [comment]
![image](https://user-images.githubusercontent.com/52440189/123947307-e04b2700-d9bd-11eb-8a20-90d761c12ff6.png)

Yeah, something like this would work?
In this, the text in the contact header (Nimisha, Company) is left aligned with the property title (Timezone, Social network, Phone, Email, Address), and the avatar in the header is aligned with the end of property title icons (timezone icon, heart, etc).
The 3 dot menu is aligned with end of the longest property input field.
(Also maybe a tiny bit more space between property labels and property values, it was 5px, in this screenshot it is 8px).

What do you think?

**Comment by szaimen** [comment]
Looks already much better, thanks! :)

How would you solve this one?
> the `Last modified seconds ago` looks out of place simply floating and interfering with anything behind it

**Comment by nimisha-vijay** [comment]
That can go at the bottom of the content after scrolling all the way down, because I don't really think people want to see it that much, but it's probably useful for checking if the information was updated recently.
