### ISSUE TITLE
Sync with Thunderbird and SOGo Connector

### ISSUE THREAD

**Issue by icehawk-de** [nextcloud/contacts#231]
I'm syncing my contacts with Thunderbird via SOGo Conncetor it works fine.
Only one Problem:
In Thunderbird addressbook are two email-fields (E-Mail-Adresse and Weitere E-Mail-Adresse). Both emails are transfered into the contacts-plugin, but the first as "work" and the second as "private".

I want to have it otherwise: The first as "private" and the second as "work".

Is this possible? Or is this a SOGo Connector issue?

**Comment by mburnicki** [comment]
IMO, the SoGo connector is generally very limited. I've quite a number of contacts who have more than 2 email addresses, and SoGo is unable to assign an email to the contact unless the emails refers to one of the 2 first email addresses.

There's a nice addon which can handle this:
https://addons.mozilla.org/de/thunderbird/addon/cardbook/

However, I've also been using contact images which show up in TB, and there's a cool addon which can show images from local address books, LDAP servers, or gravatar.org:
https://addons.mozilla.org/de/thunderbird/addon/ldapinfoshow/

Unfortunately "ldapinfo" doesn't recognize the address books maintained by "cardbook", so currently this doesn't work properly.

However, this would be a nice combination, so I've opened a feature request to implement this:
https://github.com/wangvisual/ldapinfo/issues/29

**Comment by skjnldsv** [comment]
Closing since this is not related to the contacts app.
We're a standard webdav server. Sogo can connect to any of them. Any errors should be notified to sogo directly unless they advize you to do that here, therefore this will come from https://github.com/nextcloud/server :)
