### ISSUE TITLE
Interface slightly messy when requesting membership

### ISSUE THREAD

**Issue by ArtificialOwl** [nextcloud/contacts#2317]
before and after I clicked on _'Request to join'_ there is a lot of wrong information displayed !

![image](https://user-images.githubusercontent.com/1038617/123696513-f2548a80-d842-11eb-8c07-3c371b95fc06.png)

**Comment by skjnldsv** [comment]
What wrong informations?

**Comment by ArtificialOwl** [comment]
My bad, not 'totally' wrong, but:

- 'There is no member in this Circles' (I already opened a ticket about it)
- 'You are not a member of <circle>' should be replaced by 'Your request have not been accepted/confirmed yet'
- 'Request to join' should be deleted or replaced by 'Cancel your request'.
- and the overall design is kind of confusing.

(please note that this is not high priority!)

**Comment by skjnldsv** [comment]
> * 'You are not a member of ' should be replaced by 'Your request have not been accepted/confirmed yet'
> * 'Request to join' should be deleted or replaced by 'Cancel your request'.

https://github.com/nextcloud/circles/issues/647

**Comment by skjnldsv** [comment]
> * and the overall design is kind of confusing.

It was accepted by Jan.

**Comment by ArtificialOwl** [comment]
Ok, effectivement  :-]
Let me have a look.

**Comment by skjnldsv** [comment]
Closing?
