### ISSUE TITLE
Group name is splitted when creating new contact in existing group

### ISSUE THREAD

**Issue by fzirker** [nextcloud/contacts#232]
### Steps to reproduce
1. Create a contact with group "Friends"
2. Select group Friends in the left bar
3. Click "New Contact"

### Expected behaviour
In group field "Friends" is pre selected

### Actual behaviour
Every character of the group name ar selected ("F", "r", "i", "e", "n", "d", "s"):
![groups](https://user-images.githubusercontent.com/2885066/26929474-217ebf7a-4c5a-11e7-875d-087c91e2a3ed.png)

### Server configuration
**Operating system**: Linux h2669288.stratoserver.net 3.16.0-042stab120.20 #1 SMP Fri Mar 10 16:52:50 MSK 2017 x86_64

**Web server:** Apache (apache2handler)

**Database:** mysql 10.0.30

**PHP version:** 5.6.30-0+deb8u1
Modules loaded: Core, date, ereg, libxml, openssl, pcre, zlib, bcmath, bz2, calendar, ctype, dba, dom, hash, fileinfo, filter, ftp, gettext, SPL, iconv, mbstring, session, posix, Reflection, standard, shmop, SimpleXML, soap, sockets, Phar, exif, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xml, xmlreader, xmlwriter, zip, apache2handler, PDO, apcu, curl, gd, imagick, intl, json, mcrypt, mysql, mysqli, pdo_mysql, pdo_sqlite, readline, sqlite3, tidy, xmlrpc, mhash, apc, Zend OPcache

**Nextcloud version:** 12.0.0 - 12.0.0.29

**Updated from an older Nextcloud/ownCloud or fresh install:** upgraded from nc 11

**Where did you install Nextcloud from:**  Official nextcloud package (ZIP)

</details>

**List of activated apps:**
<details>
	<summary>App list</summary>
```
Enabled:
 - activity: 2.5.2
 - bruteforcesettings: 1.0.2
 - calendar: 1.5.3
 - checksum: 0.3.4
 - comments: 1.2.0
 - contacts: 1.5.3
 - dav: 1.3.0
 - drawio: 0.8.8
 - federatedfilesharing: 1.2.0
 - federation: 1.2.0
 - files: 1.7.2
 - files_external: 1.3.0
 - files_pdfviewer: 1.1.1
 - files_sharing: 1.4.0
 - files_texteditor: 2.4.1
 - files_trashbin: 1.2.0
 - files_videoplayer: 1.1.0
 - firstrunwizard: 2.1
 - gallery: 17.0.0
 - issuetemplate: 0.2.1
 - logreader: 2.0.0
 - lookup_server_connector: 1.0.0
 - mail: 0.6.4
 - news: 11.0.5
 - nextcloud_announcements: 1.1
 - notifications: 2.0.0
 - oauth2: 1.0.5
 - password_policy: 1.2.2
 - previewgenerator: 1.0.6
 - provisioning_api: 1.2.0
 - serverinfo: 1.2.0
 - sharebymail: 1.2.0
 - survey_client: 1.0.0
 - systemtags: 1.2.0
 - tasks: 0.9.5
 - theming: 1.3.0
 - twofactor_backupcodes: 1.1.1
 - twofactor_totp: 1.3.0
 - updatenotification: 1.2.0
 - workflowengine: 1
Disabled:
 - admin_audit
 - encryption
 - files_versions
 - notes
 - user_external
 - user_ldap
```
</details>

**The content of config/config.php:**
<details>
	<summary>Config report</summary>

```
{
    "instanceid": "52a83b8cd6622",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "datadirectory": "\/var\/oc-data",
    "dbtype": "mysql",
    "version": "12.0.0.29",
    "installed": true,
    "theme": "",
    "maintenance": false,
    "dbname": "owncloud",
    "dbhost": "localhost",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "loglevel": 2,
    "trusted_domains": [
        "owncloud.florianzirker.de",
        "nextcloud.florianzirker.de"
    ],
    "mail_smtpmode": "php",
    "check_for_working_webdav": false,
    "mail_from_address": "no-reply",
    "mail_domain": "florianzirker.de",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "forceSSLforSubdomains": true,
    "appstore.experimental.enabled": true,
    "enable_previews": true,
    "singleuser": false,
    "trashbin_retention_obligation": "60",
    "activity_expire_days": 100,
    "memcache.local": "\\OC\\Memcache\\APCu",
    "overwrite.cli.url": "https:\/\/owncloud.florianzirker.de",
    "htaccess.RewriteBase": "\/",
    "updater.release.channel": "stable"
}
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:53.0) Gecko/20100101 Firefox/53.0

**Comment by irgendwie** [comment]
Already fixed; will be in the next release
