### ISSUE TITLE
macOS contacts app sync stopped working with Nextcloud 12 in combination with IMAP auth

### ISSUE THREAD

**Issue by maximusVII** [nextcloud/contacts#233]
After the upgrade to nextcloud 12, the sync between macOS address book app and nextcloud contacts is broken. It was working before the upgrade. After the upgrade I'm getting an incorrect login error message.

All other devices are working as expected (Android, iOS)

The issue is most likely related to the IMAP auth back-end. The sync is working fine for local users (if you create a local user instead of an IMAP user account).

I assume it is related to the replacement of the "@" by "%40" in the username (see dovecot and nextcloud log)

### Steps to reproduce
1. Activate IMAP auth
2. Create new account in macOS address book app
3. Error message (incorrect login)

### Expected behaviour
The macOS address book app should sync all contacts

### Actual behaviour
Incorrect login error message

### Server configuration
**Operating system**:
Debian Jessie 8.8

**Web server:**
Apache/2.4.10

**Database:**
mysql  Ver 14.14 Distrib 5.5.55,

**PHP version:**
PHP 7.1.2

**Server version:** (see your admin page)
12.0.0

**Calendar version:** (see the apps page)
1.5.3

**Updated from an older installed version or fresh install:**
Updated from Nextcloud 11 and partial fresh install (w/o purging the db entries)

**Signing status (ownCloud/Nextcloud 9.0 and above):**
No errors have been found.

**List of activated apps:**
Enabled:
  - activity: 2.5.2
  - admin_audit: 1.2.0
  - calendar: 1.5.3
  - comments: 1.2.0
  - contacts: 1.5.3
  - dav: 1.3.0
  - encryption: 1.6.0
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_external: 1.3.0
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - passman: 2.1.2
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - systemtags: 1.2.0
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - user_external: 0.4
  - workflowengine: 1.2.0
Disabled:
  - logreader
  - survey_client
  - user_ldap

**Nextcloud configuration:**
All details in uppercase have been removed by the author.

{
    "system": {
        "instanceid": "ID",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "DOMAIN.TLD"
        ],
        "datadirectory": "\/var\/www\/DOMAIN.TLD\/web\/cloud\/data",
        "overwrite.cli.url": "https:\/\/DOMAIN.TLD\/cloud",
        "dbtype": "mysql",
        "version": "12.0.0.29",
        "dbname": "c1_owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "CET",
        "installed": true,
        "user_backends": [
            {
                "class": "OC_User_IMAP",
                "arguments": [
                    "{DOMAIN:TLD:993\/imap\/ssl}"
                ]
            }
        ],
        "maintenance": false,
        "loglevel": 1,
        "appstore.experimental.enabled": true,
        "mail_from_address": "admin",
        "mail_smtpmode": "php",
        "mail_domain": "DOMAIN.TLD",
        "theme": "",
        "htaccess.RewriteBase": "\/cloud",
        "updater.release.channel": "stable"
    }
}

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
Yes

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
IMAP

### Client configuration
**Browser:**
N/A
**Operating system:**
macOS Sierra

**CalDAV-clients:**
macOS address book app (not working)
iOS address book (working as expected)

#### Web server error log
Mailserver log:
Jun 14 23:06:24 localhost dovecot: imap-login: Aborted login (auth failed, 1 attempts in 2 secs): user=<USER%40DOMAIN.TLD>, method=PLAIN, rip=XXX.XXX.XXX.XXX, lip=XXX.XXX.XXX.XXX, TLS, session=<KL6j7PFRJAAuZeaP>

#### Log file (data/nextcloud.log)
' (Remote IP: 'XXX.XXX.XXX.XXX')","userAgent":"Mac OS X\/10.12.3 (16D32) AddressBook\/1756.14.6","version":"12.0.0.29"}
{"reqId":"qGC4cIe5uqj8dCZYo8vo","level":2,"time":"2017-06-14T22:07:01+01:00","remoteAddr":"XXX.XXX.XXX.XXX","user":"--","app":"core","method":"PROPFIND","url":"\/cloud\/remote.php\/dav\/addressbooks\/users\/USER%40DOMAIN.TLD\/default\/","message":"Login failed: 'USER%40DOMAIN.TLD' (Remote IP: 'XXX.XXX.XXX.XXX')","userAgent":"Mac OS X\/10.12.3 (16D32) AddressBook\/1756.14.6","version":"12.0.0.29"}

#### Browser log
N/A

**Comment by MarvAmBass** [comment]
👍 - I like to confirm this bug

I too use the imap backend. And I disabled the bruteforce plugin.

## Log Output:

`{"reqId":"ASDFASDF","level":2,"time":"2017-06-25T20:46:29+00:00","remoteAddr":"192.168.XX.XX","user":"--","app":"core","method":"OPTIONS","url":"\/remote.php\/dav\/principals\/users\/asdf@asdf.asdf\/","message":"Login failed: 'asdf%40asdf.asdf' (Remote IP: '192.168.XX.XX')","userAgent":"Mac OS X\/10.12.5 (16F73) AddressBook\/1756.20","version":"12.0.0.29"}`

sensetive informations where replaced with an 'asdf'

in my optinion its a problem with the __@__ symbol which is converted into a __%40__ by the addressbook app.

if i try a wrong password with the same username in chrome i get the following error (without a replacement of the __@__ symbol)

`{"reqId":"ASDF","level":2,"time":"2017-06-25T20:37:03+00:00","remoteAddr":"192.168.XX.XX","user":"--","app":"core","method":"POST","url":"\/index.php\/login","message":"Login failed: 'asdf@asdf.asdf' (Remote IP: '192.168.XX.XX')","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/58.0.3029.110 Safari\/537.36","version":"12.0.0.29"}`

**Comment by MarvAmBass** [comment]
I was able to make a quickfix to get it running again:

In File: nextcloud/apps/user_external/lib/imap.php 
I added the following line directly at the beginning of the **checkPassword** function:

`		$uid = str_replace("%40","@",$uid);
`

Full File:

```
<?php
/**
 * Copyright (c) 2012 Robin Appelman <icewind@owncloud.com>
 * This file is licensed under the Affero General Public License version 3 or
 * later.
 * See the COPYING-README file.
 */

/**
 * User authentication against an IMAP mail server
 *
 * @category Apps
 * @package  UserExternal
 * @author   Robin Appelman <icewind@owncloud.com>
 * @license  http://www.gnu.org/licenses/agpl AGPL
 * @link     http://github.com/owncloud/apps
 */
class OC_User_IMAP extends \OCA\user_external\Base {
	private $mailbox;
	private $domain;

	/**
	 * Create new IMAP authentication provider
	 *
	 * @param string $mailbox PHP imap_open mailbox definition, e.g.
	 *                        {127.0.0.1:143/imap/readonly}
	 * @param string $domain  If provided, loging will be restricted to this domain
	 */
	public function __construct($mailbox, $domain = '') {
		parent::__construct($mailbox);
		$this->mailbox=$mailbox;
		$this->domain=$domain;
	}

	/**
	 * Check if the password is correct without logging in the user
	 *
	 * @param string $uid      The username
	 * @param string $password The password
	 *
	 * @return true/false
	 */
	public function checkPassword($uid, $password) {

		$uid = str_replace("%40","@",$uid);

		if (!function_exists('imap_open')) {
			OCP\Util::writeLog('user_external', 'ERROR: PHP imap extension is not installed', OCP\Util::ERROR);
			return false;
		}

 		// Check if we only want logins from ONE domain and strip the domain part from UID		
 		if($this->domain != '') {
 			$pieces = explode('@', $uid);
 			if(count($pieces) == 1) {
 				$username = $uid . "@" . $this->domain;
 			}elseif((count($pieces) == 2) and ($pieces[1] == $this->domain)) {
 				$username = $uid;
 				$uid = $pieces[0];
 			}else{
 				return false;
 			}
 		}else{
 			$username = $uid;
 		}


 		$mbox = @imap_open($this->mailbox, $username, $password, OP_HALFOPEN, 1);
		imap_errors();
		imap_alerts();
		if($mbox !== FALSE) {
			imap_close($mbox);
			$uid = mb_strtolower($uid);
			$this->storeUser($uid);
			return $uid;
		}else{
			return false;
		}
	}
}
```

**Comment by MarvAmBass** [comment]
created a pullrequest

https://github.com/nextcloud/apps/pull/35
