### ISSUE TITLE
Dark contactsmenu icon in files and contacts app

### ISSUE THREAD

**Issue by szaimen** [nextcloud/contacts#2330]
With the latest release of the contacts app, the contactsmenu icon looks inverted in the files and contacts app on c.nc.c:
![image](https://user-images.githubusercontent.com/42591237/124522550-f741ad00-ddf3-11eb-93fc-34abecabc188.png)
I think this is due to the newly added icon import here https://github.com/nextcloud/contacts/blob/d970d5df0fa835d663c4390e3064759cad28e284/css/icons.scss#L36 which overwrites the icon that is inserted via the core css and displays it in the wrong color. Can we fix this by simply removing this import or is a different fix needed?

**Comment by szaimen** [comment]
@skjnldsv as this chrrently looks pretty bad in the files app on NC22 on c.nc.c, do you have some feedback on this?

**Comment by skjnldsv** [comment]
22 is bundled already, we should fix in contacts.
I guess just making sure that it's properly defined to white my default instead or adding an exclusion rule?

**Comment by szaimen** [comment]
Hm, how to do that? I wanted to fix it in the contacts app by removing the line that I mentioned in the fescription. But I am not sure if this breaks things...

**Comment by skjnldsv** [comment]
It will for everything that uses `icon-contacts`.
I guess it should be replacing `icon-contacts` in contacts with `icon-contacts-dark`!

**Comment by szaimen** [comment]
ah okay, I am preparing a PR

**Comment by szaimen** [comment]
Only problem that I see is that the admin needs to run maintenance:repair after updating the contacts app to make this change visible... But I guess there is no way around it...

**Comment by skjnldsv** [comment]
> Only problem that I see is that the admin needs to run maintenance:repair after updating the contacts app to make this change visible... But I guess there is no way around it...

Cache will expire and get recompiled after a bit, maintenance:repair is not always needed.

**Comment by szaimen** [comment]
> Cache will expire and get recompiled after a bit, maintenance:repair is not always needed.

Good to know :)

**Comment by szaimen** [comment]
I can still reproduce that so it seems like #2331 didn't fix the issue...
