### ISSUE TITLE
contacs is not compatible to nextcloud 22.0.0

### ISSUE THREAD

**Issue by uvolmer** [nextcloud/contacts#2335]
### Describe the bug
contacs is not compatible to nextcloud 22.0.0
......
ulf@nextcloud:~$ sudo -u www-data php /var/www/html/nextcloud/occ app:enable contacts
App "Contacts" cannot be installed because it is not compatible with this version of the server.
......

**To Reproduce**
1. install/upgrade to NC 22
2. occ app:enable contacts

**Comment by skjnldsv** [comment]
We're still on the beta channel, let me release as stable! :)

**Comment by skjnldsv** [comment]
Done
