### ISSUE TITLE
Accents in "mailing lists" get garbled in the web interface

### ISSUE THREAD

**Issue by nekohayo** [nextcloud/contacts#234]
Theoretically I'm using the addressbooks through CardDAV and imported my contacts through CardDAV, but this is a bug I'm seeing only in Nextcloud's contacts _web interface_, so I presume this is the right place...

If I have a contact named "Bob Doré", it shows up fine as an individual contact. However, if `"Bob Doré <bob@example.com>"` is inside a "mailing" list (you can create such a list with Evolution, for example) for batch mail sending, while it will show up fine in Evolution and other clients, in the nextcloud contacts web interface it will show up as `Bob =?ISO-8859-1?Q?Dor=E9?=<bob@example.com>`

**Comment by skjnldsv** [comment]
@nekohayo Hey! Somehow I never seen this issue before! Please forgive me!
I'm going through the old issues to cleanup.
Is this still happening on the version 3.0.0 alpha?

I know it's a bit late, but could you attach here a vcard example with the `=?ISO-8859-1?Q?Dor=E9?=` inside?

**Comment by skjnldsv** [comment]
As there is no feedback since a while I will close this ticket. If this is still happening please feel free to reopen.
