### ISSUE TITLE
Textarea for contact notes does not show all content from database

### ISSUE THREAD

**Issue by uok** [nextcloud/contacts#2347]
I noticed that the textarea for contact notes does not show all content (seems to be cut off at first comma)
But in the database everything is stored correctly (data has been synced via DAV).

Nextcloud v21.0.3 with Contacts v4.0.0
Browser: Chromium v91

**Comment by skjnldsv** [comment]
Please share the vcard as text

**Comment by uok** [comment]
I downloaded the vcard and as expected it contains complete notes

```
BEGIN:VCARD
VERSION:3.0
UID:1234
FN:John Smith
N:John;Smith;;;
CATEGORIES:Friends
MPHONE.X-ABLABEL:Mobile
MPHONE.TEL;TYPE="HOME,CELL":1234567890
HEMAIL.X-ABLABEL:Home
HEMAIL.EMAIL;TYPE=HOME:example@example.com
ADR;TYPE=HOME:;;Street;City;;123456;
BDAY;VALUE=DATE:19700101
NOTE:Text 1\n\nText 2, more text\nText 3\nText 4
END:VCARD
```
In contacts the notes look like this

```
Text 1

Text 2
```

but should be

```
Text 1

Text 2, more text
Text 3
Text 4
```

**Comment by uok** [comment]
Found it: the comma needs to be escaped as `\,` when writing it with DAV. 
It is now displayed correctly in Nextcloud. On the phone it works with/without escaping.
