### ISSUE TITLE
SocialApiService: Call to a member function supportsContact() on null

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/contacts#2348]
### Describe the bug
Error on SocialUpdate background job

```
Error: Call to a member function supportsContact() on null
```

Full trace at: https://sentry.io/share/issue/836e7100013b4de9824a5bc95b31d426/

**To Reproduce**
1. Enable update avatars from social media
2. Let the cronjob run

**Expected behavior**
No errors in the logs

**Actual behavior**
See error log linked above

### Server configuration

**Operating system**: Windows, Linux, MacOS...

**Web server:** Apache

**Database:** MariaDB

**PHP version:** 8.0

**Nextcloud version:** 22.0.0

**Contacts version:** 4.0.0

**Updated from an older Nextcloud or fresh install:** Updated

**Comment by call-me-matt** [comment]
I do not see this error in my logs with same configuration. I suppose you do have contacts in your address book?

**Comment by juliushaertl** [comment]
I only had a quick look at the code but I couldn't see any handling of the `any` string that is passed in here:

https://github.com/nextcloud/contacts/blob/c03bd908b6df2018b54fc6cdbdd90dca922e1c10/lib/Cron/SocialUpdate.php#L49

To me it seems as if that is just not handled properly as it would basically result in a `$allConnectors = [null];` within https://github.com/nextcloud/contacts/blob/205df6a57d79c730274a36ade8eba6813ec58256/lib/Service/SocialApiService.php#L191 and then directly lead to the error.

The tests I looked add might not catch that though, since the provider is mocked there independent on the network:
https://github.com/nextcloud/contacts/blob/2a3950e425d0caac6ba3fa7bbbe84003f6f5cb99/tests/unit/Service/SocialApiServiceTest.php#L443-L445
https://github.com/nextcloud/contacts/blob/2a3950e425d0caac6ba3fa7bbbe84003f6f5cb99/tests/unit/Service/SocialApiServiceTest.php#L410

If you need any additional info let me know.

**Comment by call-me-matt** [comment]
ah, yes.
So should we simply check for this keyword [here](https://github.com/nextcloud/contacts/blob/205df6a57d79c730274a36ade8eba6813ec58256/lib/Service/SocialApiService.php#L190)?
`if ($network && $network != 'any') {`

**Comment by juliushaertl** [comment]
I pushed the patch i had in mind to #2351 but it showed up further errors once it passes to the actual providers


![image](https://user-images.githubusercontent.com/3404133/125746750-9c3b2848-56ed-4d59-9d67-5edf50635747.png)


https://sentry.io/share/issue/d247613a85f14dff9abeddb287d1bf73/

**Comment by call-me-matt** [comment]
Thank you, it looks fine. I will add some checks in the supportsContact functions to return false if no respective field is set so the error log will be clean again.
