### ISSUE TITLE
Many Phone fields not translated after update to contacts v4

### ISSUE THREAD

**Issue by tdoerschel** [nextcloud/contacts#2349]
Hi,

after updating the contacts app to v4.0.0 on our NC 21.0.10 with old MySQL 5.7.32 and PHP 7.3.29 most but not all contacts have the phone field description not translated. It shows the VCARD raw "WORK,CELL" etc.
Not all contacts, but most of the 1 address book that we use (with about 1800 entries).

You can click on the description and choose the correct name. Then it is displayed correctly.
Here is a screenshot
![image](https://user-images.githubusercontent.com/46196223/125405653-3bb2e700-e3b8-11eb-8ee0-27aea114c2e4.png)

**Comment by SaimenSays** [comment]
Same here. For me it seems as the correct items are in the dropdown. These untranslated only appear when a new contact is created on my phone and synced to nextcloud.

**Comment by hamza221** [comment]
I can't reproduce anymore
