### ISSUE TITLE
Failing npm ci for v4.0.0

### ISSUE THREAD

**Issue by mchobbel** [nextcloud/contacts#2352]
Hello all,

I am trying to build version v4 but it fails on the `npm ci` line with the following error:
```
npm ERR! fsevents not accessible from chokidar
```
I have npm version 6.14.13 and node version v14.17.0.

What I did was:
```
git clone https://github.com/nextcloud/contacts.git
cd contacts
git checkout v4.0.0
make
```
Greetings,
Michiel

**Comment by skjnldsv** [comment]
Please use npm 7 and node 14

**Comment by skjnldsv** [comment]
https://github.com/nextcloud/contacts/blob/1e9b72f0d491735fde4291fc01280e11b8c57837/package.json#L72-L75

**Comment by mchobbel** [comment]
Aha, thanks. It works now!  

Nb.  Since I am on an OS that doesnt ship these npm/node versions I went for a docker-based setup like this:
```
mkdir -p tmp/nc
cd tmp/nc
chcon -Rt svirt_sandbox_file_t .   #  label this dir to gant docker-container access
git clone https://github.com/nextcloud/contacts.git
cd contacts
git checkout v4.0.0
cd ..
```
Enter container:
```
podman run --rm -v ./contacts:/contacts -it node:16-buster bash
```
Run inside the container:
```
cd  /contacts
make dev-setup
make build-js
```
