### ISSUE TITLE
Ok button for selecting birtday date is invisible

### ISSUE THREAD

**Issue by CarlSchwan** [nextcloud/contacts#2354]
### Describe the bug

When selecting a birthday date for a contact, I was unable at first to save it. It turns out the Ok button was invisible and I needed to to scroll to make the ok button appear, but considering the big amount of white space it wasn't oblivious to me. See screenshot:

![image](https://user-images.githubusercontent.com/23653902/125920232-5b1298ef-befa-4d67-8249-3360f79a624c.png)

**To Reproduce**
1. Go to a contact
2. Click on add new propriety -> birthday
4. try to set a birthday and don't understand why you are unable to save it

**Expected behavior**
The popup appears fully and isn't masked

**Actual behavior**
The end of the popup is masked

### Server configuration

It's running on cloud.nextcloud.com (no idea what specific version is running there) and using the webui.

**Comment by Ethaseo** [comment]
Im having the same problem here. Thanks for bringing this up i was searching the whole time in my logs why i couldnt save it and thought it shouild save it automatically.

**Comment by lunar91** [comment]
Same issue here. Good catch, @Ethaseo.

The [overflow:auto](https://github.com/nextcloud/contacts/blob/25571144429ccd5dda2ddc05069175dce21c08fc/css/contacts.scss#L53) on the contact details parent element is cutting off the Datepicker element. In my testing I haven't seen any issue with removing the overflow:auto, but I'm not sure why it was added to begin with.

**Comment by Quintasan** [comment]
Took me 30 minutes to realize that I'm probably supposed to somehow accept the changes to the contact, but I couldn't figure out how to do it. Can we just remove the `overflow: auto` property for now? I think working-but-ugly is better than broken-but-pretty.

**Comment by lolli78** [comment]
Same here, Nextcloud 22.2.5

**Comment by hamza221** [comment]
Not reproducible on latest main
