### ISSUE TITLE
.vcf import fails silently

### ISSUE THREAD

**Issue by dhowe** [nextcloud/contacts#236]
ubuntu 16.04
nextcloud 12.0.0
client: chromium 57.0.2987.133 (64-bit)
client OS: osx 10.10.5

no errors in any logs

**Comment by dhowe** [comment]
this happens because no address book is selected (or none exist) -- this should clearly be an interface warning

**Comment by jancborchardt** [comment]
If no address book exists, an import should trigger the creation of one. A warning is not needed.

cc @nextcloud/contacts

**Comment by dhowe** [comment]
yes, even better

**Comment by skjnldsv** [comment]
Hum, strange. I thought we implemented the creation of an addressbook if none existed! 
Maybe was it on the loading of the app. 🤔

**Comment by skjnldsv** [comment]
Okay, I've given some thought, and because a new book is created if there isn't an addressbook available ON APP LOAD and since you can't remove the last addressbook, I don't see this situation occuring.

However, we should indeed display an error on a contact creation failure.
