### ISSUE TITLE
`npm ci` fails due to wrong cdav-library tarball checksum.

### ISSUE THREAD

**Issue by mejo-** [nextcloud/contacts#2362]
Installing NodeJS dependencies for the contacts app currently fails both locally on my machine and in Gitlab CI due to a integrity checksum missmatch for nextcloud/cdav-library:

```
> git show -q
commit b8dc17def6e82c6e59e28d00ff27980050c49057 (HEAD -> master, origin/master, origin/HEAD)
[...]
> npm -v
7.6.3
> npm ci
[...]
npm WARN tarball tarball data for cdav-library@git+ssh://git@github.com/nextcloud/cdav-library.git#0d826181fdb3958ad7ec214fc00b450edb55a866 (sha512-pa6beP0vY/exZKPOhEpqHTnkVLtksjZaPKFTmhCHvhieDxrNbpqCC2EHHZHy5x1RPFxMbpqeipTLK80m3A+MZw==) seems to be corrupted. Trying again.
npm WARN tarball tarball data for cdav-library@git+ssh://git@github.com/nextcloud/cdav-library.git#0d826181fdb3958ad7ec214fc00b450edb55a866 (sha512-pa6beP0vY/exZKPOhEpqHTnkVLtksjZaPKFTmhCHvhieDxrNbpqCC2EHHZHy5x1RPFxMbpqeipTLK80m3A+MZw==) seems to be corrupted. Trying again.
npm ERR! code EINTEGRITY
npm ERR! sha512-pa6beP0vY/exZKPOhEpqHTnkVLtksjZaPKFTmhCHvhieDxrNbpqCC2EHHZHy5x1RPFxMbpqeipTLK80m3A+MZw== integrity checksum failed when using sha512: wanted sha512-pa6beP0vY/exZKPOhEpqHTnkVLtksjZaPKFTmhCHvhieDxrNbpqCC2EHHZHy5x1RPFxMbpqeipTLK80m3A+MZw== but got sha512-Ndwy4++X1m1jIqoQFP882SQH+RfkDTLbYRXnePavNNlLx5vmR4sHLRWZMIlwphWtxiU+mKhGisPM10V6K6ISXA==. (262717 bytes)

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2021-07-20T08_57_59_563Z-debug.log
```

`package-lock.json` references `cdav-library` as follows:

```
               "node_modules/cdav-library": {
                        "version": "0.0.1",
                        "resolved": "git+ssh://git@github.com/nextcloud/cdav-library.git#0d826181fdb3958ad7ec214fc00b450edb55a866",
                        "integrity": "sha512-pa6beP0vY/exZKPOhEpqHTnkVLtksjZaPKFTmhCHvhieDxrNbpqCC2EHHZHy5x1RPFxMbpqeipTLK80m3A+MZw==",
                        "license": "AGPL-3.0",
                        "dependencies": {
                                "core-js": "^3.15.2",
                                "regenerator-runtime": "^0.13.7"
                        },
                        "engines": {
                                "node": ">=14.0.0"
                        }
                },
```

When manually installing `cdav-library#0d826181fdb3958ad7ec214fc00b450edb55a866`, the sha512 sum is different than the one referenced above:

```
> npm install git+ssh://git@github.com/nextcloud/cdav-library.git#0d826181fdb3958ad7ec214fc00b450edb55a866
[...]
> git diff package-lock.json
diff --git a/package-lock.json b/package-lock.json
index 74498ff6..00d19083 100644
--- a/package-lock.json
+++ b/package-lock.json
@@ -23,7 +23,7 @@
                                "@nextcloud/vue": "^4.0.3",
                                "b64-to-blob": "^1.2.19",
                                "camelcase": "^6.2.0",
-                               "cdav-library": "git+https://github.com/nextcloud/cdav-library.git",
+                               "cdav-library": "github:nextcloud/cdav-library#0d826181fdb3958ad7ec214fc00b450edb55a866",
                                "debounce": "^1.2.1",
                                "downloadjs": "^1.4.7",
                                "ical.js": "^1.4.0",
@@ -3861,7 +3861,7 @@
                "node_modules/cdav-library": {
                        "version": "0.0.1",
                        "resolved": "git+ssh://git@github.com/nextcloud/cdav-library.git#0d826181fdb3958ad7ec214fc00b450edb55a866",
-                       "integrity": "sha512-pa6beP0vY/exZKPOhEpqHTnkVLtksjZaPKFTmhCHvhieDxrNbpqCC2EHHZHy5x1RPFxMbpqeipTLK80m3A+MZw==",
+                       "integrity": "sha512-Ndwy4++X1m1jIqoQFP882SQH+RfkDTLbYRXnePavNNlLx5vmR4sHLRWZMIlwphWtxiU+mKhGisPM10V6K6ISXA==",
                        "license": "AGPL-3.0",
                        "dependencies": {
                                "core-js": "^3.15.2",
@@ -15470,7 +15470,7 @@
                },
                "cdav-library": {
                        "version": "git+ssh://git@github.com/nextcloud/cdav-library.git#0d826181fdb3958ad7ec214fc00b450edb55a866",
-                       "integrity": "sha512-pa6beP0vY/exZKPOhEpqHTnkVLtksjZaPKFTmhCHvhieDxrNbpqCC2EHHZHy5x1RPFxMbpqeipTLK80m3A+MZw==",
+                       "integrity": "sha512-Ndwy4++X1m1jIqoQFP882SQH+RfkDTLbYRXnePavNNlLx5vmR4sHLRWZMIlwphWtxiU+mKhGisPM10V6K6ISXA==",
                        "from": "cdav-library@github:nextcloud/cdav-library#0d826181fdb3958ad7ec214fc00b450edb55a866",
                        "requires": {
                                "core-js": "^3.15.2",
```

Let me know if I should open a PR to fix the shasum for `cdav-library` in `package-json.lock`.

**Comment by skjnldsv** [comment]
> Let me know if I should open a PR to fix the shasum for `cdav-library` in `package-json.lock`.

Sure! I guess something changed in the cdav-lib repo :)
Thanks for noticing!

**Comment by mejo-** [comment]
> Sure! I guess something changed in the cdav-lib repo :)

Here you are: #2363 :blush:

**Comment by mejo-** [comment]
Mh, so apparently there's something weird happening. On Github Actions, the old SHA512 sum (`pa6beP0vY/exZKPOhEpqHTnkVLtksjZaPKFTmhCHvhieDxrNbpqCC2EHHZHy5x1RPFxMbpqeipTLK80m3A+MZw==`) works and the new one (`Ndwy4++X1m1jIqoQFP882SQH+RfkDTLbYRXnePavNNlLx5vmR4sHLRWZMIlwphWtxiU+mKhGisPM10V6K6ISXA==`) fails. On my local system and on Gitlab CI, the old SHA512 sum is reported as missmatch by NPM. I'll have to further investigate this :thinking:

**Comment by mejo-** [comment]
I was able to track down the issue to the NPM version being installed: with NPM 7.7.0 or newer installed, the existing integrity checksum is calculated, with NPM 7.6.4 or older, the other one. I suspect the [change regarding `npm publish` in NPM 7.7.0](https://github.com/npm/cli/commit/8cce4282f7bef11aeeb73cffd532b477b241985e) to be the reason for this.

In other words, there's no problem with the `package-lock.json` as it is right now, but it requires NPM >= 7.7.0. Sorry for the noise.

I's always so much fun (not!) to debug the toolchain only to realize that something backwards-incompatible changed "somewhere" :cry:

**Comment by szaimen** [comment]
Hi @mejo, I have the same problem but on my machine is npm 7.19.1 installed which shouldn't have this issue based on your findings, no?

**Comment by mejo-** [comment]
Hey @szaimen :blush:

That's indeed strange. I was able to fix this issue by upgrading to 7.20.0 in our [Gitlab CI builds](https://gitlab.com/collectivecloud/docker-builds/-/commit/1dbb06f0638fc6d3477fb52701aff8282c6e50a7).

Since I wanted to understand the reason, I went all the way and gradually downgraded again to 7.10, 7.8, 7.7 and 7.6.4. That revealed that the checksum missmatch happens with 7.6.4 (which I also have installed locally as it's the version currently packaged in Debian/experimental), but it doesn't happen with 7.7.0. Looking at the changelog between 7.6.4 and 7.7.0, the [change regarding npm publish](https://github.com/npm/cli/commit/8cce4282f7bef11aeeb73cffd532b477b241985e) seemed to be the one that is most likely to cause the changed checksums.

Do you get the same checksum missmatch as I did? With the same (wrong) checksum?

**Comment by szaimen** [comment]
Thanks for the response!
I actually have a different checksum but also a different commit reference.
See https://github.com/nextcloud/contacts/pull/2372#issuecomment-885210643

**Comment by szaimen** [comment]
Seems like when I run ` npm install git+ssh://git@github.com/nextcloud/cdav-library.git#e62c7c9942d6759743dc9a0350921e898440f2d5` I get this:
![image](https://user-images.githubusercontent.com/42591237/126709738-fb218450-b619-4159-92b9-533282122a2b.png)

**Comment by szaimen** [comment]
Sry for the noise. Could solve it
