### ISSUE TITLE
Add a contact (with umlauts) to a group (with umlauts) breaks encoding

### ISSUE THREAD

**Issue by kesselb** [nextcloud/contacts#2365]
### Describe the bug

Add a contact (with umlauts) to a group (with umlauts) breaks encoding

**To Reproduce**

- Create a contact with umlauts (e.g. Mäx)
- Create a group with umlauts (e.g. Täst)
- Add contact Mäx to group Täst

**Expected behavior**

Mäx should be Mäx

**Actual behavior**

Mäx is now MÃ¤x

**Screenshots**

https://user-images.githubusercontent.com/3902676/126527774-5428c7da-1e07-43c0-baf6-910c7c73b2b3.mp4

**Comment by kangaroo72** [comment]
I think, I can confirm.
Actually I have 282 Contacts, and the umlauts are suddenly broken.
What happened??

![image](https://user-images.githubusercontent.com/6906390/194835824-911ca713-d97a-402b-ae32-3a3b45a60323.png)

**Comment by ChristophWurst** [comment]
You tell us :)

Did you update the app? Did you update Nextcloud?

**Comment by kangaroo72** [comment]
Actually I'm on NC 24.0.5 and Contacts 4.2.2

**Comment by kangaroo72** [comment]
Same on 24.0.6
![grafik](https://user-images.githubusercontent.com/6906390/194853782-9825549c-c0e5-41fc-b60f-82bfcca98359.png)

**Comment by ChristophWurst** [comment]
Could you share the redacted .vcf?

**Comment by kangaroo72** [comment]
Here is one affected vcf.
[D40302BD-DDB1-485D-AF45-A6163E922C85.vcf.zip](https://github.com/nextcloud/contacts/files/9748472/D40302BD-DDB1-485D-AF45-A6163E922C85.vcf.zip)

**Comment by joshtrichards** [comment]
Related: #946
