### ISSUE TITLE
Delete a group feature

### ISSUE THREAD

**Issue by kesselb** [nextcloud/contacts#2369]
**Is your feature request related to a problem? Please describe.**

I'm always frustrated when deleting groups. It's necessary to edit **each** contact and unset the group to remove a group.

**Describe the solution you'd like**

A function to delete a group

**Describe alternatives you've considered**

Not using groups ;)

**Additional context**

**Comment by skjnldsv** [comment]
https://github.com/nextcloud/contacts/issues/1175

**Comment by pjotrek-b** [comment]
I have to admit: +1 :+1:
I just spent 2 days sorting out contacts manually to clean up an imported address book.

Thank you very much in advance!
