### ISSUE TITLE
configuring a Circle as ROOT makes it LOCAL

### ISSUE THREAD

**Issue by ArtificialOwl** [nextcloud/contacts#2371]
![image](https://user-images.githubusercontent.com/1038617/126650913-9dfd06ad-8ff6-41c4-b29b-ac9ff1a77b8c.png)

```
	public const CFG_LOCAL = 4096;              // Local even on GlobalScale
	public const CFG_ROOT = 8192;               // Circle cannot be inside another Circle
```

**Comment by ArtificialOwl** [comment]
in 22.1.0, Circles won't allow the changes from Local to non-local (and non-local to Local)

**Comment by ArtificialOwl** [comment]
_Current behaviour_: enabling/disabling the option 'Prevent circle from being a member of another circle' does not set the Circle as ROOT, but instead try to set the Circle as LOCAL.

_Expected behaviour_: enabling/disabling the option 'Prevent circle from being a member of another circle' should set the Circle as LOCAL

The reason behind this is that for the Contacts App, the config flag for ROOT is `4096`, which is the config flag for LOCAL. The wrong config flag is sent when enabling/disabling the option. The correct config flag for ROOT is `8192`

**Comment by ChristophWurst** [comment]
So https://github.com/nextcloud/contacts/blob/54580214dc060bfae65d250e86d35a8030f44052/src/models/constants.ts#L75 has to be changed to 8192 and that's it?

**Comment by ArtificialOwl** [comment]
Yes, it seems to be the origin of the issue !

**Comment by ChristophWurst** [comment]
Then this is a regression caused by https://github.com/nextcloud/circles/commit/40616b67642e3884ba5bf751462d4b9035d0e7fb

**Comment by ArtificialOwl** [comment]
I don't think #2520 fixes this issue, it is still missing the correct value for ROOT config flag

**Comment by ArtificialOwl** [comment]
please note that 'LOCAL' at this point is not important, as while it is set as a flag in the definition of a Circle, you cannot switch from local to not-local anymore. It is set at the creation of the Circle and cannot be changed
