### ISSUE TITLE
Deactivated Accounts still show up in Contacts for Chat and Videocalls

### ISSUE THREAD

**Issue by RuudschMaHinda** [nextcloud/contacts#238]
### Steps to reproduce
Deactivate an account

### Expected behaviour
Accounts should be unavailable for chat and videocalls

### Actual behaviour
Contacts show up as able to chat and for videocalls

### Server configuration

**Nextcloud version:** (see Nextcloud admin page)
12.0.0
**Contacts version:** (see Nextcloud apps page)
1.5.3
**Updated from an older Nextcloud or fresh install:**
Updated since owncloud 6, migrated to Nextcloud 10 from owncloud 9

**Comment by jancborchardt** [comment]
This issue relates to the user management, not to Contacts. :) Please reopen the issue at https://github.com/nextcloud/server/issues – thanks!
