### ISSUE TITLE
No release or tag for 4.0.1

### ISSUE THREAD

**Issue by raimund-schluessler** [nextcloud/contacts#2381]
@szaimen It would be nice if there was a release and a tag for 4.0.1.

**Comment by szaimen** [comment]
Is this what you are looking for? https://github.com/nextcloud-releases/contacts/releases

**Comment by raimund-schluessler** [comment]
Yes. But what is this repository? Did the app move?

**Comment by skjnldsv** [comment]
Yes, security measures

**Comment by raimund-schluessler** [comment]
> 
> 
> Yes, security measures

Ok. Whatever this means.
In which repository should we work now? And is there a bit of background for this decision anywhere?

**Comment by skjnldsv** [comment]
Work here, but the releases are stored in https://github.com/nextcloud-releases/
