### ISSUE TITLE
From nextcloud exported vcard files can't be imported correctly

### ISSUE THREAD

**Issue by knut-hildebrandt** [nextcloud/contacts#239]
I had already reported this behaviour in this bug report https://github.com/nextcloud/contacts/issues/235#issuecomment-309798824 but it later turned out to be a different issue.

I exported the address book from my nextcloud, deleted it on the server and re-imported it. Less than 15% of the contacts were imported. Tried it several times and it always was the same. Then I had a short look at the exported VCard-file and saw that:

1.   it was somehow mixed and held version 3.0 AND version 4.0 vcards
2.   the majority of the vcards had several - up to five - VERSION entries, all looking the exactly the same for one vcard
3.    many of the vcards had several PRODID entries, some of them up to three or four. All of these entries were generated by different clients

Somehow I had the idea that vcards with more than one VERSION and PRODID entry were not imported. Thus I deleted all of these entries and all of a sudden I was able to import the contacts.

Now I wonder why the vcards are exported in a mixed format file and why leftover entries are not stripped from them. Thus, I suppose, problems like the one I experienced probably could be avoided by exporting a correctly formatted vcard file. Or should better the import process be changed?

Knut

**Comment by skjnldsv** [comment]
The nextcloud contact app/backend does not automatically edit/fix your vCard yet (we started implementing this recently, but we're not done yet). 
So if you imported apps before we put our vCard syntax restrictions, your cards may be invalid but still used by nextcloud (though editing them with the latest versions will probably mark them as invalid and reject your changes). You can edit them manually but you should treat each error as individual bug (multiple prodid...) the mixed version can't be fix as we don't provide an upgrade script.

**Comment by skjnldsv** [comment]
See #137 & #209
