### ISSUE TITLE
Telegram avatar contacts sync

### ISSUE THREAD

**Issue by Casuallynoted** [nextcloud/contacts#2393]
I really like the idea behind the "Update avatars from social media" feature for contacts. However, I don't believe it currently supports telegram, which natively adds telegram profile links to contacts on iOS. Is there a way that support could be added for this? I currently don't use Facebook and don't see a list anywhere of what other social networks the feature supports.

**Comment by call-me-matt** [comment]
Hi. I think it could work if you store the username (https://t.me/USERNAME). I don't think it works for phone numbers. Would that be sufficient?

**Comment by call-me-matt** [comment]
PS: currently supported networks:

* Madison
* Diaspora
* Gravatar
* Twitter
* Tumblr
* Instagram
* Xing

Broken:

* Facebook

**Comment by Casuallynoted** [comment]
> Hi. I think it could work if you store the username (https://t.me/USERNAME). I don't think it works for phone numbers. Would that be sufficient?

That would be great! II appreciate that you guys support Mastodon as well :) I've gone ahead and added the telegram urls for my contacts to the "Other social networks" option for now.

**Comment by call-me-matt** [comment]
I am planning to implement this finally.
Maybe `t.me` information is better in `messengers` > `Telegram` than `other social network` though.

**Comment by call-me-matt** [comment]
And it's released with contacts v5.1.0! :tada: 
[Screencast from 02.02.2023 21:13:23.webm](https://user-images.githubusercontent.com/34400929/216439901-84ed56f9-6c51-482a-a7ec-597098b2196b.webm)
