### ISSUE TITLE
Allow for not importing duplicate contacts when importing contacts

### ISSUE THREAD

**Issue by deefdragon** [nextcloud/contacts#2403]
**Is your feature request related to a problem? Please describe.**
When using the Nextcloud android app, my contacts are backed up daily. Opening one of the backup files causes the contacts app to import those contacts, which is great. 

The issue is if I do this again on another/the same contacts file, all the contacts are then duplicated.

**Describe the solution you'd like**
A setting to determine what to do when identical contacts, or contacts with the same name are encountered.

With identical, the options could be 

- rename duplicate
- add duplicate
- ignore
- ask each time

For ones that are not identical, but have the same name
- rename Old
- rename New
- Use Old
- Use New
- add contact with same name
- merge
- ignore
- ask each time

**Comment by skjnldsv** [comment]
Hi,

Duplicate contacts are rejected by the server if the UUID already exists.
If you backup is done properly, importing the same contact twice in the same address book will result in an error.

**Comment by deefdragon** [comment]
@skjnldsv that does not resolve the situation where the same contact is imported from a different devices' backup. A rare situation for it to be identical, but having the same name would be common enough.

**Comment by JL102** [comment]
> Hi,
> 
> Duplicate contacts are rejected by the server if the UUID already exists. If you backup is done properly, importing the same contact twice in the same address book will result in an error.

FYI: Importing from the same VCF file multiple times results in many duplicates.
