### ISSUE TITLE
Phone and E-mail "Type" settings don't display in Firefox

### ISSUE THREAD

**Issue by ghost** [nextcloud/contacts#2409]
### Steps to reproduce
1.Create a contact, including a phone number
2.Click on "Select Type" to the left of the phone number and specify "Work" (or any other type)
3.View in Firefox

### Expected behaviour
The phone number should have "Work" appear to the left of it.

### Actual behaviour
"Select type" is displayed is displayed to the left of the phone number, as if one had not been set. The same problem occurs with any other selected type, and with types for e-mail addresses. Tested most recently in Firefox 79, and has been the case in Firefox for at least a year, maybe much longer. The specified type displays properly in Chrome.

## Server configuration detail

**Operating system:** Linux 5.4.0-81-generic #91-Ubuntu SMP Thu Jul 15 19:09:17 UTC 2021 x86_64

**Webserver:** Apache/2.4.41 (Ubuntu) (apache2handler)

**Database:** mysql 8.0.26

**PHP version:** 

7.4.3
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, sodium, apache2handler, mysqlnd, PDO, xml, apcu, bcmath, calendar, ctype, curl, dom, mbstring, FFI, fileinfo, ftp, gd, gettext, gmp, iconv, imagick, intl, json, exif, memcache, mysqli, pdo_mysql, apc, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, xmlreader, xmlwriter, xsl, zip, Phar, Zend OPcache

**Nextcloud version:** 21.0.4 - 21.0.4.1

**Updated from an older Nextcloud/ownCloud or fresh install:** Have been through many update cycles. Started with 14.x when it was current.

**Where did you install Nextcloud from:** Downloaded from NextCloud web site.

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.7.0
 - activity: 2.14.3
 - admin_audit: 1.11.0
 - apporder: 0.13.0
 - calendar: 2.3.2
 - cloud_federation_api: 1.4.0
 - comments: 1.11.0
 - contacts: 4.0.2
 - contactsinteraction: 1.2.0
 - dashboard: 7.1.0
 - dav: 1.17.1
 - federatedfilesharing: 1.11.0
 - files: 1.16.0
 - files_markdown: 2.3.4
 - files_pdfviewer: 2.1.0
 - files_rightclick: 1.0.0
 - files_sharing: 1.13.1
 - files_trashbin: 1.11.0
 - files_versions: 1.14.0
 - files_videoplayer: 1.10.0
 - firstrunwizard: 2.10.0
 - groupfolders: 9.0.2
 - guests: 2.0.2
 - issuetemplate: 0.7.0
 - logreader: 2.6.0
 - lookup_server_connector: 1.9.0
 - mail: 1.10.3
 - nextcloud_announcements: 1.10.0
 - notes: 4.1.1
 - notifications: 2.9.0
 - oauth2: 1.9.0
 - password_policy: 1.11.0
 - phonetrack: 0.6.9
 - photos: 1.3.0
 - previewgenerator: 3.1.1
 - privacy: 1.5.0
 - provisioning_api: 1.11.0
 - serverinfo: 1.11.0
 - settings: 1.3.0
 - sharebymail: 1.11.0
 - spreed: 11.3.1
 - survey_client: 1.9.0
 - systemtags: 1.11.0
 - tasks: 0.14.1
 - text: 3.2.0
 - theming: 1.12.0
 - twofactor_backupcodes: 1.10.0
 - updatenotification: 1.11.0
 - user_status: 1.1.1
 - viewer: 1.5.0
 - weather_status: 1.1.0
 - workflowengine: 2.3.0
Disabled:
 - encryption
 - external
 - federation
 - files_accesscontrol
 - files_external
 - gallery
 - impersonate
 - recommendations
 - support
 - user_ldap
 - workflow_script

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "localhost",
        "***REMOVED SENSITIVE VALUE***",
        "nextcloud.silverflash.net",
        "192.168.***REMOVED SENSITIVE VALUE***"
    ],
    "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "http:\/\/localhost",
    "overwriteprotocol": "https",
    "overwritehost": "nextcloud.silverflash.net",
    "dbtype": "mysql",
    "default_phone_region": "US",
    "version": "21.0.4.1",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "smtp",
    "mail_smtpauthtype": "LOGIN",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "25",
    "maintenance": false,
    "loglevel": 0,
    "memcache.local": "\\OC\\Memcache\\APCu",
    "trashbin_retention_obligation": 15,
    "updater.release.channel": "stable",
    "theme": "",
    "log_type": "syslog",
    "logtimezone": "America\/Los_Angeles",
    "data-fingerprint": "48986e3741f6036d8afe2eec916c5fec",
    "app_install_overwrite": [
        "gallery",
        "phonetrack",
        "issuetemplate"
    ],
    "mail_sendmailmode": "smtp"
}
```
</details>

**Are you using external storage, if yes which one:** /var/www/nextcloud/data is a symbolic link to /usr/local/nextcloud/data, which is a dedicated LVM volume to permit better space management.

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** No

## Client configuration

**Browser:** Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:79.0) Gecko/20100101 Firefox/79.0

**Operating system:** Ubuntu 20.04

## Logs

<details><summary>Web server error log</summary>

```
192.168.xxx.xxx - - [26/Aug/2021:09:39:48 -0700] "PROPFIND /remote.php/dav/addressbooks/users/xxx/contacts/xxx.vcf HTTP/1.1" 207 6185 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:79.0) Gecko/20100101 Firefox/79.0"
[ sensitive information replaced with "xxx" ]

```
</details>

<details><summary>Nextcloud log</summary>

```
(none)
```
</details>

<details><summary>Browser log</summary>

</details>

**Comment by GVodyanov** [comment]
Thanks for reporting! Works now!
