### ISSUE TITLE
Imported vCard Org contacts are all displayed as "New Contact"

### ISSUE THREAD

**Issue by liamdennehy** [nextcloud/contacts#241]
### Steps to reproduce
1. Import vCards that include Organisations (so no given/surname)

### Expected behaviour
Display name/title should be the organisation name (probably "FN" property?)

### Actual behaviour
"FN" property is set to "New contact", so all organisational contacts are titled "New contact". Note that vCard (exported from G Suite/Google) have FN: field, but it is empty, so "New contact" is being explicitly generated and populated in the cards_properties table. "N" field is also a sequence of four semicolons, since no personal names are present in the export.

**Nextcloud version: 12

**Contacts version: 1.5.3

**Comment by skjnldsv** [comment]
Well, a vcard without a FN value is not rfc compliant and therefore, invalid 😉
https://tools.ietf.org/html/rfc6350#section-6.2.1

Can you provide a vcard example please?

**Comment by talmage** [comment]
Here is an example. 

BEGIN:VCARD
ADR:;;405 8th ST NW;Washington;DC;20004;USA
EMAIL:info@cafeatlantico.com
LABEL:405 8th ST NW\, 20004 Washington\, DC\, USA
N:;;;;
ORG:Cafe Atlantico
TEL;TYPE=VOICE:2023930812
UID:3554
URL:www.cafeatlantico.com
VERSION:3.0
REV:20120715T035621Z
END:VCARD

**Comment by talmage** [comment]
I recently switched from [DAViCal](https://www.davical.org/index.php), doesn't exhibit this behavior, to Nextcloud, which does.  With DAViCal, my desktop client, Kaddressbook, displayed the organization as the name for vcards like the one I posted above.  With Nextcloud, Kaddressbook displays "New Contact" for such vcards.

Strangely, the default Android Contacts app displays the organization name when there is no personal  name.

**Comment by irgendwie** [comment]
@talmage The problem is, that the VCARD states itself as VERSION:3.0 - still beginning with version 3.0 the FN property is a mandatory property but missing in your example vcard as stated by @skjnldsv. I'll write a patch, which handles your case.

**Comment by talmage** [comment]
@irgendwie Thank you.
