### ISSUE TITLE
User manual link broken (stable)

### ISSUE THREAD

**Issue by Pada0** [nextcloud/contacts#2421]
Hello there,

Here :
https://apps.nextcloud.com/apps/contacts
the link to user manual :
https://docs.nextcloud.com/server/stable/user_manual/pim/contacts.html
is broken and should be replace by : 
https://docs.nextcloud.com/server/19/user_manual/pim/contacts.html

Don't know if it is a nextcloud.com repository issue.

P.

**Comment by skjnldsv** [comment]
https://docs.nextcloud.com/server/stable/user_manual/en/pim/contacts.html

**Comment by Pada0** [comment]
The link still broken :
https://docs.nextcloud.com/server/stable/user_manual/pim/contacts.html
