### ISSUE TITLE
Several contacts couldnt be imported

### ISSUE THREAD

**Issue by KDropZ** [nextcloud/contacts#2430]
### Describe the bug
I tried to import my contacts.vcf into the contact tab of my NextCloud. Many contacts went well but on some just failed (screenshot).
Browser console log:
"/remote.php/dav/addressbooks/users/XXX/kontakte/403968CF-0E25-4D92-8511-A39642C2F1F8.vcf?photo:1 Failed to load resource: the server responded with a status of 404 ()"
This Error all along.

I use this https://www.qnapclub.eu/en/qpkg/348 repo on my QNAP TS X53. Everything works well with my Nextcloud, so I think the compatibility should be fine.

"Completed the import of 110 contacts - 15 Failed"
![nextcloud](https://user-images.githubusercontent.com/77630187/132899440-d88d71f6-0964-4bb2-ac3c-b5675992a897.PNG)

**Comment by miaulalala** [comment]
Hi, could you please post the server logs for this?

**Comment by joshtrichards** [comment]
Closing due to lack of additional information needed to triage after 3 years. Feel free to re-open/revisit if this occurs again.
