### ISSUE TITLE
Continous error in cronjob: 'Error: Undefined array key "PHOTO"'

### ISSUE THREAD

**Issue by adi-dev** [nextcloud/contacts#2438]
I see in my logs, every cronjob:
```
Error: Undefined array key "PHOTO" at /var/www/nextcloud/apps/contacts/lib/Service/SocialApiService.php#232
    /var/www/nextcloud/apps/contacts/lib/Service/SocialApiService.php - line 232:
    OC\Log\ErrorHandler::onError()
    /var/www/nextcloud/apps/contacts/lib/Service/SocialApiService.php - line 409:
    OCA\Contacts\Service\SocialApiService->updateContact("*** sensiti ... *")
    /var/www/nextcloud/apps/contacts/lib/Cron/SocialUpdate.php - line 49:
    OCA\Contacts\Service\SocialApiService->updateAddressbooks("*** sensiti ... *")
    /var/www/nextcloud/lib/private/BackgroundJob/Job.php - line 51:
    OCA\Contacts\Cron\SocialUpdate->run()
    /var/www/nextcloud/lib/private/BackgroundJob/QueuedJob.php - line 45:
    OC\BackgroundJob\Job->execute()
    /var/www/nextcloud/cron.php - line 127:
    OC\BackgroundJob\QueuedJob->execute()
```
Not sure, what and why this is happening.

NC 22.1.1
Linux Ubuntu
PHP 8.0.10, Memory Limit 4GB, Max Execution Time 3600, Upload max size 100MB
PostgreSQL 12.8
Contacts app: 4.0.3

**Comment by call-me-matt** [comment]
Hi.
I wrote these lines. It's the background job that searches for contact pictures on social networks.
But I do not see this error in my logs. And I do not know why it's happening for you.

**Comment by adi-dev** [comment]
@call-me-matt, is there any way to help, debug?

**Comment by call-me-matt** [comment]
Currently I do not have an idea, maybe someone more experienced in PHP can take a look?

**Comment by miaulalala** [comment]
An isset check on `$changes` in 
https://github.com/nextcloud/contacts/blob/27354f1922c8df20f007501d3ca8bf7145813809/lib/Service/SocialApiService.php#L232

might help.

**Comment by call-me-matt** [comment]
same as https://github.com/nextcloud/contacts/issues/2532 and fixed by https://github.com/nextcloud/contacts/pull/2533 ?
