### ISSUE TITLE
Contact list sorting

### ISSUE THREAD

**Issue by Sargastic** [nextcloud/contacts#245]
Using NC 11

The contacts list seems to be always sorted by First Name / Last Name (or company if no name is provided). It should be possible to sort by Last Name / First Name.

**Comment by skjnldsv** [comment]
Please see in the settings part.
![kazam_screenshot_00000](https://user-images.githubusercontent.com/14975046/27625458-fed0b434-5be4-11e7-8969-86eabd5d57b7.png)

**Comment by Sargastic** [comment]
Weird. I do not have this parameter (cannot add image here, probably because account is too young). There is nothing under the "Import" function.

Did I mess something during install ?

**Comment by skjnldsv** [comment]
You must be on an old version :)

**Comment by Sargastic** [comment]
It's an 11.0.3 release.

**Comment by Sargastic** [comment]
Okay, just check, I thought 11.0.3 was the latest. Upgrading to 12.0 very soon, will keep you informed (hoping it will close my rant, of course).

**Comment by Sargastic** [comment]
Sorry, but NC 12.0.0, Contact 1.5.3, still no 'Sort by' in the Contact parameters box.
