### ISSUE TITLE
Multiple adressbooks and import

### ISSUE THREAD

**Issue by ThomasAusSinsheim** [nextcloud/contacts#246]
### Steps to reproduce
1. Create more than one adressbooks
2. Import more than one adressbooks in the format of .vcf (the .vcf file contains a list of contacts)

### Expected behaviour
During the import I expect a request to which adressbook the .vcf list should be assigned.

### Actual behaviour
The importet contacts will be assigned to the first created adressboks

### Server configuration
**Operating system**:
Raspbian Jessie (Debian 8)
**Web server:**
apache2 2.4
**Database:**
MySql
**PHP version:**
5.6
**Nextcloud version:** (see Nextcloud admin page)
12.0.0
**Contacts version:** (see Nextcloud apps page)
1.5.3
**Updated from an older Nextcloud or fresh install:**
fresh install
**Signing status:**
No errors have been found

**List of activated apps:**
Enabled:
  - activity: 2.5.2
  - bruteforcesettings: 1.0.2
  - calendar: 1.5.3
  - comments: 1.2.0
  - contacts: 1.5.3
  - dav: 1.3.0
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_pdfviewer: 1.1.1
  - files_reader: 1.0.4
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - mail: 0.6.4
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - ownbackup: 17.5.0
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - quota_warning: 1.0.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - tasks: 0.9.5
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - weather: 1.4.2
  - workflowengine: 1.2.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_external
  - user_ldap

**Nextcloud configuration:**
{
    "system": {
        "datadirectory": "\/media\/USB-DATA\/owncloud\/120\/data",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "logfile": "\/var\/log\/owncloud.log",
        "log_type": "owncloud",
        "logtimezone": "Europe\/Berlin",
        "loglevel": 1,
        "instanceid": "oc07gsahnd45",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "meister",
            "meister.fritz.box",
            "192.168.1.211",
            "mittermueller-online.de",
            "wolke.dynvpn.de"
        ],
        "overwrite.cli.url": "https:\/\/192.168.1.211\/owncloud",
        "dbtype": "sqlite3",
        "version": "12.0.0.29",
        "installed": true,
        "mail_from_address": "owncloud",
        "mail_smtpmode": "php",
        "mail_smtpauthtype": "LOGIN",
        "mail_domain": "localhost",
        "maintenance": false
    },
    "apps": {
        "activity": {
            "installed_version": "2.5.2",
            "types": "filesystem",
            "enabled": "yes"
        },
        "backgroundjob": {
            "lastjob": "14"
        },
        "bruteforcesettings": {
            "installed_version": "1.0.2",
            "enabled": "yes",
            "types": ""
        },
        "calendar": {
            "installed_version": "1.5.3",
            "enabled": "yes",
            "types": ""
        },
        "comments": {
            "installed_version": "1.2.0",
            "types": "logging",
            "enabled": "yes"
        },
        "contacts": {
            "installed_version": "1.5.3",
            "enabled": "yes",
            "types": ""
        },
        "core": {
            "installedat": "1498330670.8432",
            "lastupdatedat": "1498587159",
            "vendor": "nextcloud",
            "public_files": "files_sharing\/public.php",
            "public_webdav": "dav\/appinfo\/v1\/publicwebdav.php",
            "installed.bundles": "[\"CoreBundle\"]",
            "oc.integritycheck.checker": "[]",
            "scss.variables": "b94476925f12dd2453a199f7e244cd69",
            "lastcron": "1498367490",
            "lastupdateResult": "[]",
            "backgroundjobs_mode": "cron",
            "shareapi_enforce_links_password": "yes",
            "shareapi_allow_resharing": "no",
            "shareapi_allow_group_sharing": "no"
        },
        "dav": {
            "installed_version": "1.3.0",
            "types": "filesystem",
            "enabled": "yes"
        },
        "federatedfilesharing": {
            "installed_version": "1.2.0",
            "types": "",
            "enabled": "yes"
        },
        "federation": {
            "installed_version": "1.2.0",
            "types": "authentication",
            "enabled": "yes"
        },
        "files": {
            "installed_version": "1.7.2",
            "types": "filesystem",
            "enabled": "yes",
            "cronjob_scan_files": "500"
        },
        "files_pdfviewer": {
            "installed_version": "1.1.1",
            "ocsid": "166049",
            "types": "",
            "enabled": "yes"
        },
        "files_reader": {
            "installed_version": "1.0.4",
            "enabled": "yes",
            "types": "filesystem"
        },
        "files_sharing": {
            "installed_version": "1.4.0",
            "types": "filesystem",
            "enabled": "yes",
            "outgoing_server2server_share_enabled": "no",
            "incoming_server2server_share_enabled": "no",
            "lookupServerUploadEnabled": "no"
        },
        "files_texteditor": {
            "installed_version": "2.4.1",
            "ocsid": "166051",
            "types": "",
            "enabled": "yes"
        },
        "files_trashbin": {
            "installed_version": "1.2.0",
            "types": "filesystem",
            "enabled": "yes"
        },
        "files_versions": {
            "installed_version": "1.5.0",
            "types": "filesystem",
            "enabled": "yes"
        },
        "files_videoplayer": {
            "installed_version": "1.1.0",
            "types": "",
            "enabled": "yes"
        },
        "firstrunwizard": {
            "installed_version": "2.1",
            "types": "logging",
            "enabled": "yes"
        },
        "gallery": {
            "installed_version": "17.0.0",
            "types": "",
            "enabled": "yes"
        },
        "logreader": {
            "installed_version": "2.0.0",
            "ocsid": "170871",
            "types": "",
            "enabled": "yes",
            "levels": "01111"
        },
        "lookup_server_connector": {
            "installed_version": "1.0.0",
            "types": "authentication",
            "enabled": "yes"
        },
        "mail": {
            "installed_version": "0.6.4",
            "enabled": "yes",
            "types": ""
        },
        "nextcloud_announcements": {
            "installed_version": "1.1",
            "types": "logging",
            "enabled": "yes",
            "pub_date": "Sat, 10 Dec 2016 00:00:00 +0100"
        },
        "notifications": {
            "installed_version": "2.0.0",
            "types": "logging",
            "enabled": "yes"
        },
        "oauth2": {
            "installed_version": "1.0.5",
            "types": "authentication",
            "enabled": "yes"
        },
        "ownbackup": {
            "installed_version": "17.5.0",
            "enabled": "yes",
            "types": ""
        },
        "password_policy": {
            "installed_version": "1.2.2",
            "types": "",
            "enabled": "yes",
            "minLength": "6",
            "enforceNonCommonPassword": "0"
        },
        "provisioning_api": {
            "installed_version": "1.2.0",
            "types": "prevent_group_restriction",
            "enabled": "yes"
        },
        "quota_warning": {
            "installed_version": "1.0.0",
            "enabled": "yes",
            "types": "filesystem"
        },
        "serverinfo": {
            "installed_version": "1.2.0",
            "types": "",
            "enabled": "yes"
        },
        "sharebymail": {
            "installed_version": "1.2.0",
            "types": "filesystem",
            "enabled": "yes",
            "sendpasswordmail": "no"
        },
        "survey_client": {
            "installed_version": "1.0.0",
            "types": "",
            "enabled": "yes"
        },
        "systemtags": {
            "installed_version": "1.2.0",
            "types": "logging",
            "enabled": "yes"
        },
        "tasks": {
            "installed_version": "0.9.5",
            "enabled": "yes",
            "types": ""
        },
        "theming": {
            "installed_version": "1.3.0",
            "types": "logging",
            "enabled": "yes",
            "name": "OwnCloud",
            "cachebuster": "1"
        },
        "twofactor_backupcodes": {
            "installed_version": "1.1.1",
            "types": "",
            "enabled": "yes"
        },
        "updatenotification": {
            "installed_version": "1.2.0",
            "types": "",
            "enabled": "yes"
        },
        "weather": {
            "installed_version": "1.4.2",
            "enabled": "yes",
            "types": ""
        },
        "workflowengine": {
            "installed_version": "1.2.0",
            "types": "filesystem",
            "enabled": "yes"
        }
    }
}

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Client configuration
Firefox 54.0 (64 bit)
**Operating system:**
W10

**CardDAV-clients:**
does not matter
#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
not possible to edit the logfile

**Comment by skjnldsv** [comment]
Duplicate #55 
see #123
