### ISSUE TITLE
Exclude Contacts from Birthday-Calendar

### ISSUE THREAD

**Issue by newhinton** [nextcloud/contacts#2464]
**Is your feature request related to a problem? Please describe.**
Sometimes there are contacts that do have birthdays saved, but a user might not care about them in their calendar. (Old Friends, Coworkers, etc)

**Describe the solution you'd like**
I'd like the ability to exclude them from the automatic generation of the birthday-calendar, without having to delete the actual birthday from the contact. There is already a three-dot menu in the ui, it could be added there as a simple button.

**Comment by sylvainmetayer** [comment]
Hi, I'd like to work on this feature.

From what I've seen, we need to add a button to exclude/include the contact into the birthday calendar in the three-dot ui as you mentioned, and we need to handle the inclusion/exclusion in the BirthdayService (https://github.com/nextcloud/server/blob/master/apps/dav/lib/CalDAV/BirthdayService.php).

My question is do we need to add a new property "exclude_from_birthday_calendar" to the vcard data or is there another way to handle this ?

**Comment by miaulalala** [comment]
@sylvainmetayer you can add a custom property formatted like X-NC-YOUR-PROPERTY-NAME. You could then modify the cardData on saving via the exclude button to add this property, and then look for this property before returning.

If you want to get stuck in, tag me and I'll look over your PR.

If you get stuck or want to stay in touch, you can join us on on the Developer Chat - send me an email at anna.larch@nextcloud.com and I'll organize one for you 😊

**Comment by sylvainmetayer** [comment]
Thanks @miaulalala for the help !

I've pushed the 2 PR as drafts for now. 

For the server side, their is not much more to do, I just need to see how to write the test for this one.

For the contacts side, I'm not sure I did this right and I need to write tests before submitting this one.

**Comment by sylvainmetayer** [comment]
It seems this issue has been closed however the contacts PR is still open. Should we reopen it until it is merged?

**Comment by simsonfahrer** [comment]
Hi there,
would it be possible to allow the same feature for multiple contacts at once?
For example, selecting all contacts of one group, or just select multiple contacts and then check those to exclude from birthday calendar?
For touching every single contact I would need hours...
Thanks and Regards

**Comment by st3iny** [comment]
@simsonfahrer No, that is not possible.
