### ISSUE TITLE
Unified search: provide proper thumnail url

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/contacts#2470]
```
http://localhost/nc/ocs/v2.php/search/providers/contacts/search
```

does not provide thumbnailUrl, but it could show a correct preview of the note.

**Comment by tobiasKaminsky** [comment]
😢 please not :-)

**Comment by ChristophWurst** [comment]
is there any context to this report? is this a bug report?

**Comment by ChristophWurst** [comment]
It's set if available https://github.com/nextcloud/server/blob/75857db49da7a45c0580666263e19c9ea2f7269b/apps/dav/lib/Search/ContactsSearchProvider.php#L142-L151

**Comment by tobiasKaminsky** [comment]
Thanks, I was (again) mixing up address book and users, so I searched for an user who had an avatar, but was only in local address book without avatar.
