### ISSUE TITLE
Display errors / names are missing

### ISSUE THREAD

**Issue by Mululu** [nextcloud/contacts#2473]
### Describe the bug
If contacts are shared with several users individually, the names are no longer displayed. So you don't know with whom something is shared or who has which permissions.

**To Reproduce**
Share contacts with multiple users

**Expected behavior**
Names are still legible

**Actual behavior**
Names can no longer be read

**Screenshots**
![image](https://user-images.githubusercontent.com/5918495/138411185-08304777-2e6b-4c1e-aa78-e6ab6d78bf3a.png)

**Comment by nursoda** [comment]
I just ran into the same issue. A crude workaround is to use context menu → "Query (Q)" on the user icon in Firefox. One may deduct the user/group name from the source code view…

Apart from the UX issue, there's also some translation issue here… "Einstellungen" is in German, "Add new address book" is not.

**Comment by ChristophWurst** [comment]
Dup of https://github.com/nextcloud/contacts/issues/2495. @GretaD is working on this :)
