### ISSUE TITLE
Checkbox to hide/show contacts of a specific adressbook

### ISSUE THREAD

**Issue by ThomasAusSinsheim** [nextcloud/contacts#248]
In eralier issues of NC or OC it was possible to fade out all contacts of an adressbook. This was very helpful to keep the overview. I miss this option very much.

**Comment by skjnldsv** [comment]
Hi! What exactly are you calling "fading out"? :)

**Comment by ThomasAusSinsheim** [comment]
Using Owncloud up to 8.2 it was possible to set a check box and the contacts of this addressbook were shown in the list. When the checkbox was not set, the contacts of the related addressbooks were hidden. So it was possible to show/see only the contacts of a special addressbook. This was very helpful to administrate all addressbooks and contatcs.

![2017-06-28 21_33_52-choose an addressbook](https://user-images.githubusercontent.com/29738467/27656705-45490dac-5c4a-11e7-8c42-f130d5b13218.png)

**Comment by tuxlama** [comment]
Hello,
it is any chance to implements 

>  possible to set a check box and the contacts of this address book were shown in the list.

and thank you for a NC great app

**Comment by skjnldsv** [comment]
Duplicate #36
