### ISSUE TITLE
NextCloud User Group as Contact Group

### ISSUE THREAD

**Issue by financelurker** [nextcloud/contacts#2485]
We use our NextCloud instance to keep track of all our contacts (and even import them to Thunderbird via TbSync). So, the contacts we manage in the contacts app are exposed via CardDAV, but the NextCloud users themselves are not. And we have to manually add each user to a dedicated shared contact group each time a new user gets created.

Let administrators define a shared contact group, automatically containing all NextCloud users, so they automatically get exposed via CardDAV.

Alternatively:
Expose each Circle/User Group a NextCloud user is member of via CardDAV (so they can choose which group to sync within TB/any other CardDAV client).

Is there any possibility for that?

**Comment by ChristophWurst** [comment]
I think https://github.com/nextcloud/server/issues/13478 touches on this.
