### ISSUE TITLE
Cannot Download Groups

### ISSUE THREAD

**Issue by tdoerschel** [nextcloud/contacts#2486]
Hi,

when I click on the ... -> Download option of a group of contacts, nothing happens.
Tested on 2 NC instances with server 22.2.0 and contacts 4.0.3, PHP 8 FPM, Postgresql and MariaDB
Browsers Chrome and Firefox (latest versions)

![image](https://user-images.githubusercontent.com/46196223/140052740-2922bcf6-64b7-4f58-9755-ab86e3ef7cc6.png)

Can others confirm this bug?

**Comment by ChristophWurst** [comment]
dup of https://github.com/nextcloud/contacts/issues/2345
