### ISSUE TITLE
Blank page with v4.0.4

### ISSUE THREAD

**Issue by Crashone** [nextcloud/contacts#2488]
**Description**
Since 4.0.4 upgrade, Contacts shows a blank page.

**Operating system**: Ubuntu 21.10

**Web server:** Apache

**Database:** MySQL 

**PHP version:**
 8.0

**Nextcloud version:** 
22.2

**Contacts version:** 4.0.4
**Updated from an older Nextcloud**

**Signing status:**

No errors have been found.

**List of activated apps:**
Enabled:
  - accessibility: 1.8.0
  - activity: 2.15.0
  - announcementcenter: 6.0.0
  - apporder: 0.13.0
  - approval: 1.0.7
  - audioplayer: 3.2.2
  - bruteforcesettings: 2.2.0
  - calendar: 2.3.4
  - circles: 22.1.1
  - cloud_federation_api: 1.5.0
  - comments: 1.12.0
  - contacts: 4.0.4
  - contactsinteraction: 1.3.0
  - dashboard: 7.2.0
  - dav: 1.19.0
  - deck: 1.5.3
  - external: 3.9.0
  - federatedfilesharing: 1.12.0
  - federation: 1.12.0
  - files: 1.17.0
  - files_pdfviewer: 2.3.0
  - files_rightclick: 1.1.0
  - files_sharing: 1.14.0
  - files_trackdownloads: 1.11.0
  - files_trashbin: 1.12.0
  - files_versions: 1.15.0
  - files_videoplayer: 1.11.0
  - firstrunwizard: 2.11.0
  - geoblocker: 0.5.1
  - integration_google: 1.0.3
  - logreader: 2.7.0
  - lookup_server_connector: 1.10.0
  - mail: 1.10.5
  - maps: 0.1.9
  - nextcloud_announcements: 1.11.0
  - notifications: 2.10.1
  - oauth2: 1.10.0
  - password_policy: 1.12.0
  - photos: 1.4.0
  - privacy: 1.6.0
  - provisioning_api: 1.12.0
  - quota_warning: 1.11.0
  - recommendations: 1.1.0
  - richdocuments: 4.2.3
  - riotchat: 0.9.9
  - serverinfo: 1.12.0
  - settings: 1.4.0
  - sharebymail: 1.12.0
  - side_menu: 1.28.0
  - spreed: 12.1.2
  - support: 1.5.0
  - survey_client: 1.10.0
  - suspicious_login: 4.0.0
  - systemtags: 1.12.0
  - tasks: 0.14.2
  - text: 3.3.0
  - theming: 1.13.0
  - twofactor_admin: 3.1.0
  - twofactor_backupcodes: 1.11.0
  - twofactor_gateway: 0.19.0
  - updatenotification: 1.12.0
  - user_status: 1.2.0
  - viewer: 1.6.0
  - weather_status: 1.2.0
  - workflowengine: 2.4.0
Disabled:
  - admin_audit
  - encryption
  - files_downloadactivity
  - files_external
  - user_ldap

**Nextcloud configuration:**

{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.crashone.net"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "22.2.0.2",
        "overwrite.cli.url": "https:\/\/cloud.crashone.net\/",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "default_phone_region": "FR",
        "htaccess.RewriteBase": "\/",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "maintenance": false,
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "theme": "",
        "loglevel": 2
    }
}

Client configuration
**Browser:**
Firefox 93
**Operating system:**
Arch Linux

**Comment by cm-schl** [comment]
Can confirm this issue on Nextcloud 21.0.5 - the Contacts Page remains empty after the update to 4.0.4.
Tested also with Google Chrome - same issue.

CardDAV synchronization with Thunderbird (Cardbook) works perfectly.

**Comment by acsfer** [comment]
Confirmed, browser console shows:

> Refused to execute script from 'https://example.com/apps/contacts/js/contacts-main.js?v=952c108f-4' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.

**Comment by m8ichael** [comment]
Same problem here.

**Comment by ChristophWurst** [comment]
My bad. Let me push a 4.0.5.

**Comment by MrLoverLoverMMMM** [comment]
I have the same issue with Chrome Browser and NC 22.2.

**Comment by MrLoverLoverMMMM** [comment]
I have the same issue with Chrome Browser and NC 22.2.

**Comment by ChristophWurst** [comment]
Please update to https://github.com/nextcloud-releases/contacts/releases/tag/v4.0.5

**Comment by ChristophWurst** [comment]
Ironic how in 4.0.4 files were missing, huh …

**Comment by ChristophWurst** [comment]
https://github.com/nextcloud/contacts/issues/2489 I did it another time because apparently the wrong .tar.gz was uploaded …

**Comment by WNYmathGuy** [comment]
I feel like a real knob/noob, but I'm running two instances of Nextcloud 22 on the same physical server. I typically update the apps about the same time, but somehow one is still stuck in Contacts 4.0.4, and the other is in 4.0.6 so obviously I have the blank screen on one and contacts working fine on the other.

The one stuck in 4.0.4 was a fresh install of NC 22 using the no brainer web install trick, and the other one was a server first set-up as a NC12 site. I've never tried to force a update of an app before it got suggested in the point and click system, and I rarely do the occ commands so can't remember how to force it to be the 4.0.6, so anybody want to include a link to the recipie for forcing the upgrade?

**Comment by ChristophWurst** [comment]
No need to force anything. Just install the update via the app management page ;-)

**Comment by cm-schl** [comment]
Hi,

in fact this happens also to me: Nextcloud does not offer me the possibility to update via the app management page. I see that Contacts has got a new version in the changelog of the app, but I'm stuck on 4.0.4.

So maybe a `php occ app:update contacts` directly on the server should do the trick?
See: https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/occ_command.html?highlight=occ#apps-commands

**Comment by WNYmathGuy** [comment]
> Nextcloud does not offer me the possibility to update via the app management page.

Right, that's why I posted. I couldn't understand why the two instances on the same physical server were acting differently. Only the install method and starting NC version were different. Same virtual server, same PHP version and method.

**Comment by ChristophWurst** [comment]
Okay, my bad. I was not aware that the app store would not send out the update in some cases.

If I look at https://apps.nextcloud.com/api/v1/platform/22.2.0/apps.json then it shows that the app store advertises the release of v4.0.5 and v4.0.6

![Bildschirmfoto von 2021-11-08 14-39-25](https://user-images.githubusercontent.com/1374172/140751936-71a918d0-6ba2-4de6-8887-146b6cbb853b.png)

What's the precise version that you are on? 22.2.0 or older?

**Comment by cm-schl** [comment]
I'm on 21.0.5 and checked the file https://apps.nextcloud.com/api/v1/platform/21.0.5/apps.json - this looks ok.

@skjnldsv - thanks for the hint, I will check this!

**Comment by WNYmathGuy** [comment]
> Okay, my bad. I was not aware that 
> What's the precise version that you are on? 22.2.0 or older?

Both my instances are NC 22.2.0. That's why I found it puzzling. The insurance that didn't update part contacts 4.0.4 is the one that was a clean install to next cloud 22. I used a new type of installer from next cloud for fun where you just put one single file in the web directory open by going to the URL of your intended instance and boom a bunch of magic happens. Should have been the same NC no matter which way you install it but that's the only difference I know between the two instances I run.

**Comment by WNYmathGuy** [comment]
> Locally cached apps.json file might take some time to update.
> You can delete it from appdata/appstore and open the apps management page to fetch update

![jsonStatus](https://user-images.githubusercontent.com/28640985/140790257-681a29d1-3f97-470c-8f00-4f3aa88f80fc.png)

I'm thinking that the JSON file is updated but for some reason, the `.com/index.php/settings/apps/installed` doesn't have the upgrade appearing.

**Comment by ChristophWurst** [comment]
They are not unstable. There is a nightly additional to the latest release. You can compare with other apps.

**Comment by WNYmathGuy** [comment]
> They are not unstable. There is a nightly additional to the latest release. You can compare with other apps.

I assumed they were stable, but wondered if that mismarking of them is why my one instance isn't getting to see the updated version.

**Comment by WNYmathGuy** [comment]
"[Aw man, aw jeez Rick](https://duckduckgo.com/?q=aw+jeez+Rick&t=ffcm&iax=images&ia=images)"

So, I'm currently away from home and can't find a way to do a terminal command of `php occ app:update contacts`. I tried a few things like making it into a cron job, but it's not firing as far as I can tell. It might be, but it's not seeing version 4.0.6 somehow.

I did try deleting the `apps.json` file and running the apps UI page, but it never saw the update. The `.com/index.php/settings/apps` is working though because the latest upgrade to the "Announcements" app came in.

I hate to be an edge-case, but normal problems never post on GitHub, right?

What's the best practice for me forcing the update? Delete the contents of `/www/html/apps/contacts` then unpack a contacts 4.0.6 edition `https://github.com/nextcloud-releases/contacts/releases/download/v4.0.6/contacts.tar.gz` in the folder?

**Comment by nunesgh** [comment]
> What's the best practice for me forcing the update?

This is something I would also like to know. I have tried to run `sudo -u www-data php occ app:update contacts` on my instance with no success. I am still stuck at version 4.0.4 and I am experiencing the same blank page issue.

**Comment by WNYmathGuy** [comment]
Not sure if this is just a red-herring, or a significant thing, but when I try to open my `oc_cards` table for Browse mode in a phpMyAdmin environment it throws an error.
![BrowseErrorCardsTable](https://user-images.githubusercontent.com/28640985/141200969-e0df301f-516f-4740-94d5-12bec014a4f9.png)

I'm simultaneously trying to bug report to Polls and starting to think it's a [PEBCAK ](https://en.wiktionary.org/wiki/PEBCAK) type bug. Maybe it's normal that phpMyAdmin can't display it?

**Comment by WNYmathGuy** [comment]
> > What's the best practice for me forcing the update?
> 
> This is something I would also like to know. I have tried to run `sudo -u www-data php occ app:update contacts` on my instance with no success. I am still stuck at version 4.0.4 and I am experiencing the same blank page issue.

I think it's `extracting downloaded package to the apps folder` based on what I saw in the template for a bug report I'm filing in the Polls app right now.
So, set maintenance mode on, rename the current `contacts` folder or move it out of its current location of your web server's space, then extract the downloaded version into the subfolder for `apps`, turn off maintenance mode.

**Comment by ChristophWurst** [comment]
I'm still clueless why this happens for some of you. It doesn't seem to be a general issue because according to the github download stats the 4.0.6 release has been downloaded 13k times. I don't think that many admins updated manually ;-)

**Comment by WNYmathGuy** [comment]
> clueless why this happens for some of you

Right, and in my case two similarly created Virtual Servers on the exact same 2U rack server takes away a lot of variables. And that other apps update fine on both NC22 instances.

It's not obvious so I'll ask, should I expect contacts to upgrade normally in the future after the forcing?

**Comment by WNYmathGuy** [comment]
> I'm still clueless why this happens for some of you.

I had one thought come up yesterday. Despite having both instances on the same server, I recalled that the older one, because of unique circumstances, is connecting to a MySQL server on another rack in the LAN. This problematic new one is connecting to the local MariaDB database. My base server is Ubuntu 18.04, but I decided on my own to run the updated databases on both 

The MySQL is version 8.0.25, and the MariaDB version is 10.5.6, so that might be a possible reason?

**Comment by bertrand-benoit** [comment]
I have got exactly the same issue with Nextcloud 21. Stuck with empty-page- v4.0.4 Contacts version application.
`php occ app:update contacts` or removing cache file does nothing.

**Comment by cm-schl** [comment]
Yes, I can confirm that this steps didn't help to resolve the problem - but the steps provided by WNYmathGuy to do a manual update work perfectly.

**Comment by ChristophWurst** [comment]
I've checked https://github.com/nextcloud/server/issues for any similar requests because it's mostly code in server that fetches or doesn't fetch an update. Maybe one of you is more successful with the search terms.

> The MySQL is version 8.0.25, and the MariaDB version is 10.5.6, so that might be a possible reason?

Does it happen only on MariaDB instances? What do you all use?

**Comment by codeling** [comment]
Same issue (no update to 4.0.5/6 offered) happens on my installation too. Using MariaDB version 10.4.22...

**Comment by nunesgh** [comment]
> I'm still clueless why this happens for some of you. It doesn't seem to be a general issue because according to the github download stats the 4.0.6 release has been downloaded 13k times. I don't think that many admins updated manually ;-)

@ChristophWurst, the weirdest thing is that, at least on my instance of Nextcloud, this issue is only happening with the Contacts app. The other apps are receiving updates as expected.

**Comment by nunesgh** [comment]
> Does it happen only on MariaDB instances? What do you all use?

**Operating system**: Debian 10

**Web server:** Apache 2.4.38

**Database:**  MySQL 10.3.31

**PHP version:** 7.3.31

**Nextcloud version:** 22.2.3

**Contacts version:** 4.0.4

**Updated from an older Nextcloud or fresh install:** Updated.

**Signing status:**
```
No errors have been found.
```

**List of activated apps:**
```
Enabled:
  - accessibility: 1.8.0
  - activity: 2.15.0
  - admin_audit: 1.12.0
  - apporder: 0.13.0
  - bruteforcesettings: 2.3.0
  - calendar: 3.0.3
  - checksum: 1.1.3
  - circles: 22.1.1
  - cloud_federation_api: 1.5.0
  - comments: 1.12.0
  - contacts: 4.0.4
  - contactsinteraction: 1.3.0
  - dashboard: 7.2.0
  - dav: 1.19.0
  - federatedfilesharing: 1.12.0
  - federation: 1.12.0
  - files: 1.17.0
  - files_accesscontrol: 1.12.1
  - files_antivirus: 3.2.2
  - files_automatedtagging: 1.12.0
  - files_external: 1.13.0
  - files_pdfviewer: 2.3.1
  - files_rightclick: 1.1.0
  - files_sharing: 1.14.0
  - files_trashbin: 1.12.0
  - files_versions: 1.15.0
  - files_videoplayer: 1.11.0
  - firstrunwizard: 2.11.0
  - forms: 2.4.0
  - groupfolders: 10.0.0
  - impersonate: 1.9.0
  - integration_github: 1.0.2
  - integration_gitlab: 1.0.3
  - integration_mastodon: 1.0.2
  - integration_reddit: 1.0.3
  - integration_twitter: 1.0.2
  - logreader: 2.7.0
  - lookup_server_connector: 1.10.0
  - news: 17.0.1
  - nextcloud_announcements: 1.11.0
  - notifications: 2.10.1
  - oauth2: 1.10.0
  - password_policy: 1.12.0
  - polls: 3.4.2
  - privacy: 1.6.0
  - provisioning_api: 1.12.0
  - quota_warning: 1.13.0
  - recommendations: 1.1.0
  - richdocuments: 4.2.3
  - serverinfo: 1.12.0
  - settings: 1.4.0
  - sharebymail: 1.12.0
  - support: 1.5.0
  - survey_client: 1.10.0
  - suspicious_login: 4.1.0
  - systemtags: 1.12.0
  - tasks: 0.14.2
  - text: 3.3.0
  - theming: 1.13.0
  - twofactor_admin: 3.2.0
  - twofactor_backupcodes: 1.11.0
  - twofactor_totp: 6.2.0
  - updatenotification: 1.12.0
  - user_status: 1.2.0
  - viewer: 1.6.0
  - weather_status: 1.2.0
  - workflowengine: 2.4.0
Disabled:
  - encryption
  - photos
  - user_ldap
```

**Nextcloud configuration:**
```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "cipher": "AES-256-CFB",
        "login_form_autocomplete": false,
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "22.2.3.0",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "htaccess.RewriteBase": "\/",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "enable_previews": false,
        "filelocking.enabled": true,
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "default_language": "en",
        "default_locale": "***REMOVED SENSITIVE VALUE***",
        "default_phone_region": "BR",
        "defaultapp": "dashboard,files",
        "knowledgebaseenabled": true,
        "skeletondirectory": "",
        "maintenance": false,
        "twofactor_enforced": true,
        "twofactor_enforced_groups": [
            "admin"
        ],
        "twofactor_enforced_excluded_groups": [
            "guest_app"
        ],
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "ssl",
        "mail_smtpport": "465",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "theme": "",
        "loglevel": 2,
        "logtimezone": "America\/Sao_Paulo",
        "trashbin_retention_obligation": "auto, 180",
        "versions_retention_obligation": "auto",
        "updater.release.channel": "stable",
        "data-fingerprint": "87185c627a98d7f1ebc3c7888c4ad5ee",
        "connectivity_check_domains": [
            "www.duckduckgo.com",
            "www.eff.org",
            "www.nextcloud.com"
        ]
    }
}
```

**Comment by WNYmathGuy** [comment]
I have some other things happening wonky with the MariaDB instance that other apps I put issues on can't reproduce. Like groups I created in the Users section won't appear to click on until they are fully written out; no partial search results, only the exact match. 
MariaDB and MySQL have diverged enough now that they cannot be thought of as identical. I have a thing I'm building and the data is so critical that I add info to two mirrored systems; MariaDB and MySQL. I have to make different SQL statements for many of my data manipulations because I take advantage of "on primary key match update" type statements. There are other quirks I figured out years ago too when trying to migrate large databases from one to the other.

**Comment by nunesgh** [comment]
> **Nextcloud version:** 22.2.3

Just upgraded to Nextcloud version 23.0.0, but Contacts is still stuck at version 4.0.4.

**Comment by Crashone** [comment]
> > **Nextcloud version:** 22.2.3
> 
> Just upgraded to Nextcloud version 23.0.0, but Contacts is still stuck at version 4.0.4.

Uninstalling the app and reinstall it did fix the problem in my case.

**Comment by nunesgh** [comment]
Thanks for the suggestion, @Crashone! But it was reported in https://github.com/nextcloud/contacts/issues/2584#issuecomment-1002626655 that this is not a general solution.

**Comment by nunesgh** [comment]
> > **Nextcloud version:** 22.2.3
> 
> Just upgraded to Nextcloud version 23.0.0, but Contacts is still stuck at version 4.0.4.

Just upgraded to Nextcloud version 23.0.1, but Contacts is still stuck at version 4.0.4.

**Comment by Popkornium18** [comment]
Use this as a workaround: https://github.com/nextcloud/contacts/issues/2584#issuecomment-1009401922

I doubt this will be fixed anytime soon, since it affects only very few users.
