### ISSUE TITLE
Contacts page is blank after upgrade to v4.0.4

### ISSUE THREAD

**Issue by vincowl** [nextcloud/contacts#2491]
After upgrading `contacts` to v4.0.4 on a `Nextcloud` 22.2.0 docker instance, `contacts` page is totally blank, nothing displayed. Recreating the docker image, and removing the browser's cache doesn't change anything.

The console displays this error :
```
Refused to execute script from 'https://xxx.yyy.zzz/apps/dashboard/' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
```

`dashboard` is the app I had opened when clicking on the `contacts` icon. The same type of message occurs when clicking on `contacts` from `files`, `deck`, `agenda` or whatever.
​

**Comment by ChristophWurst** [comment]
Dup of https://github.com/nextcloud/contacts/issues/2488. Update to 4.0.6.

**Comment by vincowl** [comment]
Thanks ! Works like a charm !
