### ISSUE TITLE
Releases vs. Changelog

### ISSUE THREAD

**Issue by thomas-mc-work** [nextcloud/contacts#2493]
### Describe the bug

Rather a meta issue: There are three different "latest" releases in three different places, which should only be a single one:

- `4.0.6` in [the NC appstore](https://apps.nextcloud.com/apps/contacts)
- `4.0.4` in [the releases section](https://github.com/nextcloud/contacts/releases)
- `4.0.5` in [the Changelog](https://github.com/nextcloud/contacts/blob/master/CHANGELOG.md)

**Expected behavior**
Having this data properly in sync in each place.

**Comment by ChristophWurst** [comment]
Forgot to forward port the changelog. That is fixed now.

I've also added the release here.
