### ISSUE TITLE
Contacts in Web-Interface do not display anything since update to 4.0.4 yesterday

### ISSUE THREAD

**Issue by ralfi** [nextcloud/contacts#2494]
Hi there,

after yesterday upgrading contacts to 4.0.4 web interface (only contacts app) do not display anything. Access with DAVx from Smartphone works without any problems, seems to me only the browser interface is affected.

Configuration:
Nextcloud 22.2.0
Docker based
self-hosted

Try to solve the problem without success:
same with ff94, chrome95, edge91
disable / delete and re-install contacts
disable / enable dashboard causes by curious console message

Screenshot:

![grafik](https://user-images.githubusercontent.com/294423/140288512-111baacd-dfd3-431d-a02a-735f4682b6c2.png)

Browser console error:

![grafik](https://user-images.githubusercontent.com/294423/140288644-3a7488f0-49fb-4ab0-a052-e5c7dcfb2b51.png)

Thanks in advance for any hints!

**Comment by skjnldsv** [comment]
Please upgrade to 4.0.6

**Comment by ralfi** [comment]
Work again, Thanks!
