### ISSUE TITLE
Design Review

### ISSUE THREAD

**Issue by miaulalala** [nextcloud/contacts#2504]
Before we start blindly fixing bugs, a design review would be greatly appreciated. @nextcloud/designers would you be free at some point?

**Comment by nimishavijay** [comment]
This design review issue https://github.com/nextcloud/contacts/issues/1923 is a good starting point, we could go through it and prioritise and also have another review to update it?

**Comment by miaulalala** [comment]
Yeah sounds great!

**Comment by ChristophWurst** [comment]
Let's target https://github.com/nextcloud/contacts/issues/1923 first then.
