### ISSUE TITLE
A freshly created group is not persisted after a page reload

### ISSUE THREAD

**Issue by pmarini-nc** [nextcloud/contacts#2511]
### Describe the bug
A freshly created group is not persisted after a page reload

**To Reproduce**
1- add a group
2- add one or more users to the group
3- verify the user is (users are) in the group
4- reload the page

**Expected behavior**
The group just created is there

**Actual behavior**
The group doesn't exist

**Screenshots**

![Peek 2021-11-11 15-39](https://user-images.githubusercontent.com/85954408/141320371-1cd95397-a988-45ef-b889-bc3f2ed2c21d.gif)

### Server configuration

[2021-11-11.md](https://github.com/nextcloud/contacts/files/7521321/2021-11-11.md)

**List of activated apps:**

See system report

**Nextcloud configuration:**

See system report

### Client configuration
**Browser:** Firefox 94

**Operating system:** Ubuntu Desktop 21.04

**CardDAV-clients:** -

**Comment by miaulalala** [comment]
Can you have a look at your nextcloud.log and also try the same process with the dev console open please?

**Comment by skjnldsv** [comment]
This is per design.
Groups are virtual, they only exists in vcard they're written on.
They will persists if you add at least one contacts to it

**Comment by skjnldsv** [comment]
Would require #213

**Comment by pmarini-nc** [comment]
> This is per design. Groups are virtual, they only exists in vcard they're written on. They will persists if you add at least one contacts to it

What do you mean? I have added a contact to the group, but still the group disappears.

**Comment by pmarini-nc** [comment]
> Can you have a look at your nextcloud.log and also try the same process with the dev console open please?

I get this error in nextcloud.log
```
{
  "reqId": "GjeGeWCh3VMLk5l2XflX",
  "level": 0,
  "time": "2021-11-11T15:14:19+00:00",
  "remoteAddr": "10.23.46.1",
  "user": "sbianchi",
  "app": "webdav",
  "method": "PUT",
  "url": "/remote.php/dav/addressbooks/users/sbianchi/z-app-generated--contactsinteraction--recent/3",
  "message": "Node with name '3' could not be found",
  "userAgent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:94.0) Gecko/20100101 Firefox/94.0",
  "version": "22.2.0.2",
  "exception": {
    "Exception": "Sabre\\DAV\\Exception\\NotFound",
    "Message": "Node with name '3' could not be found",
    "Code": 0,
    "Trace": [
      {
        "file": "/var/www/nextcloud/3rdparty/sabre/dav/lib/DAVACL/Plugin.php",
        "line": 855,
        "function": "checkPrivileges",
        "class": "OCA\\DAV\\Connector\\Sabre\\DavAclPlugin",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/apps/dav/lib/Connector/Sabre/DavAclPlugin.php",
        "line": 98,
        "function": "beforeMethod",
        "class": "Sabre\\DAVACL\\Plugin",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php",
        "line": 89,
        "function": "beforeMethod",
        "class": "OCA\\DAV\\Connector\\Sabre\\DavAclPlugin",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php",
        "line": 456,
        "function": "emit",
        "class": "Sabre\\DAV\\Server",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php",
        "line": 253,
        "function": "invokeMethod",
        "class": "Sabre\\DAV\\Server",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php",
        "line": 321,
        "function": "start",
        "class": "Sabre\\DAV\\Server",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/apps/dav/lib/Server.php",
        "line": 333,
        "function": "exec",
        "class": "Sabre\\DAV\\Server",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/apps/dav/appinfo/v2/remote.php",
        "line": 35,
        "function": "exec",
        "class": "OCA\\DAV\\Server",
        "type": "->"
      },
      {
        "file": "/var/www/nextcloud/remote.php",
        "line": 166,
        "args": [
          "/var/www/nextcloud/apps/dav/appinfo/v2/remote.php"
        ],
        "function": "require_once"
      }
    ],
    "File": "/var/www/nextcloud/apps/dav/lib/Connector/Sabre/DavAclPlugin.php",
    "Line": 65,
    "CustomMessage": "--"
  }
}
```

**Comment by skjnldsv** [comment]
> What do you mean? I have added a contact to the group, but still the group disappears.

Very sorry, I completely read your ticket too fast.
You had all the information needed, ignore my intervention :)

**Comment by miaulalala** [comment]
Interesting - thanks for looking @pmarini-nc ! I will investigate this soon.

**Comment by Mer0me** [comment]
Some news on this one ? And is it useful to have both Contact Groups and Circles ? What are the differences ?
