### ISSUE TITLE
Move sharing settings to a modal

### ISSUE THREAD

**Issue by st3iny** [nextcloud/contacts#2513]
**Is your feature request related to a problem? Please describe.**
The sharing menu for address books is frustrating to use in its current state. The user name and the read-only checkbox labels are truncated because the width is too low.

**Describe the solution you'd like**
Move the sharing menu to a modal. When the sharing icon/button is clicked in the settings menu on the bottom left, this modal would open and let me handle sharing with other users.

**Additional context**
See this example screenshot from #2503:

![canedit](https://user-images.githubusercontent.com/12728974/141438378-81fd71c7-9026-4e8c-ba93-691e2c2f22d9.png)

**Comment by miaulalala** [comment]
Wanna add it to the XMas list?

**Comment by skjnldsv** [comment]
There is an issue about moving the entire settings to a Modal, like talk :)
Design team approved it :)

**Comment by ChristophWurst** [comment]
Then let's link and close as duplicate @st3iny

**Comment by st3iny** [comment]
Already tracked in https://github.com/nextcloud/contacts/issues/1923.
