### ISSUE TITLE
when adding a new instant messaging field, the dropdown options are wrong.

### ISSUE THREAD

**Issue by xh3n1** [nextcloud/contacts#252]
I think there should be something like skype, telegram etc

**Comment by xh3n1** [comment]
let me quickly have a look if I can fix it

**Comment by jonatoni** [comment]
Yes, we will work on this issue.

**Comment by jancborchardt** [comment]
Yup, same for the social media field :) https://github.com/nextcloud/contacts/issues/130

**Comment by jancborchardt** [comment]
Fixed through https://github.com/nextcloud/contacts/pull/254 :)
