### ISSUE TITLE
Unable to delete app generated contacts

### ISSUE THREAD

**Issue by andyxheli** [nextcloud/contacts#2524]
I shared a file via email with none NC users and now those emails are in my contacts but i cant delete them
**Expected behavior**
unable to delete automatically generated email in contract. 

**Screenshots**
![image](https://user-images.githubusercontent.com/59488153/142127251-309e44d1-d48b-4823-9b46-f74fcc94d14c.png)

### Server configuration

**Operating system**: Windows, Linux, MacOS...
Ubuntu
**Web server:** Apache, Nginx...
Apache
**Database:** MariaDB, MySQL, PostgreSQL... 
MariaDB 10.15
**PHP version:** 7.0, 7.1, 7.2...
8.0
**Nextcloud version:** (see Nextcloud admin page)
22.2.3
**Contacts version:** (see Nextcloud apps page)
4.0.6
**Updated from an older Nextcloud or fresh install:**
22.2.1
```

**Comment by ChristophWurst** [comment]
Yes, they are read-only. They are collected and provided by https://github.com/nextcloud/server/tree/master/apps/contactsinteraction. You can disable the app.

**Comment by andyxheli** [comment]
Thank you!
