### ISSUE TITLE
How do I enable VCard4 instead of VCard3?

### ISSUE THREAD

**Issue by flexagoon** [nextcloud/contacts#2534]

**Comment by flexagoon** [comment]
Oh wait, just noticed that VCard4 is already supported.

**Comment by flexagoon** [comment]
Wait, no, all of my contacts use VCard3. How do I switch them to VC4?

**Comment by ChristophWurst** [comment]
> If you have any questions, head over to https://help.nextcloud.com/c/apps/contacts

:v:

**Comment by flexagoon** [comment]
Oh, sorry. thanks.
