### ISSUE TITLE
When sharing address book, name of target is not visible

### ISSUE THREAD

**Issue by vasyugan** [nextcloud/contacts#2540]
When I share an address book, I cannot see the name of the target:

![grafik](https://user-images.githubusercontent.com/3313208/143731037-b01900cc-36f9-47f8-87fb-b0b88d1b059a.png)
 
Even zooming out does not make a difference.

**Browser:** Firefox 94 on Linux, 
**Nextcloud server:** 22.2.3
**Contacts app:** 4.0.6

**Comment by miaulalala** [comment]
Please add your version and browser.

**Comment by vasyugan** [comment]
> Please add your version and browser.

Sorry, added now.

**Comment by ChristophWurst** [comment]
@GretaD didn't you just fix this?

**Comment by ChristophWurst** [comment]
https://github.com/nextcloud/contacts/pull/2503
