### ISSUE TITLE
still not possible to enter a birthday without a year

### ISSUE THREAD

**Issue by tessus** [nextcloud/contacts#2542]
I have opened an issue many years ago but I can't even find it anymore.

But it is still not possible to enter a birthday without a year. Since this is part of the CardDAV spec I strongly believe this is a bug and not a feature request.

Nextcloud version: all
Contacts version: all
OS: all
browser: all

**Comment by miaulalala** [comment]
This one? #4287

**Comment by tessus** [comment]
Nope. That one was about the backend. I am talking about the contacts app. The date picker requires a year. This should just be a flag, thus such a change should be fairly easy. Yet, I have to use my phone to add proper dates, because the web app can't do it.

**Comment by miaulalala** [comment]
Ok, thanks, we'll look into it!

**Comment by skjnldsv** [comment]
https://github.com/nextcloud/contacts/issues/1814
