### ISSUE TITLE
Drop Nextcloud 20 support

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/contacts#2543]
Ref https://github.com/nextcloud/groupware/issues/7

**Comment by ChristophWurst** [comment]
@miaulalala could you take care of this? :)

**Comment by miaulalala** [comment]
Do I need to limit the php version?

**Comment by ChristophWurst** [comment]
Yes, please add explicit php version ranges. Let's say 7.3 to 8.0? Then we cover all of Nextcloud 21 to 23.
