### ISSUE TITLE
Date formatter for DatePicker is wrong

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/contacts#2551]
https://github.com/nextcloud/contacts/blob/6cee25027dae1732e1855074d8874c888124fb25/src/components/Properties/PropertyDateTime.vue#L63

this should be `formatter`
https://github.com/nextcloud/nextcloud-vue/pull/1517

I don't even understand why it is not throwing :shrug:

**Comment by sunnyjain15699** [comment]
Hi @skjnldsv. I would like to contribute . Can you guide me through it ?

**Comment by skjnldsv** [comment]
Sure, when using latest dependencies for @nextcloud/vue as well as vue2-datepicker, we need to chaneg the prop from `format` to `formatter`.

See https://github.com/nextcloud/nextcloud-vue/pull/1517 
https://github.com/nextcloud/nextcloud-vue/pull/1495#issuecomment-989730285
