### ISSUE TITLE
No js/ folder?

### ISSUE THREAD

**Issue by sixtyfive** [nextcloud/contacts#2553]
@ChristophWurst, is it possible you accidentally zipped up your working copy before building the js? `git remote -v` in `apps/contacts/` works and mentions `/home/christoph/...`.

**Comment by ChristophWurst** [comment]
v4.0.4 and v4.0.5 were botched, my bad. v4.0.6 works also for 22.

**Comment by sixtyfive** [comment]
ah, then there must be a problem with our installation ... while on 22, `updater.phar` stopped after v4.0.4.
