### ISSUE TITLE
The contact page is empty, there is no interface anymore

### ISSUE THREAD

**Issue by Synochy** [nextcloud/contacts#2563]
### Describe the bug
The contact page is empty, there is no interface anymore:
![image](https://user-images.githubusercontent.com/20789073/146350462-2f3f8984-ec33-47c2-a28d-e6aa8f3dad37.png)

But the contact are still there:
![image](https://user-images.githubusercontent.com/20789073/146350700-cfd8ec62-9d7b-4892-bbf0-7c86ff26054f.png)

### Server configuration

**Operating system**: Debian

**Web server:** Apache

**Database:** MariaDB

**PHP version:** 8.0

**Nextcloud version:** 23
**Contacts version:** 4.0.4

**Comment by ChristophWurst** [comment]
Update to 4.0.6

**Comment by berkaycagir** [comment]
I'm having the same issue with 4.0.7, what may be the culprit here?

**Comment by Synochy** [comment]
I was not able to upgrade to 4.0.6, the best solution found was to uninstall and install again contact app to fix the problem. 
For your information you don't loose your contacts when uninstalling the app.
