### ISSUE TITLE
Cannot see 'Add Members' button when Circles is configured as 'Members can also invite'

### ISSUE THREAD

**Issue by ArtificialOwl** [nextcloud/contacts#2578]
The button `Add Members` is not available to non-moderator members when the Circles is not configured as '_Members can also invite_' (`CFG_FRIEND`) which is the expected behavior.

However, when the Circle is configured as `CFG_FRIEND` every members should have access to the `Add Members` button.

The value for `CFG_FRIEND` is `128`, it should be available as a bitwise in the '`config`' entry of the Model of the current Circle.

_Note_: the back-end is also faulty, and patch is available here: nextcloud/circles#872

**Comment by ChristophWurst** [comment]
> The value for `CFG_FRIEND` is `128`, it should be available as a bitwise in the '`config`' entry of the Model of the current Circle.

https://github.com/nextcloud/contacts/pull/2579
