### ISSUE TITLE
Broken on Nextcloud 24 (undefined method `OC-Util::isIe()`)

### ISSUE THREAD

**Issue by mejo-** [nextcloud/contacts#2581]
The Contacts app is currently broken on NC24 with PHP8:

> Call to undefined method OC_Util::isIe()
> /var/www/html/apps/contacts/templates/main.php:2

Seems like this function got removed from server in nextcloud/server#25676.

**Comment by ChristophWurst** [comment]
https://docs.nextcloud.com/server/latest/developer_manual/app_publishing_maintenance/upgrade-guide.html#id5 documented but nobody took care.

**Comment by miaulalala** [comment]
SO what's the solution? Remve the check completely? Global usage of IE is at 0.49%. Risk it for a bisquit?

**Comment by ChristophWurst** [comment]
It was officially dropped. We can remove all IE logic.

**Comment by ChristophWurst** [comment]
Imagine someone [warned us](https://github.com/nextcloud/contacts/issues/2124)
