### ISSUE TITLE
Contact app make fails on 'Could not read "phpunit.integration.xml'

### ISSUE THREAD

**Issue by brjhaverkamp** [nextcloud/contacts#2588]
Could not read "phpunit.integration.xml".
### Describe the bug
I have cloned the git repro for contacts and try to build the app locally with
git clone https://github.com/nextcloud/contacts.git
After 
sudo -u www-data make 
in /var/www/nextcloud/apps/contacts, the process fails on:
> phpunit -c phpunit.integration.xml --fail-on-warning
Could not read "phpunit.integration.xml".
Script phpunit -c phpunit.integration.xml --fail-on-warning handling the test:integration event returned with error code 1
make: *** [Makefile:56: test-php] Error 1

**To Reproduce**
clone git repro
start make process 

**Expected behavior**
full build of contacts app
**Actual behavior**
build of contacts app is not complete and fails on above error.

**Operating system**: Windows, Linux, MacOS...
Ubuntu 21.04 on laptop. Nextcloud 23.0.0, Latest contacts git repro,  
******************************************
I'm curious if I am doing something wrong here,  But I see no phpunit.integration.xml anywhere.
For the moment I have renamed it to phpunit.xml in composer.json , so I can run make succesful.

Regards,
Bert

**Comment by ChristophWurst** [comment]
fixed by https://github.com/nextcloud/contacts/pull/2589

**Comment by brjhaverkamp** [comment]
Thanks for the fast fix!
I do see now a new error/warning (Not sure how serious it is, actually.. but the stop sound serious:-)

make: *** No rule to make target 'build-js-production', needed by 'all'.  Stop.

I think this is coming from the #2589 patch. build-js-production was taken out there, but is stil used for all:
I'm away for a few days unfortunately, otherwise I would have attempted a patch.

**Comment by ChristophWurst** [comment]
My bad. I wasn't careful enough.

Nevertheless you shouldn't need any more Makefile/make for the dev setup. See the latest https://github.com/nextcloud/contacts#build-the-app
