### ISSUE TITLE
ENCODING=BASE64 is not valid for this document type.

### ISSUE THREAD

**Issue by iamtpage** [nextcloud/contacts#260]
### Steps to reproduce
1. Have a contact with a picture on android phone
2. Sync with DAVdroid
3. Look in error log

### Expected behaviour
Photo would be reflected in contacts on nextcloud

### Actual behaviour
Server reports: Sabre\DAV\Exception\UnsupportedMediaType: HTTP/1.1 415 Validation error in vCard: ENCODING=BASE64 is not valid for this document type.

### Server configuration
**Operating system**: Linux Odin 4.9.30-unRAID #1 SMP PREEMPT Fri May 26 13:56:36 PDT 2017 x86_64

**Web server:** nginx/1.12.1 (fpm-fcgi)

**Database:** mariadb

**PHP version:** 7.1.5
Modules loaded: Core, date, libxml, pcre, filter, hash, readline, Reflection, SPL, session, cgi-fcgi, bz2, ctype, curl, dom, fileinfo, ftp, gd, gmp, iconv, intl, json, ldap, mbstring, mcrypt, openssl, pcntl, PDO, pgsql, posix, standard, SimpleXML, smbclient, sqlite3, xml, xmlwriter, zip, zlib, exif, imap, mysqlnd, pdo_pgsql, pdo_sqlite, xmlreader, pdo_mysql, memcached, apcu, libsmbclient, Zend OPcache

**Nextcloud version:** 12.0.0 - 12.0.0.29

**Updated from an older Nextcloud/ownCloud or fresh install:**  fresh install

**Where did you install Nextcloud from:** website

**Signing status:**
<details>
	<summary>Signing status</summary>

```
[]
```

</details>

**List of activated apps:**
<details>
	<summary>App list</summary>
```
Enabled:
 - activity: 2.5.2
 - admin_audit: 1.2.0
 - audioplayer: 2.0.2
 - bruteforcesettings: 1.0.2
 - calendar: 1.5.3
 - checksum: 0.3.5
 - comments: 1.2.0
 - contacts: 1.5.3
 - dav: 1.3.0
 - federatedfilesharing: 1.2.0
 - federation: 1.2.0
 - files: 1.7.2
 - files_markdown: 1.0.1
 - files_pdfviewer: 1.1.1
 - files_reader: 1.0.4
 - files_sharing: 1.4.0
 - files_texteditor: 2.4.1
 - files_trashbin: 1.2.0
 - files_versions: 1.5.0
 - files_videoplayer: 1.1.0
 - firstrunwizard: 2.1
 - gallery: 17.0.0
 - issuetemplate: 0.2.1
 - logreader: 2.0.0
 - lookup_server_connector: 1.0.0
 - nextcloud_announcements: 1.1
 - notes: 2.3.1
 - notifications: 2.0.0
 - oauth2: 1.0.5
 - ocsms: 1.12.0
 - password_policy: 1.2.2
 - previewgenerator: 1.0.6
 - provisioning_api: 1.2.0
 - serverinfo: 1.2.0
 - survey_client: 1.0.0
 - systemtags: 1.2.0
 - tasks: 0.9.5
 - telephoneprovider: 1.0.0
 - theming: 1.3.0
 - twofactor_backupcodes: 1.1.1
 - twofactor_totp: 1.3.0
 - updatenotification: 1.2.0
 - workflowengine: 1.2.0

Disabled:
 - encryption
 - files_external
 - mail
 - rainloop
 - sharebymail
 - user_external
 - user_ldap
```
</details>

**The content of config/config.php:**
<details>
	<summary>Config report</summary>

```
{
    "memcache.local": "\\OC\\Memcache\\APCu",
    "datadirectory": "\/data",
    "instanceid": "ocycnzp6ao9v",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "192.168.1.107",
        "10.0.0.4:8080",
        "cloud.tpage.io"
    ],
    "overwrite.cli.url": "https:\/\/cloud.tpage.io",
    "overwritehost": "cloud.tpage.io",
    "overwriteprotocol": "https",
    "dbtype": "mysql",
    "version": "12.0.0.29",
    "dbname": "nextcloud",
    "dbhost": "odin.vik:3306",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "maintenance": false,
    "mail_from_address": "nextcloud",
    "mail_smtpmode": "smtp",
    "mail_smtpauthtype": "LOGIN",
    "mail_domain": "tpage.io",
    "mail_smtpsecure": "tls",
    "mail_smtphost": "tpage.io",
    "mail_smtpport": "587",
    "mail_smtpauth": 1,
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "mysql.utf8mb4": true
}
```
</details>

**Are you using external storage, if yes which one:** files_external is disabled

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:**

### Client configuration
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36

**Operating system:**

#### Web server error log
<details>
	<summary>Web server error log</summary>
	```
	Insert your webserver log here
	```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
	<summary>Nextcloud log</summary>
	```
.1 415 Validation error in vCard: ENCODING=BASE64 is not valid for this document type. | 2017-07-20T21:14:46-0500
-- | --
Fatal | webdav | Sabre\DAV\Exception\UnsupportedMediaType: HTTP/1.1 415 Validation error in vCard: ENCODING=BASE64 is not valid for this document type. | 2017-07-20T21:14:45-0500
Fatal | webdav | Sabre\DAV\Exception\UnsupportedMediaType: HTTP/1.1 415 Validation error in vCard: ENCODING=BASE64 is not valid for this document type. | 2017-07-20T21:14:45-0500
Fatal | webdav | Sabre\DAV\Exception\UnsupportedMediaType: HTTP/1.1 415 Validation error in vCard: ENCODING=BASE64 is not valid for this document type. | 2017-07-20T21:14:45-0500
Fatal | webdav | Sabre\DAV\Exception\UnsupportedMediaType: HTTP/1.1 415 Validation error in vCard: ENCODING=BASE64 is not valid for this document type. | 2017-07-20T21:14:45-0500
Fatal | webdav | Sabre\DAV\Exception\UnsupportedMediaType: HTTP/1.1 415 Validation error in vCard: ENCODING=BASE64 is not valid for this document type. | 2017-07-20T21:14:45-0500
Fatal | webdav | Sabre\DAV\Exception\UnsupportedMediaType: HTTP/1.1 415 Validation error in vCard: ENCODING=BASE64 is not valid for this document type. | 2017-07-20T21:14:45-0500
Fatal | webdav | Sabre\DAV\Exception\UnsupportedMediaType: HTTP/1.1 415 Validation error in vCard: ENCODING=BASE64 is not valid for this document type. | 2017-07-20T21:14:45-0500
Fatal | webdav | Sabre\DAV\Exception\UnsupportedMediaType: HTTP/1.1 415 Validation error in vCard: ENCODING=BASE64 is not valid for this document type. | 2017-07-20T21:14:45-0500
Fatal | webdav | Sabre\DAV\Exception\UnsupportedMediaType: HTTP/1.1 415 Validation error in vCard: ENCODING=BASE64 is not valid for this document type.
etc..

	```
</details>

#### Browser log
<details>
	<summary>Browser log</summary>
	```
No errors in browser log
	```
</details>

**Comment by skjnldsv** [comment]
Can't reproduce on android aosp.
Mind to provide us the broken vcard? From your android phone? :)

**Comment by iamtpage** [comment]
[test.zip](https://github.com/nextcloud/contacts/files/1174138/test.zip)

**Comment by skjnldsv** [comment]
File is empty :p

**Comment by iamtpage** [comment]
Not sure what's going on, I downloaded the attachment, opened the zip archive and extracted it.  Here is a snip of the file open in notepad++ and window's contacts:
![image](https://user-images.githubusercontent.com/8901422/28584477-855c0ab4-7132-11e7-8040-8302c3b047f1.png)

**Comment by skjnldsv** [comment]
Indeed, the correct format is `ENCODING=b` not `ENCODING=BASE64`.
It's probably coming from your phone. Not a nextcloud issue.

What android version and rom are you using?

**Comment by iamtpage** [comment]
Android 6.0.1, Motorola stock ROM.

Using Google contacts, the picture does appear in the app.  And exporting seems to only be able to have BASE64 encoding, no other options.  Any alternative suggestions?  I'm a big fan of facebook photo sync -> contacts app on phone -> nextcloud.  Or some converter out there to convert my vcards from base64 to b(inary)

**Comment by skjnldsv** [comment]
So aside from the log error, everything is working fine?

**Comment by iamtpage** [comment]
I suppose so, there's only support for binary encoding of contact photos? Nothing else is planned for compatibility?

**Comment by skjnldsv** [comment]
Wait, I'm lost here. The binary mode and direct url are the only two options accepted by a vcard, and we support them both. When your facebook photosync update your contacts on your phone, and after your phone synced them on nextcloud, do the pictures appear on the contact app?

**Comment by iamtpage** [comment]
Looks like binary and direct URI are only valid photo inputs for vCard 3.0, however Google Contacts exports vCards in 2.1 format (per my screenshot above).  Looking up the RFC for vCard 2.1, base64 is a valid photo input, however in 3.0 they switched to only binary/URI.

There is a check in the Sabre project that checks this logic, and it seems they support 2.1 vCards:
https://github.com/fruux/sabre-vobject/blob/master/lib/Property.php#L617

I ended up having to sync the contacts from nextcloud onto my phone, and from there use the facebook photosync to add the pictures, the result being that the photos are now visible in the contacts on my nextcloud instance. This works probably because nextcloud syncs the vCard as 3.0 or something it accepts and then my contacts app also supports it, allowing it to write the photo to it.

**Comment by skjnldsv** [comment]
So, everything's fine now? 😋

**Comment by iamtpage** [comment]
Yes, closing.

**Comment by seblu** [comment]
I have the same error message which prevent me from updating several contacts from the webapps. I'm using version 12.0.2 in the docker image.

**Comment by iamtpage** [comment]
The way I went about this was by taking my contacts, exporting them from google. Importing them and converting them to a supported format, then importing them back into Nextcloud and syncing with them from there.

**Comment by seblu** [comment]
I find a way to workaround this too by using another client. It remains :
- Edition of those contacts via the web interface are not saved without error messages;
- The pictures are displayed, so there is no obvious way to know if the contact has this issue;
- Fatal error are reported in the admin log.

At least the use should be warned of what he just write has been lost. IMHO, that should be handled in the web client.
