### ISSUE TITLE
Opt-out birthday calender auto-creation

### ISSUE THREAD

**Issue by mcnesium** [nextcloud/contacts#261]
I don't want a "Birthdays of your contacts" calendar, but every now and then it re-appears in my list of calendars. I would like to have an opt-out option to that. Is this a contacts or a calendar issue?

**Comment by skjnldsv** [comment]
A server issue maybe? Related to dav?
@Henni ? @MorrisJobke ?

**Comment by MorrisJobke** [comment]
cc @georgehrke

**Comment by georgehrke** [comment]
https://github.com/nextcloud/server/issues/3003
