### ISSUE TITLE
Rename Groups to Contact groups

### ISSUE THREAD

**Issue by miaulalala** [nextcloud/contacts#2612]
Rename the groups inside contacts to "Contact groups" as to not cause confusion with the other concept of Groups that exists within Nextcloud.

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
What is the alternative concept?

**Comment by ChristophWurst** [comment]
PR at https://github.com/nextcloud/contacts/pull/3097

**Comment by miaulalala** [comment]
> What is the alternative concept?

User groups
