### ISSUE TITLE
Contacts work over CalDAV, but web interface always reports no contacts, and clicking 'Create Contact' does absolutely nothing

### ISSUE THREAD

**Issue by morsedl** [nextcloud/contacts#2623]
### Describe the bug
......
Contacts work over CalDAV, but web interface always reports no contacts, and clicking 'Create Contact' does absolutely nothing
......

**To Reproduce**
1. Go to the contacts app
2. Click 'Create Contacts'

**Expected behavior**
A form for adding a contact.

**Actual behavior**
Absolutely nothing. Yet, for example, adding a CalDAV 'Internet Account' on iPhone using the user-specific CalDAV URL (obtained under Contacts App -> Settings for the user) seems to work just fine. Specifically, additions, modifications, and deletions seem to work as they should. But contacts created etc. over CalDAV do not show up ever for the user in the web interface. In addition, clicking on 'Create Contact' within the user interface does nothing.

**Screenshots**

### Server configuration

Using official Docker Hub NextCloud docker images (Docker running on Debian 10).

**Nextcloud version:** 

23

**Contacts version:** (see Nextcloud apps page)

Lastest. Have uninstalled and reinstalled, without any effect.

**Updated from an older Nextcloud or fresh install:**

Brand new install.

**Comment by miaulalala** [comment]
HI, can you please look at your browser console and nextcloud.log to see if there are any errors?

**Comment by morsedl** [comment]
Hi miaulalala,

Thank you again very kindly for your prompt response.

No, no error messages under Settings -> Logging, where I do see error messages, specifically, those regarding the email message body retrieval problem I reported at the same time under a different issue. Unfortunately there have been no error messages there whatsoever.

I'll take a look again at my nextcloud-errors.log (the file that I've set up to write to when debugging at `loglevel=3` is enabled) as soon as I can and get back with you later today. Unfortunately I have an appointment I must leave for right now.

Thanks again, and more soon.

**Comment by morsedl** [comment]
"Unfortunately there have been no error messages there whatsoever."

"... regarding the Contacts app." I should have appended to this sentence for clarity.

**Comment by ChristophWurst** [comment]
> can you please look at your browser console

Check the browser logs too, it might be something on the front-end.

**Comment by morsedl** [comment]
I will do so here shortly. It’ll be interesting to see where the problem resides. That said, I’ve been testing with A rather vanilla instance of safari on macOS, on a Brand New Mac mini with M1 chip. So I’ll be a bit surprised if we find anything there, but who knows. 😀


Von meinem iPhone gesendet

**Comment by eliasp** [comment]
Same for me using:
- Nextcloud 23.0.0
- Contacts 4.0.7
- Firefox 96.0.1

Clicking on "Create Contact" does absolutely nothing:
- no JS Console output
- no network activity (and therefore also no server logs)

**Comment by as01p** [comment]
Same problem, everything is good in the database and a synchronization (add/remove) seems to be correct (from desktop to laptop). But nothing is visible in the web interface anymore.

**Comment by ChristophWurst** [comment]
is your address book disabled from the menu in the bottom left?

**Comment by as01p** [comment]
> is your address book disabled from the menu in the bottom left?

Yes, I alternativly enable/disable to migrate from one to another.
But now I cannot see it anymore !
Only the old one empty..., it's ok I delete everything from it.
But the one you is full of contacts and sync perfectly, hidden. Impossible to activate it.

**Comment by aptiko** [comment]
Same here with Nextcloud 23.0.0, Contacts 4.0.7, Firefox 97.0

Note that there are two buttons for creating a contact: the top left (which is always there) and the one in the middle (only available if there are no contacts):

![image](https://user-images.githubusercontent.com/2692385/154273486-dd42dc73-87cb-4350-a147-af25a6ae4da5.png)

The top left "New contact" button **works properly**. It is the "Create contact" in the middle that does nothing (and nothing shows in the JavaScript console).

**Comment by miaulalala** [comment]
@morsedl can you confirm that this is also the case for you?

**Comment by chribre** [comment]
Hi, I have the same issue with my freshly updated instance (23.0.2) - Checked in Firefox 97.0 and Chromium 99.0.4...

**notes**
- synchronizing contacts via calDAV works like it should
- contacts with location information are visible on Maps app
- creating new address book is possible, identic address book name will have additional number in link as it should
  - can create new contact in new address book
- global search lists contact matches, opening in app not working
- opening contacts from Maps also not working (but never did)

I hope this helps, let me know if I can help with more infos.

**Comment by mandavister** [comment]
same here - versions are up to date and same as @chribre 
contacts are clearly in the database and searchable via contact search, but not visible in the web-app
