### ISSUE TITLE
deleting circles doesn't clean up shares

### ISSUE THREAD

**Issue by schiessle** [nextcloud/contacts#2643]
Tested on Nextcloud 22.2.3

If I delete a circle shares with the circle are not cleaned up correctly.

Steps to reproduce:

1. create a circle
2. Share a document with a circle
3. delete the circle
4. go back to the document and look at the sharing tab on the right sidebar.

What I see:

![grafik](https://user-images.githubusercontent.com/1589737/154117497-84a290c0-05c4-434d-acbb-a77ac49590d5.png)

The circle share is still there with a cryptic ID and no icon

Expected:

The share gets removed correctly when the user deletes the circle

**Comment by ArtificialOwl** [comment]
fixed in 22.2.4: https://github.com/nextcloud/circles/pull/911
