### ISSUE TITLE
shared address book user are not display with full name 

### ISSUE THREAD

**Issue by Pikaso78** [nextcloud/contacts#2660]
Hi,

![grafik](https://user-images.githubusercontent.com/100866301/156616646-e7a9c423-e1d2-47b8-9b64-c4ed1700a256.png)

We cannot see the username that got the address book shared.

**Comment by ChristophWurst** [comment]
Version?

**Comment by Pikaso78** [comment]
Contacts 4.0.8
[Nextcloud Hub II] (23.0.2)

**Comment by ChristophWurst** [comment]
https://github.com/nextcloud/contacts/pull/2503
