### ISSUE TITLE
info pane in v4.10 shows incorrect label for contacts made in earlier version

### ISSUE THREAD

**Issue by r-hmn** [nextcloud/contacts#2687]
### Steps to reproduce
(untested)
1. i had contacts v4.08 (i'm not sure in which version i created the existing contacts)
2.  i created some contacts. 
3.  upgraded to 4.10
4. i opened the contacts-page, and instead of  `Home` it says  `HOME","VOICE`
![contacts--Dutch-localization](https://user-images.githubusercontent.com/55837027/159705634-c12a934c-184c-49ba-9d23-40756d831380.jpg)
6. i created a new contact and that info-page does show 'Home' 
![contacts--English-localization_New-is-Ok](https://user-images.githubusercontent.com/55837027/159705687-3c4069db-e574-4145-b6e4-9f5beb29a427.jpg)
8. i switched language translations but that doesn't change the issue at point 4.

### Expected behaviour
The info page should show the label `Home'  for the 'Phone' entry

### Actual behaviour
The info page shows 'HOME","VOICE' for contacts created in an older version of contacts

### Server configuration

**Operating system**:
Lubuntu 20.4

**Web server:**
**Database:**
**PHP version:**
**Nextcloud version:** (see Nextcloud admin page)
"NextCloud All-In-One" container v0.9.0 Beta (contains nextcloud 23.0.3)
Dutch Language enabled

**Contacts version:** (see Nextcloud apps page)
Contacts 4.10

**Updated from an older Nextcloud or fresh install:**
First upgraded from Contacts 4.08 to to 4.10  and upgraded Deck and Talk.
Then i updated "NextCloud All-In-One" container by stopping restarting. Nc via the admin-console at http://localhost:8080/containers 
(updating from previous container version v0.8.0 to v0.9.0)

**Signing status:**

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
404 not found

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
[app-versions.txt](https://github.com/nextcloud/contacts/files/8333412/app-versions.txt)

**Are you using external storage, if yes which one:** local/smb/sftp/...
No
**Are you using encryption:** yes/no
No
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
**Browser:**
Chromium Version 89.0.4389.114 (Developer Build, ungoogled-chromium) (64-bit)

**Operating system:**
Windows 10

**CardDAV-clients:**
NA 

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
[nextcloud-upgrade-log-redacted.txt](https://github.com/nextcloud/contacts/files/8333279/nextcloud-upgrade-log-redacted.txt)

**Comment by joshtrichards** [comment]
Hi @r-hmn - Are you still experiencing this in newer versions?

**Comment by r-hmn** [comment]
Hi @joshtrichards
Good you ask. in current version AIO 8.2.1 , contacts 5.5.3 i don't see this issue anymore.👍
