### ISSUE TITLE
Improve the layout of the contacts app with single column list view and other changes

### ISSUE THREAD

**Issue by arnowelzel** [nextcloud/contacts#2699]
### Is your feature request related to a problem? Please describe.

The current layout of the contact app is not very efficient. A lot of space is wasted and some labels can't even be displayed completely because of this.

Example - this is the view when having the browser full screen using the equivalent of 1920*1080 (4K with 200% scaling):

![image](https://user-images.githubusercontent.com/6613614/161437766-ccd74ddd-9289-4210-a095-1d4b4a59ecf2.png)

As you can see the contact details use three quite narrow columns with a lot of space left and right in the view. This means that the labels "Zusätzliche Namen", "Erweiterte Adresse" and "Bundesland oder Region" are not displayed completely.

Another issue is the invisible "trash can" icon which appears when touching elements - sometimes it is not clear what exactly that icon applies to. In some cases it means to delete a field only but in other cases a whole block will be affected. However there is no visual indication what exactly will happen when clicking the icon and deleting something will also happen immediately without any confirmation.

![image](https://user-images.githubusercontent.com/6613614/161438136-518d3cc2-a329-49b5-b882-deba832931ca.png)

![image](https://user-images.githubusercontent.com/6613614/161438145-331a9820-6361-4eea-81df-161dc8ded658.png)

### Describe the solution you'd like

The layout could be improved in the following way:

- Use the available space completely and do not use fixed sized elements or maybe even only one colum so labels and content will have enough space.
- Have different modes for "view" and "edit". Most of the time people don't want to edit contacts but just look them up and use them. However in the current implementation one can very easy change data by accident and since all changes get saved immediately and without confirmation you may not even be aware that you have changed something.
- Indicate visually which element will be affected when deleting something (e.g. by putting a red border around the affected elements when hovering the trash can icon or by describing this in the tooltop like "Delete address" or "Delete field xyz").
- Do not delete elements without confirmation.
- Make adding fields easier to understand - at the moment there is a text "+ Add new property" wich can not be clicked at all. However one would think that clicking "+" will do something. And below there is an input element which can be clicked and will open a list to select what to add. However when selecting the property from the list the new element will show up somewhere in the form and the "+Add new property" will move around to another column which is quite confusing for many people.

### Describe alternatives you've considered

Provide the option to use your own HTML template with placeholders for the elements.

### Additional context

The layout of iCloud contacts may be a inspiration how to create a clean and simple layout - even though I would not exactly copy it, but the general way how this was done is much easier to use for many people:

![image](https://user-images.githubusercontent.com/6613614/161438925-64bda10b-7110-496d-8209-b0580738065b.png)

![image](https://user-images.githubusercontent.com/6613614/161439085-d29cb1dc-c68d-41f5-b816-ad55441258a3.png)

**Comment by IndrekHaav** [comment]
A linear layout (like in the iCloud screenshots) would also fix the annoyance of the form elements moving around as you add or remove contact properties.

**Comment by ChristophWurst** [comment]
Related https://github.com/nextcloud/contacts/issues/1923

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
@arnowelzel, potentially rename this issue so that is demonstrates that the priority, if not sole problem that is demonstrates, is that the fields should be presented as a list, because locating this was difficult, so I almost created a duplicate for a list-view of forms.

**Comment by robertmx** [comment]
I am just testing a fresh install of NC 25.0.1 and found the contacts app layout to be even worse than before. 
The spacing between the elements look random, the arrangement of the individual inputs is confusing. Not a single element is properly aligned. That does not look like an improvement at the moment.

![Bildschirmfoto_2022-11-08_09-02-04](https://user-images.githubusercontent.com/16461424/200590304-a7dba8d3-240d-4bc8-8ddd-8a23126588d7.png)

**Comment by arnowelzel** [comment]
Since it seems to take a while until this is fixed, I started working on a workaround using [CustomCSS](https://apps.nextcloud.com/apps/theming_customcss). So far I added the following rules to achieve the following goals:

- have a single column layout
- make sure all labels are the same format and use more space, so you can also read the label and do not have to guess the text

```
/* Customize "contacts" layout */

section.contact-details {
  width: 100% !important;
}

section.contact-details .property-masonry {
  display: block !important;
  position: relative !important;
  left: 0 !important;
  top: 0 !important;
  width: 100% !important;
}

section.contact-details .property-masonry .property__label {
  text-align: left !important;
  padding-right: 1em !important;
  width: 16em !important;
  min-width: 16em !important;
  max-width: 16em !important;
}

section.contact-details .property-masonry .multiselect__tags {
  padding-left: 0 !important;
}

section.contact-details .property-masonry .property {
  width: 100% !important;
  max-width: 50em !important;
}

section.contact-details .property--rev {
  display: block !important;
  position: relative !important;
  left: 0 !important;
  top: 0 !important;
  bottom: 0 !important;
  height: auto !important;
  line-height: inherit !important
}
```

The result is not perfect yet and will not work nicely on mobile devices since labels and input element should be placed in a different way there - but it is still much easier to use than before in my opinion and one might add a media selector for mobile devices as well to cope with that:

![image](https://user-images.githubusercontent.com/6613614/226120972-f42e2903-fe4b-44c5-bdfb-8c45d3c7e5c3.png)

**Comment by st3iny** [comment]
Development is now tracked in:
- https://github.com/nextcloud/contacts/issues/3305
- https://github.com/nextcloud/contacts/issues/3284
- https://github.com/nextcloud/contacts/issues/3304
