### ISSUE TITLE
Ability to have custom labels

### ISSUE THREAD

**Issue by pieplu** [nextcloud/contacts#27]
### Expected behaviour

* Be able to create custom vCardMeta (exemple: skype name, github name, etc...)
* Be able to add custom vCardMeta options (exemple, for "tel": WORK,CELL)
* Can be on the admin of contact app, or directly on the contact edit

### Actual behaviour

* We can only use pre-defined vCardMeta
* We can only use pre-defined option for an new tel, email, or other

**Comment by skjnldsv** [comment]
You mean labels?

**Comment by pieplu** [comment]
I'm not sur to understand. But it's more like "[TYPE](https://tools.ietf.org/html/rfc6350#section-5.6)" . Used for [TEL](https://tools.ietf.org/html/rfc6350#section-6.4.1), EMAIL, etc...

**Comment by ionl** [comment]
On gmail contact (or others), for tel, we can edit default label (instead of "Home","Work","Mobile", etc.). It's very usefull, because with some enterprises, there are a lot of differents entities.
Regards,

**Comment by olantrust** [comment]
The Originator was basically asking two things:
"Be able to create custom vCardMeta (exemple: skype name, github name, etc...)"
I.e. Custom fields
"Be able to add custom vCardMeta options (exemple, for "tel": WORK,CELL)"
I.e. Custom labels

I've created the issue #303 to deal with the first request separately as they are quite distinct.

I think it would help Users understand to re-name this Issue to 'Add ability for Custom Labels' to be clear.

This would mean that each label (usually Work, Home, Other) could also be assigned manually by the User, as is already possible on other systems, for example Android, Google, Apple etc...

**Comment by olantrust** [comment]
Please change the title of this to: Ability to have custom labels
As #303 already deals with custom fields, and to make it clearer what this issue is about.
Thanks @skjnldsv @ionl

**Comment by GLLM** [comment]
I definitely miss this ability ... When I imported my contacts from Google, I lost plenty of custom labels (mostly phones labels), making my contatcs unusable.

Thanks !

**Comment by livingsilver94** [comment]
I need this feature too. I've just migrated my Google contacts to Nextcloud and I got a bunch of phone numbers with an blank label.

**Comment by bpcurse** [comment]
I would greatly appreciate this feature as well.
As discussed in https://github.com/nextcloud/contacts/issues/672 there is a lot more instant messaging systems than provided. At least a label called "others" is badly needed. Our organizations needs "Threema" as an example.

**Comment by skjnldsv** [comment]
Hey everyone!
You can find the final release update here: https://github.com/nextcloud/contacts/pull/991
I added the support for ITEM.xxx properties, but also a support to allow custom labels! This is a huge step forward and I would need some help testing this feature before pushing a new release.

Thanks :)
@bpcurse, @pieplu,  @ionl, @olantrust, @GLLM, @livingsilver94, @WNiels, @joekerna, @blkeller, @auberginepop, @daniel-illi, @fazlerabbi37, @hanzei, @kromuchi

**Comment by skjnldsv** [comment]
Tes build have been updated on https://github.com/nextcloud/contacts/pull/991#issue-260272203
Please make sure you're trying the most updated build :v:
