### ISSUE TITLE
Contacts app shows only a blank screen in firefox

### ISSUE THREAD

**Issue by tomdeck** [nextcloud/contacts#2709]
### Describe the bug

When I go to the Contacts app in Nextcloud (tried 22.2.6 and 23.0.3) I get a blank page in Firefox - only the top line with the apps is visible. In firefox, the browser console shows this error, not sure if related:
Uncaught SyntaxError: private fields are not currently supported
contacts-main.js:2:386917

The same page works correctly in the browser Falkon.

### Steps to reproduce

1. Log in to nextcloud
2. Click on the Contacts app

### Expected behavior

List of contacts should appear.

### Actual behavior

Only the top line with the icons for apps is visible, below these, the page is completely empty.
Tried this with Nextcloud version 22.2.6 (all apps up-to-date) and with the recently upgraded 23.0.3 (all apps up-to-date).
I tried installing 23.0.3 into a new directory and the same issue is there.

### Contact version

4.1.0

### Operating system

openSUSE Leap 15.3

### PHP engine version

PHP 7.4

### Web server

Apache (supported)

### Database

PostgreSQL

### Operating system

openSUSE Leap 15.3

### List of activated Apps

```shell
The process control (PCNTL) extensions are required in case you want to interrupt long running commands - see https://www.php.net/manual/en/book.pcntl.php
Enabled:
  - accessibility: 1.9.0
  - activity: 2.15.0
  - bruteforcesettings: 2.3.0
  - calendar: 3.2.2
  - circles: 23.1.0
  - cloud_federation_api: 1.6.0
  - comments: 1.13.0
  - contacts: 4.1.0
  - contactsinteraction: 1.4.0
  - dashboard: 7.3.0
  - dav: 1.21.0
  - deck: 1.6.1
  - federatedfilesharing: 1.13.0
  - federation: 1.13.0
  - files: 1.18.0
  - files_pdfviewer: 2.4.0
  - files_rightclick: 1.2.0
  - files_sharing: 1.15.0
  - files_trashbin: 1.13.0
  - files_versions: 1.16.0
  - files_videoplayer: 1.12.0
  - firstrunwizard: 2.12.0
  - forms: 2.4.0
  - logreader: 2.8.0
  - lookup_server_connector: 1.11.0
  - mail: 1.11.7
  - nextcloud_announcements: 1.12.0
  - notifications: 2.11.1
  - oauth2: 1.11.0
  - password_policy: 1.13.0
  - photos: 1.5.0
  - privacy: 1.7.0
  - provisioning_api: 1.13.0
  - recommendations: 1.2.0
  - richdocuments: 5.0.3
  - richdocumentscode: 21.11.204
  - serverinfo: 1.13.0
  - settings: 1.5.0
  - sharebymail: 1.13.0
  - spreed: 13.0.4
  - support: 1.6.0
  - survey_client: 1.11.0
  - systemtags: 1.13.0
  - text: 3.4.1
  - theming: 1.14.0
  - twofactor_backupcodes: 1.12.0
  - updatenotification: 1.13.0
  - user_status: 1.3.1
  - viewer: 1.7.0
  - weather_status: 1.3.0
  - workflowengine: 2.5.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_ldap
```

### Nextcloud Signing status

```shell
No errors have been found.
```

**Comment by tomdeck** [comment]
Firefox version: 89.0 (64-bit), under openSUSE 15.3

**Comment by tacruc** [comment]
I have the same Visual issue i.e. a blank screen.
Browser Console logs:
```
The resource from “https://domain.com/apps/contacts/js/contacts-main.js?v=2b273cd8-2” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff). contacts
Loading failed for the <script> with source “https://domain.com/apps/contacts/js/contacts-main.js?v=2b273cd8-2”. contacts:56:1
The resource from “https://domain.com/apps/dashboard/” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff). contacts
```

Not sure if it is the same or a different Issue.

**Comment by wargreen** [comment]
Same here with firefox 78.9.0esr and 87.0-2 from debian
Fixed with 91.8.0esr-1

**Comment by Quix0r** [comment]
> Firefox version: 89.0 (64-bit), under openSUSE 15.3

Mine is `78.12.0esr (64-bit)` under Debian here. It did work with previous stable version.

**Comment by tomdeck** [comment]
I updated firefox to 91.8.0esr (64-bit), nothing else changed, and contacts are available now.
So for me this issue can be closed.

**Comment by Quix0r** [comment]
Not here: `Uncaught SyntaxError: private fields are not currently supported`. And maximum `78.15.0esr-1~deb11u1` is available. I'm using Debian Unstable. Please don't tell me you don't support ESR?

**Comment by Quix0r** [comment]
It LOOKS like private fields are experimental in most browsers, except Google Chrome. So please do not use them (yet). Firefox 91.8 [seem](https://searx.mxchange.org/search?q=firefox%2091.8&categories=general&language=en-US) to be also in ESR?

**Comment by Quix0r** [comment]
I found [here](https://github.com/mrdoob/three.js/issues/22434#issuecomment-906287306=) that you can somehow use babel for older browsers?

**Comment by Quix0r** [comment]
@ChristophWurst Yes, okay. Still I'm getting that message and a blank contacts page. I sometimes really need access my contacts over the web page (as sync with Thunderbird isn't working due to enabled 2FA (which I'm unwilling to disable) and I cannot set up an app-specific password there. :-(

**Comment by Moe1369** [comment]
Same issue on the newest contacts.

**Comment by Quix0r** [comment]
> Same issue on the newest contacts.

I guess you have an error message somewhere? Is also a backtrace included?

**Comment by Moe1369** [comment]
Close again. Reverse Proxy nginx error regarding MIME Type. Chrome ignores that error and accepts .mjs files as application/octet-stream.  Fix should look like something like this:
```

http {
    include mime.types;
    default_type  application/octet-stream;
    types {
        text/javascript mjs;
        application/wasm wasm;
    }
```
