### ISSUE TITLE
Support threema as contact type for IM

### ISSUE THREAD

**Issue by frlan** [nextcloud/contacts#2716]
### Is your feature request related to a problem? Please describe.

I want to store my threema-contact-ID using contacts app.

### Describe the solution you'd like

Enable support of threema inside pulldown of IM widget

### Describe alternatives you've considered

--

### Additional context

--

**Comment by mgrunwald** [comment]
Wow, two in almost four years... still, I'd like to have it :)

**Comment by frlan** [comment]
Wondering whether it's as easy as 

```diff
diff --git a/src/models/rfcProps.js b/src/models/rfcProps.js
index 145c5a9c..1e21caa1 100644
--- a/src/models/rfcProps.js
+++ b/src/models/rfcProps.js
@@ -192,6 +192,7 @@ const properties = {
                        { id: 'KAKAOTALK', name: 'KakaoTalk' },
                        { id: 'MATRIX', name: 'Matrix' },
                        { id: 'ZOOM', name: 'Zoom' },
+                       { id: 'THREEMA', name: 'Threema' },
                ],
        },
        tel: {

```
