### ISSUE TITLE
contact app auto-adds new contacts to 6 groups G E N R A L

### ISSUE THREAD

**Issue by bahbarnett** [nextcloud/contacts#275]
### Steps to reproduce
1. Create a contact, all is fine
2. Move on, and create a second or more contacts
3. Groups G E N R A L are created and assigned to the new contact, when you click on 'new contact'

### Expected behaviour
New contacts should have no group, or a preferred group -- but, not automatically create 6 new groups with random letters.

### Actual behaviour
6 groups are created, G E N R A L

### Server configuration
**Operating system**: Debian Jessie

**Web server:**  Apache

**Database:**  MySQL 5.5

**PHP version:**  PHP 5.6.30-0+deb8u1

**Nextcloud version: 12.0.0

**Contacts version:** 1.5.3

**Updated from an older Nextcloud or fresh install:**  Updated from 11.x 

**Signing status:**

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.

"No results found"

``

**Comment by jonatoni** [comment]
@bahbarnett please have a look at the issue #244 if they are similar

**Comment by bahbarnett** [comment]
Identical issue.  Thanks.  Closing.
