### ISSUE TITLE
Question when deleteing a contact

### ISSUE THREAD

**Issue by DiGGeR2** [nextcloud/contacts#276]
### Steps to reproduce
1. Create a contact
2. Delete it
3.

### Expected behaviour
Question about I want really delete it

### Actual behaviour
No question...

PS : sorry but i cannot put this requestion in "Pull request"... it ask me to choose a branch etc.

**Comment by skjnldsv** [comment]
I don't understand what you are trying to say. 🤔😕

**Comment by awallat** [comment]
I think what @DiGGeR2 is trying to say is that there's no confirmation when you delete a contact. I also find it quite disturbing and wish that there would be a dialog or an undo button, like in all those other applications.

**Comment by skjnldsv** [comment]
You're probably right! 
If so, let's create a more understandable issue. :)

**Comment by DiGGeR2** [comment]
Sorry for my english :) but yes  I find cool To have question with "do you really  want To delele  this contact.. .."Best regardsLe 22 août 2017 05:40, John Molakvoæ <notifications@github.com> a écrit :You're probably right!
If so, let's create a more understandable issue. :)

**Comment by skjnldsv** [comment]
No worries! 😉
