### ISSUE TITLE
Huge design regressions on server master

### ISSUE THREAD

**Issue by st3iny** [nextcloud/contacts#2777]
### Describe the bug

The app looks utterly broken on current server master. This might be caused by recent theming and styling changes.

I also tested stable24 and it is not affected.

### Steps to reproduce

1. Checkout server master.
2. Checkout contacts master.
3. Look at the app in the browser.

### Expected behavior

The app should look the same on server stable24 and master.

### Actual behavior

It looks broken on server master. It does not look broken on server stable24.

![Screenshot_20220607_123713](https://user-images.githubusercontent.com/1479486/172361414-d7f34787-2912-4f89-8753-a36fc288e1be.png)

### Contact version

master

**Comment by ChristophWurst** [comment]
Some parts should be improved with https://github.com/nextcloud/contacts/pull/2808

**Comment by st3iny** [comment]
Reopened because #2817 is still pending.
