### ISSUE TITLE
The date  fields are not working

### ISSUE THREAD

**Issue by xh3n1** [nextcloud/contacts#278]
### Steps to reproduce
Pick a date on the birthday or Date of death fields.

### Expected behaviour
The date should be picked. For example: 12/05/1994

### Actual behaviour
I can't pick the date.

### Server configuration

**Operating system**:
Ubuntu 16.04

**Nextcloud version:** (13.0.0 alpha)

**Contacts version:** (1.5.4)

#### Browser log
```

a) The console log
uncaught exception: Missing instance data for this datepicker
"Error: [ngRoute:norout] Tried updating route when with no current route
 ...
```

**Comment by skjnldsv** [comment]
This is related to a recent change to the jQuery calendar picker script
The clickable elements are now links with a href defined by a hash
`<a class="ui-state-default" href="#">9</a>`

This initiate a change in the url and angular is debuging the fact that this hash is invalid

Fix: use `javascript:void(0)` and not `#`

**Comment by skjnldsv** [comment]
I need to investigate, but this should come from server. :)

**Comment by skjnldsv** [comment]
Can't be changed server side. This is messing with the angular routeProvider.
Will fix asap.
