### ISSUE TITLE
Confirm before importing contacts

### ISSUE THREAD

**Issue by bertptrs** [nextcloud/contacts#2788]
### Is your feature request related to a problem? Please describe.

When you click a `.vcf` file in the Files app, you are immediately transfered to the Contacts app which will start importing the VCF file. This can lead to undesired situations where you import a large amount of contacts into your contacts, either resulting in a mess or even duplicate contacts.

### Describe the solution you'd like

The app could show a confirmation window where you still need to click a button before it would start the import process. That also has the nice benefit that you could also select the destination contact list to import into.

### Additional context

Contacts 4.1.1, Nextcloud 24.0.1

**Comment by nolden** [comment]
This just happened to me as well, accidentally clicking on the contacts backup vcf file presented on the Dashboard. And just using browser's back triggered another import, so all my contacts are now tripled. I would vote for labeling this as a bug, not an enhancement. Is there an easy way to get rid of all the duplicates from within Nextcloud?

**Comment by llucax** [comment]
I was also just bitten by this. It is really ugly. Also it doesn't ask in which address book to import contacts, so it completely littered my main address book. 

I agree that even when it is not a *bug* per se, this is a serious usability issue, so please either mark is as a bug anyway or maybe add a higher priority to it?
