### ISSUE TITLE
cURL error 35: OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to github.com:443 

### ISSUE THREAD

**Issue by vermaden** [nextcloud/contacts#280]
Nextcloud works very good, I am not able to install Contacts app.

### Steps to reproduce
1. Click Enable to 'add' Contacts app.

### Actual behaviour
After clicking the 'Enable' button I get this error:
cURL error 35: OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to github.com:443 

### Server configuration
**Operating system**:
FreeBSD 11.1-RELEASE

**Web server:**
NGINX 1.12

**Database:**
PostgreSQL 9.6.3

**PHP version:**
PHP 7.0.21

**Nextcloud version:** (see Nextcloud admin page)
12.0.1

**Contacts version:** (see Nextcloud apps page)
(dit not wanted to install)

**Updated from an older Nextcloud or fresh install:**
12.0.0 (behaviour was the same as is now)

**Signing status:**
No errors have been found.

**List of activated apps:**
Activity
File sharing
Gallery
LDAP user and group backend
Log Reader
Monitoring
Notifications
Password policy
PDF viewer
Share by mail
Theming
Update notification
Brute-force settings 

**Nextcloud configuration:**
{
    "system": {
        "instanceid": "XXXXXXXXXXXX",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "XXXXXXXX",
            "YYYYYYYY"
        ],
        "datadirectory": "\/var\/db\/nextcloud\/data",
        "overwrite.cli.url": "https:\/\/YYYYYYYY\/",
        "overwritehost": "YYYYYYYY",
        "overwriteprotocol": "https",
        "dbtype": "pgsql",
        "version": "12.0.1.5",
        "dbname": "ncdb",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\Memcached",
        "memcache.distributed": "\\OC\\Memcache\\Memcached",
        "memcached_servers": [
            [
                "localhost",
                11211
            ]
        ],
        "appstoreurl": "https:\/\/apps.nextcloud.com\/api\/v0",
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "remember_login_cookie_lifetime": 0,
        "session_lifetime": 60,
        "session_keepalive": false,
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "PLAIN",
        "mail_smtphost": "ZZZZZZZZ",
        "mail_smtpport": "10025",
        "log_type": "syslog",
        "logfile": "",
        "loglevel": "1",
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "theme": ""
    }
}

**Are you using external storage, if yes which one:** local/smb/sftp/...
Local ZFS Pool.

**Are you using encryption:** yes/no
Nope.

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
LDAP.

#### LDAP configuration (delete this part if not used)
(works / not part of the issue)

### Client configuration
**Browser:**
Firefox 45.7 (not related to the error)

**Operating system:**
(not related to the error)

**Comment by skjnldsv** [comment]
Don't think it's related to the contacts app. 😕 
@nickvergessen? @MorrisJobke?

**Comment by MorrisJobke** [comment]
Looks like a setup problem. Please ask for help in the forums: https://help.nextcloud.com/

Thanks

**Comment by vermaden** [comment]
Thanks.

For the reference:
https://help.nextcloud.com/t/curl-error-35-openssl-ssl-connect-ssl-error-syscall-in-connection-to-github-com-443/19248/2

**Comment by vermaden** [comment]
For the record ...

I was told by out _'network team'_ that access to **github.com:443** is set to allow so its probably server issue or curl issue ... but of course they lied and now as they REALLY allowed access to  **github.com:443** everything works properly.

Thanks You for suggestions and sorry for wasting your time.

Regards,
vermaden

**Comment by believerlyrics** [comment]
thanks for the idea 
[Hindi lyrics](url)
