### ISSUE TITLE
When creating a new contact the filtered groupname gets split up into separate groups and added to the contact

### ISSUE THREAD

**Issue by linuxpete** [nextcloud/contacts#282]
### Steps to reproduce
1. Create a contact (see contact1.png)
2. Add this contact to a group (see contact1.png  , groupname "gro up")
3. filter on the group and see the contact
4. Add a contact with the button "New Contact" (see contact2.png)
5. The app creates as much groups as there are different characters in the group name
6. See the created groups on the left panel (see contact3.png)

### Expected behaviour
Two behaviours come into mind:

1. automatically add the selected group (perhaps was the meaning of the programmer)

Or, less expected behaviour 
2, add no groups

### Actual behaviour
app adds as much groups as there are different characters in the selected groupname

**file : contact1.png**
![contact1](https://user-images.githubusercontent.com/7695965/29119085-07ddefba-7d05-11e7-941e-18c4e24dbf56.png)
**file : contact2.png**
![contact2](https://user-images.githubusercontent.com/7695965/29119086-07e0e828-7d05-11e7-99de-692933e4f2dd.png)
**file : contact3.png**
![contact3](https://user-images.githubusercontent.com/7695965/29119087-07e20140-7d05-11e7-9ec9-ee719b9dd287.png)

### Server configuration

**Operating system**:
Linux  4.1.19-v7+ #858 SMP Tue Mar 15 15:56:00 GMT 2016 armv7l GNU/Linux

**Web server:**
nginx version: nginx/1.6.2

**Database:**
mysqld  Ver 5.5.54-0+deb8u1-log for debian-linux-gnu on armv7l ((Raspbian)

**PHP version:**
PHP 5.6.30-0+deb8u1

**Nextcloud version:** (see Nextcloud admin page)
12.0.1

**Contacts version:** (see Nextcloud apps page)
1.5.3

**Updated from an older Nextcloud or fresh install:**
Updated from 12.0.0.

**Signing status:**

```
No errors have been found.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:

Enabled:
  - activity: 2.5.2
  - admin_audit: 1.2.0
  - apporder: 0.4.0
  - audioplayer: 2.0.2
  - bookmarks: 0.10.1
  - calendar: 1.5.3
  - comments: 1.2.0
  - contacts: 1.5.3
  - dav: 1.3.0
  - deck: 0.2.1
  - encryption: 1.6.0
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_external: 1.3.0
  - files_opds: 0.8.2
  - files_pdfviewer: 1.1.1
  - files_reader: 1.0.4
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - gpxedit: 0.0.7
  - gpxmotion: 0.0.4
  - gpxpod: 2.1.4
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.1
  - notes: 2.3.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - ownpad: 0.5.10
  - password_policy: 1.2.2
  - previewgenerator: 1.0.6
  - provisioning_api: 1.2.0
  - qownnotesapi: 17.5.0
  - rainloop: 5.0.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - spreed: 2.0.1
  - spreedme: 0.3.11
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - tasks: 0.9.5
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0
Disabled:
  - user_external
  - user_ldap

```

**Nextcloud configuration:**

```

{
    "system": {
        "instanceid": "ocl3mzv8sorh",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "xxx.xxxxx.nl"
        ],
        "datadirectory": "\/mnt\/owncloud\/owncloud",
        "overwrite.cli.url": "xx.xxxxx.nl",
        "dbtype": "mysql",
        "version": "12.0.1.5",
        "logtimezone": "UTC",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "loglevel": 0,
        "defaultapp": "bookmarks",
        "knowledgebaseenabled": "true",
        "custom_csp_policy": "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline' data: blob:; frame-src *; img-src *; font-src 'self' data: blob:; media-src *",
        "maintenance": false,
        "dbname": "ocdatabase",
        "dbhost": "127.0.0.1",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "theme": "",
        "data-fingerprint": "ab51ae68f88b0d5df560447d24ce885f",
        "mail_from_address": "oc",
        "mail_smtpmode": "smtp",
        "mail_domain": "xxxxxx.nl",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtphost": "mail.xxxxxx.nl",
        "mail_smtpauth": 1,
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "ssl",
        "enabledPreviewProviders": [
            "OC\\Preview\\Image",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\Epub",
            "OC\\Preview\\PDF",
            "OC\\Preview\\OpenDocument",
            "OC\\Preview\\StarOffice",
            "OC\\Preview\\MSOfficeDoc",
            "OC\\Preview\\MSOffice2003",
            "OC\\Preview\\MSOffice2007",
            "OC\\Preview\\FB2"
        ]
    }
}



**Are you using external storage, if yes which one:** yes : local

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:** No

### Client configuration
**Browser:**
Chrome : Versie 60.0.3112.90 (Officiële build) (64-bits)
Firefox : 54.0.1 (32-bits)

**Operating system:**
Win10

**CardDAV-clients:**
Webinterface Nextcloud


### Logs
#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

Fout tijdens het parsen van waarde voor ‘top’.  Declaratie genegeerd.  contacts
Fout tijdens het parsen van waarde voor ‘left’.  Declaratie genegeerd.  contacts
Gebruik van getAttributeNode() wordt niet meer ondersteund. Gebruik in plaats daarvan getAttribute().  core.js:7:1714
Gebruik van nodeValue-attribuut op attribuut wordt niet meer ondersteund. Gebruik in plaats daarvan value.  core.js:7:1714
Content Security Policy: De instellingen van de pagina blokkeerden het laden van een bron op self (‘script-src 'nonce-VTJzeERkRDdEdEI4Zk84ZWhRd0lQcnZiMjJReW81Nm5vTUh3WWhrSURVST06SkQxVGV1REpkdUVFVGRwSXhsbCtSTmk0OEJON3dmK2Y1K3JERDIwK2VoRT0=' 'unsafe-eval'’). Source: ondrop attribute on INPUT element. contacts
Error: Bad status: 412 dav.js:3649:27
GET 
XHR 
https://xx.xxxx.nl/ocs/v2.php/apps/notifications/api/v2/notifications [HTTP/1.1 200 OK 3398ms]
GET 
XHR 
https://xx.xxxxnl/ocs/v2.php/apps/notifications/api/v2/notifications [HTTP/1.1 200 OK [3318ms]]

**Comment by skjnldsv** [comment]
Duplicate #232

**Comment by linuxpete** [comment]
Hi @skjnldsv , thnks, looking forward to new version.
