### ISSUE TITLE
Show vcard as qrcode

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/contacts#283]
We can easily convert a vcard as a qrcode for easy flash and save in smartphone.
What do you think @nextcloud/contacts, do you feel like this is a good idea?

Example: 
![qrcode](https://user-images.githubusercontent.com/14975046/29124291-d3509c5c-7d18-11e7-9ad5-9934612a3772.png)

```
BEGIN:VCARD
VERSION:4.0
FN:Test 1
UID:dec8b591-ac52-437a-a9d1-060e714eb252
CATEGORIES:Group 1
END:VCARD
```

rel: https://www.npmjs.com/package/qrcode

**Comment by jancborchardt** [comment]
What’s the use-case here though? Nextcloud Contacts is all about syncing, so you already will have it in your phone?

Also, which phone contacts app has a QR code reader?

**Comment by skjnldsv** [comment]
@jancborchardt  it was for quick share! :) 
You just pop it up on your phone and add it to your contacts

**Comment by Matthias84** [comment]
Same here, this feature would be useful to share contacts with guests or strangers quickly and without creating accounts, ...

**Comment by creopard** [comment]
It's a great idea, but it might not be necessary, as there are already phone apps that do all that on the fly.
(e.g.: https://play.google.com/store/apps/details?id=com.teacapps.barcodescanner and many more)
On the one hand these apps can create/display a QR code by sharing a contact via the app and on the other hand it can also scan a QR code and create a new contact automatically.

**Comment by jancborchardt** [comment]
@skjnldsv I’d close this issue cause it’s more like a »we could do this thing« than »this is something we actually need«. Sharing contacts would be much simpler and more versatile by sharing a link.

**Comment by skjnldsv** [comment]
@jancborchardt There is a loooot of enhancement requests on the contacts app, and I can't get myself to close them ^^

**Comment by j-ed** [comment]
@skjnldsv Does this feature depend on any function provided by the server? I've discovered this function after I installed one of your test versions (20190328), but it seems not to work yet on my server (NC v15.0.5)

**Comment by skjnldsv** [comment]
@j-ed no, works from the app directly :)

**Comment by j-ed** [comment]
@skjnldsv That's weird. If I select that function on a contact only a white dot is shown on my server (NC v15.0.5 + FF v66.0.2):

![grafik](https://user-images.githubusercontent.com/2572764/55484548-f6c07780-5628-11e9-9f95-faaf0e8e4f62.png)

**Comment by skjnldsv** [comment]
@j-ed that's interesting :)
Any log in the browser console?

**Comment by j-ed** [comment]
If I select a contact the following messages are logged:
```
XHR - PROPFIND - https://<my-nextcloud-server>/remote.php/dav/addressbooks/users/<user>/Kontakte/1b3105f6-cdef-42e2-abc5-c752a4cc908b.vcf
[HTTP/2.0 207 Multi-Status 294ms]
ReferenceError: reference to undefined property "isdate" contacts.js:377:25934
ReferenceError: reference to undefined property "_tzm" contacts.js:377:23929
ReferenceError: reference to undefined property 2
```
If I select the **Generate QR code** function the following messages are logged:
```
ReferenceError: reference to undefined property 3 contacts.js:409:72621
ReferenceError: reference to undefined property "undefined" contacts.js:409:72376
ReferenceError: reference to undefined property "recognizers" contacts.js:135:11259
ReferenceError: reference to undefined property "enable" contacts.js:135:10524
ReferenceError: reference to undefined property 1 contacts.js:135:11710
port already set to: page
```

**Comment by skjnldsv** [comment]
@j-ed those messages are not complete.
I would need the more detailed ones, you should have the ability to expand those errors, right?

I can also just create a debug release for you to try.
[contacts.tar.gz](https://github.com/nextcloud/contacts/files/3039224/contacts.tar.gz)

**Comment by j-ed** [comment]
@skjnldsv I've installed the app, updated the server configuration, cleared the browser cache and started testing the function again. Unfortunately it shows less information than before but the result is the same. To sum up my tests with different browsers:
- Firefox 66.0.2 - only a dot is shown 😞 
- Microsoft Edge - a QR code is displayed. 👍 
- Vivaldi - a QR code is displayed. 👍

**Comment by skjnldsv** [comment]
> Unfortunately it shows less information than before

what do you mean by that? :thinking:

**Comment by j-ed** [comment]
@skjnldsv With the release you provided I couldn't see reference errors anymore. Only the following messages are shown:

![20190403_nc_contacts_app_qr_code_test](https://user-images.githubusercontent.com/2572764/55498033-e917eb80-5642-11e9-8e4f-40e10f5e5ab9.png)

**Comment by skjnldsv** [comment]
@j-ed thx! I fixed in on master!
It will be part of this week's release (3.1.0)

**Comment by j-ed** [comment]
@skjnldsv congrats! You're awesome 🥇

**Comment by reos-rcrozier** [comment]
> What’s the use-case here though? Nextcloud Contacts is all about syncing, so you already will have it in your phone?
> 
> Also, which phone contacts app has a QR code reader?

One use case is creating QR codes for staff to share at in-person events using their phone instead of business cards.
