### ISSUE TITLE
Alignment of app settings elements

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/contacts#2830]
### Describe the bug

Things are floating around

![Bildschirmfoto vom 2022-07-13 15-43-33](https://user-images.githubusercontent.com/1374172/178748505-5b86ca6d-5b4a-41bb-bfe5-e600616be8e5.png)

### Steps to reproduce

1. Open the Contacts app
2. Open the settings bottom left

### Expected behavior

Good design

### Actual behavior

Bad design

### Contact version

main

### List of activated Apps

```shell
a
```

**Comment by ChristophWurst** [comment]
@GretaD you mentioned a PR that would fix that. Could you link it and double-check the design works like before with that PR?

**Comment by szaimen** [comment]
I think it was this one: https://github.com/nextcloud/contacts/pull/2807
