### ISSUE TITLE
Weird cut off border around "Create new group" name input

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/contacts#2831]
### Describe the bug

There is a mix of thick and thin border around the new group input

### Steps to reproduce

1. Open the app
2. Try to create a new group

### Expected behavior

Smooth design

### Actual behavior

![Bildschirmfoto vom 2022-07-13 15-47-19](https://user-images.githubusercontent.com/1374172/178749447-e86b507b-69cd-4598-b3f9-b79ff271d5b5.png)

### Contact version

main

### List of activated Apps

```shell
n/a
```

### Nextcloud Signing status

```shell
n/a
```

**Comment by st3iny** [comment]
This seems to be a regression from NC 25.

**Comment by ChristophWurst** [comment]
Nope
