### ISSUE TITLE
Could not find initial state contactsinteraction of contacts

### ISSUE THREAD

**Issue by wolegis** [nextcloud/contacts#2867]
### Describe the bug

Web GUI, logged in, select Contacts tab => blank page (except top bar with symbols for various apps, search, notifications, etc.)

Logs on server side show nothing relevant. JS consol in Browser shows:

```
Uncaught Error: Could not find initial state contactsinteraction of contacts
    loadState index.js:24
    <anonymous> isContactsInteractionEnabled.js:25
    Webpack 3
        o
        <anonymous>
        <anonymous>
[index.js:24:10](webpack:///node_modules/@nextcloud/initial-state/dist/index.js)
    loadState index.js:24
    <anonym> isContactsInteractionEnabled.js:25
    Webpack 3
        o
        <anonym>
        <anonym>
```

### Steps to reproduce

Log into Nextcloud Wb GUI, select contacts tab (in top bar)

### Expected behavior

Usual content of contacts page (categories, list of contacts, details of selected contact) should be displayed

### Actual behavior

blank page (except top bar with symbols for various apps, search, notifications, etc.)

### Contact version

4.2.0

### Operating system

Arch Linux kernel 5.18.12

### PHP engine version

PHP 8.1

### Web server

Nginx

### Database

PostgreSQL

### Additional info

Nextcloud version: 24.0.3

Browser: Firefox 102.0

```
$ occ app:list
Enabled:
  - accessibility: 1.10.0
  - activity: 2.16.0
  - bookmarks: 10.5.1
  - calendar: 3.4.2
  - circles: 24.0.0
  - cloud_federation_api: 1.7.0
  - comments: 1.14.0
  - contacts: 4.2.0
  - contactsinteraction: 1.5.0
  - dashboard: 7.4.0
  - dav: 1.22.0
  - extract: 1.3.5
  - federatedfilesharing: 1.14.0
  - federation: 1.14.0
  - files: 1.19.0
  - files_pdfviewer: 2.5.0
  - files_rightclick: 1.3.0
  - files_sharing: 1.16.2
  - files_trashbin: 1.14.0
  - files_versions: 1.17.0
  - files_videoplayer: 1.13.0
  - firstrunwizard: 2.13.0
  - logreader: 2.9.0
  - lookup_server_connector: 1.12.0
  - mail: 1.13.6
  - notifications: 2.12.0
  - oauth2: 1.12.0
  - password_policy: 1.14.0
  - photos: 1.6.0
  - privacy: 1.8.0
  - provisioning_api: 1.14.0
  - recommendations: 1.3.0
  - serverinfo: 1.14.0
  - settings: 1.6.0
  - sharebymail: 1.14.0
  - systemtags: 1.14.0
  - tasks: 0.14.4
  - text: 3.5.1
  - twofactor_backupcodes: 1.13.0
  - updatenotification: 1.14.0
  - user_status: 1.4.0
  - viewer: 1.8.0
  - workflowengine: 2.6.0

Disabled:
  - admin_audit
  - encryption
  - files_external
  - nextcloud_announcements: 1.6.0
  - support: 1.6.0
  - survey_client: 1.6.0
  - theming: 1.9.0
  - user_ldap
  - weather_status: 1.0.0
```

**Comment by wolegis** [comment]
Probably a duplicate of #2339 . But since this issue showed no signs of activity I refrained from adding yet another *me too* comment

**Comment by harmonicoscillator** [comment]
I had this same bug for several weeks, and it turned out in my case it was due to multiple versions of the `contacts` app existing in both the 'read-only' app folder and the 'read-write' app folder.

At least for Arch Linux using the official package, there is a read-only folder located at
`/usr/share/webapps/nextcloud/apps/`
And a read-write folder located at
`/var/lib/nextcloud/apps/`

At some point in the past, the `contacts` app shipped in the read-only location, but recent archlinux Nextcloud package releases no longer ship it in that location so newer versions of the app live in the read-write location, but old versions remain in the old location.

I had to go to the read-only location and delete all the apps that were no longer owned by the nextcloud archlinux package:

```
cd  /usr/share/webapps/nextcloud/apps
pacman -Qo *
# check which apps are no longer owned by the `nextcloud` package
rm -r contacts <plus a lot more>
```

After deleting my contacts showed up again.

**Comment by wolegis** [comment]
@harmonicoscillator Thank you very much for your hint. This indeed solved my issue.

May I kindly ask whether you could share this information in the [troubleshooting section](https://wiki.archlinux.org/title/Nextcloud#Troubleshooting) of the Nextcloud article in the Arch Linux Wiki? If you don't want to (for whatever reasons) I will do so (after my vacation).

**Comment by wolegis** [comment]
https://wiki.archlinux.org/title/Nextcloud#Weird_behavior_of_one_or_more_apps
