### ISSUE TITLE
REQ low code layout per group

### ISSUE THREAD

**Issue by punkyard** [nextcloud/contacts#2873]
### Is your feature request related to a problem? Please describe.

contact details are quite messy - sorry to say
added fields mix one with another, sometimes in one place, sometimes in another

### Describe the solution you'd like

layout option for groups, grid for positioning, different templates 
when adding new contact through group list, the layout template for that group would appear in the details of the new contact

### Describe alternatives you've considered

All details already available in the detail of a new contact, in a fix layout (just not the phonetic ones ^^)
which would avoid going to "Add new property" to often

### Additional context

same layout concept, but for address books
very useful to professional usage ..

**Comment by jancborchardt** [comment]
There is a design review and some mockups over at https://github.com/nextcloud/contacts/issues/1923#issuecomment-1046688003
This would take care of the layout, so I would close this in favor of the issue over there if that’s ok? :)
