### ISSUE TITLE
Disable address books on a DAV level, not just visually.

### ISSUE THREAD

**Issue by 2andgi** [nextcloud/contacts#2879]
### Is your feature request related to a problem? Please describe.

Currently, disabling an address book is only a visual thing and doesn't really influence the availability of an address book on a DAV level. If I sync my contacts to a different client, the "disabled" address books still show up anyway.

### Describe the solution you'd like

Set the disabled property on a DAV level, so sync clients do not sync them any longer.

**Comment by miaulalala** [comment]
Please fill out the template questions.

**Comment by tcitworld** [comment]
Most sync clients (DAVx⁵, Thunderbird) allow to pick the address books to sync. iOS and MacOS allow you to "disable" some calendars as well even though they are synced.

What's the main reason of wanting to disable them at the DAV level? Performance? Not having to deal with a very long list in clients if you have many?

**Comment by miaulalala** [comment]
both of those points you brought up at the end, plus sysadmin complaints that "enable / disable" should do what it says on the can, not just disable it visually.

**Comment by tcitworld** [comment]
The main way I can see this working is having extra collection types like « DisabledAddressbook » and « DisabledCalendar » similar to how DeletedCalendar works for calendar trashbin, so that we're able to have these collections in our own apps which use DAV without the 3rd-party clients detecting them.

**Comment by miaulalala** [comment]
We won't be implementing this after all as it will break other clients. An admin managed address book type feature is to be preferred.
