### ISSUE TITLE
Packages Missing in contacts

### ISSUE THREAD

**Issue by DineshRefex** [nextcloud/contacts#2890]
### Describe the bug

Hi there, I'm using Nextcloud - 24.0.1 version . In Contacts app , many packages are missing (like .github, package-lock.json, package.json, Src directory, etc.,). Though I have installed this contact app from Nextcloud , these packages are missing .

I manually created these files and directories , also changed their ownership . But still its not working, So can anyone help to find where I can able to find all these packages . Or is there any option to manually download contacts app?

### Steps to reproduce

i'm working on organization.

### Expected behavior

I want all these packages which are available in this https://github.com/nextcloud/contacts.
![Screenshot (21)](https://user-images.githubusercontent.com/105905278/185549585-81761f05-bfff-4ba4-8d12-fac398dc6490.png)
![Screenshot (20)](https://user-images.githubusercontent.com/105905278/185549577-e515576c-651a-4fb5-af29-08858a8f0762.png)

### Actual behavior

Most of the packages are missing
![Screenshot (19)](https://user-images.githubusercontent.com/105905278/185548810-aaf03d49-7ad8-446f-9174-6505b73ff593.png)

### Contact version

4.2.0

### Operating system

Ubuntu 20.0.8

### PHP engine version

PHP 8.0

### Web server

Apache (supported)

### Database

MySQL

### Additional info

I'm trying to implement organization chart in contacts for that some packages are need but it does not exit for me. So for that reason, I'm request somebody help me to overcome this issue. Thank you!

**Comment by ChristophWurst** [comment]
You are looking at a production build. Anything in https://github.com/nextcloud/contacts/blob/main/.nextcloudignore is removed because it is not required.

If you would like to develop then git clone the app and follow https://github.com/nextcloud/contacts#build-the-app.

**Comment by DineshRefex** [comment]
Thank you for the support @ChristophWurst. Your hint's helped me. Now Organization chart is working. how can i make a tree with it.
