### ISSUE TITLE
Contacts fails to install on Nextcloud 24

### ISSUE THREAD

**Issue by grosjo** [nextcloud/contacts#2897]
### Describe the bug

Using https://download.nextcloud.com/server/installer/setup-nextcloud.php, Nextcloud 24 installs properly but Contacts is /not/ installed, and is /not/ available in the list of app in the menu

### Steps to reproduce

Just install using https://download.nextcloud.com/server/installer/setup-nextcloud.php

### Expected behavior

Contacts available and enabled

### Actual behavior

Contacts not available to be enabled

### Contact version

n.a.

### Operating system

Linux

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database

MariaDB

**Comment by ChristophWurst** [comment]
The app is on https://apps.nextcloud.com/apps/contacts. It should be installable.

**Comment by tcitworld** [comment]
It's not installed *by default* if that's what you mean.

**Comment by grosjo** [comment]
No, it was not working. Anmyway, NC30 solved the topic
