### ISSUE TITLE
Can't switch a contact's addressbook

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/contacts#2942]
### Describe the bug

I can't switch between address books

### Steps to reproduce

1. Create an address book or even two
2. Create a new contact
3. Try to select that AB for the new contact

### Expected behavior

*Address book* multiselect lets me pick the AB

### Actual behavior

My default AB *contacts* is selected

| ![Bildschirmfoto vom 2022-09-19 15-10-36](https://user-images.githubusercontent.com/1374172/191024910-c160c33c-4614-4363-8e71-db1c37340d95.png) | ![Bildschirmfoto vom 2022-09-19 15-10-39](https://user-images.githubusercontent.com/1374172/191024907-98f34823-c30e-4a28-9587-72b8e35a2a50.png) |
|---|---|

### Contact version

v5

**Comment by JuliaKirschenheuter** [comment]
@ChristophWurst could you please test it again? I've tried it, but can't reproduce - everything works.

**Comment by ChristophWurst** [comment]
Fixed by https://github.com/nextcloud/contacts/pull/2997
