### ISSUE TITLE
Left sidebar: Badge counter doesn't use primary color

### ISSUE THREAD

**Issue by st3iny** [nextcloud/contacts#2948]
### Describe the bug

The badge counters in the left sidebar don't use the primary color. They use the primary color in other apps (e.g. Mail).

### Steps to reproduce

1. Open the Contacts app.
2. Observe left sidebar.

### Expected behavior

The badge counter should use the primary color.

### Actual behavior

They are gray. 

![image](https://user-images.githubusercontent.com/1479486/191475445-1e8a57a3-06f5-4e8c-bd79-0d75f014f7c0.png)

Take a look at the Mail app for comparison:

![image](https://user-images.githubusercontent.com/1479486/191475571-93888545-1a01-41d8-aec5-e193c2dc03e5.png)

### Contact version

main

**Comment by st3iny** [comment]
cc @GretaD You already had an idea how to fix this easily.

**Comment by GretaD** [comment]
yes, do the same in contacts like we did on mail: https://github.com/nextcloud/mail/pull/7058

the appnavigationcounter is not used anymore

**Comment by ChristophWurst** [comment]
appnavigationcounter should be marked for deprecation then

**Comment by GretaD** [comment]
> appnavigationcounter should be marked for deprecation then

it is on vue: https://github.com/nextcloud/nextcloud-vue/blob/master/src/components/NcAppNavigationCounter/NcAppNavigationCounter.vue
