### ISSUE TITLE
Contacts list: "Close navigation" toggle has uneven margins

### ISSUE THREAD

**Issue by st3iny** [nextcloud/contacts#2951]
### Describe the bug

The margins of the "Close navigation" toggle in the top left corner has uneven margins.

![toggle-margins](https://user-images.githubusercontent.com/1479486/191478755-7aab2304-efcd-4a2a-bedc-28c2dd378297.png)

### Steps to reproduce

1. Open Contacts app.
3. Observe the "Close navigation" toggle in the top left corner next to the search bar.

### Expected behavior

The margins to the left and the right of the toggle should be the same.

### Actual behavior

The margins are different.

### Contact version

main

**Comment by hamza221** [comment]
<img width="1334" alt="image" src="https://github.com/nextcloud/contacts/assets/40746210/59457099-a877-40f5-a703-0e4a710a746e">
<img width="801" alt="image" src="https://github.com/nextcloud/contacts/assets/40746210/bcc712f9-929c-4802-9ece-052d0b2f7918">
Can't reproduce on latest main
