### ISSUE TITLE
Left sidebar: Move settings to a modal

### ISSUE THREAD

**Issue by st3iny** [nextcloud/contacts#2952]
### Is your feature request related to a problem? Please describe.

The settings in bottom left corner are awkward to use and have some design issues.

![image](https://user-images.githubusercontent.com/1479486/191479212-fda9f0ef-a853-4efa-bba7-a4c17ed9e9d6.png)

### Describe the solution you'd like

Move the whole settings section to a modal.

**Comment by ChristophWurst** [comment]
I looked into this as well for a bit. Unfortunately the settings modal doesn't come with a standardized trigger button. E.g. in Talk they mimic the legacy apps styling: https://github.com/nextcloud/spreed/blob/59257b1ef288a9a8da3912fdce1458f632904d78/src/components/LeftSidebar/LeftSidebar.vue#L106-L112

**Comment by JuliaKirschenheuter** [comment]
> I looked into this as well for a bit. Unfortunately the settings modal doesn't come with a standardized trigger button. E.g. in Talk they mimic the legacy apps styling: https://github.com/nextcloud/spreed/blob/59257b1ef288a9a8da3912fdce1458f632904d78/src/components/LeftSidebar/LeftSidebar.vue#L106-L112

Thank you! I've done it as well like this. Now i have to fix styles inside of the modal.

**Comment by JuliaKirschenheuter** [comment]
![image](https://user-images.githubusercontent.com/6078378/195044001-59ea0e84-dfb0-4f29-9988-62c123b25919.png)

This sorting inside of the modal makes no sense anymore. Should i comment it out for now and make follow-up ticket to find a right place for it?

**Comment by ChristophWurst** [comment]
It is maybe a bit of a strange place but please leave it visible and inside the modal

**Comment by JuliaKirschenheuter** [comment]
How does it look like? Ok for the first time? 
![image](https://user-images.githubusercontent.com/6078378/195091577-28e50507-d817-458d-9839-2174e61a7075.png)
