### ISSUE TITLE
Update to Nextcloud 25 design

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/contacts#2953]
### Is your feature request related to a problem? Please describe.

Nextcloud 25 comes with a new UI and this app needs to be adjusted.

### Describe the solution you'd like

- [x] https://github.com/nextcloud/contacts/pull/2917

### High priority

- [x] https://github.com/nextcloud/contacts/issues/2950
- [x] https://github.com/nextcloud/contacts/issues/2952

### Medium/low priority

- [x] https://github.com/nextcloud/contacts/issues/2948
- [ ] https://github.com/nextcloud/contacts/issues/2949
- [ ] https://github.com/nextcloud/contacts/issues/2951
- [ ] https://github.com/nextcloud/contacts/issues/2963
- [ ] https://github.com/nextcloud/contacts/issues/2964
- [ ] https://github.com/nextcloud/contacts/issues/2965
- [ ] https://github.com/nextcloud/contacts/issues/2966
- [ ] https://github.com/nextcloud/contacts/issues/2967
- [ ] https://github.com/nextcloud/contacts/issues/2968
- [ ] https://github.com/nextcloud/contacts/issues/2969
- [ ] https://github.com/nextcloud/contacts/issues/2970
- [x] https://github.com/nextcloud/contacts/issues/2971
- [ ] Implement a view mode https://github.com/nextcloud/contacts/issues/1923#issuecomment-1046688003

**Comment by st3iny** [comment]
I linked all tickets from the design review.
