### ISSUE TITLE
Contact details: Three dot menu of header is not vertically aligned properly

### ISSUE THREAD

**Issue by st3iny** [nextcloud/contacts#2967]
### Describe the bug

The three dot menu of the header in the contact details page should be vertically aligned with the second row of inputs.

![three-dot-menu-alignment](https://user-images.githubusercontent.com/1479486/191949715-137bfca5-f741-4544-a59f-612cd319427b.png)

### Steps to reproduce

1. Open the Contacts app.
2. Create a contact.
3. Edit this contact.
4. Observe the input group at the top (name, company, title etc).

### Expected behavior

The three dot menu on the right side should vertically aligned with the lower input row.

### Actual behavior

The menu is not aligned with the lower row. Instead, it's floating somewhere between both input rows.

### Contact version

main

**Comment by auroraanna** [comment]
Why should it be aligned with the lower row? The button doesn't have anything to do just with the lower row.

It looks different now on 5.4.0-beta.2:
![image](https://github.com/nextcloud/contacts/assets/81317317/cf091d50-5bf1-49f0-96b6-7c5056abd00c)

There's another button and there's centered vertically with the rest.

**Comment by st3iny** [comment]
I agree, it looks fine now. I think this ticket predates the design rework.
