### ISSUE TITLE
Contact details: Improve form layout

### ISSUE THREAD

**Issue by st3iny** [nextcloud/contacts#2968]
### Is your feature request related to a problem? Please describe.

The contact details form layout could be improved.

### Describe the solution you'd like

- [ ] Use a single column layout -> remove masonry
- [ ] All labels should have exactly the same width

![form-labels-width](https://user-images.githubusercontent.com/1479486/191950464-5e616a5d-f498-41e3-9db2-f99b3253b4c9.png)

**Comment by arnowelzel** [comment]
Also see https://github.com/nextcloud/contacts/issues/2699.

If you use CustomCSS you can add my stylsheet rules as a temporary fix until the app is fixed.

**Comment by ChristophWurst** [comment]
As far as I can see this is no longer an issue
