### ISSUE TITLE
Contact details: Weird "yp" suffix in property type selects

### ISSUE THREAD

**Issue by st3iny** [nextcloud/contacts#2971]
### Describe the bug

There is a weird "yp" suffix in some property type selects. 

Take a look at this example:

![yp-suffix](https://user-images.githubusercontent.com/1479486/191952061-3bfb7283-234b-4ae1-a3d7-b1ee756435ac.png)

### Steps to reproduce

1. Open the Contacts app.
2. Create a contact.
3. Edit this contact.
4. Observe the property type select of e.g. the phone number type.

### Expected behavior

There shouldn't be a suffix. It should just show the selected type e.g. "Home".

### Actual behavior

There is a weird suffix "yp" next to the actual type "Home".

### Contact version

main

**Comment by ChristophWurst** [comment]
T**yp**e
