### ISSUE TITLE
hovering over trashbin displays "Download"

### ISSUE THREAD

**Issue by JuangDse** [nextcloud/contacts#298]
### Steps to reproduce
1. hover over the trashbin (top right)

### Expected behavior
Should say "Delete"

### Actual behaviour
Says "Download"

### Server configuration
**Arch Linux**:
**Apache:**
**mysql:**
**php5:**
**Nextcloud 12
**Contacts 1.5.3:**
**Updated from an older Nextcloud :**
**List of activated apps:**
Enabled:
  - activity: 2.5.1
  - audioplayer: 2.0.2
  - calendar: 1.5.3
  - comments: 1.2.0
  - contacts: 1.5.3
  - dav: true
  - federatedfilesharing: true
  - files: 1.7.2
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_videoplayer: 1.1.0
  - gallery: 17.0.0
  - gpxedit: 0.0.7
  - gpxpod: 2.1.4
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.1
  - notes: 2.3.1
  - notifications: 2.0.0
  - passman: 2.1.2
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - tasks: 0.9.5
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.0
  - twofactor_totp: 1.3.0
  - updatenotification: 1.2.0
  - workflowengine: true

**Comment by xh3n1** [comment]
This issue has been fixed. Just be patient and wait for  the next update of the contacts app :)

**Comment by xh3n1** [comment]
This issue has been fixed. Just wait for  the next update of the contacts app :)
