### ISSUE TITLE
Cannot "Copy Link" when using Firefox

### ISSUE THREAD

**Issue by meichthys** [nextcloud/contacts#2980]
### Describe the bug

I cannot copy the address book link when using Firefox even though Nextcloud shows that the link was copied:
<img width="267" alt="Screen Shot 2022-09-25 at 9 41 33 PM" src="https://user-images.githubusercontent.com/10717998/192177699-422da3bc-e68d-4ddd-8752-b57f7297fe5a.png">

It works fine in Safari.

### Steps to reproduce

1. [In Firefox] Go to Nextcloud > Contacts > Settings
2. Click on ellipsis next to address book
3. Click "Copy Link"
4. Try to Paste link

### Expected behavior

Link to address book should be coppied.

### Actual behavior

Nothing is copied.

### Contact version

 5.0.0-alpha.3

### Operating system

Ubuntu (Nextcloud VM)

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database

PostgreSQL

### Additional info

Nextcloud has all permissions from firefox, so it should be a permissions issue.

Nothing seems to show in the browser console when clicking "Copy Link".

**Comment by ChristophWurst** [comment]
Possibly related to https://github.com/nextcloud/nextcloud-vue/issues/3275#issuecomment-1253436933

**Comment by ChristophWurst** [comment]
Related: https://github.com/nextcloud/calendar/issues/4526

**Comment by st3iny** [comment]
Fixed by https://github.com/nextcloud/contacts/pull/3012.
