### ISSUE TITLE
Missing Fields

### ISSUE THREAD

**Issue by olantrust** [nextcloud/contacts#302]
Currently the following fields are missing. This limits vCard/CardDAV 4 interoperability.  It also limits business usage of the Contacts app. In this list: _CAPITALS=CardDAV property name._

**Fields to add to 'Add field' list:**
_**Interests**_ (user-entered, multiple entries, comma-separated?) (INTEREST)
_**Related**_ (can relate the contact to existing individual and organisation contacts, or other entities.) (RELATED) (see list for auto-completion at para 7 below)

**Use vCard KIND property to organise contacts**
   
vCard permits five 'kinds' that can be allocated to each contact. These are: 'Organisation', 'Individual', 'Location' (i.e. venue, premises), 'Group' (automatically applied for group contacts). (There is also 'Application' which is not relevant for our purposes)

It is proposed that Nexcloud Contacts should apply these 'kinds' automatically to each contact to help Users manage and sort them:

_Individual_ - default type
_Group_ - applied automatically where a group contact is created
_Organisation_ - applied automatically if an Organisation name is entered and no FullName is entered)
_Location_ - applied automatically if user enters 'Location' info under 'Add Ext Field', and no FullName is entered.

User could change the auto-assigned Kind by selected 'Kind' from the 'Add Ext Field' dropdown.
Once added, users should be able to filter by Kind, making contact management simpler and more intuitive, for example showing only Groups, Organisations, Individuals or Locations.

**Timezone icon next to phone numbers**
Ability for user to set TIMEZONE vCard property per phone number (editable as small clock symbol next to phone numbers), thus avoiding losing a deal when waking up an overseas colleague at the wrong time.

 **Create an advanced drop-down list for extra fields - 'Add extra'.**
Thus a user would see both 'Add Field' and 'Add extra' when creating/editing a contact.
This would ensure that Users have access to a full range of fields, which is critical for many business users, without cluttering the interface or bothering those who don't need it. 
The 'Add extra' dropdown would be much longer and would include any previously created 'Custom fields' a User had entered (once this is available).

**Advanced fields to include in 'Add extra':**
Role (role within organisation such as Member, Client, or vocation, different to job title) (ROLE)
Account number (X-ACCOUNT)
Language (LANG)
Timezone for contact (auto-set by address entry, or set manually) (TZ)
Expertise (EXPERTISE)
Birthplace (BIRTHPLACE)
Key (encryption) (KEY)
Calendar (contact's calendar address) (CALURI)
Household (X-HOUSEHOLD)
Logo (for organisations, image upload) LOGO
Anniversary (ANNIVERSARY)
Agent (assistant etc) (AGENT)
Hobby (HOBBY)
Deathplace (DEATHPLACE)
Deathdate (can apply to dissolved organisations as well as deceased individuals) (DEATHDATE
Class (sensitivity) (CLASS)
Sound (attach short audio, for pronouncing name correctly etc..) (SOUND)
Free/Busy address (FBURL)
Scheduling email address (CALADRUR)
Kind (see explanation above) (KIND)

**Display alternative names NAME, ALTID**
Under 'Detailed Name' field, Alternative Name should be displayed. This could contain Maiden names, past names, formal names etc... The user should be able to enter multiple instances of the field (in some countries it's important to store both the formal and the familial name, and other users would want to store a name in the contact's indigenous language, and in their own language.

**dealing with MAIDENNAME property
MAIDENNAME and X-MAIDENNAME is relatively common in other systems.
It should sync with Nextcloud to 'NAME, ALTID'
For syncing compatability with other systems.

**List of types for _'Related'_ field dropdown box**
A User can choose multiple instances of the related field per contact.
User should be permitted free entry, but should have some suggested types (auto-complete). 
Ideally remembering types entered previously in the App.

_Basic types:_
Partner, Business partner, Association, Friend, Family, Housemate, Classmate, Colleague, College, Pet, Offspring, Parent, Neighbour, Spouse, Employer, Assistants
_Extended:_
Associate, Acquaintance, Next of Kin, Relative, School, Workmate, , Employee, Employer, Contractor, Contractee, Landlord, Tenant, Consultant, Constultee, Lawyer, Advisor, Client, Media agent, Members, Sibling

**Comment by jancborchardt** [comment]
@olantrust since this issue and others you report are strongly about business use, it would be cool if you could fund the development of the Contacts app through Bountysource: https://www.bountysource.com/teams/nextcloud/issues

This would be great especially since the Contacts app is completely community-driven, and I’m sure contributors like @skjnldsv and @irgendwie would appreciate it. :)

**Comment by olantrust** [comment]
We have funded other issues, though we are volunteers, and a non profit organisation, relying on donations, not a commercial business

_Sent from my Sony E6683 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by MisterY** [comment]
+1 for Relationships

**Comment by tflidd** [comment]
Issue for geo-coordinates: https://github.com/nextcloud/contacts/issues/485

**Comment by skjnldsv** [comment]
Duplicates:
- Use vCard KIND property to organise contacts #608 #213 

Done:
- List of types for _'Related'_ field

Wont be added:
- dealing with MAIDENNAME property
- Display alternative names NAME, ALTID
- Timezone icon next to phone numbers

We do not want to add properties that does not exists on the rfc.
UNLESS they're used in a lot of devices and by a lot of people and supported by famous connectors. 
Example [X-PHONETIC-FIRST-NAME](https://www.davdroid.com/manual/supported-contact-fields/)
