### ISSUE TITLE
Ability to create and remember custom fields

### ISSUE THREAD

**Issue by olantrust** [nextcloud/contacts#303]
_Not to be confused with custom labels_ #27 These issues need two separate bugs.

Currently almost all common addressbook systems allow custom field creation in some way.
For example, a business user needs to create a field: customertype, and use it for every contact.
A political user needs a field: constituency, and an organisational user needs a date field: membership renewal.

Zimbra Gmail etc.. allow this, and Zimbra and Outlook allow the user to select the data type.

Our app should allow:
Create custom:

On selection, a pop-up appears to the User where they can set:
'Field name:' 
'Field type:' (single line, multiple lines, yes/no, date, url, number, random number, [maybe in future: sequential number]), 
'Occurs:'(single, or multiple per contact).
'Appears:' (each time on main screen, each time in 'Add field' dropdown, this time only)

**Example:**
User wants to create a 'member' field.
User selects 'Add custom'
Pop-up screen presents:
User enters:
Field name: Member
Field type: Yes/no
Occurs: Single
Appears: Every new contact

The new field will now appear for the current contact, and each new contact created, and the User can tick the Member:'Yes' or 'No' tickboxes (or leave blank for unknown).

**Comment by skjnldsv** [comment]
I tend to aim for simplicity, but you have my attention! :)
Could you propose a mockup of what you suggest?
I'm not really sure how to implement this without breaking the nice fit we have between all of our properties.

**Comment by jancborchardt** [comment]
Where does Gmail allow this? Can you post a screenshot?

**Comment by olantrust** [comment]
![gmailcustom-screenshot_20170830_151041](https://user-images.githubusercontent.com/627140/29876742-77cc1388-8d95-11e7-94ee-c3d08ea3e1ba.png)

**Comment by olantrust** [comment]
Can we remove the needsinfo label now, or is there anything else we can clarify? It's not clear what information is still needed. Thanks
@skjnldsv @jancborchardt

**Comment by mhgithub20** [comment]
I need this too.  I also need CardDAV to be able to sync it to other systems.  I've found comments in other discussions indicating that the underlying core and CardDAV already support custom fields, but the web UI does not -- though I'm not in a position to verify that claim.  What is needed to transition this from a wish to an active project.  Do we need more votes in favor?  Do we need a bounty?

**Comment by bpmartin20** [comment]
I need this too. I also need CardDAV to be able to sync it to other systems. I've found comments in other discussions indicating that the underlying core and CardDAV already support custom fields, but the web UI does not -- though I'm not in a position to verify that claim. What is needed to transition this from a wish to an active project. Do we need more votes in favor? Do we need a bounty?

**Comment by skjnldsv** [comment]
> Do we need more votes in favor? Do we need a bounty?

Both can attract developers :)
Or you can add this yourself if you have the knowledge ;)

**Comment by skjnldsv** [comment]
Currently there a no plans to implement such a feature. Thus I will close this ticket for now. This is simply not on our roadmap for the near future. Thanks for your suggestions nonetheless! I really appreciate it :)

**Comment by punkyard** [comment]
imagine how precious this would be for professional usage though!
