### ISSUE TITLE
Contact export malformed

### ISSUE THREAD

**Issue by ph00lt0** [nextcloud/contacts#3035]
### Describe the bug
Export misses several fields. 

### Steps to reproduce

Taking an export from Nextcloud of all contacts and try to import them in Google or Icloud

### Expected behavior

All contacts to include all information. 

### Actual behavior

Contacts are missing the email. 

### Contact version

4.2.2

### Operating system

Ubuntu 20

### PHP engine version

PHP 8.0

### Web server

Apache (supported)

### Database

MySQL

### Additional info

Using Nextcloud snap package.

**Comment by ChristophWurst** [comment]
> Contacts are missing the email.

Could you post the export data so we can inspect it?

**Comment by ChristophWurst** [comment]
> Of course not. Why would I be sharing the contact data of one of my users. Ridiculous request.

https://nextcloud.com/contribute/code-of-conduct/

I meant to ask for an exemplary export of dummy data.

**Comment by joshtrichards** [comment]
> `EMAIL;TYPE="INTERNET,HOME":@ .**`
> in the export. I assume this is a non standard format as it's not recognized on import in any other contact system I have tried.

The format looks okay-ish (assuming the `@.**` part is really `user@tld.ocm`), but the INTERNET type isn't typical  and I don't see how it came from us originally. These are the only exports for the EMAIL field I can manage to generate from contacts created via the Contacts app and exported:

```
EMAIL;TYPE=WORK:jsmith@abc-not-really.com
EMAIL;TYPE=OTHER:jsmith@personal-only.com
NEXTCLOUD1.EMAIL;TYPE=HOME:jsmith@custom-address-type.com
```

So I can't figure out how you ended up with contacts with that type of `EMAIL` field. 

- Have you used other CardDAV clients besides the Contacts app itself in Nextcloud?
- Were the contact(s) in question imported into Nextcloud from elsewhere originally?

**Comment by jancborchardt** [comment]
@ph00lt0 like Christoph already said above, please keep in mind that we have a code of conduct: https://nextcloud.com/contribute/code-of-conduct/
Asking for help on debugging an issue via logs or dummy data is reasonable, so no wonder it can not be fixed if this is not provided. If you don’t use Nextcloud anymore, closing the issue is enough and it doesn’t need to be insulting.
