### ISSUE TITLE
Custom default fields and layout order

### ISSUE THREAD

**Issue by olantrust** [nextcloud/contacts#304]
#253 Helped display more default fields.
However, many users (business and personal) would like to save huge amounts of time when regularly entering contact details, by personalising what fields and order is displayed by default.
Also, it is very poor usability for users scrolling through multiple contacts and trying to scan information, for each contact to have different fields appearing in different places, and even different columns.

**Resolution:**
There should be an Admin preference for layout.
In it Admin can select:
a) Which fields to display by default (including custom fields)
b) Which column they should appear in by default.
c) Which order they should appear in.

**Comment by jancborchardt** [comment]
The default is showing name, email, phone and address. This is an absolutely sane default used by Android contacts etc.

Offering a completely custom preference for layout is total overkill and will result in a testing & maintenance nightmare. It’s out of scope. I suggest reading this time-tried article on preferences: http://ometer.com/preferences.html
