### ISSUE TITLE
Manage "Duplicate contacts"

### ISSUE THREAD

**Issue by MWL1701** [nextcloud/contacts#3053]
### Is your feature request related to a problem? Please describe.

It's not related to a problem of the software but a matter of to many duplicates to handle ;-)

### Describe the solution you'd like

I would like to have a function that checks for duplicate contacts by name, first name maybe telefon-number and so on and offers a choice of "deleting" the duplicate or "merge" the two duplicates to one.

### Describe alternatives you've considered

At the moment I don't have an alternative but doing it manually or use third-party-software on a complicated way ...

### Additional context

If you concider to create such a functionality I'm open for assistance, if I can

**Comment by MWL1701** [comment]
Thank you, but I don't have a "Merge Duplicates"-Button.
Where is this button or how do I activate it?

**Comment by ChristophWurst** [comment]
It's not a merged feature. This is just a proposed change.

**Comment by MWL1701** [comment]
Ah, sorry for misunderstanding.
Now I added a comment in the related topic. This might help, at least to identify the duplicates.
I think that I close this Issue because there is no such functionality at the moment and somebody tries to develop one, if I understood corectely.
