### ISSUE TITLE
Contacts UI vs Zimbra

### ISSUE THREAD

**Issue by olantrust** [nextcloud/contacts#306]
Zimbra's contacts UI (the backend also uses CardDAV) is more graceful, more informative, and more space efficient than Nexcloud Contacts. We could learn from there. And surpass!

References to specific bugs will be added (or bugs created).

See screenshots for a sample contact created in both systems.
The noticeable differences:

**Address layout:** #309  Zimbra changes layout according to Country of UI, Nextcloud doesn't
**Address layout:** #309 Nextcloud includes a clunky POBox field, Zimbra doesn't. Most Users in most countries barely use (and Users can enter POBox manually).
**Custom fields:** #303 Nextcloud does not allow their creation yet, Zimbra does. 
**Default fields:** #304
Zimbra automatically displays the commonly-used Notes, Birthday and Website fields, Nextcloud doesn't. Allowing custom layouts would massively help workflow.
**Missing fields:** #302
Zimbra includes 'Department', Nextcloud doesn't 
**Choice of display name:** Zimbra allows User to override default display name per contact, in this example, the User wants to see the contact's personal and organisation name for ease. Nextcloud doesn't permit this at all!
**Name mess:** #307 Nextcloud is a big mess once you select detailed name, and nickname. It shows them in three different places, and is unintuitive (which overrides which? the User is thinking). Zimbra displays all the name details gracefully in once place. By default it only shows First and Last and Organisation name (just like Nextcloud) but lets you add 'More', adding Prefix, Suffix, Nickname, Department, Title, Middle names etc.. But all in the same place. No confusion, and taking far less space up, and letting the User focus on the contacts other details.
**Edit and view mode:** Zimbra looks much better than Nextcloud, when a viewer is simply browsing rather than editing contacts (that's the main use of an address book after all). And it also prevents accidental changes.
**Missing headers:** #305
Unlike Zimbra, Nextcloud is missing headers for groups of fields - when looking at a contact in Nextcloud, there is nothing saying what is a phone number, email address, address etc... Yes, it can be worked out from the field entry, but that is more looking and more unnecessary work for a tired and busy User. The lack of headers also prevents easy-scanning of details and make the contact look messy.

**Comment by olantrust** [comment]
These screenshots show the massive difference in appearance and ease of usability.

![nextcloudissue-screenshot_20170827_235308](https://user-images.githubusercontent.com/627140/29755513-48dc6a88-8b91-11e7-9894-ddd24be5cf9b.png)
![nextcloudissue2-screenshot_20170827_235308](https://user-images.githubusercontent.com/627140/29755514-48dd5b1e-8b91-11e7-9718-aea9ed1b97fc.png)
![nextcloudissue3-screenshot_20170827_235308](https://user-images.githubusercontent.com/627140/29755515-48decd78-8b91-11e7-99a4-5d3d3035fe84.png)

**Comment by skjnldsv** [comment]
What is the point of this issue? If this is only to reference the others, we can close.

**Comment by jancborchardt** [comment]
Also as mentioned in another issue:
> While it is something to improve, let’s please not use Zimbra’s messy interface as any kind of benchmark. Google Contacts or Apple Contacts is way more widely used, and far better designed.
