### ISSUE TITLE
Can't import vCard v2.1 contacts

### ISSUE THREAD

**Issue by xchoice** [nextcloud/contacts#3064]
### Describe the bug

Upon importing this shows:
![image](https://user-images.githubusercontent.com/4960673/196821332-806670a9-ce68-4c57-a2fb-70e08101d0d0.png)
and then nothing else happens

### Steps to reproduce

import->from files->contacts.vcf

### Expected behavior

Import the contacts or error out with something like vCard v2.1 not supported or something?

### Actual behavior

I most definitely did not expect a blank popup <.<

### Contact version

5.0.1

### Operating system

nextcloud 25.0.0 <- docker <- alpine 3.16.2 (lxc) <- proxmox ve (linux 5.19.6)

### PHP engine version

PHP 8.1

### Web server

Nginx

### Database

PostgreSQL

**Comment by nicobo** [comment]
Yes, [the doc says](https://docs.nextcloud.com/server/latest/user_manual/en/groupware/contacts.html#importing-virtual-contacts) :
> The Contacts app only supports import of vCards version 3.0 and 4.0.

However I managed to convert a 2.1 VCF into a 3.0 one using this tool : https://github.com/jowave/vcard2to3
(almost) all my contacts were imported successfully (took 20 mn for 900 contacts).

I agree the UI is missing informations though... I've observed that you can consider the operation ended (ok or ko) if the cross appears in the top-right corner as shown on your screenshot.

**Comment by ChristophWurst** [comment]
> I agree the UI is missing informations though...

https://github.com/nextcloud/contacts/issues/2944. Should be fixed with the next releases.

**Comment by joshtrichards** [comment]
Fixed in #3038 
The 2.1 stuff is tracked elsewhere - see #492
