### ISSUE TITLE
InvalidSignatureException

### ISSUE THREAD

**Issue by laolux** [nextcloud/contacts#3065]
### Describe the bug

App integrity check fails with an invalid signature exception. Noticed after upgrading to NC 25 and checking my install. Might be related to [https://github.com/nextcloud/related_resources/issues/106](https://github.com/nextcloud/related_resources/issues/106)

### Steps to reproduce

1. run `php occ integrity:check-app contacts`

### Expected behavior

Nothing should be returned, as integrity check passes.

### Actual behavior

Integrity check fails and

      - EXCEPTION:
        - class: OC\IntegrityCheck\Exceptions\InvalidSignatureException
        - message: Signature data not found.

is returned. Also get a warning in Administration->Overview.

### Contact version

5.0.1

### Operating system

Debian

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database

PostgreSQL

### Additional info

App seems to run fine, but might secretly have been infected by malware.

**Comment by ChristophWurst** [comment]
As the output says, there is no signature data for this app.
