### ISSUE TITLE
Org Chart features not available

### ISSUE THREAD

**Issue by meichthys** [nextcloud/contacts#3066]
### Describe the bug

I've updated to NC25 and Contacts v5.0.1 but still don't see the Organizational Chart features. I've tried clearing cache, and checking for additional updates. 
![image](https://user-images.githubusercontent.com/10717998/196959703-0c530257-e6e6-4a9a-8eb1-2d80063c1943.png)
![image](https://user-images.githubusercontent.com/10717998/196959862-364756d6-04da-4b7a-a7f6-00596c61acb8.png)

### Steps to reproduce

1. Update to NC25 and Contacts v5.0.1
2. Go to Contacts
3. Try to create an organizational chart

### Expected behavior

Organizational Chart features should be available

### Actual behavior

No Organizational Chart features are available.

### Contact version

5.0.1

### Operating system

Ubuntu (Nextcloud VM)

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database

PostgreSQL

### Additional info

Apps on my instance:
```
Enabled:
  - activity: 2.17.0
  - admin_audit: 1.15.0
  - apporder: 0.15.0
  - calendar: 4.1.0-rc.1
  - circles: 25.0.0-alpha.0
  - cloud_federation_api: 1.8.0
  - comments: 1.15.0
  - contacts: 5.0.1
  - contactsinteraction: 1.6.0
  - cookbook: 0.9.15
  - dashboard: 7.5.0
  - dav: 1.24.0
  - deck: 1.8.0
  - drawio: 1.0.3
  - external: 5.0.0
  - extract: 1.3.5
  - federatedfilesharing: 1.15.0
  - files: 1.20.0
  - files_automatedtagging: 1.15.0
  - files_fulltextsearch: 24.0.1
  - files_fulltextsearch_tesseract: 24.0.0
  - files_pdfviewer: 2.6.0
  - files_retention: 1.14.0
  - files_rightclick: 1.4.0
  - files_sharing: 1.17.0
  - files_trashbin: 1.15.0
  - files_versions: 1.18.0
  - files_zip: 1.1.2
  - firstrunwizard: 2.14.0
  - forms: 3.0.0
  - fulltextsearch: 24.0.0
  - fulltextsearch_elasticsearch: 24.0.1
  - impersonate: 1.11.0
  - logreader: 2.10.0
  - lookup_server_connector: 1.13.0
  - mail: 2.1.0-rc.1
  - maps: 0.2.1
  - money: 0.7.0
  - nextcloud_announcements: 1.14.0
  - notifications: 2.13.1
  - oauth2: 1.13.0
  - occweb: 0.1.0
  - password_policy: 1.15.0
  - pdf_downloader: 1.0.6
  - photos: 1.7.1
  - privacy: 1.9.0
  - provisioning_api: 1.15.0
  - radio: 1.0.3
  - recognize: 3.1.0
  - recommendations: 1.4.0
  - related_resources: 1.0.1
  - serverinfo: 1.15.0
  - settings: 1.7.0
  - sharebymail: 1.15.0
  - socialsharing_email: 2.5.0
  - suspicious_login: 4.3.0
  - systemtags: 1.15.0
  - tasks: 0.14.5
  - text: 3.6.0
  - theming: 2.0.0
  - twofactor_backupcodes: 1.14.0
  - twofactor_totp: 7.0.0
  - updatenotification: 1.15.0
  - user_status: 1.5.0
  - viewer: 1.9.0
  - weather_status: 1.5.0
  - workflowengine: 2.7.0
Disabled:
  - bookmarks_fulltextsearch: 1.2.0
  - bruteforcesettings: 2.4.0
  - encryption: 2.13.0
  - federation: 1.13.0
  - files_antivirus: 3.3.1
  - files_external: 1.15.0
  - support: 1.6.0
  - survey_client: 1.11.0
  - user_ldap
  ```

**Comment by meichthys** [comment]
I do see this in my console when i load the contacts app, but I'm assuming that isn't the cause of the issue:
![image](https://user-images.githubusercontent.com/10717998/196960428-2ec8309a-660e-4755-9f06-1c22a6c9acf3.png)

**Comment by ChristophWurst** [comment]
assign managers to your contacts. the chart will appear.

**Comment by meichthys** [comment]
That did the trick. Thanks. 👍

**Comment by NangeGao** [comment]
> assign managers to your contacts. the chart will appear.

How to assign manager, please?

**Comment by NangeGao** [comment]
> 

I got it. I must have three or more contacts. It's so confused for me.
