### ISSUE TITLE
Minor layout issue: Submit button for "New address book" is red

### ISSUE THREAD

**Issue by nicokaiser** [nextcloud/contacts#3067]
### Steps to reproduce

1. Go to Contacts app
2. Click on Contacts settings

The "submit" button for adding address books is outlined red, which looks weird. Probably a minor CSS or state issue.

See screenshot:

![Bildschirmfoto 2022-10-20 um 19 49 05](https://user-images.githubusercontent.com/238631/197021975-576cca92-5865-4232-898b-7b6d3d4adfa4.png)

### Expected behavior

The "submit" button should not be outlined in red

### Actual behavior

The "submit" button should is outlined in red

### Server operating system

Debian 11

### Web server

Apache

### Database engine version

MariaDB

### PHP engine version

PHP 8.1

### Nextcloud version

25.0.0

### Updated from an older installed version or fresh install

Updated from 24

### Signing status

```Text
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- related_resources
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Signature data not found.

Raw output
==========
Array
(
    [related_resources] => Array
        (
            [EXCEPTION] => Array
                (
                    [class] => OC\IntegrityCheck\Exceptions\InvalidSignatureException
                    [message] => Signature data not found.
                )

        )

)
```

### Browser

Chrome

### Client operating system

macOS

**Comment by aryatalathi** [comment]
I would like to contribute here. May I work on this issue? Can you please assign me?

**Comment by ChristophWurst** [comment]
Sure sure :)

**Comment by SebastianKrupinski** [comment]
This issue is no longer applicable.
