### ISSUE TITLE
Update app screenshot to Nextcloud 25 design

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/contacts#3079]
### Is your feature request related to a problem? Please describe.

https://raw.githubusercontent.com/nextcloud/screenshots/master/apps/Contacts/contacts.png shows the old design

### Describe the solution you'd like

Update
- [x] README
- [x] info.xml (app store)

**Comment by GretaD** [comment]
@ChristophWurst info.xml doesnt have screenshots, should i add it there too?

**Comment by ChristophWurst** [comment]
https://github.com/nextcloud/contacts/blob/ef66b3bfeed5dc79ecf3b38b2ae5c2573709c159/appinfo/info.xml#L38 it link so the same image

**Comment by ChristophWurst** [comment]
https://apps.nextcloud.com/apps/contacts already had the new image
