### ISSUE TITLE
Add more information to the search results

### ISSUE THREAD

**Issue by ostasevych** [nextcloud/contacts#3080]
### Is your feature request related to a problem? Please describe.

When searching the contacts using the search button located on the Nextcloud bar a user may see only name and email with the suggestion to see details. This is not enough for normal browsing.

![image](https://user-images.githubusercontent.com/5199030/197695676-6e55d15c-d715-4344-b9ac-c536bf549893.png)

### Describe the solution you'd like

Please, add the possibility to customise the quick output results of the search for a contact by providing additional information in the search results, eg phone number(s), birthdate etc. 

### Describe alternatives you've considered

As almost all contacts have phone numbers comparing to emails I suggest at least to output phone number(s) in addition to names and emails.

### Additional context

Contacts may have several emails and phones, it is good to add the primary one and output it or output all and indicate the type of phone/email, eg home/work.

**Comment by ChristophWurst** [comment]
The *contacts menu* is a feature of https://github.com/nextcloud/server. 

https://github.com/nextcloud/server/issues?q=is%3Aissue+is%3Aopen++label%3A%22feature%3A+contacts+menu%22+ has a set of open feature requests for that feature. If yours is missing, please file a new ticket.
