### ISSUE TITLE
Layout issue: "Select type" label does not cover placeholder

### ISSUE THREAD

**Issue by nicokaiser** [nextcloud/contacts#3086]
For phone, email and address types, there are dropdowns for the type. In languages where "Select type" is longer than in english (e.g. German "Typ auswählen"), the label is too small and the rest of "Typ auswählen" is still visible:

![Bildschirm­foto 2022-11-03 um 21 05 56](https://user-images.githubusercontent.com/238631/199823997-106a580e-691f-47a1-b357-d633d23c9f37.png)

Also, the "Select type" label is being cut off when the dropdown is opened:

![Bildschirm­foto 2022-11-03 um 21 08 13](https://user-images.githubusercontent.com/238631/199824032-c1dd9c01-7dde-46ef-9a6d-e17f766efcc9.png)

Nextcloud 25.0.1

**Comment by theGitMichel** [comment]
The complete layout is somewhat broken. It looks really ugly and messy.

**Comment by ChristophWurst** [comment]
Fixed with v5.3.0
