### ISSUE TITLE
Fix address layout

### ISSUE THREAD

**Issue by olantrust** [nextcloud/contacts#309]
There are several issues caused by the current address layout:

**Currently**
1) It is US-centric and doesn't reflect the many varied address layouts globally, making it hard for most of the world to use.
2) The Post Office Box section is almost redundant in most of the world, and takes up unnecessary space.

**Solution**
A simple and graceful but powerful improvement would make the app look and work better for users around the globe: To relieve problematic issues with users having to distort address layouts, and postal printing, etc... dependant upon their country:

1) Have a back-end of address layouts stored in the code, per country (Universal Postal Union has this listed, we're happy to do the work to put them in a file and upload).
 
2) Provide an Option to set which address layout to use by default for each Administrator/User.

3) If User changes the 'Country' field in a contact's address, change the address layout for that address to the appropriate style for that country.

4) Remove Post Office Box from the standard layouts.
When adding address, allow the user to choose from 'Home', 'Work', 'Other', and 'POBox' in case they need to use that format of address.

**Comment by brianWreaves** [comment]
@olantrust Perhaps when you created this post the address format was "US-centric" but it is currently European-centric.

**Comment by skjnldsv** [comment]
@brianWreaves I forgot about this issue. Let's close this one and continue to yours since a bit more talk occurred :)
