### ISSUE TITLE
undeletable duplicates in "z-app-generated--contactsinteraction--recent"

### ISSUE THREAD

**Issue by knieskopp** [nextcloud/contacts#3095]
### Describe the bug

When sharing files with an e-mail adress, a contact is automatically created. This contact can not be modified, you can't add a name, phone number etc.. So the only option is to create a seperate contact which leaves you with lots of duplicates in your adress book.

### Steps to reproduce

1. share a folder or file via email

### Expected behavior

The automatically created contact should be editable or mergable with another contact. Also the adress book for these automatically created contacts could have a sexier name in the UI than "z-app-generated--contactsinteraction--recent".

### Actual behavior

The contact can't be deleted, edited or merged.

### Contact version

5.0.1

### Operating system

Windows

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database

MariaDB

**Comment by ChristophWurst** [comment]
Dup of https://github.com/nextcloud/contacts/issues/2187 and https://github.com/nextcloud/contacts/issues/2187#issuecomment-914258853
