### ISSUE TITLE
Prevention of fields straddling two columns

### ISSUE THREAD

**Issue by olantrust** [nextcloud/contacts#31]
It is highly undesirable for a field (such as address) to straddle two columns:
a) aesthetically unappealing and cluttered
b) visually difficult to read and assess data
Is there a fix in the works in another issue, else can this issue be resolved here?

**Comment by skjnldsv** [comment]
Two columns have been implemented long time ago after a talk about a better visual (see owncloud/contacts)

It will stay like that. Of course we can improve the look of those two columns, but we won't get back to one 😃

**Comment by olantrust** [comment]
Hi, @skjnldsv apologies if the bug lacked clarity.
Please re-open.
This bug is not about going back to one column. It is about ensuring individual fields do not cross over two columns.

**Comment by skjnldsv** [comment]
hi @olantrust !
Can you provide any screenshots?

**Comment by irgendwie** [comment]
duplicate ref. https://github.com/nextcloud/contacts/issues/56
