### ISSUE TITLE
Use Nextcloud tag system

### ISSUE THREAD

**Issue by olantrust** [nextcloud/contacts#310]
1) Rename 'groups' (categories) to 'tags'
(As groups has a specific meaning when syncing with other CardDAV systems - a Group contact is a single contact containing others)

2) Utilise the Nextcloud tag system so User benefits from using the same tags and a better (and consistent) tag ecosystem and UI can develop, and eventually the User can use the same UI for each app when searching/applying tags.

**Comment by skjnldsv** [comment]
We're a simple dav reader, we can't and won't use nc tags. We're only focusing on the carddav rfc compliance. 

For the groups/tags nomenclature, groups is far much understandable for the vast majority of our users! :)

**Comment by olantrust** [comment]
@skjnldsv Fairplay, you know better about the technical limitations, and keeping it slim.
Though Users think of their contacts app as a contacts app, that complements their workflow, they compare it with other contacts apps functionality, and are generally agnostic to the technical challenges, especially when they see other apps managing (admittedly not in the area of semantic tagging).
Indeed, on testing, most mobile device apps know treat tags and actual group contacts interchangeably.
Users are then free to use 'Groups' as tags or groups.
But that is really a hack, and it's unfortunate that we don't use the actual 'GROUP' vCard kind instead to represent groups, and 'category' to represent a tag, as intended in the specs.

**Comment by skjnldsv** [comment]
Maybe nextcloud/server#693 will earn your interest then. 
If this gets implemented, we could have the same groups for the contacts.

**Comment by jancborchardt** [comment]
»Groups« is the commonly understood and used name for, well, Groups of people. Hence we use it and will keep using that. :)

The Files app tags have little to do with that actually.
