### ISSUE TITLE
Wrong assignment of fields while syncing contacts

### ISSUE THREAD

**Issue by kangaroo72** [nextcloud/contacts#32]
Hi,

testet on several equipments, so I think the contacts app has the "bug" ...

while creating a new contact in NC 10.01 with two phone numbers (one private at home, and one at office for work), I sync them with the latest davdroid to my Android-System, both phone numbers are shown in the same category "main" ... that's not good ...

Similar problem appeared on iOs ... Known bugs there anywhere??

Regards,

kangaroo72

**Tested on "Samsung Galaxy Note 5 running 6.01", "Samsung Galaxy S7 running 6.01" and now also on "Samsung Galaxy S5 Mini running 5.1.1" - with CardDav-Clients "davdroid" (a very good premium app, but also with other CardDav Apps**

**Comment by skjnldsv** [comment]
Maybe your phone doesn't handle the contact very well. After creating the contact on your phone, try exporting it and post the result here! :)

**Comment by kangaroo72** [comment]
Well - I've tested on "Samsung Galaxy Note 5" and "Samsung Galaxy S7".  Sorry for asking but can you exactly explain what you want to have exported? I don't tried before, is it an export from android?? Thanks

**Comment by riegercloud** [comment]
I have similar issues on iOS 10.1.1 and iPhone 5S:
(1) I created a new contact in nextcloud ui

![1](https://cloud.githubusercontent.com/assets/20593693/20065687/44d8eb3c-a50f-11e6-9865-3a4926d39a86.jpg)

(2) Synced with iPhone 5s

![2](https://cloud.githubusercontent.com/assets/20593693/20065729/721a7804-a50f-11e6-9f64-a310249f6713.jpg)

The mis-spelling home,voice / work/voice appear

(3) edited the contact in iPhone: changed to Privat, Arbeit, Mobil

![3](https://cloud.githubusercontent.com/assets/20593693/20065753/8aa0d1c0-a50f-11e6-88ef-313a67ff97f0.jpg)

(4) Switched back to nextclouds ui

![4](https://cloud.githubusercontent.com/assets/20593693/20065997/64be491e-a510-11e6-8b55-3f7dde7a4213.jpg)

Home and Cell Voice will appear in nextcloud ui.

I am running nextcloud 10.0.1 stable, Contacts 1.4.0.0, nginx 1.11.5, mariaDB 10.0.27, php 7.0.12
Browser Edge and Firefox 49.0.2/50.0

Same issue?! [https://github.com/nextcloud/contacts/issues/15](url)

Looking forward to your response, many thanks in advance,
Cheers, Carsten

**Comment by kangaroo72** [comment]
Here my results ...

Nextcloud 10.01 stable / Contacts 1.4.0.0 / Tested on Apache and nginx, MySQL & MariaDB, PHP5 & 7 / Chrome / FF / Safari

1.) The Nextcloud
![contacts-bug-nextcloud](https://cloud.githubusercontent.com/assets/6906390/20338911/f6866280-abd9-11e6-843d-1c42db5ec7c1.jpg)

2.) The Smartphones
![image](https://cloud.githubusercontent.com/assets/6906390/20338981/6f66d374-abda-11e6-8b93-05b437a4a1f5.png)

Thanks,

kangaroo72

**Comment by skjnldsv** [comment]
I mean with the "export contact" function from android. you should be able to find it in the contacts settings. :)

Thank you both for giving info.

**Comment by kangaroo72** [comment]
I only can export as vcf - is that what you mean??

**Comment by kangaroo72** [comment]
This is the info of the vcf ...

> BEGIN:VCARD
VERSION:2.1
N:Duck;Donald;;;
FN:Donald Duck
TEL;PREF:0612399999999
TEL;PREF:069777777777
END:VCARD

**Comment by skjnldsv** [comment]
This was exactly what I meant! thank you :)
Yep, this definitely comes from your phone. Setting the type looks like this:

```
TEL;TYPE=HOME,VOICE:+9876543210
TEL;TYPE=HOME,VOICE:+0123456789
```

**Comment by kangaroo72** [comment]
okay - but how can we fix this - I cannot change Android-System :-P

**Comment by skjnldsv** [comment]
This is a good question :/
Could you try another contact manager from the play store?

**Comment by kangaroo72** [comment]
hmm ... davdroid is a very recommended app for android (also I paid two times for it - 'cause two devices) - and - davroid-dev's said it's not the problem of davdroid. I believe them 'cause Carsten has a similar bug ... can you recommend a tool for android which I can test?! Thanks

**Comment by kangaroo72** [comment]
but other apps don't work too ... just tested

**Comment by kangaroo72** [comment]
Well done ... I think that is it?!

https://forums.bitfire.at/topic/1206/fields-in-nextcloud-got-other-labels-in-android

cya

**Comment by skjnldsv** [comment]
Non no, davdroid is good, it doesn't change anything since it's just a transport for your vcf cards.
The main issue will be with your contact manager (so samsung on your case if I understand correctly) :)

But there seems to be an issue with what @riegercloud said. We need to fix the coma escaping.

**Comment by kangaroo72** [comment]
Well - not Samsung-specific ;-) - Just tested on an oldtimer. An Archos-Android-Tablet.
Same problem ;-)

Cheers

**Comment by kangaroo72** [comment]
Hmmm there's a new version of Contacts (1.5) but it doesn't fix this problem :-/

**Comment by riegercloud** [comment]
i updated to the current contact app (apps.nextcloud.com) v. 1.5.2 but the behaviour ist still the same:
Instead of the german words "Arbeit" or "Privat" again "Work, Voice" and "Privat, Voice are shown:

![grafik](https://cloud.githubusercontent.com/assets/20593693/20803307/ffcbe6c8-b7ee-11e6-9ea8-da7555090c96.png)

**Comment by kangaroo72** [comment]
Using this one works great now ...
This one is solved now and works [https://github.com/owncloud/contacts/issues/530](url)

**Comment by riegercloud** [comment]
hi guys, any progress?

**Comment by skjnldsv** [comment]
I will work on it very soon!

**Comment by kangaroo72** [comment]
@skjnldsv would be very nice 'cause it blocks me to update to further versions of NC. I have to use contacts-app to leave exchange-provider ;-) - Thanks.
BTW .... is there an ETA?

**Comment by skjnldsv** [comment]
@kangaroo72 since we're all working on many stuff on nextcloud, I can't really tell! :/

**Comment by kangaroo72** [comment]
Is it in 11 still possbile to use the contacts-app from the oc-repo - do you know maybe?

**Comment by skjnldsv** [comment]
Good question. I didn't tried it yet :/

**Comment by kangaroo72** [comment]
Did you change anything since the last version? If not, then yes.

**Comment by skjnldsv** [comment]
^^
Since the vcard lib update. Some people mentioned that it fixed labels for them.

Will take a look at this.

**Comment by kangaroo72** [comment]
Remember: The OC-Version works like a charm ...

**Comment by skjnldsv** [comment]
@kangaroo72 glad to hear!

**Comment by kangaroo72** [comment]
[https://github.com/owncloud/contacts/releases/tag/v1.5.1](url)
fixed it ...

**Comment by skjnldsv** [comment]
And we already downstreamed the pull requests from owncloud here. So we shouldn't have issues.

**Comment by kangaroo72** [comment]
I will install latest release now and let you know

**Comment by kangaroo72** [comment]
Okay ...
tried following with latest Nextcloud ...
Added new contact on Android with fist name, last name, home-phone, cell-phone

In german it should be Vorname, Nachname, Privat and Mobil.
So far so good, but Privat is shown as "Home" in NC Web-Interface

**Comment by skjnldsv** [comment]
Okay, I think we need to rewrite all of the definitions.
This is the list that comes from android java source:

```
TYPE_HOME			-> HOME
TYPE_MOBILE			-> CELL
TYPE_WORK			-> WORK
TYPE_FAX_WORK		-> WORK,FAX
TYPE_FAX_HOME		-> HOME,FAX
TYPE_PAGER			-> PAGER
TYPE_OTHER			-> VOICE
TYPE_CALLBACK		-> undefined
TYPE_CAR			-> CAR
TYPE_COMPANY_MAIN	-> undefined
TYPE_ISDN 			-> ISDN
TYPE_MAIN 			-> undefined
TYPE_OTHER_FAX 		-> FAX
TYPE_RADIO 			-> undefined
TYPE_TELEX 			-> TLX
TYPE_TTY_TDD 		-> undefined
TYPE_WORK_MOBILE 	-> WORK,CELL
TYPE_WORK_PAGER 	-> WORK,PAGER
TYPE_ASSISTANT 		-> undefined
TYPE_MMS 			-> MSG
```

**Comment by skjnldsv** [comment]
@riegercloud since I don't have an apple product, can you try the various options apple offers for tel types and post the corresponding values here?

**Comment by kangaroo72** [comment]
@skjnldsv 

> Okay, I think we need to rewrite all of the definitions.
This is the list that comes from android java source:

Let me know, when done - I'll try then ...

Cheers

**Comment by riegercloud** [comment]
apologize, i am currently off, so I will send all the details in the second week of 2017.
happy new year!

**Comment by skjnldsv** [comment]
@riegercloud No problem! Happy new year to you too!!

**Comment by kangaroo72** [comment]
@riegercloud I can "jump in" in this case ... best wishes 4 you ;-)
@skjnldsv I have an iOS-device too - just let me know, what you exact need.

**Comment by skjnldsv** [comment]
@kangaroo72 Happy new year to you too 😝 

Glad to hear. I want to check if android and ios devices uses the same matching string.
I don't know what dropdown options you have on ios, but if you could create a contact with every tel types and the export it as vcf, it could be great so we can see what it uses. :)

**Comment by riegercloud** [comment]
@kangaroo72 and @skjnldsv: will be back after rehab...thx, guys!

**Comment by jospoortvliet** [comment]
@riegercloud heroin or christmas cake? :godmode:

**Comment by kangaroo72** [comment]
@skjnldsv - can you explain me, what you exact need from an ios-device?

**Comment by kangaroo72** [comment]
@skjnldsv latest ios-app is still not working

**Comment by skjnldsv** [comment]
@kangaroo72 what I need is the match between phone types and what is really written on the vcard data.
Like "WORK,FAX" for Professional fax...

When you create a contact on your ios, you should have a choice between types like "home phone", "work phone"... I want you to create a contact with as many number entries that there is a choice (one for mobile, one for work, one for... etc) 
Then export it as vcf (vcard) and post it here 😃

**Comment by kangaroo72** [comment]
@all ... I've entered a lot of fields in an iOS-Contact ... but I'm not so experienced. Can someone explain me how to export a vcf in iOS??

**Comment by skjnldsv** [comment]
https://www.imobie.com/support/export-contacts-from-iphone.htm ?

**Comment by kangaroo72** [comment]
@skjnldsv Just tried "AnyTrans" ... it's a piece of crap (sorry) ... I have 1 Contact in the ipad. Fields in ipad are correct of course. Opening this contact in Anytrans the fields are all the same name ... loooool - we have to go another way ...

**Comment by kangaroo72** [comment]
Well ... scrolling down in contact and "share via mail" .... *ROFL*
You see, I'm Android-User ... ;-)).
Here's the vcf from iOS:

`BEGIN:VCARD
VERSION:3.0
PRODID:-//Apple Inc.//iPhone OS 10.1.1//EN
N:Doe;John;;;
FN: John  Doe 
ORG:Testcompany;
EMAIL;type=INTERNET;type=HOME;type=pref:jdoe@web.de
EMAIL;type=INTERNET;type=WORK:jdoework@web.de
TEL;type=HOME;type=VOICE;type=pref:06543 789876
TEL;type=WORK;type=VOICE:0511 5678321
TEL;type=CELL;type=VOICE:0176 543222776
TEL;type=HOME;type=FAX:07644 555432
item1.TEL:0172 5653367
item1.X-ABLabel:Mobil Arbeit
TEL;type=WORK;type=FAX:45666546
ADR;type=HOME;type=pref:;;Schmittstrasse 8;Köln;;55555;Deutschland
ADR;type=WORK:;;Kaiserstrasse 200;Limburg;;65432;Deutschland
item2.URL;type=pref:www.jdoe.cc
item2.X-ABLabel:_$!<HomePage>!$_
BDAY:1975-01-05
item3.X-ICQ;type=pref:ICQ 5574357
item3.X-ABLabel:ICQ
item4.IMPP;X-SERVICE-TYPE=ICQ;type=pref:aim:ICQ%205574357
item4.X-ABLabel:ICQ
item5.IMPP;X-SERVICE-TYPE=Skype:skype:j.doe.anywhere
item5.X-ABLabel:Skype
END:VCARD
`

**Comment by skjnldsv** [comment]
That is a weird card! But thanks a lot, I will work with that.

**Comment by kangaroo72** [comment]
Olá ... any update?

**Comment by kangaroo72** [comment]
There are a lot of commits meanwhile. Isn't this problem still not fixed? Is there a known ETA? If not I have to reactivate my Exchange-Account :-(

**Comment by skjnldsv** [comment]
Sorry, I havent seen your new message.
There isn't a lot of commits. This is some simple fixes.

There is not ETA since I haven't tested anything yet and can't tell if this is gonna be a big work or not.
But this is an opensource app, feel free to contribute. :)

**Comment by kangaroo72** [comment]
@skjnldsv ... Did you change something??
I just tried after a couple of days again ... (had to update NC to 11.01).
And now with 11.01 & Contacts 1.5.3 one contact synced nice.
I will look further, 'cause I have several systems to test ...
@riegercloud can U also check, pls?

**Comment by kangaroo72** [comment]
@riegercloud Update: checked also on iPad (iOS 10.2.1) - worked like a charm
Whoever fixed that - **BIG THANK YOU!!!!**
That solved one of my biggest problems

**Comment by skjnldsv** [comment]
@kangaroo72 Didn't changed a thing! ^^
Damn, I was done gathering all the data I needed to work on this pr... 

We'll wait for @riegercloud's answer.

**Comment by irgendwie** [comment]
@skjnldsv maybe because of the vcard lib update? (https://github.com/nextcloud/contacts/commit/a2f49e13a95c49541d9422392699169979b13055)

**Comment by skjnldsv** [comment]
@irgendwie maybe, but strange.

**Comment by riegercloud** [comment]
Hi guys,
it works as expected. Great job ... without any effort ;-)
From my perspective: to be closed

---
BEGIN:VCARD
VERSION:3.0
FN:Next Cloud
UID:469ec1c6-bf27-4976-a87a-5a387e998136
TEL;TYPE=HOME,VOICE:+498976760
TEL;TYPE=WORK,VOICE:+493076760
TEL;TYPE=CELL:+4915176760
EMAIL;TYPE=WORK:next@cloud.com
EMAIL;TYPE=HOME:next@cloud.de
REV:20170208T141942Z
ORG:Privacy First
TITLE:Dr. Med.
END:VCARD

Thanks to all of you!
Cheers, Carsten

**Comment by irgendwie** [comment]
@riegercloud @kangaroo72 Thanks for the feedback! Feel free to open a new issue, if you are experiencing problems again!
