### ISSUE TITLE
Set up Bountysource and use Bountysource plugin

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/contacts#322]
Since the Contacts app is basically completely community-driven, it might be cool to setup Bountysource, just like Mail and Deck do. :) Including a plugin which adds the links and amount to the issue.

@nextcloud/contacts what do you think? @ChristophWurst @juliushaertl @jospoortvliet how to set that up?

**Comment by juliushaertl** [comment]
@jancborchardt You can simply enable it for the repo in the bountysource tools section: https://www.bountysource.com/tools

**Comment by jospoortvliet** [comment]
Yeah, it has to show up there, though. I believe one had to have admin rights in github and then, after some delay, it might show up there. I just added myself and Jan, made him admin, let's see - it doesn't show up yet, and it's been 20 minutes. Sigh.

**Comment by skjnldsv** [comment]
Any news? @ChristophWurst did you get the same issue?

**Comment by jospoortvliet** [comment]
It just doesn't show in the list for me... I see 50 projects in Nextcloud and Contacts isn't in that list. Jan?

**Comment by jospoortvliet** [comment]
You GOT TO BE fSCKSS@@$&^#^$

So I reload the page one more time, just...  who knows. Suddenly: 51 projects. SEARCH: contacts - FOUND.

Install.

DONE.

**Comment by skjnldsv** [comment]
Ahahhahaha! You're awesome!! 😘

**Comment by alexanderdd** [comment]
YEEEHHHHH
