### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by gartenbauer** [nextcloud/contacts#3232]
### Describe the bug

Hi, I'm trying to import about 400 contacts into the contacts. I exported these directly from the Contacts app on the iPhone.

### Steps to reproduce

1. Export Contacts on the iPhone on in the Contacts App as ALL_CONTACTS.vcf
2. Send ALL_CONTACTS.vcf to my Windows 10 computer
3. Go to the Contacts App in Nextcloud with Microsoft Edge Version 110.0.1587.41
4. Klick on the left bottom on Contacts Settings gear
5. klick on import Contacts
6. Chose local file
7. Select the exported ALL_CONTACTS.vcf File
8. Error ocours

### Expected behavior

All contacts shoud be imported in the contacts app in nextcloud

### Actual behavior

Error ocours
![Error](https://user-images.githubusercontent.com/49751694/218303602-5347dee5-c6e8-46a3-b89f-13cabcecc5ce.png)

### Contact version

5.1.0

### Operating system

Linux 5.19.17-Unraid x86_64

### PHP engine version

PHP 8.0

### Web server

Apache (supported)

### Database

PostgreSQL

### Additional info

Set up based on [NC-AIO](https://github.com/nextcloud/all-in-one)

**Comment by gartenbauer** [comment]
So on my iPad with Microsoft Edge version 109.0.1518.80 it worked 😐

**Comment by ChristophWurst** [comment]
What browser did you use before? Safari?

**Comment by gartenbauer** [comment]
No, I have as described used Edge on my Windows workstation

**Comment by WolfgangFahl** [comment]
why is this closed? I have the same style behavior and can not debug. If basically all vcards can not be imported this looks like a systematic problem

**Comment by WolfgangFahl** [comment]
This looks like cookie problem. My assumption is that the wrong target account is used and duplicate uids are the trouble. This is why a different browswer works - it will give you access to the correct account independently.
