### ISSUE TITLE
Contacts Problem in platform_check.php

### ISSUE THREAD

**Issue by Uwe-MrT** [nextcloud/contacts#3233]
### Describe the bug

Hi, after Update of contacts today i get an error.

**Composer detected issues in your platform:
Your Composer dependencies require a PHP version ">= 8.0.0". You are running 7.4.33.**

i searched a while and find out, that is contacts platform_check.php

My default linux php is 7.4, because other webservers on my system uses php 7.4. 
But my Nextcloud (/var/www/html/nextcloud/) runs under php 8.1
This is regulatet in apache2 config

`<Directory /var/www/html/nextcloud/>

<FilesMatch \.php$>
      SetHandler "proxy:unix:/run/php/php8.1-fpm.sock|fcgi://localhost"
</FilesMatch>
`
So why i get this error ?

isnt it possible to check the php version of my nextcloud or my folder ?

I use Debian 11 + Apache2 + php8.1 + Nextcloud 25.0.3 + Contacts 5.1.0

### Expected behavior

no error should appear

### Actual behavior

recive lot of error messages 

### PHP engine version

None

### Web server

None

### Database

None

**Comment by ChristophWurst** [comment]
> ### Steps to reproduce
> 
>     1. Go to '...'
> 
>     2. Click on '....'
> 
>     3. Scroll down to '....'
> 
>     4. See error

Mind telling us how you trigger the error?

**Comment by ChristophWurst** [comment]
v5.1.0 does no longer support PHP7.4: https://github.com/nextcloud/contacts/blob/v5.1.0/appinfo/info.xml#L41

**Comment by camouflage81** [comment]
Hello all,

I think I have the same issue. 
Currently I use the php version 8.1.
The error occurs for me every 5 minutes when running the cron job.
I only noticed the issue now. 
But it must have occurred for the first time after an app update. 
After the update a few weeks ago to the Nextcloud version 25.0.3 I did not have the error yet.
Here is the log file detail:

[PHP] Fehler: Error: Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.0.0". You are running 7.4.33. at /var/www/vhosts/XXX/XXX.de/nextcloud/apps/contacts/vendor/composer/platform_check.php#24 at <<closure>>

 0. <<closure>>
    OC\Log\ErrorHandler::onError(256, "Composer detect ... .", "/var/www/vhosts ... p", 24, [["Your Composer ... ]])
 1. /var/www/vhosts/XXX/XXX.de/nextcloud/apps/contacts/vendor/composer/platform_check.php line 24
    trigger_error("Composer detect ... .", 256)
 2. /var/www/vhosts/XXX/XXX.de/nextcloud/apps/contacts/vendor/composer/autoload_real.php line 25
    require("/var/www/vhosts ... p")
 3. /var/www/vhosts/XXX/XXX.de/nextcloud/apps/contacts/vendor/autoload.php line 25
    ComposerAutoloaderInitContacts::getLoader()
 4. /var/www/vhosts/XXX/XXX.de/nextcloud/apps/contacts/composer/autoload.php line 5
    require_once("/var/www/vhosts ... p")
 5. /var/www/vhosts/XXX/XXX.de/nextcloud/lib/private/legacy/OC_App.php line 285
    require_once("/var/www/vhosts ... p")
 6. /var/www/vhosts/XXX/XXX.de/nextcloud/lib/private/AppFramework/Bootstrap/Coordinator.php line 117
    OC_App::registerAutoloading("contacts", "/var/www/vhosts ... s")
 7. /var/www/vhosts/XXX/XXX.de/nextcloud/lib/private/AppFramework/Bootstrap/Coordinator.php line 91
    OC\AppFramework\Bootstrap\Coordinator->registerApps(["files","activi ... "])
 8. /var/www/vhosts/XXX/XXX.de/nextcloud/lib/base.php line 671
    OC\AppFramework\Bootstrap\Coordinator->runInitialRegistration()
 9. /var/www/vhosts/XXX/XXX.de/nextcloud/lib/base.php line 1144
    OC::init()
10. /var/www/vhosts/XXX/XXX.de/nextcloud/cron.php line 43
    require_once("/var/www/vhosts ... p")

at 2023-02-21T08:10:02+00:00

**Comment by ChristophWurst** [comment]
Your cron job uses PHP7.4. That is the issue. Fix that and the error will disappear.

**Comment by camouflage81** [comment]
Ah Okay. Now I have understood that.
I hope that I can change this by my hoster.
Thank you very much.

**Comment by camouflage81** [comment]
Works Thanks again.

**Comment by Uwe-MrT** [comment]
In my opinion, this query is not properly programmed in platform_check.php.
1.) Even if I run the php cronjob with php8.1-fpm I get this error message.
2.) Even if Apache has the instruction to execute php requests with php8.1 in the Nextcloud folder, this error message comes up.
I can't switch my PHP to 8.1 by default because other PHP applications are still working with php7.4.
The only option for me is to edit the platform_check.php and change the value from 80000 to 70000.

**Comment by ChristophWurst** [comment]
You do realize that the platform check is there for a reason and that the app will fall apart on an incompatible runtime, do you?

If you think the platform check is wrong, please head over to https://github.com/composer/composer and report it.

**Comment by Uwe-MrT** [comment]
In some case, it is not possible to change the default PHP Version.
So maybe (i can tell more later) it helps, if the Cronjob is edited to use php8.1 insted of using php.
example:
`*/5  *  *  *  * php8.1 -f /var/www/html/nextcloud/cron.php --define apc.enable_cli=1`
