### ISSUE TITLE
The "Circles" are not deleted.

### ISSUE THREAD

**Issue by IgorD1245** [nextcloud/contacts#3234]
### Steps to reproduce

The "Circles" are not deleted. After clicking the delete button, the "Circle" disappears from the list. But after refreshing the F5 page, the circle is displayed in the list again.

### Expected behavior

Удаление "Круга"

### Actual behavior

The "Circles" are not deleted. After clicking the delete button, the "Circle" disappears from the list. But after refreshing the F5 page, the circle is displayed in the list again.

### Server operating system

ubuntu 22.04

### Web server

Apache

### Database engine version

MySQL

### PHP engine version

PHP 8.1

### Nextcloud version

25

### Updated from an older installed version or fresh install

Fresh install

**Comment by ChristophWurst** [comment]
> ### Nextcloud log
> 
> _No response_

There's probably more info there. Check for log messages written while you delete the circle.

**Comment by IgorD1245** [comment]
OCA\Circles\Tools\Exceptions\RequestNetworkException: 
/var/www/html/apps/circles/lib/Service/FederatedEventService.php - line 443:

OCA\Circles\Service\FederatedEventService->doRequest()

/var/www/html/apps/circles/lib/Service/FederatedEventService.php - line 188:

OCA\Circles\Service\FederatedEventService->initBroadcast()

/var/www/html/apps/circles/lib/Service/CircleService.php - line 264:

OCA\Circles\Service\FederatedEventService->newEvent()

/var/www/html/apps/circles/lib/Controller/LocalController.php - line 172:

OCA\Circles\Service\CircleService->destroy()

/var/www/html/lib/private/AppFramework/Http/Dispatcher.php - line 225:

OCA\Circles\Controller\LocalController->destroy()

/var/www/html/lib/private/AppFramework/Http/Dispatcher.php - line 133:

OC\AppFramework\Http\Dispatcher->executeController()

/var/www/html/lib/private/AppFramework/App.php - line 172:

OC\AppFramework\Http\Dispatcher->dispatch()

/var/www/html/lib/private/Route/Router.php - line 298:

OC\AppFramework\App::main()

/var/www/html/ocs/v1.php - line 63:

OC\Route\Router->match()

/var/www/html/ocs/v2.php - line 23:

require_once("/var/www/html/ocs/v1.php")

**Comment by ChristophWurst** [comment]
Please post the raw logs. The formatted logs miss a lot of critical information.

**Comment by IgorD1245** [comment]
[] Ошибка: OCA\Circles\Tools\Exceptions\RequestNetworkException:  at <<closure>>

0. /var/www/html/apps/circles/lib/Service/FederatedEventService.php line 443
   OCA\Circles\Service\FederatedEventService->doRequest()
1. /var/www/html/apps/circles/lib/Service/FederatedEventService.php line 188
   OCA\Circles\Service\FederatedEventService->initBroadcast()
2. /var/www/html/apps/circles/lib/Service/CircleService.php line 264
   OCA\Circles\Service\FederatedEventService->newEvent()
3. /var/www/html/apps/circles/lib/Controller/LocalController.php line 172
   OCA\Circles\Service\CircleService->destroy()
4. /var/www/html/lib/private/AppFramework/Http/Dispatcher.php line 225
   OCA\Circles\Controller\LocalController->destroy()
5. /var/www/html/lib/private/AppFramework/Http/Dispatcher.php line 133
   OC\AppFramework\Http\Dispatcher->executeController()
6. /var/www/html/lib/private/AppFramework/App.php line 172
   OC\AppFramework\Http\Dispatcher->dispatch()
7. /var/www/html/lib/private/Route/Router.php line 298
   OC\AppFramework\App::main()
8. /var/www/html/ocs/v1.php line 63
   OC\Route\Router->match()
9. /var/www/html/ocs/v2.php line 23
   require_once("/var/www/html/ocs/v1.php")

DELETE /ocs/v2.php/apps/circles/circles/H29yHU8QbKAvXgzdf1aMsxXJFsePsuL
from xxxx by divit at 2023-02-15T12:53:28+00:00

**Comment by ChristophWurst** [comment]
That is not it, unfortunately. This is still a formatted log. Not the raw log info.

**Comment by IgorD1245** [comment]
How do I get the original log information?

**Comment by ChristophWurst** [comment]
Please use https://help.nextcloud.com/ to reach out for help. I do not have the time to explain this step by step. Sorry.

**Comment by nextcloud-command** [comment]
Hi there! It looks like this issue hasn’t seen much activity for a while and might need a bit more information to move forward. If we don’t hear back soon, we may close it to keep things organized. Thanks again for your contributions – we really appreciate it!

**Comment by nextcloud-command** [comment]
Hi there! It looks like this issue hasn’t seen much activity for a while and might need a bit more information to move forward. If we don’t hear back soon, we may close it to keep things organized. Thanks again for your contributions – we really appreciate it!
