### ISSUE TITLE
Clicking on Email Id in contact opens external app instead of default mail app of nextcloud

### ISSUE THREAD

**Issue by dharmikvyas** [nextcloud/contacts#3264]
### Describe the bug

Hi,
I hope it is clear from title of this thread..
When you click on email send icon tiny one besides email id in contact display, It is sending email from external app. It tries to find out external app to send that email instead of looking for default mail app.
As we have email app that sends and receives mail from nextcloud itself than why we need to go to external app to send email??
That is why I mention this as bug.. 

### Steps to reproduce

1. Go to Contact app in nextcloud
2. Click on Contact to display detail of contact
3. Click on tiny send mail icon besides contact's email id
4. See it will look for external app of system..

### Expected behavior

It should open default mail app inside nextcloud. There is already small mail box that opens when we click on new message in mail app. It should be open here too...

### Actual behavior

it is opening external app though nextcloud has provided it's default mail app..

### PHP engine version

None

### Web server

None

### Database

None

**Comment by tcitworld** [comment]
Nextcloud provides `mailto:` links which opens the default mail app registered in your browser.

In the mail app, open the settings, then click on « Register as application for mail links » to register the Nextcloud mail app.
