### ISSUE TITLE
Testing to the max 🚀  

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/contacts#327]
Have as many tests as we can on the contacts app
Here are some examples:
 - [ ] Contact validation
 - [ ] Disabled state of template if RO ab
 - [ ] Group list order
 - [ ] Import dropdown depending  on how many ab we have
 - [ ] Copy to keyboard ab link popover
 - [ ] Importing?
 - [ ] ...
 - [ ] ...

**Comment by alexanderdd** [comment]
What is "ab"?

**Comment by irgendwie** [comment]
@alexanderdd address book
