### ISSUE TITLE
Implement read-only/view mode for contact details view

### ISSUE THREAD

**Issue by dschrempf** [nextcloud/contacts#3284]
### Is your feature request related to a problem? Please describe.

When opening the contacts on Nextcloud, I am always afraid that I add or delete characters or other things to the fields by accident.

### Describe the solution you'd like

- [x] When viewing a contact, the contact should be in "read-only" (or "viewing") mode by default.
- [x] There should be a button "Edit" to edit the contact
- [x] The "Save" button should be in the same place as the "Edit" button after toggling modes.
- [ ] View mode has quick actions and shared items.
- [x] Switch between view and edit mode should not cause jumping around of text. The text is placed such that on changing to edit mode, the position of the text itself changes as little as possible, and only a border appears around the text indicating an input field.
- [x] Switching between view and edit mode should not change the position of the Edit/save button either, esp. in mobile view.

Mockups are at https://github.com/nextcloud/contacts/issues/3305.

### Describe alternatives you've considered

_None_

### Additional context

Thanks for considering this feature request!

**Comment by ChristophWurst** [comment]
This is mentioned in https://github.com/nextcloud/contacts/issues/2699 too

**Comment by st3iny** [comment]
I added more bullet points from https://github.com/nextcloud/contacts/issues/1923#issuecomment-1506870070.

**Comment by ChristophWurst** [comment]
Let's also move and merge the todos and screenshots from https://github.com/nextcloud/contacts/issues/1923#issuecomment-1046688003 into this ticket for better clarity.

**Comment by dschrempf** [comment]
Thank you so much for your work on this!
