### ISSUE TITLE
Ready-only shared contacts shouldn't be editable

### ISSUE THREAD

**Issue by yennor** [nextcloud/contacts#329]
1. as user1 share your contacts with user2 as read only
2. user2, open your contacts, and edit some of the contacts which newly appeared

### Expected behaviour
user2 shouldn't be able to edit the contacts, if he tries an eror message should appear, but it would even be better if the fields would be somehow disabled. In general it would be good, if user2 would somehow be able to see, that those are shared contacts and not his own ones

### Actual behaviour
user2 can edit the contact, even several of them, when he clicks on previous ones he will see his changes. When he reloads the page, all the changes are gone.

**Comment by skjnldsv** [comment]
Duplicate #294
