### ISSUE TITLE
Contact image improvements

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/contacts#33]
To improve the performance of the Nextcloud contacts, we should consider about the following:

- Resize the Images when they are uploaded (for too large images)
- Provide an editor to cut and resize images (see personal-settings)

Discussed with @schiessle and @nickvergessen

**Comment by skjnldsv** [comment]
For information, the actual max size allowed is 1MB (f026e4660679799673fd42b60214f656cb812a32)

**Comment by amittel** [comment]
Just cleaned up my android contacts and transfered them to NC.
But finding a contact image (which are most of the time photos taken by my mobile) below 1MB is almost impossible.

So I'm asking if this issue is still current?

Right now I may just edit the hard-coded limit.
Would it be hard to transfer the code from personal-settings to contacts?

**Comment by nursoda** [comment]
Please also add an (editable?!) file size and/or image resolution WARNING limit.
I see two modes possible:

- bigger effort to implement but ease of use:
  pictures are resized automatically if above any warning limit
- less effort to implement but usable
  warn user to resize image(s) prior to uploading them

Interesting question is what should happen if a user saves an EXISTING contact that exceeds any limit.


BTW: in VCARD 3.0, there's also a LOGO: property which seems to be for company contacts without personal data. Would be nice to be able to use that, too, although I'm not sure which clients properly do support that.

**Comment by jancborchardt** [comment]
cc @rullzer @icewind1991 @schiessle on this.

**Comment by sunjam** [comment]
If it helps, [here is a script being used to import Google profile photos to Nextcloud Vcard.](https://github.com/IamTheFij/google-photo-to-vcard)

**Comment by skjnldsv** [comment]
Merging this into #106
