### ISSUE TITLE
In the webinterface it is impossible to distinguish different addressbooks

### ISSUE THREAD

**Issue by yennor** [nextcloud/contacts#330]
1. Add a new addressbook to your contacts, add some contacts, maybe even get a shared addressbook included from somebody else.
2. now try to find out which contact belongs to which addressbook without clicking on every single contact. Or try to see only contacts from one addressbook.
3.

### Expected behaviour
It should be possible that I can choose, "Only show me contacts from addressbook xyz"
There could be a dropdown box at the top in which one could choose what addressbook to show. There should also be the choice "all".
Also it should be possible to choose which should be the default addressbook to show first.

Otherwise there could be an other column on the left of the group column, with the addressbooks.
Or it could be included in the group column. 
At the top show the different addressbooks, then a big fat line or something, and then the groups below.

### Actual behaviour
All the contacts of all the different addressbooks are just a big mess and indistinguishable.

**Comment by skjnldsv** [comment]
Duplicate #36
