### ISSUE TITLE
Design improvements to "Add new property" 

### ISSUE THREAD

**Issue by nimishavijay** [nextcloud/contacts#3304]
### Is your feature request related to a problem? Please describe.

Improvements to the visual design of "Add new property". Current design makes it difficult to distinguish from other elements on the screen, and finding the property you need is confusing as there are so many to scroll through.

### Describe the solution you'd like

<img src="https://user-images.githubusercontent.com/52440189/231490185-3855e2db-a036-456c-a05a-3a2800ff50c8.png" width=50% height=50%>

- [x] Use a button (secondary button) instead of a multiselect
- [x] Use wording "Add more info" to keep is simple 
- [x] Clicking on the button opens an action menu where you can select the type of the property
- [x] Since the list of property types is very long, it would be a 2-level action menu
  - [x] First level contains commonly used properties like phone, email, address, birthday, website, social network and manager
  - [x] Second level contains the rest of the fields sorted in alphabetical order
    - [x] Nice to have: Phoenetic first name, phoenetic last name and nickname are combined with "Detailed name"
  - [x] All property types are shown all the time (even if it already exists) so that there is one place to go to add any property
  - [x] Use material design icons for each of the properties as we do for action menu items. The same MDI icons can also be used in the content itself on the left of the label of the property 
    - [x] Phone: [call](https://fonts.google.com/icons?selected=Material%20Icons%3Acall%3A)
    - [x] Email: [email](https://fonts.google.com/icons?selected=Material%20Icons%3Aemail%3A)
    - [x] Address: [location-on](https://fonts.google.com/icons?selected=Material%20Icons%3Alocation_on%3A)
    - [x] Birthday: [cake](https://fonts.google.com/icons?selected=Material%20Icons%3Acake%3A)
    - [x] Website: [language](https://fonts.google.com/icons?selected=Material%20Icons%3Alanguage%3A)
    - [x] Social network: [favorite](https://fonts.google.com/icons?selected=Material%20Icons%3Afavorite%3A)
    - [x] Manager: [supervisor-account](https://fonts.google.com/icons?selected=Material%20Icons%3Asupervisor_account%3A)
    - [x] Anniversary: [calendar-heart](https://pictogrammers.com/library/mdi/icon/calendar-heart/)
    - [x] Date of death: [coffin](https://pictogrammers.com/library/mdi/icon/coffin/)
    - [x] Detailed name: [badge-account-horizontal](https://fonts.google.com/icons?selected=Material%20Icons%3Abadge%3A)
    - [x] Federated cloud ID: [cloud](https://fonts.google.com/icons?selected=Material%20Icons%3Abadge%3A)
    - [x] Instant message: [message-text](https://fonts.google.com/icons?selected=Material%20Icons%3Achat%3A)
    - [x] Location: [map](https://fonts.google.com/icons?selected=Material%20Icons%3Amap%3A)
    - [x] Notes: [text](https://fonts.google.com/icons?selected=Material%20Icons%3Anotes%3A)
    - [x] Spoken languages: [translate](https://fonts.google.com/icons?selected=Material%20Icons%3Atranslate%3A)
    - [x] Related contacts: [contacts](https://fonts.google.com/icons?selected=Material%20Icons%3Acontacts%3A)
    - [x] Relationship to you: [account-switch](https://pictogrammers.com/library/mdi/icon/account-switch/)

What do you think? cc @jancborchardt for any feedback :) 

### Additional context

part of #1923

**Comment by ChristophWurst** [comment]
From https://github.com/nextcloud/contacts/issues/1923

> "Add new property" always moves around → Rename to "Add field" as a primary button in the top right, left of the 3-dot-menu

Where does the button of your mockup go? Left of the 3dot menu?

**Comment by nimishavijay** [comment]
> Where does the button of your mockup go? Left of the 3dot menu?

Opening new issue with single column layout which has screenshots about placement in a sec

**Comment by st3iny** [comment]
@JohannesGGE This ticket is done, right?

**Comment by JohannesGGE** [comment]
There is a bug related to the enhancement "Nice to have: Phoenetic first name, phoenetic last name and nickname are combined with "Detailed name"" : https://github.com/nextcloud/contacts/issues/3486

I couldn't find an acceptable way to fix that. Is it okay from designers perspective to list nickname, phoenetic first name, phoenetic last name again as seperate secondary property? (In the "Add new Property" Button as well as in the Contacts Details list)

@nimishavijay @jancborchardt

**Comment by nimishavijay** [comment]
@JohannesGGE no worries, we can list them separately 👍
