### ISSUE TITLE
In social media dropdown: "Other ... ial media" is ellipsized

### ISSUE THREAD

**Issue by GretaD** [nextcloud/contacts#3316]
### Describe the bug

In social media dropdown: "Other ... ial media" is ellipsized

### Steps to reproduce

1. add property social network
2. go to social network and change the social network 
3. look at the end of the list

### Expected behavior

Other Social media is shown correctly

### Actual behavior

is ellipsized

### PHP engine version

None

### Web server

None

### Database

None

### Additional info

![Screenshot from 2023-04-18 14-32-13](https://user-images.githubusercontent.com/12728974/232778420-5deb5275-f953-43d0-b6c5-eaeca25dac6f.png)

**Comment by GretaD** [comment]
same for
![Screenshot from 2023-04-18 17-17-48](https://user-images.githubusercontent.com/12728974/232823551-49dd4012-cde9-4471-a790-f25736b54693.png)

**Comment by ChristophWurst** [comment]
https://github.com/nextcloud/contacts/issues/3305 will help when we can give the property label more space
