### ISSUE TITLE
Frontend part: expose system address book

### ISSUE THREAD

**Issue by miaulalala** [nextcloud/contacts#3317]
### Is your feature request related to a problem? Please describe.

After https://github.com/nextcloud/server/issues/37797 is done, the system address book has to be handled in the fronted.

### Describe the solution you'd like

The system address book should be called "Accounts" and should be read only.

### Describe alternatives you've considered

N. A.

### Additional context

https://github.com/nextcloud/server/issues/19575

**Comment by ChristophWurst** [comment]
> The system address book should be called "Accounts" and should be read only.

This can be done via the displayname property in the backend, as discussed, so it also shows as *Accounts* on other connected clients.

**Comment by ChristophWurst** [comment]
Nothing to do here. The app can work with read-only address books. Closing.
