### ISSUE TITLE
Group actions: Wording of "Download" should rather be "Export"

### ISSUE THREAD

**Issue by GretaD** [nextcloud/contacts#3318]
### Describe the bug

Group actions: Wording of "Download" should rather be "Export"

### Steps to reproduce

1. Go to an already created group
2. Click on action menu

### Expected behavior

Its export and not download

### Actual behavior

the wording is download

### PHP engine version

None

### Web server

None

### Database

None

### Additional info

![Screenshot from 2023-04-18 14-44-04](https://user-images.githubusercontent.com/12728974/232781082-f92b3a80-0d73-4f67-8280-b9557e4bc989.png)

**Comment by tarunsamanta2k20** [comment]
I'd like to work on this issue

**Comment by ChristophWurst** [comment]
Go ahead :)
