### ISSUE TITLE
Change "New contact" wording to "Name"

### ISSUE THREAD

**Issue by GretaD** [nextcloud/contacts#3319]
### Describe the bug

When you click new contact, the default name for it its new contact. Should be name instead

### Steps to reproduce

Create a new contact
Look at the detailed view

### Expected behavior

The name is name and not new contact

### Actual behavior

The field is called new contact

### PHP engine version

None

### Web server

None

### Database

None

### Additional info

![Screenshot from 2023-04-18 14-48-07](https://user-images.githubusercontent.com/12728974/232782412-a29ecf3b-1ac8-4d51-bb59-a1e836b7b5f0.png)

**Comment by tarunsamanta2k20** [comment]
I'd like to work on this issue
