### ISSUE TITLE
When deleting an addressbook, no contact is selected if the group doesn't exist anymore

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/contacts#333]
We need to check if the $routeParams.gid exist in the group list.
If not, fallback to `All contacts`

**Comment by arunikayadav42** [comment]
Can I please start working on this issue :)

**Comment by jonatoni** [comment]
@arunikayadav42 feel free to start working on this issue :)

**Comment by arunikayadav42** [comment]
@jonatoni can you help me get started please, by pointing to the file that needs to be dealt with.I have already cloned the repo :)
