### ISSUE TITLE
German translation wrong, but correct on transifex

### ISSUE THREAD

**Issue by alexanderdd** [nextcloud/contacts#335]
### Steps to reproduce
1. switch language to german
2. create a contact
3. the top right buttons (arrow and trash bin) both have the tooltip "Herunterladen" which means download in German. 

### Expected behaviour
The arrow should have "Herunterladen" and the trash bin "Löschen" as a tooltip.

### Actual behaviour
the top right buttons (arrow and trash bin) both have the tooltip "Herunterladen" which means download in German.

I already checked, the translation for delete is correct.
https://www.transifex.com/nextcloud/nextcloud/translate/#de_DE/contacts/99347828

**Nextcloud version:** (see Nextcloud admin page)
12.0.2
**Contacts version:** (see Nextcloud apps page)
1.5.3

### Client configuration
**Browser:**
Firefox
**Operating system:**
Xubuntu
**CardDAV-clients:**

**Comment by skjnldsv** [comment]
It's because you're using an old version of contacts. It has been fixed in #298 already! :)

**Comment by alexanderdd** [comment]
Sorry. I searched but didnt find this dublicate.
