### ISSUE TITLE
"No contacts in here" message when you select a group 

### ISSUE THREAD

**Issue by xh3n1** [nextcloud/contacts#336]
### Steps to reproduce
1. Select a group 

### Expected behaviour
Contacts should appear.

### Actual behaviour
"No contacts in here". It works only after  reloading the page.

**Comment by xh3n1** [comment]
@skjnldsv yep, it's on the latest master.

**Comment by skjnldsv** [comment]
Can't reproduce! 😕

**Comment by xh3n1** [comment]
@MorrisJobke @nickvergessen

**Comment by skjnldsv** [comment]
@xh3n1 Could you try re clone the repo?

**Comment by MorrisJobke** [comment]
I also tried to reproduce and failed. Cloned latest master, ran `make` and then created some contacts with groups. All works fine here 😢

**Comment by skjnldsv** [comment]
@MorrisJobke do not cry when everything works! 😂
