### ISSUE TITLE
Add shared items and events for each contact

### ISSUE THREAD

**Issue by nimishavijay** [nextcloud/contacts#3364]
### Is your feature request related to a problem? Please describe.

Currently the information shown for each contact is just the info in the vCard and nothing else. Now that system users are shown in contacts with https://github.com/nextcloud/server/issues/19575 there is the possibility to show additional info for these contacts, such as files or photos shared between the person and the contact, and more.

Google Contacts also has a similar idea with the "You and Person" section

![image](https://user-images.githubusercontent.com/52440189/235978548-15c726e9-93c1-41b1-8d8f-729ece05b427.png)

### Describe the solution you'd like

For the contacts which are in the system address book, if there are some existing items shared with the person and that contact they can be displayed in view mode. For example, shared files and photos, and shared events. More possibilities are recently sent emails, Talk conversations which are common, etc.

![image](https://user-images.githubusercontent.com/52440189/235982619-8c3e0587-8507-439c-9260-6ed8b3a52685.png)

In mobile it can be shown below all the vCard info.

### Describe alternatives you've considered

n/a

### Additional context

n/a

**Comment by ChristophWurst** [comment]
We have to check which of the sections/items are technically feasible within Nextcloud

**Comment by ChristophWurst** [comment]
Related resources can also be shown like in 1:1 chats in Talk

**Comment by ChristophWurst** [comment]
I don't know how to use it but https://nextcloud-vue-components.netlify.app/#/Components/NcRelatedResourcesPanel might be a component we can use for this feature.

**Comment by GretaD** [comment]
Chris created the file and i can brainstorm it with him

**Comment by ChristophWurst** [comment]
https://github.com/nextcloud/related_resources#relatedresources

**Comment by GretaD** [comment]
We agreed with Nimisha that:

_We can think of it in stages so that you are not overwhelmed. For the first stage we can do files that have been shared by you to that user or shared by that user to you, and events between just the 2 users._

Maxence needs to do some small changes on the RelatedRrecourses app in order for this to be possible.
