### ISSUE TITLE
Add quick actions for each contact

### ISSUE THREAD

**Issue by nimishavijay** [nextcloud/contacts#3365]
### Is your feature request related to a problem? Please describe.

Currently the information shown for each contact is just the info in the vCard and nothing else. With email and phone properties, it would be nice to directly email a contact with just one click, for example. We can show some "Quick actions" for each contact depending on the information available. 

Such quick actions also seems to be the norm for other contact management apps also, eg Apple Contacts

![image](https://user-images.githubusercontent.com/52440189/235974994-f9b51c0b-643a-4d8e-a52f-bd8f9134f87f.png)

### Describe the solution you'd like

There can be some suitable actions for some fields, and if those fields are filled for a contact then the actions can be shown. For example,

Phone: Call
Email: Mail
If the contact can be linked to Talk through the system address book: Message via Talk
and more

It can be shown in the view mode for a contact, on desktop it can be on the right of the properties and on mobile it can shown below the basic info (name, role, org, photo)

![image](https://user-images.githubusercontent.com/52440189/235982127-4a38d07f-1f36-4759-bccf-70c94067ae51.png)

![image](https://user-images.githubusercontent.com/52440189/235983889-a3bcf4c3-5588-4cce-8c45-2ec2c43c459e.png)

### Describe alternatives you've considered

n/a

### Additional context

n/a

**Comment by ChristophWurst** [comment]
Dup of https://github.com/nextcloud/contacts/issues/3352. @nimishavijay @st3iny merge?

**Comment by st3iny** [comment]
> Dup of #3352. @nimishavijay @st3iny merge?

Done

**Comment by ChristophWurst** [comment]
Removed from the 27 cycle because we are past feature freeze and this hasn't made it so far

**Comment by nimishavijay** [comment]
After discussion with @jancborchardt and @szaimen some points to add here:
- remove sharing action
- in place of that, add a "View profile" button, which opens the contacts profile if it exists (so for system address book contacts)
- in place of message, show "Talk" with the Talk icon if the contact has Talk (system address book contacts)
- for the rest of the actions also, show only if the appropriate field has been filled. So don't show "Mail" if the email is missing, "Call" if the phone number is missing, etc.

What do you think? :)

**Comment by ChristophWurst** [comment]
User can have multiple email addresses and phone numbers. How do we pick the correct one or do we show all of them for the actions?

**Comment by szaimen** [comment]
> How do we pick the correct one or do we show all of them for the actions?

On my phone I usually have the option to set one of them as the default one. Maybe this could be done here as well?

**Comment by nimishavijay** [comment]
Hmm, I dunno if people would always set defaults, and in case they haven't there should still be some fallback behaviour. Especially with the system address book, there is no way to edit a contact.

I am thinking of the organisational use case, and I would say to show all the email addresses to avoid the situation where a confidential document was accidentally sent to the wrong email address. We could list the email addresses in an action menu and let the user choose which email every time. 
![image](https://github.com/nextcloud/contacts/assets/52440189/2f325302-5513-43a0-a139-c8bd3e88740a)

What do you think? @nextcloud/designers

**Comment by szaimen** [comment]
LGTM :) 👍

**Comment by ChristophWurst** [comment]
> in place of that, add a "View profile" button, which opens the contacts profile if it exists (so for system address book contacts)

The profile URL is not mapped yet. We have to make sure the URL is only written for users who have the profile enabled.

Ref https://github.com/nextcloud/server/issues/37800 for the optional mapping of the profile URL. It was not trivial to solve and thus omitted for 27.

I opened https://github.com/nextcloud/server/issues/38944, which has to be implemented before Contacts can make use of it.

For the *Talk* call we can use the URL scheme ``https://cloud.domain.tld/apps/spreed/?callUser=<uid>`` according to @jancborchardt. We only have to check if the app is enabled.
