### ISSUE TITLE
Layout of contacts

### ISSUE THREAD

**Issue by kaffeeringe** [nextcloud/contacts#3384]
### Steps to reproduce

Open a contact

### Expected behavior

I expect a fixed layout for all the fields.

### Actual behavior

Actually, when I add new fields, they are flip-flopping to where-ever there seems to be enough space for them.

This makes it harder to explain it to newbies. Can you explain, why the same fields are sometimes in an other column?

I would be good, if every field "knew" where it should appear (like in Outl**k)

### Web server

None

### Database engine version

None

### PHP engine version

None

### Updated from an older installed version or fresh install

None

**Comment by ChristophWurst** [comment]
Addressed with https://github.com/nextcloud/contacts/issues/1923

**Comment by kaffeeringe** [comment]
This one should be fixed with Hub 5. It looked way more clean in the presentation! Thank you!
