### ISSUE TITLE
Failed opening required '/var/www/nextcloud/apps/contacts/composer/../vendor/autoload.php' 

### ISSUE THREAD

**Issue by pboguslawski** [nextcloud/contacts#3398]
### Steps to reproduce

After manual installation of contacts v5.2.0 in server v25.0.6 with

```
npm ci
npm run build
```
as described on https://github.com/nextcloud/contacts#build-the-app an error is thrown on nc startup:

```
PHP Fatal error:  require_once(): Failed opening required '/var/www/nextcloud/apps/contacts/composer/../vendor/autoload.php' (include_path='/var/www/nextcloud/3rdparty/pear/archive_tar:/var/www/nextcloud/3rdparty/pear/console_getopt:/var/www/nextcloud/3rdparty/pear/pear-core-minimal/src:/var/www/nextcloud/3rdparty/pear/pear_exception:/var/www/nextcloud/apps') in /var/www/nextcloud/apps/contacts/composer/autoload.php on line 5
```
No such error if
```
composer dump-autoload
```
is executed after make commands above.

Similar problem in calendar:
https://github.com/nextcloud/calendar/issues/5247

### Expected behavior

No error thrown on nc startup after building contacts like described on https://github.com/nextcloud/contacts#build-the-app

### Actual behavior

Error is thrown.

### Web server

None

### Database engine version

None

### PHP engine version

None

### Nextcloud version

25.0.6

### Updated from an older installed version or fresh install

None

**Comment by pboguslawski** [comment]
Please see also [comments in similar calendar issue](https://github.com/nextcloud/calendar/issues/5247) and consider moving building commands (optimized for dev and production) to `Makefile`. Will simplify docs maintenance probably (only `Makefile` must be updated when building procedure changes for dev and/or production).

**Comment by ChristophWurst** [comment]
Makefiles don't work out of the box on all distros. They just increase the entry barrier for newcomers and abstract away the basic concepts engineers should be familiar with before they start working on Nextcloud.

**Comment by hamza221** [comment]
`composer install ` was added to readme long time ago , I probably forgot to link the Pr
