### ISSUE TITLE
Show single-value dropdowns as text in view mode

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/contacts#3411]
### Is your feature request related to a problem? Please describe.

Properties with none or one value are rendered as disabled dropdown in view mode

![image](https://github.com/nextcloud/contacts/assets/1374172/f722fd6d-def8-45dd-b544-aa01e5a56228)

### Describe the solution you'd like

Show those values as simple text

![image](https://github.com/nextcloud/contacts/assets/1374172/d413da9b-bb5e-48f6-b218-1831401f2ec8)

### Additional context

@jancborchardt @marcoambrosini @nimishavijay what do you think?

Ref https://github.com/nextcloud/contacts/issues/3284

**Comment by nimishavijay** [comment]
Makes sense! If the value can't be changed it makes sense to show it as text rather than a dropdown :)
