### ISSUE TITLE
Hide empty fields of structured properties (e.g. address, detailed name)

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/contacts#3412]
### Is your feature request related to a problem? Please describe.

The app renders all part of a structured property like ADR in view mode

![Bildschirmfoto vom 2023-05-26 08-51-54](https://github.com/nextcloud/contacts/assets/1374172/d61549d6-1999-4f2e-acf2-31618e913715)

![image](https://github.com/nextcloud/contacts/assets/1374172/94c47781-8aff-453c-96f9-ed3f88058980)

### Describe the solution you'd like

Hide the parts in view mode, only show in edit mode

![image](https://github.com/nextcloud/contacts/assets/1374172/ea88e7a7-e3ae-4c9c-9b1b-aa0700a26d9f)

(*Other* is the type of the address. Like *Home* vs *Work* vs *Other*. It's placement is topic of another discussion)

### Additional context

@jancborchardt @marcoambrosini @nimishavijay do or don't?

**Comment by ChristophWurst** [comment]
> @jancborchardt @marcoambrosini @nimishavijay do or don't?

I'll go ahead and assume you'll approve this

**Comment by jancborchardt** [comment]
Yeah definitely hiding looks better. Best would be to put it in a readable single line form when in view mode, so not:

> First name: Christine
> Last name: Schott

But just:

> Christine Schott

Same for address.

Or do we run into issues there because we do not know which format the names and addresses of the locale have? (And have no way to define it?)

**Comment by jancborchardt** [comment]
> Or do we run into issues there because we do not know which format the names and addresses of the locale have? (And have no way to define it?)

Is there any list of name and address formats of various locales we could use? Or we might have to just add it ourselves.
E.g. saying for Hungarian and Japanese, use Last Name First name, etc etc.
Same for address formats.

**Comment by ChristophWurst** [comment]
Let's take baby steps and hide empty parts as a start

**Comment by JohannesGGE** [comment]
Should already be done by https://github.com/nextcloud/contacts/pull/3422
