### ISSUE TITLE
Hide contact groups in read mode if there are no groups

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/contacts#3420]
### Is your feature request related to a problem? Please describe.

Showing

![image](https://github.com/nextcloud/contacts/assets/1374172/d22971f5-aff2-4da4-b906-cfbe8d7c6c91)

adds no value

### Describe the solution you'd like

Hide the prop

**Comment by martinyis** [comment]
Hey, can I work on this issue, it seems interesting to me

**Comment by ChristophWurst** [comment]
The ticket was picked earlier today and a PR can be found at https://github.com/nextcloud/contacts/pull/3423.

Maybe you find yourself another ticket at https://github.com/nextcloud/contacts/labels/good%20first%20issue?

**Comment by martinyis** [comment]
> The ticket was picked earlier today and a PR can be found at #3423.
> 
> Maybe you find yourself another ticket at [ good first issue](https://github.com/nextcloud/contacts/labels/good%20first%20issue) Good for newcomers ?

Oh, okay, you should be closing issues if its done already:)
