### ISSUE TITLE
Read-only system address book is selectable as copy target

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/contacts#3421]
### Describe the bug

The SAB is read-only (both the address book and contents) so it can't be used as target for a copy operation

### Steps to reproduce

1. Open the Contacts app
2. Open the card of your system contact
3. Open the actions menu
4. Click *Copy contact*

### Expected behavior

*Accounts* is not listed because I do not have permission to write to that address book

### Actual behavior

*Accounts* is listed and copying leads to an error

![image](https://github.com/nextcloud/contacts/assets/1374172/93e42ffe-ff2a-4fda-bf67-3aac9cfcf4de)

### Contact version

5

### PHP engine version

None

### Web server

None

### Database

None

**Comment by schmidchr** [comment]
maybe this helps to debug: 
additional _Accounts_ Addressbook appeared after update of Contacts app to 5.3.2 (Nextcloud 27.0.0)
**Expected behavior**
Accounts is not listed

**Comment by ChristophWurst** [comment]
Welcome to Nextcloud 27 https://docs.nextcloud.com/server/27/admin_manual/release_notes/upgrade_to_27.html#exposed-system-address-book

**Comment by ChristophWurst** [comment]
@hamza221 @JohannesGGE I guess this problem can also be solved with an ACL privilege check
