### ISSUE TITLE
can't share address book in Contact settings

### ISSUE THREAD

**Issue by punkyard** [nextcloud/contacts#3424]
### Describe the bug

existing shares function
impossible to make new share

### Steps to reproduce

1. Go to Contact
2. Click on Contacts settings
3. Scroll down to Adress books / Contacts <:
4. See error: no results
![Capture d’écran 2023-05-31 à 16 48 01](https://github.com/nextcloud/contacts/assets/59349105/5494addc-5a7e-40ea-993a-b1db546b3f5b)

### Expected behavior

see a list of users or results after typing users of the same user group

### Actual behavior

no results are displayed

### Contact version

5.3.0rc2

### Operating system

osx catalina AiO 5.2.2

### PHP engine version

None

### Web server

None

### Database

MariaDB

### Additional info

I have requested evolution of Contacts display
and I want to tell you how I appreciate the new display

Still requesting a list view, with selectable fields to display ^^

good work guys!

**Comment by Hainer1** [comment]
Sorry, but for me the failure is already existing.
NC26.0.2 
Contact 5.3.1

**Comment by punkyard** [comment]
> Sorry, but for me the failure is already existing.
> NC26.0.2
> Contact 5.3.1

Hi @Hainer1 - what is your message supposed to mean? I don't understand? The issue has been reported somewhere else?

**Comment by Hainer1** [comment]
> > Sorry, but for me the failure is already existing.
> > NC26.0.2
> > Contact 5.3.1
> 
> Hi @Hainer1 - what is your message supposed to mean? I don't understand? The issue has been reported somewhere else?

Hi, the error described above is still present in the current version.

**Comment by hamza221** [comment]
@ChristophWurst did a backport of the fix  #3456, You should expect the fix in the next . release
