### ISSUE TITLE
NcSelect in Addressbook share is broken

### ISSUE THREAD

**Issue by JohannesGGE** [nextcloud/contacts#3428]
### Describe the bug

Due to the change from Multiselect to NcSelect in https://github.com/nextcloud/contacts/pull/3374 the share option for addressbooks is broken.

(Maybe other NcSelects are broken as well, just tested this one)

### Steps to reproduce

1. Go to Contacts settings
2. Click on share icon next to an addressbook
3. Type a username

### Expected behavior

Matching usernames are suggested.

### Actual behavior

Nothing happens. No call to the backend.

### Contact version

main

### PHP engine version

None

### Web server

None

### Database

None

**Comment by hamza221** [comment]
Can you reproduce on latest main ?

**Comment by JohannesGGE** [comment]
Duplicate: https://github.com/nextcloud/contacts/issues/3424
