### ISSUE TITLE
Wrong sorting for cyrillic symbols

### ISSUE THREAD

**Issue by ostasevych** [nextcloud/contacts#3435]
### Describe the bug

I have found that the surnames written in Ukrainian (Cyrillic symbols) in the contact list are not sorted in the proper way. Eg, the symbols "І", "Є" come before "А". 
![image](https://github.com/nextcloud/contacts/assets/5199030/d391d94f-240f-458b-9a85-aae3834e3e37)
Please, help to fix them.

### Steps to reproduce

1. Click on Quick contacts button
3. Observe, that the names are sorted not in a proper way.

### Expected behavior

According to the Ukrainian ABC the names started from "І" and "Є" should not be at the very beginning of the list. See the ABC.
![Uploading image.png…]()

### Actual behavior

All names started from "І" come at the beginning of sorting. This is also relevant to the contacts app.

### Contact version

5.2.0

### Operating system

Windows 10.

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database

MariaDB

**Comment by ChristophWurst** [comment]
The *contacts menu* is provided by the server component. Please report this at https://github.com/nextcloud/server/issues/new/choose.
