### ISSUE TITLE
Phone field missing on many contacts

### ISSUE THREAD

**Issue by meichthys** [nextcloud/contacts#3440]
### Describe the bug

Recently I've noticed that many of the contacts (when viewed from the nextcloud web ui) are missing phone numbers. 
The numbers are however synced to my other devices via cardDav.

### Steps to reproduce

1. Go to Contacts app via web ui
2. View some contacts that you know should have phone numbers

### Expected behavior

All contacts that have phone numbers should show the phone numbers.

### Actual behavior

Some contacts that have phone numbers when synced with a carddav client do not show the phone number.

### Contact version

5.3.0-rc.3

### Operating system

Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database

PostgreSQL

### Additional info

I'm not sure if this is also happening for other fields. I've only noticed it for the phone field.

**Comment by thanoskarras** [comment]
Just installed contacts version 5.3.0 on Nextcloud 25.0.7 (opensuse leap, apache, mysql, php 8.0) and have the same problem.

**Comment by Hainer1** [comment]
Same here NC26.0.2, Contact 5.3.2, apache, mariaDB, ubuntu VM, php8.1

**Comment by blausand** [comment]
Also seeing it around the globe, folks. **This is not a small issue**. Almost killed some contacts b/c the web interface made me believe they contain no info but the name.

**Comment by cm-schl** [comment]
Could someone give some example how this looks like and what the exported .vcf of such a contact contains?

**Comment by cm-schl** [comment]
Thanks for the example!
Ok, so this seams to be connected with the usage of the custom properties like in https://github.com/nextcloud/contacts/issues/3447 - or have you the same problem if the phone number is saved with one of the typical categories like `private`, `work` etc?

**Comment by cm-schl** [comment]
Just to give some more info - I think I can't reproduce this on v.25.0.8 with Contacts v5.3.2:
![grafik](https://github.com/nextcloud/contacts/assets/63400209/eac378c2-ddd6-4df9-a157-6b1353ed07e6)

```
BEGIN:VCARD
VERSION:3.0
PRODID:-//Sabre//Sabre VObject 4.4.2//EN
UID:4a8f35b8-0106-4552-afbb-4cde0cfb6b39
FN:contact new
N:new;contact;;;
TEL;TYPE=HOME:123 456 789
REV:20230706T065252Z
END:VCARD

```

**Comment by karthikiyengar** [comment]
```
BEGIN:VCARD
VERSION:3.0
PRODID;VALUE=TEXT:-//Apple Inc.//iOS 16.6//EN
N:;Fake Name;;;
FN:Fake Name
ITEM1.TEL;TYPE=pref;VALUE=UNKNOWN:+49 1111 11111
REV;VALUE=DATE-TIME:20230817T172123Z
CATEGORIES:myContacts
UID:bc8bcbbd-6199-4344-8b99-0c89840d8170
END:VCARD
```
Can't see the field. [3p software](https://app.zdechov.net/vcard-studio) reports it correctly under label "Telephone".

**Comment by nyquist2205** [comment]
Same for me, did some experiments:

Existing old contact with "mobile" number did not show the number in NC, but in Android:

```
BEGIN:VCARD
VERSION:3.0
FN:Tobias %%REMOVED%%
N:Tobias;%%REMOVED%%;;;
ITEM1.TEL:+49 176 %%REMOVED%%
ITEM1.X-ABLABEL:Mobil
CATEGORIES:myContacts
UID:b6aa81f0-0bb8-4870-a424-327a441884ce
REV:20200210T203727Z
END:VCARD
```

Changed number to "private" on Android phone and synced to NC, now numbers shows in NC Contacts:
```
BEGIN:VCARD
VERSION:3.0
PRODID:-//Sabre//Sabre VObject 4.4.2//EN
UID:b6aa81f0-0bb8-4870-a424-327a441884ce
FN:Tobias %%REMOVED%%
N:Tobias;%%REMOVED%%;;;
CATEGORIES:myContacts
TEL;TYPE=home:+49 176 %%REMOVED%%
REV:20230822T141830Z
END:VCARD
```

Created a new contact in NC Contacts, this one also has the `TEL;TYPE=` syntax and therefore shows the number:
```
BEGIN:VCARD
VERSION:3.0
PRODID:-//Sabre//Sabre VObject 4.4.2//EN
UID:784b13cf-989d-4a65-950d-e349050f7e4b
FN:Mr Nobody
N:Nobody;Mr;;;
TEL;TYPE=cell:123456789
REV:20230822T142029Z
END:VCARD
```

I do not know where the old contact was created, but I am pretty sure it was either a Android Smartphone or NC contacts.
* Nextcloud Contacts 5.3.0
* Nextcloud 26.0.0
* PHP 8.1.11

**Comment by pov91** [comment]
I have the same problem on an instance with Nextcloud 25. It is not possible to export the contacts so that a new instance with version 27 can read it. Some error messages occur, so that the contacts are not imported. Other contacts are imported but do not indicate all fields again, which occurs primarily for telephone numbers, but also for address fields. I have the impression it occurs especially if you add many additional fields to the contact. Snchonized on the phone, everything looks normal, but so you cannot change the contacts in the cloud or export/import them. This means that the contact app is not reliable.

**Comment by LittleAlf** [comment]
Unfortunately, I have to confirm this as a **_regression in version 5.4.2 of the Contacts App_** as well:

- Nextcloud 26.0.7
- Nextcloud Contacts 5.4.2
- PHP 8.1.23

### **Any phone number with a custom label does not show up in the Contacts UI anymore!**

To verify it, I did the following:

- Added phone number with a custom label under Android 13 in the Google contacts up.
- After synching this entry with my Nextcloud server the new entries did not show up in the NC Contacts UI.
- In my Android phone I changed the custom labels of the numbers to standard labels 'Mobile'.
- After doing so, the phone numbers showed up in the NC Contacts UI.
- Now I changed back to my Android phone and changed the labels of the phone numbers back to custom labels.
- Again, these numbers does not show up in the NC Contacts UI!
- **_I can confirm, that the VCARD entry from NC contains all phone numbers including the new ones and including the correct custom labels!_**

This is now at least the second time that this is happening in the NC Contacts App!

This casts a serious doubt on the usability of this App.

**Comment by LittleAlf** [comment]
@cm-schl:

You do not see it, because you use a standard label. Try changing the label of the mentioned phone number to a custom label ('benutzerdefiniert') on your Android or iOS phone. Then you will see, that the phone number is missing in the NC Contacts UI.
