### ISSUE TITLE
ITEM1 property not displayed #1842 is back

### ISSUE THREAD

**Issue by charlescurley** [nextcloud/contacts#3457]
### Describe the bug

Fields with itemX. prefixes are not displayed properly. This looks like bug #1842 again.

I commented just now on [1842](https://github.com/nextcloud/contacts/issues/1842#issuecomment-1593365932):

It's baaack! I'm seeing this on Contacts 5.3.1, Nextcloud Hub 3 (25.0.7), both of which are up to date. Several days ago, I entered a new contact. I now cannot see several fields. Exporting the contact and examining the vcard file, I see that three of the missing fields are labeled "itemX.…"., e.g.:

```
BEGIN:VCARD
VERSION:3.0
PRODID:-//Apple Inc.//iOS 16.5//EN
N:;;;;
FN:Rocky Mountain Oncology
ORG:Rocky Mountain Oncology;
TEL;type=WORK;type=VOICE;type=pref:307-235-5433
TEL;type=WORK;type=VOICE:307-332-0324
item1.TEL:+13072334783
item2.ADR;type=WORK;type=pref:;;15 Shrine Club Road;Lander;Wyoming;82520;
item3.ADR;type=WORK:;;6501 E. 2nd Street;Casper;Wyoming;82609;
NOTE:307-332-0324 is Lander\n\nJohn Purviance\, MD\n\nKelly\, scheduler\n\nSam\, 4783
REV:2023-06-14T23:22:56Z
UID:77b3ac81-5559-477e-9624-25f9245d6c6f
X-IMAGETYPE:PHOTO
END:VCARD
```
I also use an iPhone, and may have edited the contact there. All fields show up on the iPhone.

### Steps to reproduce

Enter a contact. Edit it, possibly on an iPhone. I have no idea where the itemX prefix comes from, but that's one possibility. Anyway, get the itemX prefix in there. Fields with the itemX prefix will not be displayed.

### Expected behavior

I expect to see all fields, oddball prefix or not.

### Actual behavior

Fields with the itemX prefix are retained but not displayed.

### Contact version

Contacts 5.3.1, Nextcloud Hub 3 (25.0.7), both of which are up to date.

### Operating system

Debian Linux for both server and client.

### PHP engine version

PHP 7.4

### Web server

None

### Database

None

**Comment by ChristophWurst** [comment]
Dup of https://github.com/nextcloud/contacts/issues/3447?
