### ISSUE TITLE
Cannot share addressbooks

### ISSUE THREAD

**Issue by 42ske** [nextcloud/contacts#3458]
### Describe the bug

It is not working anymore to share an existing address book with other users, user groups or circles.

### Steps to reproduce

1. Go to /apps/contacts/ > settings
2. share-symbol right of an address book’s name
3. type an existing user name, group or circle name
4. it is always „no results“ („Keine Ergebnisse“) and the search for users/groups/circles even seams to not work at all.

### Expected behavior

The search finds users/groups/circles, you can select them and share the address book with them.

### Actual behavior

nothing happens (see „Steps to reproduce“)

### Contact version

5.3.1

### Operating system

NC 26.0.2 (same on NC 27.0.0

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database

MySQL

**Comment by ChristophWurst** [comment]
Can confirm

**Comment by ChristophWurst** [comment]
It works on the `main` branch

**Comment by ChristophWurst** [comment]
Right. Dup of https://github.com/nextcloud/contacts/issues/3424
