### ISSUE TITLE
Cannot share address book anymore : sharing drop-down list is empty

### ISSUE THREAD

**Issue by Mer0me** [nextcloud/contacts#3466]
### Describe the bug

When you try to share an address book with someone, the drop down list is empty, whatever I write on the field.

### Steps to reproduce

1. Go to contacts App
2. Click on Contacts settings button
3. Try to share an address book by clicking on the share button
4. The sharing list stays empty, whatever you type

### Expected behavior

The sharing drop down list should be populated by the users/groups of the Nextcloud instance.

### Actual behavior

No sharing is possible, the list is empty

### Contact version

5.3.0/Nextcloud 26.0.2 and 5.3.1/Nextcloud 27.0.0

### Operating system

Debian 11

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database

MariaDB

### Additional info

It works on 5.2.0/Nextcloud 25.0.5

**Comment by bbx-github** [comment]
I can confirm this:
- php8.1
- fresh nextcloud installation 27.0.0
- contacts app 5.3.1

**Comment by 42ske** [comment]
see https://github.com/nextcloud/contacts/issues/3458

**Comment by Gwyll** [comment]
Checked with PHP8.2 and Contacts 5.3.2 - no luck
