### ISSUE TITLE
Recent contacts should not appear in search results

### ISSUE THREAD

**Issue by Jerome-Herbinet** [nextcloud/contacts#3473]
### Describe the bug

If I search for a contact and it's also one of the recently used contacts, it appears twice in the results, creating confusion.

![2023-06-21_10-37](https://github.com/nextcloud/contacts/assets/33763786/d7cea919-4225-44c6-b663-7d1d112ae822)

### Steps to reproduce

1. Search for a contact which is in the recently contacted
2. See the contact which appears twice

### Expected behavior

Only the original contact should appear.

### Actual behavior

The original appears with its virtual recently contacted version.

### Contact version

5.3.2

### Operating system

Ubuntu Server

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database

MySQL

### Additional info

Nextcloud 26.0.2

**Comment by Jerome-Herbinet** [comment]
@szaimen

**Comment by szaimen** [comment]
I think there have been fixes to this with 27. did you already tried rhat version?

**Comment by Jerome-Herbinet** [comment]
> I think there have been fixes to this with 27. did you already tried rhat version?

Not yet.

**Comment by ChristophWurst** [comment]
@jancborchardt @marcoambrosini @nimishavijay for making a call on whether *Recently contacted* are to be treated special and excluded from search

**Comment by marcoambrosini** [comment]
@ChristophWurst can't we just filter the list before rendering and remove dupes?

**Comment by ChristophWurst** [comment]
Recently contacted are part of *All contacts*. It is literally all contacts of all enabled address books you see there.

The duplication is tackled in https://github.com/nextcloud/server/issues/31606.

**Comment by ChristophWurst** [comment]
Well, depends.

If the issue is that you see duplicate results because of a real contact and the recently contacted entry, yes.

If the issues is that no *Recently contacted* should ever show as search result, even if you don't have that person as real contact, then no.

**Comment by marcoambrosini** [comment]
Ok I get it now, thanks. I think it could be handy to show deduplicated recently contacted people but I would add captions elements in the returned list to clearly differentiate between your contacts and people that you've recently contacted that are not in your contacts. Just like the conversation search in talk that displays the conversation you've joined first and then the conversations that you can join, and so forth.

<img width="309" alt="Screenshot 2023-06-23 at 16 29 56" src="https://github.com/nextcloud/contacts/assets/26852655/d19b27e8-e386-422d-84e0-5e98680065e3">

Not related but we could have an "add to contacts" action on the recently contacted

**Comment by ChristophWurst** [comment]
> Not related but we could have an "add to contacts" action on the recently contacted

We have that but it's called *Clone contact*

**Comment by gibelium** [comment]
> I think there have been fixes to this with 27. did you already tried rhat version?

The issue is still persitent in NC 27.1.1 with Contacts App 5.4.2

**Comment by Jerome-Herbinet** [comment]
Still occurs in NC 28.0.6 and Contacts 5.5.3.

**Comment by jancborchardt** [comment]
The original issue you describe @Jerome-Herbinet is not so much "Recent contacts should not appear in search results" but rather "Duplicate contacts should not appear.

Since the related issue @ChristophWurst mentioned is fixed as per https://github.com/nextcloud/server/issues/31606, I would say this issue can be closed.

By design, we do want recently contacted people to show up in search.
