### ISSUE TITLE
Shortly after import of 250+ contacts, they are not shown anymore in UI, but are still in SearchContacts on top right

### ISSUE THREAD

**Issue by githubcmb** [nextcloud/contacts#3474]
### Describe the bug

my installation exists for a while. Starting point war ownCloud 8.x and now am on 25.0.7
I only installed contacts in 25.0.7, so now migration (afaik) was done. (The same tables are in earlier version for user stuff as well, I can see from old backups).
So I imported my contacts through a .vcf File (created from the iphone, as syncing the existing contacts on Iphone is not possible without extra app for this task...)
It reported 1 error. It didnt mention which one. (Someone else reported this somethere; I got nolink at hand)
It showed them all in Contacs View. So I started to correct addresses, added addresses for the first like 10 items.
Then I left the Mac and cmae back later. The Contact UI says "There are no contacts yet" now.
But they are in the tables. oc_address*, oc_cards*.
The search Button (named material-design-icon__svg) shows the contacts. Clicking on the shows "contact not found" (but I cant find any errors anywhere in log files - I log in GUI (Admin) and nextcloud.log on server.
The version when importing was 5.3.0 and now is 5.3.2 - still showing nothing.

So my questions
1. any queries to debug things? (I also have the complete mariadb log when importing.... I need to know what to look for there as the log is huge - general_log = 1)
2. If I'd like to restart from scratch, any queries or "occ" commands
3. Any hints on how a user is queried to show the contacts?
4. thanks

### Steps to reproduce

1. I guess it could be something to have to do with the 20+ upgrades done with this instance. (I have had a lot of problems with different apps as my instance has lived so long and only one problem in earlier releases (upgrades) could mess up things now.
2. But I would install NC25.0.7, add contacts (all through import .vcf )
3. Manipulate some 10 items (I mostly used the beginning with A....)
4. Wait 1 hour (now sure if I needed a relogin)
5. come back to Contacts or relogin and click on Contacts. Still there?

### Expected behavior

all imported contacts are shown when clicking on Contacts

### Actual behavior

There are no contacts yet is shown instead of the 250+ contacts

### Contact version

5.3.0

### Operating system

FreeBSD12.4

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database

MariaDB

**Comment by ChristophWurst** [comment]
Open the contacts settings bottom left. You likely have your address book(s) disabled.

**Comment by githubcmb** [comment]
Hi
thanks for your feedback, but no, see screenshots
![Bildschirmfoto_2023-06-22_10 13 44](https://github.com/nextcloud/contacts/assets/135103110/24ee1274-6601-45dc-aafa-48567ab1a792)
![Bildschirmfoto_2023-06-22_10 13 04](https://github.com/nextcloud/contacts/assets/135103110/5d0a3036-b6d2-4175-830f-44c481b6cd09)
That looks enabled to me, no? (Do you have a query for me that selects the enabled in the DB)
Cheers
Christian

**Comment by ChristophWurst** [comment]
I don't know

**Comment by githubcmb** [comment]
I have had a further look into this.
(I set up another user. This other user does not raise the following debug  error messages (seen in FFox Browser Console)

XML Parsing Error: not well-formed
Location: https://EXAMPLE.COM/nc/remote.php/dav/addressbooks/users/userxxx/contacts/
Line Number 575, Column 5: contacts:575:5
XML Parsing Error: not well-formed
Location: https://EXAMPLE.COM//nc/index.php/apps/contacts/All%20contacts/0d1acc43-407d-403a-862e-c1c8e6fecfc4~contacts
Line Number 575, Column 5:

On this line is the one "erroneous contact" it had found when importing. (see description at the beginning) I didn't think that it was actually imported. That really should be changed. On import, discard the contact that do not validate. And maybe mention the one not imported as well.

After removing the (illegal?) 4 Ascii characters #19 (dec 25) in the carddata field (in oc_cards table):
The UI now shows all the contacts.
