### ISSUE TITLE
"Recently contacted" duplicates people already existing in Contacts

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/contacts#3475]
### Describe the bug

Might be an issue in Mail instead, let me know:
When you write a mail to someone using Nextcloud Mail, they always get added to "Recently contacted", no matter if you already have a person with that email in your Contacts. This leads to duplicate contact entries.

### Steps to reproduce

1. Go to mail
2. Write a mail to someone already in your contacts
3. Go to contacts
4. See a duplicate entry

Maybe a reason is because this is not my personal address book, but the one shared by Nextcloud. Either way it creates duplicates.

### Expected behavior

Mail should check with your address books to see if a contact with that mail address already exists, and if so not create a new entry in "Recently contacted".

### Actual behavior

A new entry is created in "Recently contacted" regardless of if the contact already exists in one of your address books or not.

### Contact version

Current on cloud.nc

### PHP engine version

None

### Web server

None

### Database

None

**Comment by ChristophWurst** [comment]
Dup of https://github.com/nextcloud/server/issues/31606
