### ISSUE TITLE
Contacts Search Widget Malfunction?

### ISSUE THREAD

**Issue by jtmusselman** [nextcloud/contacts#3479]
### Describe the bug

When clicking the ui element in the navigation bar that allows you to search your contacts in a pop up it thinks for a second and then responds could not load your contacts

### Steps to reproduce

1. Go to practically any page on your nextcloud
2. Click on the contacts button beside your menu/profile picture
3. See error
![image](https://github.com/nextcloud/contacts/assets/134752354/4bf07aba-6e3a-4b6f-af4f-b34855532e50)

### Expected behavior

Shows a list of contacts, and allow you to search them

### Actual behavior

Returns error message "Could not load your contacts"

### Contact version

 5.3.2

### Operating system

Fedora 37

### PHP engine version

Other

### Web server

Apache (supported)

### Database

MySQL

### Additional info

PHP vers 8.2.7

<details>
<summary>Error In logs I believe is related</summary>
<br>
```php
[index] Error: Symfony\Component\Routing\Exception\InvalidParameterException: Parameter "guestName" for route "core.GuestAvatar.getAvatar" must match "[^/]++" ("" given) to generate a corresponding URL. at <<closure>>

 0. /var/www/html/3rdparty/symfony/routing/Generator/UrlGenerator.php line 160
    Symfony\Component\Routing\Generator\UrlGenerator->doGenerate([0,1], [["core","GuestA ... l], [], [["variable","/" ... ]], ["",64], "core.GuestAvatar.getAvatar", 1, [], [])
 1. /var/www/html/lib/private/Route/Router.php line 372
    Symfony\Component\Routing\Generator\UrlGenerator->generate("core.GuestAvatar.getAvatar", ["",64], 1)
 2. /var/www/html/lib/private/Route/CachingRouter.php line 65
    OC\Route\Router->generate("core.GuestAvatar.getAvatar", ["",64], false)
 3. /var/www/html/lib/private/URLGenerator.php line 103
    OC\Route\CachingRouter->generate("core.GuestAvatar.getAvatar", ["",64])
 4. /var/www/html/lib/private/URLGenerator.php line 115
    OC\URLGenerator->linkToRoute("core.GuestAvatar.getAvatar", ["",64])
 5. /var/www/html/lib/private/Contacts/ContactsMenu/ContactsStore.php line 293
    OC\URLGenerator->linkToRouteAbsolute("core.GuestAvatar.getAvatar", ["",64])
 6. /var/www/html/lib/private/Contacts/ContactsMenu/ContactsStore.php line 110
    OC\Contacts\ContactsMenu\ContactsStore->contactArrayToEntry("*** sensitive parameters replaced ***")
 7. <<closure>>
    OC\Contacts\ContactsMenu\ContactsStore->OC\Contacts\ContactsMenu\{closure}("*** sensitive parameters replaced ***")
 8. /var/www/html/lib/private/Contacts/ContactsMenu/ContactsStore.php line 109
    array_map(["Closure"], [["65E8257D-AC3B ... "])
 9. /var/www/html/lib/private/Contacts/ContactsMenu/Manager.php line 59
    OC\Contacts\ContactsMenu\ContactsStore->getContacts(["OC\\User\\User"], null, 25)
10. /var/www/html/core/Controller/ContactsMenuController.php line 52
    OC\Contacts\ContactsMenu\Manager->getEntries(["OC\\User\\User"], null)
11. /var/www/html/lib/private/AppFramework/Http/Dispatcher.php line 230
    OC\Core\Controller\ContactsMenuController->index(null)
12. /var/www/html/lib/private/AppFramework/Http/Dispatcher.php line 137
    OC\AppFramework\Http\Dispatcher->executeController(["OC\\Core\\Cont ... "], "index")
13. /var/www/html/lib/private/AppFramework/App.php line 183
    OC\AppFramework\Http\Dispatcher->dispatch(["OC\\Core\\Cont ... "], "index")
14. /var/www/html/lib/private/Route/Router.php line 315
    OC\AppFramework\App::main("OC\\Core\\Contr ... r", "index", ["OC\\AppFramewo ... "], ["core.contactsMenu.index"])
15. /var/www/html/lib/base.php line 1064
    OC\Route\Router->match("/contactsmenu/contacts")
16. /var/www/html/index.php line 36
    OC::handleRequest()
``` 
</details>

**Comment by Arthur-D** [comment]
I have the same issue, and I have had for a long time.

`[dav] Debug: Found 1 applicable event(s), changing user status
	GET /ocs/v2.php/apps/user_status/api/v1/user_status
	from [IP] by [USER] at 9. jan. 2024, 19:22:29
`

Full log entry, except my contacts list which is also there in its entirety:
` InvalidParameterException Parameter "guestName" for route "core.GuestAvatar.getAvatar" must match "[^/]++" ("" given) to generate a corresponding URL.

    /var/www/html/3rdparty/symfony/routing/Generator/UrlGenerator.phpline 161

    Symfony\Component\Routing\Generator\UrlGenerator->doGenerate(
      [
        0,
        1
      ],
      [
        [
          "core",
          "GuestAvatarController",
          "getAvatar"
        ],
        null
      ],
      [],
      [
        [
          "variable",
          "/",
          "[^/]++",
          "size"
        ],
        [
          "variable",
          "/",
          "[^/]++",
          "guestName"
        ],
        [
          "text",
          "/avatar/guest"
        ]
      ],
      [
        "",
        64
      ],
      "core.GuestAvatar.getAvatar",
      1,
      [],
      []
    )

    /var/www/html/lib/private/Route/Router.phpline 372

    Symfony\Component\Routing\Generator\UrlGenerator->generate(
      "core.GuestAvatar.getAvatar",
      [
        "",
        64
      ],
      1
    )

    /var/www/html/lib/private/Route/CachingRouter.phpline 65

    OC\Route\Router->generate(
      "core.GuestAvatar.getAvatar",
      [
        "",
        64
      ],
      false
    )

    /var/www/html/lib/private/URLGenerator.phpline 103

    OC\Route\CachingRouter->generate(
      "core.GuestAvatar.getAvatar",
      [
        "",
        64
      ]
    )

    /var/www/html/lib/private/URLGenerator.phpline 115

    OC\URLGenerator->linkToRoute(
      "core.GuestAvatar.getAvatar",
      [
        "",
        64
      ]
    )

    /var/www/html/lib/private/Contacts/ContactsMenu/ContactsStore.phpline 345

    OC\URLGenerator->linkToRouteAbsolute(
      "core.GuestAvatar.getAvatar",
      [
        "",
        64
      ]
    )

    /var/www/html/lib/private/Contacts/ContactsMenu/ContactsStore.phpline 162

    OC\Contacts\ContactsMenu\ContactsStore->contactArrayToEntry(
      "*** sensitive parameters replaced ***"
    )

    OC\Contacts\ContactsMenu\ContactsStore->OC\Contacts\ContactsMenu\{closure}(
      "*** sensitive parameters replaced ***"
    )

    /var/www/html/lib/private/Contacts/ContactsMenu/ContactsStore.phpline 161

    undefinedundefinedarray_map(
      [
        "Closure"
      ],

(Contacts list is here.)

/var/www/html/lib/private/Contacts/ContactsMenu/Manager.phpline 54

OC\Contacts\ContactsMenu\ContactsStore->getContacts(
  [
    "OC\\User\\User"
  ],
  null,
  25
)

/var/www/html/core/Controller/ContactsMenuController.phpline 51

OC\Contacts\ContactsMenu\Manager->getEntries(
  [
    "OC\\User\\User"
  ],
  null
)

/var/www/html/lib/private/AppFramework/Http/Dispatcher.phpline 230

OC\Core\Controller\ContactsMenuController->index(
  null
)

/var/www/html/lib/private/AppFramework/Http/Dispatcher.phpline 137

OC\AppFramework\Http\Dispatcher->executeController(
  [
    "OC\\Core\\Controller\\ContactsMenuController"
  ],
  "index"
)

/var/www/html/lib/private/AppFramework/App.phpline 184

OC\AppFramework\Http\Dispatcher->dispatch(
  [
    "OC\\Core\\Controller\\ContactsMenuController"
  ],
  "index"
)

/var/www/html/lib/private/Route/Router.phpline 315

OC\AppFramework\App::main(
  "OC\\Core\\Controller\\ContactsMenuController",
  "index",
  [
    "OC\\AppFramework\\DependencyInjection\\DIContainer"
  ],
  [
    "core.contactsMenu.index"
  ]
)

/var/www/html/lib/base.phpline 1069

OC\Route\Router->match(
  "/contactsmenu/contacts"
)

/var/www/html/index.phpline 39

OC::handleRequest()`

**Comment by ximex** [comment]
possible fix: https://github.com/nextcloud/server/pull/42860

**Comment by D3nnis3n** [comment]
> possible fix: [nextcloud/server#42860](https://github.com/nextcloud/server/pull/42860)

Is this in 28.0.2? If so, it didn't work.

**Comment by D3nnis3n** [comment]
Is this in 28.0.3? If so, it ... again didn't work:
![image](https://github.com/nextcloud/contacts/assets/25908592/7d86047a-f0aa-4e4b-b2d8-a5715ad9eaea)

**Comment by susnux** [comment]
> Is this in 28.0.3? If so, it ... again didn't work

@D3nnis3n 
Can you please show the full log entry? (click on details on the right side and copy-paste the raw log entry).

**Comment by D3nnis3n** [comment]
Sorry, that's certainly a thing I should have done earlier. Here you go:
`{"reqId":"ZeeIH8VNK1ymbZQmMOcg2gAAAAA","level":3,"time":"2024-03-05T21:01:20+00:00","remoteAddr":"2a02:810d:640:1df9:fd0f:49ca:b0b2:5dea","user":"Dennis","app":"no app in context","method":"GET","url":"/ocs/v2.php/apps/dashboard/api/v2/widget-items?widgets%5B%5D=mail","message":"Exception thrown: Symfony\\Component\\Routing\\Exception\\InvalidParameterException","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36","version":"28.0.3.2","exception":{"Exception":"Symfony\\Component\\Routing\\Exception\\InvalidParameterException","Message":"Parameter \"guestName\" for route \"core.GuestAvatar.getAvatar\" must match \"[^/]++\" (\"Kulturgespräche 2022/23\" given) to generate a corresponding URL.","Code":0,"Trace":[{"file":"/var/www/vhosts/domain.com/subdomains/cloud/3rdparty/symfony/routing/Generator/UrlGenerator.php","line":161,"function":"doGenerate","class":"Symfony\\Component\\Routing\\Generator\\UrlGenerator","type":"->"},{"file":"/var/www/vhosts/domain.com/subdomains/cloud/lib/private/Route/Router.php","line":372,"function":"generate","class":"Symfony\\Component\\Routing\\Generator\\UrlGenerator","type":"->"},{"file":"/var/www/vhosts/domain.com/subdomains/cloud/lib/private/URLGenerator.php","line":103,"function":"generate","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/vhosts/domain.com/subdomains/cloud/apps/mail/lib/Dashboard/MailWidget.php","line":161,"function":"linkToRoute","class":"OC\\URLGenerator","type":"->"},{"function":"OCA\\Mail\\Dashboard\\{closure}","class":"OCA\\Mail\\Dashboard\\MailWidget","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/vhosts/domain.com/subdomains/cloud/apps/mail/lib/Dashboard/MailWidget.php","line":152,"function":"array_map"},{"file":"/var/www/vhosts/domain.com/subdomains/cloud/apps/mail/lib/Dashboard/MailWidgetV2.php","line":43,"function":"getItems","class":"OCA\\Mail\\Dashboard\\MailWidget","type":"->"},{"file":"/var/www/vhosts/domain.com/subdomains/cloud/apps/dashboard/lib/Controller/DashboardApiController.php","line":142,"function":"getItemsV2","class":"OCA\\Mail\\Dashboard\\MailWidgetV2","type":"->"},{"file":"/var/www/vhosts/domain.com/subdomains/cloud/lib/private/AppFramework/Http/Dispatcher.php","line":230,"function":"getWidgetItemsV2","class":"OCA\\Dashboard\\Controller\\DashboardApiController","type":"->"},{"file":"/var/www/vhosts/domain.com/subdomains/cloud/lib/private/AppFramework/Http/Dispatcher.php","line":137,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/vhosts/domain.com/subdomains/cloud/lib/private/AppFramework/App.php","line":184,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/vhosts/domain.com/subdomains/cloud/lib/private/Route/Router.php","line":315,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/vhosts/domain.com/subdomains/cloud/ocs/v1.php","line":65,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/vhosts/domain.com/subdomains/cloud/ocs/v2.php","line":23,"args":["/var/www/vhosts/domain.com/subdomains/cloud/ocs/v1.php"],"function":"require_once"}],"File":"/var/www/vhosts/domain.com/subdomains/cloud/3rdparty/symfony/routing/Generator/UrlGenerator.php","Line":194,"CustomMessage":"Exception thrown: Symfony\\Component\\Routing\\Exception\\InvalidParameterException"},"id":"65e86052bf280"}`

**Comment by susnux** [comment]
From the log entry I can see this is unrelated to this issue, but caused by the mail app / the mail dashboard widget.

Please open an issue [over there](https://github.com/nextcloud/mail/issues/), you can link to the server PR so it should be quickly fixed.
ref: https://github.com/nextcloud/server/pull/43317

**Comment by D3nnis3n** [comment]
Done here: https://github.com/nextcloud/mail/issues/9456

Thanks.
