### ISSUE TITLE
Nickname not exported nor synchronized

### ISSUE THREAD

**Issue by Elgomaisa** [nextcloud/contacts#3486]
### Describe the bug

When I create a new contact using the web UI and set a nickname, that field does not get synchronized to the iPhone (iOS 16.5.1) nor to the Android hpne (DAVx5 v4.3.3-ose).

I can see the contact in both devices but that field is missing.

The form contains:
![TehTest](https://github.com/nextcloud/contacts/assets/64201891/60b55a99-47ca-4ac9-8a85-ebae2fd66daf)

If I export the contact using the download button I get the following data:
```
BEGIN:VCARD
VERSION:3.0
PRODID:-//Sabre//Sabre VObject 4.4.2//EN
UID:10005022-0e4b-4aa7-92de-562d84ae2b19
FN:Test Contact
EMAIL;TYPE=HOME:noone@nowhere.com
TEL;TYPE=HOME,VOICE:+34 123 456 789
N:Contact;Test;;;;TehTest;;
REV;VALUE=DATE-AND-OR-TIME:20230626T110436Z
END:VCARD
```
As you can see from the file, there is no NICKNAME field as described [here](https://www.rfc-editor.org/rfc/rfc6350.html#section-6.2.3).

What I find interesting is that the Nickname has been inserted in the "N:" field as it has the "`N:Contact;Test;;;;TehTest;;`" value.

My guess is that the synchronization problem is linked to the missing field in the downloaded file.

If I edit the downloaded file adding the missing field, so that it looks like this one:
```
BEGIN:VCARD
VERSION:3.0
PRODID:-//Sabre//Sabre VObject 4.4.2//EN
UID:10005022-0e4b-4aa7-92de-562d84ae2b19
FN:Test Contact
EMAIL;TYPE=HOME:noone@nowhere.com
TEL;TYPE=HOME,VOICE:+34 123 456 789
N:Contact;Test;;;;TehTest;;
NICKNAME:TehTest
REV;VALUE=DATE-AND-OR-TIME:20230626T110436Z
END:VCARD
```
Then I remove the contact using the web and import my updated file I can see the nickname in the web (because it is in the N field) and both iPhone and Android devices.

### Steps to reproduce

1. Go to 'Contacts' application
2. Click on 'New contact' to add an empty contact
3. Fill the form with some basic data.
4. Click the button to download the contact and open the file with a text editor. You'll get the file as shown in the description.
5. Force a synchronization in the iPhone to fetch the new contact. It will be downloaded but the nickname is missing.
6. Force a synchronization in DAVx5 to fetch the new contact. It will be downloaded but the nickname is missing.

### Expected behavior

Since I added a nickname to the contact, it should be present in the downloaded file as well as synchronized to the devices.

### Actual behavior

The nickname is stored in the database, as I can see it in the web but it is not present in the .vcf file nor synchronized to the devices.

### Contact version

5.3.2

### Operating system

Official Docker Image v27.0.0 (System OS is ArchLinux)

### PHP engine version

Other

### Web server

Apache (supported)

### Database

MySQL

### Additional info

- PHP version 8.2.7 as it comes installed in the Docker image.

**Comment by ChristophWurst** [comment]
Thanks for the clear report and analysis

**Comment by Elgomaisa** [comment]
Thanks a lot for correcting this one! ;)
