### ISSUE TITLE
Chinese (Taiwan) text for 'Save' in contacts is incorrect

### ISSUE THREAD

**Issue by pjrobertson** [nextcloud/contacts#3489]
### Describe the bug

Text should be '編輯‘ as opposed to ’推出‘

Incorrect text:

<img width="607" alt="Screen Region 2023-06-28 at 15 45 36" src="https://github.com/nextcloud/contacts/assets/150431/605c6ab7-fe44-426c-a594-c048c5f76596">

### Steps to reproduce

1. Change user language to 正體中文（臺灣）
2. Go to contacts and open a contact
3. Note how the text for 'Edit' is incorrectly translated as 推出
		
### Contact version

5.3.2

**Comment by ChristophWurst** [comment]
Hi!

Translations are handled on Transifex. Please fix the string at https://app.transifex.com/nextcloud if you have an account on the platform. Alternatively you could raise a topic at https://help.nextcloud.com/c/translations/23.

Cheers,

**Comment by pjrobertson** [comment]
Transifex updated, waiting for latest pull from transifex: https://app.transifex.com/nextcloud/nextcloud/translate/#zh_TW/contacts/456865841?q=text%3Aedit

**Comment by pjrobertson** [comment]
You were too quick @ChristophWurst ! I was already working on it ;-) Fixed and waiting for the latest pull :)
