### ISSUE TITLE
User profile information shown in contact list, even if profile disabled, cannot be edited

### ISSUE THREAD

**Issue by floeschie** [nextcloud/contacts#3491]
### Describe the bug

I use my Nextcloud to sync contacts between my PC and several iOS devices. I recently recognized that I have duplicate entries for myself, one created by iOS and one created by the user profile.

The contact entry created by the user profile is read only, so the information shown in the contacts app is incomplete. Furthermore, I have disabled my profile in the _Personal info_ settings, so I was assuming that no personal data will be provided anywhere, not even internal apps like Contacts.

I also cannot disable or remove the address book "accounts

### Steps to reproduce

1. Go to personal profile
2. Add an Email address (for password recovery)
3. Add your full name (e. g. "John Doe")
4. Set visibility of all personal data to "hide"
5. Disable the profile
6. Go to Contacts
7. Search for your name (e. g. "John Doe")
8. Find a read only entry for yourself

### Expected behavior

I could think of several things:

1. Do not show any disabled user profiles in Contacts
2. Let users or admins disable the "Accounts" address book in Contact's settings
3. Do not show any personal user profile data if visibility set to "Hide"
4. If all personal user profile data is set to "hide", don't show the user profile in Contacts at all
5. Let users complete their user profile information (e. g. add street, zip code, ...)
6. Don't sync user profiles via CardDAV (especially if profile is disabled)

### Actual behavior

Personal user profile data (e. g. Email) is shown in Contacts, even if the option "Enable profile" is disabled in the Personal info settings. Personal user profile data is transferred via CardDAV, even though I set the visibility to "hide" in Personal info settings.

### Contact version

5.3.2

### Operating system

Linux 5.15.0-72-generic x86_64

### PHP engine version

Other

### Web server

Nginx

### Database

MariaDB

### Additional info

PHP Version: 8.2.7

**Comment by ChristophWurst** [comment]
Dup of https://github.com/nextcloud/server/issues/38880

**Comment by floeschie** [comment]
Do I get this right:

there’s personal data transferred and shown to third party systems (via CalDAV), even though I configured it to be hidden, and you plan not to fix this? Is this Nextclouds newest data privacy policy?

**Comment by ChristophWurst** [comment]
You don't. It's a duplicate report. See the other ticket.
