### ISSUE TITLE
GUI improvement

### ISSUE THREAD

**Issue by 42ske** [nextcloud/contacts#3492]
### Is your feature request related to a problem? Please describe.

In the view mode the titles of all empty fields are shown.

### Describe the solution you'd like

I would like that empty fields are only shown in the edit mode. When you are in view mode only fields which contains infomration should be shown. So e.g. in detailed name prefix, additional name, suffix, nickname and so on should be shown if they are empty.

### Describe alternatives you've considered

—

### Additional context

It’s just about a better overview within contacts. E.g. Contacts on macOS does behave like I would prefer also for Nextclouds Contacts.

**Comment by ChristophWurst** [comment]
Dup of https://github.com/nextcloud/contacts/issues/3363

**Comment by 42ske** [comment]
sorry

**Comment by ChristophWurst** [comment]
Happens to the best. No worries.
