### ISSUE TITLE
Contacts 5.3.2 - does not work at all

### ISSUE THREAD

**Issue by bassman56** [nextcloud/contacts#3501]
### Describe the bug

The recent update to 5.3.2 has broken the Contact app: When I open the web interface Contacts:
-all contacts vanished
-there is a message "Der Import ist deaktiviert da kein Adressbuch verfügbar ist" (the import is deactivated since no address book availble"
-I cannot create a new address book "Es is ein Fehler aufgetreten, das Adressbuch konnte nicht erstellt werden" (An error happened, the address book could not be created".
- No contacts in outlook etc
I tried even on a newly created test user, the same effect.   
What Can I do? go back to an earlier version of Contacts? Something else broken?

### Steps to reproduce

1. Go to Contacts
2. see description above

### Expected behavior

normal operatopn of contacts on web interface

### Actual behavior

see above

### Contact version

5.3.2

### Operating system

debian

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database

MySQL

**Comment by ChristophWurst** [comment]
see nextcloud.log for any logged errors

**Comment by bassman56** [comment]
[nextcloud-grep-contacts.log](https://github.com/nextcloud/contacts/files/11951698/nextcloud-grep-contacts.log)
I filtered nextcloud.log for "contacts". Is this OK for you?

**Comment by bassman56** [comment]
I found the issue: after apt-get update &6 apt-get upgrade, a lot of php updates came into teh system. after this update everything is working again

**Comment by AmatorPhasma** [comment]
Yes, dosent look right.

![contacts](https://github.com/nextcloud/contacts/assets/49910825/a5badff0-8158-421a-a673-855de57b5548)

```
nextcloud:  26.0.3
contacts:    5.3.2
```

```
Browser on Windows 10:
- Google Chrome: Version 114.0.5735.199 (Offizieller Build) (64-Bit)
- Google Chrome: Version 115.0.5790.99 (Offizieller Build) (64-Bit)
- Edge: Version 114.0.1823.86 (Offizielles Build) (64-Bit)
- Firefox: 115 (64Bit)
```
