### ISSUE TITLE
'Accounts' address book is not optional

### ISSUE THREAD

**Issue by jzdm** [nextcloud/contacts#3506]
### Describe the bug

The newly introduced 'Accounts' address book can not be disabled. Every user synchronizing his address books to e.g. a mobile device gets new entries in his address book for each user account of the Nextcloud instance. This can be very irritating, especially for non-technical users.

Some Nextcloud instances have non-personal user accounts for technical reasons, which now appear in every users address book. Furthermore, different users of the instance do not have each other in the address book for good reason. With the new function, all user information is forced on all users. Especially the bad CardDAV support on iOS does not allow to locally filter out the 'Accounts' address book.

This new 'Accounts' address book should be optional. Either at user level or preferably globally for the instance.

### Steps to reproduce

1. Go to 'Contacts'
2. Click on 'Contacts settings'
3. Scroll down to list of the 'Address nooks'
4. Click three-dots-menu next to 'Accounts' address books
5. Press 'Delete'
6. Confirm with 'Yes'
7. See message 'Deletion of address book was not successful' on top right of screen.

### Expected behavior

The 'Accounts' address book gets removed for the user.

### Actual behavior

The 'Accounts' address book can not be removed for the user.

### Contact version

5.3.2

### PHP engine version

PHP 8.1

### Web server

Nginx

### Database

MySQL

**Comment by ChristophWurst** [comment]
RTD: https://docs.nextcloud.com/server/latest/admin_manual/groupware/contacts.html#privacy-and-user-property-scopes

https://github.com/nextcloud/server/issues/38880
