### ISSUE TITLE
wrong display

### ISSUE THREAD

**Issue by punkyard** [nextcloud/contacts#3523]
### Describe the bug

1 apostrophes in names are not displayed
2 address book names are not displayed completely
3 can't hide/deactivate address book

### Steps to reproduce

1. APOSTROPHE
![Capture d’écran 2023-07-17 à 00 59 57](https://github.com/nextcloud/contacts/assets/59349105/f0e0a60f-81d4-4e8a-aedc-f6b3b50024c4)

2. ADDRESS BOOK NAME TRUNCATED
![Capture d’écran 2023-07-17 à 11 49 21](https://github.com/nextcloud/contacts/assets/59349105/4427262b-b380-40fb-b6bc-cd7ec03bc3b8)

2. GROUP NAME TRUNCATED
![Capture d’écran 2023-07-17 à 12 38 48](https://github.com/nextcloud/contacts/assets/59349105/46a0126f-515e-4775-99f6-947969f9901a)

3. CAN'T DEACTIVATE ADDRESS BOOK
![Capture d’écran 2023-07-17 à 11 53 21](https://github.com/nextcloud/contacts/assets/59349105/62fe1c00-a917-4cff-820f-6a78bc9112bb)

3. NO enable OPTION FOR ADDRESS BOOK
![Capture d’écran 2023-07-17 à 11 53 37](https://github.com/nextcloud/contacts/assets/59349105/383d86d6-748a-43d6-830a-163b211e9ae5)

### Expected behavior

1. same DISPLAY in detail of a contact and in the contacts list
2. show FULL NAME of the address book
3. check box goes OFF - contacts are not shown in the contact list

### Actual behavior

1 apostrophes in contact details are not displayed correctly
2 address book names are truncated after selection in the drop down menu
3 can't uncheck the 'enable' box

### Contact version

5.3.2

### Operating system

debian 11 / AiO 6.2.1 / NC 26.0.3

### PHP engine version

PHP 7.4

### Web server

Apache (supported)

### Database

MariaDB

### Additional info

web browser on mac OS 10.15.7
BRAVE and SAFARI

**Comment by MicKress** [comment]
Hi, this could be a topic of nextcloud server 26.03? On my instances with NC 25.05 and NC 27 the adressbook names and contact group names are not truncated ... On all these instances contacts app 5.32 is running.

**Comment by punkyard** [comment]
hi, thanks for your reply.
you mean that none of these 3 points are an issue in 5.32? 
🤔 could there be a problem with our instance then ..?

**Comment by MicKress** [comment]
Hi, I have the same problem with the names of address books and contact groups, but only in Nextcloud 26.03. My other instance (NC 25.05 Enterprise) shows the complete names. Both contacts apps are 5.32.

**Comment by punkyard** [comment]
what do you suggest me to do @MicKress ?

**Comment by MicKress** [comment]
@punkyard I don't know, I think it's a bug. Some other fields like gender show the same behaviour. My opinion: that depends on the type of the field. 

<img width="666" alt="Bildschirmfoto 2023-07-19 um 11 48 12" src="https://github.com/nextcloud/contacts/assets/47255870/e7cd2981-2122-4e2b-b36b-c846555e8159">

**Comment by ChristophWurst** [comment]
@GretaD could you look into this?

**Comment by GretaD** [comment]
i cannot reproduce it. on 5.3.2 for me it is shown like this:
![Screenshot from 2023-07-24 16-08-55](https://github.com/nextcloud/contacts/assets/12728974/4366d506-be1c-463d-ab9a-c3e1fe204e12)

**Comment by GretaD** [comment]
editing state
![Screenshot from 2023-07-24 16-12-04](https://github.com/nextcloud/contacts/assets/12728974/268e7c53-ce68-43bb-baeb-56eba0b22369)

**Comment by AmatorPhasma** [comment]
It is "Custom menu 3.10.2" causing this issue.

**Comment by punkyard** [comment]
thanks @AmatorPhasma 
i tried disabling Unrounded corners, but I didn't think of Custom menu
I'd like to keep it enabled .. 
what is the next step to report this?
![Capture d’écran 2023-07-24 à 21 19 04](https://github.com/nextcloud/contacts/assets/59349105/4c26c1d1-6c3f-47f9-9dbe-5e90c495eb13)
 Do you know?

**Comment by AmatorPhasma** [comment]
@ChristophWurst @GretaD I think this issue could be closed.

@punkyard The dev already has a pull request to fix this: 
https://gitnet.fr/deblan/side_menu/pulls/275

> i tried disabling Unrounded corners, but I didn't think of Custom menu
I also forgot to disable it in the first place, normally the first thing I do is disable all non-standard apps.

> what is the next step to fix this?
I would say, wait for an updated version of "custom menu" :)

**Comment by punkyard** [comment]
thanks for your help, I'm going to close this thread then
(some people use round corners?? ^^)

**Comment by punkyard** [comment]
hi - update
custom menu and unround corners are disabled
but the name display is wrong in Safari, Brave, Waterfox
The addressbook is displayed properly in Brave private mode and Water fox

<img width="568" alt="Capture d’écran 2023-10-09 à 09 24 25" src="https://github.com/nextcloud/contacts/assets/59349105/96ab68ce-3f39-4c14-bf19-a9f477ed7733">

<img width="637" alt="Capture d’écran 2023-10-09 à 09 24 31" src="https://github.com/nextcloud/contacts/assets/59349105/1a914192-22bb-4262-bf56-49ef3af7087e">

<img width="506" alt="Capture d’écran 2023-10-09 à 09 24 39" src="https://github.com/nextcloud/contacts/assets/59349105/01f58f8e-120f-46c7-a480-8a8aef911508">

**Comment by joshtrichards** [comment]
> but the name display is wrong in Safari, Brave, Waterfox
> The addressbook is displayed properly in Brave private mode and Water fox

If it works in Private Mode but not outside of it, perhaps it's a browser extension?

**Comment by punkyard** [comment]
> If it works in Private Mode but not outside of it, perhaps it's a browser extension?
there is no extension in my Waterfox (browser for test)

wrong display for apostrophes and address book name are fixed since a recent update
show/hide addressbook option appears for each address book
thanks to the team who fixed that 👏
