### ISSUE TITLE
Loading icon positioned too high when changing contacts

### ISSUE THREAD

**Issue by irgendwie** [nextcloud/contacts#353]
![untitled](https://user-images.githubusercontent.com/8360698/30699410-f42260b2-9ee4-11e7-97ec-380bc604597f.png)

**Comment by skjnldsv** [comment]
Did I forgot to add the css in my pr? 🙈

**Comment by skjnldsv** [comment]
Hum, yes I did: https://github.com/nextcloud/contacts/pull/349/files#diff-0e65f3f3b823d0d3772b8ff75cfb0041

**Comment by skjnldsv** [comment]
@nextcloud/contacts can you reproduce? :)

**Comment by xh3n1** [comment]
@skjnldsv  can't reproduce  👍

**Comment by irgendwie** [comment]
Can't reproduce anymore, seems like it was a caching issue
