### ISSUE TITLE
Improve the quick actions design

### ISSUE THREAD

**Issue by GretaD** [nextcloud/contacts#3531]
### Is your feature request related to a problem? Please describe.

Quick actions are implemented here: https://github.com/nextcloud/contacts/pull/3401. Some design improvement are needed.

- [ ] Improve the horizontal space that the actions take, they should wrap
- [ ] The contact has empty email address fields. This is not common in practice, but still looks weird.
- [ ] Add label for the buttons (its not easy to style it, so need to check with design team for options)
- [ ] Probably some improvement with different screen sizes

### Additional context

ref: https://github.com/nextcloud/contacts/issues/3365

**Comment by nimishavijay** [comment]
From the design review call on 01.08.2023:

**Overall**
* [ ] Placement: Until the shared items is implemented, show the actions in the same column as properties
  - [ ] left aligned with the "Phone", "Email", etc
* [ ] Visible labels not needed for actions, make sure that accessible labels are there, wording can look like:
  - [ ] Email test.test@example.com
  - [ ] Call +4910010010010
  - [ ] View profile

**Mobile**
* [ ] Center the actions in mobile, use flex layout with `justify-items: center;`
* [ ] Use more whitespace below actions 
* [ ] Other small issues in alignment:
  - [ ] Too much space between edit button and 3 dot menu 
  - [ ] Property values are getting ellipsized too fast in view mode, it can be show fully if there is space
  - [ ] Property type has too much space to the right  

**Bugs**
* [ ] If there is an empty email field saved, it should not show in the action menu when clicking on the email button

**Comment by GretaD** [comment]
> [ ] Other small issues in alignment:
> * [ ]  Too much space between edit button and 3 dot menu
> * [ ]  Property values are getting ellipsized too fast in view mode, it can be show fully if there is space
> * [ ]  Property type has too much space to the right

this is not related to this pr. Will open a different issue for those
