### ISSUE TITLE
The circle description field caption moves with scrolling

### ISSUE THREAD

**Issue by maximelehericy** [nextcloud/contacts#3542]
![image](https://github.com/nextcloud/circles/assets/87175513/bce26d8b-4d50-4ad4-82de-e991eb1f5006)

![image](https://github.com/nextcloud/circles/assets/87175513/9269eba0-1d64-4d83-88c9-087c7adc57c2)

![image](https://github.com/nextcloud/circles/assets/87175513/89cb011d-bafb-4185-aa1d-d3e9d4026d18)

@ArtificialOwl

**Comment by mejo-** [comment]
@maximelehericy I transfered the issue to the contacts app because that's where the user-facing circles frontend lives. The circles app itself is just the backend.

**Comment by mejo-** [comment]
This is fixed in Nextcloud 29 and higher.
