### ISSUE TITLE
Not obvious what Circles are if emptycontent message is not shown

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/contacts#3543]
If you do not have Circles yet, there is a nice emptycontent message. But it does not show anymore if some Circles already exist – which likely is the case if you are in a company.

Could we keep showing the message even if Circles are already in the list? And a slight wording enhancement from "users" to "people":
![image](https://github.com/nextcloud/circles/assets/925062/82c94c01-2794-4223-b70a-60039c79039e)

**Comment by skjnldsv** [comment]
@jancborchardt the message is huge and takes a lot of space. I think this creates more of a regression than a positive outcome:)

**Comment by jancborchardt** [comment]
@skjnldsv how about moving the message below the list of Circles? Then it is still visible but not more importantly than the list itself.

Also maybe we can shorten the message? @nimishavijay in case you have an idea (also cc @Jerome-Herbinet since you originally lengthened it, but that was before we directly displayed it):

> Circles are groups of people that you can create yourself and with whom you can share data. They can be made up of other accounts or groups of accounts of the Nextcloud instance, but also of contacts from your address book or even external people by simply entering their e-mail addresses.

**Comment by skjnldsv** [comment]
![image](https://github.com/nextcloud/contacts/assets/14975046/6938b2d0-7a14-4fe3-b52a-6436564e6235)
