### ISSUE TITLE
Typo in Polish - Circles options

### ISSUE THREAD

**Issue by elephantastyczny** [nextcloud/contacts#3544]
![image](https://user-images.githubusercontent.com/120596179/226878493-9080f3a2-be68-4ee0-a24d-78efd0dd6fe0.png)

It is:
Show conspect -> Pokaż konspekt
Show in files -> **Pokarz** w plikach

It should be 

Show conspect -> Pokaż konspekt
Show in files -> **Pokaż** w plikach

**Comment by ChristophWurst** [comment]
Translations are handled via Transifex. Please submit the issue at https://www.transifex.com/nextcloud or https://help.nextcloud.com/c/translations/23. Thanks :+1:
