### ISSUE TITLE
All quick actions should be secondary buttons

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/contacts#3564]
### Describe the bug

The mockup of https://github.com/nextcloud/contacts/issues/3365 says that all action icons should have the light blue outline. Only Talk has it:

![Bildschirmfoto vom 2023-08-14 15-27-01](https://github.com/nextcloud/contacts/assets/1374172/d51954c4-cdc5-4679-aca0-9d446bae0cc0)

### Steps to reproduce

1. Create another user
2. Open that user's system address book contact

### Expected behavior

Icons with outlines

### Actual behavior

Some icons with outlines, some without

### Contact version

5.4

### PHP engine version

None

### Web server

None

### Database

None

**Comment by GretaD** [comment]
thats weird, it shows correctly on my local env but on our cloud, it doesnt. It must be something with the actionbutton.

**Comment by ChristophWurst** [comment]
it could come from https://github.com/nextcloud/mail/issues/8735#issuecomment-1677204079

**Comment by ChristophWurst** [comment]
This change has impact on screenshots. Let's get it in for beta2 (https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule).
