### ISSUE TITLE
Possibility to filter by account

### ISSUE THREAD

**Issue by mduller** [nextcloud/contacts#36]
It would be very useful to be able to only display contacts from a certain address book in Nextcloud's UI.

In our setup, each user has his own address book plus access to a organization-wide address book (shared from a user created just for sharing organization-wide filed, appointments, contacts, etc.).
One of the use cases is to review contacts from the personal address book and move them to the company-wide because mobile devices that cannot distinguish between the two address books will just put contacts created on the device into the personal address book.

Currently we do this work using Thunderbird's address book with the SoGo connector. Both personal and org-wide address books are set up and they can be accessed independently and contacts moved around.

**Comment by irgendwie** [comment]
You can already change where contacts are stored (if more than 1 addressbook is available), when selecting the contact and looking for a field, similar to this (we already have an open pr https://github.com/nextcloud/contacts/pull/23 for the usability of the fields in the contact details):

![2016-11-29-155301_375x131](https://cloud.githubusercontent.com/assets/8360698/20714349/079ffe24-b64c-11e6-96c2-4d25ce175bf0.png)

To only display certain addressbooks, there was an open pr in [owncloud/contacts #409](https://github.com/owncloud/contacts/pull/409) - @skjnldsv are you still digging into this? :blush:

**Comment by skjnldsv** [comment]
@irgendwie not anymore. I was in need for the new dav backend. Iirc you were the one assigned to do it?
We couldn't disable/enable addressbooks since the function didn't exist in the backend we used. 
Calendar had made the switch iirc, contacts was the last app that required such a change.

**Comment by skjnldsv** [comment]
https://github.com/owncloud/contacts/pull/216

**Comment by avanc** [comment]
I'm waiting for the same feature. I have several address books and now have to review the content of one of these. However, without hiding other address books, I have to open all of my contacts and see, if the contact is in the desired address book.

**Comment by irgendwie** [comment]
@skjnldsv Thought again a bit about the disable/enable address books feature - In my opinion it would make sense to store the state in the local storage. I use the contacts app on different machines and need different address books on different machines. Saving it in Nextcloud and syncing it would lead to me (and other people) again and again clicking the disable/enable address book buttons. :thinking:

**Comment by sellth** [comment]
I agree. There is no need to sync an enabled/disabled state because many clients already have such local filtering options available (Thunderbird's Cardbook, Android's contacts app/Davdroid). A simple button in the Nextcloud UI that does the same just for the web view would be sufficient.

**Comment by skjnldsv** [comment]
@sellth there was an option which disabled the addressbook directly ON the server side.
We could also add an option to disable it on the browser side indeed though.

**Comment by nursoda** [comment]
I'd also like to have such a feature. It's handy if you manage multiple address books of different sources.

**Comment by iknietjij** [comment]
I'd like this one too. I'm using one address book on one phone, and second on another. Would like to be able to see which contacts are where easily.

**Comment by skjnldsv** [comment]
I agree with you two!

**Comment by conspacer** [comment]
+1 for this. Editing multiple addressbooks from different sources is a bit of a PITA at present. I like the (previous) checkbox feature and am willing to help beta test new ideas.

**Comment by timreeves** [comment]
+1 for this from me too! Especially when the address books involved are large, deselecting one(s) you do not usually or currently need would help to make the GUI less sluggish.

**Comment by FBachofner** [comment]
Fairly new NextCloud user here.  +1 for this improvement request.

From my vantage, "Groups" should be secondary in UI importance to "address books" -- in the left pane, somewhere.

Happy to test (and report on) this when a beta is available!

Thanks for your continued efforts.

**Comment by toxiclung** [comment]
+1

i need to open only specific address book without going to setting and enable/disabling each one

**Comment by nursoda** [comment]
Since this bug was closed LONG ago, you may want to open (a) new (and specific) feature request "bug"(s).
