### ISSUE TITLE
Incorrect phone number labels

### ISSUE THREAD

**Issue by crick-ru** [nextcloud/contacts#360]
### Steps to reproduce
1. Set up sync with Android address book
2. Create a new contact in the Android address book
3. Synchronize

### Actual behaviour
In the Android address book, the contact's phone number labels is displayed normally. For example, "mobile". But in the Nextcloud address book, the phone number labels of all contacts are displayed as "voice".

### Server configuration

**Operating system**:
Linux

**Web server:**
Apache2 v2.4.26

**Database:**
SQlite3 v3.19.3

**PHP version:**
php7 v7.1.9

**Nextcloud version:** (see Nextcloud admin page)
12.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh install

**Where did you install Nextcloud from:**
OpenSUSE repository

**Contacts app version**
v1.5.3

**Android version**
7.1.1 (clean Android on Nokia 5 phone)

**Contacts app on Android**
Google contacts v1.6.20

**Sync app on Android**
CardDAV-Sync by dmfs GmbH v0.4.23
https://play.google.com/store/apps/details?id=org.dmfs.carddav.Sync

VCARD in database:
`BEGIN:VCARD VERSION:3.0 FN:Test N:;Test;;; TEL;TYPE=VOICE;TYPE=CELL:+71111111111 PRODID:-//dmfs.org//mimedir.vcard//EN REV:20170924T093247Z UID:4cd6790f-1d64-4093-9b2b-60899220e64c END:VCARD`

The "TYPE" field is duplicated on all contacts created in the Android address book

**Comment by irgendwie** [comment]
Hello! Thanks for reporting this issue - we will try to improve the label handling of vcard properties.

**Comment by irgendwie** [comment]
Issue should be fixed by #380 and #382
