### ISSUE TITLE
'Contact groups' should be 'groups' in circles member management

### ISSUE THREAD

**Issue by pmarini-nc** [nextcloud/contacts#3607]
### Steps to reproduce

1. Go to Add Members to Circle
2. Search for an existing Nextcloud group
3. Add the Nextcloud group

Reproducible on c.nc.com

### Expected behavior

`Contact Groups` cannot be added to a Circle as their member (although it would be an interesting feature to evaluate).

So the member list name should be `Groups`.

### Actual behavior

`Groups` and `Contact Groups` are incorrectly swapped.

While adding the member, the description 'Add contact group' is misleading.

Once added, in the member list it should be shown as 'Groups', not 'Contact Groups'

### Web server

None

### Database engine version

None

### PHP engine version

None

### Updated from an older installed version or fresh install

None

**Comment by maximelehericy** [comment]
![image](https://github.com/nextcloud/contacts/assets/87175513/a3ef5998-5a0f-4eee-b14e-894ecc0ae91b)
