### ISSUE TITLE
Contact groups are removed when editing a contact in the WebGui

### ISSUE THREAD

**Issue by MicKress** [nextcloud/contacts#3614]
### Describe the bug

Contact groups worked fine until the update on 5.40. When I edit a contact, contact group entries are removed after saving the contact.

### Steps to reproduce

1. Go to contacts app in Nextcloud. Choose a contact.
2. Click on "Bearbeiten"
3. Click on "Speichern"
4. Contact group entries are removed from the contact

### Expected behavior

Contact group entries shouldn't be removed.

### Actual behavior

Contact group entries are removed.

### Contact version

5.40

### Operating system

NC 26.05, also on NC 26.04 Enterprise

### PHP engine version

PHP 8.1

### Web server

None

### Database

None

**Comment by ChristophWurst** [comment]
It's also not possible to assign a new group to a contact. The groups are gone after saving the contact.

**Comment by hamza221** [comment]
fixed here https://github.com/nextcloud/contacts/pull/3605
