### ISSUE TITLE
quick action button mailto mail app

### ISSUE THREAD

**Issue by punkyard** [nextcloud/contacts#3624]
![Capture d’écran 2023-09-17 à 21 02 06](https://github.com/nextcloud/contacts/assets/59349105/04abd4f2-ef38-4ad1-a5e8-41a7aff2541a)
### Is your feature request related to a problem? Please describe.

when clicking the quick action new button in a contact file, the icon opens my desktop mail app, but I use Maiul napp in nextcloud and i'd rather have this nextcloud app to be opened ^^
Wd that be possiblen you think? or have a choice in an pop up?
thanks guys!

### Additional context
![Uploading Capture d’écran 2023-09-17 à 21.02.06.png…]()

still expecting syncing with macos Contacts ;)

**Comment by ChristophWurst** [comment]
Mail has a mailto handler

**Comment by punkyard** [comment]
wonderful! thanks @ChristophWurst 
https://help.nextcloud.com/t/nextcloud-as-handler-of-mailto-links/27277/7
