### ISSUE TITLE
Reopened Issue: Contact groups get lost when editing contacts in Nextcloud Contacts App (even in 5.41)

### ISSUE THREAD

**Issue by MicKress** [nextcloud/contacts#3627]
### Describe the bug

Reopened Issue

Describe the bug
Contact groups worked fine until the update on 5.40. When I now edit a contact, contact group entries are removed after saving the contact.

### Steps to reproduce

Steps to reproduce
Go to contacts app in Nextcloud. Choose a contact.
Click on "Bearbeiten"
Click on "Speichern"
Contact group entries are removed from the contact

### Expected behavior

Expected behavior
Contact group entries shouldn't be removed.

### Actual behavior

Actual behavior
Contact group entries are removed.

### Contact version

5.41

### Operating system

NC 26.05

### PHP engine version

PHP 8.1

### Web server

None

### Database

None

**Comment by alphasixtyfive** [comment]
Confirm observing same behavior.

**Comment by ChristophWurst** [comment]
@hamza221 have a look please
