### ISSUE TITLE
Missing domain name after adding new address book in contacts

### ISSUE THREAD

**Issue by peterdunkin** [nextcloud/contacts#363]
### Steps to reproduce
1.  Click on contacts
2.  Enter new address book name ( Address book name )
3.  Select the arrow to create / add new address book
4.  Select link ( chain )

### Expected behaviour
We should see the full link complete with domain name and protocol ( http(s) )

https://mydomain.example.com/remote.php/dav/addressbooks/users/dustyspringfield/test/

### Actual behaviour
We only see the url without protocol and domain name

/remote.php/dav/addressbooks/users/dustyspringfield/test/

If we now refresh the page, we see the correct url in the link field

### Server configuration

**Operating system**:

CentOS 6

**Web server:**

Apache 2.4

**Database:**

**PHP version:**

PHP 7.1.9 

**Nextcloud version:** 

Nextcloud 12.0.3

**Contacts version:**

Contacts 1.5.3

**Updated from an older Nextcloud or fresh install:**

Updated from 12.0.2

**Signing status:**

No errors have been found.

**List of activated apps:**

Enabled:
  - activity: 2.5.2
  - bruteforcesettings: 1.0.2
  - calendar: 1.5.5
  - comments: 1.2.0
  - contacts: 1.5.3
  - dav: 1.3.0
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - systemtags: 1.2.0
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - richdocuments
  - survey_client
  - user_external
  - user_ldap

**Nextcloud configuration:**

{
    "system": {
        "instanceid": "ockv3iigmbiw",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.mydomain.com"
        ],
        "datadirectory": "\/home\/nextcloud\/data",
        "overwrite.cli.url": "https:\/\/cloud.mydomain.com",
        "dbtype": "pgsql",
        "version": "12.0.3.3",
        "dbname": "nextcloud",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "loglevel": 2,
        "updater.release.channel": "stable",
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "theme": ""
    },
    "apps": {
        "activity": {
            "installed_version": "2.5.2",
            "types": "filesystem",
            "enabled": "yes"
        },
        "backgroundjob": {
            "lastjob": "148"
        },
        "bruteforcesettings": {
            "installed_version": "1.0.2",
            "types": "",
            "enabled": "yes"
        },
        "calendar": {
            "installed_version": "1.5.5",
            "types": "",
            "enabled": "yes"
        },
        "comments": {
            "installed_version": "1.2.0",
            "types": "logging",
            "enabled": "yes"
        },
        "contacts": {
            "installed_version": "1.5.3",
            "types": "",
            "enabled": "yes"
        },
        "core": {
            "installedat": "1501283411.1847",
            "vendor": "nextcloud",
            "public_webdav": "dav\/appinfo\/v1\/publicwebdav.php",
            "public_files": "files_sharing\/public.php",
            "installed.bundles": "[\"CoreBundle\"]",
            "scss.variables": "8c6cdc1e777a50f400d3e83f727341ca",
            "lastupdatedat": "1506365319",
            "lastcron": "1506365402",
            "moveavatarsdone": "yes",
            "previewsCleanedUp": "1",
            "updater.secret.created": "1506360377",
            "oc.integritycheck.checker": "[]",
            "lastupdateResult": "[]"
        },
        "dav": {
            "installed_version": "1.3.0",
            "types": "filesystem",
            "enabled": "yes"
        },
        "federatedfilesharing": {
            "installed_version": "1.2.0",
            "types": "",
            "enabled": "yes"
        },
        "federation": {
            "installed_version": "1.2.0",
            "types": "authentication",
            "enabled": "yes"
        },
        "files": {
            "installed_version": "1.7.2",
            "types": "filesystem",
            "enabled": "yes",
            "cronjob_scan_files": "500"
        },
        "files_pdfviewer": {
            "installed_version": "1.1.1",
            "ocsid": "166049",
            "types": "",
            "enabled": "yes"
        },
        "files_sharing": {
            "installed_version": "1.4.0",
            "types": "filesystem",
            "enabled": "yes"
        },
        "files_texteditor": {
            "installed_version": "2.4.1",
            "ocsid": "166051",
            "types": "",
            "enabled": "yes"
        },
        "files_trashbin": {
            "installed_version": "1.2.0",
            "types": "filesystem",
            "enabled": "yes"
        },
        "files_versions": {
            "installed_version": "1.5.0",
            "types": "filesystem",
            "enabled": "yes"
        },
        "files_videoplayer": {
            "installed_version": "1.1.0",
            "types": "",
            "enabled": "yes"
        },
        "firstrunwizard": {
            "installed_version": "2.1",
            "types": "logging",
            "enabled": "yes"
        },
        "gallery": {
            "installed_version": "17.0.0",
            "types": "",
            "enabled": "yes"
        },
        "logreader": {
            "installed_version": "2.0.0",
            "ocsid": "170871",
            "types": "",
            "enabled": "yes"
        },
        "lookup_server_connector": {
            "installed_version": "1.0.0",
            "types": "authentication",
            "enabled": "yes"
        },
        "nextcloud_announcements": {
            "installed_version": "1.1",
            "types": "logging",
            "enabled": "yes",
            "pub_date": "Sat, 10 Dec 2016 00:00:00 +0100"
        },
        "notifications": {
            "installed_version": "2.0.0",
            "types": "logging",
            "enabled": "yes"
        },
        "oauth2": {
            "installed_version": "1.0.5",
            "types": "authentication",
            "enabled": "yes"
        },
        "password_policy": {
            "installed_version": "1.2.2",
            "types": "",
            "enabled": "yes"
        },
        "provisioning_api": {
            "installed_version": "1.2.0",
            "types": "prevent_group_restriction",
            "enabled": "yes"
        },
        "richdocuments": {
            "installed_version": "1.12.33",
            "types": "prevent_group_restriction",
            "enabled": "no"
        },
        "serverinfo": {
            "installed_version": "1.2.0",
            "types": "",
            "enabled": "yes"
        },
        "sharebymail": {
            "installed_version": "1.2.0",
            "types": "filesystem",
            "enabled": "yes"
        },
        "survey_client": {
            "installed_version": "1.0.0",
            "types": "",
            "enabled": "no"
        },
        "systemtags": {
            "installed_version": "1.2.0",
            "types": "logging",
            "enabled": "yes"
        },
        "theming": {
            "installed_version": "1.3.0",
            "types": "logging",
            "enabled": "yes"
        },
        "twofactor_backupcodes": {
            "installed_version": "1.1.1",
            "types": "",
            "enabled": "yes"
        },
        "updatenotification": {
            "installed_version": "1.2.0",
            "types": "",
            "enabled": "yes",
            "update_check_errors": "0",
            "core": "12.0.1.5"
        },
        "workflowengine": {
            "installed_version": "1.2.0",
            "types": "filesystem",
            "enabled": "yes"
        }
    }
}

**Are you using external storage, if yes which one:** local/smb/sftp/...

No

**Are you using encryption:** yes/no

No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Client configuration
**Browser:**

Firefox 55.0.3 (64-bit)

**Operating system:**

Fedora 26

**Comment by irgendwie** [comment]
Should already be fixed by https://github.com/nextcloud/contacts/pull/268, which will be in the next release! Until then, feel free to test the nightly builds (https://github.com/nextcloud/contacts#nightly-builds).
