### ISSUE TITLE
Members of circles are shown by user id instead of display name

### ISSUE THREAD

**Issue by susnux** [nextcloud/contacts#3646]
### Steps to reproduce

1. Open contacts
2. Create new circle
3. Add a user
4. See the user in the members list is shown by their user id instead of display name

### Expected behavior

Users are shown with their display name

### Actual behavior

The user id is shown as their name (this is confusing if you use some random digits as user ids).

### Web server

None

### Database engine version

None

### PHP engine version

None

### Nextcloud version

26.0.7 and 27.1.2

### Updated from an older installed version or fresh install

Fresh install

**Comment by ChristophWurst** [comment]
cc @artonge

**Comment by artonge** [comment]
Why me? I know very little about circles or users.

**Comment by ChristophWurst** [comment]
Right, my bad. Meant to ping @ArtificialOwl and @mejo- :)

**Comment by dschwerdel** [comment]
I've got the same issue. In contacts all users are shown by their Name Attribute.
(Nextcloud 29.0.4, Contacts Version 6.0.0)

But when I create a group or list the members of a group the Keycloak ID gets displayed as the Name of the group member.

Its in `<div ... class="members-modal"` `<div role="listitem" class="">` `<span ... class="option__lineone"`
In most of the entries the keycloak ID is displayed.

If I switch from sub to preferred_username in config.php the keycloak Loginname is displayed.
`      'oidc_login_attributes' => array (
          'id' => 'preferred_username',
...`

This is also not desired.  For a user only the Fullname is a usable label. Just as in `class="contacts-list"`
