### ISSUE TITLE
Related contacts in "NEXTCLOUDx.RELATED" format are not displayed

### ISSUE THREAD

**Issue by it-management** [nextcloud/contacts#3654]
### Describe the bug

In previous versions of Contacts app was possible to store Related contacts with custom label. They were stored as `NEXTCLOUDx.RELATED;TYPE=CONTACT;VALUE=UNKNOWN` and `NEXTCLOUDx.X-ABLABEL` where "x" is unsigned number. This related contacts are not shown anymore.

Current related contacts are stored as `RELATED;TYPE=type`, where "type" can be "contact", "agent", "emergency" and so on.

### Steps to reproduce

1. Go to Contact with Related contacts created in previous version of Contacts
2. There is no Related contacts shown

### Expected behavior

The Related contacts should be shown or converted to new format of Related contacts.

### Actual behavior

The Related contacts aren't showing.

### Contact version

5.4.2

### Operating system

CentOS 7

### PHP engine version

PHP 8.0

### Web server

Apache (supported)

### Database

MariaDB

### Additional info

An example of .VCF file exported from Contacts with both the old and new storage format of Related contacts:
```
BEGIN:VCARD
VERSION:3.0
PRODID;VALUE=TEXT:-//Sabre//Sabre VObject 4.4.2//EN
UID:4710adc9-776a-4c27-ba4b-75f086a4afb9
FN:John Doe
EMAIL;TYPE=WORK:john.doe@example.com
URL:https://example.com/
NEXTCLOUD1.RELATED;TYPE=CONTACT;VALUE=UNKNOWN:https://example.com/jane.doe.old
NEXTCLOUD2.RELATED;TYPE=CONTACT;VALUE=UNKNOWN:https://example.com/foo.ham.old
RELATED;TYPE=ASSISTANT;VALUE=UNKNOWN:https://example.com/jane.doe.new
RELATED;TYPE=CONTACT;VALUE=UNKNOWN:https://example.com/foo.ham.new
NEXTCLOUD1.X-ABLABEL:Jane Doe
NEXTCLOUD2.X-ABLABEL:Foo Ham
REV;VALUE=DATE-TIME:20231011T091007Z
END:VCARD
```

**Comment by hamza221** [comment]
Should be solved in the upcoming version 5.4.3
