### ISSUE TITLE
Contacts render unstyled

### ISSUE THREAD

**Issue by despens** [nextcloud/contacts#370]
![contacts - nextcloud - mozilla firefox_00141](https://user-images.githubusercontent.com/571494/31133599-4c080faa-a860-11e7-9bc6-d1461771fec9.png)

### Steps to reproduce
1. update contacts in apps
2. go to contacts

### Expected behaviour
Contacts should be rendered

### Actual behaviour
Contacts rendered unstyled

### General server configuration

**Operating system:** Ubuntu 16.06

**Web server:** Apache/2.4.18 (Ubuntu) (apache2handler)

**Database:** mysql 10.0.31

**PHP version:** 7.0.22-0ubuntu0.16.04.1
<details>
        <summary>PHP-modules loaded</summary>

```
 - Core
 - date
 - libxml
 - openssl
 - pcre
 - zlib
 - filter
 - hash
 - Reflection
 - SPL
 - session
 - standard
 - apache2handler
 - mysqlnd
 - PDO
 - xml
 - apcu
 - calendar
 - ctype
 - curl
 - dom
 - mbstring
 - fileinfo
 - ftp
 - gd
 - gettext
 - iconv
 - igbinary
 - imagick
 - json
 - exif
 - mysqli
 - pdo_mysql
 - Phar
 - posix
 - readline
 - redis
 - shmop
 - SimpleXML
 - sockets
 - sysvmsg
 - sysvsem
 - sysvshm
 - tokenizer
 - wddx
 - xmlreader
 - xmlwriter
 - xsl
 - zip
 - Zend OPcache
```
</details>

### Nextcloud configuration

**Nextcloud version:** 11.0.5 (stable) - 11.0.5.1

**Updated from an older Nextcloud/ownCloud or fresh install:** updated

**Where did you install Nextcloud from:**  tar file

**Are you using external storage, if yes which one:** Array
(
    [0] => \OC\Files\Storage\Local
    [1] => \OCA\Files_External\Lib\Storage\FTP
    [2] => \OC\Files\Storage\DAV
    [3] => \OCA\Files_External\Lib\Storage\OwnCloud
    [4] => \OCA\Files_External\Lib\Storage\SFTP
    [5] => \OCA\Files_External\Lib\Storage\AmazonS3
    [6] => \OCA\Files_External\Lib\Storage\Dropbox
    [7] => \OCA\Files_External\Lib\Storage\Google
    [8] => \OCA\Files_External\Lib\Storage\Swift
    [9] => \OCA\Files_External\Lib\Storage\SFTP
)

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

<details>
        <summary>Signing status</summary>

```
[]
```
</details>

<details>
        <summary>Enabled apps</summary>

```
 - activity: 2.4.1
 - admin_audit: 1.1.0
 - announcementcenter: 3.0.0
 - apporder: 0.3.3
 - calendar: 1.5.5
 - checksum: 0.3.5
 - comments: 1.1.0
 - contacts: 2.0.0
 - dav: 1.1.1
 - direct_menu: 0.10.2
 - external: 1
 - federatedfilesharing: 1.1.1
 - federation: 1.1.1
 - files: 1.6.1
 - files_accesscontrol: 1.1.2
 - files_automatedtagging: 1.1.1
 - files_external: 1.1.2
 - files_markdown: 2.0.1
 - files_sharing: 1.1.1
 - files_texteditor: 2.2
 - files_trashbin: 1.1.0
 - files_versions: 1.4.0
 - files_videoplayer: 1.0.0
 - firstrunwizard: 2.0
 - gallery: 16.0.0
 - issuetemplate: 0.2.2
 - logreader: 2.0.0
 - lookup_server_connector: 1.0.0
 - nextcloud_announcements: 1.0
 - notifications: 1.0.1
 - password_policy: 1.1.0
 - previewgenerator: 1.0.7
 - provisioning_api: 1.1.0
 - serverinfo: 1.1.1
 - sharebymail: 1.0.1
 - survey_client: 0.1.5
 - systemtags: 1.1.3
 - templateeditor: 0.2
 - theming: 1.1.1
 - twofactor_backupcodes: 1.0.0
 - updatenotification: 1.1.1
 - user_external: 0.4
 - workflowengine: 1.1.1
```
</details>

<details>
        <summary>Disabled apps</summary>

```
 - deck
 - encryption
 - files_downloadactivity
 - files_pdfviewer
 - files_retention
 - nextant
 - spreed
 - tasks
 - user_ldap
 - user_saml
```
</details>

<details>
        <summary>Content of config/config.php</summary>

```
{
    "instanceid": "51e29b69eaed2",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "datadirectory": "\/var\/nextcloud",
    "dbtype": "mysql",
    "version": "11.0.5.1",
    "dbname": "nextcloud",
    "dbhost": "localhost",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "mail_smtpmode": "sendmail",
    "forcessl": true,
    "loglevel": 0,
    "overwrite.cli.url": 1,
    "theme": "",
    "maintenance": false,
    "trusted_domains": [
        "oc.1x-upon.com",
        "staging.oc.1x-upon.com",
        "nc.1x-upon.com"
    ],
    "blacklisted_files": [],
    "secret": "***REMOVED SENSITIVE VALUE***",
    "preview_max_scale_factor": 1,
    "enabledPreviewProviders": [
        "OC\\Preview\\Image",
        "OC\\Preview\\MP3",
        "OC\\Preview\\TXT",
        "OC\\Preview\\OpenDocument",
        "OC\\Preview\\PDF",
        "OC\\Preview\\SVG",
        "OC\\Preview\\Movie",
        "OC\\Preview\\MSOffice2003",
        "OC\\Preview\\MSOffice2007",
        "OC\\Preview\\MSOfficeDoc",
        "OC\\Preview\\Illustrator",
        "OC\\Preview\\Photoshop",
        "OC\\Preview\\TIFF"
    ],
    "memcache.local": "\\OC\\Memcache\\APCu",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "localhost",
        "port": 6379
    },
    "trashbin_retention_obligation": "auto",
    "mail_from_address": "robobot",
    "mail_domain": "nc.1x-upon.com",
    "htaccess.RewriteBase": "\/",
    "appstore.experimental.enabled": true,
    "updater.release.channel": "stable"
}
```
</details>

### Client configuration

**Browser:** Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0

**Operating system:** Ubuntu 16.04

**Comment by skjnldsv** [comment]
Will fix asap! Sorry! :)

**Comment by irgendwie** [comment]
@despens If your still experiencing issues after upgrading to v2.0.1, please let me know!

**Comment by despens** [comment]
All good! Thanks for quickest bug fix ever :+1:
