### ISSUE TITLE
Visibility of Contact Groups is broken in Detail View

### ISSUE THREAD

**Issue by MicKress** [nextcloud/contacts#3706]
### Describe the bug

If a contact belongs to two or more Contact Groups, the visibility in Detail View is broken.

<img width="508" alt="Bildschirmfoto 2023-11-17 um 18 01 53" src="https://github.com/nextcloud/contacts/assets/47255870/dbfdd0f7-125b-4a2f-8951-93b031b751a8">

With only one Contact group the visibility is ok.

<img width="384" alt="Bildschirmfoto 2023-11-17 um 18 03 40" src="https://github.com/nextcloud/contacts/assets/47255870/95fda26f-b47a-4f37-8526-b0eecca33c65">

This behaviour exits since the upgrade to NC 27.12

### Steps to reproduce

1. Go to Contacts App
2. Click on one Contact with several Contact Groups
3. Look at the detail view
4. Check the visibility of Contact Groups

### Expected behavior

Contact Groups should be readable

### Actual behavior

The visibility of Contact Groups ist broken

### Contact version

5.4.3

### Operating system

NC 27.12

### PHP engine version

None

### Web server

None

### Database

None

**Comment by MicKress** [comment]
Sry, contact version 5.42

**Comment by hamza221** [comment]
@GVodyanov  were you able to reproduce ?

**Comment by GVodyanov** [comment]
Actually no but I figured while I'm here anyway may as well make it look nicer, as I don't think it makes sense for single and multiple groups to look so different, so that's what I'm working on currently.
