### ISSUE TITLE
if 'last name' sorting has been set the comma between the last and first name should be suppressed when no first name has been entered

### ISSUE THREAD

**Issue by j-ed** [nextcloud/contacts#373]
## Expected behavior
If the sorting order `last name` has been set, the comma which usually separates the last and first name, should be suppressed when no first name has been entered.

## Current behavior
A comma behind the last name is always shown independently if a first name has been entered or not.

![20171003_contacts_commata](https://user-images.githubusercontent.com/2572764/31139458-e7fb4dc6-a871-11e7-8ca5-eb37e5a7ead0.png)

### Steps to reproduce
1. Open the contacts app
2. Set the sorting order to 'last name'
3. check-out a contact for which no first name has been entered.

#### Server Configuration
OS: Linux 3.16.47
Web server: Apache2 2.4.26
Database: MariaDB 10.0.32
PHP version: 5.6.30
Nextcloud version: 12.03
Contacts app version: 2.0.0

#### Client Configuration
Browser: Mozilla Firefox 56.0
Operating system: Windows 7

**Comment by irgendwie** [comment]
Thanks for taking the time and reporting these issues! :+1:

**Comment by Nitiquita** [comment]
I'm going to try working on this!

**Comment by Henni** [comment]
@Nitiquita take a look at this section: https://github.com/nextcloud/contacts#building-the-app

To get going with this issue, you might want to start over here: https://github.com/nextcloud/contacts/blob/master/js/components/contact/contact_controller.js#L15

**Comment by j-ed** [comment]
@Nitiquita It seems that a pull request already exists for this issue: https://github.com/nextcloud/contacts/pull/377

**Comment by suntala** [comment]
I am interested in working on this issue, but I am having trouble recreating it as you can see in this picture: https://screenshot.net/ognzyiz (please ignore the red boxes). Any ideas why?

**Comment by skjnldsv** [comment]
@suntala last name sorting is broken for now. We need to fix it. :/

**Comment by skjnldsv** [comment]
@suntala you need to use the full name detailed field to reproduce this issue! :)

**Comment by suntala** [comment]
@skjnldsv thanks for the info! Is this issue something I have a chance of fixing even though last name sorting is broken?

**Comment by suntala** [comment]
Could I please be assigned this ticket?

**Comment by skjnldsv** [comment]
@suntala, don't ask, assign yourself and push a pr! :)
