### ISSUE TITLE
Modified Text on Labels of fields are not stored in db or shown from db anymore in contacts since nc26

### ISSUE THREAD

**Issue by alink03** [nextcloud/contacts#3738]
### Describe the bug

On modifing a label for example Telefon -> MyTelefon or an address lable Address -> privateAddress this is not shown again after saving, changing the dataset an recalling the modified contact.

![01 editing-dataset](https://github.com/nextcloud/contacts/assets/143262552/c1334cf6-8c80-44b8-b84f-f6d1842ebbf7)
![02 saved-dataset_after-editing](https://github.com/nextcloud/contacts/assets/143262552/27b00a15-a910-4b4c-9fee-fe7fdffbb62d)
![03 dataset-after-recalling](https://github.com/nextcloud/contacts/assets/143262552/d8c9c9d5-bd12-4eaa-b5eb-b458d477706b)
![04 dataset seen by cardbook via carddav](https://github.com/nextcloud/contacts/assets/143262552/cf4c0e84-81a0-4c9e-b1e8-dc6e169d0bbe)

Dataexport via carddav also seems not working well.

This effect or behavior was not before nc26. Since nc26 and nc27 (also on different systems) the problems existing.

### Steps to reproduce

1. Go to contacts
2. Click on new oder edit contact
3. modify label e.g. "Telefon" throug "Haustelefon" 
4. save dataset
5. change dataset
6. recall created or modified dataset
7. take a look on modified label

take a look on the tree pictures.

### Expected behavior

the content of the modified label is lost
"Haustelefon" shoud shown on label

expected behavior should be "02 saved-dataset_after-editing.jpg"

### Actual behavior

"privat" is schown instead of "Haustelefon"

take a look on "03 dataset-after-recalling.jpg"

### Contact version

5.5.0

### Operating system

NC27 - debian-bullseye

### PHP engine version

Other

### Web server

Apache (supported)

### Database

MariaDB

### Additional info

php8.2.13

**Comment by ChristophWurst** [comment]
https://github.com/nextcloud/contacts/pull/3653 could be related
