### ISSUE TITLE
do not import vcard contacts by clicking on the file, ask before!

### ISSUE THREAD

**Issue by usernamehyphen** [nextcloud/contacts#3756]
### Is your feature request related to a problem? Please describe.

when accidentally clicking on some vcf file with not a very descriptive name (turns out it was a backup), Contacts opened and duplicated most of my _contacts_

### Describe the solution you'd like

maybe ask next time? 

### Additional context

its not that complicated, so there is not much text, thanks

**Comment by joshtrichards** [comment]
Duplicate of #2788
