### ISSUE TITLE
No more export ?

### ISSUE THREAD

**Issue by MiyukiNeko** [nextcloud/contacts#381]
Hi,

Just update the new version, their is no more export adress book option ? Only import now ? 
Where is the option ? And if it disapear, why ?

Thx.

**Comment by skjnldsv** [comment]
@MiyukiNeko Hi!
Which version of nextcloud are you using? And have you tried clicking the menu icon (three dots) :)

**Comment by MiyukiNeko** [comment]
NextCloud 11.0.5

The option was in "Parameter" before, actually i have an import buton only.

![capture](https://user-images.githubusercontent.com/32509426/31168394-7846ee84-a8f5-11e7-9c0f-b03ed9e23f0f.PNG)

**Comment by MiyukiNeko** [comment]
I've found more information.

Actually i use FireFox (Cf scrennshot), and no dots option.

On Google Chrome, option appear, and i can export.

This bug is only on Firefox.
