### ISSUE TITLE
Renaming contacts app to 'people'

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/contacts#3816]
While discussing https://github.com/nextcloud/server/issues/42433 with @nextcloud/designers the request came up to rename the "Contacts" app to "People" to account for the wider scope it has with also managing Teams (circles).

@nextcloud/designers Has that decision been made final already?

Also involving @ChristophWurst as the team lead for the contacts app

**Comment by juliushaertl** [comment]
Should be rediscussed with Frank after checking with @jancborchardt. @jancborchardt will check that

**Comment by ChristophWurst** [comment]
@jancborchardt would we keep "Contact" for the entries of an addressbook or does that change to "Person" (singular of people) or anything else?

**Comment by jancborchardt** [comment]
As discussed with @karlitschek and @jospoortvliet, we can stick with "Contacts" as it’s not such an impactful change and also might be confusing since other popular apps call this place "Contacts". But the change from "Circles" to "Teams" is the relevant one.

So closing this hence.
