### ISSUE TITLE
Shares for a shared address book always empty

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/contacts#3839]
### Describe the bug

I shared my Testing address book with "Bob", but in the address book settings modal it doesn't show whom I shared the address book with for the sharer.

### Steps to reproduce

1. ??

### Expected behavior

Addressbook is shared

### Actual behavior

??

### PHP engine version

None

### Web server

None

### Database

None

**Comment by miaulalala** [comment]
It's there, just needs an interaction with the share button unlike in Calendar:

![image](https://github.com/nextcloud/contacts/assets/7427347/69d2b7e9-d1ee-4da2-b388-59a5c44f3f16)
