### ISSUE TITLE
Contacts 2.0.1 - Calendar Link URL doesn't show up

### ISSUE THREAD

**Issue by Delor3an** [nextcloud/contacts#384]
### Steps to reproduce
1. Select an address book in the list
2. Click on the pictogram link
3. Nothing shows up

### Expected behaviour
Tell us what should happen

1. Select an address book in the list
2. Click on the pictogram link
3. Address book' URL shows up

### Actual behaviour
Tell us what happens instead

1. Select an address book in the list
2. Click on the pictogram link
3. Nothing shows up

### Server configuration

**Operating system**: Synology DSM 6.1.3 15152-6

**Web server: Apache 2.4

**Database:** MySQL Maria DB 5

**PHP version: 7.0

**Nextcloud version: 12.0.3

**Contacts version: 2.0.1

**Updated from an older Nextcloud or fresh install: Updated from an older Nextcloud

**Signing status: OK

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
No errors have been found.

**List of activated apps:

[1.pdf](https://github.com/nextcloud/contacts/files/1355891/1.pdf)
[2.pdf](https://github.com/nextcloud/contacts/files/1355892/2.pdf)

**Are you using external storage, if yes which one: no

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one: no

### Client configuration
**Browser: Firefox 56.0

**Operating system: MacOS X 10.13.1

**Comment by irgendwie** [comment]
The address book list should look like this:

![2017-10-04-152441_499x101](https://user-images.githubusercontent.com/8360698/31178104-579df61e-a918-11e7-8835-88d65d35500e.png)

After you click 'Copy link', the URL should be copied to your clipboard.

**Comment by skjnldsv** [comment]
Should we set the text to "Copy link to clipboard"?

**Comment by Delor3an** [comment]
I had the 3 dots before 2.0.0 but the I had :
![contacts](https://user-images.githubusercontent.com/17692382/31178468-819205ea-a919-11e7-97ee-c91e694a7802.jpeg)

**Comment by irgendwie** [comment]
Could you try clearing the cache and/or use the private mode of your browser? I have no problems when using 2.0.1 and firefox.

**Comment by Delor3an** [comment]
Indeed... It make the trick !

Thank You Guys ;-)

You may close
