### ISSUE TITLE
Contact federation to use contacts from addressbooks on other (NC/carddav) servers (not import!)

### ISSUE THREAD

**Issue by janklostermann** [nextcloud/contacts#3855]
### Is your feature request related to a problem? Please describe.

I have described the problem in https://github.com/nextcloud/mail/issues/9487 as it affects me primarily in the mail app.
But @ChristophWurst is right, it is a problem of the Contacts app (at least from a users perspective, [server](https://github.com/nextcloud/server/) might be another possible place). At least for the prefered solution, from my point of view.

Short version: There is no federation for contacts available yet. 
In the [manual](https://docs.nextcloud.com/server/latest/user_manual/en/groupware/contacts.html) the section "Synchronizing with Nextcloud" is missing... ;-)

### Describe the solution you'd like

I would like to be able to federate my other nextclouds and this way make (all, better: selected) addressbooks from those federated servers available in the contacts app and through this, available in other apps, like Mail, for their specific usage. 
For other NC-apps there should be no difference perceivable to a NC-local addressbook, once the federation is established.
Also all meaningful Contact features should work also with the federated addressbooks (respecting permissions). Just like with synching to other counterparts (like Android and other OS, which in such case act as unifying clients, rather than as carddav servers).

Contacts would not just be the GUI to view and edit the addressbook data of the internal carddav server and serve it to other NC apps. (Do I overlook something?)

Instead Contacts would become a fully-featured addressbook management app, that can also handle addressbooks served by other servers. Maybe comparable to Cardbook (plugin) for Thunderbird, or better(?): the addressbook infrastructure of Android, with the addition of the already existing carddav server functionality. 

Long story short: Contacts becomes (or gets access to) a carddav client, capable to handle more than one carddav server, beyond the internal addressbooks from the local NC database, with all the beauties of federation.

### Describe alternatives you've considered

A more basic integration would probably be the integration of the addressbooks of other server through carddav synchronization, as all the clients mentioned in the manual (connecting to a NC server) do it. Without the simplicity for users that federation could bring.
This could have the advantage of being usable more general, as not all addressbook servers (that might serve carddav) will also serve the NC federation protocol. 

### Additional context

Providing both (carddav (client & server) and the NC federation) seems to be the perfect solution.

**Comment by janklostermann** [comment]
Sorry, I did not read the [comment] by @ChristophWurst carefully enough. 
If Contacts as well is only using the functionality provided by server's API, this should apparently be placed with [server](https://github.com/nextcloud/server/).
 
But probably the GUI elements to provide/manage this functionality would lay in Contacts, or should they be settings (under the federation or the Contacts section)?

Is it necessary to create another issue with [server](https://github.com/nextcloud/server/)?

**Comment by ChristophWurst** [comment]
I think it would be best to consult https://help.nextcloud.com/c/support/7.

I can't provide support for this.

**Comment by janklostermann** [comment]
Thanks a lot for your support so far!
