### ISSUE TITLE
Selected group GUI feedback

### ISSUE THREAD

**Issue by thesteff** [nextcloud/contacts#386]
Hi !

I'm often surprised that the search engine don't find one of my contact profil... but it's often because I've just clicked on a group label before. By the way it's a cool feature : the search engine works on the pre-selected contacts corresponding to the group wich have been clicked before. The problem is there's no visual indication saying that.

When a group is selected, the corresponding label should by displayed "selected". The rule should be that there's always a group selected, "all contacts" by default. The only exception could be when we are creating a new contact.... but on large screen the contact list remain visible so it makes sense to keep a selected item feedback even in this case.

Again, thanks for your work !

**Comment by irgendwie** [comment]
By default 'All contacts' should be auto selected. This only changes if you change the group by yourself.
The selected group is highlighted by a bar on the left (Nextcloud design) and a bold font.

If I understand you correctly, you are surprised, that the search works more like a list filter instead of a search? Maybe we can offer to expand the search to 'All contacts', if the search results in no findings.
Or even show it at the bottom of the contact list? Would this help in the understand of the mechanics of the search?

**Comment by thesteff** [comment]
Actually I'm surprised there's no way to see wich group is currently selected.

**Comment by irgendwie** [comment]
With Nextcloud 12 it should look like this:

![groups](https://user-images.githubusercontent.com/8360698/31224885-f6cbb106-a9cf-11e7-8b5c-f03618534163.png)

With Nextcloud 11 the bar on the left is missing, so maybe you are using Nextcloud 11?
The bar on the left was introduced with Nextcloud 12 in the "official" design.
This still leaves the bold font for the group.

**Comment by thesteff** [comment]
I'm using Nextcloud 12.0.3
The colored bar on the left and the bold style (as we can see on your picture) are applied on the "hover" event but that's all for me. When the group is selected I have no way to know about it. All labels are displayed in a classic way.

In my admin panel, I've just an OPCache and getenv("PATH") issues concerning PHP, but I don't think it's related to this problem. (?) Nextcloud seems to work correctly despite these warnings.

**Comment by skjnldsv** [comment]
I'm on 12 and have the coloured bar feedback  on selected groups! :/

**Comment by thesteff** [comment]
I notice that the "selected effect" (bold + left bar) is working fine for the activity/files/admin sections.
If I can do something to help you correct this minor bug, just let me know...

**Comment by irgendwie** [comment]
@thesteff If you have ssh/ftp access to your Nextcloud instance, would you mind testing the following:

1. go into `apps/contacts/css` and rename `style.css` (**not** `style.scss) to `style.css.bak`
2. access the contacts app via your browser
3. Press <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>r</kbd> to clear the cache and reload the page

Afterwards please check if everything is working correctly and if the problem persists.

**Comment by thesteff** [comment]
I just upgrade the app to 2.0.1 and now it's working fine !
Just before the upgrade, I looked into the `apps/contacts/css` and there was no files except a `public` directory containing `style.css`. After the upgrade, there's many .css files and the directory `public` no longer exist.
Thanks for your work !
