### ISSUE TITLE
Download address book option vanished in 2.0.1

### ISSUE THREAD

**Issue by dschrempf** [nextcloud/contacts#388]
Hello,

after I upgraded Contacts to version 2.0.1, the address books cannot be downloaded anymore. Usually, I click on Settings and then on a downwards facing arrow to download my address book(s). This arrow is gone. I think this already has happened before.

Nextcloud version: 12.0.3-3.

Thank you!

Edit: error -> arrow :-)

**Comment by xh3n1** [comment]
Hello  @dschrempf,
Please,  click on Settings, then on the 3-dot-icon menu of your address book and then click on the download option. It should work :)

**Comment by dschrempf** [comment]
Hi,
there is no three dot menu next to my address book. Do you have an idea
why this could be?

**Comment by irgendwie** [comment]
Can you try clearing your browser cache and/or the private mode of your browser? Maybe even try a different browser? Seems like the CSS is being cached.

**Comment by dschrempf** [comment]
Hm, thank you, this resolved the issue. After clearing the cache, the menu is visible. Sorry for bothering you, but it is strange, that these things happen :-).

**Comment by skjnldsv** [comment]
No worries! :)
