### ISSUE TITLE
Currently not possible to download group of contacts.

### ISSUE THREAD

**Issue by brjhaverkamp** [nextcloud/contacts#39]
At the moment it is not possible to select a single group of contacts and export/download it as a vcard file.
This used to be possible with the older contact app (last year) 
Can this feature be re-added again?

Regards,

Bert

**Comment by irgendwie** [comment]
#43 only restores the export functionality - downloading specific groups separately is still **not** supported

**Comment by skjnldsv** [comment]
Oooh, sorry, you meant groups, I was thinking of addressbooks :(

**Comment by brjhaverkamp** [comment]
:-) Indeed. Selecting a contact group to download. (And multiple addresses or groups, I guess for completeness). I'm really missing it now I have to do my Christmas cards again..

But I see where you are coming from, didn't know that functionality had disappeared too.
Thanks for that addition!

**Comment by brjhaverkamp** [comment]
Hello, can you comment why this issue is closed? 

Today I started my christmas card address list. I have a group for that in Nextcloud and it seems it is still not possible to download that group seperately. I now have to download my whole addressbook and script a filter.

**Comment by skjnldsv** [comment]
@brjhaverkamp this issue is not closed! :)

**Comment by skjnldsv** [comment]
This will require a php script from the server to filter out vcards or generate a single file from multiple vcards, should be straightforward though.

**Comment by brjhaverkamp** [comment]
Sounds good. 3.0? :-)

**Comment by skjnldsv** [comment]
@brjhaverkamp Not enough time available!
If someone want to take over and implement such function on server, then perfect. Otherwise too sort for 3.0! :(

**Comment by brjhaverkamp** [comment]
If you can point me at where I could integrate this, I could have a stab at it. Not in the coming weeks.(just started a new job) But christmas-card-season is slowly approaching, so around that time I have my yearly focus on the contacts app.

**Comment by skjnldsv** [comment]
Sure! :)
The vcf addressbook export is an official plugin, so you cannot edit it on nc, but the source is available as inspiration:
Example of a nextcloud plugin for dav: https://github.com/nextcloud/3rdparty/blob/master/sabre/dav/lib/CardDAV/VCFExportPlugin.phphttps://github.com/nextcloud/server/blob/2e36069e24406455ad3f3998aa25e2a949d1402a/apps/dav/lib/CardDAV/ImageExportPlugin.php

The idea would be to allow to pass data to the ?export request on an addressbook to request a set of vcard? But this will only allow download by addressbook (which is fine, 99% of our users uses 1 addressbook, and we can trigger multiple requests depending on the addressbooks od the contacts I guess)

**Comment by charismatic-claire** [comment]
Hi, I just added a pull request for that. Please review and let me know, if that is acceptable!

**Comment by charismatic-claire** [comment]
Okay. Here are some architectural thoughts and ideas:

- From the "contacts" app, we are only calling a function, say a `downloadGroup(group)` function via the computed property `groupsMenu()` in the `Contacts.vue` component.
- This call basically is a HTTP GET request from an URL like this `http://<SERVER_ADDRESS>/remote.php/dav/addressbooks/users/<USER_NAME>/<GROUP_NAME>?export`
- The actual work happens on the server side. For this we need to make a pull request to the "server" project itself.
- What we need is a `GroupExportPlugin.php` with namespace `OCA\DAV\CardDAV` extending the "dav" application of the Nextcloud server.
- The `GroupExportPlugin` would extend the `ServerPlugin` from `Sabre\DAV\ServerPlugin`.
- We would use `dav/appinfo/v1/carddav.php` to register our new plugin.
- First major question would be: How to implement the magic we want?
- Second major question would be: How and where to register the routes properly?

Well, is that more or less what we want, or do I absolutely not get it?

**Comment by skjnldsv** [comment]
@charismatic-claire I started yesterday implemnting the plugin! :)
You are mostly right on your points, only those I would make a cmall change:

> This call basically is a HTTP GET request from an URL like this http://<SERVER_ADDRESS>/remote.php/dav/addressbooks/users/<USER_NAME>/<GROUP_NAME>?export

I would rather have a POST that takes an array of vcf url to be downloaded.
Like I said to allow groups download but also selections or searches 

> We would use dav/appinfo/v1/carddav.php to register our new plugin.

Apparently also on `apps/dav/lib/Server.php`, but yes :)

**Comment by charismatic-claire** [comment]
Wow, making a PR to the "server" project seem to get the attention of quite some people. I'm impressed by the amount of feedback you already got. I'll review your code as well... Thank's a lot for pushing things forward.

**Comment by charismatic-claire** [comment]
I understand the debate. But since we are not limited to HTTP requests, we can maybe use one of those: 
- PROPFIND
- PROPPATCH
- REPORT
- MKCOL
- MKCALENDAR
- ACL

Maybe we have to study this document for answers:
[Building a CardDAV client](http://sabre.io/dav/building-a-carddav-client/)

The question is, how can we basically have a GET request, but with a body for the payload, right? The problem is: a GET request usually doesn't have a body, while a POST request usually would change a state. But we don't want to change a state. Since this is a carddav client, are we allowed to use other methods? I'm not sure...

**Comment by charismatic-claire** [comment]
In the aforementioned article [Building a CardDAV client](http://sabre.io/dav/building-a-carddav-client/), I found this. Sound like what we want, doesn't it?

---

To fetch the data for these, you can simply issue GET requests:

`GET /addressbooks/johndoe/contacts/abc-def-fez-123454657.vcf`

But that does not scale up well, in case a few hundred contacts have changed. It's better to batch the GET's together with multiget.

```
REPORT /addressbooks/johndoe/contacts/ HTTP/1.1
Depth: 1
Content-Type: application/xml; charset=utf-8

<card:addressbook-multiget xmlns:d="DAV:" xmlns:card="urn:ietf:params:xml:ns:carddav">
    <d:prop>
        <d:getetag />
        <c:address-data />
    </d:prop>
    <d:href>/addressbooks/johndoe/contacts/abc-def-fez-123454657.vcf</d:href>
    <d:href>/addressbooks/johndoe/contacts/acme-12345.vcf</d:href>
</card:addressbook-multiget>

```

This request will simply return a multi-status again with the address-data and etag.

---

I'm not sure if we can really sure if we could utilize this, but the REPORT request used as a batch GET request just sounds right...

**Comment by georgehrke** [comment]
I integrated the multiget + export in our cdav-library: https://github.com/nextcloud/cdav-library/pull/39#issue-228184231

I don't think we even need the [npm package](https://www.npmjs.com/package/file-saver) referred to by @skjnldsv in https://github.com/nextcloud/server/pull/12004.

**Comment by skjnldsv** [comment]
@georgehrke you're awesome!!
@charismatic-claire care to update your pr accordingly? :)

**Comment by skjnldsv** [comment]
https://github.com/nextcloud/cdav-library/pull/39 have been merge, we can not use it in contacts! :tada:

**Comment by brjhaverkamp** [comment]
Thank you for the great hard work!

**Comment by charismatic-claire** [comment]
@skjnldsv I will update my PR as soon as possible... Thank you for your work and your encouragement. I learned a lot.
@georgehrke Thank you for your work as well!

**Comment by skjnldsv** [comment]
@charismatic-claire awesome!
Ping me if you need anything :)

**Comment by charismatic-claire** [comment]
Alright. So let's make a little plan first. What do we wanna do? Shall I just add download links to every group, so we can download it and that's it? Or do we wanna go for more?

In case we wanna go for more, I need a little bit more information. If you want, say download 2 groups at the same time, you would need a way to first select which groups you wanna download and then trigger the download. How would that look like? You could set "download checkmarks" first and trigger the download later on by clicking a button? Where would that button be?

If you wanna make a search or a manual selection of contacts to download, how would you first select and later on trigger the download? I'm not talking about the implementation, I'm talking about the interface design here.

Personally I would prefer to just add a download button to each group, like I did before. Only this time, I'll utilize the recently added capabilities of the backend. But I'm not sure if @skjnldsv would such a pull request. My understanding is... not. So let's talk about it ;-)

**Comment by skjnldsv** [comment]
I would say, let's do it step by step! :)
Maybe create a function that trigger a download following Gerog's hack (see https://github.com/nextcloud/cdav-library/pull/39) with an array of urls within an addressbook.
So we can use it for the groups but also later use it for a selection or something :)

One issue is that we can have groups accross multiple addressbooks, so we'll have to trigger as many REPORT as there are addressbooks. I'll let you figure out, this is just a matter of sorting the proper data and triggering the proper REPORT and download I guess :)

I'm completely fine with the download button for each group. 

> If you wanna make a search or a manual selection of contacts to download, how would you first select and later on trigger the download? I'm not talking about the implementation, I'm talking about the interface design here.

Let's see that for the 3.1.0 version ;)

**Comment by charismatic-claire** [comment]
Great. I like that. So let's do it. I'll let you know if I have something to show...

**Comment by charismatic-claire** [comment]
Yeah, I implemented a new version of this feature, using the `multiget` functionality. What do you think??? See pull request.

**Comment by brjhaverkamp** [comment]
Hello Charismatic-clair,

While you are on a roll with the contacts app of Nextcloud and this great improvement in issue 37, could I ask you to take a look at issue #42?
This is my other pet-peave regarding the LABEL field in the Vcard that is used in for instance the glabel program.
