### ISSUE TITLE
Option for exporting adressbooks has vanished

### ISSUE THREAD

**Issue by dajusc** [nextcloud/contacts#392]
### Steps to reproduce
1. In the App click Settings/Options in the lower left.
2. Option to export all contacts from an adressbook has vanished

### Expected behaviour
Below the name of the adressbook, there should be an option to export an adressbook to vcf.

### Actual behaviour
The option is missing.

### General server configuration
**Operating system:** Linux cloud 3.16.0-4-amd64 #1 SMP Debian 3.16.43-2+deb8u5 (2017-09-19) x86_64

**Web server:** Apache (apache2handler)

**Database:** mysql 5.5.57

**PHP version:** 5.6.30-0+deb8u1
<details>
        <summary>PHP-modules loaded</summary>

```
 - Core
 - date
 - ereg
 - libxml
 - openssl
 - pcre
 - zlib
 - bcmath
 - bz2
 - calendar
 - ctype
 - dba
 - dom
 - hash
 - fileinfo
 - filter
 - ftp
 - gettext
 - SPL
 - iconv
 - mbstring
 - session
 - posix
 - Reflection
 - standard
 - shmop
 - SimpleXML
 - soap
 - sockets
 - Phar
 - exif
 - sysvmsg
 - sysvsem
 - sysvshm
 - tokenizer
 - wddx
 - xml
 - xmlreader
 - xmlwriter
 - zip
 - apache2handler
 - PDO
 - curl
 - gd
 - json
 - mysql
 - mysqli
 - pdo_mysql
 - redis
 - XCache
 - mhash
 - XCache Optimizer
 - XCache Cacher
 - XCache Coverager
 - Zend OPcache
```
</details>

### Nextcloud configuration

**Nextcloud version:** 12.0.3 - 12.0.3.3

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated

**Where did you install Nextcloud from:**  https://nextcloud.com/

**Are you using external storage, if yes which one:** files_external is disabled

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** WebDav (Android, DavDroid)

<details>
        <summary>Signing status</summary>

```
[]
```
</details>

<details>
        <summary>Enabled apps</summary>

```
 - activity: 2.5.2
 - admin_audit: 1.2.0
 - bruteforcesettings: 1.0.2
 - calendar: 1.5.5
 - comments: 1.2.0
 - contacts: 2.0.1
 - dav: 1.3.0
 - federatedfilesharing: 1.2.0
 - federation: 1.2.0
 - files: 1.7.2
 - files_pdfviewer: 1.1.1
 - files_sharing: 1.4.0
 - files_texteditor: 2.4.1
 - files_trashbin: 1.2.0
 - files_versions: 1.5.0
 - files_videoplayer: 1.1.0
 - firstrunwizard: 2.1
 - gallery: 17.0.0
 - issuetemplate: 0.2.2
 - logreader: 2.0.0
 - lookup_server_connector: 1.0.0
 - nextcloud_announcements: 1.1
 - notifications: 2.0.0
 - oauth2: 1.0.5
 - password_policy: 1.2.2
 - provisioning_api: 1.2.0
 - serverinfo: 1.2.0
 - sharebymail: 1.2.0
 - survey_client: 1.0.0
 - tasks: 0.9.5
 - theming: 1.3.0
 - twofactor_backupcodes: 1.1.1
 - updatenotification: 1.2.0
 - workflowengine: 1.2.0
```
</details>

<details>
        <summary>Disabled apps</summary>

```
 - encryption
 - files_external
 - systemtags
 - user_external
 - user_ldap
```
</details>

<details>
        <summary>Content of config/config.php</summary>

```
{
    "version": "12.0.3.3",
    "installed": true,
    "maintenance": false,
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "theme": "",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "***REMOVED SENSITIVE VALUE***",
        "***REMOVED SENSITIVE VALUE***",
    ],
    "datadirectory": "\/var\/www\/cloud\/data",
    "memcache.local": "\\OC\\Memcache\\Redis",
    "filelocking.enabled": "true",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "localhost",
        "port": 0,
        "timeout": 0
    },
    "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
    "forcessl": true,
    "appstore.experimental.enabled": false,
    "has_internet_connection": true,
    "check_for_working_webdav": true,
    "check_for_working_htaccess": true,
    "enable_previews": true,
    "updatechecker": true,
    "loglevel": 0,
    "trashbin_retention_obligation": "auto",
    "dbtype": "mysql",
    "dbname": "owncloud",
    "dbhost": "localhost",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "mail_from_address": "cloud",
    "mail_smtpmode": "smtp",
    "mail_smtpauth": 1,
    "mail_smtphost": "smtp.strato.de",
    "mail_smtpsecure": "ssl",
    "mail_smtpport": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauthtype": "LOGIN",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "updater.release.channel": "stable"
}
```
</details>

### Client configuration

**Browser:** Mozilla/5.0 (Windows NT 6.1; WOW64; rv:56.0) Gecko/20100101 Firefox/56.0

**Operating system:** Windows 7

### Logs

<details>
        <summary>Web server error log</summary>

No corresponding entries in logfile

</details>

<details>
        <summary>Nextcloud log (data/nextcloud.log)</summary>

No corresponding entries in logfile

</details>

<details>
        <summary>Browser log</summary>

No corresponding entries in logfile

</details>

![unbenannt](https://user-images.githubusercontent.com/6290159/31316385-613b534e-ac2c-11e7-88c6-7bc1e3ff0196.JPG)

**Comment by skjnldsv** [comment]
Please reload your cache!

**Comment by skjnldsv** [comment]
Duplicate #388

**Comment by dajusc** [comment]
Sorry for the dublicate. I was overlooking #388 because I only searched for open issues.

Clearing the cache worked, thank you! :)
