### ISSUE TITLE
Search busted in contact group search

### ISSUE THREAD

**Issue by botsarenthuman** [nextcloud/contacts#3926]
### Steps to reproduce

Go to 'Contact groups'
Create a new contact group
Go to add user to contact group
Search doesn't work
See error

### Expected behavior

Typing in a user name should show users I can add

### Actual behavior

Nothing happens when searching

### Web server

None

### Database engine version

None

### PHP engine version

None

### Updated from an older installed version or fresh install

None

### Web server error log

```Text
TypeError: undefined is not a constructor (evaluating 'new OCA.Search(this.search,this.resetSearch)')
```

**Comment by botsarenthuman** [comment]
```
TypeError: undefined is not a constructor (evaluating 'new OCA.Search(this.search,this.resetSearch)')
mounted — Contacts.vue:238
Hn — vue.esm.js:3753
_n — vue.esm.js:3253
insert — vue.esm.js:4944
k — vue.esm.js:6975
(anonymous function) — vue.esm.js:7189
(anonymous function) — vue.esm.js:2986
r — vue.esm.js:3096
(anonymous function) — vue.esm.js:4182
e — vue.esm.js:4172
(anonymous function) — vue.esm.js:3113
(anonymous function) — vue.esm.js:4742
sa — vue.esm.js:5793
(anonymous function) — main.js:78
(anonymous function) — main.js:83
Global Code — main.js:83

```

**Comment by fandong1993** [comment]
I found that only contacts created by app contact could be searched. The users contact from the nectcloud users could not be added.

**Comment by botsarenthuman** [comment]
There is no search performed, no network request. I think it's b/c of that JS error

Ah looks like this was dropped recently... https://github.com/nextcloud/contacts/commit/24b9bb264887e7db55e2ba94081353990c6b384e

**Comment by fandong1993** [comment]
> There is no search performed, no network request. I think it's b/c of that JS error
> 
> Ah looks like this was dropped recently... [24b9bb2](https://github.com/nextcloud/contacts/commit/24b9bb264887e7db55e2ba94081353990c6b384e)

Hi, there, 
   The problem I mentioned above "The users contact from the nextcloud users could not be added. " is as designed or a bug?

**Comment by botsarenthuman** [comment]
Not related to this bug

**Comment by fandong1993** [comment]
So is it another bug? or just as designed?

**Comment by botsarenthuman** [comment]
This is a new bug

**Comment by botsarenthuman** [comment]
Nevermind I added contacts to the "Contacts" address book and it worked. They were in the "Accounts" address book and not being searched.
