### ISSUE TITLE
Ampersand Display Error (&amp;)

### ISSUE THREAD

**Issue by aquaritus** [nextcloud/contacts#3948]
### Describe the bug

When using the ampersand type "&", the apps shows "&amp;" after saving the contact.
The error shows up consistently over every contact that includes one ampersand.
While the contact is ot saved the ampersand is shown correct. After saving the display error occurs.
![Correct_ed
![Display_error_after_saved](https://github.com/nextcloud/contacts/assets/1929316/6dd4a9a2-bd68-409d-a3a0-b3216ba00307)
iting](https://github.com/nextcloud/contacts/assets/1929316/12ea4944-3342-4e6b-902d-0cd85e4ac8ea)

### Steps to reproduce

1. Go to contacts app
2. Click on create new contact
3. Enter a company name for example that includes an ampersand.
4. Save the contact.
5. See error

### Expected behavior

The ampersand symbol should show up correcty as "&".

### Actual behavior

After saving the contact, the ampersand symbol is shown as "&amp;"

### Contact version

4.6.3

### Operating system

Linux 5.15.0-107-generic x86_6

### PHP engine version

Other

### Web server

Other

### Database

MySQL

### Additional info

PHP Version 8.2.14
Webserver: Managed Nextcloud from IONOS

**Comment by hamza221** [comment]
>The ampersand symbol should show up correcty as "&" 

Vs 

>After saving the contact, the ampersand symbol is shown as "&"

I'm not sure I understand the Bug, what's the incorrect representation ?

**Comment by aquaritus** [comment]
When you enter the data an hit save, it is shown correctly. But only as long as the page is open. If you open the entry later, the ampersand is shown incorrectly. I hope this makes it a little bit clearer.

**Comment by hamza221** [comment]
Can you maybe provide a screenshot

**Comment by aquaritus** [comment]
![Screenshot 2024-07-05_00](https://github.com/nextcloud/contacts/assets/1929316/fc86be43-6ebd-4b93-8906-9d6ed31bb900)
![Screenshot 2024-07-05_01](https://github.com/nextcloud/contacts/assets/1929316/38e5601d-a839-4310-ab8d-7f837c51f84e)

**Comment by hamza221** [comment]
I can't reproduce what version of contacts are you using, `4.6.3` doesn't exist

**Comment by aquaritus** [comment]
I justed checked and it is 5.5.1

**Comment by nextcloud-command** [comment]
Hi there! It looks like this issue hasn’t seen much activity for a while and might need a bit more information to move forward. If we don’t hear back soon, we may close it to keep things organized. Thanks again for your contributions – we really appreciate it!

**Comment by nextcloud-command** [comment]
Hi there! It looks like this issue hasn’t seen much activity for a while and might need a bit more information to move forward. If we don’t hear back soon, we may close it to keep things organized. Thanks again for your contributions – we really appreciate it!
