### ISSUE TITLE
nginx restart needed after upgrade to app version 2.0

### ISSUE THREAD

**Issue by crbble** [nextcloud/contacts#396]
This is a hint, maybe there is an explanation, maybe not.

### Setup
Debian 8, Nginx 1.6.2, php-fpm with PHP 7.1 (nextcloud 12.0.3 docker container)

### Behaviour
1. Upgrade app to 2.0 either via web or command line
2. Open contacts 
3. List is empty, spinner is spinning forever.
5. Login/Logout does not help
4. No error on nextcloud.log or php-fpm log

### Expected 
- Contacts should show up or error message should be shown

### Solution
nginx (and php-fpm?) need to be restarted, app works then without problems. This behaviour is unexpected.

**Comment by irgendwie** [comment]
Out of curiosity, did you try clearing your browser cache beforehand?

**Comment by crbble** [comment]
I did reload the contacts page with Ctrl+F5 in Firefox, maybe some other cache was not refreshed.

**Comment by irgendwie** [comment]
Ctrl+F5 doesn't clear the cache but does force a simple refresh. Therefore it still could have been a caching issue. Anyway, thanks for reporting! I will keep this in mind for future potential issue solving.
