### ISSUE TITLE
Privacy issue: users can see members and their details even if they are not member of their group

### ISSUE THREAD

**Issue by arnowelzel** [nextcloud/contacts#3964]
### Describe the bug

When I create a user and assign the user to a specific group, the user can see all other users as well.

- there is group A with users 1, 2, 3, 4
- there is group B with users 5, 6, 7

User 1 can see also user 5, 6, 7 and user 6 and also see user 1,2, 3, 4.

I am not sure when this started, but in older versions this was not the case and I would see this as a security incident.

### Steps to reproduce

1. Create a user group "A" and one user "One" which is only member in this group
2. Create a user group "B" and a second user "Two" which is only member in this group
3. Login as user "One" and open contacts - you can see user "B" eventhough you are not member of that group

### Expected behavior

A user can see only the users of the groups in which he is member. Groups in which a user is not a member must never be displayed and it must not be possible to obtain any details about them in any other way.

### Actual behavior

A user can see all other users of the Nextcloud instance, regardless which groups he belongs to.

### Contact version

6.0.0

### Operating system

Ubuntu Linux 22.04

### PHP engine version

Other

### Web server

Apache (supported)

### Database

MySQL

### Additional info

PHP engine is version 8.3. Please update your "PHP engine version" list since 8.2 and 8.3 are the current supported versions and 8.1 is already in security maintenance mode only!

**Comment by hamza221** [comment]
It actually works but it has to be enabled https://docs.nextcloud.com/server/stable/admin_manual/groupware/contacts.html 
To enable it 
1. Navigate to admin settings 
2. Sharing 
3. Privacy settings for sharing 
4. Allow account name autocompletion to users within the same groups and limit system address books to users in the same groups

or 
4. disable  Allow account name autocompletion in share dialog and allow access to the system address book

Depending on your use case

**Comment by arnowelzel** [comment]
Well - this setting will effectively disable all accounts. So I can not share with anyone after that since I don't see any account at all, even not those who are in the same group as my account. Is this the expected behaviour?

**Comment by arnowelzel** [comment]
So the real solution I expected is to have the system address book only containing users within the same groups of the logged in user - why is this not planned even as an option?

**Comment by hamza221** [comment]
> Well - this setting will effectively disable all accounts. So I can not share with anyone after that since I don't see any account at all, even not those who are in the same group as my account. Is this the expected behaviour?

The expected behaviour is that it shows only users from within the same group, If it doesn't work that way please open another bug issue, With log entries.

**Comment by hamza221** [comment]
> So the real solution I expected is to have the system address book only containing users within the same groups of the logged in user - why is this not planned even as an option?

So whenever a group is created, a new adressbook is generated ?

**Comment by arnowelzel** [comment]
No, it works now. I confused the setting "Allow username autocompletion in share dialog and allow access to the system address book" with "Allow account name autocompletion to users within the same groups and limit system address books to users in the same groups".

With these settings it works as expected - users will only see other users withing the same groups:

![grafik](https://github.com/nextcloud/contacts/assets/6613614/1a770a6f-b3f0-4e71-b3e8-83f501290d0b)
