### ISSUE TITLE
Warning : Contact could not be saved

### ISSUE THREAD

**Issue by linuxpete** [nextcloud/contacts#397]
### Steps to reproduce
1.  Go to a contact / make new contact (see picture)
2. Add a field (eg mail/phone) 
3. Edit the field
4. Go to next field

### Expected behaviour
App will update information on server

### Actual behaviour
1. App shows warning "Contact could not be saved" (see picture)
2. The warning is not always given and sometimes several times, when quick updating several fields. 
3. In the end the information seems to flow to the server but this is not sure.

The information is sometimes saved, sometimes not saved it seems to be a time/timing error and I see this  behaviour since the last update of the app to V2.0.1

![contactcouldnotbesaved](https://user-images.githubusercontent.com/7695965/31512375-fd16ba72-af8a-11e7-93a7-bef7c32beb14.png)

### General server configuration

**Operating system:** Linux mo 4.9.35-v7+ #1014 SMP Fri Jun 30 14:47:43 BST 2017 armv7l

**Web server:** nginx/1.6.2 (fpm-fcgi)

**Database:** mysql 5.5.57

**PHP version:** 5.6.30-0+deb8u1
<details>
        <summary>PHP-modules loaded</summary>

```
 - Core
 - date
 - ereg
 - libxml
 - openssl
 - pcre
 - zlib
 - bcmath
 - bz2
 - calendar
 - ctype
 - dba
 - dom
 - hash
 - fileinfo
 - filter
 - ftp
 - gettext
 - SPL
 - iconv
 - mbstring
 - session
 - posix
 - Reflection
 - standard
 - shmop
 - SimpleXML
 - soap
 - sockets
 - Phar
 - exif
 - sysvmsg
 - sysvsem
 - sysvshm
 - tokenizer
 - wddx
 - xml
 - xmlreader
 - xmlwriter
 - zip
 - cgi-fcgi
 - PDO
 - apcu
 - curl
 - gd
 - json
 - mcrypt
 - memcache
 - memcached
 - mysql
 - mysqli
 - pdo_mysql
 - pdo_sqlite
 - readline
 - sqlite3
 - mhash
 - apc
 - Zend OPcache
```
</details>

### Nextcloud configuration

**Nextcloud version:** 12.0.3 - 12.0.3.3

**Updated from an older Nextcloud/ownCloud or fresh install:** YOUR ANSWER HERE

**Where did you install Nextcloud from:**  YOUR ANSWER HERE

**Are you using external storage, if yes which one:** Array
(
    [0] => \OC\Files\Storage\Local
    [1] => \OCA\Files_External\Lib\Storage\FTP
    [2] => \OC\Files\Storage\DAV
    [3] => \OCA\Files_External\Lib\Storage\OwnCloud
    [4] => \OCA\Files_External\Lib\Storage\SFTP
    [5] => \OCA\Files_External\Lib\Storage\AmazonS3
    [6] => \OCA\Files_External\Lib\Storage\Dropbox
    [7] => \OCA\Files_External\Lib\Storage\Google
    [8] => \OCA\Files_External\Lib\Storage\Swift
    [9] => \OCA\Files_External\Lib\Storage\SFTP
    [10] => \OCA\Files_External\Lib\Storage\SMB
    [11] => \OCA\Files_External\Lib\Storage\SMB
)

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** YOUR ANSWER HERE (LDAP/ActiveDirectory/Webdav/...)

<details>
        <summary>Signing status</summary>

```
[]
```
</details>

<details>
        <summary>Enabled apps</summary>

```
 - activity: 2.5.2
 - admin_audit: 1.2.0
 - apporder: 0.4.0
 - audioplayer: 2.1.0
 - bookmarks: 0.10.1
 - calendar: 1.5.5
 - checksum: 0.3.5
 - comments: 1.2.0
 - contacts: 2.0.1
 - dav: 1.3.0
 - deck: 0.2.4
 - encryption: 1.6.0
 - federatedfilesharing: 1.2.0
 - federation: 1.2.0
 - files: 1.7.2
 - files_automatedtagging: 1.2.2
 - files_external: 1.3.0
 - files_opds: 0.8.2
 - files_pdfviewer: 1.1.1
 - files_reader: 1.0.4
 - files_sharing: 1.4.0
 - files_texteditor: 2.4.1
 - files_trashbin: 1.2.0
 - files_versions: 1.5.0
 - files_videoplayer: 1.1.0
 - firstrunwizard: 2.1
 - gallery: 17.0.0
 - gpxedit: 0.0.7
 - gpxmotion: 0.0.5
 - gpxpod: 2.2.0
 - issuetemplate: 0.2.2
 - logreader: 2.0.0
 - lookup_server_connector: 1.0.0
 - music: 0.5.2
 - news: 11.0.5
 - nextcloud_announcements: 1.1
 - notes: 2.3.1
 - notifications: 2.0.0
 - oauth2: 1.0.5
 - ownpad: 0.5.10
 - password_policy: 1.2.2
 - previewgenerator: 1.0.7
 - provisioning_api: 1.2.0
 - qownnotesapi: 17.5.0
 - rainloop: 5.0.3
 - serverinfo: 1.2.0
 - sharebymail: 1.2.0
 - spreed: 2.0.1
 - spreedme: 0.3.11
 - survey_client: 1.0.0
 - systemtags: 1.2.0
 - tasks: 0.9.5
 - theming: 1.3.0
 - twofactor_backupcodes: 1.1.1
 - updatenotification: 1.2.0
 - workflowengine: 1.2.0
```
</details>

<details>
        <summary>Disabled apps</summary>

```
 - user_external
 - user_ldap
```
</details>

<details>
        <summary>Content of config/config.php</summary>

```
{
    "instanceid": "cccccc",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "localhost",
        "oc.linuxpete.nl"
    ],
    "datadirectory": "\/mnt\/owncloud\/owncloud",
    "overwrite.cli.url": "oc.ddddddd.nl",
    "dbtype": "mysql",
    "version": "12.0.3.3",
    "logtimezone": "UTC",
    "installed": true,
    "memcache.local": "\\OC\\Memcache\\APCu",
    "loglevel": 0,
    "defaultapp": "apporder",
    "knowledgebaseenabled": "true",
    "custom_csp_policy": "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline' data: blob:; frame-src *; img-src *; font-src 'self' data: blob:; media-src *",
    "maintenance": false,
    "dbname": "ocdatabase",
    "dbhost": "127.0.0.1",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "theme": "",
    "data-fingerprint": "ab51ae68f88b0d5df560447d24ce885f",
    "mail_from_address": "oc",
    "mail_smtpmode": "smtp",
    "mail_domain": "ddddddd.nl",
    "mail_smtpauthtype": "LOGIN",
    "mail_smtphost": "mail.dddddd.nl",
    "mail_smtpauth": 1,
    "mail_smtpport": "465",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpsecure": "ssl",
    "enabledPreviewProviders": [
        "OC\\Preview\\Image",
        "OC\\Preview\\MP3",
        "OC\\Preview\\TXT",
        "OC\\Preview\\MarkDown",
        "OC\\Preview\\Epub",
        "OC\\Preview\\PDF",
        "OC\\Preview\\OpenDocument",
        "OC\\Preview\\StarOffice",
        "OC\\Preview\\MSOfficeDoc",
        "OC\\Preview\\MSOffice2003",
        "OC\\Preview\\MSOffice2007",
        "OC\\Preview\\FB2"
    ],
    "mysql.utf8mb4": true
}
```
</details>

### Client configuration

**Browser:** Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0

**Operating system:** Ubuntu 14.04

### Logs

<details>
        <summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

<details>
        <summary>Nextcloud log (data/nextcloud.log)</summary>

```
Insert your Nextcloud log here
```
</details>

<details>
        <summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**

**Operating system:**

**CardDAV-clients:**

#### Web server error log
``
1.1.1.1 - - [12/Oct/2017:20:02:06 +0200] "REPORT /remote.php/dav/addressbooks/users/pieter/Adressen/ HTTP/1.1" 207 2272709 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0"
1.1.1.1 - - [12/Oct/2017:20:03:30 +0200] "REPORT /remote.php/dav/addressbooks/users/pieter/Adressen/ HTTP/1.1" 207 124604 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0"
1.1.1.1 - - [12/Oct/2017:20:03:34 +0200] "REPORT /remote.php/dav/addressbooks/users/pieter/Adressen/ HTTP/1.1" 207 864 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0"
1.1.1.1 - - [12/Oct/2017:20:04:16 +0200] "PUT /remote.php/dav/addressbooks/users/pieter/Adressen/2e6ed539-561f-4a0c-8a30-4a14eeb6ebad.vcf HTTP/1.1" 204 0 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0"
1.1.1.1 - - [12/Oct/2017:20:04:18 +0200] "PUT /remote.php/dav/addressbooks/users/pieter/Adressen/2e6ed539-561f-4a0c-8a30-4a14eeb6ebad.vcf HTTP/1.1" 204 0 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0"
1.1.1.1 - - [12/Oct/2017:20:04:19 +0200] "PUT /remote.php/dav/addressbooks/users/pieter/Adressen/2e6ed539-561f-4a0c-8a30-4a14eeb6ebad.vcf HTTP/1.1" 412 324 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0"
1.1.1.1 - - [12/Oct/2017:20:04:21 +0200] "PUT /remote.php/dav/addressbooks/users/pieter/Adressen/2e6ed539-561f-4a0c-8a30-4a14eeb6ebad.vcf HTTP/1.1" 412 324 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0"
1.1.1.1 - - [12/Oct/2017:20:05:27 +0200] "GET /remote.php/dav/addressbooks HTTP/1.1" 200 125 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0"
1.1.1.1 - - [12/Oct/2017:20:05:32 +0200] "PROPFIND /remote.php/dav/addressbooks HTTP/1.1" 207 568 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0"
1.1.1.1 - - [12/Oct/2017:20:05:43 +0200] "PROPFIND /remote.php/dav/addressbooks/users/pieter/ HTTP/1.1" 207 1302 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0"
1.1.1.1 - - [12/Oct/2017:20:05:53 +0200] "PROPFIND /remote.php/dav/addressbooks/users/pieter/Adressen/ HTTP/1.1" 207 414879 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0"
1.1.1.1 - - [12/Oct/2017:20:05:55 +0200] "PROPFIND /remote.php/dav/addressbooks/users/pieter/ HTTP/1.1" 207 491 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0"
1.1.1.1 - - [12/Oct/2017:20:06:38 +0200] "REPORT /remote.php/dav/addressbooks/users/pieter/Adressen/ HTTP/1.1" 207 240836 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0"
1.1.1.1 - - [12/Oct/2017:20:06:43 +0200] "REPORT /remote.php/dav/addressbooks/users/pieter/Adressen/ HTTP/1.1" 207 124604 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0"
1.1.1.1 - - [12/Oct/2017:20:06:45 +0200] "REPORT /remote.php/dav/addressbooks/users/pieter/Adressen/ HTTP/1.1" 207 2274243 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0"
1.1.1.1 - - [12/Oct/2017:20:07:07 +0200] "REPORT /remote.php/dav/addressbooks/users/pieter/Adressen/ HTTP/1.1" 207 124604 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0"
1.1.1.1 - - [12/Oct/2017:20:07:10 +0200] "REPORT /remote.php/dav/addressbooks/users/pieter/Adressen/ HTTP/1.1" 207 858 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0"
1.1.1.1 - - [12/Oct/2017:20:07:22 +0200] "PUT /remote.php/dav/addressbooks/users/pieter/Adressen/2e6ed539-561f-4a0c-8a30-4a14eeb6ebad.vcf HTTP/1.1" 204 0 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0"
1.1.1.1 - - [12/Oct/2017:20:07:44 +0200] "PUT /remote.php/dav/addressbooks/users/pieter/Adressen/b954a580-10f1-49a1-8f9d-d75348c98280.vcf HTTP/1.1" 201 0 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0"
1.1.1.1 - - [12/Oct/2017:20:07:48 +0200] "REPORT /remote.php/dav/addressbooks/users/pieter/Adressen/ HTTP/1.1" 207 735 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0"
1.1.1.1 - - [12/Oct/2017:20:08:11 +0200] "PUT /remote.php/dav/addressbooks/users/pieter/Adressen/b954a580-10f1-49a1-8f9d-d75348c98280.vcf HTTP/1.1" 204 0 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0"
1.1.1.1 - - [12/Oct/2017:20:08:11 +0200] "PUT /remote.php/dav/addressbooks/users/pieter/Adressen/b954a580-10f1-49a1-8f9d-d75348c98280.vcf HTTP/1.1" 204 0 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0"
1.1.1.1 - - [12/Oct/2017:20:08:13 +0200] "PUT /remote.php/dav/addressbooks/users/pieter/Adressen/b954a580-10f1-49a1-8f9d-d75348c98280.vcf HTTP/1.1" 204 0 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0"
1.1.1.1 - - [12/Oct/2017:20:08:32 +0200] "PUT /remote.php/dav/addressbooks/users/pieter/Adressen/b954a580-10f1-49a1-8f9d-d75348c98280.vcf HTTP/1.1" 204 0 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0"
1.1.1.1 - - [12/Oct/2017:20:08:34 +0200] "PUT /remote.php/dav/addressbooks/users/pieter/Adressen/b954a580-10f1-49a1-8f9d-d75348c98280.vcf HTTP/1.1" 204 0 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0"
1.1.1.1 - - [12/Oct/2017:20:08:53 +0200] "PUT /remote.php/dav/addressbooks/users/pieter/Adressen/b954a580-10f1-49a1-8f9d-d75348c98280.vcf HTTP/1.1" 204 0 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0"
1.1.1.1 - - [12/Oct/2017:20:08:53 +0200] "PUT /remote.php/dav/addressbooks/users/pieter/Adressen/b954a580-10f1-49a1-8f9d-d75348c98280.vcf HTTP/1.1" 412 324 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0"

```

#### Nextcloud log (data/nextcloud.log)
```
{"reqId":"vgYXIUFTE1iY4aDNtIc6","level":0,"time":"2017-10-12T18:29:35+00:00","remoteAddr":"1.1.1.1","user":"ddd","app":"webdav","method":"PUT","url":"\/remote.php\/dav\/addressbooks\/users\/pieter\/Adressen\/b954a580-10f1-49a1-8f9d-d75348c98280.vcf","message":"Exception: {\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\PreconditionFailed\",\"Message\":\"An If-Match header was specified, but none of the specified the ETags matched.\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(474): Sabre\\\\DAV\\\\Server->checkPreconditions(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#2 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Server.php(258): Sabre\\\\DAV\\\\Server->exec()\\n#3 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(33): OCA\\\\DAV\\\\Server->exec()\\n#4 \\\/var\\\/www\\\/owncloud\\\/remote.php(162): require_once('\\\/var\\\/www\\\/ownclo...')\\n#5 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php\",\"Line\":1338}","userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:56.0) Gecko\/20100101 Firefox\/56.0","version":"12.0.3.3"}
{"reqId":"UyDDoYR7HmUFR643efIt","level":0,"time":"2017-10-12T18:30:13+00:00","remoteAddr":"1.1.1.1","user":"pieter","app":"webdav","method":"PUT","url":"\/remote.php\/dav\/addressbooks\/users\/pieter\/Adressen\/b954a580-10f1-49a1-8f9d-d75348c98280.vcf","message":"Exception: {\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\PreconditionFailed\",\"Message\":\"An If-Match header was specified, but none of the specified the ETags matched.\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(474): Sabre\\\\DAV\\\\Server->checkPreconditions(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#2 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Server.php(258): Sabre\\\\DAV\\\\Server->exec()\\n#3 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(33): OCA\\\\DAV\\\\Server->exec()\\n#4 \\\/var\\\/www\\\/owncloud\\\/remote.php(162): require_once('\\\/var\\\/www\\\/ownclo...')\\n#5 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php\",\"Line\":1338}","userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:56.0) Gecko\/20100101 Firefox\/56.0","version":"12.0.3.3"}
{"reqId":"prE2jBis9CSV6PLpMqdW","level":0,"time":"2017-10-12T18:30:14+00:00","remoteAddr":"1.1.1.1","user":"xxx","app":"webdav","method":"PUT","url":"\/remote.php\/dav\/addressbooks\/users\/pieter\/Adressen\/b954a580-10f1-49a1-8f9d-d75348c98280.vcf","message":"Exception: {\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\PreconditionFailed\",\"Message\":\"An If-Match header was specified, but none of the specified the ETags matched.\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(474): Sabre\\\\DAV\\\\Server->checkPreconditions(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#2 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Server.php(258): Sabre\\\\DAV\\\\Server->exec()\\n#3 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(33): OCA\\\\DAV\\\\Server->exec()\\n#4 \\\/var\\\/www\\\/owncloud\\\/remote.php(162): require_once('\\\/var\\\/www\\\/ownclo...')\\n#5 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php\",\"Line\":1338}","userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:56.0) Gecko\/20100101 Firefox\/56.0","version":"12.0.3.3"}

```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by skjnldsv** [comment]
Please insert your browser log. :)

**Comment by linuxpete** [comment]
OK, I've given it a Try. using FF couldn't make up how to export so a few screenshots

After opening the page ánd filling some fields. Noting is happing after loading

![contactcouldnotbesaved_browserlog](https://user-images.githubusercontent.com/7695965/31515704-793f688c-af96-11e7-8763-514036c8313b.png)

I Added "Net" to the mix and the yellow/orange lines appear when the warning appears.
![contactcouldnotbesaved_browserlog_1](https://user-images.githubusercontent.com/7695965/31515706-7b8fb7d6-af96-11e7-9a1a-7233654b7e41.png)

Below you see the network activity, you see "notifications" when the warning sign appears

![contactcouldnotbesaved_browserlog_2](https://user-images.githubusercontent.com/7695965/31515986-6357f81c-af97-11e7-920b-2316be043148.png)

I hope this suffice?

**Comment by skjnldsv** [comment]
I'd like the response from the 412 http error request please

**Comment by skjnldsv** [comment]
@linuxpete ?

**Comment by WilliamMiceli** [comment]
My instance is also having to be what looks like the same (or very similar issue).
NextCloud is at the latest version, and the Contacts app is as well.
I've noticed that I can make exactly 1 change to a contact, and all proceeding changes are met with the "Contact could not be saved" message.
After that, I have to reload the app in my browser (just by clicking the Contacts icon in the top left), and then I can make 1 more change.

Let me know where to get the response from the http error from, and I'll put it up here.
Using Firefox, if it matters.

Thank you!

**Comment by skjnldsv** [comment]
@WilliamMiceli have you checked #257

**Comment by linuxpete** [comment]
hi @skjnldsv , excuses, I was off-line for some time. I will try to catch the 412 this week.

As far as I can remember I didn't have this warning with the previous version of the app (2.0.0). 

However I upgraded the app soon after the upgrade of Nextcloud from 12.0.2. to 12.0.3 in which time I perhaps didn't use the contacts app and "just upgraded".

**Comment by linuxpete** [comment]
Another comment: 
However the app gives the warning the changes seem to happen anyway but you have to give the app enough time to store the changes between the changing of the fields, eg:

1. change address field and switcht to postalcode
2. wait 10seconds
3. change postalcode and switch to city
4. wait 10seconds
5. make another change 
6. wait 10seconds
etc, etc.

The app then gives rarely the mentioned warning and stores things correctly. When the warning appears it could be so that values are not stored or not stored correctly.

**Comment by linuxpete** [comment]
Hi John,

I'm back already :-) , this can shed some light on the problem.

First the screen of the address I have been changing. Remind the field City !!!
![nc_app_contacts_github_397_01](https://user-images.githubusercontent.com/7695965/31864860-60aff0c6-b765-11e7-90c3-e43bb319a32f.png)

Second the requested payload where you can see the requested changes
![nc_app_contacts_github_397_02](https://user-images.githubusercontent.com/7695965/31864879-9527e17e-b765-11e7-9b06-06dd91704d3f.png)

It's about this 412:
![nc_app_contacts_github_397_09](https://user-images.githubusercontent.com/7695965/31864890-cdf5c8cc-b765-11e7-86c1-8f20dd07ec0a.png)

This seems to be the 412 itself:
![nc_app_contacts_github_397_03](https://user-images.githubusercontent.com/7695965/31864897-e003ef3a-b765-11e7-93a5-11303ca2c903.png)

and this the timing of it:
![nc_app_contacts_github_397_04](https://user-images.githubusercontent.com/7695965/31864898-e4be411a-b765-11e7-8529-fff2ad9764ca.png)

the stacktrace:
![nc_app_contacts_github_397_05](https://user-images.githubusercontent.com/7695965/31864904-f731fbac-b765-11e7-991c-d2de5276ec1f.png)

The response headers:
![nc_app_contacts_github_397_06](https://user-images.githubusercontent.com/7695965/31864906-015599b8-b766-11e7-8eb4-722219c56a65.png)

and the "raw" response headers:
![nc_app_contacts_github_397_07](https://user-images.githubusercontent.com/7695965/31864911-0e7cddcc-b766-11e7-9dbe-56ef8129734e.png)

The resulting changes, It seems that the city ("stad")  is left out:

![nc_app_contacts_github_397_08](https://user-images.githubusercontent.com/7695965/31864916-1f71dfa6-b766-11e7-8052-2dce48b26105.png)

This is the history of requests (not sequential)!:
![nc_app_contacts_github_397_13](https://user-images.githubusercontent.com/7695965/31864954-ff881e16-b766-11e7-886e-1ac1496c7f43.png)
![nc_app_contacts_github_397_14a](https://user-images.githubusercontent.com/7695965/31864955-ffa5e338-b766-11e7-9e00-b7e9ea86a95f.png)
![nc_app_contacts_github_397_12](https://user-images.githubusercontent.com/7695965/31864956-ffc1a000-b766-11e7-8181-bd38ba387fab.png)
![nc_app_contacts_github_397_11](https://user-images.githubusercontent.com/7695965/31864957-ffdd4328-b766-11e7-8e4d-837bdfb50b7c.png)
![nc_app_contacts_github_397_10](https://user-images.githubusercontent.com/7695965/31864958-fff7b0dc-b766-11e7-8522-9955424201b2.png)

**Comment by skjnldsv** [comment]
Hi @linuxpete!
Thanks for taking the time to elaborate on this!! :)
Could you please post the screenshot of the first (successful? ) requests header? And its response's header too?
Is the first request always this long?

It seems we have a race condition here! :(

**Comment by WilliamMiceli** [comment]
Sorry for the delay!
Glad @linuxpete came back :D 
Unfortunately #257 didn't fix it in my case, but I'm going to be resetting everything up anyway, so best of luck to you both!

**Comment by linuxpete** [comment]
Hi @skjnldsv 

Yesterday I made some screenshots of the headers and the payload. I also send the corresponding mysql logfile with this post. I send the screenshots of one vcf which ranges from the first line (207 REPORT) until the the second 200 (GET). The second 207 REPORT is the next vcf

**First all the headers**

![screenshot from 2017-10-24 19 26 28](https://user-images.githubusercontent.com/7695965/31982555-aab4610c-b959-11e7-83b9-d2cab4ca352e.png)
![screenshot from 2017-10-24 19 26 37](https://user-images.githubusercontent.com/7695965/31982556-aad4878e-b959-11e7-8227-7f03445cd1fa.png)
![screenshot from 2017-10-24 19 26 46](https://user-images.githubusercontent.com/7695965/31982557-aaf06c38-b959-11e7-826e-87f388ad9890.png)
![screenshot from 2017-10-24 19 27 01](https://user-images.githubusercontent.com/7695965/31982558-ab4202b4-b959-11e7-99b8-1a9034241fd7.png)
![screenshot from 2017-10-24 19 27 12](https://user-images.githubusercontent.com/7695965/31982560-ab6c9312-b959-11e7-8574-68e8d357b4c0.png)
![screenshot from 2017-10-24 19 27 20](https://user-images.githubusercontent.com/7695965/31982562-ab8c2470-b959-11e7-9a18-61ab5b15292e.png)
![screenshot from 2017-10-24 19 27 28](https://user-images.githubusercontent.com/7695965/31982563-aba5e982-b959-11e7-87d2-cc0bd0aeee30.png)
![screenshot from 2017-10-24 19 27 35](https://user-images.githubusercontent.com/7695965/31982564-abe92c6a-b959-11e7-91f0-2eb1026cdb67.png)


**Then all the params**

![screenshot from 2017-10-24 19 28 03](https://user-images.githubusercontent.com/7695965/31982605-dc74fecc-b959-11e7-96d3-e805195a5fb8.png)
![screenshot from 2017-10-24 19 28 16](https://user-images.githubusercontent.com/7695965/31982606-dc90ee0c-b959-11e7-9b5e-ee519fc8f215.png)
![screenshot from 2017-10-24 19 28 24](https://user-images.githubusercontent.com/7695965/31982607-dcae8304-b959-11e7-9bec-4a5fed833c4d.png)
![screenshot from 2017-10-24 19 28 34](https://user-images.githubusercontent.com/7695965/31982608-dcc9d4d8-b959-11e7-9f10-093c4bc66dec.png)
![screenshot from 2017-10-24 19 28 42](https://user-images.githubusercontent.com/7695965/31982609-dce5ca58-b959-11e7-9ea6-ff52d2c9c199.png)
![screenshot from 2017-10-24 19 28 51](https://user-images.githubusercontent.com/7695965/31982610-dd103a72-b959-11e7-9f13-0ba9932b8bf2.png)
![screenshot from 2017-10-24 19 28 58](https://user-images.githubusercontent.com/7695965/31982611-dd36f766-b959-11e7-9261-4d6ff90c2abb.png)
![screenshot from 2017-10-24 19 29 06](https://user-images.githubusercontent.com/7695965/31982612-dd538796-b959-11e7-9aa4-f21bb31f6a0b.png)

**Then the resulting mysql logfile**

[addressbook.log](https://github.com/nextcloud/contacts/files/1413393/addressbook.log)

Hope this helps

**Comment by skjnldsv** [comment]
Thanks a lot @linuxpete 
Could you see this possible fix here: https://github.com/nextcloud/contacts/pull/402?

**Comment by linuxpete** [comment]
see my comments in #402 : test was OK.
