### ISSUE TITLE
Feature requests : optionnal periodic backups contacts into nextcloud user's file

### ISSUE THREAD

**Issue by Zeuh** [nextcloud/contacts#398]
Add options to have : 
- periodic backups of contacts into the user's files app dedicated directory
- option to keep X backups
- restore directly from a backup

**Comment by Henni** [comment]
In my opinion this is out of scope for this app.
But it shouldn't be difficult to implement this in a separate app.
Maybe for this special case a server-side implementation is better.

**Comment by skjnldsv** [comment]
I agree
