### ISSUE TITLE
All releases need to be re-created

### ISSUE THREAD

**Issue by oparoz** [nextcloud/contacts#4]
Automated scripts will fail hard because the releases are missing.

At least the last few should be recreated.

**Comment by MariusBluem** [comment]
What is with them:
https://github.com/nextcloud/contacts/releases 😁

**Comment by oparoz** [comment]
Now compare with this ;) : 
https://github.com/owncloud/contacts/releases

**Comment by MariusBluem** [comment]
I see ... We need to build 👷

**Comment by oparoz** [comment]
Maybe just upload the files from the old repo since they're already signed?

The thing I don't know is if we need a different version depending on the version of NC. If yes, then we should at least 2 releases, one for 9 and one for 10.

**Comment by irgendwie** [comment]
@oparoz the old releases should work for both, 9 and 10.
Any idea how we can easily copy them into this fork?

**Comment by oparoz** [comment]
@irgendwie I would just do this then:

1. Download the last one from oC
1. Edit the last release on here
1. Drag and drop the package
1. Ask @enoch85 to test with his script

If the script picks up the release, then we should be good to go.

**Comment by enoch85** [comment]
Please release 1.5.0.0 as the info.xml says that that is the version. Thanks!

**Comment by irgendwie** [comment]
@enoch85 the idea was to have the current version (working on) on the next version in the master branch. As you're using this for your scripts, I will move back to the old scheme -> updating it shortly before release/packaging.

**Comment by enoch85** [comment]
@irgendwie Thanks!

**Comment by irgendwie** [comment]
We shouldn't need the old releases anymore.

**Comment by enoch85** [comment]
As a side note, I'm using Github API now, and the Nextcloud scripts doesn't rely on info.xml anymore.
