### ISSUE TITLE
Contact photo cannot be uploaded without file extension / No error message

### ISSUE THREAD

**Issue by bpcurse** [nextcloud/contacts#400]
### Steps to reproduce
1. Click on the upload picture button in existing contact
2. Try to upload a picture file **without** file extension (e.g. ".jpg")

### Expected behaviour
Picture file should either be recognized without the extension and be shown after upload or an error message should be presented.

### Actual behaviour
No error message, upload is not working, picture is not shown

NC 12.0.3 / Contacts 2.0.1 / Firefox (Linux)

**Comment by Henni** [comment]
upload should be limited to supported image file types.
This can be done easily via attributes on the input field.
