### ISSUE TITLE
Replace vanilla inputs with `NcInputField`s in contact details

### ISSUE THREAD

**Issue by st3iny** [nextcloud/contacts#4027]
### Is your feature request related to a problem? Please describe.

The contact details form is still using vanilla HTML input fields instead of `NcInputField`s from our shared library.

![grafik](https://github.com/user-attachments/assets/2787156a-7fc8-44cc-9df4-0baf601a8ef8)

### Describe the solution you'd like

Replace all fields (where possible) with `NcInputField`s.

**Comment by GVodyanov** [comment]
Done in https://github.com/nextcloud/contacts/pull/4059
