### ISSUE TITLE
Uneven spacing around avatar in contact list

### ISSUE THREAD

**Issue by st3iny** [nextcloud/contacts#4029]
### Describe the bug

The margin to the left of the avatar is bigger than above and below.

![grafik](https://github.com/user-attachments/assets/b099e713-a9e5-4ee0-a1f7-db04cad53b0e)

### Steps to reproduce

1. Open the app.
2. Look at the contact list.

### Expected behavior

The margins around the avatar should be even in all four directions.

### Actual behavior

The margin to the left is bigger than above and below.

### Contact version

main

**Comment by GVodyanov** [comment]
Imma steal this one too
