### ISSUE TITLE
Multiple contacts with the same name cause wrong highlighting/marking

### ISSUE THREAD

**Issue by j-ed** [nextcloud/contacts#403]
## Expected behavior
If multiple contacts with the same name exists in an address book, it should be possible to select one and get this entry highlighted/marked correctly.

## Current behavior
If multiple contacts with the same name exists in an address bookm the last entry is always highlighted/marked although the first or second entry has been selected. Additionally the displayed record changes every time you click on the first entry and the last entry is still highlighted/marked.

![20171025_nc-same-contact-name](https://user-images.githubusercontent.com/2572764/32013966-0310210c-b9bd-11e7-959c-676cc4e801b5.png)

### Steps to reproduce
1. Open the contacts app and create e.g. three contacts with the same name but different phone numbers.
2. Select the first entry, result: the last one is marked as active.
3. Klick on the first entry multiple times, result: the displayed record changes.

### Example VCARDs
```
BEGIN:VCARD
VERSION:3.0
FN:Anton Test
UID:afd2b8dd-4a23-40a7-8a9a-3663e6c86348
CATEGORIES:Privat
REV:20171025T173242Z
TEL;TYPE=HOME,VOICE:+49 172 11223344
END:VCARD

BEGIN:VCARD
VERSION:3.0
FN:Anton Test
UID:8a196f1a-427f-432b-b68a-079401e028c9
CATEGORIES:Privat
REV:20171025T173246Z
TEL;TYPE=HOME,VOICE:+49 172 22334455
END:VCARD

BEGIN:VCARD
VERSION:3.0
FN:Anton Test
UID:5af7c730-1481-4473-befa-bc223bc05759
CATEGORIES:Privat
REV:20171025T173250Z
TEL;TYPE=HOME,VOICE:+49 172 33445566
END:VCARD
```
#### Server Configuration
OS: Linux 3.16.47
Web server: Apache2 2.4.29
Database: MariaDB 10.0.32
PHP version: 5.6.29
Nextcloud version: 12.0.3
Contacts app version: 2.0.1

#### Client Configuration
Browser: Mozilla Firefox 56.0
Operating system: Windows 7

**Comment by skjnldsv** [comment]
Yep, we need to sort by I'd after the name too! :)
