### ISSUE TITLE
field labels should correctly been interpreted independently in which order they appear

### ISSUE THREAD

**Issue by j-ed** [nextcloud/contacts#404]
## Expected behavior
The contacts app should be able to interpret field labels correctly independently in which order they appear. Wrong entries should automatically be fixed when they're read.

## Current behavior
The contacts app doesn't always interpret field labels correctly. Wrong entries are not corrected and this could cause empty field label to be shown.

### Steps to reproduce
1. Create a contact record which like this one (I don't where it comes from):
```
BEGIN:VCARD
VERSION:3.0
N:Lastname;Firstname;;;
FN:Firstname Lastname
TEL;TYPE=PREF;TYPE=CELL:+49 (157)...
UID:2803603d-aaf4-4738-8dbe...
REV:2014-08-31T16:30:59+00:00
PRODID:-//ownCloud//NONSGML Contacts 0.3.0.17//EN
CATEGORIES:Privat
END:VCARD
```
2. Select the entry and check the field label:
![20171025_nc-contact-without-label](https://user-images.githubusercontent.com/2572764/32014591-c542c03a-b9be-11e7-82b6-c42bde345453.png)

3. Change the field label to a correct value and check the contact record again:
```
BEGIN:VCARD
VERSION:3.0
N:Lastname;Firstname;;;
FN:Firstname Lastname
TEL;TYPE=CELL,PREF;TYPE=CELL:+49 (157)...
UID:2803603d-aaf4-4738-8dbe-b02b...
REV:20171025T153857Z
PRODID:-//ownCloud//NONSGML Contacts 0.3.0.17//EN
CATEGORIES:Privat
END:VCARD
```
Although the field type is now correctly been displayed the **TYPE=** is doppelt in the record.

#### Server Configuration
OS: Linux 3.16.47
Web server: Apache2 2.4.29
Database: MariaDB 10.0.32
PHP version: 5.6.29
Nextcloud version: 12.0.3
Contacts app version: 2.0.1

#### Client Configuration
Browser: Mozilla Firefox 56.0
Operating system: Windows 7

**Comment by Henni** [comment]
Seems like another case where multiple `TYPE` definitions aren't handled well...

Excerpt from the RFC:
>These type parameter values can be specified as a parameter list (e.g., TYPE=text;TYPE=voice) or as a value list (e.g., TYPE="text,voice")

I haven't found any vcard lib which supports both ways (including ours)...
We might have to patch this ourselves, to handle cases like this better.

**Comment by j-ed** [comment]
@Henni Surprisingly the tags are doubled if you change the entry from an **empty** to a **valid** entry. For me it seems that in a first step the different types are merged into on single entry and in a second step the type is set without checking against already existing types.

**Comment by skjnldsv** [comment]
Should be fixed now :)
