### ISSUE TITLE
Browser Support

### ISSUE THREAD

**Issue by Henni** [nextcloud/contacts#414]
I would like to clarify in the README which browser versions we **actively** support.

This doesn't mean that our app only runs on these browser versions. Older versions might still be supported (possibly with a reduced feature set). Also PRs are always welcome to improve support, even for older browsers.

My suggestion would be:
* Latest Firefox ESR (currently FF52, March 6 2018  FF59)
* Chrome, Opera (latest 3 versions) *are there any special enterprise releases?*
* Edge (latest 3 versions)
* Safari (latest version) *is this enough?*
* IE **don't**

Mobile Devices:
same as Desktop: iOS = Safari, Android = Chrome

@nextcloud/contacts @jancborchardt what are your thoughts on this?

**Comment by jancborchardt** [comment]
Ideally we should align that with our server support matrix, oe say something like "same as server except IE". Otherwise every app has separate compatibility and it will be just confusing.

**Comment by skjnldsv** [comment]
Agreed! 👍

**Comment by Henni** [comment]
> Web browser: IE11+, Microsoft Edge, Firefox 14+, Chrome 18+, Safari 7+

https://docs.nextcloud.com/server/12/admin_manual/installation/system_requirements.html#supported-platforms

Both IE11 and Safari (7/8/9) prevent us from using any ES6 features. There would be the option of babel or some other cross-compiler, but in my opinion we as a community project can allow ourselves stricter requirements than the server project.

Also I don't believe that our code currently properly supports either old Safari or IE and I also don't think that it should have any priority to change this.

**Comment by jancborchardt** [comment]
Ok, sounds fine. cc @karlitschek @morrisjobke

Also it might make sense to align this with other community apps like Notes, Calendar @georgehrke, News @BernhardPosselt, Tasks @raimund-schluessler and probably Mail too @ChristophWurst @Gomez.

**Comment by BernhardPosselt** [comment]
I'd just leave that up to the individual developers. Everyone uses different platforms (Mac, Linux, Windows, Android, iOS) and it's hard to test them (especially Safari which requires a Mac). Apart from that I don't really want to do work on Safari and IE related issues in my free time and I don't want to fiddle around with Firefox ESR which would require me to use a VM. 

Choose whatever platform you feel you can/are paid to support.

**Comment by georgehrke** [comment]
There is no official support for Opera at the calendar right now.
Nevertheless we support at least Internet Explorer 11. (and accept patches for 9 and 10, but no one ever sent a patch yet.)

**Comment by Henni** [comment]
@BernhardPosselt I have assumed that Firefox ESR is pretty much just a normal old version of Firefox (at least in regards of web feature support). Is that assumption wrong?

**Comment by BernhardPosselt** [comment]
Right that's why installing it in parallel is sorry shitty :)

**Comment by mathiasconradt** [comment]
@georgehrke IE11 has issues, as reported by one customer today. Ping me for details if you need more info.

Original report: 

> In Internet Explorer 11, no contact information is displayed in the Contacts application. But in all other browsers already (tested in Chrome 69, Firefox 62 and Safari 12).
>  
> As you can see in the screenshot, on the right side you only try to load the information, but nothing else happens. Unfortunately there is no entry in the Nextcloud Log during an access and the webserver log only shows the following:

> „[26/Sep/2018:15:48:37 +0200] 10.247.103.210:80 "REPORT /remote.php/dav/addressbooks/users/firstname.lastname@example.de/default/ HTTP/1.1" 207 1321 "-" "Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.3; WOW64; Trident/7.0; .NET4.0E; .NET4.0C; .NET CLR 3.5.30729; .NET CLR 2.0.50727; .NET CLR 3.0.30729)" "-"”

> 
> Translated with DeepL.com

**Comment by skjnldsv** [comment]
@mathiasconradt Georg is talking about calendar.
Contacts have never fully supported IE from the beginning. :)
