### ISSUE TITLE
headers already sent in Err log

### ISSUE THREAD

**Issue by berlin2123** [nextcloud/contacts#4147]
### Describe the bug

Errors in the logs keep appearing as `headers already sent`.
```
Cannot modify header information - headers already sent by (output started at 
/var/www/html/nextcloud/3rdparty/sabre/http/lib/Sapi.php:130) at 
/var/www/html/nextcloud/3rdparty/sabre/http/lib/Sapi.php#70
```
Seems like the issue is related to this app.

### Steps to reproduce

NC version 29.0.7, Contacts version 6.0.0

just check logs of nextcloud.

### Expected behavior

no this err log

### Actual behavior

this err log keep appearing

### Contact version

6.0.0

### Operating system

rockylinux 9

### PHP engine version

8.2

### Web server

apache

### Database

mariadb

**Comment by kesselb** [comment]
Thanks for your report 👍 

The provided stack trace does not look related to the contacts app.
