### ISSUE TITLE
contacts-index.css blocked due to MIME type (“text/html”) mismatch

### ISSUE THREAD

**Issue by melroy89** [nextcloud/contacts#4148]
### Describe the bug

Incorrect, missing contacts-index.css file when on the files tab when using Nextcloud 30.

```sh
The resource from “https://cloud.melroy.org/apps/contacts/css/contacts-index.css?v=1b4503c0-5” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff). files
```

When I visit t his css file, I got redirect to: https://cloud.melroy.org/apps/contacts/All%20contacts/4af1a2e9-c232-4fd9-8c12-62ff515bed78~default. And it shows me:

```sh
Error: page.tabs[tab.id] is undefined undefined
```

Followed by:  `group css not found`

As well as: 

```
Error: Debounced method called with different contexts.
    d https://cloud.melroy.org/apps/contacts/js/index-BYtwKcsR.chunk.mjs:2
    mounted https://cloud.melroy.org/apps/contacts/js/contacts-main.mjs?v=305544fb-5:3
    qt https://cloud.melroy.org/apps/contacts/js/index-b2_Rf36J.chunk.mjs:2
    It https://cloud.melroy.org/apps/contacts/js/index-b2_Rf36J.chunk.mjs:2
    insert https://cloud.melroy.org/apps/contacts/js/index-b2_Rf36J.chunk.mjs:2
    bt https://cloud.melroy.org/apps/contacts/js/index-b2_Rf36J.chunk.mjs:2
    _l https://cloud.melroy.org/apps/contacts/js/index-b2_Rf36J.chunk.mjs:2
    _update https://cloud.melroy.org/apps/contacts/js/index-b2_Rf36J.chunk.mjs:2
    r https://cloud.melroy.org/apps/contacts/js/index-b2_Rf36J.chunk.mjs:2
    get https://cloud.melroy.org/apps/contacts/js/index-b2_Rf36J.chunk.mjs:2
    run https://cloud.melroy.org/apps/contacts/js/index-b2_Rf36J.chunk.mjs:2
    tf https://cloud.melroy.org/apps/contacts/js/index-b2_Rf36J.chunk.mjs:2
    Kn https://cloud.melroy.org/apps/contacts/js/index-b2_Rf36J.chunk.mjs:2
    hn https://cloud.melroy.org/apps/contacts/js/index-b2_Rf36J.chunk.mjs:2
index-b2_Rf36J.chunk.mjs:2:26700
```

### Steps to reproduce

1. Go to "Files" tab in Nextcloud v30 (Hub 9)
2. Look at the console output
3. See error:

```sh
The resource from “https://cloud.melroy.org/apps/contacts/css/contacts-index.css?v=1b4503c0-5” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff). files
```

### Expected behavior

No errors in the log.

### Actual behavior

Error above.

### Contact version

6.1.0

### Operating system

Ubuntu Server

### PHP engine version

8.3

### Web server

Nginx

### Database

MariaDB

### Additional info

![image](https://github.com/user-attachments/assets/a8559e8c-b3fb-420b-8f11-c642862d16a2)

0 bytes? Response is indeed empty.

![image](https://github.com/user-attachments/assets/b95a3ac4-bd20-4b6e-9491-aacad5dd4202)

But even more JS issues as well.. 
![image](https://github.com/user-attachments/assets/9199d09d-d5ff-4325-8253-6a0635f558d0)

**Comment by meavric** [comment]
Hi,
I have the same problem, and nothing show in contacts page.
Any idea how fix it?

**Comment by melroy89** [comment]
Nope. No workaround possible. They should just fix this issue in their code.
