### ISSUE TITLE
Allow named contact events

### ISSUE THREAD

**Issue by pixelipo** [nextcloud/contacts#417]
### Steps to reproduce
1. Try to add a second `anniversary` to a contact

### Expected behaviour
Have two different anniversary dates for a single contact

### Actual behaviour
Anniversary field is occupied, no new ones can be created.

Google Calendar/Contacts allows adding as many dates to a contact as one wants. There are few default ones (Birthday, Anniversary), but also custom ones can be created. This is especially useful in situations where one might have two anniversaries worth remembering related to a single contact, or when a contact's child (child is not a contact itself) birthday should be remembered...

**Comment by Henni** [comment]
Thanks for the issue.
We can't reuse the vcard property `anniversary` because it is allowed only once in vcards.
Android creates properties like this:
```
X-ANDROID-CUSTOM:vnd.android.cursor.item/contact_event;2017-05-26;1;;;;;;;;;;;;;
```

Anyone able to test which property Apple uses?

**Comment by irgendwie** [comment]
jfr. #223

**Comment by pixelipo** [comment]
I don't think it's a duplicate. The other issue is only proposing one particular solution to this problem...

**Comment by skjnldsv** [comment]
yes this is a duplicate, we have two options, ANDROID-CUSTOM:vnd.android.cursor.item or XABDATE.
Both of them are in #223
