### ISSUE TITLE
Contact detail view: Two column layout cuts input field in half

### ISSUE THREAD

**Issue by mathiasconradt** [nextcloud/contacts#429]
@nextcloud/designers:  I have this on the Nextcloud staff internal NC 12.0.3:

When you have a wide screen and the contact layout breaks into two columns, at the end of the first column, the input field (in my case, the birthday field) gets cut off and continues at the top of the second column.

Happens on Chrome 62.0.3202. as well as Opera 48.0 on Mac OS X.

<img width="523" alt="screen shot 2017-11-04 at 14 02 15 copy" src="https://user-images.githubusercontent.com/295122/32405694-6a18ebb8-c16a-11e7-9f96-d2455cb621c0.png">

**Comment by skjnldsv** [comment]
Yes, this is a known issue! :)
#56
