### ISSUE TITLE
Export all Contacts missing and Groups not sorted

### ISSUE THREAD

**Issue by toehold** [nextcloud/contacts#431]
After updating NC to 12.0.3 and updating Contacts to 2.0.1, the Export all Contacts is missing
and the Groups are sorted wrongly!

### Steps to reproduce
1. Go to Contacts

### Expected behaviour
Export all Contacts in Settings Menu

### Actual behaviour
Export is missing

### Server configuration
**Operating system**: Linux
**Web server:** Apache2
**Database:** mysql
**PHP version:** 7
**Nextcloud version:** 12.0.3
**Contacts version:** 2.0.1
**Updated from an older Nextcloud

**Comment by skjnldsv** [comment]
You can export your addressbooks one by one. :)

**Comment by skjnldsv** [comment]
The server needs to support it.

**Comment by skjnldsv** [comment]
Groups are sorted by count
Change on that are on #522
