### ISSUE TITLE
Incorrect synchronization of the instant messaging entries

### ISSUE THREAD

**Issue by konsdibons** [nextcloud/contacts#432]
Steps to reproduce
1. Usernames for Instant Messaging that are saved and created in the nextcloud contacts app are needed.
2. Access to your contacts via e.g. DAVdroid (Android) or CardBook (Thunderbird)
3. Have a look at the Instant Messaging entrys on your Android or Thunderbird

Expected behaviour
Your choice of Instant Messaging Service when you created the entry should also be available on Android/ Thunderbird.

Actual behaviour
If you choose the Instant Messaging service in Nextcloud it is saved as "type" of the entry (this is normally filled with "WORK" or "HOME".
It should normally be saved in an extra option, which is available in the external apps.
After correcting the entry in an external app, it has the type of service as prefix in the username field.

Contacts version: 2.0.1

(Sorry for my bad English)

**Comment by Henni** [comment]
I think I should be able to reproduce this.
But just to be sure: Could you share some example vCards with us.

**Comment by konsdibons** [comment]
sure.
I have to files for you. The first one is created with the contacts app in my browser and the other one is created with CardBook (Thunderbird). The name of the vCard says with which device it was created.

**1 (contacts app):**
```
BEGIN:VCARD
VERSION:3.0
FN:instant messaging nextcloud 
UID:999beda5-b84e-4cef-a7e4-d9797c46d55a
REV:20171110T092448Z
N:nextcloud;instant;messaging;;
IMPP;TYPE=SKYPE:exampleskype
END:VCARD
BEGIN:VCARD
VERSION:3.0
PRODID:-//Thunderbird.org/NONSGML Thunderbird CardBook V23.6//EN
UID:6d491340-ca2d-459b-ac03-dd0cd9915679
N:thunderbird;instant;messaging;;CardBook
FN:instant messaging thunderbird CardBook
REV:20171110T103503Z
IMPP;TYPE=HOME;X-SERVICE-TYPE=skype:skype:exampleskype
END:VCARD
BEGIN:VCARD
VERSION:4.0
PRODID:+//IDN bitfire.at//DAVdroid/1.9-ose ez-vcard/0.10.3
UID:71139ec3-478b-4896-8cbf-e74a9c7aa5d0
FN:instant messaging android\, davdroid
N:android;instant;messaging;;davdroid
IMPP:skype:exampleskype
REV:20171110T093633Z
END:VCARD
```

**2 (CardBook/Thunderbird):**
```
BEGIN:VCARD
VERSION:3.0
PRODID:-//Thunderbird.org/NONSGML Thunderbird CardBook V23.6//EN
UID:6d491340-ca2d-459b-ac03-dd0cd9915679
N:thunderbird;instant;messaging;;CardBook
FN:instant messaging thunderbird CardBook
REV:20171110T103442Z
IMPP;TYPE=HOME;X-SERVICE-TYPE=skype:skype:exampleskype
X-THUNDERBIRD-ETAG:"876e1aed1ccfac4420bbc3fc4ac506eb"
END:VCARD

BEGIN:VCARD
VERSION:3.0
PRODID:-//Sabre//Sabre VObject 4.1.2//EN
UID:71139ec3-478b-4896-8cbf-e74a9c7aa5d0
N:android;instant;messaging;;davdroid
FN:instant messaging android\, davdroid
REV:20171110T093633Z
IMPP:skype:exampleskype
X-THUNDERBIRD-ETAG:"c6664946a919ed1cbaf092d65333e91d"
END:VCARD

BEGIN:VCARD
VERSION:3.0
PRODID:-//Thunderbird.org/NONSGML Thunderbird CardBook V23.6//EN
UID:999beda5-b84e-4cef-a7e4-d9797c46d55a
N:nextcloud;instant;messaging;;
FN:instant messaging nextcloud 
REV:20171110T092448Z
IMPP;TYPE=SKYPE:exampleskype
X-THUNDERBIRD-ETAG:"50e01df4997fde9610cd7e3019e57dc9"
END:VCARD
```

**Comment by skjnldsv** [comment]
@Henni is this still on?

**Comment by Henni** [comment]
Tried fixing it a while ago. Didn't get very far...

**Comment by skjnldsv** [comment]
Android is using `IMPP:skype:test;` which is not valid either.
I'll try with iOS
