### ISSUE TITLE
Contacts not show up after updating Contact app to 2.0.1

### ISSUE THREAD

**Issue by mlsxlist** [nextcloud/contacts#435]
### Steps to reproduce
After updating the Contacts app to version 2.0.1 it does not show any contacts but only the turning waiting indicator on the left side and on the right side the text _No contacts available_

### Expected behaviour
Stored contacts should be shown when the app is opened

### Actual behaviour
No contacts are show with Contacts 2.0.1.

### Server configuration
**Operating system**: Debian 9

**Web server:** Apache/2.4.25

**Database:** mysql  Ver 15.1 Distrib 10.1.23-MariaDB

**PHP version:** PHP 7.0.19-1

**Nextcloud version:** 12.0.3

**Contacts version:** 2.0.1

**Updated from an older Nextcloud or fresh install:** fresh install

**Signing status:**
No errors have been found.

**List of activated apps:**
Enabled:
  - activity: 2.5.2
  - bruteforcesettings: 1.0.2
  - calendar: 1.5.6
  - comments: 1.2.0
  - contacts: 2.0.1
  - dav: 1.3.0
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - tasks: 0.9.5
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_external
  - user_ldap

**Nextcloud configuration:**
{
    "system": {
        "instanceid": "blabla",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "1.2.3.4",
            "host.domain:4321"
        ],
        "datadirectory": "\/var\/www\/nextcloud\/data",
        "overwrite.cli.url": "https:\/\/1.2.3.4\/nextcloud",
        "dbtype": "mysql",
        "version": "12.0.3.3",
        "dbname": "nextcloud",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN"

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Client configuration
**Browser:** Firefox ESR 52.4.0

**Operating system:** Debian 8

**CardDAV-clients:**

#### Web server error log
nothing related in it

#### Nextcloud log (data/nextcloud.log)
nothing special concerning contacts app

#### Browser log
Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src 'nonce-WWd2QkEwMkFJMUd6WG5aUzF6Vmx2aSt4WmtYVzFwd2UzWU5FRVpZRk1VZz06VlYrU1R4ZkNjR2FET0VZajVITU1qUmZMUENPd3VjUlBqS2cwUzlOaWNEbz0=' 'unsafe-eval'”). Source: (function injected(eventName, injectedIn....
https://host.domain:4321/nextcloud/index.php/apps/contacts/
Line 1

**Comment by skjnldsv** [comment]
Have you tried clearing your cache?

**Comment by mlsxlist** [comment]
Thanks, that did the job. Sorry for the noise. Could have figured out myself.
