### ISSUE TITLE
All contacts deleted after upgrade NC from 11.0.3 to 12.0.3 and contacts 2.01

### ISSUE THREAD

**Issue by jwich71** [nextcloud/contacts#440]
After NC Upgrade with Updater App from 11.03 to 12.0.3 all my contacts syncronized via CardDAV are deleted or no more visible in the WebUI.
Before upgrade all contacts were visible.

Nextcloud 12.0.3
Contacts 2.01
CentOS 7.4
PHP 7.1.11-1.el7.remi.x86_64
mariadb-server-5.5.56-2.el7.x86_64
httpd-2.4.6-67.el7.centos.6.x86_64

**Comment by brunt82** [comment]
> no more visible in the WebUI

Means the contacts are still there? (e.g. by requesting with Thunderbird or CardDav-Client)?

**Comment by skjnldsv** [comment]
Can we have a screenshot please?
Any errors in the browser's log?

Also: yes, the contacts are handled in the db and the malfunction of this app does not induce a data loss.

**Comment by jwich71** [comment]
After a server reboot, the contacts are all visible again. Don't know what happend there.
Thanks for your help.
