### ISSUE TITLE
Feature request: show Nextcloud system users in contact app

### ISSUE THREAD

**Issue by novij** [nextcloud/contacts#446]
Nextcloud system users are displayed in contact search on the top right corner, but not in contact app if you click "show all contacts".
![contacts-empty](https://user-images.githubusercontent.com/111357/33277190-10355c4a-d398-11e7-8eb1-97d7d0f79b7b.png)

On IRC i got the answer that this is not possible at the moment. I think there are use cases where a global address book would make sense, e.g. a dedicated Nextcloud installation for a company.

**Comment by skjnldsv** [comment]
Duplicate https://github.com/nextcloud/server/issues/693
