### ISSUE TITLE
Navigation toggle and back button not shown on mobile anymore

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/contacts#448]
Previously we had the hamburger menu button on the top left so you can toggle the sidebar. And when the contact detail view is open, we had a back button. This is not there anymore, maybe due to some JS change? Because we insert `app-navigation-toggle` into `app-content`.

cc @nextcloud/contacts @nextcloud/javascript

**Comment by skjnldsv** [comment]
I will fix it on #438
