### ISSUE TITLE
Contacts ⭐️ does not work

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/contacts#451]
I think @skjnldsv introduced a ⭐️ into the contacts which should not be there, since it is not working.
Maybe we want to add something like that in a later version, but for now - it is a non-woking element and should be removed.

<img width="209" alt="bildschirmfoto 2017-12-13 um 17 14 48" src="https://user-images.githubusercontent.com/19711361/33949195-397943f8-e029-11e7-98b1-7c945dac2726.png">
<img width="202" alt="bildschirmfoto 2017-12-13 um 17 14 57" src="https://user-images.githubusercontent.com/19711361/33949200-3c5120fa-e029-11e7-977d-3f3cc1d6ec4b.png">

**Comment by skjnldsv** [comment]
It is removed on the stable13 pr.
Closing as invalid.

**Comment by MariusBluem** [comment]
Thx.
