### ISSUE TITLE
Contacts with same name are selected incorrect in list

### ISSUE THREAD

**Issue by mjohenneken** [nextcloud/contacts#463]
### Steps to reproduce
1. Create two contacts with the same name
2. Make sure the contacts list is sorted by name
3. Select the upper one of the created contacts

### Expected behaviour
The contact on which i clicked is selected, and show in the detail

### Actual behaviour
The contact below is selected, but the detail show the information of the upper contact
Also you cannot select the other one which details are not show, because it is already selected. 

### Server configuration

**Operating system**:
Linux probably debian
**Web server:**
apache (shared webhosting)
**Database:**
Mysql 5.6.38
**PHP version:**
7.1 fastcgi
**Nextcloud version:** (see Nextcloud admin page)
12.0.5
**Contacts version:** (see Nextcloud apps page)
2.0.1
**Updated from an older Nextcloud or fresh install:**
Since owncloud 8
**Signing status:**

**Are you using external storage, if yes which one:** nope

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** nope

### Client configuration
**Browser:**
Google Chrome 63.0
**Operating system:**
Android
Windows
Ubuntu
**CardDAV-clients:**

Carddav-Sync
Cardbook
Evolution

**Comment by skjnldsv** [comment]
Fixed int he last version iirc!
