### ISSUE TITLE
Add easy way to move contacts between addressbooks

### ISSUE THREAD

**Issue by Loki3000** [nextcloud/contacts#470]
It's a good idea to share contacts groups between users but, as I see, cardDAV not support shared groups - only shared addressbooks. So as a solution I see two addressbooks - private and shared. But now there is no way to quick move contact between adressbooks: if I want to share private contact, I can't move it in shared addressbook - only create new one. Maybe it's good solution to add possibility in web app to move contact from one addressbook to another?

**Comment by skjnldsv** [comment]
You can change the addressbook at the end of the contact details if that's what you were looking for? :)

**Comment by Loki3000** [comment]
Exactly! It's field was hidden while only one addressbook;)
