### ISSUE TITLE
Everyone Group missing for Global Address Book user access and update

### ISSUE THREAD

**Issue by ali3seven** [nextcloud/contacts#472]
Hi. First of all Thanks for your very good product. 
I'm using NextCloud 12.05 by using MailInABox boundle. Everything works fine.
However I'm afraid that there was only one feature missing (Or maybe I couldn't find).
I was wondering if there is any guide about that too.
But let me explain it here (According to template):

### Expected behaviour:
What actually needed is a "**Global Address Book**". but what does it mean?
A Global Address Book is something exactly the same as Exchange Global Address Book (or other app)
each user has the ability to view all of the public contact and address book as soon as it created. 
It doesn't make require administrator to share the Public List for each new user.

### Actual behaviour
Unfortunately sharing contact seems only possible through share to specific user(s).
It is very good, but large amount of job is required for sharing the list to each user.
Now only Personal Address List (and calendar) assigned to each user by default. Not a Global. 

### Example (what really happen about the case)
Let me give an example for both benefit and cons.
Consider a large company, every time new user may come and left. also you need to prepare them a contact list of present user in the company.

- What you can do (Step to Procedure):
1. You will create a list of all "**Current**" users and contact.
2. Share this list by assigning all users 
   (you can't find "all users", you need to specify it per each user eg user1, user2 and etc)
3. Now they can view your list that you shared it among them.

- Issues that will occure
It's OK. However it is very useful to specify permission to specific user for sharing The Public list But two major issue will occurred (of course two other issues might be exist):

1. Each time that new user come, you should update the public list by adding that.
2. Each time  new user come, you need to add new user to access your list.
3. Each time user left you have to delete it form list
4. Each time user left, you need to remove the user from current sharing list to deny access.

### Propose (As a non-developer):
I think these issue can solved if the current source code can change to prepare two thing:
1. Adding "Everyone" Item - that create a group by all the contact 
2. Disabled user automatically remove from the list. (If in the first propose "Everyone" item just show "Active Users" I think the second propose can be merged in that too.)
Thanks in advance.

**Comment by skjnldsv** [comment]
Actually, this is easily doable. You can create a group where all your users are and directly share an addressbook with that group.
I see your point, but I don't really like the idea of proposing that feature in-the-box. :)
I would prefer if people use the solution I gave here! ;)

@jancborchardt @Henni thoughts?

**Comment by ali3seven** [comment]
@skjnldsv John, Thanks very much for reply, but I'm afraid that it can do easily. Let me know about your idea if I was in wrong. That is what I found out from the reply:
> You can create a group where all your users are and directly share an address book with that group.

Yes, I can do it once at the first time. It means I created one list and add all of "Current user" in that. It is OK and fully acceptable. But how should we do for **new user** that come? Does them included in the list Automatically? (unfortunately I don't think so)

The created list actually should be updated each time when new user comes, because I can't do it once for "**everyone**" at the first. This is because I don't have something like everyone (as the same as windows for NTFS Permission) to access all of newly created users.  At this way I was not be worried about accessing new user to my created list. because all of them have access to view it.
But By using Everyone, I think both problem can be solved. both new user will added automatically in created list, and also new user have access to the created list. (that in usual we should it both in contact and list share permission).
Believe that many user just using exchange just for that feature. But here is really good possibility to omit it. 

**Additional Note**: Your complete package (with apps) is something like MS.Exchange+SharePoint. it has many the same features and very interesting. I hope we can see more improvement as powerful in some smaller scale.
Thanks in advance

**Comment by ali3seven** [comment]
Well, I tried it. It seems creating group for user sound good idea. It can prevent a lot of work to share.
So only the "**contact list**" is required to shared for "**group**". 
as it shown **List** refer to _Contact_ and **Group** refer to _Users_ here.
It's almost perfect if you have some fix and static contacts.

but consider dynamic environment, 
I think if we can share the list with "**No Group**" item we achive the first goal. (No need to put each new user in group). and the newly created users have access to the list by default.

But about second goal, does any way exist to add "user" to "contact list" automatically? I think "contact" and "user" are considered completely separated entity from each other. However each user may be a contact too. Then there is also need to create one contact after each user created too. So I think we can not expect such automation as the same as second goal achieved. dublicate work maybe required in lack of auto contact creation for newly created user.
but altogether good job even with these matters. I hope it can be improve even more by satisfying more automation. Thanks in advance

**Comment by svenwaibel** [comment]
Hi,
i have a similar proposal:

As admin i create an address book and share it with group X. That's already possible, but i just can say editable or not. If it's editable all group users can edit all contacts and this is not what i want.
What i need is that the address book is shared, all users from that group are in that address book automatically, but just with their name.
When they add more details like address, birthday,... they decide if they want to share their details with the group.
If a new user is added to the group then he will appear with his name and his shared details automatically.
Another option would be to share different details with different group address books.Example: In my good friend group i share my birthday, but in the work group not. This may be solved with a share - address book - relation.
Privacy of all users are considered because they can decide by themselves what details are shared.

Thanks
Sven

**Comment by skjnldsv** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there a no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.

We received similar suggestions regarding sharing in general on server and this is rather complicated security speaking. We rather not have a global group.

Automation for users in groups should be asked and handled in https://github.com/nextcloud/server. I'm pretty sure this is a feature that have already been asked ;)
