### ISSUE TITLE
Hide Birthdays "Enable disable addressbooks"

### ISSUE THREAD

**Issue by thfree** [nextcloud/contacts#473]
Раз вы добавили "Enable disable addressbooks", то может стоит реализовать возможно скрыть дни рожения отключенных контактов из календаря?

Спасибо.

-------------------
Once you added "Enable disable address books," then maybe it's worthwhile to realize it's possible to hide the birthdays of disconnected contacts from the calendar?

Thank you.

**Comment by skjnldsv** [comment]
Could you open this on the server issue repository please? :)
Calendar address books are generated there!

Thank you very much! :)
