### ISSUE TITLE
Group list broken since v2.1.0

### ISSUE THREAD

**Issue by exploide** [nextcloud/contacts#474]
Since the update to v2.1.0, the group list on the left side is broken. It shows the JSON of the group instead.

### Steps to reproduce
1. Update to v2.1.0
2. open Contacts app
3. see that the group list is broken

### Expected behaviour
I would like to see a human readable list of my groups :P

### Actual behaviour
I see entries like `{"name":"My Group","count":8}` instead.

### Server configuration

**Operating system**: Fedora 27

**Web server:** nginx

**Database:** mariadb

**PHP version:** 7.1.14

**Nextcloud version:** 13.0.0

**Contacts version:** v2.1.0

**Updated from an older Nextcloud or fresh install:** upgraded from 12.x

**Signing status:** ?

### Client configuration
**Browser:** Firefox 58.0.1

**Operating system:** Fedora 27

**CardDAV-clients:** n/a

#### Web server error log
nothing

#### Browser log
```
JQMIGRATE: Migrate is installed, version 1.4.0
core.js:7:542
Content Security Policy: [something got blocked on] self ("script-src 'nonce-[some-nonce-here]' 'unsafe-eval'"). Source: ondrop attribute on INPUT element.
contacts
Source-Map-Fehler: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Ressourcen-Adresse: [mydomain]/core/vendor/core.js?v=4c25bf16-4
Source-Map-Adresse: purify.min.js.map
```

**Comment by Henni** [comment]
I can't reproduce this
@skjnldsv can you?

**Comment by skjnldsv** [comment]
@Henni I can't! :/
@exploide Can you uninstall the contacts app, and remove it? Then install it again?

**Comment by exploide** [comment]
Apparently, the issue occurs only with Firefox, it works well with Chromium.

I disabled the app and removed if afterwards using the webinterface. `ls` on `apps/` dir confirmed it was gone. Reinstalled again also using the webinterface. Issue persists.

**Comment by skjnldsv** [comment]
Working on latest firefox! :/
@exploide could it be an extension that is breaking the app?

**Comment by exploide** [comment]
Well that's strange... 
You mean a Firefox extension? I also thought of this but even when restarting Firefox in safe-mode, which disables all extensions, the issue is present.

As I mentioned in the opening post, the dev console logs:
```
JQMIGRATE: Migrate is installed, version 1.4.0
core.js:7:542
Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src 'nonce-[some-none]' 'unsafe-eval'”). Source: ondrop attribute on INPUT element.
contacts
Source map error: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Resource URL: https://[my-domain]/core/vendor/core.js?v=4c25bf16-4
Source Map URL: purify.min.js.map
```

Anything else I can do to help?

**Comment by skjnldsv** [comment]
What ff version are you using?
Yes, I was thinking about a firefox ext! :)

**Comment by exploide** [comment]
Ok, after testing this with manually disabling extensions as well as using the safe-mode, I can rule out an extension issue.

As stated in the opening post, I'm using Firefox 58.0.1 on Fedora 27.

**Comment by skjnldsv** [comment]
@exploide Still can't reproduce. 😕

**Comment by skjnldsv** [comment]
@exploide did you cleared your cache?

**Comment by exploide** [comment]
Mh, in fact you are right. I force-reloaded the page dozen times with ctrl+F5 but it did not help. Now with the forget about this site feature in Firefox it looks as expected. Don't know what exactly was still cached there... But thanks anyway.

**Comment by skjnldsv** [comment]
This is very strange since we added a fallback for such scenario NOT to appear.
@Henni could it be that html templates are cached? Js?

**Comment by tony5** [comment]
it is a browser caching issue. ctrl+f5 is not enough to clear it.

**Comment by Henni** [comment]
hm... no idea which resource broke this... Possibly the change regarding contactFilters I did...

We could implement a way that forces the browser to reload our js by appending the version number as a querystring (`script.js?v=2.1.0) for future releases. Although this might prevent caching of the resource at all for some configurations. And this also only works if the main template wasn't cached...

> There are only two hard things in Computer Science: cache invalidation and naming things.
    -- Phil Karlton

**Comment by skjnldsv** [comment]
@Henni Ah yes, I need to implement this into the server as well for js! :/ 
I'll see what I can do!

**Comment by Henni** [comment]
No idea how other apps are currently solving this. Calendar doesn't do anything like querystring versioning as far as I can see...

**Comment by tony5** [comment]
in firefox under "privacy and security/cached web content" clear now button fixes the issue.
I hope that helps someone. 
ctrl+f5 does not clear enough it looks like.

**Comment by raoulbhatia** [comment]
I can confirm this issue when upgrading from Nextcloud 12.0.6 to 13.0.1.  "Forget about this site" solves this problem.

I think that this is a critical issue that will render the contact app unusable for regular non-tech user and will negatively impact Nextcloud adoption ☹️

**Comment by raoulbhatia** [comment]
I can confirm this issue when upgrading from Nextcloud 12.0.6 to 13.0.1.  "Forget about this site" solves this problem.

I think that this is a critical issue that will render the contact app unusable for regular non-tech user and will negatively impact Nextcloud adoption ☹️

**Comment by skjnldsv** [comment]
@raoulbhatia I completely agree, but unfortunately it's a browser issue. Though we need to add a workaround for this as too many people have had issues with this
