### ISSUE TITLE
Contact List and Group List not working after update to 2.1.0

### ISSUE THREAD

**Issue by mars24568** [nextcloud/contacts#475]
After update to 2.1.0 the group list vanished completely, the contact list contains all entries, but none of those is selectable. This might be related to entry #474 
Removing the contacts app and re-installing does not change the behaviour.

### Steps to reproduce
1. Update to 2.1.0
2. open Contacts app
3. group list is not visible, contact list entries are visible, but not selectable

### Expected behaviour
Behaviour as prior to the update

### Actual behaviour
Group list on the left side is not shown at all
Contact list on the left side contains entries, but they are not selectable

### Server configuration

**Operating system**: Raspbian Stretch

**Web server:** Apache

**Database:** SQlite

**PHP version:** 5.6.30-0+deb8u1

**Nextcloud version:** 13.0.0

**Contacts version:** 2.1.0

**Updated from an older Nextcloud or fresh install: updated from 12.x

**Errors from index.php/settings/integrity/failed 
No errors have been found.

**List of activated apps:**
Calendar
Checksum
Contacts
Unsplash

**Are you using encryption:** yes/no
no

### Client configuration
**Browser:** Firefox 52.6.0 (64bit) esr

**Operating system:** Windows 7

**CardDAV-clients:** none

#### Web server error log
no entry

#### Nextcloud log (data/nextcloud.log)
no entry

#### Browser log
This is (maybe) the relevant section of one contact entry. I don't know enough of this stuff to decide if that helps, sorry:
´´´
<div class="app-content-list-item ng-scope ng-isolate-scope active" ng-repeat="contact in ctrl.filteredContacts = (ctrl.contactList | contactGroupFilter:ctrl.routeParams.gid | localeOrderBy:ctrl.sortBy | filter:query | limitTo:ctrl.limitTo) as filtered track by contact.uid()" contact="" data="contact" ng-click="setSelected(contact.uid())" ng-class="{active: contact.uid() === ctrl.getSelectedId()}"><a class="app-content-list-item-link" ng-click="ctrl.openContact()">
    <img class="app-content-list-item-icon contact__icon ng-hide" ng-show="ctrl.contact.photo()!==undefined">
    <div class="app-content-list-item-icon contact__icon ng-binding" ng-show="ctrl.contact.photo()===undefined" ng-style="{'background-color': (ctrl.contact.uid() | contactColor) }" style="background-color: rgb(177, 231, 116);">A</div>
    <div class="app-content-list-item-star icon-star" data-starred="false"></div>
    
    <div class="app-content-list-item-line-one ng-binding" ng-class="{'no-line-two':!ctrl.contact.email()}">X Y</div>
    <div class="app-content-list-item-line-two ng-binding">xy@gmx.net</div>
</a>
</div>

**Comment by mars24568** [comment]
Ok. If anybody is interested: Everything works ok after setting Firefox to private mode.

**Comment by skjnldsv** [comment]
@mars24568 don't apologise! :)
Thanks for reporting the issue, you can follow it here: #474
