### ISSUE TITLE
Contact images "flicker" on latest Firefox

### ISSUE THREAD

**Issue by onny** [nextcloud/contacts#478]
### Steps to reproduce
1. Loading contacts app

### Expected behaviour
Vertical alignement of contact images should centered and no "flickering" should appear.

### Actual behaviour
Contact images odly move several times and are then unaligned to the top
![broken](https://user-images.githubusercontent.com/757752/36174264-205114aa-110c-11e8-943a-a0fde8ff22d7.gif)
This behaviour does not appear in Chrome/Chromium!

### Version stats
- contacts app 1.2.0
- firefox 58.0.2

**Comment by skjnldsv** [comment]
You need to clear your Firefox cache.
Use the "forget all about this site" feature :)

@Henni this does confirm that html templates are being cached by the browsers. :/
