### ISSUE TITLE
update fails with "Diese App kann nicht installiert werden, da die Version in info.xml nicht die gleiche Version wie die aus dem App Store ist."

### ISSUE THREAD

**Issue by Wikinaut** [nextcloud/contacts#48]
pls. advice

**Comment by Wikinaut** [comment]
trying to update from 
Contacts 1.4.0.0

**Comment by Wikinaut** [comment]
<dependencies>
        <owncloud min-version="9.0" max-version="9.2" />
    </dependencies>

can this be the reason ?

**Comment by Wikinaut** [comment]
running Nextcloud 10.0.1 (stable)

**Comment by DeepDiver1975** [comment]
https://github.com/owncloud/contacts/issues/547#issuecomment-265074687

**Comment by Wikinaut** [comment]
Okay, works now.
