### ISSUE TITLE
Logins with hard restrictions

### ISSUE THREAD

**Issue by MrNoname33** [nextcloud/contacts#482]
We need logins that are only useable at a single machine. When we give somebody a login we never know if this login is not distributed anywhere. Cool would be a login that generates a unique key that you can use one time in your Nextcloud client where the key generates also a unique key. This second key should be automatically send back to our Nextcloud server where this key is used to grant access rights for this one and only person from this one and only machine (computer, tablet, smartphone, etc.)

**Comment by skjnldsv** [comment]
Sorry, but I have no idea what you're talking about! :(

**Comment by MrNoname33** [comment]
When you have a Nextcloud server and creates one user login and this login have the rest of the world then the rest of the world have access to your server. When it would be possible to create a login only for the Nextcloud client and a login is nailed on one machine, where it is use the very first time, then only this machine have access. That would be very helpful for us.

**Comment by skjnldsv** [comment]
I think you're in the wrong place. This repository is for the contacts application.
But as I understand, you want specific passwords for different machines?

**Comment by MrNoname33** [comment]
Oh, excuse me. Yes, I am wrong in this place.

And yes, I want to have such passwords for the Nextcloud client.

**Comment by MrNoname33** [comment]
Can I move this thread anywhere?

**Comment by skjnldsv** [comment]
This is actually already implemented. You can go to your settings > security and create per-apps passwords :)

Don't worry, I'll close this thread
