### ISSUE TITLE
Since Upgrade from 2.0.1 to 2.1.0 all groupname apper {"name":"GROUPNAME","count":23}

### ISSUE THREAD

**Issue by Mannshoch** [nextcloud/contacts#489]
### Steps to reproduce
1. Upgrade from 2.0.1 to 2.1.0
2. Open Contact tab - First time I got only a Blank Group list
3. Refresh 
![nextcloud-contact](https://user-images.githubusercontent.com/7795891/36419061-2d2ec116-1631-11e8-94d2-7f03110bc338.png)

### Expected behaviour
See all groups listed

### Actual behaviour
{"name":"GROUPNAME","count":23}

**Comment by skjnldsv** [comment]
Duplicate #474

**Comment by Mannshoch** [comment]
As described in #474 I cleared the cache. Problem solved:
![nextcloud cache leeren](https://user-images.githubusercontent.com/7795891/36423462-5c0481ec-1640-11e8-8652-d8f0f34825df.png)

**Comment by raoulbhatia** [comment]
I can confirm this issue when upgrading from Nextcloud 12.0.6 to 13.0.1.  "Forget about this site" solves this problem.

I think that this is a critical issue that will render the contact app unusable for regular non-tech user and will negatively impact Nextcloud adoption ☹️
