### ISSUE TITLE
Can't update Contacts 2.1.1

### ISSUE THREAD

**Issue by WNYmathGuy** [nextcloud/contacts#499]
### Steps to reproduce
1. Click the button for "Update to 2.1.1"

### Expected behaviour
Install the update

### Actual behaviour
Fails to install see attached screenshot for on screen error message.
[https://ruppssites.com/NextCloud-Fail-1.png](https://ruppssites.com/NextCloud-Fail-2.png)
### Server configuration

[https://ruppssites.com/NextCloud-Fail-2.png](https://ruppssites.com/NextCloud-Fail-2.png)

**Operating system**: Ubuntu 16.04 LTS

**Web server:** Apache2

**Database:** MariaDB 10.0.33

**PHP version:** 7.0

**Nextcloud version:** (see Nextcloud admin page) 13

**Contacts version:** (see Nextcloud apps page) 2.1.0

**Updated from an older Nextcloud or fresh install:** Fresh Install

**Signing status:** ? Let's Encrypt?

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- core
	- EXTRA_FILE
		- .well-known/acme-challenge/.htaccess

Raw output
==========
Array
(
    [core] => Array
        (
            [EXTRA_FILE] => Array
                (
                    [.well-known/acme-challenge/.htaccess] => Array
                        (
                            [expected] => 
                            [current] => d1c54aa5adc100187bee69c06d79c6a9a54dc6338c398c21c8dd48c8fbdfd72a2f2ca73433ae5bf4255a61c6d2806ba8ba3fff12d3e677273345eea85ed47bc5
                        )

                )

        )

)

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
Could not open input file: occ

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your instance's installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
<?php
$CONFIG = array (
  'instanceid' => '',
  'passwordsalt' => '',
  'secret' => '',
  'trusted_domains' => 
  array (
    0 => '',
  ),
  'datadirectory' => '',
  'overwrite.cli.url' => '',
  'dbtype' => 'mysql',
  'version' => '13.0.0.14',
  'dbname' => '',
  'dbhost' => '',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => '',
  'dbpassword' => '',
  'installed' => true,
  'mail_from_address' => '',
  'mail_smtpmode' => 'smtp',
  'mail_smtpauthtype' => '',
  'mail_domain' => '',
  'mail_smtphost' => 'smtp.mailgun.org',
  'mail_smtpport' => '587',
  'mail_smtpauth' => 1,
  'mail_smtpname' => '',
  'mail_smtppassword' => '',
  'maintenance' => false,
);

**Are you using external storage, if yes which one:** 

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** no

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';
No data returned

Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:** Firefox

**Operating system:** Ubuntu 17.04 workstation
![screenshot from 2018-02-27 23-10-03](https://user-images.githubusercontent.com/28640985/36770151-ab8a1bba-1c16-11e8-9118-952f8d79bb30.png)
![screenshot from 2018-02-27 22-58-13](https://user-images.githubusercontent.com/28640985/36770152-ab98494c-1c16-11e8-9e22-eddc20d59353.png)
![screenshot from 2018-02-27 23-10-03](https://user-images.githubusercontent.com/28640985/36770168-cb26a57e-1c16-11e8-9125-297735af4f96.png)
![screenshot from 2018-02-27 22-58-13](https://user-images.githubusercontent.com/28640985/36770169-cb31d110-1c16-11e8-8b0c-44e12f72aece.png)
![screenshot from 2018-02-27 23-10-03](https://user-images.githubusercontent.com/28640985/36770175-dd54c532-1c16-11e8-8121-df4f95957ea8.png)
![screenshot from 2018-02-27 22-58-13](https://user-images.githubusercontent.com/28640985/36770176-dd62883e-1c16-11e8-966d-517b21e4064f.png)

**CardDAV-clients:**

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by WNYmathGuy** [comment]
FUCK!!! I'm such an asshole. I went over my own self-prescribed limits on my own server. I uploaded a fuck load of files from my google mobile dev to my private NextCloud that I hit the quota and didn't realize it till I tried to open my email box and got an over quota warning.

**Comment by skjnldsv** [comment]
A bit too extreme, but I'm glad you found the solution :)
