### ISSUE TITLE
Contact could not be saved if both anniversary and birthday

### ISSUE THREAD

**Issue by pinowthebird** [nextcloud/contacts#501]
### Steps to reproduce
1. Create a new contact
2. Add birthday
3. Add anniversary
----
1. Edit an existing contact that has a birthday
2. Add anniversary

### Expected behaviour
Save contact.

### Actual behaviour
Error message: "Contact could not be saved."

#### Browser log
"Calendar object with uid already exists in this calendar collection."

**Comment by christian-weiss** [comment]
@pinowthebird i have a very similar issue in #507 and some findings. Can you confirm my findings with your issue?

**Comment by pinowthebird** [comment]
Yes, and I'm pretty sure the issue comes down to "more than one date field for a contact". So the same goes for date of death as well.
