### ISSUE TITLE
Thunderbird: Synchronize e-mails seems to be random

### ISSUE THREAD

**Issue by boldt** [nextcloud/contacts#502]
I don't get, how the my nextcloud contacts are synced with Thunderbird (with Sogo). As far as I recall, Thunderbrid can only handle two e-mail adresses (I cant find the related issue on bugzilla now).

Imagine I have a contact with 2 or 3 adresses. I can apply the following cases:

| | WORK          | PRIVATE       | OTHER  |
|-| ------------- | ------------- | ------ |
Case 1 | ✓                   | ✓                  |        |
Case 2 | ✓                   |               | ✓        |
Case 3 |               | ✓                   | ✓        |
Case 4 | ✓              | ✓                   | ✓        |

## Case 1

1) PRIVATE: private@test.de
2) WORK: work@test.de

Result in Thunderbird:

1) main-adress: work@test.de
2) other adress: private@test.de

The VCF cotains the following:

```
EMAIL;TYPE=HOME:private@test.de
EMAIL;TYPE=WORK:work@test.de
```
## Case 2

1) WORK: work@test.de
2) OTHER: other@test.de

Result in Thunderbird:

1) main-adress: other@test.de
2) other adress: **EMPTY**

The VCF cotains the following:

```
EMAIL;TYPE=WORK:work@test.de
EMAIL;TYPE=OTHER:other@test.de
```

## Case 3

1) PRIVATE: private@test.de
2) OTHER: other@test.de

Result in Thunderbird:

1) main-adress: other@test.de
2) other adress: private@test.de

The VCF cotains the following:

```
EMAIL;TYPE=HOME:private@test.de
EMAIL;TYPE=OTHER:other@test.de
```

## Case 4

1) PRIVATE: private@test.de
2) OTHER: other@test.de
3) WORK: work@test.de

Result in Thunderbird:

1) main-adress: other@test.de
2) other adress: private@test.de

The VCF cotains the following:

```
EMAIL;TYPE=HOME:private@test.de
EMAIL;TYPE=WORK:work@test.de
EMAIL;TYPE=OTHER:other@test.de
```
## Obervation

It's seems to be random, which address in Thunderbird is synced into which field.

**Comment by mburnicki** [comment]
As far as I know, the limitation of 2 email addresses is also in Sogo. I'm using the Cardbook plugin for Thunderbird which can also synchronize with Nextcloud but supports more than 2 email addresses.

**Comment by wjwieland** [comment]
I have also found that Thunderbird with Cardbook handles syncing and generally behaves better with the NC's Contacts DAV than it does with the basic Thunderbird Contacts app.  I have some contacts with more than two email addresses and they sync fine with Thunderbird as well as to my tablet and phone now that Cardbook is installed.  

I hope that this rather anecdotal input is helpful in some way....

**Comment by boldt** [comment]
I'm also happy with the following combination:

- Ubuntu/Thunderbird/Cardbook
- Android/CardDAV-Sync

**Comment by skjnldsv** [comment]
Same as #231 

> Closing since this is not related to the contacts app.
> We're a standard webdav server. Sogo can connect to any of them. Any errors should be notified to sogo directly unless they advize you to do that here, therefore this will come from https://github.com/nextcloud/server :)
> 
>
