### ISSUE TITLE
Enable/disable birthday information for auto-generation on server

### ISSUE THREAD

**Issue by oresch** [nextcloud/contacts#504]
In the contact app there should be a possibility to enable/disable the birthday information for the server to generate/or not the calendar event.

In my case I got a lot of birthday information in my address book. But I don't want them all to be used for event generation by the server.
Maybe the [closed issue 473](https://github.com/nextcloud/contacts/issues/473) is pointing in the same direction.

My proposal: add a switch to the birthday field (on/off) which than afterwards shall be taken into account by the server.

**Comment by skjnldsv** [comment]
Like it says on #473, the calendar is being generated by the server.

**Comment by oresch** [comment]
But the server can not know which contact he should not render! This is, why I opened this issue in the contact app.
