### ISSUE TITLE
Contact sorting still doesn't work as expected

### ISSUE THREAD

**Issue by RainerEmrich** [nextcloud/contacts#505]
At the moment we have the option to sort the contacts by "Display name", "First name" or "Last name". But the "Last name" sorting still doesn't work.

Her are simple data to test with:

BEGIN:VCARD
VERSION:3.0
FN:Auser Zname 
UID:4d73a9f3-a63c-453c-b042-5620c6373115
N:Zname;Auser;;;
REV:20180228T151648Z
END:VCARD
BEGIN:VCARD
VERSION:3.0
FN:Buser Yname 
UID:8fc04e91-a1e0-44a5-a17b-90c15a2ff692
N:Yname;Buser;;;
REV:20180228T151718Z
END:VCARD
BEGIN:VCARD
VERSION:3.0
FN:Cuser Xname 
UID:5db8def9-31fc-4504-9f4c-9241d67f6791
N:Xname;Cuser;;;
REV:20180228T151751Z
END:VCARD

First I imported these data in to the default address book:

![contacts1](https://user-images.githubusercontent.com/26002841/36799615-df045572-1cad-11e8-8181-891075bb2f2b.png)

![contacts2](https://user-images.githubusercontent.com/26002841/36799641-ec237620-1cad-11e8-93d8-0c280d31a4b4.png)

Afterwards I switched to "Last Name" Sorting.

![contacts3](https://user-images.githubusercontent.com/26002841/36799695-0cd77736-1cae-11e8-9a8b-2e981c1f7e76.png)

This seems to be ok. But after switching to a different app and coming back to the contacts, I see the following:

![contacts4](https://user-images.githubusercontent.com/26002841/36799755-387b092a-1cae-11e8-9eb4-3eacfa488688.png)

For "Auser Zname" the entry is switched to "Zname, Auser" and moved in the list. But only the selected contact entry is affected, which was the first one in the list.

The only way to get the list sorted by "Last name" is to click every single entry.

![contacts5](https://user-images.githubusercontent.com/26002841/36800076-e610ecd0-1cae-11e8-8f04-e7825f93bd96.png)

I think we need a solution here. Otherwise the contact app isn't really usable in a business environment.

**Comment by skjnldsv** [comment]
Hi! :)
If I understand correctly, it works but the sorting settings are not properly saved?

**Comment by RainerEmrich** [comment]
The sorting setting is saved, as you see on the fourth screen shot. But only the selected entry is affected. So if you come back to the contacts app, only the first entry gets changed to "Last name, First name" display and moved in the list. When you select an entry by click, the name display is also changed and the entry is moved. So, to sort the entire list by "Last name" you have to click every single contact entry. You may use the example data and try it yourself.

**Comment by RainerEmrich** [comment]
Same applies to "First name" sorting. If set a prefix in the detailed name, you observe the same issue for "First name" sorting. Summary: Sorting by "First name" or "Last name" doesn't work as expected.

**Comment by vvdimako** [comment]
Same here, too. After changing sorting to "Last name", I can see my contacts list been reordered but not all contacts are sorted correctly. Clicking on a wrongly placed contact results in it being reordered to the correct position.

**Comment by skjnldsv** [comment]
Let's fix this for the next version
