### ISSUE TITLE
Option to display last name first

### ISSUE THREAD

**Issue by vvdimako** [nextcloud/contacts#506]
Hi there, 
maybe I did not search exhaustively, but I could not find a similar request:
Is it possible to add an option to show contacts by LAST name first? 
I am not referring to sorting, just how a contact name is displayed.

**Comment by skjnldsv** [comment]
Duplicate #373

**Comment by vvdimako** [comment]
No problem; tried to avoid this with my last sentence but failed :-)
Yes, I mean display last name first, no matter what the sorting preference is (the display style and the sorting order should be independent)
Thanks for the quick reaction!

**Comment by vvdimako** [comment]
From what I see this is related to the sorting order, i.e. when I select sorting by first name, then contacts are displayed as (firstname lastname) *and* sorted by firstname. If I select sorting by last name then (I just discovered) that contacts are displayed as (lastname, firstname) *and* sorted by lastname. I.e. sorting changes the way a contact is displayed.

Actually, the way it works now is satisfactory (so you might leave this request as low priority) but due to bug #505, sorting by last name does not actually produced the correct display unless you click on each contact.

**Comment by Luckyvb** [comment]
Change format of FullName, need to add setting to allow user slect wich its want:
`diff --git a/js/components/detailsItem/detailsItem_controller.js b/js/components/detailsItem/detailsItem_controller.js`
`index a8808e6..3ebff23 100644`
`--- a/js/components/detailsItem/detailsItem_controller.js`
`+++ b/js/components/detailsItem/detailsItem_controller.js`
`@@ -101,15 +101,15 @@ angular.module('contactsApp')`
 `               if (ctrl.data.value[3]) {`
 `                       fn += ctrl.data.value[3] + ' ';`
 `               }`
`+               if (ctrl.data.value[0]) {`
`+                       fn += ctrl.data.value[0] + ' ';`
`+               }`
`                if (ctrl.data.value[1]) {`
`                        fn += ctrl.data.value[1] + ' ';`
`                }`
`                if (ctrl.data.value[2]) {`
`                        fn += ctrl.data.value[2] + ' ';`
 `               }`
`-               if (ctrl.data.value[0]) {`
`-                       fn += ctrl.data.value[0] + ' ';`
`-               }`
`                if (ctrl.data.value[4]) {`
`                        fn += ctrl.data.value[4];`
 `               }`

**Comment by Luckyvb** [comment]
```
diff --git a/js/components/contact/contact_controller.js b/js/components/contact/contact_controller.js
diff --git a/js/components/contact/contact_controller.js b/js/components/contact/contact_controller.js
index aa3dcd4..fc33434 100644
--- a/js/components/contact/contact_controller.js
+++ b/js/components/contact/contact_controller.js
@@ -21,6 +21,15 @@ angular.module('contactsApp')
                        ).trim();
                }

+               if (SortByService.getSortByKey() === 'sortLastNameNoComma') {
+                       return (
+                               ctrl.contact.lastName()
+                               + (ctrl.contact.firstName() ? ' ' : '')
+                               + ctrl.contact.firstName() + ' '
+                               + ctrl.contact.additionalNames()
+                       ).trim();
+               }
+
                if (SortByService.getSortByKey() === 'sortFirstName') {
                        return (
                                ctrl.contact.firstName() + ' '
diff --git a/js/services/sortBy_service.js b/js/services/sortBy_service.js
index b83654b..9c0b675 100644
--- a/js/services/sortBy_service.js
+++ b/js/services/sortBy_service.js
@@ -6,6 +6,7 @@ angular.module('contactsApp')
        var sortOptions = {
                sortFirstName: ['firstName', 'lastName', 'uid'],
                sortLastName: ['lastName', 'firstName', 'uid'],
+               sortLastNameNoComma: ['lastName', 'firstName', 'uid'],
                sortDisplayName: ['displayName', 'uid']
        };

@@ -45,6 +46,7 @@ angular.module('contactsApp')
                                sortDisplayName: t('contacts', 'Display name'),
                                sortFirstName: t('contacts', 'First name'),
                                sortLastName: t('contacts', 'Last name')
+                               sortLastNameNoComma: t('contacts', 'Last name no comma')
                        };
                }
        };
diff --git a/l10n/en_GB.js b/l10n/en_GB.js
index edfaedc..3f8c903 100644
--- a/l10n/en_GB.js
+++ b/l10n/en_GB.js
@@ -45,6 +45,7 @@ OC.L10N.register(
     "Address" : "Address",
     "(new group)" : "(new group)",
     "Last name" : "Surname",
+    "Last name no comma" : "Surname(No comma)",
     "First name" : "First-name",
     "Additional names" : "Middle names",
     "Prefix" : "Prefix",
diff --git a/l10n/en_GB.json b/l10n/en_GB.json
index 11e62fa..9333a9b 100644
--- a/l10n/en_GB.json
+++ b/l10n/en_GB.json
@@ -43,6 +43,7 @@
     "Address" : "Address",
     "(new group)" : "(new group)",
     "Last name" : "Surname",
+    "Last name no comma" : "Surname(No comma)",
     "First name" : "First-name",
     "Additional names" : "Middle names",
     "Prefix" : "Prefix",
diff --git a/l10n/ru.js b/l10n/ru.js
index 52ffcd0..d3211ab 100644
--- a/l10n/ru.js
+++ b/l10n/ru.js
@@ -45,6 +45,7 @@ OC.L10N.register(
     "Address" : "Адрес",
     "(new group)" : "(новая группа)",
     "Last name" : "Фамилия",
+    "Last name no comma" : "Фамилия(Без запятой)",
     "First name" : "Имя",
     "Additional names" : "Отчество",
     "Prefix" : "Префикс",
diff --git a/l10n/ru.json b/l10n/ru.json
index 4919a5b..ffdc4cd 100644
--- a/l10n/ru.json
+++ b/l10n/ru.json
@@ -43,6 +43,7 @@
     "Address" : "Адрес",
     "(new group)" : "(новая группа)",
     "Last name" : "Фамилия",
+    "Last name no comma" : "Фамилия(Без запятой)",
     "First name" : "Имя",
     "Additional names" : "Отчество",
     "Prefix" : "Префикс",

```

**Comment by L0ric0** [comment]
isn't this already possible if you select sort by second name?

**Comment by skjnldsv** [comment]
@L0ric0 this is about displaying in the contact edit view, not sorting the list :)

Nonetheless, this sounds like a nice feature, but the requests for this are quite low. Currently there a no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.
