### ISSUE TITLE
Problems after update to Version 2.1.1 (Nextcloud Version 13)

### ISSUE THREAD

**Issue by MaxMihawk** [nextcloud/contacts#508]
The layout is broken now after the update (see the left column). Further the pictures of the contacts are not preloaded. They appear after i click on a contact (but only the picture of the contact i´ve clicked).

![unbenannt](https://user-images.githubusercontent.com/19865256/36938113-45af1340-1f1d-11e8-9480-e07e0f08e205.jpg)

Seems, that something is missing. I tried to deactivate and delete the "contacts" app and reinstall it, but the problem still appears. Is their another way to fix this?

**Comment by skjnldsv** [comment]
Please clear your cache :)

**Comment by MaxMihawk** [comment]
The installation is on a webhosting package. I dont have access to a console. How can I clear it?

**Comment by mgrueni** [comment]
@skjnldsv thanx, worked
@MaxMihawk you should clear the cache of your internet browser, how to do depends on which browser you use

**Comment by MaxMihawk** [comment]
Thx a lot. Now it works better. The pictures still dont get preloaded, but i´m fine with it (=without :) ) .

**Comment by skjnldsv** [comment]
@MaxMihawk it will be fixed soon :)
