### ISSUE TITLE
Some problems I had with Gmail export to NextCloud import

### ISSUE THREAD

**Issue by WNYmathGuy** [nextcloud/contacts#516]
I'm certain these glitches are independent of OS, etc.

Minor crap first:
- [x] When typing a new group, theirs an annoying " **(New Group)**" appended to the name of the group if you click the hover label; that doesn't happen if you press the tab key after typing the label. I couldn't find a way to edit it off after, so annoying, but not important.
- [ ] ~~Gmail exports must be in the shitty *.vcf format to import in NextCloud~~. duplicate of #20

Fixable Items:
* The import procedure ran into trouble parsing my data because I use many of the available Gmail contact fields.
  - [x] The escaped semicolon was left untreated. I assume your pre-processing puts in the escapes, but it left them in. This screwed up data in two places. Note fields where I wrote hours of operation in standard time format. After importing `1:30pm` became `1\:30pm`. URL's of any type in Gmail went from `http://somewhere` to the unclickable `http\://somewhere`. I had a lot of manual edits with my 300+ contacts.
  - [x] Comma's caused irregularities in names and addresses. John Smith, Jr., Ph.D., DVM would get really wonky. Maybe their's a way to boundary the parse of a name by looking for the next label of a field before assuming the comma terminated the name. Addresses also had occasional trouble with commas in weird addresses like campus housing. Fields would misalign because of extra unexpected commas.
  - [ ] Non-printing characters. I ran into trouble with this once where data got in a database and the white-space was replaced by an NBSP character due to copy-paste operations on different software. Chaos ensued. Also the new-line vs the end-line. It would behoove you to pre-process the import correcting this before other operations. My Gmail address entries were some with a line break after the street, others with a comma and space. Depending on how I copied an address to paste it into my Gmail contacts caused the NextCloud import to get weird on many addresses. Some went perfect, others would have the whole address in the street field. Sometimes there was no whitespace between the end of the street portion and the start of the city. I had a lot of manual edits to parse them back to good entries.
* Post import issue
  - [ ] Object Labels weren't displaying or permitting editing. I used the "Custom" sooooo many times in Gmail contacts that were so appropriate, and when I first imported, there was just a blank label wherever I used one that wasn't in the standard NextCloud set. I saw the custom labels were preserved when viewing a contact on my mobile device. Since I imported you fixed that display problem because I see them now in a browser, but they seem to be locked types now. I tried to change from address type "SUMMER" for a contact to "Other"; the drop-down lets me select "Other" but the change never sticks.

I'm not sure if this is for you to fix or some other Git repo, but the Circles app won't let me add anybody from my contacts into my circles. I could add a group to a circle, but not a person.

**Comment by Amolith** [comment]
To add to the above, many of the imported contacts from Google were missing names, many of the names were incorrect, and, even after editing names, they all reverted back to the imported name.

**Comment by WNYmathGuy** [comment]
@Amolith just to add a bit more resolution to your comment, my google contacts had selectable ones and other unselectable ones. I could export all or export selected. The distinction I discovered later was the unselectable ones were g+ connections that I put in a circle and may never have been manually added to my address book. The g+ "contacts" can go in the export without names.

Were the ones you had missing names from the selectable cards in your address book?

**Comment by Amolith** [comment]
Whatever issues Contacts used to have, they've since been fixed. My experience was wonderful and I only had to make minor edits to a few of the contacts.

There was still one issue that @WNYmathGuy mentioned and that's escaping website URLs. What he said was:

> URL's of any type in Gmail went from `http://somewhere` to the unclickable `http\://somewhere`

And I'm experiencing this as well.

**Comment by skjnldsv** [comment]
We fixed most of those issues now.
If you still encounter a similar one with the new 3.0.0 version, please create a ticker per issue, this is easier for us to follow and keep track of the progress ;)

Thanks a lot!!
