### ISSUE TITLE
CardDav types

### ISSUE THREAD

**Issue by volker-raschek** [nextcloud/contacts#518]
Hello, 
where can I find a list showing me which information types the contacts application creates by default via the web interface?

For example a contact exported by a Thunderbird plugin named Cardbook.
```bash
BEGIN:VCARD
VERSION:3.0
PRODID:-//Sabre//Sabre VObject 4.1.1//EN
UID:9a8e0c61-4f66-4d01-a8d8-a7482cbf35f2
CATEGORIES:TEAM
N:Mustermann;Max;;;
FN:Max Mustermann
ORG:COMPANY
REV:2018-01-13T13:39:57Z
ADR;TYPE=PREF;TYPE=WORK:;;Musterstraße 1, Musterstadt 12345, Germany
EMAIL;TYPE=PREF;TYPE=WORK:max.mustermann@example.com
X-THUNDERBIRD-ETAG:"0ad4c253ee83ee0c9d01822297482008"
END:VCARD
```
Information Types which I mean are for example in `ADR`, `TYPE=WORK`, `TYPE=PRIVATE`, `CATEGORIES`, `ORG` and all nextclourd specified `X`-Types for example `X-FEDARATED-NEXTCLOUD-ID`.

Problem:
I use DavDroid on my Android to synchronize my contacts. Contacts are created, edited or deleted using Android's Contacts App. I have no influence in the Contacts app on the information types I can store. So are after synchronisations same labels on the web interface empty.

In Thunderbird I use the addon Cardbook to specify my information types. For example, the following is stored there for mail addresses.

| Code | Label |
| ------- | ------- |
| HOME | Privat |
| WORK | Geschäftlich |

I want the same categories, information types and labels over all plattforms!

**Comment by brunt82** [comment]
It is difficult to find the client, which produces the error while using multiple clients at the same moment. I know from experience that Thunderbird + Nextcloud works as expected specified by the CardDAV-RFCs. So currently I don't know any problems about synchronizing the work / home addresses between Cardbook from Thunderbird and Nextcloud.

But I also does not know any problem between DavDroid and Nextcloud. Therefore I suppose the problem may be the local contacts app.

Anyhow I recommend to make some tests between 
1. Thunderbird and Nextcloud, then
2. Android / DavDroid and Nextcloud and at least
3. Thunderbird and Android (via Nextcloud)

Ensure that you always uses the update version (Thunderbird / Cardbook, Nextcloud / Calendar and Davdroid (and maybe Android version). 

Afterwards you should be able to describe the problem more detailed (e.g. "DavDroid does not synchronize HOME address from Android firmware 4.4" or similar.)

**Comment by skjnldsv** [comment]
Quick info: we do not change the types of the properties without user interaction .
We use the default structure android uses, but some other softwares decide that they want to do other ways. Unless you narrow down the issue to really come from nextcloud, I close this :)
