### ISSUE TITLE
Next release

### ISSUE THREAD

**Issue by Peque** [nextcloud/contacts#527]
I see some bugs currently affecting version 2.1.2 have already been fixed. As some of them really affect the usability of the web application, would it be possible to make an earlier 2.1.3 release with the current changes and move remaining open issues to 2.1.4? :innocent:

**Comment by skjnldsv** [comment]
It will arrive this week!

**Comment by skjnldsv** [comment]
@Peque new update is available :)

**Comment by Peque** [comment]
@skjnldsv The new upgrade is working great, thanks! :blush:
