### ISSUE TITLE
Define different levels of access to contacts list - in view of GDPR

### ISSUE THREAD

**Issue by rollanders** [nextcloud/contacts#531]
I have a concern (question/issue) about the full access to the contacts list for all the Nexctcloud users. In the Contacts list there may be some information that not all Nextcloud users should have access to according to the new law (GDPR in english). I would propose the possibility to define users access to selective parts (or not at all) of the Contacts list. 
In the first place I would like to turn off access to the contacts list for some users.

**Comment by skjnldsv** [comment]
Hello!
Every user has its own addressbook. Unless you share one with another, one user's contacts won't be shared with another contact. :)

**Comment by rollanders** [comment]
OK. I did not now that. Very good. So my main concern is not a problem. 

Remains the possibility to share only parts of the details. I would for instance like the possibility to share the name and e-mail adress but not other details (birthdate, adress etc)

**Comment by skjnldsv** [comment]
@rollanders, that on the other hand, it's not possible. :/
unfortunately, we only have a sharing system for addressbooks :)
