### ISSUE TITLE
big Noobie question - iOS app

### ISSUE THREAD

**Issue by rwat1** [nextcloud/contacts#532]
I have the NextCloud App called 'Contacts' enabled in settings of WebUI.

But how do I access the Contacts on the iOS app on iPhone?

I have iPhone contacts is there a way I can sync from my iPhone via the NC App on iOS?

**Comment by skjnldsv** [comment]
Hello! :)
Yes, you can find the documentation here: https://docs.nextcloud.com/server/13/user_manual/pim/sync_ios.html

**Comment by rwat1** [comment]
@skjnldsv 

wow thank you. It's all connected. 

Just One last noobie question, can I make it so:

"iPhone contact list ---> NextCloud server backup"

For example, I have a ton of contacts already in my iPhone, just connected my CaDAV account, but I don't see the contacts on my NextCloud server?

If I add a new contact on iPhone, it doesn't show up on Nextcloud either :(

I also use gmail contacts.

**Comment by skjnldsv** [comment]
Your contacts are probably saved in another addressbook on your ios device.
You need to make sure the contacts are now saved (and created) on the new nextcloud addressbook you just added to your ios :)

Apparently you can't export or move your contacts in ios.
You need to find the trick to do it somehow. I found a guide here: http://www.leawo.com/knowledge/5-ways-to-back-up-and-export-iphone-contacts-to-csv-vcf-html-pst-file-on-pc.html

Which sounds simple with the windows method (if you have win of course :/ )


Once you successfully exported/retrieved your contacts as vcf file, you can import it via nextcloud contacts app. Then it should appear (twice) on you rios (the original ones and the nextcloud ones) :)

Keep me updated!

**Comment by skjnldsv** [comment]
Or if you have the sync with iCloud enabled: https://support.apple.com/kb/PH3606
Teems the best to me
