### ISSUE TITLE
Describe what does Username in the Social Media field means

### ISSUE THREAD

**Issue by Mannshoch** [nextcloud/contacts#535]
How do I get that "Username" the Social Media Field mention?
Example:
![nextcloudsocial_media](https://user-images.githubusercontent.com/7795891/38235669-3309ae22-3722-11e8-8ae3-6b2c7606ce96.png)

**Comment by skjnldsv** [comment]
Hello! :)
@Mannshoch usually, it's the username located after the facebook.com url `https://www.facebook.com/max.muster34`

**Comment by Mannshoch** [comment]
Maybe my English is to easy to get miss-understood. 🤔
 
I'm unsure, If I look on subjects I have to teach some so called Facebook "Pro User". Subjects I think think it's logic and I use Facebook maybe once a month.
