### ISSUE TITLE
Keine Synchronisation mit Outlook 2016

### ISSUE THREAD

**Issue by Andreas111** [nextcloud/contacts#536]
Ich bin leider nicht der englichen Sprache mächig, aber mein Problem ist hier sehr gut beschrieben

I do not speak English, but my problem is very well described here

[https://help.nextcloud.com/t/keine-synchronisation-von-kontakten-moeglich/29868](url)

Andreas

**Comment by skjnldsv** [comment]
Nice! Closing then.
