### ISSUE TITLE
Neue Gruppe / new group - Gruppe umbenennen / rename group

### ISSUE THREAD

**Issue by RealMabuse** [nextcloud/contacts#537]
Sobald ich einem Kontakt eine neue Gruppe (also wirklich neu, nicht in eine bestehende andere) zuweisen möchte wird der Name der Gruppe um den Zusatz "(neue Gruppe)" erweitert.
Ich finde keine Möglichkeit das zu verhindern oder die Gruppe anschließend umzubenennen.

Generell wäre es toll bestehende Gruppen einfach umbenennen zu können.

---

Whenever I want to assign a new group (i.e. really new, not into an existing one) to a contact, the name of the group is extended by the addition"(new group)".
I can't find any way to prevent this or rename the group afterwards.

In general it would be great to be able to rename existing groups.

**Comment by skjnldsv** [comment]
Duplicate of #444

**Comment by joe-pirat** [comment]
das ist im Moment ein bug ( 08/2018  )  es hilft nur eine .vcf datei zu importiren die die den gewünschen Kategorie Namen führt. So lassen sich auch z.B. 2 Notizen Felder erzeugen.
Datei anlgen mit dem Inhalt : 
BEGIN:VCARD
VERSION:3.0
FN:AAA-1
NOTE:1
NOTE:1
TEL;TYPE=WORK,VOICE:2
TEL;TYPE=HOME,VOICE:3
TEL;TYPE=FAX:0351 808
UID:
CATEGORIES:neue-Gruppe
REV:
EMAIL;TYPE=HOME:1@1.de
END:VCARD

--------

als a.vcf   abspeichern und zu den Kontakten importieren
damit wird eine neue Gruppe "neue-Gruppe" angelegt ohne die doofen Klammern.  So lassen sich auch leere Kontakte anlegen so da sman nicht immer die nötigen felder dazuklicken muss - was ich sehr nervig finde.
