### ISSUE TITLE
No contacts after upgrade from Nextcloud 12.0.6 to 13.0.1

### ISSUE THREAD

**Issue by danjde** [nextcloud/contacts#538]
Hi Friends,
after the upgrade from NC 12.0.6 to NC 13.0.1 if I try to access to the contacts obtains only a spinning wheel and no contacts.

All other applications works fine: calendar, task, notes.
My nextcloud is on my Debian Jessie VPS, PHP 5.6.33-0+deb8u1.
No error for apache error.log.

Do you have experience of something like this? How I could debug it?

Many many thanks!

Davide

**Comment by danjde** [comment]
Update:

The problem seems shows up only using the Seamonkey browser (which I usually use).
Now I've try from Firefox 57.0.4 (Quantum) and the contacts show up correctly.
However using debug console, this error are shown: 

`Content Security Policy: Uploading a resource to self has been blocked by page settings (“script-src 'nonce-VHdxTGROV2pLYnNWMW0wVGhxVWxDRXI2MjhpR1ZwU3dIZm9LMm0zR3VRZz06SEYzZE5aZkdVTTF2dFF0VXRJNVZQeTJzdktmd05mWC9WNjVCaVNhc2pFMD0=' 'unsafe-eval'”). Source: ondrop attribute on INPUT element.`


That could be the cause of the problem.

Many thanks again!

Davide

**Comment by skjnldsv** [comment]
Hello! :)
The error shown is not related to this failure. :)
We do not support seamonkey browser, only recents chrome/ium, firefox, safari... etc

**Comment by danjde** [comment]
Ah, ok effectively maybe it's not that important :-)
I just wanted to let you know about this problem, and that "Contacts" on every my many other NC apps is the only one with this issue.

Thank you for the work you do for the community ;-)

Ciao!

Davide

**Comment by Steineklopfer** [comment]
I have the same issue with Chrome 66.0.3359.117.
Contact app only shows an endless spinning wheel and nothing. 

It works on FF though.

**Comment by skjnldsv** [comment]
@Steineklopfer any log in the console?

**Comment by Steineklopfer** [comment]
Well actually no. I didn't check the console yesterday and today it works. Don't know what changed. I even reinstalled Chrome yesterday and it didn't want to work. Maybe because I was able to use it with FF or my phone in the meanwhile? Didn't change anything else...

**Comment by skjnldsv** [comment]
@Steineklopfer Probably a caching issue, we had this a lot lately :)
