### ISSUE TITLE
Add confirmation on addressbook deletion 

### ISSUE THREAD

**Issue by orcu** [nextcloud/contacts#539]
### Steps to reproduce
1. Create a new addressbook by writing down the name and clicking on the arrow on contacts app's settings, shown at the bottom left of the page.
2. Add new contacts into the addressbook
3. Delete newly created addressbook by clicking on the options of the addressbook and hitting delete

### Expected behaviour
To be asked if I am sure to delete the addressbook AND the contacts associated with the addressbook selected

### Actual behaviour
Deletes newly created addressbook and associated contacts directly. There is no easy recovery of contacts after deletion. This risks losing all contacts at once with a single click.

**Comment by skjnldsv** [comment]
> **Thank you for the great application!**

Thanks a lot :)
We'll try to get this very soon ;)
