### ISSUE TITLE
Allow vCard importing into custom AddressBook

### ISSUE THREAD

**Issue by cyphar** [nextcloud/contacts#55]
### Steps to reproduce
1. Create a new AddressBook.
2. Import a `.vcf` file.
3. Note that the AddressBook of all of the contacts is the default `Contacts` addressbook. 

### Expected behaviour
There should be a field or other option to import into a custom AddressBook

### Actual behaviour
There is no such option.

### Server configuration
**Nextcloud version:** (see Nextcloud admin page)
`10.0.1`

**Contacts version:** (see Nextcloud apps page)
`1.4.0.0`

**Updated from an older Nextcloud or fresh install:**
Fresh install

**Comment by j-ed** [comment]
👍 The default address book seems always to be the first one which has been created. Due to the fact that the order of the address books cannot be changed at the moment, it should be possible to configure a default address book in the setting dialog. An additional selection dialog should only be the second choice because it wouldn't allow to import many vcf file in a row.

**Comment by devillemereuil** [comment]
Hi,

Nice to see this addressed (pun not intended), thank you for this!

Is there a possible workaround while this is properly implemented? I'm doing a new install and got all my contacts from Owncloud in separate .vcf files (corresponding to different addressbooks). It's kinda important for me to keep these contacts separate. Anything that could do the trick (like changing the order of the address books manually somewhere)?

Cheers!

**Comment by skjnldsv** [comment]
No there isn't. But this should comes soon enough.

**Comment by devillemereuil** [comment]
Thanks. Since I'm super eager to have this, I can offer my time for some patch testing (should be easy enough to apply a patch on Nextcloud PHP code right?).

**Comment by skjnldsv** [comment]
It will be a simple contact release.
Thanks

**Comment by nursoda** [comment]
Does the solution fully cover https://github.com/nextcloud/contacts/issues/148 ?
What does "3. to review" mean? Can I help here or does it have to be a senior nc dev?

**Comment by skjnldsv** [comment]
Will be fixed in #101

**Comment by Tost69** [comment]
Hi developers,

would'nt it be better to have a checkbox beside the download/link/share/delete buttons to select the addressbook(s) as it is in the Owncloud contacts app?
Only the contacts of the selected addressbooks would be shown and you could also use this to select to which addressbook the vcf entries are added in case of an import.
I migrated my three addressbooks to Nextcloud, each with >100 contacts in it and it's a mess beacuse I cannot separete them visually.

Thanks a lot, great work nevertheless and kind regards, Tom

**Comment by kallegit1950** [comment]
@nursoda How did you get this screen? I tried to import into a NC12 address book but I cannot choose "Import into". I believe I have the latest release. Tried as well on demo.nextcloud.com. Any advice?

**Comment by nursoda** [comment]
True. It's not available in NC12. I tried to enter a new name in the "new addressbook" field and then import, but contacts end up in the first address book, and no new custom address book is created upon importing.

**Comment by devillemereuil** [comment]
If you look on the right of this bug report, you can see it was tagged for 1.5.4. It didn't make it to 1.5.3 which was released a few months ago. Incidentally, the [corresponding pull request](https://github.com/nextcloud/contacts/pull/123) is still open and not merged (review requested?).

I don't know why, but this issue and the next release seem to be stuck. Probably some issue elsewhere or the devs are lacking some free time?

**Comment by ThomasAusSinsheim** [comment]
And it's not available in the nightly_build_2017-07-02. I thought, when this feature would be relaunched, it may be available in a nightly build, but it is not.

**Comment by skjnldsv** [comment]
Update is done, feel free to test #123 and review it there :)
@nursoda, @cyphar, @j-ed

**Comment by nursoda** [comment]
Just did so.
