### ISSUE TITLE
Contacts not working with Chromium, if protected by basic authentication

### ISSUE THREAD

**Issue by jm009** [nextcloud/contacts#553]
### Steps to reproduce
I installed Nextcloud under the Tomcat webserver: https://help.nextcloud.com/t/success-nextcloud-runs-with-jfastcgi-on-tomcat-9-0-1-beta/23935

I found out, the issue can be reproduced with a 'normal' installation under Apache, if I protect the nextcloud directory by adding add the end of the .htaccess file (create user tom in Nextcloud first, use the same password in Nextcloud and with htpasswd):

    AuthUserFile /var/websites/config/nextcloud_users.txt
    AuthName "Nextcloud"
    AuthType Basic
    require user tom

Then create `/var/websites/config/nextcloud_users.txt` like this:

    htpasswd -c -B /var/websites/config/nextcloud_users.txt tom

Of course `/var/websites/config/nextcloud_users.txt` needs to be readable by Apache.

Now open /nextcloud13/index.php/apps/contacts/ in Chromium.
Chromium asks again for username and password, even if username and password were saved in Chromium, and no contacts are listed.

Chromium Developer Tools (Ctrl+Shift+I) shows the following:

```
GET https://null:null@<domain>/nextcloud13/remote.php/dav/addressbooks 401 ()
send @ dav.js?v=fcb5a2f2-0:3738
callee$2$0$ @ dav.js?v=fcb5a2f2-0:3251
tryCatch @ dav.js?v=fcb5a2f2-0:121
[...]
createAccount @ dav.js?v=fcb5a2f2-0:1436
(anonymous) @ dav_service.js:3
instantiate @ angular.min.js?v=fcb5a2f2-0:42
(anonymous) @ angular.min.js?v=fcb5a2f2-0:42
[...]
Gc @ angular.min.js?v=fcb5a2f2-0:21
se @ angular.min.js?v=fcb5a2f2-0:20
(anonymous) @ angular.min.js?v=fcb5a2f2-0:323
j @ core.js?v=fcb5a2f2-0:2
fireWith @ core.js?v=fcb5a2f2-0:2
ready @ core.js?v=fcb5a2f2-0:2
I @ core.js?v=fcb5a2f2-0:2
dav.js?v=fcb5a2f2-0:3738 PROPFIND https://null:null@<domain>/nextcloud13/remote.php/dav/addressbooks 401 ()
send @ dav.js?v=fcb5a2f2-0:3738
callee$2$0$ @ dav.js?v=fcb5a2f2-0:3251
tryCatch @ dav.js?v=fcb5a2f2-0:121
invoke @ dav.js?v=fcb5a2f2-0:294
Gp.(anonymous function) @ dav.js?v=fcb5a2f2-0:330
[...]
createPromise @ dav.js?v=fcb5a2f2-0:3799
createAccount @ dav.js?v=fcb5a2f2-0:1436
(anonymous) @ dav_service.js:3
instantiate @ angular.min.js?v=fcb5a2f2-0:42
(anonymous) @ angular.min.js?v=fcb5a2f2-0:42
[...]
c @ angular.min.js?v=fcb5a2f2-0:21
Gc @ angular.min.js?v=fcb5a2f2-0:21
se @ angular.min.js?v=fcb5a2f2-0:20
(anonymous) @ angular.min.js?v=fcb5a2f2-0:323
j @ core.js?v=fcb5a2f2-0:2
fireWith @ core.js?v=fcb5a2f2-0:2
ready @ core.js?v=fcb5a2f2-0:2
I @ core.js?v=fcb5a2f2-0:2
dav.js?v=fcb5a2f2-0:3746 Uncaught (in promise) Error: Bad status: 401
    at XMLHttpRequest.request.onreadystatechange (dav.js?v=fcb5a2f2-0:3746)
```

**Nextcloud version:** 13.0.2

**Browser:** Version 64.0.3282.119 (Developer Build) built on Debian 9.3, running on Debian 9.4 (64-bit)

**Operating system:**

Nothing in nextcloud.log.

How can I debug that further? Alone the dav.js Stacktrace has about 25 levels, the Stacktrace in angular.js is about twice as high...
If you want access to my example installation, send me a note.
I am wondering, where the null:null in the urls comes from...

**Comment by skjnldsv** [comment]
Hello :)
Can you check if the calendar is working too?

**Comment by jm009** [comment]
Yes, calendar is working, with Chromium and with Firefox.
And, I forgot to tell, contacts are working with Firefox.
The only thing that does not work are Contacts with Chromium.

**Comment by skjnldsv** [comment]
Okay, thanks :)

**Comment by jm009** [comment]
I am not familiar with debugging dav.js and angular.js.
Can this be a bug in Chromium?
