### ISSUE TITLE
contacts not working in Firefox, Chromium, Konqueror for ubuntu 16.04

### ISSUE THREAD

**Issue by kadkarol** [nextcloud/contacts#554]
-->
### Steps to reproduce
1. Clear install nextcloud 13
2. Run Contacts app
3. When I want to add or import addresses, nothing happens, See 
"Contact could not be created" or " Address book could not be created."

**Operating system: 
**Web server:*

**Database:**

**PHP version: 5.6.31 or 7.0.24 or 7.1.10

**Nextcloud version:13.02 clear install
**Contacts version:** 2.1.3

**Signing status:**

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.

`No errors have been found.`

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```


### Client configuration
**Browser: Firefox, Chroime, Chromium, Konkqueror

**Operating system: Kubuntu 16.04, Ubuntu 16.04


#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log from Firefox 59.0.2

`Error: ContactService.create(...) is undefined
ctrl.createContact@http://example.com/apps/contacts/js/public/script.js?v=a78ce0f3-0:1351:3
fn@http://cexample.com/apps/contacts/js/vendor/angular/angular.min.js?v=a78ce0f3-0 line 236 > Function:4:266
b@http://example.com/apps/contacts/js/vendor/angular/angular.min.js?v=a78ce0f3-0:127:472
e@http://example.com/apps/contacts/js/vendor/angular/angular.min.js?v=a78ce0f3-0:281:165
$eval@http://example.com/apps/contacts/js/vendor/angular/angular.min.js?v=a78ce0f3-0:147:65
$apply@http://example.com/apps/contacts/js/vendor/angular/angular.min.js?v=a78ce0f3-0:147:297
compile/</<@http://example.com/apps/contacts/js/vendor/angular/angular.min.js?v=a78ce0f3-0:281:215chmura.akademiasorobanu.pl
dispatch@http://example.com/core/vendor/core.js?v=a78ce0f3-0:3:6414
add/r.handle@http://example.com/core/vendor/core.js?v=a78ce0f3-0:3:3224
angular.js:14199:17
Error: Bad status: 403
dav.js:3746:27
TypeError: contact.addProperty is not a function[Więcej informacji]
newContactButton_controller.js:13:4
Błąd mapy źródła: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
URL zasobu: http://example.com/core/vendor/core.js?v=a78ce0f3-0
URL mapy źródła: purify.min.js.map[Więcej informacji]
TypeError: contact.addProperty is not a function[Więcej informacji]`

```

**Comment by kadkarol** [comment]
Yes, I see

`/**
 * Polyfill from developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Array/find
 */
if (!Array.prototype.find) {
  Array.prototype.find = function(predicate) {
    if (this == null) {
      throw new TypeError('Array.prototype.find called on null or undefined');
    }
    if (typeof predicate !== 'function') {
      throw new TypeError('predicate must be a function');
    }
    var list = Object(this);
    var length = list.length >>> 0;
    var thisArg = arguments[1];
    var value;

    for (var i = 0; i < length; i++) {
      value = list[i];
      if (predicate.call(thisArg, value, i, list)) {
        return value;
      }
    }
    return undefined;
  };
}
/**
 * Polyfill from developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Object/assign
 */ etc...`

**Comment by skjnldsv** [comment]
So, it's strange that you get s a 403.
Care to screenshot your browser network requests, especially the `js` list?

**Comment by kadkarol** [comment]
js
`JQMIGRATE: Migrate is installed, version 1.4.0
/index.php/apps/files/:1 REPORT http://example.com/index.php/apps/files/ 403 (Forbidden)
3dav.js?v=a78ce0f3-0:3746 Uncaught (in promise) Error: Bad status: 403
    at XMLHttpRequest.request.onreadystatechange (dav.js?v=a78ce0f3-0:3746)
request.onreadystatechange @ dav.js?v=a78ce0f3-0:3746
DevTools failed to parse SourceMap: http://example.com/core/vendor/purify.min.js.map
DevTools failed to parse SourceMap: http://example.com/apps/contacts/css/vendor/ui-select/select.min.css.map
dav.js?v=a78ce0f3-0:3738 PUT http://example.com/index.php/apps/files/ 403 (Forbidden)
send @ dav.js?v=a78ce0f3-0:3738
callee$2$0$ @ dav.js?v=a78ce0f3-0:3251
tryCatch @ dav.js?v=a78ce0f3-0:121
invoke @ dav.js?v=a78ce0f3-0:294
Gp.(anonymous function) @ dav.js?v=a78ce0f3-0:330
onFulfilled @ dav.js?v=a78ce0f3-0:3834
(anonymous) @ dav.js?v=a78ce0f3-0:3823
co @ dav.js?v=a78ce0f3-0:3819
send @ dav.js?v=a78ce0f3-0:3229
createObject @ dav.js?v=a78ce0f3-0:3506
createCard @ dav.js?v=a78ce0f3-0:1751
createCard @ dav.js?v=a78ce0f3-0:1516
create @ contact_service.js:230
ctrl.createContact @ newContactButton_controller.js:10
fn @ VM177:4
b @ angular.js:16213
e @ angular.js:26592
$eval @ angular.js:17994
$apply @ angular.js:18094
(anonymous) @ angular.js:26597
dispatch @ core.js?v=a78ce0f3-0:3
r.handle @ core.js?v=a78ce0f3-0:3
newContactButton_controller.js:13 Uncaught (in promise) TypeError: contact.addProperty is not a function
    at newContactButton_controller.js:13
    at Array.forEach (<anonymous>)
    at newContactButton_controller.js:11
(anonymous) @ newContactButton_controller.js:13
(anonymous) @ newContactButton_controller.js:11
Promise.then (async)
ctrl.createContact @ newContactButton_controller.js:10
fn @ VM177:4
b @ angular.js:16213
e @ angular.js:26592
$eval @ angular.js:17994
$apply @ angular.js:18094
(anonymous) @ angular.js:26597
dispatch @ core.js?v=a78ce0f3-0:3
r.handle @ core.js?v=a78ce0f3-0:3
dav.js?v=a78ce0f3-0:3738 PUT http://example.com/index.php/apps/files/ 403 (Forbidden)
send @ dav.js?v=a78ce0f3-0:3738
callee$2$0$ @ dav.js?v=a78ce0f3-0:3251
tryCatch @ dav.js?v=a78ce0f3-0:121
invoke @ dav.js?v=a78ce0f3-0:294
Gp.(anonymous function) @ dav.js?v=a78ce0f3-0:330
onFulfilled @ dav.js?v=a78ce0f3-0:3834
(anonymous) @ dav.js?v=a78ce0f3-0:3823
co @ dav.js?v=a78ce0f3-0:3819
send @ dav.js?v=a78ce0f3-0:3229
createObject @ dav.js?v=a78ce0f3-0:3506
createCard @ dav.js?v=a78ce0f3-0:1751
createCard @ dav.js?v=a78ce0f3-0:1516
create @ contact_service.js:230
ctrl.createContact @ newContactButton_controller.js:10
fn @ VM177:4
b @ angular.js:16213
e @ angular.js:26592
$eval @ angular.js:17994
$apply @ angular.js:18094
(anonymous) @ angular.js:26597
dispatch @ core.js?v=a78ce0f3-0:3
r.handle @ core.js?v=a78ce0f3-0:3
newContactButton_controller.js:13 Uncaught (in promise) TypeError: contact.addProperty is not a function
    at newContactButton_controller.js:13
    at Array.forEach (<anonymous>)
    at newContactButton_controller.js:11
(anonymous) @ newContactButton_controller.js:13
(anonymous) @ newContactButton_controller.js:11
Promise.then (async)
ctrl.createContact @ newContactButton_controller.js:10
fn @ VM177:4
b @ angular.js:16213
e @ angular.js:26592
$eval @ angular.js:17994
$apply @ angular.js:18094
(anonymous) @ angular.js:26597
dispatch @ core.js?v=a78ce0f3-0:3
r.handle @ core.js?v=a78ce0f3-0:3`

**Comment by shawe** [comment]
Same problem here, can I attach any useful information?

**Comment by skjnldsv** [comment]
@kadkarol I would prefer a screenshot of the network tab. Your output is barely readable :p
Thanks

**Comment by kadkarol** [comment]
![request_firefox]
(https://user-images.githubusercontent.com/1473762/39739825-34d29872-5293-11e8-830c-62c711b9bd77.png)

**Comment by skjnldsv** [comment]
Okay, it's the 302 that interests me :)
I now understand why this happens. Could you click the 302 redirect requests and screenshot the full headers please? (request, server and browser's headers )

**Comment by kadkarol** [comment]
![302_nextcloud](https://user-images.githubusercontent.com/1473762/39742567-477825cc-529e-11e8-8648-eb3833e8941c.png)

**Comment by skjnldsv** [comment]
Thanks for your time @kadkarol :)
Could you give the full request url ? It's clipped in your screenshot. Just remove your domain name and replace your userid if you want ;)

**Comment by kadkarol** [comment]
Yes, sorry adres:
http://example/remote.php/dav/addressbooks/users/kadkarol/contacts/d85464b7-8729-411b-be3b-fd1155420425.vcf

My adressbook is clear, no adress:)

**Comment by skjnldsv** [comment]
@kadkarol What do you mean by: your addressbook is clear?

It seems that the ressource you're trying to get/create/edit is not available. Either the addressbook or the contact.
My guess is that your suer is not initiated. Do you have access to a dav browser? Like cadaver?
If so, could you try to log into your dav account and list the available entries?

`cadaver https://cloud.xxxxx.com/remote.php/dav/addressbooks/users/kadkarol
> ls `

**Comment by kadkarol** [comment]
There is only the Contacts directory and 0 elements in it

**Comment by skjnldsv** [comment]
Could you try to delete the default addressbook and create a new one?

**Comment by kadkarol** [comment]
I do not know how to delete the default address book.
I can't create a new one. I see: "Address book could not be created."

**Comment by skjnldsv** [comment]
Either with cadaver or in the contacts app, on the bottom left :)

**Comment by kadkarol** [comment]
No option to delete
![delete_adressbook](https://user-images.githubusercontent.com/1473762/39745210-e5507aa8-52a6-11e8-88f6-943da4ae185b.png)

**Comment by skjnldsv** [comment]
AH yes, because it's the only one left, my bad :)
Then cadaver only: `rmcol contacts`
Reloading the contacts app will automatically trigger a new addressbook creation

**Comment by kadkarol** [comment]
I used a cadaver and deleted contacts.
After logging in to the nextcloud, it's the same. I have just tried with owncloud and it is similar :).

**Comment by kadkarol** [comment]
`dav:/remote.php/dav/addressbooks/users/kadkarol/> rmcol *
[Matching... 1 match.]
Deleting collection `contacts/': redirect to http://chmura.akademiasorobanu.pl/index.php/apps/files/
dav:/remote.php/dav/addressbooks/users/kadkarol/> ls
Listing collection `/remote.php/dav/addressbooks/users/kadkarol/': succeeded.
Coll:   contacts                               0  sty  1  1970
dav:/remote.php/dav/addressbooks/users/kadkarol/> 
`

**Comment by skjnldsv** [comment]
@kadkarol sooo, still not working?
Still getting a redirect?

I don't get why dav is redirecting you. What web server are you using?

**Comment by kadkarol** [comment]
I have a hosting on the server  linux.pl

**Comment by skjnldsv** [comment]
So you don't have access to the webserver config?
Could you try to reach them?

**Comment by kadkarol** [comment]
I can change some php options
If I know what to change, I can ask for it.

**Comment by skjnldsv** [comment]
Well, considering the fact that the data exists in the dav server, the redirection should not happen. Is this a nextcloud hosting or a traditional web hosting?

**Comment by kadkarol** [comment]
Traditional web hosting, and I manualy install nextcloud

**Comment by kadkarol** [comment]
Hi, I found a solution.
You must add an entry to .htaccess
`<Limit GET POST>
order allow,deny
allow from all
</Limit>
<Limit PUT DELETE>
order allow,deny
allow from all
</Limit>`

However, the reason why this entry does not work is not known to me

**Comment by skjnldsv** [comment]
Thanks :)
I guess it was a config issue then ;)
