### ISSUE TITLE
info button within the quick contact search doesn't work

### ISSUE THREAD

**Issue by jones1008** [nextcloud/contacts#557]
### Steps to reproduce
1. click on quick contact search button
2. search for a contact
3. click on the "info"-button behind a found contact

### Expected behaviour
opens contacts app and automatically selects the contact you searched for

### Actual behaviour
opens contacts app and only selects first contact instead of the contact you searched for

## Server configuration detail

**Operating system:** Linux 4.9.58+ SMP PREEMPT Tue Oct 24 08:27:19 UTC 2017 armv7l

**Webserver:** Apache (apache2handler)

**Database:** mysql 10.1.26

**PHP version:** 7.0.19-1
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, apache2handler, mysqlnd, PDO, xml, apcu, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, intl, json, exif, mcrypt, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlrpc, xmlwriter, xsl, zip, Zend OPcache

**Nextcloud version:** 13.0.2 - 13.0.2.1

<details><summary>List of activated apps</summary>

```
Enabled:
 - activity: 2.6.1
 - apporder: 0.4.1
 - audioplayer: 2.3.0
 - bruteforcesettings: 1.0.3
 - calendar: 1.6.1
 - comments: 1.3.0
 - contacts: 2.1.3
 - dav: 1.4.6
 - drawio: 0.8.9
 - federatedfilesharing: 1.3.1
 - federation: 1.3.0
 - files: 1.8.0
 - files_downloadactivity: 1.2.0
 - files_pdfviewer: 1.2.1
 - files_rightclick: 0.8.4
 - files_sharing: 1.5.0
 - files_texteditor: 2.5.1
 - files_trashbin: 1.3.0
 - files_versions: 1.6.0
 - files_videoplayer: 1.2.0
 - firstrunwizard: 2.2.1
 - gallery: 18.0.0
 - groupfolders: 1.2.0
 - impersonate: 1.0.4
 - issuetemplate: 0.3.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.1.0
 - metadata: 0.6.0
 - nextcloud_announcements: 1.2.0
 - notifications: 2.1.2
 - oauth2: 1.1.0
 - password_policy: 1.3.0
 - provisioning_api: 1.3.0
 - rainloop: 5.0.6
 - serverinfo: 1.3.0
 - sharebymail: 1.3.0
 - spreed: 3.2.1
 - survey_client: 1.1.0
 - systemtags: 1.3.0
 - tasks: 0.9.6
 - theming: 1.4.1
 - twofactor_backupcodes: 1.2.3
 - updatenotification: 1.3.0
 - workflowengine: 1.3.0
Disabled:
 - admin_audit
 - encryption
 - files_external
 - user_external
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "***REMOVED SENSITIVE VALUE***"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "13.0.2.1",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "memcache.local": "\\OC\\Memcache\\APCu",
    "mail_smtpmode": "smtp",
    "mail_smtpauthtype": "LOGIN",
    "mail_smtpsecure": "tls",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "587",
    "maintenance": false,
    "theme": "",
    "loglevel": 1,
    "updater.release.channel": "stable",
    "auth.bruteforce.protection.enabled": false,
    "trashbin_retention_obligation": "auto, 180",
    "filelocking.enabled": false,
    "mail_smtpauth": 1
}
```
</details>

**Are you using encryption:** no

## Client configuration

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:59.0) Gecko/20100101 Firefox/59.0

**Comment by skjnldsv** [comment]
Hello @jones1008 
Do you have an error on the top when you get redirected? Like "contact not found" or something like that?

**Comment by tdoerschel** [comment]
I have 2 systems: The bug happens only on system A.
Both systems have NC 15.0.0 and Contacts app 3.0.1

System A: Webhosting (Hetzner), MySQL database, PHP 7.1 with APC and OPCache active
System B: virtual server (Strato), PostgreSQL 11, PHP 7.2 with APCu, OPCache and memcached active.

Also, in System A the contact list does not sort correctly. New contacts are added at the bottom.
Let me know if I help you anyway further.
