### ISSUE TITLE
Contacts in Webinterface from NC are shown with a semicolon (;)

### ISSUE THREAD

**Issue by kangaroo72** [nextcloud/contacts#558]
Hi all ..

I've recognized, that the contacts in NC are shown with a semicolon between last and first name ...
See here ..

![grafik](https://user-images.githubusercontent.com/6906390/40332690-34d23ce8-5d55-11e8-8b45-f845a139344d.png)

Seems not to have an impact, but is annoying ...
Is someone aware of that?

NC 13.02
Contacts 2.1.3

**Comment by skjnldsv** [comment]
Hey @kangaroo72 
Can you post a vcard example? :)

**Comment by skjnldsv** [comment]
@kangaroo72 Do you have any errors in your browser's console log?

**Comment by skjnldsv** [comment]
As a reference, I understand this now that I went on it 4 months later ^^
This is one of the feature linked to the `sorting by` :grin: 
It automatically put the last name in front, separated by a semicolon. But now we don't anymore :)
