### ISSUE TITLE
Changes not saved

### ISSUE THREAD

**Issue by brettferrell** [nextcloud/contacts#559]
### Steps to reproduce
Just like #533 #402 #405 Every single time I try to make a change to a contact in the Contacts app, it says "Contact Could Not Be Saved", making the web interface completely useless.  Fortunately I can create and edit contacts on my iOS devices.
1. Create or edit a contact
2. Change any data
3. Try to Save
4. Weep in disgust

### Expected behaviour
It should save the contact data

### Actual behaviour
It does not save contact data.  I can often get 2 or 3 letters saved if I switch between fields quickly enough....

### Server configuration

**Operating system:** Linux 4.4.0-96-generic #119-Ubuntu SMP Tue Sep 12 14:59:54 UTC 2017 x86_64

**Webserver:** Apache/2.4.18 (Ubuntu) (apache2handler)

**Database:** mysql 10.2.10

**PHP version:** 7.0.30-0ubuntu0.16.04.1
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, apache2handler, redis, mysqlnd, PDO, xml, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, imap, intl, json, ldap, exif, mcrypt, mysqli, pdo_mysql, pdo_pgsql, pdo_sqlite, pgsql, Phar, posix, readline, shmop, SimpleXML, smbclient, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, libsmbclient, Zend OPcache

**Nextcloud version:** 13.0.2 - 13.0.2.1

**Updated from an older Nextcloud/ownCloud or fresh install:** 
Upgraded from 12

**Where did you install Nextcloud from:** 
Started from TechAndMe's VM image
https://www.techandme.se/nextcloud-vm/

<details><summary>Signing status</summary>

Array
</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - activity: 2.6.1
 - admin_audit: 1.3.0
 - admin_notifications: 1.0.1
 - announcementcenter: 3.2.1
 - bruteforcesettings: 1.0.3
 - calendar: 1.6.1
 - caniupdate: 0.1.2
 - comments: 1.3.0
 - contacts: 2.1.3
 - dashboard: 4.0.6
 - dav: 1.4.6
 - drawio: 0.8.9
 - external: 3.0.3
 - federatedfilesharing: 1.3.1
 - federation: 1.3.0
 - files: 1.8.0
 - files_pdfviewer: 1.2.1
 - files_sharing: 1.5.0
 - files_texteditor: 2.5.1
 - files_trashbin: 1.3.0
 - files_versions: 1.6.0
 - files_videoplayer: 1.2.0
 - firstrunwizard: 2.2.1
 - gallery: 18.0.0
 - issuetemplate: 0.3.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.1.0
 - music: 0.6.1
 - nextcloud_announcements: 1.2.0
 - notifications: 2.1.2
 - oauth2: 1.1.0
 - onlyoffice: 1.3.0
 - ownbackup: 17.5.0
 - password_policy: 1.3.0
 - previewgenerator: 1.0.9
 - provisioning_api: 1.3.0
 - quota_warning: 1.2.0
 - ransomware_protection: 1.1.0
 - serverinfo: 1.3.0
 - sharebymail: 1.3.0
 - spreed: 3.2.1
 - survey_client: 1.1.0
 - systemtags: 1.3.0
 - theming: 1.4.3
 - twofactor_backupcodes: 1.2.3
 - twofactor_totp: 1.4.1
 - updatenotification: 1.3.0
 - user_usage_report: 1.0.1
 - workflowengine: 1.3.0
Disabled:
 - encryption
 - files_external
 - user_external
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "localhost",
        "192.168.10.18",
        "ferrellmac.com",
        "ferrellmac.com"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "https:\/\/ferrellmac.com\/",
    "dbtype": "mysql",
    "version": "13.0.2.1",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "maintenance": false,
    "mail_smtpmode": "smtp",
    "log_rotate_size": "10485760",
    "memcache.local": "\\OC\\Memcache\\Redis",
    "filelocking.enabled": true,
    "memcache.distributed": "\\OC\\Memcache\\Redis",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 0,
        "timeout": 0,
        "dbindex": 0,
        "password": "***REMOVED SENSITIVE VALUE***"
    },
    "htaccess.RewriteBase": "\/",
    "loglevel": "2",
    "log_type": "file",
    "logfile": "\/var\/ncdata\/nextcloud.log",
    "logtimezone": "US\/Eastern",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauthtype": "LOGIN",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "587",
    "mail_smtpauth": 1,
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "theme": ""
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

<details><summary>LDAP configuration (delete this part if not used)</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder
Symfony\Component\Console\Exception\CommandNotfoundException There are no commands defined in the ldap namespace

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

## Client configuration

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36 Edge/16.16299

**Operating system:** 
WIn10

## Logs

 CSP14312: Resource violated directive 'script-src 'self' 'unsafe-eval'' in Content-Security-Policy: inline script. Resource will be blocked.

 HTTP500: SERVER ERROR - The server encountered an unexpected condition that prevented it from fulfilling the request.
(XHR)PUT - https://ferrellmac.com:444/remote.php/dav/addressbooks/users/bferrell/contacts/0de04bae-1f41-4f39-b33b-59144a2b0768.vcf

4 HTTP412: PRECONDITION FAILED - The precondition given in one or more of the request header fields evaluated to false when it was tested on the server.
(XHR)PUT - https://ferrellmac.com:444/remote.php/dav/addressbooks/users/bferrell/contacts/0de04bae-1f41-4f39-b33b-59144a2b0768.vcf

 Current window: EdgeExtension_DC5C65101Password

 Current window: ferrellmac.com/apps/contacts

```
Insert your webserver log here 
```
</details>

<details><summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

<details><summary>Browser log</summary>

Insert your browser log here, this could for example include:

	a) The javascript console log
	b) The network log
	c) ...
</details>

----------------------------------------------------------------------

**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**Nextcloud version:** (see Nextcloud admin page)

**Contacts version:** (see Nextcloud apps page)

**Updated from an older Nextcloud or fresh install:**

**Signing status:**

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your instance's installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**

**Operating system:**

**CardDAV-clients:**

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by skjnldsv** [comment]
Hey, thanks for reporting! :)

> HTTP500: SERVER ERROR - The server encountered an unexpected condition that prevented it from fulfilling the request.
(XHR)PUT - https://ferrellmac.com:444/remote.php/dav/addressbooks/users/bferrell/contacts/0de04bae-1f41-4f39-b33b-59144a2b0768.vcf

This is the error. After you get one error 500, the precondition will fail on every edit you do.
Can I see your nextcloud log as well please?
You will probably need to cut out the unwanted parts, but there should be one retarding this error.

**Comment by brettferrell** [comment]
I'd love to give you that, but I don't find any log in /var/www/nextcloud/data for some reason. Is there some place else I should look?

**Comment by skjnldsv** [comment]
Your webserver log maybe?
The nextcloud.log should be into your data directory, if he's not, either the permissions are wrong or the config.php have overridden the correct path :)

**Comment by skjnldsv** [comment]
There is this line:
> Allowed memory size of 536870912 bytes exhausted (tried to allocate 20480 bytes)

You need to increase you php `memory_limit` :)

**Comment by danicotillas** [comment]
@skjnldsv could you tell me where do I have to edit that line and what should it be written down please?

**Comment by skjnldsv** [comment]
@danicotillas depends on what system and software you got :)
What os?

**Comment by skjnldsv** [comment]
Usually it's on /etc/php.ini.
Search for the 'memory_limit'. Try increasing it to something like 64M

**Comment by danicotillas** [comment]
There is not php.ini on that folder. There are the folders for emails apparently.

**Comment by skjnldsv** [comment]
try /etc/php/php.ini. Or search the centos documentation

**Comment by danicotillas** [comment]
:( When I set a php.ini with 64M the site cracks and goes to localhost url.
There is a user.ini on nextcloud root folder and it´s set to 1024MB... but there is still the error that changes are not saved. Any other idea?

**Comment by skjnldsv** [comment]
@danicotillas are you sure you're experiencing the same issue than @brettferrell ?

Do you have any error in your browser console?

**Comment by brettferrell** [comment]
I doubled it, but I still get the could not save error.  It still says memory exhausted at 1024M.  Any idea how much memory this thing needs, or do I just keep plugging away until I find something that works?

**Comment by skjnldsv** [comment]
@brettferrell 1024 is already crazy. I suspect something else.
I'm not the best in this, but you need to debug your mysql instance and find what is responsible for this memory exhaustion :(

**Comment by brettferrell** [comment]
4096 seems to have worked...

**Comment by brettferrell** [comment]
and the only thing running in this VM is a (pretty small) NextCloud instance...

**Comment by skjnldsv** [comment]
@brettferrell that is really strange. :/
Shall we close then? @danicotillas please ensure you have the same issue (see above logs). If so, the fix I provided should be enough.
If not, then create your own issue. Thanks :)
