### ISSUE TITLE
Fields should not cross over two columns

### ISSUE THREAD

**Issue by amittel** [nextcloud/contacts#56]
The group dropdown is cut in half as long as the input field stays on the left side.

If you have enough input fields on the left, like adress and the group input goes to right it's ok again.

**Nextcloud version:** 11 RC1
**Contacts version:** 1.5.2

![chrome_2016-12-08_07-59-20](https://cloud.githubusercontent.com/assets/822396/21000792/03a0887a-bd1d-11e6-968e-4102c40ef9e1.png)

**Comment by irgendwie** [comment]
@PatrycjaPuczko mind looking into it? :blush:

**Comment by jancborchardt** [comment]
Perfect starter issue for @jonatoni @xh3n1 :)

**Comment by jonatoni** [comment]
@irgendwie @amittel can you provide me more information about this issue? I saw that this issue was mentioned even at #31

**Comment by skjnldsv** [comment]
@jonatoni basically, you need to find another way to split the screen in two when large screen. My guess would be flex magic instead of the CSS column, but that is a rigorous process but a good one! 😉

**Comment by irgendwie** [comment]
I remember an PR on upstream, which took care of some multi column stuff - maybe it already solves our problems: https://github.com/owncloud/contacts/pull/600

**Comment by amittel** [comment]
@jonatoni there is not much I can provide. The problem is that the dropbox content remains in the second column when the group input moves to the first. There are no errors or a like. More a design issue I think.

**Comment by olantrust** [comment]
Earlier bug #31 (closed for this later one, unsure why) was clearer about the issue:
Fields should not cross over two columns.

**Comment by rutujasurve94** [comment]
I would like to take this bug up as a part of beginner level bug for Rails Girls Summer of Code 2018

**Comment by skjnldsv** [comment]
Hi @rutujasurve94 :)

This has already been addressed in #481, nonetheless, you can see in https://github.com/nextcloud/contacts/pull/481#issuecomment-365593321 that there is still some work to move from the column system to the grid system. It could be a little more tricky, but I don't know your css level, maybe you can wait for #481 to be merged and then create a new pr for the new system?
