### ISSUE TITLE
HTTP error 415 "Unsupported media type" happens again

### ISSUE THREAD

**Issue by bestouff** [nextcloud/contacts#561]
As specified in #46 the problem happens again since around DAVDroid 1.11.1-ose from f-droid : `Validation error in vCard: REV MUST NOT appear more than once in a VCARD component`; using Nextcloud 12.

**Comment by bestouff** [comment]
Davical log:
```
content://at.bitfire.davdroid.log/debug-info/debug.txt
```

**Comment by skjnldsv** [comment]
Do you use other tool than your phone to edit your contacts?

**Comment by bestouff** [comment]
Yes, GNOME Evolution. The problem seems to come from Davical which adds a REV without replacing the existing one.

**Comment by skjnldsv** [comment]
Unfortunately there is nothing we can do then. :/
It needs to be directly seen with davical or gnome evolution. :(
