### ISSUE TITLE
Changes not saved on Contacts

### ISSUE THREAD

**Issue by danicotillas** [nextcloud/contacts#562]
### Steps to reproduce
1. I create a new contact or modify one
2. It appears the message "Changes not saved"

### Expected behaviour
The changes should be saved automatically

### Actual behaviour
When I write a change or a new contact it simply doesn´t save on the records.

### Server configuration

https://caracol.nodocomun.org/i.php

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Client configuration
**Browser:**
Chrome

**Operating system:**
MacOS

#### Browser log
```
Insert your browser log here, this could for example include:

a) Browser log

core.js?v=2d0ffb9a-15:7 JQMIGRATE: Migrate is installed, version 1.4.0
DevTools failed to parse SourceMap: https://caracol.nodocomun.org/core/vendor/purify.min.js.map
DevTools failed to parse SourceMap: https://caracol.nodocomun.org/apps/contacts/css/vendor/ui-select/select.min.css.map

```

**Comment by skjnldsv** [comment]
Hey again :)
Can you screenshot your network request list after the message appear? (Open dev tools > network tab > there must be one request in red)

**Comment by skjnldsv** [comment]
Perfect! Don't be sorry :)
Can you click on the 412 red request and copy the 'response' tab here please?

**Comment by danicotillas** [comment]
## When I click on dav.js

send | @ | dav.js?v=2d0ffb9a-15:3738
-- | -- | --
  | callee$2$0$ | @ | dav.js?v=2d0ffb9a-15:3251
  | tryCatch | @ | dav.js?v=2d0ffb9a-15:121
  | invoke | @ | dav.js?v=2d0ffb9a-15:294
  | Gp.(anonymous function) | @ | dav.js?v=2d0ffb9a-15:330
  | onFulfilled | @ | dav.js?v=2d0ffb9a-15:3834
  | (anonymous) | @ | dav.js?v=2d0ffb9a-15:3823
  | co | @ | dav.js?v=2d0ffb9a-15:3819
  | send | @ | dav.js?v=2d0ffb9a-15:3229
  | updateObject | @ | dav.js?v=2d0ffb9a-15:3512
  | updateCard | @ | dav.js?v=2d0ffb9a-15:1850
  | updateCard | @ | dav.js?v=2d0ffb9a-15:1524
  | update | @ | contact_service.js:331
  | (anonymous) | @ | contact_service.js:14
  | (anonymous) | @ | angular.js:16696
  | $eval | @ | angular.js:17994
  | $digest | @ | angular.js:17808
  | $apply | @ | angular.js:18102
  | (anonymous) | @ | angular.js:19950
  | f | @ | angular.js:6045
  | (anonymous) | @ | angular.js:6324
  | setTimeout (async) |   |  
  | k.defer | @ | angular.js:6322
  | e | @ | angular.js:19940
  | $$debounceViewValueCommit | @ | angular.js:28482
  | $setViewValue | @ | angular.js:28460
  | l | @ | angular.js:24474
  | dispatch | @ | core.js?v=2d0ffb9a-15:3
  | r.handle | @ | core.js?v=2d0ffb9a-15:3




## When I click on "Name"

Request URL: https://caracol.nodocomun.org/remote.php/dav/addressbooks/users/danicotillas/contacts/0680790f-da73-4bb3-b3b6-fb68e90c7f2c.vcf
Request Method: PUT
Status Code: 412 
Remote Address: 77.104.183.247:443
Referrer Policy: no-referrer
cache-control: no-store, no-cache, must-revalidate
content-encoding: gzip
content-length: 227
content-security-policy: default-src 'none';
content-type: application/xml; charset=utf-8
date: Wed, 30 May 2018 13:48:12 GMT
expires: Thu, 19 Nov 1981 08:52:00 GMT
host-header: 192fc2e7e50945beb8231a492d6a8024
pragma: no-cache
server: nginx
status: 412
vary: Accept-Encoding,User-Agent
x-content-type-options: nosniff
x-download-options: noopen
x-frame-options: SAMEORIGIN
x-permitted-cross-domain-policies: none
x-robots-tag: none
x-xss-protection: 1; mode=block
:authority: caracol.nodocomun.org
:method: PUT
:path: /remote.php/dav/addressbooks/users/danicotillas/contacts/0680790f-da73-4bb3-b3b6-fb68e90c7f2c.vcf
:scheme: https
accept: */*
accept-encoding: gzip, deflate, br
accept-language: es-ES,es;q=0.9,en;q=0.8,it;q=0.7,fr;q=0.6,ca;q=0.5,pt;q=0.4,la;q=0.3
cache-control: no-cache
content-length: 164
content-type: text/vcard;charset=UTF-8
cookie: __Host-nc_sameSiteCookielax=true; __Host-nc_sameSiteCookiestrict=true; oc_sessionPassphrase=UQmn4JhOYPtAiREJ%2Bbnaim%2BFFT4KVnD09C%2BBz8QcyZvM8iLCdzNeqi3wc6zBDD6LEL89MQHvD9RAB2YxBP45c6ZMGeNdqggl5v7wt70jI3XafmcRjMdNaZ57DFBDGAGa; oc6wmartpr1u=5e481aeaa7c8211af53b7040e4c1d764; nc_sameSiteCookielax=true; nc_sameSiteCookiestrict=true
if-match: null
origin: https://caracol.nodocomun.org
pragma: no-cache
requesttoken: v+3W7URA4WWh5h9kC7VExNGijto5p3is+c4HeHYBomA=:iZSE2hANlAnNhSsiacU+tZLU/q1diEHjt71rAUcz41c=
user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36
BEGIN:VCARD
VERSION:3.0
FN:Pedro Barrios
UID:0680790f-da73-4bb3-b3b6-fb68e90c7f2c
REV:20180530T134811Z
EMAIL;TYPE=HOME:pedro@nodocomun.org
ORG:Nodo
END:VCARD

**Comment by skjnldsv** [comment]
@danicotillas sorry, There was too much sensible data. I edited your post.
I'm interested in the response tab visible after you clicked the failed request :)

**Comment by danicotillas** [comment]
Oh, thanks! What would be the response tab exactly?

**Comment by skjnldsv** [comment]
![capture d ecran_2018-05-30_20-45-42](https://user-images.githubusercontent.com/14975046/40740964-7095bc90-644a-11e8-9967-cc31d7884ccb.png)

**Comment by danicotillas** [comment]
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\PreconditionFailed</s:exception>
  <s:message>An If-Match header was specified, but none of the specified the ETags matched.</s:message>
  <s:header>If-Match</s:header>
</d:error>

**Comment by skjnldsv** [comment]
Okay, thanks! :)
Now, you seems to have one successful request before the faile done, can you copy me the requests headers? I'm interested in the two etag and oc-etag response

![capture d ecran_2018-05-30_20-49-58](https://user-images.githubusercontent.com/14975046/40741187-22641818-644b-11e8-9bd7-eebeab5c3a11.png)


Also, I see you have an auto completion happening on your failed request, can I see the requets payload (you can edit the sensitive data like mail, phone, whataver) :)
![capture d ecran_2018-05-30_20-51-40](https://user-images.githubusercontent.com/14975046/40741241-51927d46-644b-11e8-8369-e75e06f2c713.png)

**Comment by danicotillas** [comment]
Request URL: https://caracol.nodocomun.org/remote.php/dav/addressbooks/users/danicotillas/contacts/5e06bf89-13d6-490f-9bbd-ad64b5332ac0.vcf
Request Method: PUT
Status Code: 412 
Remote Address: 77.104.183.247:443
Referrer Policy: no-referrer
cache-control: no-store, no-cache, must-revalidate
content-encoding: gzip
content-length: 227
content-security-policy: default-src 'none';
content-type: application/xml; charset=utf-8
date: Wed, 30 May 2018 18:54:48 GMT
expires: Thu, 19 Nov 1981 08:52:00 GMT
host-header: 192fc2e7e50945beb8231a492d6a8024
pragma: no-cache
server: nginx
status: 412
vary: Accept-Encoding,User-Agent
x-content-type-options: nosniff
x-download-options: noopen
x-frame-options: SAMEORIGIN
x-permitted-cross-domain-policies: none
x-robots-tag: none
x-xss-protection: 1; mode=block
:authority: caracol.nodocomun.org
:method: PUT
:path: /remote.php/dav/addressbooks/users/danicotillas/contacts/5e06bf89-13d6-490f-9bbd-ad64b5332ac0.vcf
:scheme: https
accept: */*
accept-encoding: gzip, deflate, br
accept-language: es-ES,es;q=0.9,en;q=0.8,it;q=0.7,fr;q=0.6,ca;q=0.5,pt;q=0.4,la;q=0.3
cache-control: no-cache
content-length: 211
content-type: text/vcard;charset=UTF-8
cookie: __Host-nc_sameSiteCookielax=true; __Host-nc_sameSiteCookiestrict=true; oc_sessionPassphrase=UQmn4JhOYPtAiREJ%2Bbnaim%2BFFT4KVnD09C%2BBz8QcyZvM8iLCdzNeqi3wc6zBDD6LEL89MQHvD9RAB2YxBP45c6ZMGeNdqggl5v7wt70jI3XafmcRjMdNaZ57DFBDGAGa; oc6wmartpr1u=5e481aeaa7c8211af53b7040e4c1d764; nc_sameSiteCookielax=true; nc_sameSiteCookiestrict=true
if-match: null
origin: https://caracol.nodocomun.org
pragma: no-cache
requesttoken: V7tWRORB/D/HtRasUFnNFi4hqszoZVexIEQ/WwPLLN8=:YcIEc7AMiVOr1iLqMim3Z21X2ruMSm7+bjdTIjL5beg=
user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.181 Safari/537.36
BEGIN:VCARD
VERSION:3.0
FN:Raquel
UID:5e06bf89-13d6-490f-9bbd-ad64b5332ac0
REV:20180530T185448Z
EMAIL;TYPE=HOME:xxxxx@xxxx.com
CATEGORIES:Whatever
ORG:Whatever
TITLE:Whoever
END:VCARD

**Comment by skjnldsv** [comment]
>if-match: null


That's what I'm interested about, can you post the **successful** request headers (see my previous message) especially the etag and oc-etag part please.

**Comment by danicotillas** [comment]
A succesful one:

BEGIN:VCARD
VERSION:3.0
FN:Raquel
UID:5e06bf89-13d6-490f-9bbd-ad64b5332ac0
REV:20180530T185442Z
EMAIL;TYPE=HOME:xxxxx@xxxx.com
CATEGORIES:Whatever
ORG:Whoever
TITLE:Adm
END:VCARD

**Comment by skjnldsv** [comment]
Amazing!
This is a duplicate of #257 Which has been fixed.
I need to publish a new release :)

Closing since it's fixed but not released

**Comment by danicotillas** [comment]
So.... what should I do noW???

**Comment by skjnldsv** [comment]
Wait for a new release of contacts! :)

**Comment by skjnldsv** [comment]
@danicotillas New release published just for you ;)
Update when you'll get the notification that it's available to download :)

**Comment by danicotillas** [comment]
@skjnldsv Your heart doesn´t fit in your chest cause it´s so huge! Thanks a million!
