### ISSUE TITLE
Error in german translation

### ISSUE THREAD

**Issue by hgraeber** [nextcloud/contacts#567]
The german translations of "Specify a relationship between you and the entity represented by this vCard." and "Specify a relationship between another entity and the entity represented by this vCard." are swapped.

**Comment by xh3n1** [comment]
@hgraeber The translations are handled on transifex: https://www.transifex.com/nextcloud/nextcloud/contacts/
Please join there to fix it directly :)

**Comment by jnagler** [comment]
Done today. Not sure when/how this will be reviewed/propagated to the next release.

**Comment by skjnldsv** [comment]
@jnagler this is automatically pushed to this repo.
So next release :)
