### ISSUE TITLE
Self Managed Contacts

### ISSUE THREAD

**Issue by gnilebein** [nextcloud/contacts#568]
This is a feature request and not a bug report.

It would be nice if the contacts app give you the possibility to invite your contacts to review their contact data. 

For example you can send an invitation link via mail to one or more of your contacts. Now your contact can review their data and change the data via web frontend. But the changed data has to be approved by the next cloud user before the data get finally stored in database.

**Comment by skjnldsv** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there a no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.
