### ISSUE TITLE
Add end to end encryption support

### ISSUE THREAD

**Issue by mejo-** [nextcloud/contacts#569]
Now that Nextcloud has end to end (e2e) encryption support, it would be awesome to extend that support to the Contacts and Calendar apps.

One would have to agree on a standard for delivering encrypted content via cardDAV/calDAV, implement it server-side in the Nextcloud apps and then coordinate with the cardDAV/calDAV clients (e.g. DAVdroid, Thunderbird Lightning, ...) to make them support the new e2e feature.

Do you think, that's feasible?

Certainly, the web applications no longer would work with e2e encryption, but that's an acceptable tradeoff in my opinion. It's quite common to merely use the contacts & calendars apps for syncing via cardDAV/calDAV and don’t use the web interface at all.

There's a related discussion on help.nextcloud.com: [Add end-to-end encryption for contacts & calendar](https://help.nextcloud.com/t/add-end-to-end-encryption-for-contacts-calendar/28879)

**Comment by skjnldsv** [comment]
Hey @mejo- 
Thanks for your suggestion!
Unfortunately, this would require a significant amount of work on our webdav server. 

Sorry :)

**Comment by rugk** [comment]
But it's worth it, please re-consider it. Also the "normal" e2e crypto for files required a "significant amount of work", so yeah…

**Comment by skjnldsv** [comment]
@rugk Could you create the request in the server repo then :)
Maybe people with more knowledge on the e2e integration will have better answers

**Comment by rugk** [comment]
Done: https://github.com/nextcloud/server/issues/9782
