### ISSUE TITLE
Move Contact to Different Addressbook Fails in Calendar Birthdays

### ISSUE THREAD

**Issue by bj-github** [nextcloud/contacts#571]
### Steps to reproduce
1. Move Contact to a different Address Book

### Expected behaviour
It happens without error

### Actual behaviour
It generates an error message in the log: "Sabre\DAV\Exception\BadRequest: Calendar object with uid already exists in this calendar collection."

## Server configuration detail

**Operating system:** Linux 2.6.32-696.30.1.el6.x86_64 #1 SMP Tue May 22 03:28:18 UTC 2018 x86_64

**Webserver:** Apache (fpm-fcgi)

**Database:** mysql 10.1.33

**PHP version:** 7.1.18
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, cgi-fcgi, bcmath, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, iconv, imap, intl, json, exif, mcrypt, mysqlnd, PDO, Phar, posix, SimpleXML, sockets, sqlite3, tokenizer, xml, xmlwriter, xsl, zip, mysqli, pdo_mysql, pdo_sqlite, wddx, xmlreader, Zend OPcache

**Nextcloud version:** 13.0.2 - 13.0.2.1

**Updated from an older Nextcloud/ownCloud or fresh install:** Originally a fresh install of NextCloud 12.

**Where did you install Nextcloud from:** NextCloud via the Web Installer

<details><summary>List of activated apps</summary>

```
Enabled:
 - activity: 2.6.1
 - admin_audit: 1.3.0
 - bruteforcesettings: 1.0.3
 - calendar: 1.6.1
 - comments: 1.3.0
 - contacts: 2.1.5
 - dav: 1.4.6
 - federatedfilesharing: 1.3.1
 - files: 1.8.0
 - files_pdfviewer: 1.2.1
 - files_sharing: 1.5.0
 - files_texteditor: 2.5.1
 - files_trashbin: 1.3.0
 - files_versions: 1.6.0
 - firstrunwizard: 2.2.1
 - gallery: 18.0.0
 - issuetemplate: 0.3.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.1.0
 - metadata: 0.6.0
 - nextcloud_announcements: 1.2.0
 - notifications: 2.1.2
 - oauth2: 1.1.0
 - password_policy: 1.3.0
 - provisioning_api: 1.3.0
 - serverinfo: 1.3.0
 - sharebymail: 1.3.0
 - spreed: 3.2.2
 - systemtags: 1.3.0
 - theming: 1.4.5
 - twofactor_backupcodes: 1.2.3
 - updatenotification: 1.3.0
 - workflowengine: 1.3.0
Disabled:
 - encryption
 - federation
 - files_external
 - files_videoplayer
 - survey_client
 - user_external
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "*REMOVED by submitter*"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "https:\/\/*REMOVED by submitter*",
    "dbtype": "mysql",
    "version": "13.0.2.1",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "php",
    "mail_smtpauthtype": "LOGIN",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "maintenance": false,
    "theme": "",
    "loglevel": 2,
    "updater.release.channel": "stable"
}
```
</details>

**Are you using external storage, if yes which one:** local
**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** No

*(No LDAP)*

</details>

## Client configuration

**Browser:** Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0

**Operating system:** Linux 4.16.12

## Logs

<details><summary>Nextcloud log</summary>

    Sabre\DAV\Exception\BadRequest: Calendar object with uid already exists in this calendar collection.

    .../apps/dav/lib/CalDAV/BirthdayService.php - line 309: OCA\DAV\CalDAV\CalDavBackend->createCalendarObject('9', 'Shared with Ann...', 'BEGIN VCALENDAR...')
    .../apps/dav/lib/CalDAV/BirthdayService.php - line 99: OCA\DAV\CalDAV\BirthdayService->updateCalendar('321f6696-b719-4...', 'BEGIN VCARD\r\nVE...', Array, '9', Array)
    .../apps/dav/lib/AppInfo/Application.php - line 119: OCA\DAV\CalDAV\BirthdayService->onCardChanged('18', '321f6696-b719-4...', 'BEGIN VCARD\r\nVE...')
    [internal function] OCA\DAV\AppInfo\Application->OCA\DAV\AppInfo\{closure}(*** sensitive parameters replaced ***)
    .../3rdparty/symfony/event-dispatcher/EventDispatcher.php - line 212: call_user_func(Object(Closure), Object(Symfony\Component\EventDispatcher\GenericEvent), '\\OCA\\DAV\\CardDA...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
    .../3rdparty/symfony/event-dispatcher/EventDispatcher.php - line 44: Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, '\\OCA\\DAV\\CardDA...', Object(Symfony\Component\EventDispatcher\GenericEvent))
    .../apps/dav/lib/CardDAV/CardDavBackend.php - line 633: Symfony\Component\EventDispatcher\EventDispatcher->dispatch('\\OCA\\DAV\\CardDA...', Object(Symfony\Component\EventDispatcher\GenericEvent))
    .../3rdparty/sabre/dav/lib/CardDAV/AddressBook.php - line 144: OCA\DAV\CardDAV\CardDavBackend->createCard('18', '321f6696-b719-4...', 'BEGIN VCARD\r\nVE...')
    .../3rdparty/sabre/dav/lib/DAV/Tree.php - line 314: Sabre\CardDAV\AddressBook->createFile('321f6696-b719-4...', 'BEGIN VCARD\r\nVE...')
    .../3rdparty/sabre/dav/lib/DAV/Tree.php - line 130: Sabre\DAV\Tree->copyNode(Object(Sabre\CardDAV\Card), Object(OCA\DAV\CardDAV\AddressBook), '321f6696-b719-4...')
    .../3rdparty/sabre/dav/lib/DAV/Tree.php - line 161: Sabre\DAV\Tree->copy('addressbooks/us...', 'addressbooks/us...')
    .../3rdparty/sabre/dav/lib/DAV/CorePlugin.php - line 642: Sabre\DAV\Tree->move('addressbooks/us...', 'addressbooks/us...')
    [internal function] Sabre\DAV\CorePlugin->httpMove(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
    .../3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105: call_user_func_array(Array, Array)
    .../3rdparty/sabre/dav/lib/DAV/Server.php - line 479: Sabre\Event\EventEmitter->emit('method MOVE', Array)
    .../3rdparty/sabre/dav/lib/DAV/Server.php - line 254: Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
    .../apps/dav/lib/Server.php - line 283: Sabre\DAV\Server->exec()
    .../apps/dav/appinfo/v2/remote.php - line 35: OCA\DAV\Server->exec()
    .../remote.php - line 164: require_once('/.../p...')
    {main}

</details>

**Comment by skjnldsv** [comment]
@bj-github this is not related to the contacts app.
Could you reopen this here please? https://github.com/nextcloud/server/issues
