### ISSUE TITLE
upload of contacts does not work anymore

### ISSUE THREAD

**Issue by NESC1US** [nextcloud/contacts#576]
### Steps to reproduce
1. install the contacts
2. import vcf contacts
3. importing into shows up and stays forever

### Expected behaviour
imported contacts 

### Actual behaviour
importing into dialog shows and stays forever, nothing is loaded, firebug shows few errors regarding angularjs, why is this loaded externally? is there not enough space after installing 297MB of the nextcloud? ...why the heck would anyone want to install their own instance of this server and then allow loading of third-party scripts?

### Server configuration

**Operating system**: linux

**Web server:** nginx

**Database:** see bellow

**PHP version:** 7.2

**Nextcloud version:** (see Nextcloud admin page)

**Contacts version:** see List of activated apps bellow

**Updated from an older Nextcloud or fresh install:** fresh, it used to work about a week ago in another instance.

**Signing status:**

```
No errors have been found.
```

**List of activated apps:**

```
Enabled:
  - activity: 2.6.1
  - admin_audit: 1.3.0
  - bookmarks: 0.11.0
  - bruteforcesettings: 1.1.0
  - calendar: 1.6.1
  - camerarawpreviews: 0.5.3
  - comments: 1.3.0
  - contacts: 2.1.5
  - dav: 1.4.7
  - federatedfilesharing: 1.3.1
  - files: 1.8.0
  - files_rightclick: 0.8.4
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trackdownloads: 1.2.2
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - firstrunwizard: 2.2.1
  - gallery: 18.0.0
  - groupfolders: 1.2.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - mail: 0.8.2
  - music: 0.7.0
  - news: 12.0.4
  - notifications: 2.1.2
  - oauth2: 1.1.1
  - password_policy: 1.3.0
  - previewgenerator: 1.0.9
  - provisioning_api: 1.3.0
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - systemtags: 1.3.0
  - tasks: 0.9.6
  - theming: 1.4.5
  - twofactor_backupcodes: 1.2.3
  - updatenotification: 1.3.0
  - user_ldap: 1.3.1
  - workflowengine: 1.3.0
Disabled:
  - encryption
  - federation
  - files_external
  - files_pdfviewer
  - nextcloud_announcements
  - survey_client
  - user_external

```

**Nextcloud configuration:**

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nimbus.perfugium.net"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/nextcloud.example.com",
        "dbtype": "mysql",
        "version": "13.0.4.0",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "maintenance": false
    }
}

```

**Are you using external storage, if yes which one:** nope

**Are you using encryption:** https? yes, disk encryption? no

**Are you using an external user-backend, if yes which one:** no
### Client configuration
**Browser:** see Nextcloud log bellow

**Operating system:**  see Nextcloud log bellow

**CardDAV-clients:** none yet

#### Web server error log
```
there is no error relevant error (nothing today)
```

#### Nextcloud log (data/nextcloud.log)
```
{"reqId":"KxfC1qxggGcqg53ZOogo","level":4,"time":"2018-06-29T12:25:45+00:00","remoteAddr":"193.29.76.166","user":"nescius","app":"webdav","method":"MKCOL","url":"/remote.php/dav/addressbooks/users/nescius/Contacts","message":"Exception: {\"Exception\":\"Sabre\DAV\Exception\MethodNotAllowed\",\"Message\":\"The resource you tried to create already exists\",\"Code\":0,\"Trace\":\"#0 /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php(594): Sabre\DAV\Server->createCollection('addressbooks/us...', Object(Sabre\DAV\MkCol))\
#1 [internal function]: Sabre\DAV\CorePlugin->httpMkcol(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))\
#2 /var/www/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\
#3 /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php(479): Sabre\Event\EventEmitter->emit('method:MKCOL', Array)\
#4 /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php(254): Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))\
#5 /var/www/nextcloud/apps/dav/lib/Server.php(287): Sabre\DAV\Server->exec()\
#6 /var/www/nextcloud/apps/dav/appinfo/v2/remote.php(35): OCA\DAV\Server->exec()\
#7 /var/www/nextcloud/remote.php(164): require_once('/var/www/nextcl...')\
#8 {main}\",\"File\":\"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php\",\"Line\":1181}","userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0","version":"13.0.4.0"}

```

#### Browser log
a) The javascript console log

```
JQMIGRATE: Migrate is installed, version 1.4.0
core.js:7:542
Source map error: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Resource URL: https://nextcloud.example.com/apps/contacts/js/vendor/angular/angular.min.js?v=md69t77-0
Source Map URL: angular.min.js.map[Learn More]
Source map error: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Resource URL: https://nextcloud.example.com/core/vendor/core.js?v=md69t77-0
Source Map URL: purify.min.js.map[Learn More]
Source map error: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Resource URL: https://nextcloud.example.com/apps/contacts/js/vendor/angular-route/angular-route.min.js?v=md69t77-0
Source Map URL: angular-route.min.js.map[Learn More]
Source map error: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Resource URL: https://nextcloud.example.com/apps/contacts/js/vendor/angular-cache/angular-cache.min.js?v=md69t77-0
Source Map URL: angular-cache.min.map[Learn More]
Source map error: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Resource URL: https://nextcloud.example.com/apps/contacts/js/vendor/angular-sanitize/angular-sanitize.min.js?v=md69t77-0
Source Map URL: angular-sanitize.min.js.map[Learn More]
Source map error: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Resource URL: https://nextcloud.example.com/apps/contacts/css/vendor/ui-select/select.min.css?v=md69t77-0
Source Map URL: select.min.css.map[Learn More]
Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src”). Source: onloadedmetadata attribute on SPAN eleme....
contacts
Error: [$rootScope:inprog] http://errors.angularjs.org/1.5.11/$rootScope/inprog?p0=%24apply
G/<@https://nextcloud.example.com/apps/contacts/js/vendor/angular/angular.min.js?v=md69t77-0:6:426
n@https://nextcloud.example.com/apps/contacts/js/vendor/angular/angular.min.js?v=md69t77-0:139:271
$apply@https://nextcloud.example.com/apps/contacts/js/vendor/angular/angular.min.js?v=md69t77-0:147:274
link/</</</</<@https://nextcloud.example.com/apps/contacts/js/public/script.js?v=md69t77-0:655:9
this.import@https://nextcloud.example.com/apps/contacts/js/public/script.js?v=md69t77-0:2588:6
link/</</</<@https://nextcloud.example.com/apps/contacts/js/public/script.js?v=md69t77-0:632:8
$eval@https://nextcloud.example.com/apps/contacts/js/vendor/angular/angular.min.js?v=md69t77-0:147:65
$apply@https://nextcloud.example.com/apps/contacts/js/vendor/angular/angular.min.js?v=md69t77-0:147:297
link/</</<@https://nextcloud.example.com/apps/contacts/js/public/script.js?v=md69t77-0:625:7
angular.min.js:119:446
Error: [$rootScope:inprog] http://errors.angularjs.org/1.5.11/$rootScope/inprog?p0=%24apply
G/<@https://nextcloud.example.com/apps/contacts/js/vendor/angular/angular.min.js?v=md69t77-0:6:426
n@https://nextcloud.example.com/apps/contacts/js/vendor/angular/angular.min.js?v=md69t77-0:139:271
$digest@https://nextcloud.example.com/apps/contacts/js/vendor/angular/angular.min.js?v=md69t77-0:143:500
$apply@https://nextcloud.example.com/apps/contacts/js/vendor/angular/angular.min.js?v=md69t77-0:147:361
link/</</</</<@https://nextcloud.example.com/apps/contacts/js/public/script.js?v=md69t77-0:655:9
this.import@https://nextcloud.example.com/apps/contacts/js/public/script.js?v=md69t77-0:2588:6
link/</</</<@https://nextcloud.example.com/apps/contacts/js/public/script.js?v=md69t77-0:632:8
$eval@https://nextcloud.example.com/apps/contacts/js/vendor/angular/angular.min.js?v=md69t77-0:147:65
$apply@https://nextcloud.example.com/apps/contacts/js/vendor/angular/angular.min.js?v=md69t77-0:147:297
link/</</<@https://nextcloud.example.com/apps/contacts/js/public/script.js?v=md69t77-0:625:7
angular.min.js:119:446
```

**Comment by skjnldsv** [comment]
> importing into dialog shows and stays forever, nothing is loaded, firebug shows few errors regarding angularjs, why is this loaded externally? is there not enough space after installing 297MB of the nextcloud? ...why the heck would anyone want to install their own instance of this server and then allow loading of third-party scripts?

We do not load any external scripts.
Angular errors of Source Map are unrelated to this issue.

The issue in your Nextcloud log is related to the creation of an addressbook which already exists.

On your developer tools, after an import error, could you check if you have a failing request (in the network tab)?
The failed entry should be in red. Thanks

**Comment by 2xlink** [comment]
I have the same issue with Nextcloud 13, maybe I can help out (I use the latest docker image with apache).

The network tab does not seem to show anything broken, every request gives a 200 or 207. (see screenshot).

I am also getting some warnings about an empty JSON, but this might not be related to the issue …

    Source map error: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
    Resource URL: http://192.168.178.50:8080/custom_apps/contacts/js/vendor/angular-route/angular-route.min.js?v=6f0ea3ae-0
    Source Map URL: angular-route.min.js.map[Learn More]

I also checked if the CSP error has something to do with it, but even with CSP disabled it does not work.



![screenshot from 2018-07-07 11-58-25](https://user-images.githubusercontent.com/8763936/42409654-dff1648a-81dd-11e8-8d33-2d4f00dd1970.png)

Thanks for your support :)

**Comment by skjnldsv** [comment]
@2xlink please open your own issue otherwise it's going to be difficult :)

**Comment by rob1998** [comment]
@skjnldsv I installed Nextcloud today using Linuxserver's Docker on UnRAID and experiencing the same problem.
I'm getting the same error in my browsers, but have no failing network request.

Are you using external storage, if yes which one: nope
Are you using encryption: https? yes, disk encryption? no
Are you using an external user-backend, if yes which one: no

Client configuration
Browser: Firefox, Chrome
Operating system: UnRAID
CardDAV-clients: none

**Comment by skjnldsv** [comment]
@rob1998 please open you rown issue unless you have an exact match with an existing/closed one.

**Comment by rubo77** [comment]
shouldn't be there an issue where to collect this error?

I also cannot import my 800 contacts VCF file exported from android 7.

there are more  reportings here:

- https://github.com/owncloud/contacts/issues/588
- https://github.com/nextcloud/server/issues/5478

**Comment by 2xlink** [comment]
See [this comment](https://github.com/nextcloud/contacts/issues/433#issuecomment-356301406) to work around this bug. 
The problem is probably that nextcloud does not support VCard versions < 3.0 and fails silently. There should probably at least be an error message so that people can troubleshoot easier (or even better: some internal conversion like [this script here](https://github.com/jowave/vcard2to3)).

**Comment by KozakIvan** [comment]
Use https://play.google.com/store/apps/details?id=by.androld.contactsvcf to import Android Contacts, it's store in VCARD 3.0, then import to Nextcloud

**Comment by skjnldsv** [comment]
Upload is fixed and will now continue if errors
