### ISSUE TITLE
Unable to add, remove or change contact entries

### ISSUE THREAD

**Issue by fossxplorer** [nextcloud/contacts#580]
### Steps to reproduce
1.Click on "+ New Contact" or try to delete an existing contact entry
2. See the spinner spins for ever for the former and 500 for the latter
3. 

### Expected behaviour
Able to create, edit and remove contacts

### Actual behaviour
1. Spins for ever, unable to create a new contact. When removing a contact:
NOTICE: PHP message: PHP Fatal error:  Allowed memory size of 1073741824 bytes exhausted (tried to allocate 84 bytes) in 3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php on line 128.
Even with 5GB of memory for the PHP-FPM process, it fails.

### Server configuration

**Operating system**:
CentOS 7
**Web server:**
Nginx

**Database:**
MariaDB 10
**PHP version:**
5.6.x
**Nextcloud version:** (see Nextcloud admin page)
12.0.9
**Contacts version:** (see Nextcloud apps page)
2.1.5
**Updated from an older Nextcloud or fresh install:**
Updated from 11

**List of activated apps:**

php occ app:list
Enabled:
  - activity: 2.5.2
  - admin_audit: 1.2.0
  - admin_migrate: 0.1
  - admin_notifications: 1.0.1
  - announcementcenter: 3.1.1
  - bookmarks: 0.11.0
  - bruteforcesettings: 1.1.0
  - calendar: 1.5.8
  - comments: 1.2.0
  - contacts: 2.1.5
  - dav: 1.3.1
  - deck: 0.3.1
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_external: 1.3.0
  - files_markdown: 2.0.4
  - files_pdfviewer: 1.1.2
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - gallery: 17.0.0
  - lookup_server_connector: 1.0.0
  - mozilla_sync: 1.4
  - music: 0.7.0
  - news: 11.0.5
  - notes: 2.3.2
  - oauth2: 1.0.6
  - ocsms: 1.13.1
  - ownnote: 1.08
  - passman: 2.1.4
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - systemtags: 1.2.0
  - tasks: 0.9.6
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0

**Nextcloud configuration:**
Pretty standard config with Redis, APU etc.

**Are you using external storage, if yes which one:** local/smb/sftp/...
No
**Are you using encryption:** yes/no
No
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
**Browser:**
Chrome, Firefox
**Operating system:**
Linux/RHEL7
**CardDAV-clients:**
Web and Thunderbird via SoGO
#### Web server error log
2018/07/17 14:08:21 [error] 9744#0: *72983675 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Allowed memory size of 1073741824 bytes exhausted (tried to allocate 9 bytes) in 3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php on line 128" while reading response header from upstream, client: IP-ADDR, server: domain.com", request: "DELETE /remote.php/dav/addressbooks/users/user01/my_contacts_new/b2d894c6-1aa2-4ebd-9e53-23bc4c8e47b8.vcf HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm/.sock:", host: 

#### Nextcloud log (data/nextcloud.log)
Nothing related to this issue in the NC log.

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by skjnldsv** [comment]
Can you try to upgrade to 13?
I have no idea what can cause that except an issue from server :/

**Comment by fossxplorer** [comment]
Hi,
unfortunately, an upgrade to version 13 need planning as it's a pretty big instance with many thousands users. The size of the DB is the major concern due to schema changes that might take very very long time. So it's not planned nor tested yet.
Could of course be a server settings issue, but the settings although didn't change from 11 to 12. 
It's Nginx proxy server <-> Nginx web server with PHP-FPM and MariaDB.

And yes, new users are affected as well:
- adding new contact: you get a message in the UI "Contacts could not be saved":
Console: 
 PUT remote.php/dav/addressbooks/users/user1/default/4e5857e8-a273-4f41-b2b8-49d77d4a8034.vcf 500 (Internal Server Error) dav.js?v=a64a05af-15:3738
PUT remote.php/dav/addressbooks/users/user1/default/4e5857e8-a273-4f41-b2b8-49d77d4a8034.vcf 412 (Precondition failed) dav.js?v=a64a05af-15:3738

**Comment by skjnldsv** [comment]
No error in the nextcloud log?
Nothing in the db? Space still available?

Have you disabled the birthday calendar generator?

**Comment by fossxplorer** [comment]
I can't see anything in the NC log at least. DB is fine with just regular queries, no error messages.
How to disable  birthday calendar generator? Is that on an instance or per user basis?

**Comment by skjnldsv** [comment]
Hello!
Is it still happening on nextcloud 14?

**Comment by skjnldsv** [comment]
Closing as this is on an old contact app. If it still happen on 3.x.x version, please reopen this issue !
