### ISSUE TITLE
Errors on contacts on initial NC 14 installation

### ISSUE THREAD

**Issue by TecJon** [nextcloud/contacts#586]
### Steps to reproduce
1. Fresh installation of NC 14 beta 1
2. Open contacts page

### Expected behaviour
Option to add address book / contact
Nice layout

### Actual behaviour
- Settings button scrolled out of the view
- No response when clicking on "+ new contact"
- {{ctrl.t.emptySearch}} on screen when scrolling down
- after adding address book, still no resposne when clicking on "+ new contact"

![initial](https://user-images.githubusercontent.com/11375752/43356291-1d6f5b6e-926e-11e8-9cf2-9e48cd37ae48.PNG)

After scrolling down
![2](https://user-images.githubusercontent.com/11375752/43356295-2a3c7322-926e-11e8-8492-c3f285871321.PNG)

### Server configuration

**Nextcloud version:** 14.0.0 Beta 1

**Contacts version:** 2.1.5

**Updated from an older Nextcloud or fresh install:** fresh

**Signing status:** no errors

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Edge, Chrome, Firefox

**Operating system:** Win 10

#### Browser log
```
Refused to execute script from 'https://cloud.example.com/apps/notifications/js/notifications.js?v=4554f71a-0' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
2angular.js:14199 Error: searchCallback must be a function
    at Search.initialize (search.js?v=4554f71a-0:55)
    at new Search (search.js?v=4554f71a-0:37)
    at new <anonymous> (search_service.js:45)
    at Object.instantiate (angular.js:4786)
    at Object.<anonymous> (angular.js:4625)
    at Object.invoke (angular.js:4771)
    at Object.$get (angular.js:4609)
    at Object.invoke (angular.js:4771)
    at angular.js:4569
    at d (angular.js:4716)
```

**Comment by skjnldsv** [comment]
@TecJon Thanks for reporting :)
Contacts won't be compatible for 14. A new update is coming for this.

https://github.com/nextcloud/contacts/commit/f87c27a0d690f01d4c7e328b557e862cdd6045aa

**Comment by skjnldsv** [comment]
Actually since I've done the error of releasing the past versions with 14 compatibility, I'll need to provide a patch for the old app while we wait for the new one :)
So I'll re-open this!

**Comment by cabaretboy** [comment]
The issue presents itself the same when doing an upgrade from 13 to 14 beta as well. That is, a populated address book shows the same - not just an issue for fresh installs.

**Comment by skjnldsv** [comment]
@TecJon @cabaretboy can you try #588 please?

**Comment by TecJon** [comment]
@skjnldsv Making sure I did the right steps.
I removed the old contacts app via the web interface. I unpacked the tar from #588 in apps/. Then go to apps on the nc web interface and enable contacts.

The app version which appears is still 2.1.5. After enabling it, it still says 2.5.1 only after refreshing the page it will say 2.1.6
![2 5 1](https://user-images.githubusercontent.com/11375752/43569180-0923ec2a-9637-11e8-9bde-9733eb5d8257.PNG)


The contacts page itself is empty and shows a spinner on the left side. Settings button is disabled.

![contacts](https://user-images.githubusercontent.com/11375752/43569416-b29298f6-9637-11e8-829b-2def88b38266.PNG)

Happens on two test installations. Both should have zero addressbooks/contacts

**Comment by skjnldsv** [comment]
@TecJon please make sure you cleared your cache :)

**Comment by TecJon** [comment]
Alright 😃 
Here's the Edge browser log

`
JQMIGRATE: Migrate is installed, version 1.4.0
 New search handler registered
 querying Whats New data was successful: nocontent
 undefined
 HTML1300: Navigation occurred.
contacts (1,1)
2 CSP14309: Unknown directive 'manifest-src' in Content-Security-Policy - directive will be ignored.
 CSS3121: The media query -ms-viewport has been deprecated.
4 HTML1500: Tag cannot be self-closing. Use an explicit closing tag.
contacts (94,21)
 HTML1508: Unmatched end tag.
contacts (214,50)
2 SEC7112: Script from https://example.com/apps/files/ was blocked due to mime type mismatch
contacts (1,1)
 JQMIGRATE: Migrate is installed, version 1.4.0
`

heres Chromes:
`Refused to execute script from 'https://example.com/apps/contacts/js/contacts-inject-14.js?v=2df6b6be-0' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.`

Site behaves the same everywhere

**Comment by skjnldsv** [comment]
`Refused to execute script from 'https://example.com/apps/contacts/js/contacts-inject-14.js?v=2df6b6be-0' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.`

That is strange. Let me check!

**Comment by skjnldsv** [comment]
@TecJon I updated the OP on #588 There was an issue in the build package.
Please try again :)

**Comment by TecJon** [comment]
@skjnldsv you mean https://github.com/nextcloud/contacts/files/2252661/contacts.tar.gz right? Same behavior. Also with a cleared cache it will say 2.1.5 first.

**Comment by skjnldsv** [comment]
@TecJon Better? :)

**Comment by TecJon** [comment]
Alright. This one works 😃 

Some design issues I have found:
- contact width not 100% 
- loading spinner positioned weird in chrome and firefox 
- When scrolling down on the contact, the list is also shifted up (not scrolled). See last screenshot. The list doesn't end there so it shouldn't shift. 
- After scrolling through the list, I cannot scroll on the contact for 2 seconds
- Scrolling seems buggy in Chrome. It often responds after 1-2 seconds and results in shifting and scrolling the contact list.
- address book name input field has a red border for some reason
- "no contacts info" not centered
- the weird email label on the last screenshot is in vcf "ITEM1.EMAIL;TYPE=INTERNET,pref:" in iOS simply "other"



![contacts2](https://user-images.githubusercontent.com/11375752/43572303-757afa46-963f-11e8-9e4a-9a2ed9eeda31.PNG)

![nocontacts](https://user-images.githubusercontent.com/11375752/43572495-fbfecfd4-963f-11e8-9ae5-f24fd455a7b5.PNG)

Spinner at the top of the contact list, overlapping with the list, the navbar and the content. Can also be scrolled away. 
![spinner](https://user-images.githubusercontent.com/11375752/43572735-8288d982-9640-11e8-827d-7b1dc74f70d1.PNG)

![contac](https://user-images.githubusercontent.com/11375752/43573460-0c0edc32-9642-11e8-8168-69b2df02fd64.PNG)


Since I had zero contacts on my test installation I tried to import an old contacts dump file. It worked quite well and I really liked the visual feedback on the web interface. At around 80% I got several `Failed to load resource: net::ERR_SPDY_PROTOCOL_ERROR` errors in the browser log and 170 `Failed to load resource: the server responded with a status of 504 ()`

**Comment by skjnldsv** [comment]
@TecJon Okay, I'm guessing most of the design will be fixed on the new beta. We merged quite a lot of design fixes for this :)

Can you confirm you're not on server@master ?

Also: the 504 error, the import issues and the label are not related as this is not the point of this 14 compatibility update ;)

**Comment by TecJon** [comment]
Cool, I'm happy to hear that. 

> Can you confirm you're not on server@master ?

What exactly do you mean by that? I am on the update channel beta and have installed beta 1

**Comment by skjnldsv** [comment]
@TecJon that answers my question. I wanted to make sure you were on the beta1 and did not updated to the latest git version on master
