### ISSUE TITLE
Cannot remove contact from group with very long name

### ISSUE THREAD

**Issue by awesome-manuel** [nextcloud/contacts#587]
### Steps to reproduce
1. Add a contact to a new group with a long name (> 30 characters)
2. Try to remove the contact from that group

### Expected behaviour
The "x" icon should be visible beneath the group name

### Actual behaviour
The input box for the groups is too small so that the group name and therefore also the "x" icon are truncated. Resizing the browser window does not help.

### Client configuration
**Browser:** Chrome 68.0.3440.75

**Operating system:** Ubuntu 18.04

**CardDAV-clients:** Akonadi

**Comment by awesome-manuel** [comment]
As a workaround it is possible to place the cursor in the group edit box and hit "backspace" on the keyboard.

**Comment by skjnldsv** [comment]
@awesome-manuel fixed in 3.0.0
