### ISSUE TITLE
Bulk import of about 400 randomly fails

### ISSUE THREAD

**Issue by AuspeXeu** [nextcloud/contacts#589]
I get the following errors when I try to import around 400 contacts.

![screen shot 2018-08-02 at 09 51 14](https://user-images.githubusercontent.com/2115696/43573518-c9515df0-9639-11e8-9611-99917933add1.png)

I tried the same procedure several times and the contacts that get rejected are not always the same which leads me to believe that there is some rate limiting/queueing maybe needed during imports of larger contact lists?

**Comment by skjnldsv** [comment]
@AuspeXeu Thanks for reporting :)
Thsi is an issue related to the dav server.
Could you report directly to https://github.com/nextcloud/server
