### ISSUE TITLE
wrong translation(option) of sex.

### ISSUE THREAD

**Issue by run2death** [nextcloud/contacts#594]
Wrong translation(option) in Chinese(zh_CN, 简体中文). 
### Steps to reproduce
1. edit a contact
2. add field sex(性别)
3. choose option

### Expected behaviour
femal 女性
male 男性
other 其他
### Actual behaviour
femal 女性
male 女性
other 其他

**Comment by skjnldsv** [comment]
Hello!
Translation are managed on transifex :)

https://www.transifex.com/nextcloud/nextcloud/contacts/

**Comment by run2death** [comment]
@skjnldsv 
Updated, respect!

**Comment by skjnldsv** [comment]
@run2death thanks a lot! :)
