### ISSUE TITLE
[Vue] Design issues for addressbook sharing 

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/contacts#600]
- [x] No cursor on delete icon
- [x] Checkbox design a bit off
- [x] No loading state
- [x] Clicking the share button directly focus the input

**Comment by sleepypioneer** [comment]
Noted 👍

**Comment by sleepypioneer** [comment]
@skjnldsv I have added the loading icon and the cursor Im not sure what about the checkbox other than the font weight we discussed is off, can you please look again and elaborate :)

**Comment by skjnldsv** [comment]
Loading looks nice!!
Still this small dropdown showing before loading, which is annoying, but it's  a nitpick ;)

I added one small great addtion to the top :) :+1:

**Comment by sleepypioneer** [comment]
Can you check again, I'm not sure I see the small drop down before loading. I am still unsure also about how the checkbox differs. Thank you 🙈
