### ISSUE TITLE
Improve the Contactlist by loading in Chunks

### ISSUE THREAD

**Issue by Offerel** [nextcloud/contacts#61]
I have a small Idea for Speed Improvement in the Contact App. Loading my 200 Contacts on a Raspberry Pi takes some time. I think, it would be better to load them in Chunks. What do you think, if we load only 30 or 50 Contacts and load the rest if we scroll the list to the bottom and reach the end (next 30 entrys)? 

Additionally, the Counter for all Contacts should always visible, not only at the end as last Contact, maybe this could be done, if the Contactlist ends above the Counter. Any chance to get this in a upcoming version?

BTW: The value for Chunk-Count should be configurable.

**Comment by skjnldsv** [comment]
Duplicate #12 ?

**Comment by Offerel** [comment]
Uppps sorry. I didn't have seen this after searching, if there is a similar idea here. Feel free to merge the requests.
