### ISSUE TITLE
Show organization & title in contacts list

### ISSUE THREAD

**Issue by Stabington** [nextcloud/contacts#621]
As the title suggests, simply show organization and title in the contact list.

https://spaceweb.asuscomm.com/index.php/s/aD8ozxmd9JgRwwG

Example:
https://xnspy.com/img/en/contact-mobile.png

**Comment by skjnldsv** [comment]
@Stabington Thanks for you rsuggestion :)
I'm not sure we can do that, the space availability is tiny and we need to keep things clean and easy to read.

Currently we have the name and the email, you want to add an option to chose ether to display, the email, or the org+title, right?

**Comment by skjnldsv** [comment]
After giving some thoughts, we won't do that for regular vcards, but we definitively will for org cards :)
