### ISSUE TITLE
Add ability to store contact relations

### ISSUE THREAD

**Issue by eglipeter** [nextcloud/contacts#635]
I would like to hand in this proposal for a new feature within the Nextcloud contact app:

It should be possible to "link" contacts to other contacts such that a user can model relationship diagrams within the contact app. It should be possible to describe a "type" of relation like "customer" or "supplier". I can think of many use cases for that: Businesses can capture their relations to customers or partners. E.g. attorneys can link the adversary or the attorney of the adversary to a client. Therefore, it would be needed that the user can define a "type" of relation for the individual contacts. Also, for private persons this can be interesting. E.g. when you store which people know each other, one can easily obtain interesting insights into the contact situation. A far term goal could be to generate graphs of the stored links between individual contact objects.

Yours,
Peter

**Comment by skjnldsv** [comment]
@eglipeter You can already store the contact relation, but there is no diagram. :)

As this sounds like a nice feature, currently there a no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.

**Comment by bpmartin20** [comment]
+1
