### ISSUE TITLE
Address book data lost when any user receiving a share is deleted

### ISSUE THREAD

**Issue by cemrich** [nextcloud/contacts#64]
### Steps to reproduce
1. Create user1 with an address book shared to group1
1. Create user2 of group1 to view the address book
1. Delete user2

### Expected behaviour
User2 gets deleted but the shared address book of user1 remains intact. 

### Actual behaviour
The shared address book of user1 gets deleted. The tables ``oc_addressbooks`` and ``oc_cards`` are wiped of all information regarding this address book. If the given address book is the only one of user1, the "infinite loading bug" as described in #58 appears.

### Server configuration
**Operating system**: ?

**Web server:** ?

**Database:** mysql 5.1.73

**PHP version:** 7.0.13

**Nextcloud version:** 11.0.0 (stable)

**Contacts version:** 1.5.2

**Updated from an older Nextcloud or fresh install:** fresh install

**Signing status:**

```
No errors have been found.
```

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox 50.0.2 and Chrome 54.0.2840.99 m (64-bit)

**Operating system:** Windows 10

**Comment by jeweloper** [comment]
I can confirm this bug.
In my case I shared the address book of user1 directly to user2.
After I deleted user2, I sadly missed the address book of user1. :weary:

To restore the address book:
Is it enough to restore the corresponding records in `oc_addressbooks`, oc_cards and `oc_cards_properties`?
This is exactly what I done by now and at first sight everything seems to be OK.
Or did I possibly miss something to restore a specific book from a database dump.

Thx for your help.

**Comment by nickallevato** [comment]
@jeweloper thank you for this post! Saved our butts because:

1. Same bug (deleted user and lost all contacts).
2. I was restoring just _cards & _cards_properties and no contacts.

Read your post, restored address-books, and contacts were back.

Thanks again, will check back on this thread in case something develops!

**Comment by ccoenen** [comment]
So, in other words, we have a reproducible scenario where user data is lost. And this has been open for six weeks?

**Comment by skjnldsv** [comment]
@ccoenen feel free to contribute here. It's an open-source project, everyone can help us! 😃

**Comment by ccoenen** [comment]
I'll start by proposing the label `bug` and putting it on the roadmap.

Code-wise, sadly, I do not need another open source project. I limit myself to scouring issue trackers, looking for important but overlooked issues.

**Comment by skjnldsv** [comment]
Sure.

@cemrich I think this is a server issue. The removal of a user and the related database entries are not done here. I'll look into it.

**Comment by cemrich** [comment]
Thank you for your work!
