### ISSUE TITLE
Move contact to another adressbook only copy

### ISSUE THREAD

**Issue by ml94** [nextcloud/contacts#644]
I have installed the Nextcloud VM 14.0.0 (Contact-App 2.1.6) last Week and import my contacts (around 100) from my Smartphone (Android) via CalDAV. 
Then I sort my contact in NC with Groups and a second Adressbook. And here is the Problem: When I change the Adressbook the Contact did not change and when I reload the Page is the Contact on the old Adressbook.
The only Way for me to change the Adressbook is to download the contact, delete it in NC and import to the right Adressbook. But after reload the Page I have the contacts which I imported are double. Then I must delete one from the double contacts. 
Today I make the Update to NC 14.0.1. But its the same Problem.

**Comment by skjnldsv** [comment]
@ml94 Morning! :)
Are you having any error on the browser's log?

**Comment by ml94** [comment]
I have one Error from PHP in my log. This error comes frequently every time. When I editing a Contact (also move the adressbook) I get no extra Error.

Error | PHP | Module 'redis' already loaded at Unknown#0 | 3 minutes ago
Error | PHP | Module 'redis' already loaded at Unknown#0 | 4 minutes ago
Error | PHP | Module 'redis' already loaded at Unknown#0 | 4 minutes ago
Error | PHP | Module 'redis' already loaded at Unknown#0 | 4 minutes ago
Error | PHP | Module 'redis' already loaded at Unknown#0 | 7 minutes ago
Error | PHP | Module 'redis' already loaded at Unknown#0 | 8 minutes ago
Error | PHP | Module 'redis' already loaded at Unknown#0 | 13 minutes ago
Error | PHP | Module 'redis' already loaded at Unknown#0 | 13 minutes ago
Error | PHP | Module 'redis' already loaded at Unknown#0 | 15 minutes ago
Error | PHP | Module 'redis' already loaded at Unknown#0 | 15 minutes ago
Error | PHP | Module 'redis' already loaded at Unknown#0 | 15 minutes ago
...and so on...

**Comment by skjnldsv** [comment]
@ml94 Hey!
Thanks for your feedback.
I would prefer the browser's log please.

> You can open the Browser Console in one of two ways:
> 
> 1. from the menu: select "Browser Console" from the Web Developer submenu in the Firefox Menu (or Tools menu if you display the menu bar or are on OS X)
> 2. from the keyboard: press Ctrl+Shift+J (or Cmd+Shift+J on a Mac).

Opening it before and do your move, then check if anything happens here please :)

**Comment by ml94** [comment]
Hi skjnldsv!
Here the Log from Firefox 62.0.2. The first Log came by loading the Contact-Page and Log 2 to 4 by editing the Adressbook.

1. Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf self blockiert ("script-src"). Source: onloadedmetadata attribute on SPAN element. contacts
2. Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf self blockiert ("script-src"). Source: ondrop attribute on INPUT element. contacts
3. Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf self blockiert ("script-src"). Source: ondrop attribute on INPUT element. contacts
4. Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf self blockiert ("script-src"). Source: ondrop attribute on INPUT element. contacts

**Comment by skjnldsv** [comment]
@ml94 I was expecting something else :stuck_out_tongue_closed_eyes: 
Okay, then, before you copy, still on the console, there is a tab called "network", click the xhr filter, move your contact and do a screenshot of the network log.
This should look like this: 
![capture d ecran_2018-09-27_21-49-46](https://user-images.githubusercontent.com/14975046/46170857-43548000-c29f-11e8-9403-db72713dd9c1.png)

**Comment by ml94** [comment]
Ok, here the Screenshot. Thanks for your help!

![unbenannt](https://user-images.githubusercontent.com/43516978/46171705-99c2be00-c2a1-11e8-96bf-65183e225757.PNG)

**Comment by ml94** [comment]
Hi skjnldsv! 
In Firefox looks the Log-Window different as by your Screenshot. I hope I copy the right Code with the Name https://123.456.7.890/remote.php/dav/principals/users/ml94/ (Second entry). 

My first Adressbook names "JDAV" and is a Shared Adressbook. The second names "Persönlich" and is not Shared. When I create a new Contact it is in the "JDAV" Adressbook.

`<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:card="urn:ietf:params:xml:ns:carddav" xmlns:oc="http://owncloud.org/ns" xmlns:nc="http://nextcloud.org/ns"><d:response><d:href>/remote.php/dav/addressbooks/users/ml94/</d:href><d:propstat><d:prop><d:owner><d:href>/remote.php/dav/principals/users/ml94/</d:href></d:owner><d:resourcetype><d:collection/></d:resourcetype></d:prop><d:status>HTTP/1.1 200 OK</d:status></d:propstat><d:propstat><d:prop><d:displayname/><x1:getctag xmlns:x1="http://calendarserver.org/ns/"/><d:sync-token/><oc:read-only/><oc:invite/><oc:enabled/></d:prop><d:status>HTTP/1.1 404 Not Found</d:status></d:propstat></d:response><d:response><d:href>/remote.php/dav/addressbooks/users/ml94/JDAV/</d:href><d:propstat><d:prop><d:displayname>JDAV</d:displayname><d:owner><d:href>/remote.php/dav/principals/users/ml94/</d:href></d:owner><x1:getctag xmlns:x1="http://calendarserver.org/ns/">63</x1:getctag><d:resourcetype><d:collection/><card:addressbook/></d:resourcetype><d:sync-token>http://sabre.io/ns/sync/63</d:sync-token><oc:invite><oc:user><d:href>principal:principals/groups/JDAV</d:href><oc:invite-accepted/><oc:access><oc:read/></oc:access></oc:user></oc:invite><oc:enabled>1</oc:enabled></d:prop><d:status>HTTP/1.1 200 OK</d:status></d:propstat><d:propstat><d:prop><oc:read-only/></d:prop><d:status>HTTP/1.1 404 Not Found</d:status></d:propstat></d:response><d:response><d:href>/remote.php/dav/addressbooks/users/ml94/Pers%c3%b6nlich/</d:href><d:propstat><d:prop><d:displayname>Persönlich</d:displayname><d:owner><d:href>/remote.php/dav/principals/users/ml94/</d:href></d:owner><x1:getctag xmlns:x1="http://calendarserver.org/ns/">43</x1:getctag><d:resourcetype><d:collection/><card:addressbook/></d:resourcetype><d:sync-token>http://sabre.io/ns/sync/43</d:sync-token><oc:invite/><oc:enabled>1</oc:enabled></d:prop><d:status>HTTP/1.1 200 OK</d:status></d:propstat><d:propstat><d:prop><oc:read-only/></d:prop><d:status>HTTP/1.1 404 Not Found</d:status></d:propstat></d:response></d:multistatus>`

**Comment by skjnldsv** [comment]
@ml94 Hey again!
I'm guessing you're trying to move from **Persönlich** to **JDAV** ?
Persönlich is in read-only, so you cannot add/edit/delete contacts from it.

**Comment by ml94** [comment]
Hi skjnldsv,
yes I try to move the contact from Persönlich to JDAV (both not read-only!) and I think I have found the problem: It is the letter ö in the Adressbookname. 
When I delete the Adressbook, make a new with a name without ä/ö/ü then the contact is move after refreshing the site. 

I found a hint in the copied Code (--> Pers%c3%b6nlich):
`HTTP/1.1 404 Not Found</d:status></d:propstat></d:response><d:response><d:href>/remote.php/dav/addressbooks/users/ml94/Pers%c3%b6nlich/</d:href><d:propstat><d:prop>`

**Comment by skjnldsv** [comment]
Nice catch!!!
We'll have to check if this still fails on the new contact v3.0.
If it still fails, I'll assume we need a fix on the server ;)
I'll leave this open.
