### ISSUE TITLE
[Vue] New properties should be sorted

### ISSUE THREAD

**Issue by rullzer** [nextcloud/contacts#653]
When adding a new property now the order looks kind of random. I wanted to add the e-mail address of a contact and it was at some random spot. Just having it sorted alphabetically would make most sense I guess

**Comment by skjnldsv** [comment]
You're talking in the add new property drop down or in the main ui?

**Comment by rullzer** [comment]
![prop](https://user-images.githubusercontent.com/45821/46243637-dba15080-c3d6-11e8-957d-f2126a4d3c39.png)

That one in the main view/editing of a contact
