### ISSUE TITLE
Layout sometimes broken

### ISSUE THREAD

**Issue by rullzer** [nextcloud/contacts#654]
![broken](https://user-images.githubusercontent.com/45821/46243498-51a4b800-c3d5-11e8-877f-98b10aab2de7.png)

As you can see the phone numbers seem to be spread of two columns. Which is odd and looks out of place.

If I zoom in a bit all is good

![good](https://user-images.githubusercontent.com/45821/46243518-93cdf980-c3d5-11e8-8470-fcf8fdd2214c.png)

**Comment by skjnldsv** [comment]
Yes, this is due to the algorithm we use. Basically they're displayed right after the other, but flex is displaying them horizontally. There is no way to prioritise them vertically but filling them horizontally the way we implemented this.
I have another algorithm in testing that improve this but add other drawbacks :)

**Comment by violoncelloCH** [comment]
I want to add here that it's quite confusing that depending on how many properties are set, other properties jump from the left to the right ore vice versa. So you always have to look for the right field. Also while switching between different contacts, I would expect to always have a specific field at a specific place, not one time on the left and for an other contact on the right.

**Comment by gary-kim** [comment]
Could it be possible to place each set of properties in their own `div`?

**Comment by skjnldsv** [comment]
Hello @gary-kim :)
It was like that before and it was creating other issues.
The grid view was not possible and therefore could lead to really big incoherence in the size of each rows :/

**Comment by gary-kim** [comment]
Okay. I don't think there is a way to tell a grid when to wrap so I'll see if I can find a solution.

**Comment by skjnldsv** [comment]
@gary-kim there is a working solution with require a javascript algorithm.
We count how many column there is and we iterate over all the displayed properties:
1. if the property have another same property: put it in the same column
2. if not, put it in the column with the smallest height.

Like so it will stack and group properties of the same type, and always try to fill the column that is the smallest (for visual balance)
I tried it before, and it was decent :)

**Comment by rponline** [comment]
Hi!
I tried sth:
I grouped the properties, removed the grid view and made columns instead.
The props are still sorted, but the sorting happens in columns. 
(I tried using [vue-masonry](https://github.com/shershen08/vue-masonry) but importing didn't work for some reason.)

https://github.com/rponline/contacts/tree/experiment/neat-props  
(sorry for this big chuck of changes)

I guess it still needs a few improvements, but would this be a solution? 

![Screenshot-2019-4-10 Contacts - Nextcloud Dev](https://user-images.githubusercontent.com/1266260/55917839-b2435780-5ba5-11e9-8daa-40e67ae75de0.png)

**Comment by skjnldsv** [comment]
@rponline Hey thanks for taking a shot at it! :)

Unfortunately, I don't want to go back to this solution. This is exactly what we had in the 2.x version and it lead to a lof of different issues.

> It was like that before and it was creating other issues.
The grid view was not possible and therefore could lead to really big incoherence in the size of each rows :/

Amongst those issues is how browsers are treating columns. The main problem is that columns are prioritised vertically, and not horizontally. Which is the opposite of what we're trying to do. We want to fill the horizontal space in priority. Your examples looks good, but they're carefully chosen. Take a look at those:

| 1 | 2 |
|:---------:|:------:|
|![dev skjnldsv com_apps_contacts_All%20contacts_c7351e3f-96c1-4b8b-ba5e-1b6cc07ea6f9_contacts](https://user-images.githubusercontent.com/14975046/55934638-7c4bb500-5c31-11e9-975c-d384bdd8d2c5.png)|![dev skjnldsv com_apps_contacts_All%20contacts_c7351e3f-96c1-4b8b-ba5e-1b6cc07ea6f9_contacts (1)](https://user-images.githubusercontent.com/14975046/55934639-7c4bb500-5c31-11e9-8567-5db929100910.png)|

And the most important of all: Browsers does NOT properly display absolute items in columns and this is not possible in our case: :disappointed: 
![Capture d’écran_2019-04-11_08-11-44](https://user-images.githubusercontent.com/14975046/55934660-9c7b7400-5c31-11e9-87ee-e8695f1bd98d.png)

The only issue here is either a masonry plugin (but they're often heavy and can be hard to implement) or to create our own algorithm to place the items in specific columns (tried it, works ok, lost my code :see_no_evil: )

**Comment by rponline** [comment]
There are some lightweight masonry scripts out there which make use of css grid. I can have a look at them.

I honestly don't think that removing grouping is the way to go. 

Having this abstraction layer makes the design process so much more flexible.

**Comment by skjnldsv** [comment]
@rponline depends on what kind of implementation you do.
I don't have anything against grouping, but css column is not the proper solution for sure :)

**Comment by skjnldsv** [comment]
> I can have a look at them.

That would be awesome! Thanks :)

**Comment by rponline** [comment]
@skjnldsv 
I updated this branch:  
https://github.com/rponline/contacts/tree/experiment/neat-props

Now, it's masonry with css grid (and a bit of js). It's working, but not ready for production.  
I'll polish it if you think we can use this.

**Comment by skjnldsv** [comment]
Visually looks very nice!!
I really like your simple idea of the grid span! Let's do it! :tada: :wink: 

I saw a few changes, but I will comment then in the pr once created, it's mostly a few bad code practice we coul dimprove on contact-details-property-group!

Thanks a lot! This is awesome!!! :rocket:

**Comment by skjnldsv** [comment]
@rponline any news? :)

**Comment by rponline** [comment]
I'll create a pull request in the next days.
Had some problems, but i solved them ... now i have to merge/catch up with the current master.

You can already look into or even test my branch if you feel like it :)

**Comment by skjnldsv** [comment]
Awesome!! I'll be pretty busy, but I will make sure to check and assist you on your awesome work :)

**Comment by f3lixdev** [comment]
![NextCloud Contact failure](https://user-images.githubusercontent.com/52625423/60767938-2adf8480-a0bf-11e9-82ae-64166fd44a36.jpg)
Bug in list after moving contact to another address book.

**Comment by myrho** [comment]
What's the state of this issue?

**Comment by Luzifer** [comment]
Maybe this could be helpful for someone debugging this:

For me the design is
- usable up to and equal `window.innerWidth = 1729px`
- broken above and equal `window.innerWidth = 1730px`

**Comment by skjnldsv** [comment]
https://jbaysolutions.github.io/vue-grid-layout/examples/06-responsive.html
