### ISSUE TITLE
Contacts app doesn't show anything after Upgrade to NC 11.0

### ISSUE THREAD

**Issue by nursoda** [nextcloud/contacts#66]
Since you state "migration issues belong in the server repo", but also ask for "Updated from an older Nextcloud or fresh install", I'm unsure if this should be here or in server. Please point me there if you feel it should be elsewhere.

I upgraded three NC installations from 10.0.2 to 11.0 and all went smooth. In two of them, all apps work flawless, in one the calendar app no longer works at all: It no longer shows any contacts in the web interface (idles, see screenshot), and clients (DAVdroid, CardDAV) show error "not found".

![contacts](https://cloud.githubusercontent.com/assets/8425483/21469267/b8a8d656-ca41-11e6-856c-ba53cdbad9f4.png)

Any hint appreciated on how to recover from this (preferrably without loosing contact data), or how to reset.

These seem to be a similar issues:
 - https://github.com/nextcloud/contacts/issues/53
 - https://github.com/owncloud/contacts/issues/430
 - https://central.owncloud.org/t/webdav-no-longer-working-after-upgrade-to-9-1-2/4263

Notes:
 - In the problematic installation, I use a user name that does not contain spaces (but a dot).
 - In one of the working installations, I use a username containing a space character but in that account, all contacts work fine.
 - Contacts in both installations contain pictures.

### System parameters

OS: debian stable, Web server: apache2, Database: MySQL 5.5, PHP 5.6, Nextcloud 11.0.0.10, Contacts: 1.5.2, UPDATED FROM 10.0.0.2, Signing: No errors in Admin check, /settings/integrity/failed yields "No errors have been found.", NOT using external storage, encryption or external user-backend.

**List of activated apps:**
Enabled:
  - activity: 2.4.1
  - announcementcenter: 3.0.0
  - apporder: 0.3.3
  - bookmarks: 0.9.1
  - calendar: 1.4.1
  - comments: 1.1.0
  - contacts: 1.5.2
  - dav: 1.1.1
  - direct_menu: 0.9.3
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_pdfviewer: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - gallery: 16.0.0
  - keeweb: 0.3.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - mail: 0.6.2
  - nextcloud_announcements: 1.0
  - notifications: 1.0.1
  - ownbackup: 16.11.0
  - ownpad: 0.5.7
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - systemtags: 1.1.3
  - tasks: 0.9.4
  - templateeditor: 0.2
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - twofactor_totp: 0.5.0
  - twofactor_u2f: 0.1.0
  - updatenotification: 1.1.1
  - workflowengine: 1.1.1

Disabled:
  - admin_audit
  - audioplayer
  - encryption
  - external
  - files_accesscontrol
  - files_automatedtagging
  - files_external
  - files_retention
  - firstrunwizard
  - richdocuments
  - spreed
  - spreedme
  - survey_client
  - user_external
  - user_ldap
  - user_saml

**The content of config/config.php:**
{
    "system": {
        "instanceid": "<ID>",
        "trashbin_retention_obligation": "auto,90",
        "versions_retention_obligation": "90,auto",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": "true",
        "redis": {
            "host": "localhost",
            "port": 6379,
            "timeout": 0
        },
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "<DOMAIN>"
        ],
        "datadirectory": "\/<PATH>",
        "overwrite.cli.url": "https:\/\/<DOMAIN>\/cloud",
        "dbtype": "mysql",
        "version": "11.0.0.10",
        "dbname": "<DBNAME>",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "Europe\/Berlin",
        "installed": true,
        "mail_from_address": "<FROM>",
        "mail_smtpmode": "php",
        "mail_domain": "<DOMAIN>",
        "defaultapp": "calendar",
        "maintenance": false,
        "loglevel": 2,
        "theme": "",
        "updater.release.channel": "stable"
    }
}

### Client configuration
Browser: Firefox 50, OS: ApricityOS, CardDAV-clients: DAVdroid, CardDAV.

#### Web server error log
<IP> - <USER> [25/Dec/2016:00:44:29 +0100] "PROPFIND /cloud/remote.php/webdav/ HTTP/1.1" 207 2231 "-" "Mozilla/5.0 (Linux) mirall/2.2.4"
<IP> - - [25/Dec/2016:00:44:34 +0100] "GET /cloud/ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 200 913 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:50.0) Gecko/20100101 Firefox/50.0"

#### Nextcloud log (data/nextcloud.log)
{"reqId":"<ID>","remoteAddr":"<IP>","app":"core","message":"Login failed: '<USER>' (Remote IP: '<IP>')","level":2,"time":"2016-12-25T01:25:59+01:00","method":"PROPFIND","url":"\/cloud\/remote.php\/webdav\/","user":"--","version":"11.0.0.10"}
{"reqId":"<ID>","remoteAddr":"<IP>","app":"core","message":"Login failed: '<USER>' (Remote IP: '<IP>')","level":2,"time":"2016-12-25T01:25:59+01:00","method":"GET","url":"\/cloud\/ocs\/v2.php\/apps\/notifications\/api\/v1\/notifications?format=json","user":"--","version":"11.0.0.10"}

#### Browser JS log
Sending message that cannot be cloned. Are you trying to send an XPCOM object?  MessageChannel.jsm:504:4
JQMIGRATE: Migrate is installed, version 1.4.0  jquery-migrate.min.js:2:542
Sending message that cannot be cloned. Are you trying to send an XPCOM object?  MessageChannel.jsm:504:4

**Comment by nursoda** [comment]
This seems to be a similar issue: https://central.owncloud.org/t/webdav-no-longer-working-after-upgrade-to-9-1-2/4263

**Comment by skjnldsv** [comment]
Could you try #73 please?

**Comment by skjnldsv** [comment]
@nursoda Could you try #73 please?

**Comment by nursoda** [comment]
Sorry for the delay, I'm moving my office.
I tried #73 - seems to be exactly the same behavior.
I tried master - shows even less: there is no idle, no "Alle Kontakte"/"Nicht gruppiert", no dummy user logo on the right. All plain white (except for the header).

**Comment by skjnldsv** [comment]
Any log in the console?

**Comment by nursoda** [comment]
In Firefox Developer Panel / Console I see CSS warnings, but no JS warnings/errors at all.

**Comment by nursoda** [comment]
Can I do anything else?

**Comment by skjnldsv** [comment]
Do you have access to your database?

Could you send an export of oc_cards to skjnldsv@protonmail.com?
If not, you can always try to send an export of your addressbooks to the same email.

I can't really debug remotely, and since you don't have any errors, it seems to be the best way (like I did in #53 with op)

**Comment by skjnldsv** [comment]
Okay, so I tried importing your data with the app and this literally took like 15 mins..
So we really need to optimise that, but that's another issue.

After importing you rdata works fine.
My bet is a failed upgrade when we transitioned from a different table (maybe a failed process or your installation blocked while migrating) to oc_cards.

Please use your dump file and import it directly into the app file. Should do the trick. :)

**Comment by nursoda** [comment]
I restored oc_cards via ownbackup and get the error below. Don't know what to do next.

```
Tables restored

Table(s) could not be restored: Inserting data row failed: An exception occurred while executing 'INSERT INTO `oc_cards` (`id`,`addressbookid`,`carddata`,`uri`,`lastmodified`,`etag`,`size`) SELECT ?,?,?,?,?,?,? FROM `oc_cards` WHERE `id` = ? AND `addressbookid` = ? AND `carddata` = ? AND `uri` = ? AND `lastmodified` = ? AND `etag` = ? AND `size` = ? HAVING COUNT(*) = 0' with params ["5", "1", "BEGIN:VCARD\r\nVERSION:3.0\r\nPRODID:-\/\/Sabre\/\/Sabre VObject 3.5.0\/\/EN\r\nUID:olav.seyfarth\r\nFN:Olav Seyfarth\r\nCLOUD:olav.seyfarth@datenschutz-individuell.de\/cloud\r\nPHOTO;ENCODING=b;TYPE=image\/jpeg:\/9j\/4AAQSkZJRgABAQEAYABgAAD\/\/gA+Q1JFQVRPUj\r\n ogZ2QtanBlZyB
]...]
GEQNl\r\n hnbgY6dc9T0p0sX2iX5XCKx3Et7Z4OB833etBWKCMJvyVHCogbGe36UAf\/\/Z\r\nN:Seyfarth;Olav;;;\r\nEMAIL:olav.seyfarth@datenschutz-individuell.de\r\nEND:VCARD\r\n", "Database:olav.seyfarth.vcf", "1473203029", "9d399baa474d74d34d719982dc84fd6f", "114261"]: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'carddata' in 'where clause'
```

**Comment by skjnldsv** [comment]
No, I meant import it from the import function of the contacts app :)

**Comment by nursoda** [comment]
I can't, since my contacts app is not responsive at all (idle only). How to reset it?

**Comment by skjnldsv** [comment]
Create a new addressbook and delete the old ones.

**Comment by nursoda** [comment]
I cannot access the app settings! So I cannot delete any address book (IF it is still there).

**Comment by skjnldsv** [comment]
This is strange. Could your remove it from your database directly?

**Comment by skjnldsv** [comment]
Okay, I just deleted my old addressbook and I found out what is your issue.
The app can't load without addressbook.

![capture d ecran_2017-01-10_12-11-49](https://cloud.githubusercontent.com/assets/14975046/21804195/fd1ab860-d72d-11e6-96b3-b07636e3dd63.png)

**Comment by skjnldsv** [comment]
When you click the Settings in the bottom left, what's in there?

**Comment by nursoda** [comment]
Sure, how? Could you provide the correct SQL statements?

This is what I see:
![settings](https://cloud.githubusercontent.com/assets/8425483/21804231/2d47e56c-d72e-11e6-992f-0e9dbf19d3bd.png)

I can enter a new addressbok name, but cannot create it.

**Comment by skjnldsv** [comment]
You can't create a new addressbook?
Because I can.

When clicking the arrow, do you get a failed request in your network debug tab?

**Comment by nursoda** [comment]
I did try that of course, but nothing happens (no visible feedback). Would it help to use the master app? Or should I add some debugging somewhere in the code?

**Comment by skjnldsv** [comment]
I need to see if the dav core is blocking the creation.
You need to open the console, click the network tab and try to create an addressbook
![capture d ecran_2017-01-10_13-17-03](https://cloud.githubusercontent.com/assets/14975046/21805926/23d6c45e-d737-11e6-91e2-dd3fd890fda7.png)
![capture d ecran_2017-01-10_13-17-21](https://cloud.githubusercontent.com/assets/14975046/21805927/23d92280-d737-11e6-99e6-6f2d315d248b.png)

**Comment by nursoda** [comment]
No, only when opening settings, I see network activity. And (periodically) notifications (not related to klicking the right-arrow):
![network](https://cloud.githubusercontent.com/assets/8425483/21806114/f5887f7e-d737-11e6-965c-765661c12f96.png)

BTW: Would it help to uninstall and reinstall the app? I guess not since the data in the DB is not modified, is it?

**Comment by skjnldsv** [comment]
You could try the latest master release (don't forget to compile it).
Stupid question, but did you try with the enter key? 😛 
In case of the arrow didn't work (which I don't understand)

**Comment by nursoda** [comment]
No, Enter also does not do anything.

**Comment by skjnldsv** [comment]
See #91 :)

**Comment by nursoda** [comment]
*thumbup* - so if I understand the process correctly, I must wait for review before I could download master. Could you send me a compiled version to test/verify?

**Comment by skjnldsv** [comment]
Added a tar.gz for testing :)

**Comment by nursoda** [comment]
I moved app/contacts, extracted .tar.gz, copied it from contacts-73 to contacts, checked ownership and permissions (was OK), shift-reloaded contacts, tried to add an addressbook. Same as before!

**Comment by skjnldsv** [comment]
Could you try again the network tab?
This contact app should automatically create an addressbook if there isn't one available. SO in theory we should see something. :)

**Comment by nursoda** [comment]
![network-73](https://cloud.githubusercontent.com/assets/8425483/21809126/a26dbb92-d746-11e6-81d6-09ce537d2d38.png)

**Comment by skjnldsv** [comment]
You got indeed an error 500. Mind to check your logs? 😄

**Comment by nursoda** [comment]
Sorry, should have done that right away. Since it contains more personal data, I sent it to protonet.

**Comment by skjnldsv** [comment]
Perfect!
This is indeed a different issue. Your database seemed invalid.
Could you output your oc_cards and oc_addressbooks table structure and post it here please?

**Comment by nursoda** [comment]
Do you mean these? I use the latest ownbackup copy - OK?

oc_cards/structure.xml:
<database><name>*dbname*</name><create>true</create><overwrite>false</overwrite><charset>utf8</charset><table><name>oc_cards</name><declaration><field><name>id</name><type>integer</type><default>0</default><notnull>true</notnull><autoincrement>1</autoincrement><unsigned>true</unsigned><length>8</length></field><field><name>addressbookid</name><type>integer</type><default>0</default><notnull>true</notnull><length>4</length></field><field><name>uri</name><type>text</type><default/><notnull>false</notnull><length>255</length></field><field><name>lastmodified</name><type>integer</type><default>0</default><notnull>false</notnull><unsigned>true</unsigned><length>8</length></field><field><name>etag</name><type>text</type><default/><notnull>false</notnull><length>32</length></field><field><name>size</name><type>integer</type><default>0</default><notnull>true</notnull><unsigned>true</unsigned><length>8</length></field></declaration></table></database>

oc_addressbooks/structure.xml
<database><name>*dbname*</name><create>true</create><overwrite>false</overwrite><charset>utf8</charset><table><name>oc_addressbooks</name><declaration><field><name>id</name><type>integer</type><default>0</default><notnull>true</notnull><autoincrement>1</autoincrement><unsigned>true</unsigned><length>8</length></field><field><name>principaluri</name><type>text</type><default/><notnull>false</notnull><length>255</length></field><field><name>displayname</name><type>text</type><default/><notnull>false</notnull><length>255</length></field><field><name>uri</name><type>text</type><default/><notnull>false</notnull><length>255</length></field><field><name>description</name><type>text</type><default/><notnull>false</notnull><length>255</length></field><field><name>synctoken</name><type>integer</type><default>1</default><notnull>true</notnull><unsigned>true</unsigned><length>4</length></field><index><name>addressbook_index</name><unique>true</unique><field><name>principaluri</name><sorting>ascending</sorting></field><field><name>uri</name><sorting>ascending</sorting></field></index></declaration></table></database>

**Comment by skjnldsv** [comment]
This seems to be the problem.

This is what I got:
``` sql
CREATE TABLE `oc_addressbooks` (
  `id` bigint(20) UNSIGNED NOT NULL,
  `principaluri` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `displayname` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `uri` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `description` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `synctoken` int(10) UNSIGNED NOT NULL DEFAULT '1'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE `oc_cards` (
  `id` bigint(20) UNSIGNED NOT NULL,
  `addressbookid` int(11) NOT NULL DEFAULT '0',
  `carddata` longblob,
  `uri` varchar(255) COLLATE utf8_bin DEFAULT NULL,
  `lastmodified` bigint(20) UNSIGNED DEFAULT NULL,
  `etag` varchar(32) COLLATE utf8_bin DEFAULT NULL,
  `size` bigint(20) UNSIGNED NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
```

**Comment by nursoda** [comment]
OK, so I need to DROP tables before that, right? Anything else I must do prior to importing cards via the app?

**Comment by skjnldsv** [comment]
The app can easily become unresponsive (I opened an issue about that)
But since your got ownbackups ready, you can try restoring the tables after fixing them, should do the trick I hope :)

**Comment by nursoda** [comment]
Dropping and creating tables allows me to create a new addressbook. But if I import cards, they aren't associated to any addressbook, even if there's only one. So, I cannot delete these cards by deleting the addressbook (after adding a second one). There seems to be more corrupt. Would you recommend to setup from scratch?

**Comment by skjnldsv** [comment]
``` mysql
MariaDB [nexttest]> SELECT * FROM `oc_addressbooks`;
+----+--------------------------+-------------+----------+-----------------------------------------------------------+-----------+
| id | principaluri             | displayname | uri      | description                                               | synctoken |
+----+--------------------------+-------------+----------+-----------------------------------------------------------+-----------+
|  2 | principals/system/system | system      | system   | System addressbook which holds all users of this instance |        27 |
| 23 | principals/users/admin   | Contacts    | Contacts | NULL                                                      |         1 |
+----+--------------------------+-------------+----------+-----------------------------------------------------------+-----------+
```
Get your addressbook id and then
`UPDATE `oc_cards` SET `addressbookid`=YOURID` (here 23)

**Comment by skjnldsv** [comment]
@nursoda Can we close?

**Comment by nursoda** [comment]
Sorry I did not respond earlier. I had no time to solve this out since I see similar issues in multiple NC instances each supporting multiple users and NC does not provide tools or documentation that allows me to fix things myself.

Due to time constraints, I did not try your last recommendation. Yet I will one day in the near future.

Sure, you may close the bug, I'll ask to reopen if necessary. But does label "invalid" suggest that this bug that was not caused by software but by me. If so, I'm irritated, since all I did was to upgrade from NC10 to NC11. Before the upgrade, all was fine, after the upgrade, I had trouble getting things back to a usable state.

**Comment by skjnldsv** [comment]
Well, this isn't related to the contacts app, this is why I added the invalid label.
Your database error comes from server.

**Comment by nursoda** [comment]
OK, Thanks.

**Comment by skjnldsv** [comment]
I'm closing this, so if you got any more issues, let me know :)

**Comment by nursoda** [comment]
I will.
Thanks a lot for your kind support.
