### ISSUE TITLE
[Vue] Cleanup css file names

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/contacts#660]
- [ ] use vue filenames

**Comment by SerekKiri** [comment]
What do you mean by "vue filenames". Components, index... ?

**Comment by skjnldsv** [comment]
@SerekKiri Hey!
I mean we use two different type of syntax here for our css files, the PascaleCase and kebab case.
But our vue components only use PascaleCase. We should unify this.

e.g. `settings-section.scss` -> `SettingsSection.scss`

**Comment by SerekKiri** [comment]
Ok, i will work on this 👍

**Comment by skjnldsv** [comment]
@SerekKiri Awesome! Feel free to ask if you have any questions :)

**Comment by SerekKiri** [comment]
I made an PR,  I hope this will help 😄
