### ISSUE TITLE
Some fields from android 9 contact apps are not updated on server

### ISSUE THREAD

**Issue by js-d-coder** [nextcloud/contacts#665]
## Steps to reproduce
1. change company name of any contact in android contact app
2. Sync from Settings > Accounts
3. Check Contacts in Nextcloud

### Expected behaviour
Changes made to contact on android 9 contact app should show in Contact app in Nextcloud. Changes made in Contact app in Nextcloud should show in Android 9 contact app.
This happens with only some fields like company, notes. Not with first name, last name fields. I have also tried using open source Simple Contact android app but changes were not present in it either.
I made sure I sync from android settings > accounts
I am using CardDav open source app to sync contacts on nextcloud with android.

### Actual behaviour
Some fields from android 9 contact apps are not updated on server and vice-versa

### Server configuration

**Operating system**: Raspbian GNU/Linux 9 (stretch)

**Web server:** Apache 2.4.25-3+deb9u5

**Database:** Postgresql 9.6+181+deb9u2

**PHP version:** 7.0.30-0+deb9u1

**Nextcloud version:** 14.1

**Contacts version:** 2.1.6

**Updated from an older Nextcloud or fresh install:** Fresh install

**Signing status:** (I dont know what is this, please help)

```
No errors have been found.
```

**List of activated apps:**

```
Enabled:
  - accessibility: 1.0.1
  - activity: 2.7.0
  - bookmarks: 0.13.0
  - bruteforcesettings: 1.1.0
  - calendar: 1.6.2
  - cloud_federation_api: 0.0.1
  - comments: 1.4.0
  - contacts: 2.1.6
  - dav: 1.6.0
  - deck: 0.4.1
  - federatedfilesharing: 1.4.0
  - files: 1.9.0
  - files_pdfviewer: 1.3.2
  - files_rightclick: 0.8.4
  - files_sharing: 1.6.2
  - files_texteditor: 2.6.0
  - files_trashbin: 1.4.1
  - files_versions: 1.7.1
  - files_videoplayer: 1.3.0
  - firstrunwizard: 2.3.0
  - gallery: 18.1.0
  - issuetemplate: 0.4.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.2.0
  - nextcloud_announcements: 1.3.0
  - notes: 2.4.2
  - notifications: 2.2.1
  - oauth2: 1.2.1
  - password_policy: 1.4.0
  - provisioning_api: 1.4.0
  - quota_warning: 1.3.0
  - serverinfo: 1.4.0
  - sharebymail: 1.4.0
  - support: 1.0.0
  - survey_client: 1.2.0
  - tasks: 0.9.7
  - theming: 1.5.0
  - twofactor_backupcodes: 1.3.1
  - updatenotification: 1.4.1
  - workflowengine: 1.4.0
Disabled:
  - admin_audit
  - encryption
  - federation
  - files_external
  - systemtags
  - user_external
  - user_ldap
```

**Nextcloud configuration:**

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "raspberry",
            "192.168.*.*"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "14.0.1.1",
        "overwrite.cli.url": "https:\/\/raspberry\/picloud",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false
    }
}
```

**Are you using external storage, if yes which one:** No

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:* none

### Client configuration
**Browser:** Any - Chromium, Firefox

**Operating system:** Elementary OS 0.4.1 based on Ubuntu 16.04

**CardDAV-clients:** CardDav for accounts, Contacts of android 9 stock

#### Web server error log
```
There are no errors for the day I am having this issue
```

#### Nextcloud log (data/nextcloud.log)
Too long to paste here, link: https://transfer.sh/gs1DP/nextcloud.log

#### Browser log
```
No errors in console or network
```

Thanks

**Comment by skjnldsv** [comment]
@js-d-coder Hello!
usually synchronisation issues are not related to this app since we're just a contact editor (basically).
If you manually download your contact on the contacts app and open it in a text editor, do you find the informations you edited on your phone?

If not, this will means this is coming from your phone because the contact your phone sent to nextcloud is the exact same you just downloaded. :)

**Comment by js-d-coder** [comment]
@skjnldsv 
I have did an experiment, I uploaded the backup of contact I had to Nextcloud Contact and found that fields like notes are preserved. But when I sync them to phone they disappear.
So where could be the error?

**Comment by js-d-coder** [comment]
problem is from cardDav, which provides full functionality, last time I checked, to premium users.
