### ISSUE TITLE
Contacts not working behind reverse proxy

### ISSUE THREAD

**Issue by schaarsc** [nextcloud/contacts#668]
### Steps to reproduce
1. setup apache2 reverse proxy in front of NC, with mod_proxy_html and ProxyHTMLEnable On
2. open contacts in nextcloud

### Expected behaviour
open available contacts

### Actual behaviour
empty page

### Server configuration
**Web server:** Apache2 with mod_proxy_html
**Nextcloud version:** 14.0.3
**Contacts version:** 2.1.6

### Problem
Contacts is using templates. These templates use file extension .html and are retrieved using GET. Because of the file extension templates are "intercepted" by mod_proxy_html and passed to xml2enc. xml2enc cannot parse the templates and reports "Skipping invalid byte(s) in input stream!". as a result angular.js gets an empty response and the application is not working.

### Possible solution
instead of .html use .html_template or .txt for those files

**Comment by skjnldsv** [comment]
COntacts 3.0.0 doesn't use templates like that anymore and works behind reverse proxy :)
