### ISSUE TITLE
Contact app should handle field labels correctly also if written in lowercase

### ISSUE THREAD

**Issue by j-ed** [nextcloud/contacts#67]
## Expected behavior

The Contacts app should handle phone number or email labels correctly, independently if they're stored in one or multiple lines or written in lowercase.

## Current behavior

The Contacts app doesn't handle phone number or email labels correctly if they're stored in one or multiple lines or written in lowercase. Instead strange labels will be displayed in a contact record.
Additionally it is not possible to correct these records using the web GUI. The field label will be kept unchanged. If you export a contact record to vcf-file, manually delete the `X-ABLABEL` field and reimport the vcf-file the field labels can be edited again using the web GUI.

Example:

![20161225_nc_home_prefs](https://cloud.githubusercontent.com/assets/2572764/21472024/8854eaf4-cac7-11e6-9f5d-cc75c432023d.png)
![20161225_nc_cell_prefs](https://cloud.githubusercontent.com/assets/2572764/21472027/8db08364-cac7-11e6-986c-088e6dbd076b.png)
```
3V1RRX.TEL;TYPE=HOME\,VOICE:+49 2222 3333333
3V1RRX.X-ABLABEL:home\,pref

IX9FXH.TEL;TYPE=CELL:+49 2222 3333333
IX9FXH.X-ABLABEL:cell\,pref

KX0S98.TEL:+49 2222 3333333
KX0S98.X-ABLABEL:work,pref
```

### Steps to reproduce
1. Import a vcf file which contains the mentioned syntax.
2. Try to change the field labels using the web GUI.

#### Server Configuration

OS: Linux 3.2.82
Web server: Apache2 2.4.25
Database: MariaDB 5.5.53
PHP version: 5.6.23
Nextcloud version: 10.0.2
Contacts app: 1.5.2
#### Client Configuration

Browser: Mozilla Firefox 50.1.0
Operating system: Windows 7

**Comment by skjnldsv** [comment]
Could be great to use the android list:

> TYPE_HOME -> HOME
> TYPE_MOBILE -> CELL
> TYPE_WORK -> WORK
> TYPE_FAX_WORK -> WORK,FAX
> TYPE_FAX_HOME -> HOME,FAX
> TYPE_PAGER -> PAGER
> TYPE_OTHER -> VOICE
> TYPE_CAR -> CAR
> TYPE_ISDN -> ISDN
> TYPE_OTHER_FAX -> FAX
> TYPE_TELEX -> TLX
> TYPE_WORK_MOBILE -> WORK,CELL
> TYPE_WORK_PAGER -> WORK,PAGER
> TYPE_MMS -> MSG
