### ISSUE TITLE
Sync existing contact not working

### ISSUE THREAD

**Issue by Phil1988** [nextcloud/contacts#671]
I am using Nextcloud 14.0.3 and Android 6.0.1 with Davdroid.

Synchronised changed data from an existing contact does not change in the contacts app of my phone.

### Steps to reproduce 
When I create a contact on either the contacts app on Nextcloud or my phone the new contact is send/synchronised correctly.

If the contact was created on the cloud I can change it there as often as I want. Everything is working and changed on may phone.

If the contact was created on the phone or was once edited on the phone, it synchronises it correctly to the cloud, BUT if I then edit it again on the cloud, the contact has a strange behaviour:
The new name ist NOT shown in the contacts app on the phone.

I tried that several times and can reproduce it every time.

The strange thing is, that the old name is shown on the phones contact app, but if I edit it, the new name is correctly in the name field.
I can cancel the edit or press 'save' (without changing the name) and can still see the wrong old name.
If I edit the name and delete one letter and replace it with the same and then press 'save', the contact is shown correctly.

### Expected behaviour
The contacts changed 'attribute' should be changing the contact in my phone. 

### Actual behaviour
The contact is by not changing on my ohones contacts app, but the new data was send/synced to my phone as I can see the data when I try to edit this contact.

I am currently not at home and can't give all the coming information. 
I will edit it, when I am back home and if you guys think it is important. 
I will leave the form as default to know what information is needed and where I can find it.
### Server configuration

**Operating system**:
dietpi

**Web server:**
apache2

**Database:**
mysql

**PHP version:**
7

**Nextcloud version:** 
14.0.3

**Contacts version:** 2.1.6

**Updated from an older Nextcloud or fresh install:**
fresh install

**Signing status:**

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your instance's installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

**Are you using external storage, if yes which one:** using internal storage

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**

**Operating system:**

**CardDAV-clients:**

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by skjnldsv** [comment]
Hey @Phil1988!
When you edit the contact on nextcloud, does the contact get saved?
If so this is not related to the contacts app as this is behaving properly.
Unfortunately it will means that the sync between nextcloud and your phone is misbehaving.
What CardDAV-client are you using?

**Comment by Phil1988** [comment]
Hallo @skjnldsv !
Thanks for you kind message :)

Well I found out that the problem is a bit different then I noticed before (on my phone the overview is a bit worse then on my computer right now):
Everything is synced correctly, but the nextclouds contacts app has a small problem.
I can change the nam in 2 different fields.
The first field is the one in a big font with a colored background (that I changed in the past - I call it BIG FIELD).
If I change something here then only this field is changed.

But there is a 2nd field called "First name".
This field is not automatically changed.
If I sync now, then the input of the BIG FIELD is send and I can see it, only when I edit the contact.
The BIG FIELD input is the name that is in the contacts list of my phone.

If I change the input of the "First name"'s field, then the input of the BIG FIELD ist automatically changed and the sync is correct.

I might be wrong, but I would say it is a bug that the BIG FIELD is not automatically changed with the input of the "First name"'s field.

I hope you have a hint for that and I can close this issue here (sorry for the wrong notice of this issue, but on a mobile device screen its really not that visible).

btw: I am using DAVdroid for my phone :)

**Comment by skjnldsv** [comment]
Aaah, it make sense now! :D 
It's because contacts have two fields:
1. displayname
2. detailed name

**Comment by Phil1988** [comment]
Why does the displayname change automatically, when I change the detailed name, but not vice versa?

Is there any fix for that, so that these fields always match?

**Comment by skjnldsv** [comment]
@Phil1988 This is a feature that we changed in the 3.0.0 version
Nonetheless this behavior is the same as the Android app for example, but it  also sync from the displayname to fullname as well.

This is therefor fix in the next version :)

**Comment by Phil1988** [comment]
Thanks a lot for the information given and the help.
You already closed this issue, so I dont have to ;)

Cheers!
