### ISSUE TITLE
CardDAV and CalDAV *Client in Nextcloud web interface*

### ISSUE THREAD

**Issue by GM-G** [nextcloud/contacts#676]
Hello,

Nextcloud's web interface can become a do-a-lot from one point solution - files, calls, email client, contacts, cal, tasks, note.

Currently though it can only act as server for contacts and calendars, am I missing out on detecting how to use it as a client as well? While we share addressbok with other same-nextcloud users, there is no way to add a third party CardDAV addressbok, nor a CalDAV to the calendar module (only ICS on the calendar app which is not a solution for proper sharing as opposed to simple accessing the calendar data)

I'd like the contacts and calendar (should I create a separate issue/request) Apps to have a client to start a sync against third party CardDAV / CalDAV servers.

The current setup requires a client to be used / which is fine but my point is to give users full flexibility from their own nextcloud page

Thanks,
GMG

**Comment by skjnldsv** [comment]
Hello!
I'm not sure I understand properly. You want us to support other syncing options than CalDav/CardDav?

**Comment by GM-G** [comment]
Hoping I am not missing out on something but:

Yes I wish to see a group of contacts from another carddav server inside Nextcloud webpage in the contacts app.

The same for caldav and other sets of webdav resources.

Point is now the contacts shown are hosted in nextcloud but it would be nice to access those from pre-existing collaboration suite so users can switch freely between one and the other.

**Comment by skjnldsv** [comment]
@GM-G Could you suggest from what services you wish to share the contacts with nextcloud?

**Comment by MeCias** [comment]
I understand it like to subscribe to another carddav server within the contacts app. As you would do in Thunderbird with different provider (own Address-book from Nextcloud and maybe one from posteo, one from Google, etc). Vice versa the calendar app.

**Comment by skjnldsv** [comment]
If this is the case, I will have to say that this is out of scope for us.
The contacts app is already complicated enough and I would rather keep it simple :)

**Comment by skjnldsv** [comment]
Closing as out of scope
