### ISSUE TITLE
3500 contacts and Contacts web app is near-unusably slow

### ISSUE THREAD

**Issue by GM-G** [nextcloud/contacts#677]
Slow App on webpage. Creating a new contact and adding several new groups in the same moment and it is all but snappy.

I copied 3500 contacts into the Contacts App synced by a phone
Went online to create groups. The sole creating a new contact takes like 2-3 seconds to start creation. 

Any character typed in takes time / not simply instantaneous.
Is it because it is constantly saved without the user pressing a final save button

What I'd expect is a fast user experience
On a no-contacts test account on the same server it is adequately fast.

Currently it is dead slow for frequent operation as needed. (frequent addition and editing of contacts from the web interface)

### Server configuration
Server on Debian 9
OSX Firefox Client behaving quickly in other pages.

Apache2 

MariaDB

PHP 7.0.30-0+deb9u1

14.0.3 Server 
 2.1.6 Contacts App

Fresh install using old Files and Database, apps from scratch and just started using the other apps.
**Signing status:**
No errors have been found.
```

**List of activated apps:**
```
Enabled:
  - accessibility: 1.0.1
  - activity: 2.7.0
  - admin_audit: 1.4.0
  - apporder: 0.5.0
  - audioplayer: 2.4.1
  - bruteforcesettings: 1.1.0
  - calendar: 1.6.3
  - cloud_federation_api: 0.0.1
  - comments: 1.4.0
  - contacts: 2.1.6
  - dav: 1.6.0
  - deck: 0.4.1
  - dicomviewer: 1.0.2
  - encryption: 2.2.0
  - end_to_end_encryption: 1.0.5
  - external: 3.1.0
  - federatedfilesharing: 1.4.0
  - files: 1.9.0
  - files_accesscontrol: 1.4.0
  - files_external: 1.5.0
  - files_linkeditor: 1.0.7
  - files_pdfviewer: 1.3.2
  - files_rightclick: 0.8.4
  - files_sharing: 1.6.2
  - files_texteditor: 2.6.0
  - files_trashbin: 1.4.1
  - files_versions: 1.7.1
  - files_videoplayer: 1.3.0
  - fulltextsearch: 1.0.3
  - gallery: 18.1.0
  - groupfolders: 1.3.3
  - impersonate: 1.1.0
  - issuetemplate: 0.4.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.2.0
  - mail: 0.11.0
  - mindmaps: 0.1.0
  - notes: 2.4.2
  - notifications: 2.2.1
  - oauth2: 1.2.1
  - ocsms: 1.13.1
  - password_policy: 1.4.0
  - phonetrack: 0.3.6
  - provisioning_api: 1.4.0
  - quota_warning: 1.3.0
  - radio: 0.6.3
  - richdocuments: 3.0.1
  - serverinfo: 1.4.0
  - sharebymail: 1.4.0
  - sharerenamer: 2.2.0
  - socialsharing_email: 1.0.4
  - spreed: 4.0.0
  - systemtags: 1.4.0
  - tasks: 0.9.7
  - theming: 1.5.0
  - twofactor_backupcodes: 1.3.1
  - twofactor_nextcloud_notification: 0.2.4
  - twofactor_totp: 1.5.0
  - w2g2: 2.2.3
  - workflowengine: 1.4.0
Disabled:
  - federation
  - firstrunwizard
  - nextcloud_announcements
  - support
  - survey_client
  - updatenotification
  - user_external
  - user_ldap

**Nextcloud configuration:**
sudo -u www-data php occ config:list system
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.dom1.tld”,
            "cloud.dom2.tld”,
            "cloud.dom3.tld”
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "http:\/\/cloud.dom1.tld”,
        "dbtype": "mysql",
        "version": "14.0.3.0",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "log_type": "owncloud",
        "logfile": "\/var\/log\/nextcloud\/nextcloud.log",
        "loglevel": 2,
        "logdateformat": "F d, Y H:i:s",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379,
            "dbindex": 0,
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "htaccess.RewriteBase": "\/",
        "maintenance": false,
        "theme": "",
        "updater.release.channel": "stable",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpsecure": "ssl",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***"
    }
}

### Client configuration
**Browser:**
Firefox OSX 10.12.6
#### *Web server error log*
```
Insert your webserver log here
```

### Nextcloud log
a failed password every bunch of minutes from a poorly set up client

**Comment by skjnldsv** [comment]
@GM-G Hello!
Could you try the latest contacts beta 3.0.0 ?
This should be fine there.

**Comment by skjnldsv** [comment]
Closing as this is on an old contact app. If it still happen on 3.x.x version, please reopen this issue !
