### ISSUE TITLE
Full CLI Support

### ISSUE THREAD

**Issue by theendcomplete** [nextcloud/contacts#679]
Hi!
Is there a command line interface for a Contacts app?
I mean, a possibility to share contacts, import and edit shared address books via CLI (for cron tasks/integration with 3-rd party systems).

dav utility (https://docs.nextcloud.com/server/14/admin_manual/configuration_server/occ_command.html#dav-label)  doesn't have import options, it creates user's own address book, which can be edited by user.
I need to share an address book without ability for user to change it.

Thank you!

**Comment by skjnldsv** [comment]
Hey @theendcomplete :)
As stated in the bug report model and the Readme:

```
Migration and CardDAV issues belong in the server repo!
https://github.com/nextcloud/server/issues
```

Nonetheless, this is an interesting addition. Please submit this to https://github.com/server after searching that this feature have not yet been requested :)
