### ISSUE TITLE
Contacts app should create human readable vcf-file names when exporting a contact record.

### ISSUE THREAD

**Issue by j-ed** [nextcloud/contacts#68]
## Expected behavior

The Contacts app should create a human readable vcf-file name when exporting a contact record.
E.g. if the full name of a contact is `Tom Johnes` the vcf-file name should be `tom_johnes.vcf` and not `6d9b3192-4eb4-4f6b-81d8-971ddcb6b28f.vcf`.

## Current behavior

The Contacts app uses the UID of a record to create the file name of the vcf-file, like `6d9b3192-4eb4-4f6b-81d8-971ddcb6b28f.vcf`.

### Steps to reproduce
1. Open the Contacts app and export a contact record.
2. Check-out the default vcf-file name.

#### Server Configuration

OS: Linux 3.2.82
Web server: Apache2 2.4.25
Database: MariaDB 5.5.53
PHP version: 5.6.23
Nextcloud version: 10.0.2
Contacts app: 1.5.2
#### Client Configuration

Browser: Mozilla Firefox 50.1.0
Operating system: Windows 7

**Comment by j-ed** [comment]
I've just seen that this problems has already been addressed in the ownCloud repository:
https://github.com/owncloud/contacts/issues/396

**Comment by skjnldsv** [comment]
Same answer, this comes from sabre/dav in core/server.
You need to open the issue there :)

**Comment by blizzz** [comment]
In https://github.com/nextcloud/contacts/blob/master/js/services/contact_service.js#L100  the card file is created using the uuid:

```js
		return DavClient.createCard(
			addressBook,
			{
				data: newContact.data.addressData,
				filename: newUid + '.vcf'
			}
```

This makes sense, since it is an empty data set at this point.

The resulting filename is used in the URL and also always to link to the file for download purposes. 

https://github.com/nextcloud/contacts/blob/master/js/models/contact_model.js#L221 Might be related

**Comment by blizzz** [comment]
The server part is here: https://github.com/nextcloud/server/pull/2940

However contacts will need to add an  "?export" to the download URL once this is merged.

**Comment by Henni** [comment]
@blizzz awesome!
We'll use your server implementation instead. No need to reimplement this in the client.

**Comment by blizzz** [comment]
@Henni no, the client approach is far better, less code and simple :)

**Comment by Henni** [comment]
:+1:
