### ISSUE TITLE
Respect vCard UID on Contacts Import

### ISSUE THREAD

**Issue by Staja** [nextcloud/contacts#682]
It would be good if the vCard UID was respected when importing vCard Contacts into an address book. If an existing contact with the same UID is found, replace the existing contacts attributes with the imported ones.

**Comment by skjnldsv** [comment]
Hello! I thought abou tthis a bit and I think this more error-prone than anything.
Importing a same uid should just deny the overwrite. Even with a warning the regular user wil not understand what an uid is and what this is all about. This could have been a feture some would have wanted, but I will set this as out of scope :)

**Comment by strugee** [comment]
Ref #70 which is where this issue came up originally.
