### ISSUE TITLE
Git master upgrade fails

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/contacts#685]
**Describe the bug**
I did a git pull on master and all apps.

**To Reproduce**
1. git pull
2. see this on reloading page
```
Doctrine\DBAL\Exception\InvalidFieldNameException: An exception occurred while executing 'SELECT `id`, `carddata` FROM `oc_cards` WHERE `uid` IS NULL LIMIT 1000': SQLSTATE[42S22]: Column not found: 1054 Unknown column 'uid' in 'where clause'
```

**Expected behavior**
Smooth updgrade.

**Comment by skjnldsv** [comment]
Nothing to do here :p 
This belong to server :)

**Comment by tobiasKaminsky** [comment]
Damn journey…I was already mislead by cards and opened the issue in deck…
