### ISSUE TITLE
Date fields are not localized

### ISSUE THREAD

**Issue by johkoenig** [nextcloud/contacts#687]
**To Reproduce**
Use a nextcloud with localization, e.g. German.
Pick any user, add birthday or death date.

**Expected behavior**
Dates are shown in localized date format, e.g. German: 31.12.2018

**Actual behavior**
A "technical" date is shown: 2018-12-31

**Screenshots**
![dates](https://user-images.githubusercontent.com/42836313/48092668-98c06d00-e20d-11e8-89fe-d5d22ef39905.PNG)

### Server configuration

**Nextcloud version:** 14.0.3

**Contacts version:** 2.1.6

**Comment by skjnldsv** [comment]
Hello,
Thanks a lot for your report!

This is fixed in the next version :wink:
