### ISSUE TITLE
creating distribution list or contact groups for mailing

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/contacts#688]
Hi, 

I would like to use distribution lists or contact groups in Nextcloud for sendung emails to prebuild groups e.g. "my-coworkers" or "my-best-buddies"

Is that possible? Is that planed? I did not find any Issue about that. Or is there another way to solve that topic?

Thanks!

**Comment by skjnldsv** [comment]
Hello :)
You mean be able to use the contacts groups inside the mail app?

**Comment by jakobroehrl** [comment]
Hello @skjnldsv 
Exactly. I can build contact groups but I can't use them in the Mail/Rainloop App. 
And the groups aren't downloaded to the smartphone via cardDAV. 

What are the difference between the user groups from the Admin area and the contact groups from the contact App?

**Comment by skjnldsv** [comment]
@jakobroehrl users are different from contacts.
So the groups are differents.

We're planning to to a cleanup on those behaviours and simplify the link between users, contacts, groups and circle :)

**Comment by jakobroehrl** [comment]
Hello @skjnldsv
That are great news! When will it be done? Are there any Issues on that topic?
Can I help?

**Comment by skjnldsv** [comment]
Actually there is multiple discussions that relate:
There is the: https://github.com/nextcloud/server/issues/693 `Expose system contacts as address book to users` Which want to show the users data in the contacts as well
There is also https://github.com/nextcloud/server/issues/4643 `Contacts in contact menu needs to be merged`
I will close this issue as this should not be in contacts but in server (sharing components are there)

For the groups/circle/contacts work I don't think there is an official issue opened, but this is an internal discussion :)
