### ISSUE TITLE
Contacts app should allow to remove an assigned contact picture from a contact record

### ISSUE THREAD

**Issue by j-ed** [nextcloud/contacts#69]
## Expected behavior

The Contacts app should allow to remove an assigned contact picture from a contacts record.

## Current behavior

The Contacts app only allows to assign a contact picture to a contact record, but not to remove it.

### Steps to reproduce
1. Open the Contacts app and assign a picture to a contact record.
2. Try to delete the assigned picture from the contact record.

#### Server Configuration

OS: Linux 3.2.82
Web server: Apache2 2.4.25
Database: MariaDB 5.5.53
PHP version: 5.6.23
Nextcloud version: 10.0.2
Contacts app: 1.5.2
#### Client Configuration

Browser: Mozilla Firefox 50.1.0
Operating system: Windows 7

**Comment by irgendwie** [comment]
This feature was already implemented with #54 but wasn't released in a version by now. It will be available with next contacts app release.
