### ISSUE TITLE
Number of displayed contacts to the bottom of the contact list should be grey

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/contacts#7]
https://github.com/owncloud/contacts/pull/453 introduced a number of the displayed contacts at the bottom of the contact list. We should style it in the same way we're doing in the files-app 😉 

### Expected behaviour
Number is displayed in grey.
<img width="849" alt="summ_files" src="https://cloud.githubusercontent.com/assets/19711361/19642369/3f2ca1f4-99e5-11e6-8fbe-2f4dee5abc46.png">

### Actual behaviour
Number of contacts is displayed in black. 
<img width="360" alt="contacts_summ" src="https://cloud.githubusercontent.com/assets/19711361/19642392/53403804-99e5-11e6-86db-584a012babf7.png">
cc @nextcloud/designers

**Comment by irgendwie** [comment]
The number of contacts should be displayed next to the 'All contacts' and group labels in the sidebar and not at the bottom of the list. As discussed at the meetup @jancborchardt

**Comment by jancborchardt** [comment]
Closing in favor of https://github.com/nextcloud/contacts/issues/17 hence. :)
