### ISSUE TITLE
Missing "extended address" field when importing from Google contacts

### ISSUE THREAD

**Issue by nicobo** [nextcloud/contacts#712]
### Describe the bug
When importing contacts from Google contacts (VCF 3.0), the content of the second value of the `ADR` field ([looks like it's called "extended address"](https://tools.ietf.org/html/rfc2426#section-3.2.1)) is empty after import into NextCloud.

**To Reproduce**
1. Go to contacts.google.com
2. Create a contact with content in the "street address" 1st line
3. Export as VCF
4. Go to Nextcloud contacts
5. Import VCF file

Sample VCF : 
```vcf
BEGIN:VCARD
VERSION:3.0
FN:Test Person
N:Person;Test;;;
NICKNAME:MyNameisNobody
EMAIL;TYPE=INTERNET:nobody@nowhere.com
EMAIL;TYPE=INTERNET;TYPE=HOME:nobody@anywhere.com
TEL;TYPE=HOME:0612345678
ADR;TYPE=HOME:;5 anystreet\n12345 somewhere;;;;;
END:VCARD
```

**Expected behavior**
All address fields should be imported into NC Contacts.

**Actual behavior**
The so-called "address" field in Google is not imported into NextCloud contacts.

**Screenshots**
In Google :
![ingoogle](https://user-images.githubusercontent.com/339840/48318828-34831c00-e606-11e8-9fc5-9a079b86ecc2.png)

In NextCloud :
![innccontacts](https://user-images.githubusercontent.com/339840/48318829-364cdf80-e606-11e8-97d2-e8fbb8449d6e.png)

### Server configuration

**Operating system**: Linux 4.14.71-v7+ #1145 SMP Fri Sep 21 15:38:35 BST 2018 armv7l

**Web server:** Apache (apache2handler)

**Database:** mysql 10.1.23

**PHP version:** 7.0.30-0+deb9u1
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, apache2handler, mysqlnd, PDO, xml, apcu, apc, bcmath, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, gmp, iconv, igbinary, imagick, imap, intl, json, exif, mcrypt, msgpack, mysqli, pdo_mysql, Phar, posix, readline, redis, shmop, SimpleXML, smbclient, sockets, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, memcached, libsmbclient, Zend OPcache

**Nextcloud version:** 14.0.3 - 14.0.3.0

**Contacts version:** 2.1.6

**Updated from an older Nextcloud or fresh install:** updated

**Signing status:**
```
Array
(
)
```

**List of activated apps:**
```
Enabled:
 - accessibility: 1.0.1
 - activity: 2.7.0
 - admin_audit: 1.4.0
 - bookmarks: 0.13.1
 - bookmarks_fulltextsearch: 1.0.0
 - calendar: 1.6.3
 - cloud_federation_api: 0.0.1
 - comments: 1.4.0
 - contacts: 2.1.6
 - dav: 1.6.0
 - federatedfilesharing: 1.4.0
 - federation: 1.4.0
 - files: 1.9.0
 - files_antivirus: 1.4.1
 - files_external: 1.5.0
 - files_external_gdrive: 0.2.8
 - files_pdfviewer: 1.3.2
 - files_sharing: 1.6.2
 - files_texteditor: 2.6.0
 - files_trashbin: 1.4.1
 - files_versions: 1.7.1
 - files_videoplayer: 1.3.0
 - firstrunwizard: 2.3.0
 - gallery: 18.1.0
 - issuetemplate: 0.4.0
 - keeporsweep: 0.1.6
 - logreader: 2.0.0
 - lookup_server_connector: 1.2.0
 - news: 13.0.3
 - nextcloud_announcements: 1.3.0
 - notifications: 2.2.1
 - oauth2: 1.2.1
 - password_policy: 1.4.0
 - provisioning_api: 1.4.0
 - serverinfo: 1.4.0
 - sharebymail: 1.4.0
 - support: 1.0.0
 - survey_client: 1.2.0
 - systemtags: 1.4.0
 - theming: 1.5.0
 - twofactor_backupcodes: 1.3.1
 - updatenotification: 1.4.1
 - workflowengine: 1.4.0
Disabled:
 - deck
 - encryption
 - files_opds
 - files_reader
 - user_external
 - user_ldap
```

**Nextcloud configuration:**
```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [***REMOVED SENSITIVE VALUE***
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
    "htaccess.RewriteBase": "\/",
    "dbtype": "mysql",
    "version": "14.0.3.0",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "default_language": "fr",
    "maintenance": false,
    "mail_smtpmode": "smtp",
    "mail_smtpauthtype": "LOGIN",
    "mail_smtpsecure": "tls",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauth": 1,
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "587",
    "memcache.local": "\\OC\\Memcache\\Memcached",
    "memcached_servers": [
        [
            "localhost",
            11211
        ]
    ],
    "theme": "",
    "enabledPreviewProviders": [
        "OC\\Preview\\Image",
        "OC\\Preview\\MP3",
        "OC\\Preview\\TXT",
        "OC\\Preview\\MarkDown",
        "OC\\Preview\\Epub",
        "OC\\Preview\\PDF",
        "OC\\Preview\\OpenDocument",
        "OC\\Preview\\StarOffice",
        "OC\\Preview\\MSOfficeDoc",
        "OC\\Preview\\MSOffice2003",
        "OC\\Preview\\MSOffice2007",
        "OC\\Preview\\FB2"
    ],
    "loglevel": 2
}
```

### Client configuration
**Browser:** Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:63.0) Gecko/20100101 Firefox/63.0

**Operating system:** Ubuntu

**CardDAV-clients:** N/A

**Comment by skjnldsv** [comment]
Hello @nicobo :)
Thanks for your report!
Have you tried the latest Contacts 3.0 alpha?

**Comment by nicobo** [comment]
@skjnldsv No but I will

**Comment by nicobo** [comment]
It looks like with 3.0 alpha the field "Extended address" is correctly displayed and filled !

**Comment by nicobo** [comment]
There are several addresses that could not be imported and the search field is missing though, but it's alpha ;-)

**Comment by skjnldsv** [comment]
@nicobo yes, the beta will have plenty of fixes for that :)
Glad to hear that it's improved for the address field

**Comment by skjnldsv** [comment]
Hello, have you tried the latest stable version? :)
Any news?

**Comment by clotrock** [comment]
I had the same problem and the latest stable version imports the addresses properly.
It is missing custom names for addresses though, but that's is for a different issue

**Comment by skjnldsv** [comment]
@clotrock custom labels?
