### ISSUE TITLE
Contacts button localization 

### ISSUE THREAD

**Issue by NotesTaker** [nextcloud/contacts#713]
Buttons are not in correct language in contacts app.  

Create contact in contacts app having set the localization set to e.g. german. Going to the menu of the contact where you can delete or download the contact it will say "Delete" and "Download" instead of "Löschen" and "Herunterladen"

**Comment by skjnldsv** [comment]
@NotesTaker Hello! Which version of contacts are you using? :)

**Comment by NotesTaker** [comment]
Indeed an essential information :) 
Contacts version is 2.1.6, NextCloud is 14.0.3

**Comment by skjnldsv** [comment]
Awesome!
This then should be fixed with the 3.0.0 :)
