### ISSUE TITLE
add possibility to mark dead people

### ISSUE THREAD

**Issue by Mannshoch** [nextcloud/contacts#735]
I realize I get older and way older people around me sometimes say goodbye for ever.
But what should I do with such people in my contact-list? I do not like the Idea to cleanup and delete them.
Please add the possible to mark people as dead.
Such marked People should not appear in any sync or in the everyone section anymore. Maybe a thumb-stone category at the bottom of the category list would be nice.
In this category entries should appear at first with name, day of death and the note section.

**Comment by skjnldsv** [comment]
Hello! :hugs: 
We currently have the `date of death` field that is available.
Removing them from the sync is unfortunately not possible as it would require us to remove the card from the addressbook. What I could suggest you is to create an addressbook dedicated for the people that you lost and move them in it. On your phone you can then disable the sync of this specific addressbook.

On another note, I'm not against the idea of adding a tombstone icon somewhere if the contact have a death date set, but I'm afraid some people would find that inappropriate or even worse, lacking sensitivity.

**Comment by radoeka** [comment]
Be carefull with this.  A thumbstone is nice for Christian (Chatolic?) people.  But for other religions it may not be appreciated.  Hence, when I'm not mistaken the Gramps webcalendar project provides various icons for death people.
https://www.gramps-project.org/wiki/index.php/Gramps_5.0_Wiki_Manual_-_Reports_-_part_7#Web_Calendar

**Comment by jancborchardt** [comment]
The date of death is already there, and @skjnldsv mentioned the options for if you don't want to have them synced.

As mentioned we should not have an icon. Providing various icons would just be too much work.

Also thought about desaturating their photo or something like that, but people deal with dead loved ones differently and greying them out is a bit strange too.

Simply having the date is a good basis. Either you set it or not, or you remove them from your contacts, or you move them into a dedicated address book, or you make their image grayscale manually, or you add a unicode or emoji icon to their name – lots of possibilities.

**Comment by jancborchardt** [comment]
Sorry, didn't mean to close it right away – @Mannshoch @radoeka is the explanation sufficient?

The point is basically that people deal with death very differently, be it based on relationship with that person or based on religion, or other factors. There's lots of ways you can handle that in Contacts already, and it doesn't feel right to push a specific one.

Does that make sense?

**Comment by radoeka** [comment]
Fine with me.  I just added the remark, to make you (nc contact developers) aware of the issue of adding an icon.  Even when the gesture is nice and with the best intentions.

**Comment by Mannshoch** [comment]
I'm ok with that. I'll create a new address-book.
the Idea with a Unicode Icon in the contact-name will sort this contact on top of the contact list. it seems that the Unicode for a christian cross is sorted before the character A
