### ISSUE TITLE
In dark mode groups in group list are not readable

### ISSUE THREAD

**Issue by radoeka** [nextcloud/contacts#760]
### Describe the bug
In Dark mode the group field is in not readable, as the characters are in black instead of white.

**To Reproduce**
1. Set nextcloud on the web in dark mode
2. Goto a contact, add a group (existing or a new one).  The available groups can't be read.

**Expected behavior**
The list with groups should be readable (white font)

**Actual behavior**
The list with groups is not readable (black font)

**Screenshots**

![image](https://user-images.githubusercontent.com/2937666/50052496-28b6d800-0125-11e9-848c-656dc146f9af.png)

### Server configuration

**Operating system**: Linux

**Web server:** Apache

**Database:** sqlite
**PHP version:** 7.0.1

**Nextcloud version:** 14.0.3

**Contacts version:** 2.1.8

**Comment by radoeka** [comment]
That is a very swift response.  I'll try when 3.0 is (general) available.

**Comment by skjnldsv** [comment]
> That is a very swift response. I'll try when 3.0 is (general) available.

This is released already. You need to upgrade to nextcloud 15 though :)

**Comment by radoeka** [comment]
Solution is confirmed to be working.  Thanks knurpht for testing.
