### ISSUE TITLE
add email address not possible if contact already has one or more email addresses

### ISSUE THREAD

**Issue by Hoppaz** [nextcloud/contacts#771]
### Describe the bug
contacts 3.0.0 with nextcloud 15

It is not possible to add an email address to a contact which already has one (or more than one).
"property-type" disappears from dropdown box.

**To Reproduce**
1. Create new contact with email address
2. Try to add a new email address to contact via property type dropdown box

If the contact already exists without an email address ithe property type is available in dropdown box.
New contacts have at least one empty email address field and so the property type is also not available in dropdown box.

![screenshot-2018-12-17 kontakte - nextcloud 1](https://user-images.githubusercontent.com/1319036/50067009-19846880-01bf-11e9-9609-1446d8c80fd2.png
![screenshot-2018-12-17 kontakte - nextcloud](https://user-images.githubusercontent.com/1319036/50067024-2ef99280-01bf-11e9-8f2d-49aa00ead65b.png)
)

Please let me know if you need more details.

**Comment by skjnldsv** [comment]
That is indeed an issue!
Thanks for the report! This must have slip through!

**Comment by skjnldsv** [comment]
@Slowlyer this issue have already been reported and fixed on #773 :)

**Comment by Slowlyer** [comment]
@skjnldsv  oh so sry.. grat that is an big issue by NC15 with V3

**Comment by fvhockney** [comment]
So I don't mean to be a negative nancy and reopen this comment for nothing, but I really just have to say it. I noticed that this was slated for a 3.0.1 release. That's all well and good, but when looking at your 3.0.1 milestones, this looks like quite a ways off ... its still only 46% complete. Something this major should ideally be hotfixed (and hence the semantic bug release)

**Comment by skjnldsv** [comment]
@fvhockney Don't focus on what is planned on the 3.0.1, this is everything that might be planned for the next patch version, but not necessarily everything that needs to be in it :)
