### ISSUE TITLE
vcard gender not working properly since vue.js

### ISSUE THREAD

**Issue by hirschrobert** [nextcloud/contacts#780]
can someone give some hints, since i am new to vue.js? (@skjnldsv )

vcard `GENDER` has no type parameter according to [rfc 6350](https://tools.ietf.org/html/rfc6350#section-6.2.7), but here is saved with one(`GENDER;TYPE=F:` instead of `GENDER:F`). this probably leads to the superfluous input text field. just the select field with the three options ("female", "male", "other") would be enough.

property heading "Gender" in the view is missing, too. Or some hint what this field is supposed to save.

further the question, how a single gender value (i.e. female) can be saved with both `GENDER:F` and `X-WAB-GENDER:1`? This is necessary for i.e. MS Outlook compatibility.

thanks!
(this is an update for issue #214 )

**Comment by donvipre** [comment]
This issue occurs since Nextcloud 15.0.0 Contacts 3.0.0 app as well.

**Comment by skjnldsv** [comment]
> further the question, how a single gender value (i.e. female) can be saved with both GENDER:F and X-WAB-GENDER:1? This is necessary for i.e. MS Outlook compatibility.

Please open another ticket for that. This is a separate discussion that needs to be discussed.

**Comment by hirschrobert** [comment]
actually this is not solved. the entry is again `GENDER;TYPE=M:` and thus not rfc conform, see my initial [comment](https://github.com/nextcloud/contacts/issues/780#issue-393016680). it needs to be saved as `GENDER:M`. in my last [commit](https://github.com/nextcloud/contacts/pull/825/commits/8565a79ded16a4930d5433ae87b5e2eeffcb2d24) it worked.

**Comment by skjnldsv** [comment]
Raah, dammit you're right! I read the rfc too fast and butchered your pr! :disappointed: 
Shall we revert it?

**Comment by hirschrobert** [comment]
i dont mind continuing with the latest master branch. but i havent figured out the logic of it in detail, yet.

but nextcloud-vue 0.5.0 still gives error
`TypeError: nextcloud_vue__WEBPACK_IMPORTED_MODULE_2__.DatetimePicker.methods is undefined`
even on the latest master branches of server and contacts, making the whole contacts app crash ([see also here](https://github.com/nextcloud/nextcloud-vue/pull/193#issuecomment-452900128)). when i set nextcloud-vue back to 0.4.6. in the contacts package.json manually, it works. so would you set it back until it is fixed?

**Comment by skjnldsv** [comment]
I'd rather revert the pull request first. I'm not happy with what I did. :)
I will then push a fix for the Datepicker.

**Comment by skjnldsv** [comment]
@hirschrobert master is fixed now! The datepicker does not cause any more issue :)
