### ISSUE TITLE
Deleting a contact does not remove them from the group

### ISSUE THREAD

**Issue by cdmlb** [nextcloud/contacts#792]
I created a contact, and in the groups drop down I saw it said list is empty, so decided to type in the box and hit enter, wow to my amazement it created a group. Very confusing app design. Why not use the same groups nextcloud uses?

I now noticed under the All contacts list that a new group is listed.

I decided to delete the contact, the group is still listed as count of 1, instead of 0. I created a new contact in the same group, the group is now listing 2 members even thought there is really 1, since I delete the first.

**Comment by skjnldsv** [comment]
@cdmlb the groups are always linked to contacts. Indeed, if a contact does not exists and was the last member of the group, the group will disappear. This is the default behaviour imposed by the rfc standards. To change this we'll need to support individual vcard groups like stated in #213
