### ISSUE TITLE
3.0.1 does not display address (home/work/other) information

### ISSUE THREAD

**Issue by lyallp** [nextcloud/contacts#793]
⚠ Please report only issues corresponding to the contacts app for Nextcloud ⚠

Migration and CardDAV issues belong in the server repo!
https://github.com/nextcloud/server/issues

If you have any questions, head over to https://help.nextcloud.com/c/apps/contacts
__________________________________________________________________

### Describe the bug
Address information, present in the vcard, is not displayed

**To Reproduce**
1. Establish contact with one or more addresses (ie, using another mechanism such as iPhone sync or existing contact from previous versions)
2. Search for and display contact on browser
3. Addresses not shown.
 
**Expected behavior**
Expect to see all addresses. Additionally, if an address is added, a second and subsequent address cannot be added using the Web UI

**Actual behavior**
No addresses displayed and cannot add more than one.

### Server configuration

**Operating system**: Shared hosting cpanel linux

**Web server:** Apache

**Database:** MySQL

**PHP version:** 7.1

**Nextcloud version:** 15

**Contacts version:** 3.0.1

**Updated from an older Nextcloud**

**Signing status:**
```
Results
=======
- core
	- INVALID_HASH
		- .htaccess
	- EXTRA_FILE
		- .webapp-nextcloud-15.0.0
```

**List of activated apps:**
```
Enabled:
  - accessibility: 1.1.0
  - activity: 2.8.2
  - admin_audit: 1.5.0
  - apporder: 0.6.0
  - bookmarks: 0.15.1
  - calendar: 1.6.4
  - cloud_federation_api: 0.1.0
  - comments: 1.5.0
  - contacts: 3.0.1
  - dav: 1.8.0
  - external: 3.2.0
  - federatedfilesharing: 1.5.0
  - files: 1.10.0
  - files_pdfviewer: 1.4.0
  - files_sharing: 1.7.0
  - files_texteditor: 2.7.0
  - files_videoplayer: 1.4.0
  - firstrunwizard: 2.4.0
  - gallery: 18.2.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.3.0
  - notifications: 2.3.0
  - oauth2: 1.3.0
  - password_policy: 1.5.0
  - provisioning_api: 1.5.0
  - serverinfo: 1.5.0
  - sharebymail: 1.5.0
  - support: 1.0.0
  - survey_client: 1.3.0
  - systemtags: 1.5.0
  - tasks: 0.9.8
  - theming: 1.6.0
  - twofactor_backupcodes: 1.4.1
  - updatenotification: 1.5.0
  - workflowengine: 1.5.0
Disabled:
  - encryption
  - federation
  - files_external
  - files_trashbin
  - files_versions
  - keeweb
  - nextcloud_announcements
  - user_external
```

**Nextcloud configuration:**
```
$ php ./occ config:list system
The current PHP memory limit is below the recommended value of 512MB.
{
    "system": {
        "installed": true,
        "dbtype": "mysql",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "forcessl": false,
        "theme": "",
        "3rdpartyroot": "",
        "3rdpartyurl": "",
        "blacklisted_files": [
            ".htaccess"
        ],
        "default_language": "en",
        "overwritehost": "",
        "overwriteprotocol": "",
        "overwritewebroot": "",
        "overwritecondaddr": "",
        "overwrite.cli.url": "\/",
        "defaultapp": "calendar",
        "knowledgebaseenabled": true,
        "knowledgebaseurl": "http:\/\/api.apps.nextcloud.com\/v1",
        "appstoreenabled": true,
        "appstoreurl": "http:\/\/api.apps.nextcloud.com\/v1",
        "apps_paths": [
            {
                "path": "\/home\/remotely\/www\/cloud\/apps",
                "url": "\/apps",
                "writable": true
            }
        ],
        "mail_smtpdebug": false,
        "mail_smtpmode": "smtp",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtptimeout": 10,
        "mail_smtpauthtype": "LOGIN",
        "appcodechecker": "",
        "log_type": "nextcloud",
        "logfile": "\/home\/remotely\/cloud\/logs\/nextcloud.log",
        "loglevel": 0,
        "logdateformat": "F d, Y H:i:s",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "hashingCost": 10,
        "trashbin_retention_obligation": "180, auto",
        "allow_user_to_change_display_name": true,
        "xframe_restriction": true,
        "custom_csp_policy": "default-src 'self'; script-src 'self' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; frame-src *; img-src *; font-src 'self' data:; media-src *",
        "customclient_desktop": "",
        "customclient_android": "",
        "customclient_ios": "",
        "remember_login_cookie_lifetime": 1296000,
        "updatechecker": true,
        "writable_appsdir": true,
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "version": "15.0.0.10",
        "maxZipInputSize": "838860800",
        "allowZipDownload": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "trusted_domains": [
            "cloud.remotely-helpful.info",
            "cloud.remotely-helpful.com",
            "remotely@vmres08",
            "~\/www\/cloud"
        ],
        "secret": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "appstore.experimental.enabled": true,
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***"
    }
}

```

### Client configuration
**Browser:** firefox 64

**Operating system:** Gentoo linux

**CardDAV-clients:** iPhone, Thunderbird

**Comment by skjnldsv** [comment]
Hello and thanks for you report. I'm having trouble understanding your issue.
Is this happening only on search? Your issue is the missing address when you search a contact?
Could you post a screenshot as well?

**Comment by lyallp** [comment]
Closer examination of various vcards has revealed that ones that I have created the address component on my iPhone have ITEM2.ADDR;TYPE=HOME;TYPE=pref 
rather than ADR; TYPE=home;LABEL=....
I have attempted to anonymise 2 VCARD files exported from Nextcloud, so line length may be off but the field identifiers are unchanged, it would 'appear' that address info created on my iPhone (latest IOS) is the problem.

[Ute (yes address).vcf.gz](https://github.com/nextcloud/contacts/files/2711060/Ute.yes.address.vcf.gz)
[Val (no address).vcf.gz](https://github.com/nextcloud/contacts/files/2711061/Val.no.address.vcf.gz)

An additional problem is that if I try to add an address to 'Val', using the Web Interface (not the iPhone, because it already shows on the iPhone), 
1. I can add the new 'blank'
2. I start to fill out the new 'blank'
3. I am notified that the contact has been changed and further edits will be discarded
4. I re-load the contact which now shows a partially filled new address
5. I resume entering the address details and then am notified again that further edits will be discarded
6. Reload the contact, a bit more info has been recorded

BTW. My phone only syncs when I use the contacts app, I try to save battery by disabling ALL push.

**Comment by lyallp** [comment]
Additional fiddling by editing a contact in my iPhone can change the number of item#. entries if I choose types that are 'standard', for example, phone, if I choose home or work, item#.TEL changes to a TEL, however, if I choose iPhone, it is recorded as an ITEM#.TEL
I am also seeing nonstandard stuff in the ADR entries, "type=WORK;type=pref" when I expected to see something like "type=WORK;pref=1"
I don't envy you trying to address all this bullshit behaviour, and this is only between iPhone and Nextcloud, let alone other clients.
I would almost be tempted to do a regexp replace of `^item[0-9]+\.` with nothing on receipt of a vcard **then** process it.

**Comment by brettferrell** [comment]
I believe I am also seeing this issue (in addition to the annoying searching bug that appears to be related to capitalization).  The symptoms....

I add an address to a contact, it saves and appears good.  It syncs to my iOS devices fine, and I can see the address there no problem, but the next time I come into the contact it is not displayed.  I can add an address field and enter data, and it creates another address field on my iOS devices.

Related, sometimes when I'm editing a contact and want to add both a home and work address, the fields are 'connected', when I edit the one the data changes in the other, so I cannot have different data in each.  Very odd and annoying.

This might be related to how/where the data was created.  I was moving from a VM in a QNAP NAS to a VM on a Proxmox server so I exported my contacts and reimported them into the new instance.  My intuition is that data I have only entered in Nextcloud web interface works OK, but I'll try to prove this if it's helpful.  But right now, when syncing with iOS, the app is pretty buggy and frustrating for me.

**Comment by brettferrell** [comment]
Strike that, I just added a new entry in the web app (just upgraded to 3.0.2 on NC15 on Ubuntu 16.04 VM) and when it sync'ed to my iPad pro it brought the work and home addresses I entered, but also a Home address from a previously entered contact that I did not create for this contact.

**Comment by brettferrell** [comment]
Also, just went to create another new contact to see if this repeats, and it pulled data from the previous contact's work address into the home address field for some reason.  All on Chrome browser Version 68.0.3440.106 (Official Build) (32-bit)

**Comment by brettferrell** [comment]
Another oddity I just noticed.  I was putting "Sam" in all of my test contacts to make them easier to find/check, and a contact that does not include "Sam" anywhere in it popped up.  I downloaded the contact to see why, and it appears search is also searching the 'encoded photo' field, which I think is not the intent.

**Comment by lyallp** [comment]
I find search does not successfully search notes. I have contacts with a keyword in the notes and Search does not find them.

**Comment by brettferrell** [comment]
@lyallp try changing the capitalization.  I find that sometimes if I add/remove capitalization it returns very different results (which was a surprise to me - 'sam' and 'Sam' return different sets).

**Comment by lyallp** [comment]
@brettferrell regardless of case

**Comment by skjnldsv** [comment]
Sorry about the wait :)
So if I understand the issue, this is just because we get properties like `ITEM2.ADDR;TYPE=HOME;TYPE=pref` ?

I could add an automated fix for that.
Though There is an already opened issue about supporting ITEM.XXX properties somewhere I think :thinking:

**Comment by lyallp** [comment]
If there is already an issue to support ITEM.XXX then feel free to close this issue and focus on that one.

**Comment by JAKuhr** [comment]
@skjnldsv 

Perhaps you mean this issue: https://github.com/nextcloud/contacts/issues/42
But for me it doesn't seem related.

**Comment by skjnldsv** [comment]
@JAKuhr thanks! Yes this is the one :)
@lyallp do you concur that this is just the issue you're experiencing?

**Comment by skjnldsv** [comment]
Closing as duplicate then, see #42
