### ISSUE TITLE
Vcard import of "NOTE:" field stops at comma

### ISSUE THREAD

**Issue by tdoerschel** [nextcloud/contacts#798]
⚠ Please report only issues corresponding to the contacts app for Nextcloud ⚠

Migration and CardDAV issues belong in the server repo!
https://github.com/nextcloud/server/issues

If you have any questions, head over to https://help.nextcloud.com/c/apps/contacts
__________________________________________________________________

### Describe the bug
I import a VCARD v3.0 file (UTF-8) with NOTE: field.
All text after a comma is ignored by the importer.

**To Reproduce**
1. Go to Calender
2. Click on 'Import from'
3. Select a vcf file with content below
4. check "notes" section of contact "TEST NAME" in NC

> BEGIN:VCARD
> VERSION:3.0
> N:TEST NAME;;;;
> FN: TEST NAME
> NOTE:Text before comma, text after comma
> END:VCARD

**Expected behavior**
Full note should be imported, including the comma and text afterwards.

**Actual behavior**
Only text of note before comma is imported

**Screenshots**

### Server configuration

**Operating system**: Windows, Linux, MacOS...
Hetzner webhosting
**Web server:** Apache, Nginx...
Hetzner webhosting
**Database:** MariaDB, MySQL, PostgreSQL... 
MySQL
**PHP version:** 7.0, 7.1, 7.2...
7.1
**Nextcloud version:** (see Nextcloud admin page)
15.0.0
**Contacts version:** (see Nextcloud apps page)
3.0.1
**Updated from an older Nextcloud or fresh install:**
Fresh install
**Signing status:**
```
No errors have been found.
```

**List of activated apps:**
```
All that comes with 15.0.0 standard installation
```

**Nextcloud configuration:**
```
<?php
$CONFIG = array (
  'instanceid' => '',
  'passwordsalt' => '',
  'secret' => '',
  'trusted_domains' => 
  array (
    0 => '',
  ),
  'datadirectory' => '',
  'overwrite.cli.url' => '',
  'dbtype' => 'mysql',
  'version' => '15.0.0.10',
  'dbname' => '',
  'dbhost' => '',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => '',
  'dbpassword' => '',
  'installed' => true,
  'updater.release.channel' => 'stable',
  'maintenance' => false,
  'theme' => '',
  'loglevel' => 2,
  'defaultapp' => 'apporder',
  'mail_from_address' => 'nc',
  'mail_smtpmode' => 'smtp',
  'mail_domain' => '',
  'mail_smtpauth' => 1,
  'mail_smtphost' => '',
  'mail_smtpport' => '587',
  'mail_smtpname' => '',
  'mail_smtppassword' => '',
  'mail_smtpsecure' => 'tls',
);

```

### Client configuration
**Browser:**
Firefox 64.0 (64 bit)
**Operating system:**
Windows 10 Pro

#### *data/nextcloud.log*
```
no entry generated during import
```

**Comment by skjnldsv** [comment]
Hello @tdoerschel 
your vcard is incorrect. Inside the note field, any comma must be escaped.
A proper one would be:

> BEGIN:VCARD
> VERSION:3.0
> N:TEST NAME;;;;
> FN: TEST NAME
> NOTE:Text before comma\, text after comma
> END:VCARD
