### ISSUE TITLE
"index.php/apps" links are not working

### ISSUE THREAD

**Issue by weeman1337** [nextcloud/contacts#802]
### Describe the bug
Links using the `index.php/` schema are not working for the contacts app.  
It works on the same system for other URLs like, files app or settings.

Closes nextcloud/server/issues/13265

**To Reproduce**
1. Open any contact
2. Modify the path and put `index.php` to the front
  e.g. https://nc.local/apps/contacts#/contact/a8e331ef-944d-4906-a9b2-5c696bcd9d63  
  → https://nc.local/index.php/apps/contacts#/contact/a8e331ef-944d-4906-a9b2-5c696bcd9d63
3. Open this URL

**Expected behavior**
The contact is displayed.

**Actual behavior**
Nothing displayed.

**Screenshots**
![image](https://user-images.githubusercontent.com/6216686/50541759-79f6ab00-0bac-11e9-99af-7b60ed5ff5fa.png)

**Comment by skjnldsv** [comment]
@weeman1337 I'm having issues understanding this.
We're using the OC.generateURL function which automatically prepend the index.php if `oc_config.modRewriteWorking` is set to false. Can you access it without index.php?

**Comment by skjnldsv** [comment]
@weeman1337 bump?

**Comment by weeman1337** [comment]
@skjnldsv sorry, I missed the previous notification.

Yes, it works without `index.php`. It doesn't if you add it. Have a look at the original issue, reported in the server repo. There the API is called including the `index.php`.

The question is: should it work in both cases: with and without `index.php`?

If yes: then there should be a fix here  
no: the link generation from the original issue should be fixed. Then close this one here please.

**Comment by skjnldsv** [comment]
> The question is: should it work in both cases: with and without index.php?

No, is index.php is supported the server is designed to be used without it. At least the url generation algorithm we used is working like that :)
Though we should probably add a redirect on contacts then :thinking:
