### ISSUE TITLE
two address fields are connected after adding a phone number

### ISSUE THREAD

**Issue by violoncelloCH** [nextcloud/contacts#803]
### Describe the bug
For a contact with e.g. a home and a work address, after adding or removing a phone number entry, these two addresses are connected and typing into one of them simultaneously changes the other one. (You are actually just changing one of them, regardless in which one you type, only one of them is overwritten, you just can't edit / see the other address until you make a browser refresh.)

**To Reproduce**
1. Go to a contact entry with two addresses (e.g. work and home)
2. Add a new "Phone" field or remove one
3. See the two addresses displaying the same values and on typing both of the addresses 
4. type in one of the addresses and see the other one changing at the same time

**Expected behavior**
both addresses should still be correctly displayed and you should be able to edit both of them independently

**Actual behavior**
the two addresses are synchronised and you therefore can't see the other address (because one of them overwrites the other)

**Screenshots**
![image001](https://user-images.githubusercontent.com/22591354/50546112-97665c00-0c22-11e9-9429-ab50f8ff2ce2.jpg)

### Server configuration
**Operating system**: Linux

**Web server:** Apache

**Database:** MariaDB

**PHP version:** 7.2

**Nextcloud version:** 15.0.0

**Contacts version:** 3.0.1

**Signing status:**
```
No errors have been found.
```

### Client configuration
**Browser:** Firefox 64.0

**Operating system:** Win 10 / Ubuntu 18.10

**Comment by skjnldsv** [comment]
An issue with the vuejs keys indeed!
Nice catch! :+1:
