### ISSUE TITLE
Creating a contact results in two PUT requests with same content

### ISSUE THREAD

**Issue by raimund-schluessler** [nextcloud/contacts#804]
### Describe the bug
When you create a new contact, you see two PUT requests with the same content. While this does not affect the functionality, I think the second request is not necessary.

**To Reproduce**
1. Create a new contact.
2. See two PUT requests and a PROPFIND.

This is because when a contact is created first line https://github.com/nextcloud/contacts/blob/master/src/store/contacts.js#L288 is called. Afterwards https://github.com/nextcloud/contacts/blob/master/src/store/contacts.js#L297 is called as well.

**Contacts version:** (see Nextcloud apps page)
Current master 8c4e9cbe3ce9f24216dd489cc3ca41054a654694

@skjnldsv Is this a wanted behaviour? Did I miss something?

**Comment by skjnldsv** [comment]
> @skjnldsv Is this a wanted behaviour? Did I miss something?

Most likely a sync that gets triggered. Should not happens indeed! :)
Thanks @raimund-schluessler :+1:
