### ISSUE TITLE
Group cannot be removed

### ISSUE THREAD

**Issue by lpet** [nextcloud/contacts#81]
It seems that you can only add more groups to a contact, but removing a group is not possible

### Steps to reproduce
1. Create a new contact
2. Add contact to one (existing) group
3. Add contact to a second (existing) group
4. Try to remove contact from teh first group

### Expected behaviour
There should be a trash bin icon next to each groupo label or any other obvious way to remove a group

### Actual behaviour
The groups the contact belongs to are displayed. Clicking on a group name doesn't do anything. Clicking in the groups-field next to the contact labels brings up the drop down of all not selected groups. Clicking one of them add the group.

![2016-12-30 21_54_35-kontakte - nextcloud](https://cloud.githubusercontent.com/assets/4774592/21572800/cb7c481c-cedd-11e6-887a-00a0e548b13d.png)

### Server configuration
**Operating system**:
Raspbian

**Web server:**
Apache 2.4.10

**Database:**
MariaDB 10.0.28

**PHP version:**
5.6

**Nextcloud version:** (see Nextcloud admin page)
11.0.0.

**Contacts version:** (see Nextcloud apps page)
1.5.2
![2016-12-30 21_54_30-apps - nextcloud](https://cloud.githubusercontent.com/assets/4774592/21572810/dd94b552-cedd-11e6-9138-593b4305c72e.png)

**Updated from an older Nextcloud or fresh install:**
Updated

**Signing status:**
No errors have been found.

**List of activated apps:**
Enabled:
  - activity: 2.4.1
  - bookmarks: 0.9.1
  - calendar: 1.4.1
  - contacts: 1.5.2
  - dav: 1.1.1
  - federatedfilesharing: 1.1.1
  - files: 1.6.1
  - files_external: 1.1.2
  - files_pdfviewer: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - mail: 0.6.2
  - nextcloud_announcements: 1.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - survey_client: 0.1.5
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - updatenotification: 1.1.1
  - workflowengine: 1.1.1
Disabled:
  - admin_audit
  - comments
  - encryption
  - external
  - federation
  - files_accesscontrol
  - files_automatedtagging
  - files_retention
  - systemtags
  - templateeditor
  - user_external
  - user_ldap
  - user_saml

**The content of config/config.php:**
{
    "system": {
        "instanceid": "XXXX",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [ XXX ],
        "datadirectory": "\/mnt\/fancyDrive\/nextcloud_data\/",
        "overwrite.cli.url": "XXXXX",
        "dbtype": "mysql",
        "version": "11.0.0.10",
        "dbname": "nextcloud",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "tls",
        "mail_smtphost": "smtp.gmail.com",
        "mail_smtpport": "587",
        "mail_smtpauth": 1,
        "mail_from_address": "XXXXXX",
        "mail_domain": "gmail.com",
        "mail_smtpauthtype": "PLAIN",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "appstore.experimental.enabled": true,
        "loglevel": 2,
        "theme": ""
    }
}

**Are you using external storage, if yes which one:** local/smb/sftp/...
yes, local

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
Chrome 55.0.2883.87 m
 or
Firefox 50.1.0

**Operating system:**
Windows 8.1

**CardDAV-clients:**
(also in use, but not showing this issue: ) Android (Davdroid)

### Logs
I don't see any reason to supply logs right now. Tell me if they are necessary.

**Comment by skjnldsv** [comment]
You can remove the different groups by using the delete key. But yes, we should add a click-to-remove button.

**Comment by skjnldsv** [comment]
References: https://github.com/angular-ui/ui-select/issues/1203
Correct use of select2 in files:
```
<div class="select2-container select2-container-multi systemTagsInputField systemtags-select2-container" id="s2id_autogen3">
	<ul class="select2-choices">
		<li class="select2-search-choice">
			<div>    <span class="label">TEST</span></div>
			<a href="#" class="select2-search-choice-close" tabindex="-1"></a>
		</li>
		<li class="select2-search-choice">
			<div>    <span class="label">TEST2</span></div>
			<a href="#" class="select2-search-choice-close" tabindex="-1"></a>
		</li>
		<li class="select2-search-field">    <label for="s2id_autogen4" class="select2-offscreen"></label>    <input type="text" autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false" class="select2-input" id="s2id_autogen4" style="width: 10px;" placeholder="" aria-activedescendant="select2-result-label-11">  </li>
	</ul>
</div>
```

Incorrect of select2 in contacts:
```
<ul class="select2-choices">
	<span class="ui-select-match ng-scope" placeholder="Groups">
		<li class="ui-select-match-item select2-search-choice ng-scope" ng-repeat="$item in $select.selected" ng-class="{'select2-search-choice-focus':$selectMultiple.activeMatchIndex === $index, 'select2-locked':$select.isLocked(this, $index)}" ui-select-sort="$select.selected"><span uis-transclude-append=""><span class="ng-binding ng-scope">test</span></span> <a href="javascript:;" class="ui-select-match-close select2-search-choice-close" ng-click="$selectMultiple.removeChoice($index)" tabindex="-1"></a></li>
		<li class="ui-select-match-item select2-search-choice ng-scope" ng-repeat="$item in $select.selected" ng-class="{'select2-search-choice-focus':$selectMultiple.activeMatchIndex === $index, 'select2-locked':$select.isLocked(this, $index)}" ui-select-sort="$select.selected"><span uis-transclude-append=""><span class="ng-binding ng-scope">test2</span></span> <a href="javascript:;" class="ui-select-match-close select2-search-choice-close" ng-click="$selectMultiple.removeChoice($index)" tabindex="-1"></a></li>
	</span>
	<li class="select2-search-field"><input type="text" autocomplete="false" autocorrect="off" autocapitalize="off" spellcheck="false" role="combobox" aria-expanded="true" aria-owns="ui-select-choices-2" aria-label="Select box" aria-activedescendant="ui-select-choices-row-2-0" class="select2-input ui-select-search ng-valid ng-dirty ng-empty ng-touched" placeholder="" ng-disabled="$select.disabled" ng-hide="$select.disabled" ng-model="$select.search" ng-click="$select.activate()" style="width: 186px;" ondrop="return false;"></li>
</ul>
<div class="ui-select-dropdown select2-drop select2-with-searchbox select2-drop-active select2-display-none" ng-class="{'select2-display-none': !$select.open}" style="opacity: 1;">
	<ul class="ui-select-choices ui-select-choices-content select2-results ng-scope" repeat="group in ctrl.availableGroups | filter:$select.search">
		<li class="ui-select-choices-group" ng-class="{'select2-result-with-children': $select.choiceGrouped($group) }">
			<div ng-show="$select.choiceGrouped($group)" class="ui-select-choices-group-label select2-result-label ng-binding ng-hide" ng-bind="$group.name"></div>
			<ul role="listbox" id="ui-select-choices-2" ng-class="{'select2-result-sub': $select.choiceGrouped($group), 'select2-result-single': !$select.choiceGrouped($group) }" class="select2-result-single">
			</ul>
		</li>
	</ul>
</div>
```

This isn't html5 compliant since there is a span inside the ul.
