### ISSUE TITLE
please delete.. 

### ISSUE THREAD

**Issue by blackcrack** [nextcloud/contacts#835]
Please Delete
@skjnldsv 

this language fit's your not.. f. o. 
YOU have driven me out ....

you can not live with peoples with handicap.. 

the fucking language it IS YOUR PROBLEM, NOT MINE !

IF YOU WANT UNDERSTAND ME IT IS OKEY; BUT IF I AM DISTURB YOU , ITS YOUR PROBLEM !!

**Comment by Jab2870** [comment]
Maybe Open Streetmap would be better. Many people turn to Nextcloud to de-googlify.

**Comment by blackcrack** [comment]
> 
> 
> Maybe Open Streetmap would be better. Many people turn to Nextcloud to de-googlify.

maybe configuration in personally Config,
i like Google maps, you like Open Streetmap, so, make it possible to have different possible, 
this iss my idea, but thank you for want make enhanced ..

Google.com/maps need not a login, and this is good so..
:smiley:

**Comment by skjnldsv** [comment]
Hello @blackcrack 
I will consider it, I don't know exactly how or if we should do it. Though we won't add a dedicated config just to select a maps provider, another option is just confusing for the user. :)

PS: I have trouble understanding your English sometimes. May I suggest you to use https://www.deepl.com, the results are really good, maybe that could help you? :)
Cheers

**Comment by blackcrack** [comment]
i use qtranslate.. and your nose is also nice like my ;)
if your Nose disturbs, looked not on in the mirror.. ;)
My nose is grow up 20 Years and has works up to now so far,
Especially in the years when I gave away and exchanged software 20 years ago..
Something else of topic ? Or do you want to expel me ? if not, delete my/this post.

.... regards
Blackcrack

**Comment by blackcrack** [comment]
po
