### ISSUE TITLE
Search does not include data from `Company` field

### ISSUE THREAD

**Issue by fa-ribeiro** [nextcloud/contacts#843]
**Steps To Reproduce**
1. Create a couple of contacts
2. Create a contact with "XPTO' in the `Company` field
3. Search for "XPTO"

**Expected behavior**
The contact with "XPTO" in the `Company` field should be listed.

**Actual behavior**
The contact with "XPTO" in the `Company` field is not listed.

### Server configuration

**Operating system**: Linux Debian 9

**Web server:** Nginx

**Database:** MariaDB

**PHP version:** 7.2-fpm

**Nextcloud version:** 15.0.0

**Contacts version:** 3.0.1

**Comment by FredericLespez** [comment]
I can confirm this bug. This is the same for the 'Title' field. When you have a lot of contacts, this kind of search is very useful.

**Comment by skjnldsv** [comment]
Hum, I cannot reproduce. :thinking: 
Please make sure this is not a duplicate of #815 ?

**Comment by fa-ribeiro** [comment]
@skjnldsv , you're right this is a duplicate of #815, so I'll close this. Sorry for that :-(

**Comment by skjnldsv** [comment]
@fa-ribeiro Don't be!! Thanks for your help!! :)

**Comment by skjnldsv** [comment]
Duplicate of #815
