### ISSUE TITLE
Use pattern attribute for date fields

### ISSUE THREAD

**Issue by yannickoo** [nextcloud/contacts#845]
**Is your feature request related to a problem? Please describe.**
When trying to enter dates in a format like `dd.mm.yyyy` you get no error or hint regarding the format. The correct format would be `yyyy-mm-dd`.

**Describe the solution you'd like**
It would be so cool to have the `pattern` attribute implemented for that field so that we can define a regex for those fields.

`<input type="text" pattern="[0-9]{4}-(0[1-9]|1[012])-(0[1-9]|1[0-9]|2[0-9]|3[01])">`

You can verify that pattern here in the second example: http://html5pattern.com/Dates

**Comment by skjnldsv** [comment]
Hello! :)
@yannickoo what app version are you using?

**Comment by yannickoo** [comment]
@skjnldsv it's still Nextcloud 13 and yes I know it's definitely time to upgrade 😬 Do you know if this also occurs with the latest version of Nextcloud?

**Comment by skjnldsv** [comment]
@yannickoo You need to upgrade to at least 15 and contacts 3.0.0, I cannot help you on older versions :)
Only security fixes will be updated for older apps.

Please reopen after your upgrade if this is still occuring! :wink:
