### ISSUE TITLE
Contact name displayed as "New contact" for contacts with only a number of enterprise name

### ISSUE THREAD

**Issue by plmrn** [nextcloud/contacts#848]
### Describe the bug

When opening the Contacts tab of Nextcloud, all my contacts that are:
- only a phone number, no first or last name
- only a company name and phone number, no first or last name
are displayed as "New contact" in the contact list.

For contacts *with* a company name, when I click on such a contact to view it, the displayed name updates to the company name and the list is updated accordingly.

**To Reproduce**

1. Create a contact with just a phone number or a phone number and a company name
2. (You might need to delete the "New contact" default text in the "Name" field)
3. Refresh the Contacts tab, or go to another tab then come back to it. The new contact should be at the top of the contacts list listed as "New contact".
4. Click on this contact. If you inserted a company name its displayed name should be updated to the company name and the contact will move accordingly in the alphabetical list.

**Expected behavior**

When a contact has a company name and no first/last name, it should be displayed directly as "Company name" and not show up as "New contact" until I click on it.

When a contact only has a phone number, I guess both actions make sense:
- as is: keep it as "new contact" to single it out
- alternative way: some contact managers (iOS in my recollection) use the phone number as display name when no other information is attached to the contact

**Actual behavior**
The contacts were displayed as "New contact".

**Screenshots**
I can take some screenshots if my explanations are not clear enough, I just need to change the display language of my nextcloud instance to make it english and to redact some phone numbers so let me know if it's necessary.

### Server configuration
Operating system: Linux 4.14.66-ovh-vps-grsec-zfs-classid #1 SMP Thu Aug 23 15:15:40 CEST 2018 x86_64

Webserver: Apache (cgi-fcgi)

Database: mysql 5.5.60

PHP version:

7.0.32 Modules loaded: Core, date, libxml, openssl, pcre, sqlite3, zlib, bcmath, bz2, calendar, ctype, curl, dba, dom, hash, fileinfo, filter, ftp, gd, gettext, gmp, SPL, iconv, imagick, session, intl, json, mbstring, mcrypt, memcached, standard, mysqlnd, PDO, pdo_mysql, pdo_pgsql, pdo_sqlite, pgsql, Phar, posix, pspell, redis, Reflection, imap, SimpleXML, soap, sockets, mongodb, exif, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, mysqli, cgi-fcgi, ionCube Loader

Nextcloud version: 14.0.3 - 14.0.3.0

Updated from an older Nextcloud/ownCloud or fresh install: fresh install

Where did you install Nextcloud from: unknown

**Signing status:**
Raw output
==========
Array
(
    [core] => Array
        (
            [INVALID_HASH] => Array
                (
                    [.htaccess] => Array
                        (
                            [expected] => 70183f641f39fc5f43065aeb15b86ac99e86b82310d5467e1c4d935df30acc6155c0905f84f59616885275c19ffacea59e354a87a5c97c94f50d50d4eff0370e
                            [current] => b6802812526e6b12aab5a12d468a59da3b05fde3aacbae5fc465ab8f7f1039a32ee2a2f0e3686ee95aebe0bfef849d2ceb1ce14e2c3fa2fb74f9b4dad39afccd
                        )

                )

        )

)

**List of activated apps:**
Enabled:
 - accessibility: 1.0.1
 - activity: 2.7.0
 - calendar: 1.6.4
 - cloud_federation_api: 0.0.1
 - comments: 1.4.0
 - contacts: 2.1.8
 - dav: 1.6.0
 - federatedfilesharing: 1.4.0
 - federation: 1.4.0
 - files: 1.9.0
 - files_pdfviewer: 1.3.2
 - files_sharing: 1.6.2
 - files_texteditor: 2.6.0
 - files_trashbin: 1.4.1
 - files_versions: 1.7.1
 - files_videoplayer: 1.3.0
 - firstrunwizard: 2.3.0
 - flowupload: 0.0.9
 - gallery: 18.1.0
 - issuetemplate: 0.4.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.2.0
 - nextcloud_announcements: 1.3.0
 - notes: 2.5.1
 - notifications: 2.2.1
 - oauth2: 1.2.1
 - passman: 2.2.1
 - password_policy: 1.4.0
 - provisioning_api: 1.4.0
 - serverinfo: 1.4.0
 - sharebymail: 1.4.0
 - support: 1.0.0
 - survey_client: 1.2.0
 - systemtags: 1.4.0
 - tasks: 0.9.8
 - theming: 1.5.0
 - twofactor_backupcodes: 1.3.1
 - updatenotification: 1.4.1
 - workflowengine: 1.4.0
Disabled:
 - admin_audit
 - encryption
 - files_external
 - user_external
 - user_ldap

**Nextcloud configuration:**
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "cloud.paulmorin.fr"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "14.0.3.0",
    "overwrite.cli.url": "https:\/\/cloud.paulmorin.fr",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "memcache.local": "\\OC\\Memcache\\ArrayCache",
    "mail_smtpmode": "smtp",
    "mail_smtpsecure": "ssl",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauth": 1,
    "mail_smtpauthtype": "LOGIN",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "465",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "debug": true,
    "maintenance": false
}

### Client configuration
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:64.0) Gecko/20100101 Firefox/64.0

Operating system: MacOS 10.13.6

**Comment by skjnldsv** [comment]
Hello!
Please upgrade to nextcloud 15 and contacts 3.0.1 :)

**Comment by plmrn** [comment]
Hi!
Indeed I didn't even think of checking that, my apologies. Thanks for the fast reply and again, sorry about the useless noise!

**Comment by skjnldsv** [comment]
@plmrn Nothing to apologise for :hugs: 
Keep me updated if this happens again! :)

**Comment by skjnldsv** [comment]
Thanks for taking the time :)
Could you download and paste one of the 'blank' contact here?

**Comment by skjnldsv** [comment]
@plmrn bump! :)

**Comment by plmrn** [comment]
@skjnldsv Pertinent bump, for some reason I didn't see your previous message!

Here is one of the contacts. It's a company so no worries about privacy, their phone number is public.

[edd6141e-1c6c-4006-961a-c01b045ffc71.vcf.zip](https://github.com/nextcloud/contacts/files/2795339/edd6141e-1c6c-4006-961a-c01b045ffc71.vcf.zip)

Let me know if I can help
Thanks

**Comment by skjnldsv** [comment]
@plmrn thanks! Fixed in #880  :wink:

**Comment by skjnldsv** [comment]
If you can help test the build I attached in the issue above that would be awesome :hugs: :)

**Comment by plmrn** [comment]
@skjnldsv Downloaded the archive in #880 and uploaded it in my apps folder (renamed the former "contacts" folder that was already sitting there)
Is there any other step I need to follow? I didn't notice any change after doing what I just described
Thanks

**Comment by skjnldsv** [comment]
@plmrn you need to clear your cache as well :)
There is no other steps. All the 'empty contacts' should be gone now.
