### ISSUE TITLE
Option to select default "Work" or "Home" for new contacts

### ISSUE THREAD

**Issue by tdoerschel** [nextcloud/contacts#855]
When creating a new contact, by default all information (email, phone, address) is set to "Home".
It would be nice to have a settings option that all new contacts are "Work".
Alternatively the new information fields should be generic ("select type" or "Peferred").

Thanks for the great work so far!

**Comment by skjnldsv** [comment]
Thanks for the kind words :)

I'll leave this opened to see if people really want this feature, but I'm not convinced. 
We usually try to avoid adding too many options.

**Comment by tdoerschel** [comment]
How about setting the default to generic phone and email, then?
E.g. neither "home" nor "work" as default.
This way, no extra options are needed.

**Comment by skjnldsv** [comment]
Well, it's better having a default that reflect most of the users. The default is set to 'Home' as it is the most used and the default on android and ios as well (iirc) :)

**Comment by JC5** [comment]
That would be more annoying than helpful really.

**Comment by olantrust** [comment]
When the 'Org' contact type pref is implemented, then those contacts labeled as Orgs could have the 'work' type as default, and 'individual' type contacts would contribute to have 'home' set as default.

**Comment by skjnldsv** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there a no plans to implement such a feature. Thus I will close this ticket for now. Too many options is something we should really avoid, and I think this does not fit our app :)

Thanks nonetheless, I really appreciate your tickets! :)
