### ISSUE TITLE
Expand the Group field in contact details when multiple groups selected

### ISSUE THREAD

**Issue by tdoerschel** [nextcloud/contacts#856]
When adding a contact to multiple groups, the group field does not expand. Instead, the group names are shortened, and further groups are only listed as "+1" etc.

Here is an example from a contact in 7 groups:
VOD-001
VOD-005
VOD-007
VOD-008
VOD-015
Test-2
Test-3

![groups-example](https://user-images.githubusercontent.com/46196223/51102193-49cf1f00-17de-11e9-8c4d-da859680af75.jpg)

It is better if the group field expands so that all groups are shown with full name.

**Comment by SebastianKrupinski** [comment]
Contact groups selection and display has been reworked. This should no longer be an issue.
