### ISSUE TITLE
Add uncategorised group (Not grouped) on the app navigation

### ISSUE THREAD

**Issue by zero-24** [nextcloud/contacts#874]
### Describe the bug

It seams the latest update removed the Information about contacts without Category.

**To Reproduce**

- create contacts without categories
- create contacts with an category.

**Expected behavior**

On the left hand side I would expect an possibility stating what contacts are not on categories. 

**Actual behavior**

I think starting with the latest updates this Information (what contacs are not assigned yet to a categorie) is missing.

**Screenshots**
![contacts](https://user-images.githubusercontent.com/2596554/51552553-1725c600-1e71-11e9-909e-40d51680246c.JPG)

### Server configuration

**Operating system**: Linux

**Web server:** Apache

**Database:** MariaDB, MySQL

**PHP version:** 7.1

**Nextcloud version:** 15.0.2

**Contacts version:** 3.0.2

**Updated from an older Nextcloud or fresh install:** 14.0.0

**Signing status:** No errors have been found.

**Comment by zero-24** [comment]
@nextcloud-bot thanks for your suggestion but they are not related to this issue. Thanks

**Comment by zero-24** [comment]
Found it now. The feature was called `Not grouped`

**Comment by rakekniven** [comment]
Fully support the issue. Please re-add the "Not grouped" entry.

**Comment by zero-24** [comment]
Dear @rakekniven and @skjnldsv can you please have a look into: https://github.com/nextcloud/contacts/pull/905 and give me some feedback there?

**Comment by rakekniven** [comment]
Hey @zero-24, I am not a dev but I am sure @skjnldsv will judge your work the right way.
