### ISSUE TITLE
Papierkorb

### ISSUE THREAD

**Issue by hhhppp28** [nextcloud/contacts#881]
Mir fehlt der Papierkorb in contacts.

Wenn man einen Kontakt löscht, wird nicht nachgefragt und gleich gelöscht.

Ebenso wären Subgruppen sehr hilfreich.

Gruppe1
---Subgruppe1
---Subgruppe2
---Subgruppe3
---......

**Comment by skjnldsv** [comment]
Hello @hhhppp28 
please create your issues in English.
