### ISSUE TITLE
Subgroups

### ISSUE THREAD

**Issue by hhhppp28** [nextcloud/contacts#882]
~~I miss a trash bin in contacts.~~

~~It happens that i deleted a contact and it was gone.~~

Also it would be helpful to have subgroups

Group1
---Subgroup1
---Subgroup2
---Subgroup3
---......

**Comment by skjnldsv** [comment]
@hhhppp28 Hum, sorry about closing the other one. I thought you would edit the original issue!
My apologies :see_no_evil: :wink: 

For the delete feature, there is an opened ticket here: https://github.com/nextcloud/contacts/issues/296

For the subgroups, this is unfortunately not *really* possible. The contact format (VCard) does not support it. BUT what we could do is parse any group and split across a slash.
For example, if you have the following groups:
- Company/Management
- Company/Sales
- Company/Board

It could translate to
- Company
  - Management
  - Sales
  - Board

What do you think? :)

**Comment by hhhppp28** [comment]
the suggestion, i think it is OK. I have to try it. Thanks

I don´t really understand whats in the ticket #296 

Do i have to programm it by my self?
It would be nice if you build it in.

**Comment by skjnldsv** [comment]
@hhhppp28 the ticket #296 is a feature request. It is still opened because the feature have not been coded nor implemented. There are various requests on this repo and not all of them are priorities :)
Usually you have to wait for a developer (me or anyone with the skills) to code it and to request the integration to the main project.

**Comment by jancborchardt** [comment]
@skjnldsv does any other contact system have subgroups? Couldn’t find that in Android contacts or iOS contacts. So it doesn’t really make sense to do a home-baked system for that?

@hhhppp28 The widely used apps treat groups as labels, so what you could do is simply do all the group naming as @skjnldsv describes above, but we don’t do any of the subgroup display magic. Then it would be the same across platforms.

What do you think @skjnldsv? I’d say we close this.
