### ISSUE TITLE
Deleting FN displays nonsense

### ISSUE THREAD

**Issue by Huster-at-github** [nextcloud/contacts#885]
NC 15.0.2
Contacts 3.0.2

1. Deleting FN 
2. Refreshing web site
3. Now private e-mail-address is shown in the overview
  

Deleting FN:

![fn1](https://user-images.githubusercontent.com/3857906/51771457-53635b80-20e9-11e9-9506-eeebf0b3eca8.JPG)

![fn2](https://user-images.githubusercontent.com/3857906/51771467-5f4f1d80-20e9-11e9-88a0-f3879722ea61.JPG)

Refreshing web site
Now private e-mail-address is shown in the overview:

![fn3](https://user-images.githubusercontent.com/3857906/51771485-6bd37600-20e9-11e9-9d1c-c48c890d99b7.JPG)

**Comment by skjnldsv** [comment]
> Deleting FN

You mean setting it as *empty*?

**Comment by Huster-at-github** [comment]
Yes, FN is empty:

BEGIN:VCARD
VERSION:3.0
PRODID:-//Sabre//Sabre VObject 4.1.6//EN
UID:c7d113b8-6977-4056-8922-4d76ae7fef8b
FN:
ADR;TYPE=HOME:adresse-privat-postfach;adresse-privat-erweiterte...;adresse-
 privat-adresse-straße;adresse-privat-stadt;adresse-privat-bundesland;adress
 e-privat-postleitzahl;adresse-privat-land
ADR;TYPE=WORK:adresse-arbeit-postfach;adresse-arbeit-erweiterte...;adresse-
 arbeit-adresse-straße;adresse-arbeit-stadt;adresse-arbeit-bundesland;adress
 e-arbeit-postleitzahl;adresse-arbeit-land
ADR;TYPE=OTHER:adresse-andere-postfach;adresse-andere-erweiterte...;adresse
 -andere-adresse-straße;adresse-andere-stadt;adresse-andere-bundesland;adres
 se-andere-postleitzahl;adresse-andere-land
EMAIL;TYPE=HOME:e-mail-privat
TEL;TYPE="HOME,VOICE":tel-privat
TEL;TYPE="WORK,VOICE":tel-arbeit
TEL;TYPE=CELL:tel-mobil
TEL;TYPE="WORK,CELL":tel-mobil-arbeit
TEL;TYPE="HOME,CELL":tel-mobil-privat
TEL;TYPE=FAX:tel-fax
TEL;TYPE="WORK,FAX":tel-fax-arbeit
TEL;TYPE="WORK,FAX":tel-fax-arbeit
TEL;TYPE=PAGER:tel-pager
TEL;TYPE=VOICE:tel-anruf
TEL;TYPE=CAR:tel-auto
TEL;TYPE="WORK,PAGER":tel-pager-arbeit
ORG:display-firma
TITLE:display-titel
CATEGORIES:WS
N:detaillierter-name-nachname;detaillierter-name-vorname;detaillierter-name
 -zusätzliche;detaillierter-name-präfix;detaillierter-name-suffix
URL:internetseite1
URL:internetseite2
RELATIONSHIP:COLLEAGUE
CLOUD;TYPE=HOME:federated-cloud-id-privat
CLOUD;TYPE=WORK:federated-cloud-id-arbeit
CLOUD;TYPE=OTHER:federated-cloud-id-andere
EMAIL;TYPE=WORK:e-mail-arbeit
EMAIL;TYPE=OTHER:e-mail-andere
NOTE:Notizen\, Notizen\, Notizen\, Notizen\, Notizen\, Notizen\, Notizen\, 
 Notizen\, Notizen\, Notizen\, Notizen\, Notizen\, Notizen\, Notizen\, Notiz
 en\, Notizen\, Notizen\, Notizen\, Notizen
EMAIL;TYPE=HOME:e-mail-privat2
EMAIL;TYPE=HOME:e-mail-privat3
BDAY:20190121T190614
X-SOCIALPROFILE;TYPE=facebook:soziales-netzwerk-facbook
X-SOCIALPROFILE;TYPE=GITHUB:soziales-netzwerk-github
X-SOCIALPROFILE;TYPE=GOOGLEPLUS:soziales-netzwerk-google+
X-SOCIALPROFILE;TYPE=INSTAGRAM:soziales-netzwerk-instagram
X-SOCIALPROFILE;TYPE=LINKEDIN:soziales-netzwerk-pinterest
X-SOCIALPROFILE;TYPE=PINTEREST:soziales-netzwerk-pinterest
X-SOCIALPROFILE;TYPE=QZONE:soziales-netzwerk-qzone
X-SOCIALPROFILE;TYPE=TUMBLR:soziales-netzwerk-tumblr
X-SOCIALPROFILE;TYPE=TWITTER:soziales-netzwerk-twitter
X-SOCIALPROFILE;TYPE=WECHAT:soziales-netzwerk-wechat
X-SOCIALPROFILE;TYPE=YOUTUBE:soziales-netzwerk-youtube
X-SOCIALPROFILE;TYPE=MASTODON:soziales-netzwerk-mastodon
X-SOCIALPROFILE;TYPE=DIASPORA:soziales-netzwerk-diasprora
X-SOCIALPROFILE;TYPE=OTHER:soziales-netzwerk-other_social_media
NICKNAME:spitzname
END:VCARD

**Comment by skjnldsv** [comment]
Should already be fixed in the incoming version
Can you test [contacts.tar.gz](https://github.com/nextcloud/contacts/files/2796513/contacts.tar.gz) ?

**Comment by Huster-at-github** [comment]
> Should already be fixed in the incoming version
> Can you test [contacts.tar.gz](https://github.com/nextcloud/contacts/files/2796513/contacts.tar.gz) ?

Yes, I will.

**Comment by Huster-at-github** [comment]
@skjnldsv : Can I stay on your current version in my Nextcloud? It still shows me 3.0.2.

**Comment by skjnldsv** [comment]
@Huster-at-github you can, this will be 3.0.3.
You will be able to upgrade as soon as the release comes out

**Comment by Huster-at-github** [comment]
> 
> 
> Should already be fixed in the incoming version
> Can you test [contacts.tar.gz](https://github.com/nextcloud/contacts/files/2796513/contacts.tar.gz) ?

In this build: Enlarging notes fiel does not work.
