### ISSUE TITLE
connection to server lost

### ISSUE THREAD

**Issue by Aviorleking** [nextcloud/contacts#896]
### Describe the bug
after editing one contact, and waiting for the saving icon to end I can't edit any propertie or contact with the error "connection to server lost"

**To Reproduce**
1. click on a contact
2. edit the contact information
3. wait for the save icon to disapear
4. try to edit the contact again
5. see the error "connection to server lost"

**Expected behavior**
we should be able to edit contacts without having to reload the page each time

**Actual behavior**
i can only edit one time before having to reload the page

**Screenshots**
![image](https://user-images.githubusercontent.com/15822031/51896394-aa4c8780-23ac-11e9-894e-ca4f46088b4b.png)

### Server configuration

**Operating system**: Linux
**Web server:** Apache

**Database:** MariaDB

**PHP version:** 7.2

**Nextcloud version:** 15.0.2

**Contacts version:** 3.0.2

**Updated from an older Nextcloud or fresh install:** from older

**Signing status:**
```
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- tasks
	- INVALID_HASH
		- l10n/fa.js
		- l10n/ru.js

Raw output
==========
Array
(
    [tasks] => Array
        (
            [INVALID_HASH] => Array
                (
                    [l10n/fa.js] => Array
                        (
                            [expected] => bd584b57921f379b128d9f4581fbeecfc2444e05390fa64b387614e927a8e2f5d6036a528efdc6e2b0e87f385bc53f5dcfbd32ce3d7ac332418e851a30bfeecf
                            [current] => 6e97ff850c34e4793ccceaca4d1baabbb1143f33470f3eaf7258db46b3c041ca6c2e682f1a36406c5516f5040a5d4965c59c7660b7271464f7a0bb47f5c9af75
                        )

                    [l10n/ru.js] => Array
                        (
                            [expected] => fed3cf349922c41fd979df347ef87b854a649e7db85f621ae4044bf7fffd40e55ded5d66beec823dfc5d60508b468889dba4cba3e8fbecfb748ac07ca26e83c4
                            [current] => 09b5fc177042f8c831666976e9cef7b3a8b9f91ab0e874a777c285262c5b7679a0dbba4120697c6a094048b4ac6894e6916f5edb5314a964bb931f08b4af32ea
                        )

                )

        )

)

```

**List of activated apps:**
```
Activity 2.8.2

AppOrder 0.6.0

Bookmarks 0.16.0

Brute-force settings 1.3.0

Calendar 1.6.4

Contacts 3.0.2

Deleted files 1.5.0

File sharing 1.7.0

Gallery 18.2.0

Issue Template 0.4.0

Log Reader 2.0.0

Mail 0.11.0

Markdown Editor 2.0.5

Monitoring 1.5.0

Notes 2.5.1

Notifications 2.3.0

Passwords 2019.1.0

PDF viewer 1.4.0

PhoneTrack 0.4.3

Tasks 0.9.8

Text editor 2.7.0

Theming 1.6.0

Two Factor TOTP Provider 2.1.0

Update notification 1.5.0

Usage survey 1.3.0

Versions 1.8.0
```

**Nextcloud configuration:**
```
<?php
$CONFIG = array (
  'instanceid' => '*************',
  'passwordsalt' => '*************',
  'secret' => '*************',
  'trusted_domains' => 
  array (
    0 => 'cloud.*************.net',
  ),
  'datadirectory' => '/home/*************/cloud/data',
  'dbtype' => 'mysql',
  'version' => '15.0.2.0',
  'overwrite.cli.url' => '*************',
  'dbname' => '*************',
  'dbhost' => '*************',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => '*************',
  'dbpassword' => '*************',
  'installed' => true,
  'theme' => '',
  'loglevel' => 2,
  'maintenance' => false,
  'mail_smtpmode' => 'smtp',
  'mail_smtpsecure' => 'ssl',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_from_address' => '*************',
  'mail_domain' => '*************',
  'mail_smtpauth' => 1,
  'mail_smtphost' => '*************',
  'mail_smtpport' => '465',
  'mail_smtpname' => '*************',
  'mail_smtppassword' => '*************',
  'overwriteprotocol' => 'https',
  'updater.release.channel' => 'beta',
  'updater.secret' => '*************',
);

```

### Client configuration
**Browser:** Firefox 64.0

**Operating system:** Linux KDE neon (ubuntu)

**CardDAV-clients:**

#### *Web server error log*
```
[Tue Jan 29 09:44:34 2019] [error] [client 185.160.53.160] [host cloud.delta-wings.net] (104)Connection reset by peer: AH00574: ap_content_length_filter: apr_bucket_read() failed
[Tue Jan 29 09:45:21 2019] [error] [client 185.160.53.160] [host cloud.delta-wings.net] (104)Connection reset by peer: AH00574: ap_content_length_filter: apr_bucket_read() failed
[Tue Jan 29 09:45:57 2019] [error] [client 185.160.53.160] [host cloud.delta-wings.net] (104)Connection reset by peer: AH00574: ap_content_length_filter: apr_bucket_read() failed
[Tue Jan 29 09:49:21 2019] [error] [client 185.160.53.160] [host cloud.delta-wings.net] (104)Connection reset by peer: AH00574: ap_content_length_filter: apr_bucket_read() failed
[Tue Jan 29 09:49:30 2019] [error] [client 185.160.53.160] [host cloud.delta-wings.net] (104)Connection reset by peer: AH00574: ap_content_length_filter: apr_bucket_read() failed
[Tue Jan 29 09:50:40 2019] [crit] [client 185.160.53.160] [host cloud.delta-wings.net] (13)Permission denied: AH00529: /homez.31/deltawinbo/cloud/data/.htaccess pcfg_openfile: unable to check htaccess file, ensure it is readable and that '/homez.31/deltawinbo/cloud/data/' is executable
[Tue Jan 29 09:50:50 2019] [crit] [client 185.160.53.160] [host cloud.delta-wings.net] (13)Permission denied: AH00529: /homez.31/deltawinbo/cloud/data/.htaccess pcfg_openfile: unable to check htaccess file, ensure it is readable and that '/homez.31/deltawinbo/cloud/data/' is executable
[Tue Jan 29 09:51:23 2019] [error] [client 185.160.53.160] [host cloud.delta-wings.net] (104)Connection reset by peer: AH00574: ap_content_length_filter: apr_bucket_read() failed
[Tue Jan 29 09:52:46 2019] [error] [client 185.160.53.160] [host cloud.delta-wings.net] (104)Connection reset by peer: AH00574: ap_content_length_filter: apr_bucket_read() failed
[Tue Jan 29 09:52:50 2019] [error] [client 185.160.53.160] [host cloud.delta-wings.net] (104)Connection reset by peer: AH00574: ap_content_length_filter: apr_bucket_read() failed
[Tue Jan 29 09:52:51 2019] [error] [client 185.160.53.160] [host cloud.delta-wings.net] (104)Connection reset by peer: AH00574: ap_content_length_filter: apr_bucket_read() failed
[Tue Jan 29 09:53:10 2019] [error] [client 185.160.53.160] [host cloud.delta-wings.net] (104)Connection reset by peer: AH00574: ap_content_length_filter: apr_bucket_read() failed
[Tue Jan 29 09:59:25 2019] [error] [client 185.160.53.160] [host cloud.delta-wings.net] (104)Connection reset by peer: AH00574: ap_content_length_filter: apr_bucket_read() failed
[Tue Jan 29 10:08:16 2019] [crit] [client 185.160.53.160] [host cloud.delta-wings.net] (13)Permission denied: AH00529: /homez.31/deltawinbo/cloud/data/.htaccess pcfg_openfile: unable to check htaccess file, ensure it is readable and that '/homez.31/deltawinbo/cloud/data/' is executable
[Tue Jan 29 10:08:21 2019] [crit] [client 185.160.53.160] [host cloud.delta-wings.net] (13)Permission denied: AH00529: /homez.31/deltawinbo/cloud/data/.htaccess pcfg_openfile: unable to check htaccess file, ensure it is readable and that '/homez.31/deltawinbo/cloud/data/' is executable
[Tue Jan 29 10:08:28 2019] [crit] [client 185.160.53.160] [host cloud.delta-wings.net] (13)Permission denied: AH00529: /homez.31/deltawinbo/cloud/data/.htaccess pcfg_openfile: unable to check htaccess file, ensure it is readable and that '/homez.31/deltawinbo/cloud/data/' is executable
[Tue Jan 29 10:08:38 2019] [crit] [client 185.160.53.160] [host cloud.delta-wings.net] (13)Permission denied: AH00529: /homez.31/deltawinbo/cloud/data/.htaccess pcfg_openfile: unable to check htaccess file, ensure it is readable and that '/homez.31/deltawinbo/cloud/data/' is executable
[Tue Jan 29 10:10:09 2019] [crit] [client 185.160.53.160] [host cloud.delta-wings.net] (13)Permission denied: AH00529: /homez.31/deltawinbo/cloud/data/.htaccess pcfg_openfile: unable to check htaccess file, ensure it is readable and that '/homez.31/deltawinbo/cloud/data/' is executable
[Tue Jan 29 10:11:21 2019] [error] [client 185.160.53.160] [host cloud.delta-wings.net] Script timed out before returning headers: index.php
[Tue Jan 29 10:23:38 2019] [crit] [client 185.160.53.160] [host cloud.delta-wings.net] (13)Permission denied: AH00529: /homez.31/deltawinbo/cloud/data/.htaccess pcfg_openfile: unable to check htaccess file, ensure it is readable and that '/homez.31/deltawinbo/cloud/data/' is executable
[Tue Jan 29 10:23:42 2019] [crit] [client 185.160.53.160] [host cloud.delta-wings.net] (13)Permission denied: AH00529: /homez.31/deltawinbo/cloud/data/.htaccess pcfg_openfile: unable to check htaccess file, ensure it is readable and that '/homez.31/deltawinbo/cloud/data/' is executable
[Tue Jan 29 10:25:15 2019] [error] [client 185.160.53.160] [host cloud.delta-wings.net] Script timed out before returning headers: index.php
[Tue Jan 29 10:33:45 2019] [crit] [client 185.160.53.160] [host cloud.delta-wings.net] (13)Permission denied: AH00529: /homez.31/deltawinbo/cloud/data/.htaccess pcfg_openfile: unable to check htaccess file, ensure it is readable and that '/homez.31/deltawinbo/cloud/data/' is executable
[Tue Jan 29 10:33:48 2019] [crit] [client 185.160.53.160] [host cloud.delta-wings.net] (13)Permission denied: AH00529: /homez.31/deltawinbo/cloud/data/.htaccess pcfg_openfile: unable to check htaccess file, ensure it is readable and that '/homez.31/deltawinbo/cloud/data/' is executable
[Tue Jan 29 10:34:27 2019] [error] [client 185.160.53.160] [host cloud.delta-wings.net] (104)Connection reset by peer: AH00574: ap_content_length_filter: apr_bucket_read() failed

```

#### *data/nextcloud.log*
```
{"reqId":"XFAdjQoUFBEAAEtJrlMAAAAE","level":1,"time":"2019-01-29T09:32:58+00:00","remoteAddr":"185.160.53.160","user":"--","app":"updater","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=bx2kdpQFBWZeWzqjCh5dSBAEhLn0kClKNOnYUMQCARw%3D%3APFrsQsdMbiobPmLTW3hqCV8rssGW1l8ibaa0ZetlR3g%3D","message":"\\OC\\Updater::updateEnd: Update successful","userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:64.0) Gecko\/20100101 Firefox\/64.0","version":"15.0.2.0"}
{"reqId":"XFAdjQoUFBEAAEtJrlMAAAAE","level":1,"time":"2019-01-29T09:32:58+00:00","remoteAddr":"185.160.53.160","user":"--","app":"updater","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=bx2kdpQFBWZeWzqjCh5dSBAEhLn0kClKNOnYUMQCARw%3D%3APFrsQsdMbiobPmLTW3hqCV8rssGW1l8ibaa0ZetlR3g%3D","message":"\\OC\\Updater::maintenanceDisabled: Turned off maintenance mode","userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:64.0) Gecko\/20100101 Firefox\/64.0","version":"15.0.2.0"}
{"reqId":"XFAdjQoUFBEAAEtJrlMAAAAE","level":1,"time":"2019-01-29T09:32:58+00:00","remoteAddr":"185.160.53.160","user":"--","app":"updater","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=bx2kdpQFBWZeWzqjCh5dSBAEhLn0kClKNOnYUMQCARw%3D%3APFrsQsdMbiobPmLTW3hqCV8rssGW1l8ibaa0ZetlR3g%3D","message":"\\OC\\Updater::resetLogLevel: Reset log level to Warning(2)","userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:64.0) Gecko\/20100101 Firefox\/64.0","version":"15.0.2.0"}
```
__not everything but the latest__

#### Browser log

```
JQMIGRATE: Migrate is installed, version 1.4.0 core.js:7:542
New search handler registered search.js:67:4
Connected to dav! 
Object { rootUrl: Getter & Setter, advertisedFeatures: Getter & Setter, currentUserPrincipal: Getter & Setter, principalCollections: Getter & Setter, calendarHomes: Getter & Setter, addressBookHomes: Getter & Setter, parser: Getter & Setter, _isConnected: Getter & Setter, _request: Getter & Setter, … }
```

**Comment by skjnldsv** [comment]
Hello! I will need a screenshot of your network requests to investigate :)
Before you do anything, still on the development tools, there is a tab called `network`. Click on it and then the xhr filter. Do your action and screenshot the network log like this:
![capture d ecran_2018-09-27_21-49-46](https://user-images.githubusercontent.com/14975046/46170857-43548000-c29f-11e8-9403-db72713dd9c1.png)

**Comment by Aviorleking** [comment]
![image](https://user-images.githubusercontent.com/15822031/51900263-2a76eb00-23b5-11e9-957e-d7bc7ff2db7a.png)
![image](https://user-images.githubusercontent.com/15822031/51900286-36fb4380-23b5-11e9-9b01-7f38a0755d49.png)

**Comment by skjnldsv** [comment]
Hum, that is strange.
Just so you know, the `connection to server lost` does not come from the contacts app.
This is coming from the server if the network is unreachable. Though this is nothing toworry about.

Does it happens often?

Also, the 412 error you have when editing contacts is unrelated to this and a duplicate of #842 and fixed in the incoming version ! :)

**Comment by Aviorleking** [comment]
ok and yes the error come everytime i edit a contact for a second time without reloading the page

**Comment by skjnldsv** [comment]
The connexion lost error?

**Comment by Aviorleking** [comment]
yep

**Comment by Aviorleking** [comment]
Thats it

**Comment by skjnldsv** [comment]
@Aviorleking is it still happening on 3.0.3?

**Comment by Aviorleking** [comment]
it work prefectly now ! Thanks you :+1:

**Comment by Quintulius** [comment]
@Aviortheking This problem still exists with Contacts 3.1.3. I'm not able to add multiple contact data. After the first one, the connection with the server is lost. I have to refresh the page before adding some other information.

## Server

* OVH "mutualisé"
* php 7.2
* mysql 5.6

![bug_contacts](https://user-images.githubusercontent.com/5604580/64557024-f7c8a400-d340-11e9-9372-82a282662451.png)

**Comment by skjnldsv** [comment]
@Quintulius Hey!
Can you click the request that you think is failing and copy the headers/request content AND the response content to me? :)

**Comment by Quintulius** [comment]
Thanks, that's what I have : 
Code d’état : 412
Version :HTTP/2.0
Politique de référent :no-referrer

## Header response

HTTP/2.0 412 Precondition Failed
date: Tue, 10 Sep 2019 18:08:56 GMT
content-type: application/xml; charset=utf-8
server: Apache
x-powered-by: PHP/7.2
expires: Thu, 19 Nov 1981 08:52:00 GMT
cache-control: no-store, no-cache, must-revalidate
pragma: no-cache
x-frame-options: SAMEORIGIN
x-xss-protection: 1; mode=block
x-content-type-options: nosniff
x-robots-tag: none
x-download-options: noopen
x-permitted-cross-domain-policies: none
referrer-policy: no-referrer
content-security-policy: default-src 'none';
strict-transport-security: max-age=15768000; includeSubDomains; preload
x-iplb-instance: 28274
set-cookie: SERVERID100401=1520201|XXfmu|XXfmI; path=/
X-Firefox-Spdy: h2

## Header request

Host: toto.fr
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:70.0) Gecko/20100101 Firefox/70.0
Accept: */*
Accept-Language: fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3
Accept-Encoding: gzip, deflate, br
X-Requested-With: XMLHttpRequest
requesttoken: Y8I9QId7OU5Zhvd6LZwnzdgVGOyyqdtT1mwWUlXAQ2Q=:TOlSBONIFjcd0rw7G/pfu7V8Qojq/q8qnDpZADrxJAg=
Depth: 0
Content-Type: application/xml; charset=utf-8
If-Match: null
Content-Length: 257
Origin: https://toto.fr
DNT: 1
Connection: keep-alive
Cookie: ochnv2bvls5s=579789f1b69f96339741a1b8ee8861d3; oc_sessionPassphrase=qhWl9Znl0sZsvWU%2BARkoe%2FlFXa96KmHnNx%2FVrKkL%2FJuFIWFrEa7ZAWf3pgaAaBSKEiTCjz1BRaYggoA7cx%2Bgog%2B9uAMFHMh6I2B6DQWS3Ee%2B9fRI4fzo0NHPoeVSB1iZ; nc_sameSiteCookielax=true; nc_sameSiteCookiestrict=true; nc_username=Toto; nc_token=2JITRz7XwLlbLdy1v1BGz5QfsrqrIeJ9; nc_session_id=579789f1b69f96339741a1b8ee8861d3; SERVERID100401=1520201|XXfms|XXfmI
TE: Trailers

## Content response

<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\PreconditionFailed</s:exception>
  <s:message>An If-Match header was specified, but none of the specified the ETags matched.</s:message>
  <s:header>If-Match</s:header>
</d:error>

How can I help ?

**Comment by skjnldsv** [comment]
You're having issues with your server indeed.
Are you using cloudflare?

**Comment by Quintulius** [comment]
I'm not!

**Comment by skjnldsv** [comment]
On your screenshot, you're showing me a request with a 204 response which is ok, but the request data you pasted here show a 412. Could you make sure you're not mistaken on the screenshot and post the first valid and following failing request here please?

**Comment by Quintulius** [comment]
Ok, I gave it a try:

![Capture du 2019-09-11 16-47-04](https://user-images.githubusercontent.com/5604580/64708356-c8d33f00-d4b4-11e9-8e6a-7a2db40d6e39.png)


## First PUT (201)

### Response header

HTTP/2.0 201 Created
date: Wed, 11 Sep 2019 14:39:41 GMT
content-type: text/html; charset=UTF-8
content-length: 0
server: Apache
x-powered-by: PHP/7.2
expires: Thu, 19 Nov 1981 08:52:00 GMT
cache-control: no-store, no-cache, must-revalidate
pragma: no-cache
x-frame-options: SAMEORIGIN
x-xss-protection: 1; mode=block
x-content-type-options: nosniff
x-robots-tag: none
x-download-options: noopen
x-permitted-cross-domain-policies: none
referrer-policy: no-referrer
content-security-policy: default-src 'none';
oc-etag: "82eac4caab4cf8ff54f4f27b3c84d45d"
strict-transport-security: max-age=15768000; includeSubDomains; preload
x-iplb-instance: 28348
set-cookie: SERVERID100401=1520184|XXkHM|XXkG9; path=/
X-Firefox-Spdy: h2

### Request header

Host: toto.fr
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:70.0) Gecko/20100101 Firefox/70.0
Accept: */*
Accept-Language: fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3
Accept-Encoding: gzip, deflate, br
X-Requested-With: XMLHttpRequest
requesttoken: VL9r52ZVz+GArELE+2ZyQyEKtVJthOX403/JxR+IojM=:O+soljYD96jRxQa9qSkjC0JG+ABevNTJm0yEg1vyy3I=
Depth: 0
Content-Type: text/vcard; charset=utf-8
Content-Length: 255
Origin: https://toto.fr
DNT: 1
Connection: keep-alive
Cookie: ochnv2bvls5s=d32ab4e6431f91de01ddf66fc9d4ffcc; oc_sessionPassphrase=gReXNiOL%2B7rcSQRR4X%2FvrLAINGIrHPOOMStk84uYJEinJLiMtzIt3b1A3egG2kOz0a48plIwy%2BWziX%2FuznUFNiKRGt%2BZf4LktxLiSyjQlS9IuKYzBcp%2BtJO444%2BS1Se8; nc_sameSiteCookielax=true; nc_sameSiteCookiestrict=true; nc_username=Toto; nc_token=OOhtlTZkUmajZpsiCTb4lHtvLjjvuEeL; nc_session_id=d32ab4e6431f91de01ddf66fc9d4ffcc; SERVERID100401=1520184|XXkHJ|XXkG9
TE: Trailers

### Response

Empty

## Second PUT (204)

### Response header

HTTP/2.0 204 No Content
date: Wed, 11 Sep 2019 14:39:53 GMT
server: Apache
x-powered-by: PHP/7.2
expires: Thu, 19 Nov 1981 08:52:00 GMT
cache-control: no-store, no-cache, must-revalidate
pragma: no-cache
x-frame-options: SAMEORIGIN
x-xss-protection: 1; mode=block
x-content-type-options: nosniff
x-robots-tag: none
x-download-options: noopen
x-permitted-cross-domain-policies: none
referrer-policy: no-referrer
content-security-policy: default-src 'none';
oc-etag: "391bbf1029a07cb4e70635f7cda2ef3f"
strict-transport-security: max-age=15768000; includeSubDomains; preload
x-iplb-instance: 28277
set-cookie: SERVERID100401=1520184|XXkHP|XXkG9; path=/
X-Firefox-Spdy: h2

### Request header

Host: toto.fr
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:70.0) Gecko/20100101 Firefox/70.0
Accept: */*
Accept-Language: fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3
Accept-Encoding: gzip, deflate, br
X-Requested-With: XMLHttpRequest
requesttoken: VL9r52ZVz+GArELE+2ZyQyEKtVJthOX403/JxR+IojM=:O+soljYD96jRxQa9qSkjC0JG+ABevNTJm0yEg1vyy3I=
Depth: 0
Content-Type: application/xml; charset=utf-8
If-Match: "82eac4caab4cf8ff54f4f27b3c84d45d"
Content-Length: 265
Origin: https://toto.fr
DNT: 1
Connection: keep-alive
Cookie: ochnv2bvls5s=d32ab4e6431f91de01ddf66fc9d4ffcc; oc_sessionPassphrase=gReXNiOL%2B7rcSQRR4X%2FvrLAINGIrHPOOMStk84uYJEinJLiMtzIt3b1A3egG2kOz0a48plIwy%2BWziX%2FuznUFNiKRGt%2BZf4LktxLiSyjQlS9IuKYzBcp%2BtJO444%2BS1Se8; nc_sameSiteCookielax=true; nc_sameSiteCookiestrict=true; nc_username=Toto; nc_token=OOhtlTZkUmajZpsiCTb4lHtvLjjvuEeL; nc_session_id=d32ab4e6431f91de01ddf66fc9d4ffcc; SERVERID100401=1520184|XXkHM|XXkG9
TE: Trailers

### Response

Empty


## Third PUT (412)

### Response header

HTTP/2.0 412 Precondition Failed
date: Wed, 11 Sep 2019 14:40:48 GMT
content-type: application/xml; charset=utf-8
server: Apache
x-powered-by: PHP/7.2
expires: Thu, 19 Nov 1981 08:52:00 GMT
cache-control: no-store, no-cache, must-revalidate
pragma: no-cache
x-frame-options: SAMEORIGIN
x-xss-protection: 1; mode=block
x-content-type-options: nosniff
x-robots-tag: none
x-download-options: noopen
x-permitted-cross-domain-policies: none
referrer-policy: no-referrer
content-security-policy: default-src 'none';
strict-transport-security: max-age=15768000; includeSubDomains; preload
x-iplb-instance: 28348
X-Firefox-Spdy: h2

### Request header

Host: toto.fr
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:70.0) Gecko/20100101 Firefox/70.0
Accept: */*
Accept-Language: fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3
Accept-Encoding: gzip, deflate, br
X-Requested-With: XMLHttpRequest
requesttoken: VL9r52ZVz+GArELE+2ZyQyEKtVJthOX403/JxR+IojM=:O+soljYD96jRxQa9qSkjC0JG+ABevNTJm0yEg1vyy3I=
Depth: 0
Content-Type: application/xml; charset=utf-8
If-Match: null
Content-Length: 270
Origin: https://toto.fr
DNT: 1
Connection: keep-alive
Cookie: ochnv2bvls5s=d32ab4e6431f91de01ddf66fc9d4ffcc; oc_sessionPassphrase=gReXNiOL%2B7rcSQRR4X%2FvrLAINGIrHPOOMStk84uYJEinJLiMtzIt3b1A3egG2kOz0a48plIwy%2BWziX%2FuznUFNiKRGt%2BZf4LktxLiSyjQlS9IuKYzBcp%2BtJO444%2BS1Se8; nc_sameSiteCookielax=true; nc_sameSiteCookiestrict=true; nc_username=Toto; nc_token=OOhtlTZkUmajZpsiCTb4lHtvLjjvuEeL; nc_session_id=d32ab4e6431f91de01ddf66fc9d4ffcc; SERVERID100401=1520184|XXkHc|XXkG9
TE: Trailers

### Response

<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\PreconditionFailed</s:exception>
  <s:message>An If-Match header was specified, but none of the specified the ETags matched.</s:message>
  <s:header>If-Match</s:header>
</d:error>

**Comment by skjnldsv** [comment]
@Quintulius can you try this release?
[contacts.tar.gz](https://github.com/nextcloud/contacts/files/3601987/contacts.tar.gz)
