### ISSUE TITLE
[UX] Some contact card colours make contact name text unreadable

### ISSUE THREAD

**Issue by axelsimon** [nextcloud/contacts#90]
### Steps to reproduce
1. Create a contact, nextcloud automatically choses a colour for this contact
2. Click on a contact card to see details

### Expected behaviour
The contact name should be easy to read (and by extension edit), and all colour choices should provide a good contrast ratio between the randomly picked background colour and the text's font colour (white)

### Actual behaviour
Some colours are very light (very pale yellow, very pale green, etc.) and make it nearly impossible to read the name of the contacts for many users, let alone edit it.

### Server configuration
**Operating system**:
not relevant
**Web server:**
nginx (but not relevant really)
**Database:**
mysql (but not relevant really)
**PHP version:**
Version: 5.6.29+dfsg-0+deb8u1(but not relevant really)
**Nextcloud version:** (see Nextcloud admin page)
10.0.2 (first spotted on 9.0.54, the probme seems a little less worse on 10.0.2)
**Contacts version:** (see Nextcloud apps page)
1.5.1 (same, seemed a little worse on previous version)
**Updated from an older Nextcloud or fresh install:**
update from owncloud

**Comment by jancborchardt** [comment]
@axelsimon do you want to open a pull request which adds a slight (very slight) text-shadow to the text in the header? Could be the same we use in the image view for the filename.

Also cc @jonatoni @xh3n1 as it’s a good starter issue. :)

**Comment by axelsimon** [comment]
Sorry @jancborchardt, I don't current have the skills to do that. I'll get there eventually, but in the meantime I think @jonatoni or @xh3n1 are better candidates to fix this :)

**Comment by skjnldsv** [comment]
@jancborchardt It's not a really good idea. It's pretty ugly! :(
If we want to lower the contrast, we should probably create a contrast function into core, or change the colour generator! :)

**Comment by jancborchardt** [comment]
@skjnldsv it's pretty common practice to add a slight text-shadow to increase legibility of white text on any background. It just has to be slight and not noticeable. I'll check it out.

**Comment by jancborchardt** [comment]
Fix at https://github.com/nextcloud/contacts/pull/338, please review @axelsimon :)

**Comment by axelsimon** [comment]
@jancborchardt Hi and thanks for taking the time to review this issue and create a fix.
However, I don't agree this fixes the original issue, even it does clearly make a positive difference.

The initial issue is with the contrast between white text and different light coloured backgrounds. Adding a drop shadow helps, but doesn't fix the actual issue. People like my mum will still have a hard time reading the contact cards, even if this helps (I actually checked with her 😉)

(Furthermore, I'm really not sure this does much to help colour blind people. But we would probably need an actual colour blind mode to do that right, really).

By all means, I think we should keep this improvement, as it clearly improves things, but I would ask that this bug be re-opened.

Thanks for your help!
