### ISSUE TITLE
[3.0.3] Unable to close the settings dialog in the Contacts app

### ISSUE THREAD

**Issue by j-ed** [nextcloud/contacts#903]
## Expected behavior
If you have opened the settings dialog in the Contacts app, it should be possible to close this dialog again by clicking on the dialog header.

## Current behavior
If you have opened the settings dialog in the Contacts app, this dialog cannot be closed by clicking on the dialog header. Instead you have to click on e.g. an address book to get it closed.

### Steps to reproduce
1. Open the Contacts app.
2. Click on the settings dialog header and the available settings are displayed.
3. Click on the settings dialog header to close it.
-> The dialog stays open.

#### Server Configuration
OS: Linux 3.16.60
Web server: Apache2 2.4.37
Database: MariaDB 10.2.19
PHP version: 7.2.14
Nextcloud version: 15.0.2
Contacts app version: 3.0.3

#### Client Configuration
Browser: Mozilla Firefox 65.0
Operating system: Windows 10

**Comment by skjnldsv** [comment]
@ChristophWurst related to the new settings component ?

**Comment by ChristophWurst** [comment]
possible, yeah

**Comment by skjnldsv** [comment]
Requires https://github.com/nextcloud/nextcloud-vue/pull/247

**Comment by skjnldsv** [comment]
Fixed in a6722de1
