### ISSUE TITLE
[3.0.3] Year range in the date select dialog is always one year ahead of the available options.

### ISSUE THREAD

**Issue by j-ed** [nextcloud/contacts#911]
## Expected behavior
The displayed year range in the date select dialog of birth or death day fields should reflect the available options.

## Current behavior
The displayed year range in the date select dialog of birth or death day fields is always one year ahead of the available options.

![20190203_nc_contacts_date_selector](https://user-images.githubusercontent.com/2572764/52179272-5ab8f200-27d8-11e9-956c-7e63e054ed42.png)

### Steps to reproduce
1. Open the Contacts app.
2. Add a birthday.
-> Check out the displayed year range.

#### Server Configuration
OS: Linux 3.16.60
Web server: Apache2 2.4.37
Database: MariaDB 10.2.19
PHP version: 7.2.14
Nextcloud version: 15.0.2
Contacts app version: 3.0.3

#### Client Configuration
Browser: Mozilla Firefox 65.0
Operating system: Windows 10

**Comment by skjnldsv** [comment]
@j-ed Hey!
We're using the [vue2-datepicker](https://github.com/mengxiong10/vue2-datepicker) library for that.
I think this is built on the design. Could you open the issue there? :)

**Comment by j-ed** [comment]
@skjnldsv [**x**] done.

**Comment by skjnldsv** [comment]
Issue in https://github.com/mengxiong10/vue2-datepicker/issues/245
Thanks a lot @j-ed :hugs:

**Comment by j-ed** [comment]
@skjnldsv I just got the information that [version 2.9.2](https://github.com/mengxiong10/vue2-datepicker/issues/245) of **`vue2-datepicker`** has been published which fixes the problem.

**Comment by skjnldsv** [comment]
@j-ed same! Let's merge https://github.com/nextcloud/nextcloud-vue/pull/242 and then trigger a release

**Comment by skjnldsv** [comment]
Fixed in a6722de1
