### ISSUE TITLE
Search contacts by phone number, email, etc.: by anything else than name

### ISSUE THREAD

**Issue by axelsimon** [nextcloud/contacts#922]
**Is your feature request related to a problem? Please describe.**
It is currently not possible (AFAICT) to search nextcloud contacts by anything other than name.
This means that the wealth of information that may be contained in contact cards (emails, notes, phone numbers, addresses etc.) is not searchable. This is annoying as it means you can't search your contacts trying to find a person using a note you made on them, or searching a phone number if you receive a text on a phone on which you haven't got the address book synced with nextcloud (for whatever reason). 

**Describe the solution you'd like**
Anything typed in the search field will start a search in all of one's contacts's fields, not just their name.

**Describe alternatives you've considered**
An alternative is to only search names by default and offer to search other fields if the search finds nothing (if I type in a phone number, it should not find anything and offer to do an extend search).

**Comment by RobertZenz** [comment]
That works for me and has been working for a few versions (At least since version 12, I think).

I can type whatever I want into the search and it will return the contacts with the search string being contained in any field.

**Comment by skjnldsv** [comment]
@RobertZenz yes!
@axelsimon are you using the latest contacts version? 3.0.x ?

**Comment by skjnldsv** [comment]
Let's close I cannot reproduce on the latest version
