### ISSUE TITLE
Saving reverts changes which happened during the save.

### ISSUE THREAD

**Issue by RobertZenz** [nextcloud/contacts#923]
When editing a contact the contact is being automatically saved when you stop typing. Any changes you make during the saving process (the spinner is visible in the right upper corner) are being reverted the moment saving is completed.

This is especially bad when you, for example, type in a phone number while reading it from a different source. You start typing, then look at the source and this pause causes the save, so there's a chance that you'll start typing during the save and any input you've done during the saving process will be reverted, potentially leaving you with a partially filled in field.

## Steps to reproduce the behavior

 1. Open a contact.
 2. Start typing in an input field, stop for a few seconds and begin typing as soon as the saving starts.

When saving finishes, everything you've typed during the saving will be reverted.

## Expected behavior

Changes the user put into the field should never be silently reverted.

## Actual behavior
They are silently reverted when the save finishes.

## Note

It for sure is my server who is not as fast as a server could be, but this hasn't been a problem until the upgrade to 15.

**Comment by skjnldsv** [comment]
Hello @RobertZenz :)

Thanks for your report. I'm guessing you're on contacts 3.0.x?

**Comment by RobertZenz** [comment]
Exactly, 3.0.3 to be exact.

**Comment by skjnldsv** [comment]
@RobertZenz thanks.
I cannot reproduce. Every change I do are still sent to the server and kept as it is :/

As you can see (I enabled bandwidth limiter), multiple save doesn't change the edits I do to the contact.

![peek 12-02-2019 14-07](https://user-images.githubusercontent.com/14975046/52637495-a00faa80-2ecf-11e9-8e12-4a1ec7759745.gif)

**Comment by RobertZenz** [comment]
I could not clearly see whether you were typing while the saving was in progress. Can I do something to debug this on my end?

**Comment by skjnldsv** [comment]
@RobertZenz I'll try with an even longer bandwidth multiplier.
This happens when you use your phone, right?

**Comment by skjnldsv** [comment]
@RobertZenz Okay I was able to reproduce the issue just now!

**Comment by RobertZenz** [comment]
Glad to hear that you could reproduce it.

Well, in my case it is not the bandwidth of the connection, it is my server directly. I'm using an oldish (10 years approaching Atom) as my main server, which is quite fast enough for the two users it needs to serve to. But from time to time it lacks a little.

**Comment by raimund-schluessler** [comment]
@skjnldsv How do I enable bandwidth limiter? I would like to test it with Tasks as well.

**Comment by skjnldsv** [comment]
@raimund-schluessler on the network tab of your dev tools, you can set various speed limits :)
![capture d ecran_2019-02-14_14-51-03](https://user-images.githubusercontent.com/14975046/52790895-f879b000-3067-11e9-9111-4d1159979f64.png)

**Comment by jaller94** [comment]
I am in Vancouver, Canada and my home server is located in Germany. The restore on a successful autosave in version 3.0.3 makes the app’s input fields unusable for me.
The effect is strongest when typing in bursts, interrupted by a brief pause for autosave to start.

![2019-02-27 18 41 50](https://user-images.githubusercontent.com/10872136/53537617-6b9b1180-3abf-11e9-88f2-fd7abec6f15e.gif)

**Comment by JavierRSobrino** [comment]
I dont know it this is related, but now everytime I try to edit a contact, it is never saved. The circle is constantly running indicating that it is saving, but it never gets saved.

**Comment by skjnldsv** [comment]
@JavierRSobrino anything in your browser's console?

<details>
<summary>How to access your browser console (Click to expand)</summary>

# Chrome
- Press either CTRL + SHIFT + J to open the “console” tab of the Developer Tools.
- Alternative method:
    1. Press either CTRL + SHIFT + I or F12 to open the Developer Tools.
    2. Click the “console” tab.

# Safari
- Press CMD + ALT + I to open the Web Inspector.
- See Chrome’s step 2. (Chrome and Safari have pretty much identical dev tools.)

# IE9
1. Press F12 to open the developer tools.
2. Click the “console” tab.

# Firefox
- Press CTRL + SHIFT + K to open the Web console (COMMAND + SHIFT + K on Macs).
- or, if Firebug is installed (recommended):
    1. Press F12 to open Firebug.
    2. Click on the “console” tab.

# Opera
1. Press CTRL + SHIFT + I to open Dragonfly.
2. Click on the “console” tab.
</details>
