### ISSUE TITLE
delete button in the site-panel is dangerous

### ISSUE THREAD

**Issue by Chialya** [nextcloud/contacts#929]
As I updated to Nextcloud 15, I see the new delete button in the side-panel-list which every contact has.
If I accidentally press it, a whole contact is quickly deleted! That's not great!
How can I protect this?

Or in which file can I delete by myself the creation of:
`<div tabindex="0" class="icon-delete"></div>`

I tried to analyze the source code, but I can't find the place to remove the delete button.
I'm urgently asking for help!

![nc15-contacts](https://user-images.githubusercontent.com/34279677/52568615-8d35a100-2e0f-11e9-9cdd-3f300c95298f.JPG)

**Comment by skjnldsv** [comment]
@Chialya Hello and thanks for your feedback.
We planned to add a revert option for the delete action. see #637.

For the delete button it's located here: https://github.com/nextcloud/contacts/blob/master/src/components/ContactsList/ContactsListItem.vue#L22
You can remove this line and compile the app yourself if you want. Or if you're using an adblocker and it's really bothering you, you can create a rule to hide this button with `##.app-content-list-item > .icon-delete`
