### ISSUE TITLE
option "When shared show only busy": In own calendar only "busy" is shown

### ISSUE THREAD

**Issue by homer79** [nextcloud/contacts#93]
### Expected behaviour
If I set an new calendar entry with option "When shard show only busy", only for other persons with which I share my calendar "busy" should be shown for this entry. 

### Actual behaviour
"busy" is shown for myself respectively in my own calendar.

### Server configuration
Server: Ubuntu 16.04
Webserver: Apache2
Database: mysql 5.7.16
PHP version: 7.0.13
Nextcloud version: 11.0.1
Contacts version: 1.5.2
Updated from an older Nextcloud or fresh install: fresh install

### List of activated apps:
Enabled:
  - activity: 2.4.1
  - calendar: 1.4.1
  - comments: 1.1.0
  - contacts: 1.5.2
  - dav: 1.1.1
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_pdfviewer: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - tasks: 0.9.4
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - updatenotification: 1.1.1
  - workflowengine: 1.1.1

### The content of config/config.php:
{
    "system": {
        "instanceid": "ocltx252wobc",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nextcloud.domain.net",
            "88.99.**.***"
        ],
        "datadirectory": "\/var\/www\/html\/nextclouddata",
        "overwrite.cli.url": "http:\/\/nextcloud.domain.net",
        "dbtype": "mysql",
        "version": "11.0.1.2",
        "dbname": "nextcloud",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "loglevel": 2,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_from_address": "noreply",
        "mail_domain": "domain.de",
        "mail_smtpauthtype": "PLAIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "mail.domain.net",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "theme": ""
    }
}

### Client configuration
Browser: chrome 55.0.2883.87 (64-bit)

Operating system: ubuntu mate

CardDAV-clients: ios contacts

**Comment by skjnldsv** [comment]
Is this not supposed to be in https://github.com/nextcloud/calendar/ ?

**Comment by itoop** [comment]
Oh, my fault - of course it's about [https://github.com/nextcloud/calendar/](url). Sorry!
