### ISSUE TITLE
Input unfocused due to autosave

### ISSUE THREAD

**Issue by daniel-wtd** [nextcloud/contacts#930]
### Describe the bug

When manually typing a telephone number via Web Client the input is interrupted and the cursor moves around when autosave happens. Since autosaving seems to wait <1s and then saving the cursor sometimes moves to a different location, even when entering the number is not done.

**To Reproduce**
1. Open Contacts Web Ui
2. Click on a contact
3. Click on a telephone number field
4. Click the cursor at the beginning of the line
5. Try to enter some changes to the beginning of your number (wait <1s between each number)
6. Add another number
7. Manually enter a number with a short delay between each key press

**Expected behavior**

Entering new Contact Details like telephone numbers shouldnt been interrupted from mechanisms like auto save.

**Actual behavior**

The unpredictable behaviour of entering details and short interruptions from autosave are hindering me to update my contacts properly via web ui.

Nextcloud: 15.0.4
Contacts: 3.0.3

Please feel free to reach out to me for more details, if needed.

**Comment by skjnldsv** [comment]
@daniel-wtd I thought this was a lose of focus on input, but your issue is actually a duplicate of #923 
This is fixed for the next incoming version

**Comment by daniel-wtd** [comment]
@skjnldsv Thanks a lot! :)
