### ISSUE TITLE
Failure while importing vcf's (and ics's in calendar app) with more than 16 entries

### ISSUE THREAD

**Issue by riegercloud** [nextcloud/contacts#94]
I run two Nextcloud 11.0.1 server based on an ubuntu 16.04 LTS, oDoidC2, mariadb 10.x, php 7.0 and as well php 7.1 on the other server, both systems are on 64Bit.

One server ist installed from scratch and the other one was upgraded from the early beginning of Nextcloud to the current Nextcloud Release.

I enabled the contact (and calendar) app from the nextcloud appstore within Nextcloud.
Both apps crashed while importing contacts or calendar after the 16. successfull entry.
I had to split the vcf from e.g. 233 into seperate files not consisting of more than 16 contacts per file.
Then the import succeeded for all the files without modifying the content itself.

I can reproduce this behaviour on both systems. Unfortunately nothing is written into the nextcloud logs.

What do you need to investigate further? 
How can i export directly from Nextcloud contacts app?
Should i raise a second issue for the calendar issue either?

Looking forward to your response,
Cheers, Carsten

**Comment by riegercloud** [comment]
### Server configuration
**Web server:** nginx/1.11.8 (fpm-fcgi)

**Database:** mysql 10.0.28

**PHP version:** 7.1.1-1+deb.sury.org~xenial+1
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, cgi-fcgi, mysqlnd, PDO, xml, apcu, apc, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, imagick, intl, json, exif, mcrypt, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache

**Nextcloud version:** 11.0.1 (stable) - 11.0.1.2

**Updated from an older Nextcloud/ownCloud or fresh install:** FRESH

**Where did you install Nextcloud from:** Nextcloud.com

**Signing status:**
<details>
	<summary>Signing status</summary>

```
[]
```

</details>

**List of activated apps:**
<details>
	<summary>App list</summary>
```
Enabled:
 - admin_audit: 1.1.0
 - apporder: 0.3.3
 - calendar: 1.5.0
 - contacts: 1.5.2
 - dav: 1.1.1
 - direct_menu: 0.10.0
 - federatedfilesharing: 1.1.1
 - files: 1.6.1
 - files_downloadactivity: 1.0.0
 - files_pdfviewer: 1.0.1
 - files_sharing: 1.1.1
 - files_texteditor: 2.2
 - files_trashbin: 1.1.0
 - files_videoplayer: 1.0.0
 - gallery: 16.0.0
 - issuetemplate: 0.2.0
 - keeweb: 0.3.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.0.0
 - nextcloud_announcements: 1.0
 - notes: 2.2.0
 - notifications: 1.0.1
 - password_policy: 1.1.0
 - previewgenerator: 1.0.1
 - provisioning_api: 1.1.0
 - serverinfo: 1.1.1
 - sharebymail: 1.0.1
 - theming: 1.1.1
 - twofactor_backupcodes: 1.0.0
 - updatenotification: 1.1.1
 - workflowengine: 1.1.1

Disabled:
 - activity
 - comments
 - encryption
 - external
 - federation
 - files_accesscontrol
 - files_automatedtagging
 - files_external
 - files_retention
 - files_versions
 - firstrunwizard
 - survey_client
 - systemtags
 - templateeditor
 - user_external
 - user_ldap
 - user_saml
```
</details>

**The content of config/config.php:**
<details>
	<summary>Config report</summary>

```
{
    "instanceid": "ocsgxkn18248",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "192.168.2.119",
        "192.168.2.16"
    ],
    "datadirectory": "\/var\/nc_data",
    "dbtype": "mysql",
    "version": "11.0.1.2",
    "dbname": "nextcloud",
    "dbhost": "localhost",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "memcache.local": "\\OC\\Memcache\\APCu",
    "loglevel": 1,
    "logtimezone": "Europe\/Berlin",
    "logfile": "\/var\/nc_data\/nextcloud.log",
    "log_rotate_size": 10485760,
    "cron_log": true,
    "filesystem_check_changes": 1,
    "filelocking.enabled": "true",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "\/var\/run\/redis\/redis.sock",
        "port": 0,
        "timeout": 0
    },
    "integrity.check.disabled": false,
    "updater.release.channel": "stable",
    "enable_previews": true
}
```
</details>

**Are you using external storage, if yes which one:** files_external is disabled

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Client configuration
**Browser:** Mozilla/5.0 (Windows NT 10.0; WOW64; rv:50.0) Gecko/20100101 Firefox/50.0

**Operating system:**

### Logs
#### Web server error log
<details>
	<summary>Web server error log</summary>
	```
	Insert your webserver log here
	```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
	<summary>Nextcloud log</summary>
	```
	Insert your Nextcloud log here
	```
</details>

#### Browser log
<details>
	<summary>Browser log</summary>
	```
	Insert your browser log here, this could for example include:

	a) The javascript console log
	b) The network log
	c) ...
	```
</details>

**Comment by skjnldsv** [comment]
Hi!
How big was your vcf file?
Is your import successful after you split your import file?

**Comment by riegercloud** [comment]
Hi, the main file, containing all contacts: 2.293KB
The separated files from about 20KB to 400KB

Yes, all contacts and calendar entries were successfully imported using the separated/splited files.

**Comment by skjnldsv** [comment]
Do you have any feedback of failure for the big one?
Console error? Window freeze?

**Comment by riegercloud** [comment]
many hints in firefox console.
i would prepare your remote login into my Nextcloud ... where to send the credentials?
![01](https://cloud.githubusercontent.com/assets/20593693/22265172/2ed5b33e-e27b-11e6-89bb-8e7d94dff31e.JPG)
![02](https://cloud.githubusercontent.com/assets/20593693/22265173/2ef59da2-e27b-11e6-8a78-db3961641a24.JPG)

**Comment by skjnldsv** [comment]
You can send it to skjnldsv@protonmail.com.
Those 503 errors are strange.

**Comment by skjnldsv** [comment]
If you agree to send me the big file, it could help me too. :)

**Comment by riegercloud** [comment]
it contains sensible data, so how to send to you directly/private?

**Comment by riegercloud** [comment]
sorry - 3 times the attachment was filtered.
please appologize, i will try again in a few minutes

**Comment by skjnldsv** [comment]
No worries, I received everything :)
I'm checking on it. Avatars on some of your contacts seems corrupted.

**Comment by riegercloud** [comment]
fine, want some splitted files either?

**Comment by skjnldsv** [comment]
No need, I isolated the broken contacts :)

**Comment by riegercloud** [comment]
i didn't recognized yet but after your comment i do: 
the successfull import does not contain avatars/images anymore.

**Comment by riegercloud** [comment]
Error still occurs with contacts 1.5.3. 
do you need further information?

**Comment by skjnldsv** [comment]
@riegercloud Not much time atm. Could you try master? See if this works?
