### ISSUE TITLE
Missing parameter value in 'ADR;TYPE=home;LABEL=ABC\\nJalandhar\\:;;ABC;Jalandhar;Punjab;144003;India'

### ISSUE THREAD

**Issue by raoulbhatia** [nextcloud/contacts#944]
### Describe the bug
I have a vcard on my nextcloud server that displays the name in the middle contact name column.  Upon opening, the console shows the following parse error and the contact vanishes with "

```
Object { message: "Missing parameter value in 'ADR;TYPE=home;LABEL=ABC\\nJalandhar\\:;;ABC;Jalandhar;Punjab;144003;India'", name: "ParserError", 
stack: "1/ICAL.parse</i._handleContentLine@https://cloud.DOMAIN.TLD/apps/contacts/js/contacts.js?v=28c2da0b-4:7:77986\ni/<@https://cloud.DOMAIN.TLD/apps/contacts/js/contacts.js?v=28c2da0b-4:7:77288\n1/ICAL.parse</i._eachLine@https://cloud.DOMAIN.TLD/apps/contacts/js/contacts.js?v=28c2da0b-4:7:80819\ni@https://cloud.DOMAIN.TLD/apps/contacts/js/contacts.js?v=28c2da0b-4:7:77260\nt@https://cloud.DOMAIN.TLD/apps/contacts/js/contacts.js?v=28c2da0b-4:156:295\nt/</<@https://cloud.DOMAIN.TLD/apps/contacts/js/contacts.js?v=28c2da0b-4:112:4781\na@https://cloud.DOMAIN.TLD/apps/contacts/js/contacts.js?v=28c2da0b-4:7:152119\nL/<@https://cloud.DOMAIN.TLD/apps/contacts/js/contacts.js?v=28c2da0b-4:7:152264\nc@https://cloud.DOMAIN.TLD/apps/contacts/js/contacts.js?v=28c2da0b-4:7:179187\n" }
```

**To Reproduce**
The following vcard was transmitted to the browser:
```
<card:address-data>BEGIN:VCARD&#13;
VERSION:4.0&#13;
PRODID:+//IDN bitfire.at//DAVdroid/2.0.2-gplay ez-vcard/0.10.4&#13;
UID:xxxx-D5F0-0001-CF13-xxxx&#13;
FN:XXX XXX&#13;
N:XXX;XXX;;;&#13;
NICKNAME:XYZ&#13;
TEL;TYPE=work:+91 xx xx xx&#13;
TEL;TYPE=cell:+91 xx xx xx&#13;
EMAIL;TYPE=work:xxx@gmail.com&#13;
davdroid1.EMAIL;TYPE=x-other:xxx@yahoo.com&#13;
davdroid1.X-ABLabel:Other&#13;
ADR;TYPE=home;LABEL=ABC\nJalandhar\:;;ABC &#13;
 ABC;Jalandhar;Punjab;144003;India&#13;
NOTE:Home: ABC Note&#13;
BDAY:--0101&#13;
REV:20180818T062203Z&#13;
END:VCARD&#13;
</card:address-data>
```

**Expected behavior**
Vcard displays correctly.

**Actual behavior**
Tell us what happened instead.

**Fix**
I updated the contact via davx5 and it got re-uploaded.  Things are now working correctly.

I will try to provide the new vcard and/or a diff if required.

### Server configuration

**Operating system**: Ubuntu Linux 18.04.2 LTS

**Web server:** Nginx 1.14.0-0ubuntu1.2

**Database:** MySQL 5.7 5.7.25-0ubuntu0.18.04.2

**PHP version:** PHP7.2 7.2.15-0ubuntu0.18.04.1

**Nextcloud version:** 15.0.4

**Contacts version:** 3.0.3

**Updated from an older Nextcloud or fresh install:** Updated since years

**Signing status:**
```
No errors have been found.
```

**List of activated apps:**
```
  - files_versions: 1.8.0
  - files_videoplayer: 1.4.0
  - firstrunwizard: 2.4.0
  - gallery: 18.2.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.3.0
  - nextcloud_announcements: 1.4.0
  - notes: 2.5.1
  - notifications: 2.3.0
  - oauth2: 1.3.0
  - password_policy: 1.5.0
  - phonetrack: 0.4.3
  - previewgenerator: 2.0.0
  - provisioning_api: 1.5.0
  - richdocuments: 3.2.1
  - serverinfo: 1.5.0
  - sharebymail: 1.5.0
  - spreed: 5.0.2
  - support: 1.0.0
  - survey_client: 1.3.0
  - systemtags: 1.5.0
  - tasks: 0.9.8
  - theming: 1.6.0
  - twofactor_backupcodes: 1.4.1
  - updatenotification: 1.5.0
  - workflowengine: 1.5.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - unsplash
  - user_ldap
```

**Nextcloud configuration:**
```
-
```

### Client configuration
**Browser:** Firefox 65.0.1

**Operating system:** MacOS 10.14.3

**CardDAV-clients:** DAVx5

#### *Web server error log*
```
Insert your webserver log here
```

#### *data/nextcloud.log*
```
Insert your Nextcloud log here
```

#### Browser log
<details>
<summary>How to access your browser console (Click to expand)</summary>

# Chrome
- Press either CTRL + SHIFT + J to open the “console” tab of the Developer Tools.
- Alternative method:
    1. Press either CTRL + SHIFT + I or F12 to open the Developer Tools.
    2. Click the “console” tab.

# Safari
- Press CTRL + ALT + I to open the Web Inspector.
- See Chrome’s step 2. (Chrome and Safari have pretty much identical dev tools.)

# IE9
1. Press F12 to open the developer tools.
2. Click the “console” tab.

# Firefox
- Press CTRL + SHIFT + K to open the Web console (COMMAND + SHIFT + K on Macs).
- or, if Firebug is installed (recommended):
    1. Press F12 to open Firebug.
    2. Click on the “console” tab.

# Opera
1. Press CTRL + SHIFT + I to open Dragonfly.
2. Click on the “console” tab.
</details>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by skjnldsv** [comment]
Hello and thanks for your report!
`ADR;TYPE=home;LABEL=ABC\nJalandhar\:;;ABC
 ABC;Jalandhar;Punjab;144003;India`
should be
`ADR;TYPE=home;LABEL=ABC\nJalandhar:;;ABC
 ABC;Jalandhar;Punjab;144003;India`
Notice the colon, the slash before needs to be removed otherwise it's being ignored and not read as a colon

**Comment by raoulbhatia** [comment]
Thanks @skjnldsv for the feedback.  I will double cross-check this with my backup.

However, Contacts should handle such larse errors more gracefully.  Even ifnone property is wrong, the contact should not completely disaper from the view.

There should be a possibility for the user to correct the error, which is currently not available.

I am sorry I missed this in the original report.

**Comment by skjnldsv** [comment]
@raoulbhatia well, I'd say I agree with you but I also disagree.
Though we have a way to auto fix some vcards, issues like yours can be very hard to work with.
How can I be sure the `:` is here as a mistake, or because the user have a label like `Work\: ABC company`? In that case, there is no way of knowing if this is an issue or something done on purpose :(

I would then contradict myself by stating that we could also have some kind of `failed contact` category on the left, but then it would get very technical and most of our users would never know what to do with that. (Nor do most of them would take the time to manually fix those issues)

**Comment by raoulbhatia** [comment]
Even as it might be complicated to handle, simply removing the contact from the view is IMHO not a user friendly option.

I am attach some screenshots of a different contact where i still have this problem to highlight the issue.

I am happy to hear your feedback,
Raoul

![1_search](https://user-images.githubusercontent.com/727412/53232735-0e9cf700-368c-11e9-8505-e64b0da9e609.png "Contact search")
![2_loading](https://user-images.githubusercontent.com/727412/53232739-12c91480-368c-11e9-9f2e-5f687ffc3bde.png "Contact loading when selected")
![3_this_contact_doesnt_exists_anymore_on_the_server](https://user-images.githubusercontent.com/727412/53232743-152b6e80-368c-11e9-88b6-22155fa49d7a.png "This contact doesn't exists anymore on the server.")

**Comment by skjnldsv** [comment]
Yes, you're right! :)
There is even an already opened issue about better handling this error: #762
