### ISSUE TITLE
umlauts make name disappear

### ISSUE THREAD

**Issue by beinaendi** [nextcloud/contacts#946]
Hi everybody,

I am a German speaking person, thus many of my contacts have umlauts like ä, ö, ü. When I download any contact group as vcf, it works perfectly, but prenames or surnames with umlauts are deleted completely.

To reproduce
1. Make a new contact just like "Max Müller"
2. Add the contact to a group
3. Download the Group
4. Import the vcf file in your contacts programm (in my case contacts on OS X)
5. "Max Müller" will appear as "Max" without any surname

This happens on next cloud 15.0.4 with contacts 3.0.3

Best wishes

**Comment by skjnldsv** [comment]
@beinaendi Hello and thanks for your report :)
Could you attach the vcf file here please? (rename to .txt)

**Comment by beinaendi** [comment]
@skjnldsv Hello, of course not ;-) But I made you an example with Max Müller. After downloading it, the surname appears as "M¸ller". Please find the renamed vcf file attached.
[test.txt](https://github.com/nextcloud/contacts/files/2893816/test.txt)

**Comment by skjnldsv** [comment]
@beinaendi okay, so the display of the contact is ok on the nextcloud contacts app, correct?
Only when importing it into your OSX contacts manager it starts to misbehave? 

Because looking at your vcard, `FN:Max Müller` is correct and have the proper umlaut, and `N;SORT-AS=Max Müller:Müller;Max;;;` as well :woman_shrugging:

**Comment by beinaendi** [comment]
@skjnldsv Yes, on the website everything appears perfect. But when I press the download button (arrow down) next to the contact group, this is what happens. I cannot understand why the vcard looks correct on your computer. This is what it looks like on a Mac with macOS Mojave 10.14.3

BEGIN:VCARD
VERSION:3.0
PRODID:-//Sabre//Sabre VObject 4.1.6//EN
UID:urn:uuid:40595350-0230-4a91-9863-9eeccf416771
FN:Max M¸ller
CATEGORIES:test
N;SORT-AS=Max M¸ller:M¸ller;Max;;;
EMAIL;TYPE=PREF:max@mueller.de
TEL;TYPE=CELL:+49 123 456789
ORG:Max AG;
END:VCARD

**Comment by beinaendi** [comment]
So it seems to be an OS X issue. Tried to open the file with TextEdit, BBEdit and Word. Same problem in all programs.

**Comment by beinaendi** [comment]
@skjnldsv Well, I couldn't find a solution, but 2 options for a workaround, because it is a text-encoding problem:

1. Changing the file:
- Open TextEdit
- Go to open dialogue and select the file.
- Before opening it, click on the Options button and change the encoding of the file to Windows Latin 1
- Save the file

2. Importing it correctly 
- Open contacts app
- Go to import dialogue and select the file
- Before importing it, click on the Options button and change the encoding of the file to Windows Latin 1

But still I don't know if the vcf file could be changed in a way that file encoding would be recognized automatically?

**Comment by beinaendi** [comment]
@skjnldsv I finally found a workaround.

If I use a texteditor and open the file using text encoding "Western (Windows 1 Latin)", then save it encoded as "UTF-8" it everything works out fine.

What's still a bit strange for me is the fact, that it doesn't give me the correct result, when I import the vcf file directly in contacts app using "Western (Windows 1 Latin)". 

Maybe this helps to solve the problem on your side?

**Comment by skjnldsv** [comment]
Hum, that is strange. It seems indeed that the server is encoding everything in iso-8859-1 (looking at your file).

Creating new contacts on my server is properly encoding them in utf-8 for a single vcard, but us-ascii for the group download. I'll check on it later!

**Comment by call-me-matt** [comment]
I can confirm this, downloading a contact is UTF-8, while downloading a group is in ISO-8859-15. (fortunately not a problem on linux)

**Comment by call-me-matt** [comment]
I think this simple addon fixes the issue:
https://github.com/call-me-matt/contacts/commit/677da685feb01e16a5dd7ac9f89d8d2d9fbc9907
Can you verify?

**Comment by Snaptags** [comment]
I have a similar issue using Calendar 2.0.3 on Nextcloud 18.0.6: Downloading groups containing NO special characters result in an utf-8 formatted file. I can re-import that file without any issues. If the group (or any of the contacts) contains special characters I'll get a "latin-1" formatted file and have to convert it to utf-8 manually in order to be able to import it again :-(
