### ISSUE TITLE
Rename a group

### ISSUE THREAD

**Issue by lucavallerini** [nextcloud/contacts#956]
A pretty basic feature is missing: the ability to rename a group. At the moment (3.0.3) the only way to "rename" a group is to add each contact one by one to a new group. Ideally, I'd like a three-dotted menu at the end of the group name on the left column that groups a few functions, like rename, delete and download.

**Comment by skjnldsv** [comment]
Unfortunately renaming a group will not come before #213 :/

**Comment by nunesgh** [comment]
@skjnldsv, given the latest developments on #1175, would it be possible to solve this issue in the next major milestone, too?

**Comment by skjnldsv** [comment]
@nunesgh we're getting close to batch-processing, but it require some tiem to work on, time that I don't have at the moment :(

**Comment by nunesgh** [comment]
@skjnldsv I understand! Thank you for replying!

**Comment by serversci** [comment]
Any update on when groups can be renamed? Is there any **occ** workaround that can be done from the Linux command line to rename groups?

**Comment by Diskoteket** [comment]
> Any update on when groups can be renamed? Is there any **occ** workaround that can be done from the Linux command line to rename groups?

+1

**Comment by skjnldsv** [comment]
> Is there any **occ** workaround

No, there is not, sorry

**Comment by BentHaase** [comment]
Pushing this issue, any news?

**Comment by hansimausisteffiwurstbrot** [comment]
How much work is it to get implement this feature?

Perhaps we can create some financial incentive?

I'm quite surprised that this issue still is open. How do people use the group feature? It seems quite important to me, to be able to change and delete a group...

**Comment by mrzool** [comment]
> At the moment (3.0.3) the only way to "rename" a group is to add each contact one by one to a new group. 

Which would cause you to lose all settings and automations related to the original group, like custom access rights, automatic user assignment during registration and group folders assignments. Not a viable workaround for any real-world scenario sadly.

**Comment by readonly24** [comment]
I really need to change group names. When can we expect to see this feature in the release? Thanks.

**Comment by flederwiesel** [comment]
This should be regarded a **_basic feature_**. It is simply annoying not to be able to rename or delete a group. C'mon, let reality catch up....

**Comment by nikrozman21** [comment]
100% agree! I want to change one of my group names

**Comment by BFOX12** [comment]
What is the status on this issue ?

**Comment by OneAceGuy** [comment]
And why is this related to issue #213? Looks like that issue is for Contacts and CardDAV, but this issue is for Nextcloud Groups for users. I have not looked at the code yet but would have thought these were separate items. Thanks for the hard work and any feedback on this item

**Comment by itsequans** [comment]
I'd like to contribute to this apps but I'm not a PHP dev just and IT admin, so I have built a script providing this feature by updating the Database directly, until someone will develop this feature in the app.
- The script must run on the server hosting the DB
- The script has been written for MariaDB servers, and 'd need adjustments for Postgrey or other DB servers
- Feel free to update to fit your own need
- Despite I have tested the script to cover all scenarios, it could still exist bugs in, so Keep in mind that working in the DB
  directly is at your own risks
[rename_ContactsGroup_DB.sh.gz](https://github.com/nextcloud/contacts/files/7915063/rename_ContactsGroup_DB.sh.gz)

**Comment by grinapo** [comment]
@itsequans 
>  I have built a script providing this feature by updating the Database directly, 

I think the risky part is that some plugins may reference a group by name, and mysql doesn't seem to have FOREIGN KEYs around to follow that backwards.

**Comment by brendan-pike** [comment]
Just ran into this issue too, so +1

**Comment by ChristophWurst** [comment]
Just add your :+1: to the request and avoid causing a notification for everyone :v:

**Comment by lawipac** [comment]
Versioin 23.0.3,  still not having it. group name cannot be changed

**Comment by Lipovlan** [comment]
I have the same issue. Renaming contact groups saved in oc_cards (not oc_groups) seems like a possible and fast task. If possible I would like to somehow incentivize advancement on this issue.

In the meantime @itsequans script worked flawlessly (thank you), although it is a crude solution to have to manually edit the SQL database.

**Comment by chatlumo** [comment]
Hello,

Any news about this basic feature ?

**Comment by VincentSC** [comment]
From what I see in the database, there is not an "id" (Long, auto-id), but everything is linked via the "gid" (String). So the account-IDs (visible in frontend) is used to interlink the tables! This answer sums it up: https://stackoverflow.com/a/14897642

It would have been an easy thing to do when the database was designed with auto-IDs. 

What needs to be done is to totally redesign the database. This has a lot of implications, like many plugins not working anymore. The database also needs to prevent old apps from accidentally breaking the tables. So the total operation is huge!

But still - I see no reason to postpone this further. Maintenance costs for both NC and all apps will go up, if not fixed.

**Comment by oktayacikalin** [comment]
Now I'm also starting to miss this feature. I've groups for the classes in school of our children and every summer I will have to move a lot of contacts around.

**Comment by shu0406** [comment]
![grafik](https://github.com/nextcloud/contacts/assets/76654412/f6cace58-a5ca-4913-b0b2-29604042f188)

I think it is already possible with our Version 26.0.5

**Comment by oktayacikalin** [comment]
Which version does your contacts app have? Or which app is that?
I've contacts version 5.5.1 installed in Nextcloud 28.0.2 stable.

**Comment by VincentSC** [comment]
Just look at the url of a group - the group-name is shown at the end. The groups can superficially be relabelled, but will keep the same name. So the group with url `<domain>/settings/users/Squares` can be relabelled to "Circles" but they will remain named "Squares" forever.

As a result of this problem (which I technically explained above), we have for example two groups named `employees` and `Employees`, which both are labelled "Employees". Yup, it's case-sensitive in the url!
![nextcloud-employees](https://github.com/nextcloud/contacts/assets/5090382/08c95c33-ddcc-42ae-b0a2-4d67abcc0587)

So want to rename a group? First, create a new group with the right name. Can be done via the web-interface or `occ group:add`. Then run `occ group:list` to get the members of each group. Then add each user to the new group with `occ group:adduser`. Finally check if the members of the first group are all in the new group, to delete the first one. I just found https://help.nextcloud.com/t/moving-users-from-one-group-to-another-or-renaming-group/127584 which suggested the same.

Or a bash-script `rename-group.sh` - anyone? :)
One hint that solves half the work: get members of a group called "group": `occ group:list --output json | jq '.group' | jq .`, and use occ group:list --output json | jq '.group' | jq -c '.[]'` to list just the names, to use them in bash.

**Comment by oktayacikalin** [comment]
Why is it a bad thing that the URL of a group changes, when its name changes?

I think, that the URL should always (try to) reflect the name or ID of an object.

**Comment by VincentSC** [comment]
See my comment above on tue technical design mistake of the database, that has caused this problem.

**Comment by oktayacikalin** [comment]
You mean your comment about that it's being linked via the GID string? Yeah, that's a pitty. But that should be fixable by executing a couple of db transactions and some modification in the codebase. It might be a chore, yeah.

Is the gid string linked to the other tables? Do the references update automatically, when I change the gid of the group?

But for now we could have a workaround. I renamed one of my groups by using my contacts app on my Android phone. I think, it created a new group, assigned all respective contacts to the new one and deleted the old one. We should at least have this in the Nextcloud contacts web UI, too.

**Comment by shu0406** [comment]
> Which version does your contacts app have? Or which app is that? I've contacts version 5.5.1 installed in Nextcloud 28.0.2 stable.

We have also contacts 5.5.1 and NC 26.0.5 Enterprise. Maybe a Enterprise feature? I checked it, if I rename the group the changes dont effect shared folders and I can invite the "new named" group to conversations. Thats everything I want/need at the beginning of a new school year!
