### ISSUE TITLE
Import partly fails if database simultaneous connections are limited

### ISSUE THREAD

**Issue by Aurelien-** [nextcloud/contacts#957]
### Describe the bug
When importing a file containing 184 contacts using the web interface, only 30 contacts are imported. This number equals the number of simultaneous connection allowed by the database on my provider shared host.

**To Reproduce**
1 Have a database which limits the number of simultaneous connections
2. Go to the contact page
3. Click on settings and import to
4. Choose a contact archive containing more contacts than allowed simultaneous connections
5. Validate

**Expected behavior**
All contacts should be imported

**Actual behavior**
 The number of imported contacts is only equal to the number of allowed simultaneous database connections

### Server configuration

**Operating system**: Linux

**Web server:** Apache

**Database:** MySQL 5.6

**PHP version:** 7.2

**Nextcloud version:** 15.0.4
**Contacts version: 3.0.3

**Updated from an older Nextcloud or fresh install: fresh install

**Signing status:**
No errors have been found.

**List of activated apps:**
Enabled:
  - accessibility: 1.1.0
  - activity: 2.8.2
  - bruteforcesettings: 1.3.0
  - calendar: 1.6.4
  - cloud_federation_api: 0.1.0
  - comments: 1.5.0
  - contacts: 3.0.3
  - dav: 1.8.1
  - end_to_end_encryption: 1.1.0
  - federatedfilesharing: 1.5.0
  - federation: 1.5.0
  - files: 1.10.0
  - files_frommail: 0.2.0
  - files_pdfviewer: 1.4.0
  - files_sharing: 1.7.0
  - files_texteditor: 2.7.0
  - files_trashbin: 1.5.0
  - files_versions: 1.8.0
  - files_videoplayer: 1.4.0
  - firstrunwizard: 2.4.0
  - gallery: 18.2.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.3.0
  - mail: 0.11.0
  - nextcloud_announcements: 1.4.0
  - notifications: 2.3.0
  - oauth2: 1.3.0
  - password_policy: 1.5.0
  - phonetrack: 0.4.3
  - provisioning_api: 1.5.0
  - serverinfo: 1.5.0
  - sharebymail: 1.5.0
  - socialsharing_email: 1.0.5
  - spreed: 5.0.2
  - support: 1.0.0
  - survey_client: 1.3.0
  - systemtags: 1.5.0
  - tasks: 0.9.8
  - theming: 1.6.0
  - twofactor_backupcodes: 1.4.1
  - twofactor_totp: 2.1.1
  - twofactor_u2f: 2.1.1
  - updatenotification: 1.5.0
  - user_saml: 2.1.1
  - workflowengine: 1.5.0
Disabled:
  - admin_audit
  - deck
  - encryption
  - files_external
  - user_ldap

**Nextcloud configuration:**
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "exemple.com",
            "contact.exemple.com",
            "cal.exemple.com"
        ],
        "forcessl": true,
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "15.0.4.0",
        "overwrite.cli.url": "https:\/\/exemple.com",
        "htaccess.RewriteBase": "\/",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "filelocking.enabled": "true",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 35172,
            "password": "***REMOVED SENSITIVE VALUE***",
            "timeout": 0
        },
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "ssl",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "theme": "",
        "loglevel": 2
    }
}

### Client configuration
**Browser:** Firefox 65

**Operating system:** Fedora

**CardDAV-clients:**

#### *Web server error log*
PHP message: PHP Fatal error:  Uncaught Doctrine\\DBAL\\DBALException: Failed to connect to the database: An exception occured in driver: SQLSTATE[HY000] [1203] User ***** already has more than 'max_user_connections' active connections in /home/*****/www/nextcloud/lib/private/DB/Connection.php:64

### Nextcloud log
{"reqId":"XHMFzQobKJMAABzSeccAAABf","level":3,"time":"2019-02-24T20:59:58+00:00","remoteAddr":"aaa.aaa.aaa.aaa,"user":"--","app":"PHP","method":"PUT","url":"\/remote.php\/dav\/calendars\/*******\/personal\/Nextcloud-EEBGGIGY3KGEG5PHEC7K5.ics","message":"Uncaught Doctrine\\DBAL\\DBALException: Failed to connect to the database: An exception occured in driver: SQLSTATE[HY000] [1203] User *******cloud already has more than 'max_user_connections' active connections in \/home\/*******\/www\/nextcloud\/lib\/private\/DB\/Connection.php:64\nStack trace:\n#0 \/home\/*******\/www\/nextcloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Connection.php(429): OC\\DB\\Connection->connect()\n#1 \/home\/*******\/www\/nextcloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Connection.php(389): Doctrine\\DBAL\\Connection->getDatabasePlatformVersion()\n#2 \/home\/*******\/www\/nextcloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Connection.php(328): Doctrine\\DBAL\\Connection->detectDatabasePlatform()\n#3 \/home\/*******\/www\/nextcloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Connection.php(623): Doctrine\\DBAL\\Connection->getDatabasePlatform()\n#4 \/home\/*******\/www\/nextcloud\/lib\/private\/DB\/Connection.php(151): Doctrine\\DBAL\\Connection->setTransactionIsolation(2)\n#5 \/home\/*******\/www\/nextcloud\/3rdparty at \/home\/*******\/www\/nextcloud\/lib\/private\/DB\/Connection.php#64","userAgent":"Mozilla\/5.0 (X11; Fedora; Linux x86_64; rv:65.0) Gecko\/20100101 Firefox\/65.0","version":"14.0.7.1"}

#### Browser log
Do not have these logs

**Comment by skjnldsv** [comment]
Closing gin favour of nextcloud/server#14426
