### ISSUE TITLE
Some feature requests

### ISSUE THREAD

**Issue by d4v1d15** [nextcloud/contacts#96]
I have some feature request for the next version of contacts:

- Export all contacts (or select the contacts)
- Delete all contacts (or select the contacts)
- Assign all contacts to a group (or select the contacts)
- Select contacts
- Rename a group
- Delete a group (without deleting contacts)

**Comment by jancborchardt** [comment]
Please look through the existing issues as I think some of these things are already opened as issues. Then for the others please open individual issues. Thank you! :)
