### ISSUE TITLE
Spinning wheel on single contact

### ISSUE THREAD

**Issue by peteman52** [nextcloud/contacts#983]
Just 'Spinning Weel' for single contact.

**Comment by a1pilot** [comment]
@peteman52 same here.

**Comment by skjnldsv** [comment]
@peteman52 @a1pilot latest update? 3.0.4?
Any error in logs?

**Comment by a1pilot** [comment]
@skjnldsv Nothing in the logs, but I get this in the console:

`TypeError: t.split is not a function
    at Function.ICAL.VCardTime.fromDateAndOrTimeString (ical.js:6185)
    at Object.decorate (ical.js:1073)
    at n._decorate (ical.js:2888)
    at n._hydrateValue (ical.js:2871)
    at n.getFirstValue (ical.js:3017)
    at t.getFirstPropertyValue (ical.js:2449)
    at t.get (contact.js:154)
    at a.Ee (ContactDetails.vue?da84:282)
    at a.t._render (vue.runtime.esm.js:3535)
    at a.r (vue.runtime.esm.js:4041)
Ht @ vue.runtime.esm.js:1887`

**Comment by skjnldsv** [comment]
Will release the fix in less than one hour (depending on the train network!)
Sorry about this, thanks for your bug report :wink:

**Comment by alraban** [comment]
I'm experiencing this issue with contacts version 3.0.5 (no details load for any contacts, I only see a spinning wheel).  If it matters I updated directly from 3.0.3 (3.0.4 was never installed).  This is on Nextcloud 15.0.5, running on Debian 9, and there are no errors in the logs.  Let me know if I can provide any additional info.

**Comment by skjnldsv** [comment]
@alraban hello!
Please open a new issue directly! :)
When creating it, don't forget to attach the potential vcard t hat is causing the issue (if you can) and adding your browser console log :bowing_man:
