### ISSUE TITLE
False Contact Not Synced Errror

### ISSUE THREAD

**Issue by a1pilot** [nextcloud/contacts#985]
Version 3.0.5, when creating a new contact in the webapp it shows the following error:

![Untitled](https://user-images.githubusercontent.com/665111/54110475-643a0900-43d9-11e9-96de-31a3ec398f0a.png)

**Expected behavior**
Autosave should submit periodically.

**Actual behavior**
Claims it isn't saving, but when moving to another contact the newly added one persists.  Closing the browser and returning, the contact still exists.  Appears to be an erroneous error.

**Comment by skjnldsv** [comment]
What is the issue? When creating a contact, it does not push it to the server. Otherwise people would get empty contacts if they forget to edit them in the first place.
As the tooltip says, change anything in this _new contact_ and it will be synced to the server :)

**Comment by a1pilot** [comment]
@skjnldsv I did change things and the error persists.

I added a phone number and email and the error remained.

**Comment by skjnldsv** [comment]
@a1pilot Sorry then, you should have been more clear! :)
Can you post the content of your browser's log?

**Comment by a1pilot** [comment]
Console:
`JQMIGRATE: Migrate is installed, version 1.4.0
contact.js:67 This contact did not have a proper uid. Setting a new one for  t {jCal: Array(3), addressbook: {…}, vCard: t, conflict: false}`

**Comment by skjnldsv** [comment]
Nope, all is ok on those logs, when you edit the contact, there should be a little spinner.
Is it showing? Can you post a network log screenshot of the (supposed) contatc push request to the server?

Before you do anything, still on the development tools, there is a tab called `network`. Click on it and then the xhr filter. Do your action and screenshot the network log like this:
![capture d ecran_2018-09-27_21-49-46](https://user-images.githubusercontent.com/14975046/46170857-43548000-c29f-11e8-9403-db72713dd9c1.png)

**Comment by a1pilot** [comment]
@skjnldsv thanks.  Not critical.
