### ISSUE TITLE
Company Saved as Contact Name

### ISSUE THREAD

**Issue by a1pilot** [nextcloud/contacts#986]
Version 3.0.5

When creating a new contact in the webapp, it submits the contact company as the contact name.  When it syncs to my phone, it shows "Company" in the contact list.  The name isn't present.

**Comment by skjnldsv** [comment]
Hello, this ia done on purpose! If you don't have a valid `full name` property, the app will try to find the closest appropriate data to use (a `full name` data is mandatory)
So it will try to generate one by using the `detailed name` property, if present, or fallback to using the `organisztion` property :)

**Comment by a1pilot** [comment]
So I enter "Vets (Hemel)" in the name and then "Expert Care" in the company.  It ignores the name I give and just shows the name as "Expert Care" on my phone as both the name and the company.

**Comment by skjnldsv** [comment]
What does the nextcloud's ui displays?

**Comment by a1pilot** [comment]
The webapp shows the correct detail in the contact list, and in the contact information.

**Comment by a1pilot** [comment]
I note on my phone that the name of the phone number type, such as Home, is preceded by a double quote.  Not sure if this is related to the field assignments.

**Comment by a1pilot** [comment]
Possibly related to: [https://github.com/nextcloud/contacts/issues/910](url)

**Comment by a1pilot** [comment]
@skjnldsv I just removed the company "Expert Care" from the above example and the contact in ios updated to show the name "Vets (Hemel)".

But.... now I have a random contact in the ios contact list under "#" which is the number for that contact.  Doesn't appear in the nexcloud list.

Something isn't right with the generated vcards.

The number here is for the contact Vets above:

![2019-03-11_09-42-53_1572A](https://user-images.githubusercontent.com/665111/54114597-ae73b800-43e2-11e9-818d-c16fa2694577.png)

**Comment by skjnldsv** [comment]
I will need this vcard so I can understand what's going on please :)

**Comment by a1pilot** [comment]
If I open it in Outlook, the phone number is blank.

`BEGIN:VCARD
VERSION:3.0
PRODID:-//Sabre//Sabre VObject 4.1.6//EN
UID:4fcb4b82-076f-4cbf-8c58-1d01514f18cc
REV;VALUE=DATE-AND-OR-TIME:20190311T094017Z
FN:Vets (Hemel)
ADR;TYPE=HOME:;;;;;;
EMAIL;TYPE=HOME:
TEL;TYPE="WORK,VOICE":+44 1442 500260
ORG:
END:VCARD
`

**Comment by skjnldsv** [comment]
Okay, I'm a bit confused here, what issue are we talking about? The tel parameter quotes? The FN field being filled with the ORG's content? The iOS not displaying the contact properly?

**Comment by a1pilot** [comment]
All of the above.

If I put a company name, the number doesn't have a problem but the name does.  The "home" designation of a phone number shows a spurious double quote in ios.

If I don't put a company name, the name is ok but the number then becomes its own contact.

I can open multiple bug reports for each one, but I suspect they are all one in the same.

**Comment by skjnldsv** [comment]
Let's tackle them one by one then. :)

1. what about not having an org name? Does he phone displays properly?
2. What about the nextcloud's ui? Is it behaving properly? Because then this is an iOS issue. If the vCard we generate is correct according to the standards, then iOS is just not following them :confused:

**Comment by a1pilot** [comment]
1. Almost.  Where is shows the phone number or email type (e.g. Home, Work), it actually shows in all capitals with a leading double quote (e.g. "HOME, "WORK).

2. This appears to work fine.

This wasn't an issue prior to the 3.0.3 (ish) update I believe.  It was working fine for a long time, then I did a new install on a new server and contacts wasn't quite right.

**Comment by a1pilot** [comment]
@skjnldsv where do you generate the .vcf file?  I'm going to try and fix it myself.

**Comment by a1pilot** [comment]
@skjnldsv is more info needed?  I've confirmed the vcf is erroneous in ios and Outlook.  Seems like a bug.

**Comment by skjnldsv** [comment]
Sorry, this one slipped through :) 

Please post a screenshot of every vcf that failed and the associated vcf file.
I need to have a proper visibility of what error/issue we have for each case. It's getting confusing for me with all those vcard example on every issues :see_no_evil:

**Comment by a1pilot** [comment]
@skjnldsv they're all the same as the example above.  The problem is with the quotation marks on the phone number type (e.g. "work,voice").  If I remove the quotes it works in ios and outlook.

Something is applying tags wrongly and it's causing the vcf to be invalid.

**Comment by a1pilot** [comment]
@skjnldsv edited a contact on my phone and it wiped all the numbers for that contact.  Contact shows in the list in the app online, but no numbers.

This app is now fundamentally broken, and there is a lack of reply from development, so I'm classing this as closed and moving to an alternative.

**Comment by skjnldsv** [comment]
@a1pilot I'm sad to hear that!
Lots of development is pushed towards this app, but maybe not on this issue.
There are a lot of requests or discussions, and not only on the contacts app. Different priorities and focus.

This is still an open source project, anyone can contribute. Could you help and fix the issue maybe? That would be awesome!

**Comment by a1pilot** [comment]
@skjnldsv I would consider inability to edit contacts on a phone, names being incorrectly shown due to a feature attempt by devs, and incorrectly formatted vcf files as pretty fundamental and high priority.

Unfortunately, I did ask questions to get me started above, but was ignored.  So I'm out.

**Comment by skjnldsv** [comment]
> @skjnldsv I would consider inability to edit contacts on a phone

Sure, I would too!
Unfortunately I was not able to properly understand your issue.

I'm sorry I was not able to provide the solution in the timeline you expected.
I wish you a good day!
Cheers,
John

**Comment by jancborchardt** [comment]
@a1pilot we are a community-driven project, so sometimes replies or debugging issues can take some time. The more info you provide, the easier it is to reproduce and fix it.

Please be mindful of that and keep a friendly tone according to our Code of Conduct: https://nextcloud.com/code-of-conduct/

**Comment by a1pilot** [comment]
@jancborchardt a community I support with various bug reports and information, along with an attempt above to join it directly (as mentioned, was ignored).

It's disappointing that only when I complain I get quick replies.  I have continuously responded and waited, only to be told that more info is needed after I indicate I'm done waiting - couldn't have said it sooner?

I've been polite and as helpful as possible throughout.  If the frustration shows, I suggest consideration be given to the cause and not the outcome.

I won't be replying again.  As above, I'm using another app outside of Nextcloud.
