### ISSUE TITLE
Unable to create new user since v3.0.5

### ISSUE THREAD

**Issue by gnouts** [nextcloud/contacts#995]
### Describe the bug
In the contact app v3.0.5, clicking an "create contact" doesn't do anything

**To Reproduce**
1. Update the app to v3.0.5
2. Go to Contact app, in web interface
3. Click the new contact in top left corner
4. Nothing happen

**Expected behavior**
An empty contact form should appear.

### Server configuration

**Operating system**: Debian9

**Web server:** Nginx

**Database:** MariaDB

**PHP version:** 7

**Nextcloud version:** 15.0.4

**Contacts version:** 3.0.5

**Signing status:** : Integrity check disabled (using Yunohost package)

**List of activated apps:**

**Nextcloud configuration:**
```
Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

### Client configuration
**Browser:** : Firefox Quantum ESR

**Operating system:** Windows 10

**CardDAV-clients:** : nextcloud web interface

#### *Web server error log*
```
Insert your webserver log here
```

#### *data/nextcloud.log*
```
Insert your Nextcloud log here
```

#### Browser log
Console log
```
ReferenceError
​
columnNumber: 32859
​
fileName: "https://cloud.domain.tld/apps/contacts/js/contacts.js?v=635169df-17"
​
lineNumber: 177

message: "oca_contacts is not defined"

stack: "e/<@https://cloud.domain.tld/apps/contacts/js/contacts.js?v=635169df-17:177:32859
_@https://cloud.domain.tld/apps/contacts/js/contacts.js?v=635169df-17:7:161552
b/o._invoke</<@https://cloud.domain.tld/apps/contacts/js/contacts.js?v=635169df-17:7:161342
T/</t[e]@https://cloud.domain.tld/apps/contacts/js/contacts.js?v=635169df-17:7:161728
hr@https://cloud.domain.tld/apps/contacts/js/contacts.js?v=635169df-17:177:29085
a@https://cloud.domain.tld/apps/contacts/js/contacts.js?v=635169df-17:177:29292
mr/</<@https://cloud.domain.tld/apps/contacts/js/contacts.js?v=635169df-17:177:29353
O@https://cloud.domain.tld/apps/contacts/js/contacts.js?v=635169df-17:7:155885
mr/<@https://cloud.domain.tld/apps/contacts/js/contacts.js?v=635169df-17:177:29233
[155]/vr<.methods.newContact</<@https://cloud.domain.tld/apps/contacts/js/contacts.js?v=635169df-17:177:33791
Ut@https://cloud.domain.tld/apps/contacts/js/contacts.js?v=635169df-17:7:11231
n@https://cloud.domain.tld/apps/contacts/js/contacts.js?v=635169df-17:7:12948
Ut@https://cloud.domain.tld/apps/contacts/js/contacts.js?v=635169df-17:7:11231
[0]/</</t.prototype.$emit@https://cloud.domain.tld/apps/contacts/js/contacts.js?v=635169df-17:7:33898
click@https://cloud.domain.tld/apps/contacts/js/contacts.js?v=635169df-17:469:487
Ut@https://cloud.domain.tld/apps/contacts/js/contacts.js?v=635169df-17:7:11231
n@https://cloud.domain.tld/apps/contacts/js/contacts.js?v=635169df-17:7:12948
xr/o._wrapper@https://cloud.domain.tld/apps/contacts/js/contacts.js?v=635169df-17:7:44114
"
__proto__: Object { stack: "", … }
```

**Comment by gnouts** [comment]
Issue was confirmed by multiple users using Yunohost as packager. I don't have resources to setup a plain nextcloud install. If anyone can confirm this to exclude (or not) the Yunohost factor :)

**Comment by edgarm1964** [comment]
I have a plain nextcloud 15.0.5 installation and have this issue with the contacts app too.

**Comment by skjnldsv** [comment]
Can you try this release please? :)
[contacts.tar.gz](https://github.com/nextcloud/contacts/files/2965540/contacts.tar.gz)

**Comment by edgarm1964** [comment]
Alas, doesn't make a difference:

ReferenceError: Can't find variable: oca_contacts
(anonymous function) — Contacts.vue:339
_ — dist.js:1:14295
(anonymous function) — dist.js:1:14097
hr — Contacts.vue:86
a — Contacts.vue:121
(anonymous function) — Contacts.vue:121
initializePromise
Promise
(anonymous function) — Contacts.vue:127
[native code]
Ut — vue.runtime.esm.js:1854
Ut — vue.runtime.esm.js:1854
$emit — vue.runtime.esm.js:3863

**Comment by edgarm1964** [comment]
Nothing is shown and in the console log I see this:
ReferenceError: Can't find variable: oca_contacts
(anonymous function) main.js:61

**Comment by skjnldsv** [comment]
Please, try again with this one: [contacts.tar.gz](https://github.com/nextcloud/contacts/files/2968307/contacts.tar.gz)

And make sure you cleared your cache before :)

**Comment by edgarm1964** [comment]
I've emptied my caches and it made no difference. Same message.

**Comment by skjnldsv** [comment]
@edgarm1964 please do then :)
Can you send me a message at skjnldsv@protonmail.com?

**Comment by edgarm1964** [comment]
I've sent you an email.

**Comment by skjnldsv** [comment]
@edgarm1964, thanks!
Everything is working on your instance so far and I'm able to create contacts. :woman_shrugging:

**Comment by edgarm1964** [comment]
You're welcome.

Using firefox , contacts works. But using Safari (v11.1.2 and v12.0.1) it doesn't. I still get the same error message.

**Comment by skjnldsv** [comment]
@edgarm1964 Okay, I'll try it with safari next week then! :)
Don't delete the test account!

**Comment by edgarm1964** [comment]
:-D

**Comment by jpu4** [comment]
same issue on vivaldi 2.3.1440.61 x64

**Comment by Flole998** [comment]
Same issue here on Vivaldi 2.3.1440.61 x64

**Comment by cooling75** [comment]
Hi, same issue hier on Safari Version 12.0.3 (14606.4.5)
Working with Chrome Version 73.0.3683.86
on macOS Mojave 10.14.3

**Comment by skjnldsv** [comment]
@gnouts @edgarm1964 @jpu4  @Flole998 @cooling75 please check and test this contacts release and see if it works: 
[contacts.tar.gz](https://github.com/nextcloud/contacts/files/2997376/contacts.tar.gz)

**Comment by edgarm1964** [comment]
Yes! Works. Good job!
